### ISSUE TITLE
Please make it easier to change source language

### ISSUE THREAD

**Issue by dwl-sdca** [windingwind/zotero-pdf-translate#1]
If I am using this plugin correctly it seems that I must go to Zotero preferences and manually change the 2-letter code for the source language. It would be really nice to be able to make this change from within the plugin. Thank you for a wonderful plugin.

**Comment by windingwind** [comment]
Thanks! I'll @ you once it's ready.

**Comment by windingwind** [comment]
@dwl-sdca Solved.
