### ISSUE TITLE
add the ability to search for bilingual example sentences using copied vocabulary from certain websites

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [windingwind/zotero-pdf-translate#10]
It is proposed to add the ability to search for bilingual example sentences using copied vocabulary from certain websites,such as "https://www.citexs.com/AIHelp".

**Comment by windingwind** [comment]
From my point of view, that's far more than what Zotero, as well as this addon, is designed for. It's just a translate addon. ^v^ 

I'll make this issue open for weeks and see if there are other users need this function. If so, I'll consider adding it.

**Comment by windingwind** [comment]
I'll close this issue, as this need is not that urgent.
Feel free to open it again.
