### ISSUE TITLE
建议：增加有道智云翻译引擎

### ISSUE THREAD

**Issue by Fang-Ke** [windingwind/zotero-pdf-translate#100]
当前使用的免费的有道翻译引擎，翻译结果和有道翻译客户端/网页端不一致，翻译准确性不如网页端。经测试，有道智云提供的API（需密钥）翻译结果与网页端/客户端一致，翻译质量更好。所以，建议作者增加有道智云翻译引擎接口。

**Comment by ttkx123** [comment]
请问你们知道为什么我才申请的百度翻译的密钥，才用了一天就显示受限，密钥无效

**Comment by middle-chunjie** [comment]
顶一下，确实有道智云的翻译质量比免费的接口要好很多

**Comment by windingwind** [comment]
@middle-chunjie @Fang-Ke 最新版已支持。
