### ISSUE TITLE
[Feature] GPT翻译貌似只支持OpenAI的API，能否支持chatanywhere

### ISSUE THREAD

**Issue by bobjason2020** [windingwind/zotero-pdf-translate#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7
- Plugin Version: 1

### Describe the feature request

是否支持chatanywhere的api，如果可以，如何设置（我在chatGPT接口改变网址翻译无反应）；如果不可以，希望更新并支持

### Describe the solution you'd like

希望支持chatanywhere的API

**Comment by bigben446** [comment]
这个如果实现，确实很方便哈

**Comment by bigben446** [comment]
刚刚发现，可以在chatgpt下配置，把官方网址替换成chatanywhere地址就行，https://api.chatanywhere.tech/v1/chat/completions

**Comment by bigben446** [comment]
这边有说明：
https://gist.github.com/GrayXu/f1b72353b4b0493d51d47f0f7498b67b
使用第三方OpenAI兼容接口时，填写规范与上述对齐即可。
