### ISSUE TITLE
[Feature] locator phrase

### ISSUE THREAD

**Issue by luckyandfine** [windingwind/zotero-pdf-translate#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.9 (64-bit)
- Plugin Version:2.0.5

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
When encountering controversial words and phrases in translation, one has to go back to the original text for a long time.

**Why do you need this feature?**
Inability to quickly locate the original text when encountering controversial words or phrases.

### Describe the solution you'd like

**The solution you'd like**
When the user clicks on a word in the translation window, the original word is highlighted in the original text.

**Alternatives you've considered**

**Comment by windingwind** [comment]
unfortunately that's not possible
