### ISSUE TITLE
[Bug] 小牛高校版请求超时

### ISSUE THREAD

**Issue by SomeZeroK** [windingwind/zotero-pdf-translate#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.9 (64-bit)
- Plugin Version:2.0.5

### Describe the bug

使用高校版的小牛翻译API时，出现请求超时问题：Error: Request timed out。
· 接口地址： https://trans.neu.edu.cn/niutrans/textTranslation?apikey=apikey的值(可在右上角个人中心查看)
· 请求方式： POST
· 传参方式： application/json

· 请求参数：
名称 类型 是否必选 实例值 描述 
from String 是 zh 源语语种缩写 
to String 是 en 目标语语种缩写 
src_text String 是 你好 原文内容 

· 返回结果：
{
"code": 200,
"msg": "成功",
"data": [
{
"sentences": [
{
"data": "Hello",
"contrastSourceText": "你好",
"paragraphOrder": 0,
"order": 0,
"uuid": ,
"historyResult": null,
"len": 0,
"sourceLanguageAbbreviation": "zh",
"targetLanguageAbbreviation": "en"
}
],
"order": 0
}
]
}

![1731830554325](https://github.com/user-attachments/assets/b2c5013a-b86f-4a99-833d-48ff3ca7cfa0)

### Debug Output

点击设置，填写对应密钥，修改api接口，不填写账户信息（高校版无此信息）

**Comment by zhimaerfan** [comment]
hello, NEUer.
I'm also from NEU, I've given them advice before to add support for college NiuTrans, does yours ever work properly?

**Comment by SomeZeroK** [comment]
> 你好，NEUer。我也是 NEU 的，我之前给过他们建议增加对大学 NiuTrans 的支持，你的能正常工作吗？

用压缩包软件打开本地插件（.xpi），修改zoteropdftranslate.js文件里的一、服务模块（src/modules/services/niutrans.ts）和二、设置模块（src/modules/settings/niutrans.ts），然后保存重新安装一下填入API和密钥就行。

```// src/modules/services/niutrans.ts
  var niutrans_exports = {};
  __export(niutrans_exports, {
    default: () => niutrans_default
  });
  var niutrans_default;
  var init_niutrans = __esm({
    "src/modules/services/niutrans.ts"() {
      "use strict";
      init_prefs();
      niutrans_default = async function(data2) {
        const apikey = data2.secret;
        // 高校版固定地址（可配置到设置）
        const endpoint = getPref("niutransEndpoint") || "https://trans.neu.edu.cn/niutrans";
        // 构造完整请求URL
        const requestURL = `${endpoint}/textTranslation?apikey=${apikey}`;
        const xhr = await Zotero.HTTP.request(
          "POST",
          requestURL,
          {
            headers: {
              "content-type": "application/json",
              accept: "application/json, text/plain, */*"
            },

            body: JSON.stringify({
              from: data2.langfrom.split("-")[0],
              to: data2.langto.split("-")[0],
              src_text: data2.raw
            }),
            responseType: "json"
          }
        );
        if (xhr?.status !== 200) {
          throw `Request error: ${xhr.status} ${xhr.statusText}`;
        }
        if (xhr.response.code !== 200) {
          throw `Service error2: [URL: ${requestURL}]: ${xhr.response.code}: ${xhr.response.msg}`;
        }
        // 修改结果处理部分
        data2.result = xhr.response.data
        // 遍历所有段落
        .map(paragraph => 
          // 遍历段落中的所有句子
          paragraph.sentences.map(sentence => 
            // 提取目标文本，保留对比信息
            sentence.data.trim()
          ).join(' ')
        ).join('\n');

        if (!data2.result) {
        throw "空翻译结果";
        }
      };
    }
  });
```
![Image](https://github.com/user-attachments/assets/34896b58-c8d1-482e-9a93-3c0b34ac9d93)
`// src/modules/settings/niutrans.ts
  init_locale();
  init_prefs();
  // 移除所有登录相关函数，仅保留配置项
async function niutransStatusCallback(status) {
  const dialogData = {
    endpoint: getPref("niutransEndpoint"),
    beforeUnloadCallback: () => {
      setPref("niutransEndpoint", dialog.dialogData.endpoint);
    }
  };

  // 简化设置对话框
  const dialog = new ztoolkit.Dialog(2, 2)
    .addCell(
      0,
      0,
      {
        tag: "label",
        properties: { innerHTML: "API端点" }
      },
      false
    )
    .addCell(0, 1, {
      tag: "input",
      attributes: {
        "data-bind": "endpoint",
        "data-prop": "value"
      }
    })
    .addButton("保存", "save")
    .addButton("关闭", "close")
    .setDialogData(dialogData);

  dialog.open("高校版NiuTrans配置");
}`

![Image](https://github.com/user-attachments/assets/07dc4b5a-4e6c-432a-852a-582827b25e2b)

**Comment by windingwind** [comment]
@SomeZeroK 请勿推荐一般用户自行修改插件。引起问题最终会变成项目维护者的负担，建议有能力提PR
