### ISSUE TITLE
[Feature] 关于多通道翻译设置的选择

### ISSUE THREAD

**Issue by lonely67373** [windingwind/zotero-pdf-translate#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: windows 11 23H2
- Zotero Version: 7.0.9
- Plugin Version:2.0.5

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
在我使用的时候，我希望给annotation的翻译引擎和选中翻译的翻译引擎能否设置成不一样的。同时在选中翻译时的弹窗里，可以快速选择多个通道进行翻译的选项。
**Why do you need this feature?**
A clear and concise description of why you need this feature.
因为我有一个tokens计费的chatgpt api ，所以我希望在annotation上使用这个大模型进行精细翻译，在正文的超长句翻译上使用googleapi这种免费的减少计费消耗，在有需要的时候才会选择大模型进行精细翻译。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
> 同时在选中翻译时的弹窗里，可以快速选择多个通道进行翻译的选项。

可使用独立窗口并添加多个服务
