### ISSUE TITLE
[Bug]翻译标题会改变其他文献标题，再次点击标题标题信息恢复；翻译的标题会出现其他符号

### ISSUE THREAD

**Issue by Liwt0** [windingwind/zotero-pdf-translate#101]
**Describe the bug**
翻译标题会改变其他文献标题，再次点击标题标题信息恢复；翻译的标题会出现其他符号
![image](https://user-images.githubusercontent.com/90240641/164238739-29706979-0e02-4807-b678-4b3b47f0c448.png)

**To Reproduce**
右键标题翻译

**Expected behavior**
不影响其他文献标题，不出现无关符号

**Screenshots**
![image](https://user-images.githubusercontent.com/90240641/164238855-1f24aab0-310a-48b5-a929-585fec2c8dda.png)
![image](https://user-images.githubusercontent.com/90240641/164238940-0fd89c47-996c-4336-a5f7-265f60accc65.png)

**Environment**
 - OS: Windows
 - Zotero Version：6.0.4
 - Addon Version：0.6.6

**Additional context**

**Comment by windingwind** [comment]
了解。尽快修复

**Comment by windingwind** [comment]
这里的其他符号是用于识别文献是否已经翻译过，翻译过的默认直接显示翻译结果。将会在下一版本去除显示，但短标题栏仍然会有这个符号，是正常现象。

**Comment by zyx335588** [comment]
我倒是希望这个标示符号能够放在标题的前面而不是后面，以便能再小屏幕上更直观的区分显示的是翻译的中文标题还是真实的中文标题，或者使用其他更好的区分方式。

此外，还发下一个小问题：直接在点击库（libary）文件夹（而不是collection文件夹内），此时点击条目时，似乎这个改变显示的选项并不起作用。

**Comment by windingwind** [comment]
> 我倒是希望这个标示符号能够放在标题的前面而不是后面，以便能再小屏幕上更直观的区分显示的是翻译的中文标题还是真实的中文标题，或者使用其他更好的区分方式。
> 
> 此外，还发下一个小问题：直接在点击库（libary）文件夹（而不是collection文件夹内），此时点击条目时，似乎这个改变显示的选项并不起作用。

是的，库文件夹里面因为会有太多条目，合并到一次请求基本会超长度限制，单独请求又会超API访问频率限制，容易被封。所以只做了collection和item范围的。后面有空再优化批量翻译的逻辑

**Comment by windingwind** [comment]
我无法复现你所说排列错乱的问题，是否可以稳定复现？

**Comment by windingwind** [comment]
@zyx335588 我无法复现你所说排列错乱的问题

**Comment by windingwind** [comment]
@Liwt0 我无法复现你所说排列错乱的问题

**Comment by windingwind** [comment]
@Liwt0 显示错乱可能是与其他涉及更新条目元数据的插件（如better bibtext）共同修改某些条目导致的UI问题，不会导致元数据丢失或覆盖。
将关闭该issue。
