### ISSUE TITLE
[Feature] Zotero 7.0.9 全文翻译：加载到笔记/新的附件 是否可以设置为用户可选项？

### ISSUE THREAD

**Issue by gravenesss** [windingwind/zotero-pdf-translate#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win11
- Zotero Version: 7.0.9
- Plugin Version: 2.0.5

### Describe the feature request

希望全文翻译可以提供用户可选项：加载到笔记/新的附件。

### Describe the solution you'd like

希望全文翻译可以提供用户可选项：加载到笔记/新的附件。

**Comment by windingwind** [comment]
与本插件无关
