### ISSUE TITLE
[Bug] 无法安装插件“Translate for Zotero”。它可能无法与该版本的 Zotero 兼容。

### ISSUE THREAD

**Issue by potemofsolarsystem** [windingwind/zotero-pdf-translate#1012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.9
- Plugin Version:

### Describe the bug

版本都是一致的，就是安装不了

### Debug Output

不行

**Comment by Bethexone** [comment]
+1+1

**Comment by TerrenceYi** [comment]
+1

**Comment by yousimu** [comment]
+1

**Comment by xiejunjie208** [comment]
+1,同样报错，前期版本没有问题。Zotero版本7.0.10-beta.2+dc47650eb (64-bit)。

**Comment by evolighting** [comment]
manifest.json 中 "strict_min_version": "7.0.10"

大概意味着需要 9.0.10以上的版本吧

**Comment by xiejunjie208** [comment]
怎么修改呢？

**Comment by Ophryon** [comment]
xpi重命名为rar文件，解压后就有manifest.json文件，修改后再改回来就行

**Comment by xiejunjie208** [comment]
新版本什么时候兼容呢

**Comment by windingwind** [comment]
等待zotero更新，目前安装旧版本即可

**Comment by markable** [comment]
旧版本指的是zotero的旧版本还是translate旧版本
