### ISSUE TITLE
[Bug] Latest Release cannot be installed 

### ISSUE THREAD

**Issue by codycjy** [windingwind/zotero-pdf-translate#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOs 15.1
- Zotero Version: 7.0.9
- Plugin Version: 2.0.6

### Describe the bug

When installing the 2.0.6 plugins, it shows `The add-on "Translate for Zotero" could not be installed. It may be incompatible with this version of Zotero.` 
I've tested drag url and download the plugins for times. I think files are not corrupted
After fallback to 2.0.5 everything works fine.

### Debug Output

1732148116967	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148116967	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148116967	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148116968	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

1732148256160	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148256160	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148256160	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148256161	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

[JavaScript Error: "uncaught exception: undefined"]

1732148309285	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148309285	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148309286	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148309286	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

[JavaScript Error: "uncaught exception: undefined"]

1732148365059	addons.xpi	WARN	Attempted to remove zoteropdftranslate@euclpts.com from app-profile but it was already gone

1732148483107	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148483107	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148483107	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148483107	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148573223	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148573223	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148573224	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

1732148573224	addons.xpi-utils	WARN	Add-on zoteropdftranslate@euclpts.com is not compatible with application version.

appName => Zotero, version => 7.0.9 (ARM64), os => macOS 15.1, locale => en-US, extensions => 

(3)(+0698758): Dragging over item -1 with 1, drop row: -1

(3)(+0000002): Dragging over item -1 with 1, drop row: -1

(3)(+0000004): Dragging over item -1 with 0, drop row: -1

(3)(+0000001): Dragging over item -1 with 0, drop row: -1

(3)(+0000008): Dragging over item -1 with 0, drop row: -1

(3)(+0000004): Dragging over item -1 with 0, drop row: -1

(3)(+0000584): Alert: The add-on "Translate for Zotero" could not be installed. It may be incompatible with this version of Zotero.

(3)(+0009825): Running /usr/bin/sw_vers '-productVersion'

**Comment by zhimaerfan** [comment]
+1
zotero 7.0.10-beta.2+dc47650eb
Macbook Air m2 OS 15.2 Beta (24C5057p)

**Comment by Simoody** [comment]
I can't install it either

**Comment by MiguelDLM** [comment]
Same error here using Windows and Zotero 7.0.9 64 bits and release 2.0.6. 

Version 2.0.5 works fine

**Comment by jbjorgan** [comment]
Same error her using Mac OS Sequoia 15.1.1, Zotero 7.0.9.

**Comment by Aliy-lis** [comment]
Same error here, using MWindows11, Zotero 7.0.9.

**Comment by windingwind** [comment]
Install the older version for now. The latest is for Zotero 7.0.10, but it’s not yet available.
