### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Tanlei2019** [windingwind/zotero-pdf-translate#1015]

**Comment by Tanlei2019** [comment]
All done

**Comment by lyxxk** [comment]
这个是怎么解决的呀，我在页面正常勾选翻译之后，侧边栏的条目是空白的
![8d8806f9-071e-4378-b06a-6389f789b493](https://github.com/user-attachments/assets/cecada6c-733e-4d4b-89b8-37023d3591e8)
