### ISSUE TITLE
[Feature] 可否增加智谱AI（GLM）的支持，因为智谱AI有免费模型可以调用

### ISSUE THREAD

**Issue by longyongchao** [windingwind/zotero-pdf-translate#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
使用OpenAI格式接口即可

**Comment by NormanMises** [comment]
智谱的4.5模型要加thinking参数，

<img width="767" height="108" alt="Image" src="https://github.com/user-attachments/assets/d8e1a69e-56b3-4f64-bbec-76e3b166eacd" />

<img width="525" height="196" alt="Image" src="https://github.com/user-attachments/assets/16df2227-f04c-48cc-be3e-94370ad774a0" />

这么写不管用

**Comment by Chapoly1305** [comment]
帮忙开个新的Ticket, 给多点信息，比如API接口文档，晚点我看看。

**Comment by LiNY2-01** [comment]
> 智谱的4.5模型要加thinking参数，
> <img alt="Image" width="767" height="108" src="https://private-user-images.githubusercontent.com/38835726/474044058-d8e1a69e-56b3-4f64-bbec-76e3b166eacd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzMjMyMTAsIm5iZiI6MTc1NDMyMjkxMCwicGF0aCI6Ii8zODgzNTcyNi80NzQwNDQwNTgtZDhlMWE2OWUtNTZiMy00ZjY0LWJiZWMtNzZlM2IxNjZlYWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA0VDE1NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNjdjMGFjNTNmYTgwYjA4MGZlN2JmZmU0ZDczZjBlY2M0YzVkYmRjNmQ0M2YxNjk2ZGNlN2U3NTUyZWExOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NVtvLTgkLJsn4Ud9nqxYkQNKhM7rQX-X4PwXiwDI-u8"> <img alt="Image" width="525" height="196" src="https://private-user-images.githubusercontent.com/38835726/474044224-16df2227-f04c-48cc-be3e-94370ad774a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzMjMyMTAsIm5iZiI6MTc1NDMyMjkxMCwicGF0aCI6Ii8zODgzNTcyNi80NzQwNDQyMjQtMTZkZjIyMjctZjA0Yy00OGNjLWJlM2UtOTQzNzBhZDc3NGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA0VDE1NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZGMxNzdhMTQ4MDQ2M2M1OTgxOTc1Mjk0YzQ4MDYxMGE5MzBmMDVkMWM4NjY4ZTE0ZDJiZTQxMTkxODdlMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8n3k_ZEQ3OnE3qrtKldRs6HpAc-JdUZNacL31LRgb0M">
> 
> 这么写不管用

<img width="1088" height="867" alt="Image" src="https://github.com/user-attachments/assets/388dbf3c-461e-4c63-822d-9bd10c65aba5" />


thinking
{"type":"disabled"}

**Comment by NormanMises** [comment]
> > 智谱的4.5模型要加thinking参数，
> > <img alt="Image" width="767" height="108" src="https://private-user-images.githubusercontent.com/38835726/474044058-d8e1a69e-56b3-4f64-bbec-76e3b166eacd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzMjMyMTAsIm5iZiI6MTc1NDMyMjkxMCwicGF0aCI6Ii8zODgzNTcyNi80NzQwNDQwNTgtZDhlMWE2OWUtNTZiMy00ZjY0LWJiZWMtNzZlM2IxNjZlYWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA0VDE1NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNjdjMGFjNTNmYTgwYjA4MGZlN2JmZmU0ZDczZjBlY2M0YzVkYmRjNmQ0M2YxNjk2ZGNlN2U3NTUyZWExOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NVtvLTgkLJsn4Ud9nqxYkQNKhM7rQX-X4PwXiwDI-u8"> <img alt="Image" width="525" height="196" src="https://private-user-images.githubusercontent.com/38835726/474044224-16df2227-f04c-48cc-be3e-94370ad774a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzMjMyMTAsIm5iZiI6MTc1NDMyMjkxMCwicGF0aCI6Ii8zODgzNTcyNi80NzQwNDQyMjQtMTZkZjIyMjctZjA0Yy00OGNjLWJlM2UtOTQzNzBhZDc3NGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA0VDE1NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZGMxNzdhMTQ4MDQ2M2M1OTgxOTc1Mjk0YzQ4MDYxMGE5MzBmMDVkMWM4NjY4ZTE0ZDJiZTQxMTkxODdlMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8n3k_ZEQ3OnE3qrtKldRs6HpAc-JdUZNacL31LRgb0M">
> > 这么写不管用
> 
> <img alt="Image" width="1088" height="867" src="https://private-user-images.githubusercontent.com/73920059/474119383-388dbf3c-461e-4c63-822d-9bd10c65aba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzNTcyNTIsIm5iZiI6MTc1NDM1Njk1MiwicGF0aCI6Ii83MzkyMDA1OS80NzQxMTkzODMtMzg4ZGJmM2MtNDYxZS00YzYzLTgyMmQtOWJkMTBjNjVhYmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA1VDAxMjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMmIyNDRiYjlhMDI1MGViNDYyODdkMjI0MGM5Y2JmOWUwNjQxZDU0NWRjZDlhNDc3ZGYzNDNhYWI3NDVkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kg9BufL78QDNnpTvuwjh0MoafMkED-m_Gobb9MokxBY">
> thinking {"type":"disabled"}

原来如此，感谢！it works！
