### ISSUE TITLE
建议增加RSS订阅杂志里的标题及摘要翻译功能

### ISSUE THREAD

**Issue by xcpeter** [windingwind/zotero-pdf-translate#102]
zotero的RSS订阅功能十分好用，如果能增加订阅区的标题摘要翻译功能就好了，提个小建议~期待后面能加入这个功能

**Comment by windingwind** [comment]
试过，RSS条目是可修改的，但RSS集合是不可修改的，不确定是否会有副作用。同时可能由于特殊的显示机制，无法直接更新到标题栏上，只能翻译到短标题栏。
之后再试一下。

**Comment by windingwind** [comment]
@xcpeter 你认为摘要翻译放在哪里合适？

**Comment by windingwind** [comment]
v0.7.3已支持RSS翻译

**Comment by daruoxiaoyu** [comment]
顶一手自动翻译摘要，可以在原来摘要下面自动添加翻译的摘要或者另一个栏目。

**Comment by windingwind** [comment]
已支持翻译摘要

**Comment by paoniu-liu** [comment]
> 

ZOTERO7 RSS不能翻译标题

**Comment by paoniu-liu** [comment]
> > 
> 
> ZOTERO7 RSS不能翻译标题

可以了，要先把字段设置为US，才能翻译
