### ISSUE TITLE
[Bug] ] 刚才发现翻译插件消失了，侧边栏不显示了，现在的translate版本是2.0.8

### ISSUE THREAD

**Issue by MrGongqi** [windingwind/zotero-pdf-translate#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 7.0.9
- Plugin Version:2.0.8

### Describe the bug

你好，刚才正想使用以下翻译插件，但是点开文献后，发现右侧边栏的翻译插件显示消失了，翻译插件也没有反应（如图1），不知道是什么原因，我的插件是自动更新。我尝试退回到2.0.7，发现还是相同的问题，又尝试回到2.0.6，发现2.0.6已经无法安装了（如图2）。
图1：
![image](https://github.com/user-attachments/assets/659f03c2-2d1a-45ff-9206-71e79eb1d394)
-------

图2：
![image](https://github.com/user-attachments/assets/b955732f-e997-47fa-98aa-024f89ae998e)
------

### Debug Output

![image](https://github.com/user-attachments/assets/f7787aad-99da-4b81-9cca-eb0679c0be0c)

### Debeg Report

1732369518977	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1732369519037	addons.webextension.tara@linxzh.com	WARN	Loading extension 'tara@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "TypeError: Zotero.ItemTreeManager.registerColumn is not a function" {file: "jar:file:///C:/Users/GONGQ/AppData/Roaming/Zotero/Zotero/Profiles/4jbekzqp.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 15319}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

appName => Zotero, version => 7.0.9 (x64), os => Windows 10.0 19045, locale => en-US, extensions => Zotero Citation Counts Manager (2.0, extension), Tara (1.0.0-9, extension), Google Scholar Citation Count (4.1.1, extension), Easier Citation (0.4.8, extension), Ethereal Reference (1.3.2, extension), Better Notes for Zotero (2.1.6, extension), Jasminum (1.0.0-20, extension), Awesome GPT (1.5.3, extension), Ethereal Style (5.3.1, extension), Translate for Zotero (2.0.8, extension)

**Comment by Sun-Cold** [comment]
Same issue

**Comment by chen-huaneng** [comment]
The same issue, and the selected text will not disappear when I select another text.
![](https://github.com/user-attachments/assets/0b1627b8-7ec7-4b32-8419-a32a3262b3e1)

**Comment by XuanHe1225** [comment]
roll back to 2.0.4

**Comment by Jjagie** [comment]
> e
Reinstalling this new version doesn't fix it either
