### ISSUE TITLE
[Feature] 希望不要在条目上ctrl+t自动翻译标题并且把标题改成中文！

### ISSUE THREAD

**Issue by Yuki-LQ** [windingwind/zotero-pdf-translate#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win 11 24h2
- Zotero Version: 7.0.9
- Plugin Version:2.0.8

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/01fa3575-bc7b-44ad-bead-b5a4cd3e7ca0)
![image](https://github.com/user-attachments/assets/2c834752-2d66-4e1a-ad98-7b7a3909f11d)
使用ctrl t后自动翻译条目标题，并且在设置中为勾选希望展示标题翻译结果，但还是展示了翻译后标题
**Why do you need this feature?**
A clear and concise description of why you need this feature.
和其他软件功能冲突

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

希望可以自定义ctrl+t快捷键按钮，以免和其他软件冲突

**Comment by windingwind** [comment]
覆盖标题非本插件功能
