### ISSUE TITLE
[Feature] 希望可以在侧边栏信息条目中重新恢复添加标题翻译和摘要翻译，方便浏览

### ISSUE THREAD

**Issue by lhhhhhh-12345** [windingwind/zotero-pdf-translate#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win10
- Zotero Version: 7.0.9(64bit)
- Plugin Version:2.011

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
Title and summary translations always appear in ‘’Other‘’ after translation, would like to restore a separate column for title translations and summary translations under the ''title'' column like in Zotero6
标题和摘要翻译总是出现在翻译后的 “其他 ”栏中，希望能像 Zotero6 一样在 “标题 ”栏下为标题翻译和摘要翻译恢复单独的一栏

**Why do you need this feature?**
increase article visibility
方便增加可见性
![屏幕截图 2024-11-26 021658](https://github.com/user-attachments/assets/97f24afc-c70d-4a56-8bb7-c3f31f5e7733)

### Describe the solution you'd like

**The solution you'd like**
hope to restore or add a separate column for title translations and summary translations under the ''title'' column like in Zotero6
希望能像 Zotero6 一样在 “标题 ”栏下为标题翻译和摘要翻译恢复或增加单独的一栏

### Anything else?

hope to add the function to adjust the font size and line spacing of the translation window for the floating window and the sidebar translation window separately.
希望增加可以分别调整翻译浮窗和侧边栏翻译窗口字号和行距的功能

**Comment by windingwind** [comment]
> 希望能像 Zotero6 一样在 “标题 ”栏下为标题翻译和摘要翻译恢复或增加单独的一栏

更新zotero
