### ISSUE TITLE
[Feature] 需要api支持：阿里云百炼大模型平台

### ISSUE THREAD

**Issue by xianrenzhou** [windingwind/zotero-pdf-translate#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
https://bailian.console.aliyun.com/

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
使用OpenAI服务填写对应第三方接口与密钥即可
