### ISSUE TITLE
[Bug] Title Translation字段在切换条目后没有更新

### ISSUE THREAD

**Issue by zzlb0224** [windingwind/zotero-pdf-translate#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11
- Zotero Version: 7.0.10 
- Plugin Version: 2.0.12

### Describe the bug

Title Translation字段在切换条目后没有更新

### Debug Output

![image](https://github.com/user-attachments/assets/15f5c637-a34c-4a3e-b717-1d9e3cdf459a)

**Comment by gwh854649081** [comment]
我也遇到了同样的问题，我的是mac zotero7 插件版本是2.0.12

**Comment by chrsi13** [comment]
我也是，我是win zotero7.0.11 x64
