### ISSUE TITLE
[Bug]腾讯云翻译 SignatureFailure 签名计算错误

### ISSUE THREAD

**Issue by BerginJay** [windingwind/zotero-pdf-translate#103]
**Describe the bug**
使用腾讯云翻译某些句子返回
```
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Tencent*, not Zotero or the PDF Translate addon.
        AuthFailure.SignatureFailure:请求签名验证失败，请检查您的签名计算是否正确。
```

**To Reproduce**
经过反复测试，目前观察到是在含有数字`0`句子处会报错。据两个例子：

1. 原句：`values 0.1--0.7`。分别选中``0.1--0.7``和``values``，翻译没有问题，翻译``values 0.1--0.7``出现SignatureFailure，更具体点，翻译 `s 0`会报错，单独翻译 `0`不报错。
2. 原句：`25 and 0 dB`。分别选中`25 and`和 `0 dB` 不报错，翻译`d 0`报错。

总结一下，单独`0`和以`0`开头的句子没有问题，句子中含有`0`，且`0`前后有空格或小数点（即`10`这种不会报错）时会报错。

**Expected behavior**
应该是构造请求时签名计算有bug。

精力有限暂时不能自己PR，只能尽量多提供一些信息开个issue，麻烦了。

**Environment**
 - OS: macOS
 - Zotero Version 6.0.4
 - Addon Version 0.4.8

**Comment by BerginJay** [comment]
插件更新到0.6.7后仍然存在此问题

**Comment by windingwind** [comment]
谢谢。将在下一版本更新时修复。

**Comment by windingwind** [comment]
Fixed in v0.6.8
