### ISSUE TITLE
[Bug] 腾讯翻译出错

### ISSUE THREAD

**Issue by MingfuYAN** [windingwind/zotero-pdf-translate#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macos15.1
- Zotero Version: 7.0.10
- Plugin Version: 2.0.12

### Describe the bug

Service error: InvalidParameterValue:不支持的语种：ro_to_zh

### Debug Output

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Error: Handler not found for 'addons' URLs" {file: "chrome://zotero/content/xpcom/zotero.js" line: 1094}]

appName => Zotero, version => 7.0.10 (ARM64), os => macOS 15.1, locale => zh-CN, extensions => Translate for Zotero (2.0.12, extension)

(3)(+0060824): Getting contents of /Users/mfyan/Library/Application Support/Zotero/Profiles/rcyibiuy.default/treePrefs.json

(3)(+0000001): Writing column prefs of length 2392 to file /Users/mfyan/Library/Application Support/Zotero/Profiles/rcyibiuy.default/treePrefs.json

(3)(+0008790): Running /usr/bin/sw_vers '-productVersion'

(3)(+0003451): [Translate for Zotero] runTranslationTask {}

(3)(+0000001): [Translate for Zotero] try itemLanguage

(3)(+0000002): [Translate for Zotero] try inferredLanguage ro

(3)(+0000000): [Translate for Zotero] use autoDetect ro

(3)(+0000002): [Translate for Zotero] try auto detect language

(3)(+0000000): [Translate for Zotero] try itemLanguage

(3)(+0000002): [Translate for Zotero] try inferredLanguage ro

(3)(+0000000): [Translate for Zotero] use autoDetect ro

(3)(+0000000): [Translate for Zotero] {"id":"HAOT1tFi-1733124072213","type":"text","raw":"e transformation from the view of image generation by Stable Diffusion Model.","result":"","audio":[],"service":"tencent","candidateServices":[],"itemId":143,"status":"processing","extraTasks":[],"langfrom":"ro","langto":"zh-CN","callerID":"zoteropdftranslate@euclpts.com","secret":"{为了安全已删除}"}

(3)(+0000005): HTTP POST "Action=TextTranslate&Language=zh-CN&Nonce=9744&ProjectId=0&Region=ap-shanghai&SecretId={为了安全已删除}&Source=ro&SourceText=e+transformation+from+the+view+of+image+generation+by+Stable+Diffusion+Model.&Target=zh&Timestamp=1733124072&Version=2018-03-21&Signature=uaQCViNmYSXFINSpO3%2F9AdcjWL8%3D" to https://tmt.tencentcloudapi.com

(3)(+0000125): HTTP POST https://tmt.tencentcloudapi.com succeeded with 200

(3)(+0000021): [Translate for Zotero] try itemLanguage

(3)(+0000001): [Translate for Zotero] try inferredLanguage ro

(3)(+0000000): [Translate for Zotero] use autoDetect ro

(3)(+0005701): Running /usr/bin/sw_vers '-productVersion'

**Comment by windingwind** [comment]
你所选择的源语言为Romanian，腾讯翻译不支持。
