### ISSUE TITLE
[Bug] 标题翻译始终为空

### ISSUE THREAD

**Issue by cesaryuan** [windingwind/zotero-pdf-translate#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.10
- Plugin Version: 2.0.12

### Describe the bug

点击标题翻译，标题已经成功翻译并存储到【其他】的 titleTranslation 中，但是信息栏始终为空

![image](https://github.com/user-attachments/assets/c2961c22-9afe-436a-ad91-433cdadabe65)

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/17975362/Debug.Output.txt)

**Comment by windingwind** [comment]
update zotero
