### ISSUE TITLE
[Bug] 科大讯飞的翻译接口无法翻译

### ISSUE THREAD

**Issue by Guo-CS** [windingwind/zotero-pdf-translate#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows11 24H2
- Zotero Version: 7.0.11
- Plugin Version:2.0.13

### Describe the bug

使用科大讯飞[Spark4.0 Ultra]，正确输入APPID#APISecret#APIKey之后仍无法翻译。
![2024-12-11 20-20-38](https://github.com/user-attachments/assets/59994d15-ecec-45f7-95e1-00cd0948b49f)

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/18095538/Debug.Output.txt)

### Anything else?

Spark4.0 Ultra接口地址ws(s)://spark-api.xf-yun.com/v4.0/chat

**Comment by windingwind** [comment]
不支持的翻译接口。请尝试使用OpenAI服务并以兼容格式填写接口

**Comment by Guo-CS** [comment]
服务选择ChatGPT，密钥选择"http服务接口认证信息"里的APIPassword。配置信息接口填https://spark-api-open.xf-yun.com/v1/chat/completions模型选择自己对应的模型，如下图。科大讯飞的星火翻译接口就可以使用了。
![2024-12-16 17-22-26](https://github.com/user-attachments/assets/c486c2ac-36c6-4df1-ba66-494262b9c726)
