### ISSUE TITLE
批注自动翻译功能，所作批注不替换右侧栏的原文区域并执行翻译

### ISSUE THREAD

**Issue by xjtusjtu** [windingwind/zotero-pdf-translate#106]
作者大大您好，“自动翻译批注”功能
- 新版本似乎会把自动翻译的批注显示在右侧栏的原文区和翻译区
- 之前的版本似乎是自动翻译，但不会把批注的原文和翻译显示在右侧翻译栏

我个人可能希望它保持之前版本的这种模式，因为既然批注的翻译已经被写入其comments了，我个人觉得没有太大的必要在右侧栏显示出来，我想看翻译的话直接点击comments看就ok了

主要原因是我个人的使用场景：

我正在浏览一整段的文本的翻译，但其中只有那么一句我希望作为批注保存，我划选它作为批注之后，自动翻译批注功能被调用，然后我右侧栏一大段就被替换成了刚刚划选的批注，但是我之前那一大段还没看完，然后我又需要去选择这一大段，点击“Translate”……结果就是多次重复请求同一大段，也有点浪费翻译字数的

原来划选的一大段文字👇
![image](https://user-images.githubusercontent.com/57665402/164885462-6a1aa54c-7049-4b6b-a551-7806d6060680.png)

对部分语句作批注之后，右侧栏原来**整个段落的翻译**被替换为**批注语句**👇
![image](https://user-images.githubusercontent.com/57665402/164885664-89eda711-12b0-4c3d-a27f-d1c5280023d0.png)

---

除了想恢复之前版本这种批注自动翻译不替换右侧栏之外，希望作者大大可以考虑一下做一个总开关（同时有快捷键最好啦！），不是首选项中勾选，而是直接右侧栏打开/关闭按钮

关闭状态下，任何动作都不会触发翻译（自动翻译批注、自动翻译等功能也不会被执行），Xtranslator，CopyTranslator等翻译软件的UI界面都有类似的开关功能

恳请作者大大考虑一下~

**Comment by windingwind** [comment]
谢谢建议。将会给这个翻译批注功能增加开关。这个功能的初衷是供翻译以后可以在右侧进行修改，并更新到高亮批注。
近期在做其他功能，可能要一段时间更新上来。

**Comment by xjtusjtu** [comment]
好的，非常感谢您的幸苦付出！

**Comment by windingwind** [comment]
v0.7.1在设置中增加了是否更新显示与编辑上一条批注的开关，关闭后批注及翻译不会更新到翻译窗口，与先前版本的行为一致。

**Comment by xjtusjtu** [comment]
太棒了！再次感谢作者！！！

**Comment by xjtusjtu** [comment]
@windingwind 作者大大好，新版本插件似乎删除了该按钮，然后所作批注替换右侧栏的原文区域的现象又出现了。作者大大可不可以考虑加回来？😢
