### ISSUE TITLE
[Feature]增加Standalone Window的钉住功能

### ISSUE THREAD

**Issue by wohaocaiji** [windingwind/zotero-pdf-translate#107]
希望在打开Standalone Window后进行翻译阅读时，能有一个pin的选项，现在的版本在对文献划线时Standalone Window会被遮挡，钉住以后更方便，类似于沙拉查词的那个
![image](https://user-images.githubusercontent.com/35571432/164892602-163c5068-91f1-4c97-b180-40a9273bf43f.png)

**Comment by windingwind** [comment]
v0.7.1增加了翻译窗口保持最前的开关，图标为📌。
由于框架限制，无法真正做到最前，因此可能导致其他窗口的右键菜单等异常。不影响pdf阅读与划词翻译。
@wohaocaiji

**Comment by wohaocaiji** [comment]
辛苦您了，十分感谢！
