### ISSUE TITLE
[Feature] Dictionary mode for single word translation

### ISSUE THREAD

**Issue by breakertt** [windingwind/zotero-pdf-translate#108]
Would it be possible to show the detailed definitions of a word when only a word is selected instead of a sentence? In another word, this add-on acts like a dictionary rather than a translator when the selected area is only a single word.

**Comment by windingwind** [comment]
Which dictionary service provider would you prefer?

**Comment by breakertt** [comment]
I would say Youdao seems good enough?

**Comment by windingwind** [comment]
Thanks.
What would you say about placing the 'Dictionary' function? Parallel to the 'Translation' function and share the same UI elements, or have its own UI elements? 

1. When will it work, like if the selection has only 1 or 2 words the dictionary will replace the translation, or should it just work all the time?
2. How to show the results in popup, sidebar, and the standalone window?

**Comment by breakertt** [comment]
> Thanks. What would you say about placing the 'Dictionary' function? Parallel to the 'Translation' function and share the same UI elements, or have its own UI elements?
> 
> 1. When will it work, like if the selection has only 1 or 2 words the dictionary will replace the translation, or should it just work all the time?
> 2. How to show the results in popup, sidebar, and the standalone window?

I think it is absolutely fine to share the same UI (textbox) as the ‘Translation' function does.

My idea is when the selected text area a single word (maybe include some spaces or characters), the textbox returns the definition of that world.

![image](https://user-images.githubusercontent.com/17745432/164910042-79a43dda-ecb7-4c28-8038-9c9c061182b5.png)

For example, the “安全” in the above screenshot is replaced with the whole definition of "Security" in Chinese. I think we just make it simple and easy?

**Comment by windingwind** [comment]
Thanks! I'll try to make it possible.
If you have interest, welcome any PR!

**Comment by breakertt** [comment]
> Thanks! I'll try to make it possible. If you have interest, welcome any PR!

I implemented one with Eng-Chn word definition support. The implementation is a bit dirty, hope you can help me refactor it if you think it is necessary.

**Comment by breakertt** [comment]
#109

**Comment by breakertt** [comment]
Btw, I still don't know how to dynamically debug the Zotero add-on, would you mind explaining more clearly in the Readme?

**Comment by windingwind** [comment]
> Btw, I still don't know how to dynamically debug the Zotero add-on, would you mind explaining more clearly in the Readme?

Updated to README already. Thanks!
