### ISSUE TITLE
可以添加腾讯翻译和cnki学术翻译吗？这两个很不错

### ISSUE THREAD

**Issue by frja1234** [windingwind/zotero-pdf-translate#11]

**Comment by windingwind** [comment]
Thanks, I'll try to add them in the following updates.

**Comment by windingwind** [comment]
v0.3.8 support Tencent translate.
I can't find a free API of CNKI, thus it will not be supported.

**Comment by WaHulu** [comment]
https://fanyi.cnki.net/serviceIntroduce/index.html
This is some information related to CNKI api.
