### ISSUE TITLE
[Bug]设置英翻中，但读中文文献时，也会进行翻译

### ISSUE THREAD

**Issue by hysmoment** [windingwind/zotero-pdf-translate#112]
**Describe the bug**
设置英翻中，并自动记录翻译文本；读英文文献时效果不错，但读中文文献时，也会进行翻译，并将内容插入作为comment

**To Reproduce**
1. Go to 'Zotero preference->translate->Automatic annotation translation'
2. 阅读中文文献，进行文字高亮
3. 高亮文字被翻译，并作为comment附在其后

**Expected behavior**
希望当我设置英翻中的时候，只对英文文本有效，对中文文本无效

**Screenshots**
![image](https://user-images.githubusercontent.com/63805833/165406915-9f922e2b-b630-4326-94ba-6cc08711ca29.png)
设置如上图
![image](https://user-images.githubusercontent.com/63805833/165406857-4476ec3d-ac42-4df5-be67-9249c1e69858.png)
结果如上图

**Environment**
 - OS: Windows
 - Zotero Version(6.0.5)
 - Addon Version(0.7.4)

**Comment by windingwind** [comment]
see #46
