### ISSUE TITLE
[Bug]标题翻译bug

### ISSUE THREAD

**Issue by fan291752035** [windingwind/zotero-pdf-translate#113]
我发现在翻译标题的时候，翻译的中文会出现在不是该文献的条目上，虽然短标题可以看到，但是翻译过的标题会再一次出现在下方，如图：

![image](https://user-images.githubusercontent.com/73932884/165458046-f82c8e58-e4db-46f8-b11b-d8212471ca9d.png)

**Comment by windingwind** [comment]
见 #101 
我不能稳定复现这个问题，推测是由于其他插件或zotero在更新标题的同时触发了某些动作，导致错乱。如果你可以稳定复现，参见#6 提供debug输出，我会尝试排查问题。

**Comment by windingwind** [comment]
谢谢！我将会持续跟进这个问题。

**Comment by fan291752035** [comment]
作者大大，我好像发现了是某个插件的问题，我把插件disable之后再翻译就是这样了
![image](https://user-images.githubusercontent.com/73932884/165511459-c8a1c0ec-d121-4125-be83-041026d7d357.png)
这个是不是正常显示的情况，如果是那应该就是那个插件的问题

**Comment by fan291752035** [comment]
作者大大，我发现一个现象
你从第一篇文献依次翻译好像没问题，当你翻译完整个可视界面的时候，往下再翻译下一个的时候，之前翻译的所有的标题会在原标题栏里依次排序，造成错乱。似乎翻译后的短标题与可视界面之间有点bug

**Comment by windingwind** [comment]
> 作者大大，我发现一个现象 你从第一篇文献依次翻译好像没问题，当你翻译完整个可视界面的时候，往下再翻译下一个的时候，之前翻译的所有的标题会在原标题栏里依次排序，造成错乱。似乎翻译后的短标题与可视界面之间有点bug

谢谢反馈，应该是界面刷新导致的问题。

**Comment by windingwind** [comment]
@fan291752035 @breakertt 尝试v0.7.6

**Comment by fan291752035** [comment]
感谢作者大大的修复，乱序的情况不会有了，但是还有一个小问题，其实影响不大，某个文献条目在翻译后面的标题后会消失。
![image](https://user-images.githubusercontent.com/73932884/165660552-f2516c53-cd45-45ec-88dc-0e9e778008ec.png)

**Comment by windingwind** [comment]
> 感谢作者大大的修复，乱序的情况不会有了，但是还有一个小问题，其实影响不大，某个文献条目在翻译后面的标题后会消失。 ![image](https://user-images.githubusercontent.com/73932884/165660552-f2516c53-cd45-45ec-88dc-0e9e778008ec.png)

感觉不是大问题，另外我依然无法复现。。。
如果不是很影响使用，可以通过ctrl+T快速切换/刷新翻译显示

**Comment by fan291752035** [comment]
嗯嗯好的，谢谢修复
