### ISSUE TITLE
[Feature]能否固定翻译弹窗的大小？

### ISSUE THREAD

**Issue by Bryan1999-2100** [windingwind/zotero-pdf-translate#114]
有时选中一句比较短的句子后弹出的翻译弹窗也很小，会影响观看。

**Comment by windingwind** [comment]
翻译弹窗大小是自适应内容的，不太理解为什么窗口小会影响观看

**Comment by Bryan1999-2100** [comment]
就比方说这样弹窗就会很小，跟整个屏幕比起来就很不协调，而且每次弹窗大小都在变，所以想问下能不能手动更改弹窗大小，并且记忆上次更改过的大小😂。不过现在也不影响使用就是说。

**Comment by windingwind** [comment]
感觉这个需求比较弱。弹窗是用来快速查看小段内容的，长文本在侧边栏或者单独窗口看。如果觉得弹窗太小可以调整字体，也可以在设置里关闭弹窗功能
