### ISSUE TITLE
笔记栏注释翻译

### ISSUE THREAD

**Issue by BMXDa** [windingwind/zotero-pdf-translate#116]
**Is your feature request related to a problem? Please describe.**
您好，zotero pdf默认打开是zotero时，提取注释到笔记，显示翻译，当设置成系统默认时，没有翻译
**Describe the solution you'd like**
是否实现设置系统默认打开pdf时，提取注释也翻译？谢谢
**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
从注释中添加笔记是zotero的内置方法，我尽量避免对内置方法的修改，因为这是侵入性的，而且随zotero内部实现变化可能会导致意想不到的问题（但并不是不可以）。我不希望对插件引入太多的复杂性，会增加维护成本并带来成堆的bug

通过内置阅读器，可以实现添加选中文本及其翻译到note；也可以直接翻译批注（高亮），然后添加到note。我认为这两种方式足够满足一般使用需求。

毕竟，本插件是基于内置PDF阅读器开发的。大多数阅读需求内置阅读器足够满足了。

**Comment by zyx335588** [comment]
@BMXDa 
不知道我的理解是否正确：你是使用第三方PDF阅读器进行PDF标注，然后希望通过Zotero对这些标注进行翻译，并保存到笔记中？如果是的话，并且不是批量操作的话，可以通过以下途径间接实现：
（1）在第三方PDF阅读器中标注；
（2）勾选打开本插件中的“自动翻译批注”；
（3）用Zotero自身的PDF阅读器打开这篇PDF；
（4）通过Zotero阅读器的“文件”菜单中的“导入注释”，此时会触发“自动翻译批注”；
（5）然后利用zotero的“从注释中添加笔记”功能，将标注和翻译一起提取到笔记中。
这个过程通过程序自动化应该是可以的，但是这样会产生一个副作用就是会移除原文件上的批注，而新版Zotero将保存注释到文件的功能移除了（其实这个功能还是比较有用），只能“另存为”新文件，所以要看个人取舍了。

@windingwind 
这个触发“自动翻译批注”会将所有的标注都翻译，有时这并不是我们需要的，这也是我把“自动注释翻译”关掉的原因。作者是否可以考虑，除了“自动注释翻译”这个开启开关外；加一个选择条件，让大家选择是将标注全部自动翻译，还是将仅符合某一条件的注释进行翻译（例如使用某种颜色的标注的注释，但是zotero自身的标注颜色有限，可能存在第三方的标注颜色是否会被准确识别到这几种颜色等问题）。

**Comment by windingwind** [comment]
> @BMXDa 不知道我的理解是否正确：你是使用第三方PDF阅读器进行PDF标注，然后希望通过Zotero对这些标注进行翻译，并保存到笔记中？如果是的话，并且不是批量操作的话，可以通过以下途径间接实现： （1）在第三方PDF阅读器中标注； （2）勾选打开本插件中的“自动翻译批注”； （3）用Zotero自身的PDF阅读器打开这篇PDF； （4）通过Zotero阅读器的“文件”菜单中的“导入注释”，此时会触发“自动翻译批注”； （5）然后利用zotero的“从注释中添加笔记”功能，将标注和翻译一起提取到笔记中。 这个过程通过程序自动化应该是可以的，但是这样会产生一个副作用就是会移除原文件上的批注，而新版Zotero将保存注释到文件的功能移除了（其实这个功能还是比较有用），只能“另存为”新文件，所以要看个人取舍了。
> 
> @windingwind 这个触发“自动翻译批注”会将所有的标注都翻译，有时这并不是我们需要的，这也是我把“自动注释翻译”关掉的原因。作者是否可以考虑，除了“自动注释翻译”这个开启开关外；加一个选择条件，让大家选择是将标注全部自动翻译，还是将仅符合某一条件的注释进行翻译（例如使用某种颜色的标注的注释，但是zotero自身的标注颜色有限，可能存在第三方的标注颜色是否会被准确识别到这几种颜色等问题）。

会尝试在注释弹出菜单栏添加一个手动翻译的选项。通过颜色识别的很不可靠的。

**Comment by BMXDa** [comment]
好的，谢谢大佬。我现在开始使用内置阅读器了，虽然有些细节没有adobe那款好用，但是发现有些zotero功能还是内置阅读器使用方便。这是还是非常感谢大佬的奉献，祝大佬越办越好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月3日(星期二) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate] 笔记栏注释翻译 (Issue #116)





  
@BMXDa 不知道我的理解是否正确：你是使用第三方PDF阅读器进行PDF标注，然后希望通过Zotero对这些标注进行翻译，并保存到笔记中？如果是的话，并且不是批量操作的话，可以通过以下途径间接实现： （1）在第三方PDF阅读器中标注； （2）勾选打开本插件中的“自动翻译批注”； （3）用Zotero自身的PDF阅读器打开这篇PDF； （4）通过Zotero阅读器的“文件”菜单中的“导入注释”，此时会触发“自动翻译批注”； （5）然后利用zotero的“从注释中添加笔记”功能，将标注和翻译一起提取到笔记中。 这个过程通过程序自动化应该是可以的，但是这样会产生一个副作用就是会移除原文件上的批注，而新版Zotero将保存注释到文件的功能移除了（其实这个功能还是比较有用），只能“另存为”新文件，所以要看个人取舍了。
 
@windingwind 这个触发“自动翻译批注”会将所有的标注都翻译，有时这并不是我们需要的，这也是我把“自动注释翻译”关掉的原因。作者是否可以考虑，除了“自动注释翻译”这个开启开关外；加一个选择条件，让大家选择是将标注全部自动翻译，还是将仅符合某一条件的注释进行翻译（例如使用某种颜色的标注的注释，但是zotero自身的标注颜色有限，可能存在第三方的标注颜色是否会被准确识别到这几种颜色等问题）。
  
会尝试在注释弹出菜单栏添加一个手动翻译的选项。通过颜色识别的很不可靠的。

**Comment by windingwind** [comment]
> 好的，谢谢大佬。我现在开始使用内置阅读器了，虽然有些细节没有adobe那款好用，但是发现有些zotero功能还是内置阅读器使用方便。这是还是非常感谢大佬的奉献，祝大佬越办越好。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "windingwind/zotero-pdf-translate" ***@***.***&gt;; 发送时间:&nbsp;2022年5月3日(星期二) 上午10:58 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [windingwind/zotero-pdf-translate] 笔记栏注释翻译 (Issue #116) @BMXDa 不知道我的理解是否正确：你是使用第三方PDF阅读器进行PDF标注，然后希望通过Zotero对这些标注进行翻译，并保存到笔记中？如果是的话，并且不是批量操作的话，可以通过以下途径间接实现： （1）在第三方PDF阅读器中标注； （2）勾选打开本插件中的“自动翻译批注”； （3）用Zotero自身的PDF阅读器打开这篇PDF； （4）通过Zotero阅读器的“文件”菜单中的“导入注释”，此时会触发“自动翻译批注”； （5）然后利用zotero的“从注释中添加笔记”功能，将标注和翻译一起提取到笔记中。 这个过程通过程序自动化应该是可以的，但是这样会产生一个副作用就是会移除原文件上的批注，而新版Zotero将保存注释到文件的功能移除了（其实这个功能还是比较有用），只能“另存为”新文件，所以要看个人取舍了。 @windingwind 这个触发“自动翻译批注”会将所有的标注都翻译，有时这并不是我们需要的，这也是我把“自动注释翻译”关掉的原因。作者是否可以考虑，除了“自动注释翻译”这个开启开关外；加一个选择条件，让大家选择是将标注全部自动翻译，还是将仅符合某一条件的注释进行翻译（例如使用某种颜色的标注的注释，但是zotero自身的标注颜色有限，可能存在第三方的标注颜色是否会被准确识别到这几种颜色等问题）。 会尝试在注释弹出菜单栏添加一个手动翻译的选项。通过颜色识别的很不可靠的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

谢谢。我会关闭这个issue，如果有需要，可以随时重新打开。
