### ISSUE TITLE
[Bug]两个单词连起来会报TypeError: res is null

### ISSUE THREAD

**Issue by yottayeyeyeye** [windingwind/zotero-pdf-translate#117]
使用pdf划词翻译时，翻译“StatementExpression” 两个单词连起来的情况就会报TypeError: res is null，手动分开就能正常返回翻译。换用其他api也不能正常翻译，不只是Google api。

错误信息如下：
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Google(API), not Zotero or the PDF Translate addon.
        TypeError: res is null

**Comment by windingwind** [comment]
看起来是你的pdf格式可能存在错乱。选择文字然后复制到剪切板，看一下是否选中的内容是空的。

**Comment by yottayeyeyeye** [comment]
![image](https://user-images.githubusercontent.com/22636573/166422619-89d88750-b6a8-41da-8cfc-54ee0cf7c444.png)
不是空的，手动
![image](https://user-images.githubusercontent.com/22636573/166422724-73bda7e2-17b7-4973-b0e0-56c155cce1cb.png)
只要是两个单词连起来就会出现这种情况

**Comment by windingwind** [comment]
在近期的新版本，对单个单词默认开启词典翻译替代机器翻译。出现这个问题是由于使用的词典中查不到该单词。
你可以：
1. 换用bing词典，而非有道词典。bing支持网络释义，能够翻译出你所举例的单词；
2. 关闭词典翻译功能。
3. 手动编辑无效的词，加空格以后重新翻译。
