### ISSUE TITLE
[Feature] 希望添加拼接多次选中内容翻译功能

### ISSUE THREAD

**Issue by pboymt** [windingwind/zotero-pdf-translate#118]
### 问题描述

一个常见的问题，部分段落语句由于被分页或者（在格式老旧的文档中）被左右栏分隔，如果想完整翻译目前需要分别复制后拼接翻译，比较麻烦。

### 功能需求

希望能够有按住`Alt`键圈选拼接多次选中的内容，然后进行翻译的功能。

### 目前的替代方案

知云有拼接的功能，但是没去用，太麻烦。目前是打开侧边栏自己复制拼接翻译。

### 截图

<img width="971" alt="屏幕截图" src="https://user-images.githubusercontent.com/10893582/166396090-53eda38e-2b85-4f20-a661-90cbe77a22b0.png">

**Comment by windingwind** [comment]
选取文本是通过zotero内部方法完成的，我没有办法修改它的逻辑。不过你说的按住alt多选是可以尝试的一种解决方案

**Comment by pboymt** [comment]
没错，在选中事件中检查`Alt`键是否被按下，如果按下后就和目前在原文框中的内容拼接一下再翻译就行了。

知云就是这个解决方案，如果Zotero的PDF阅读器没有砍掉Event API的呈现内容，理论上可以实现。

**Comment by windingwind** [comment]
也欢迎贡献代码提PR！

**Comment by windingwind** [comment]
@pboymt 请尝试最新版本。
