### ISSUE TITLE
[Bug] 翻译后切换其他标签页的PDF进行翻译概率会显示上一文档的翻译结果

### ISSUE THREAD

**Issue by pboymt** [windingwind/zotero-pdf-translate#119]
### 问题描述

在某一标签页的PDF进行翻译后，切换到另一个文档进行翻译，概率性出现不管选中什么内容都会一只翻译上个文档中选中的内容。

### 复现方法
1. 打开多个PDF进行阅览
2. 在其中一个文档使用划句翻译功能
3. 切换到另一个文档进行划句翻译
4. 概率持续显示上一个文档的翻译结果

### 操作预期

正常显示选中内容的翻译。

### 截图
![动画](https://user-images.githubusercontent.com/10893582/166402218-9d11405a-0019-4688-bd38-ef5dd1cfc906.gif)

### 运行环境
 - OS: Windows 11 21H2
 - Zotero Version 6.0.6
 - Addon Version 0.7.6

### 其他说明

这个是完全概率性的好像，十几次就复现了一两次，出问题的话，切换回上一个文档再切换回下一个文档就不这样了。

**Comment by windingwind** [comment]
谢谢反馈，似乎是偶然触发的问题，我无法复现。如果不是破坏性的bug，可能不会花太多精力去排查。

**Comment by 406Feng** [comment]
> 这个Bug在我使用过程中已经是每次都会出现了，可能我打开的tab比较多？每次切换翻译引擎就会正常，但下一句又会那样，所以现在是一句一切换。希望作者能修复。

**Comment by 406Feng** [comment]
> 谢谢反馈，似乎是偶然触发的问题，我无法复现。如果不是破坏性的bug，可能不会花太多精力去排查。

这个Bug在我使用过程中已经是每次都会出现了，可能我打开的tab比较多？每次切换翻译引擎就会正常，但下一句又会那样，所以现在是一句一切换。希望作者能修复。

**Comment by windingwind** [comment]
> > 谢谢反馈，似乎是偶然触发的问题，我无法复现。如果不是破坏性的bug，可能不会花太多精力去排查。
> 
> 这个Bug在我使用过程中已经是每次都会出现了，可能我打开的tab比较多？每次切换翻译引擎就会正常，但下一句又会那样，所以现在是一句一切换。希望作者能修复。

请依照#6 把触发问题时的debug输出贴上来，方便排查

**Comment by 406Feng** [comment]
> > > 谢谢反馈，似乎是偶然触发的问题，我无法复现。如果不是破坏性的bug，可能不会花太多精力去排查。
> > 
> > 
> > 这个Bug在我使用过程中已经是每次都会出现了，可能我打开的tab比较多？每次切换翻译引擎就会正常，但下一句又会那样，所以现在是一句一切换。希望作者能修复。
> 
> 请依照#6 把触发问题时的debug输出贴上来，方便排查


[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

[JavaScript Error: "Permission denied to access property "__reactFiber$wv3pbipeuh"" {file: "resource://zotero/react-dom.js" line: 10608}]

version => 6.0.6, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.6, extensions => ZotFile (5.1.1, extension), Zotero PDF Translate (0.7.6, extension), Zotero LibreOffice Integration (6.0.0.SA.6.0.6, extension), Zotero Word for Windows Integration (6.0.0.SA.6.0.6, extension)

**Comment by windingwind** [comment]
@406Feng 这不是完整的debug输出，需要先打开debugs输出窗口，然后进行操作，触发问题之后，再复制完整的debug输出。

**Comment by windingwind** [comment]
将会关闭该问题。如果再次遇到该问题，可随时重新打开。
