### ISSUE TITLE
[Bug]百度翻译引擎无法使用

### ISSUE THREAD

**Issue by outlookE5** [windingwind/zotero-pdf-translate#120]
**问题描述**
使用百度翻译引擎，如果不开启弹窗，百度翻译无法使用，启用弹窗才能正常使用。

**复现方法**
1.使用百度翻译引擎，取消勾选“启用弹窗”
2.选中字段翻译，翻译窗口出现[[Request Error Engine not available, invalid secret, or request too fast. Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues The message below is from Baidu*, not Zotero or the PDF Translate addon. 54003:Invalid Access Limi]
3.勾选“启用弹窗”，选中字段翻译则可正常翻译。

**截图**
未启用弹窗
![Snipaste_2022-05-03_15-48-55](https://user-images.githubusercontent.com/96066454/166419966-9f060e1d-5ddb-4d6f-93df-d465f7380a54.png)
启用弹窗后
![image](https://user-images.githubusercontent.com/96066454/166420181-5015cdba-816b-432e-9d28-3f6fa815a62c.png)

**运行环境**
 - OS: Windows 11
 - Zotero Version：6.0.6
 - Addon Version：0.7.6

**其它说明**
软件重启后，开始几次翻译，百度翻译引擎正常。但很快又会出现访问受限，启用弹窗后又能正常使用。

**Comment by windingwind** [comment]
软件向翻译服务提供商的请求逻辑不因开启弹窗与否而改变。百度翻译已知经常会偶尔封停翻译。
