### ISSUE TITLE
翻译结果只有弹窗，没有侧边栏内容，重启也没用

### ISSUE THREAD

**Issue by 4965898** [windingwind/zotero-pdf-translate#123]
zotero版本6.06，其他插件没有任何问题

**Comment by gxy1932582** [comment]
给附件创建一个父条目就可以了

**Comment by 4965898** [comment]
呃呃，完全不会编程

**Comment by windingwind** [comment]
不需要你编程。如gxy 所说，需要给没有条目信息的pdf附件创建一个父条目。

**Comment by 4965898** [comment]
父条目是什么？

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/167285352-21e7150b-dcf6-40cf-bd4b-711a318a1f96.png)
这是一个有父条目的pdf。创建一个空的条目，然后pdf拖进去

**Comment by 4965898** [comment]
好了，正常了，谢谢
