### ISSUE TITLE
[Bug]百度翻译特定语句报错

### ISSUE THREAD

**Issue by zhjcreator** [windingwind/zotero-pdf-translate#125]
**Describe the bug**
当翻译的语句包含”between -10%“这串字符时会报错Time out

**To Reproduce**
打开论文《A review on global solar radiation prediction with machine learning models in a comprehensive perspective》
在章节3.2，框选”between -10%“进行翻译

**Expected behavior**
能够正常翻译

**Screenshots**
![image](https://user-images.githubusercontent.com/55911606/167295368-f981925b-bfee-4332-bca5-a85679887539.png)
![image](https://user-images.githubusercontent.com/55911606/167295641-403eabfb-a156-4eec-acbe-e8054479555f.png)

**Environment**
 - OS: Windows
 - Zotero Version：6.0.6
 - Addon Version：0.7.6

**Additional context**
框选包含该“-”的段落，“-”及之后的字符无法正常复制，推测是特殊字符的原因。希望可以在翻译时直接跳过这类字符。

**Comment by windingwind** [comment]
谢谢反馈。之前腾讯翻译有加密的问题，但百度翻译仅仅使用MD5进行加密，我不知道应该如何处理特殊字符。
另外，图中看起来报错是Time Out.是否是因被百度暂时屏蔽？这样的情况也比较多见。

**Comment by zhjcreator** [comment]
> 谢谢反馈。之前腾讯翻译有加密的问题，但百度翻译仅仅使用MD5进行加密，我不知道应该如何处理特殊字符。 另外，图中看起来报错是Time Out.是否是因被百度暂时屏蔽？这样的情况也比较多见。

我又进行了次尝试，结果依旧是这样，可以确定不是百度屏蔽。可能是百度无法处理这个特殊字符导致超时？
![image](https://user-images.githubusercontent.com/55911606/167302490-c9c1ff40-bd1b-4ed1-a376-32f9aeaf97d7.png)
![image](https://user-images.githubusercontent.com/55911606/167302513-a06896bc-0fef-4ad3-be96-84e8129f2166.png)

**Comment by windingwind** [comment]
我认为可能也是。快速的解决办法是在侧边栏中编辑原文，去掉字符以后重新翻译。可能无法在插件层面解决这个问题。

**Comment by zhjcreator** [comment]
> 我认为可能也是。快速的解决办法是在侧边栏中编辑原文，去掉字符以后重新翻译。可能无法在插件层面解决这个问题。

感谢回复，这倒不是什么影响使用的bug，遇到概率也低，只是偶遇然后顺手报告下。这个issue正好防止其他人和我一样傻乎乎的以为是自己被百度屏蔽了。
