### ISSUE TITLE
[Feature]生词本功能

### ISSUE THREAD

**Issue by clq9920** [windingwind/zotero-pdf-translate#128]
希望能够在翻译后添加"加入生词本"按钮,并提供简单导出和管理功能.

**Comment by windingwind** [comment]
看起来超过了一个翻译插件应该做的事情。这只是一个用来辅助文献阅读的工具，学习语言不是它的功能。

**Comment by clq9920** [comment]
> 看起来超过了一个翻译插件应该做的事情。这只是一个用来辅助文献阅读的工具，学习语言不是它的功能。

好吧,主要是以前用浏览器的沙拉查词看文献(一个浏览器翻译插件,支持网页,pdf,扩展调用,之前我一直依靠这个,zotero有这个翻译插件就不用了),所以我希望这个zotero的插件能结合沙拉查词插件,沙拉查词插件除了多引擎翻译,语音支持,还有生词本功能等,具体如何结合,我以前用的是将待翻译文本复制到剪切板,之后快捷键调用沙拉查词插件,因此我希望zotero-pdf-translate插件能在选择文本后直接复制到剪切板,同时模拟键盘输入,调用沙拉查词插件

沙拉查词:https://saladict.crimx.com/native.html

**Comment by clq9920** [comment]
> 看起来超过了一个翻译插件应该做的事情。这只是一个用来辅助文献阅读的工具，学习语言不是它的功能。

好吧,主要是以前用浏览器的沙拉查词看文献(一个浏览器翻译插件,支持网页,pdf,扩展调用,之前我一直依靠这个,zotero有这个翻译插件就不用了),所以我希望这个zotero的插件能结合沙拉查词插件,沙拉查词插件除了多引擎翻译,语音支持,还有生词本功能等,具体如何结合,我以前用的是将待翻译文本复制到剪切板,之后快捷键调用沙拉查词插件,因此我希望zotero-pdf-translate插件能在选择文本后直接复制到剪切板,同时模拟键盘输入,调用沙拉查词插件

沙拉查词:https://saladict.crimx.com/native.html

**Comment by windingwind** [comment]
> > 看起来超过了一个翻译插件应该做的事情。这只是一个用来辅助文献阅读的工具，学习语言不是它的功能。
> 
> 好吧,主要是以前用浏览器的沙拉查词看文献(一个浏览器翻译插件,支持网页,pdf,扩展调用,之前我一直依靠这个,zotero有这个翻译插件就不用了),所以我希望这个zotero的插件能结合沙拉查词插件,沙拉查词插件除了多引擎翻译,语音支持,还有生词本功能等,具体如何结合,我以前用的是将待翻译文本复制到剪切板,之后快捷键调用沙拉查词插件,因此我希望zotero-pdf-translate插件能在选择文本后直接复制到剪切板,同时模拟键盘输入,调用沙拉查词插件
> 
> 沙拉查词:https://saladict.crimx.com/native.html

在侧边栏点击复制原文本，就可以快速复制。直接复制不符合大多数用户的需要，会把剪贴板塞满的

**Comment by wkaijun** [comment]
非常支持也非常需要，我们读文献获取文献信息的同时，对于大部分中国学生来说也是一个语言学习的过程，尤其是专业词汇通过文献阅读的强化越来越提高文献阅读的速度，可以选定一个颜色的标注专门为新单词的选项，带着出现在文中的句子便于理解和复习，多次重复和不同文献中的例句是学习英语最好的方法，非常希望能有这个功能。

**Comment by windingwind** [comment]
@wkaijun @clq9920 请参见我的另一个插件，https://github.com/windingwind/Knowledge4Zotero
主要用于知识管理与快速信息提取，可将多个文献笔记、注释集成在一处。三天前刚刚发布，并计划在未来支持卡片功能。
我认为你们提到的生词本功能更接近知识管理，因此在那个插件里实现更加合适。由于都是我开发的插件，可以与翻译有一定程度的联动。可以移步那里进行进一步功能细节的探讨。

**Comment by windingwind** [comment]
由于本需求不会在这个插件实现，将关闭问题。有需要请到Zotero Better Notes进行讨论。
