### ISSUE TITLE
保留各引擎的API/密钥配置 #enhancement

### ISSUE THREAD

**Issue by xjtusjtu** [windingwind/zotero-pdf-translate#13]
老哥晚上好，我觉得插件非常不错，使用起来非常方便！

有一个小建议，可以保留不同引擎的API配置吗？这样在更换引擎的时候，就不需要重新输入一遍密钥（我个人有多个引擎的密钥，有时候回来会更换）

**Comment by xjtusjtu** [comment]
每次更换引擎，然后换回去的时候，会导致密钥丢失，需要重新输入

**Comment by windingwind** [comment]
should be solved in v0.2.4
