### ISSUE TITLE
[Bug]在右边为笔记的时候,添加注释经常会卡死,但是非笔记界面不会

### ISSUE THREAD

**Issue by Mindusk** [windingwind/zotero-pdf-translate#132]
**Describe the bug**
正常情况下划词翻译不会卡死,但是如果右边是笔记页面,划词翻译并添加标注就会卡死
**To Reproduce**

https://user-images.githubusercontent.com/93774583/168222287-14e7b1b3-a1f9-42aa-85e0-5be2dee962a9.mp4

**Environment**
 - OS: macOS
 - Zotero Version:6.0.7
 - Addon Version:0.7.8

**Comment by Mindusk** [comment]
把其他所有插件都禁用了之后这个bug还是会复现,之前是偶尔出现这样的问题,今天发现100%会这样

**Comment by Mindusk** [comment]
测试了一下0.6.0-0.7.5都不会出现卡死问题,从0.7.6开始出现,具体表现是划词标记之后,右下角不会弹出
<img width="255" alt="image" src="https://user-images.githubusercontent.com/93774583/168224516-6de32b6d-f44e-4905-9885-d82840268dc1.png">
这个窗口,同时界面无反应

**Comment by windingwind** [comment]
谢谢反馈，我将会检查并尝试修复

**Comment by Mindusk** [comment]
感谢!

**Comment by windingwind** [comment]
0.7.6的更新主要是修复了标题翻译的显示问题，似乎与pdf翻译卡死完全没有联系。如果v0.7.6存在问题，可能是更早版本中的bug，并随机触发

**Comment by Mindusk** [comment]
可能是的,0.7.6会偶尔出现, 然后最近的版本基本会出现,感觉好像是内存不够(类似这种问题),在点击标记的时候会卡顿一下,然后开始无响应

**Comment by windingwind** [comment]
请尝试v0.7.9
应当已经修复该问题

**Comment by Mindusk** [comment]
完美解决,太厉害了!
