### ISSUE TITLE
使用疑问：更新v.0.7.9之后注释窗口上的翻译图标

### ISSUE THREAD

**Issue by xiaodl813** [windingwind/zotero-pdf-translate#133]
您好，
请问在更新了5月14日的v.0.7.9之后，在注释界面出现了如下显示的图标👇。其点击之后并没有任何反应，请问是什么情况呢？
![image](https://user-images.githubusercontent.com/50045896/168407016-1941110a-a477-43f6-8406-46c1f3a5d999.png)
我查询了更新的记录，发现0.7.9的更新只是一个错误修复，并没有添加新功能。
谢谢

**Comment by windingwind** [comment]
这是在更前几个版本引入的手动翻译批注功能。已在v0.7.10修复
