### ISSUE TITLE
[Bug]update annotation 按钮不能唤起

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-pdf-translate#137]
`0.7.10`，Update Annotation 按钮不能唤起（即：原文不能修改后再翻译）。

**Comment by windingwind** [comment]
确实是这样。将会排查，但近期可能没有太多时间修复

**Comment by lil-i321** [comment]
> 确实是这样。将会排查，但近期可能没有太多时间修复

感谢！

**Comment by windingwind** [comment]
@lil-i321 在最近的测试中发现该功能正常，不清楚之前为什么出现问题。请检查是否可以使用？

**Comment by lil-i321** [comment]
> @lil-i321 在最近的测试中发现该功能正常，不清楚之前为什么出现问题。请检查是否可以使用？

`0.8.4 ` 该功能正常，感谢!
