### ISSUE TITLE
[Feature] 请求增加百度“垂直领域翻译”API

### ISSUE THREAD

**Issue by GFDGIT** [windingwind/zotero-pdf-translate#138]
**Is your feature request related to a problem? Please describe.**
希望实现专业领域更好的翻译效果。

**Describe the solution you'd like**
以下为百度对“垂直领域翻译”的介绍：
为了提升特定领域机器翻译的准确度，百度翻译针对多个垂直领域模型进行了优化，特定领域术语翻译相较于通用翻译API结果更为准确，句式更加符合该行业特点。
现在开通，即享每月50万免费字符。
目前已开通网络文学、财经金融、生物医药、科技电子、水利机械等5个垂直领域，且领域在不断扩展中。

**Describe alternatives you've considered**

**Additional context**
[垂直领域API接入文档](https://fanyi-api.baidu.com/doc/22)

感谢开发者！

**Comment by windingwind** [comment]
如果你有编程基础，欢迎在现有src/translate/baidu.ts的基础上修改并提PR。看文档似乎与机器翻译接口基本一致，仅仅增加了一个参数。

**Comment by windingwind** [comment]
v0.7.12已支持

**Comment by GFDGIT** [comment]
您好，这个API报[签名错误](https://github.com/windingwind/zotero-pdf-translate/commit/121ef45e735e0b958e171b55ee2e6b514c4710b9#r74346407)，我想应该是生成签名的过程有点问题，麻烦您看一下？
应该是个小问题，但我没有开发环境，没法验证，所以没有pr。

**Comment by GFDGIT** [comment]
> 感谢提醒，已修正。测试看还有没有问题？

测试了没有问题！
