### ISSUE TITLE
[Bug]中翻英，所有引擎都失效

### ISSUE THREAD

**Issue by LYB030** [windingwind/zotero-pdf-translate#139]
中翻英，尝试了所有的引擎都是以下的error
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Google, not Zotero or the PDF Translate addon.
        TypeError: res is null

**Comment by windingwind** [comment]
已修复
