### ISSUE TITLE
[Bug]建议对特定语言关闭翻译后，此特定语言的批注也不翻译

### ISSUE THREAD

**Issue by Jason-Deng25** [windingwind/zotero-pdf-translate#140]
我已经设置了对中文关闭翻译功能，但是中文的批注依旧在翻译，而且还翻译得很奇怪，与原文也不符。
![image](https://user-images.githubusercontent.com/74088846/169432257-7d5a3be1-b270-48c8-9145-465870e06164.png)

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/169443324-76555d3e-a2ce-44e4-bddb-6130104afb3a.png)

正确设置语言后，不会自动翻译批注

**Comment by windingwind** [comment]
如果依然出现问题，请按照#6 的步骤排查问题并贴上来debug输出

**Comment by windingwind** [comment]
将关闭该问题。如果再次遇到，可随时重新打开
