### ISSUE TITLE
[Vote] Auto-translate title for newly added items

### ISSUE THREAD

**Issue by liuenqian** [windingwind/zotero-pdf-translate#143]
> @liuenqian: 希望title能加入新文献后自动翻译

Please 👍 or 👎 to show your attitude towards this vote: If auto-translate title for newly added items is a welcomed feature?

**Comment by windingwind** [comment]
I'll make this issue a **Vote** and see if it is a welcomed feature.

**Comment by FishCatCake** [comment]
Manual add might be more convenient than auto-translate.

**Comment by windingwind** [comment]
@leaveswing 菜单已更新，除标题翻译外均放入二级菜单。

**Comment by lil-i321** [comment]
In my opinion, this will make a little bit of sense.

**Comment by lil-i321** [comment]
> 

一点点意义 的意思

**Comment by liuenqian** [comment]
我需要做卡片笔记，在卡片笔记上使用文献的中文翻译能更快的知道是哪个文章的内容，所以希望可以增加一个选项是否自动翻译，每个人都可以自由的选择。中文标题的卡片笔记和better note结合，更快的整理相关文献。

**Comment by liuenqian** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/64129965/170626419-9219ccfd-aa6f-4dc0-8ef6-bad4a59ef27e.png">

**Comment by windingwind** [comment]
@liuenqian 
![image](https://user-images.githubusercontent.com/33902321/170628187-4e7fcbb7-281b-4583-a38c-e1702765664d.png)
这个按钮可以手动翻译。默认是自动翻译的，可以在首选项中设置。
另，每个issue只讨论一个问题。建议以后放在新的issue讨论。

**Comment by windingwind** [comment]
According to the vote, this feature will not be planned.
