### ISSUE TITLE
希望在pdf阅读器内部增加选择文本搜索功能，搜索的内容可以zotero内部的文献也可以自定义互联网搜索引擎[Feature]Complete the Title Here

### ISSUE THREAD

**Issue by wuzelin** [windingwind/zotero-pdf-translate#144]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
1. zotero内部的搜索，如何触发，结果如何呈现？
2. 搜索网页，如何触发？

**Comment by wuzelin** [comment]
1.内部搜索不知道 啊
2.搜索网页 通过浏览器跳转实现  可以自定搜索引擎  通过右键选中触发

**Comment by wuzelin** [comment]
内部的搜索 可以通过文本内容 跳转到软件自带的高级搜索界面

**Comment by windingwind** [comment]
已计划
