### ISSUE TITLE
自动更新后翻译报错

### ISSUE THREAD

**Issue by YanyiPU** [windingwind/zotero-pdf-translate#145]
今天插件自动更新以后一直报错: 
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Google(API), not Zotero or the PDF Translate addon.
        TypeError: res is null

**Comment by windingwind** [comment]
我使用正常，可能是你所在的网络环境缘故。Google翻译在大陆地区是不稳定的
