### ISSUE TITLE
[Feature] 字典功能似乎不会处理没有搜索结果的情况

### ISSUE THREAD

**Issue by Saunak626** [windingwind/zotero-pdf-translate#148]
![image](https://user-images.githubusercontent.com/34276206/170495992-63c265e6-6317-46c8-95a4-b7028cf17d9d.png)
当字典功能启用的时候，对于能够搜到的词汇正确显示结果。
![image](https://user-images.githubusercontent.com/34276206/170496280-29a35236-426b-43ad-821a-c272a79b6f1a.png)
但是当这个词是特殊名词这类没有被字典收录的时候，返回的是request error。
![image](https://user-images.githubusercontent.com/34276206/170496517-17a5bdb6-db74-488d-975b-4d46c22c4fd4.png)
但是关掉字典的时候，用翻译引擎可以获得。
是否可以设置为，当启用字典引擎的时候优先显示字典的结果。如果字典没有搜到结果或者引擎无法访问，会默认去调用现在的翻译引擎？

**Comment by windingwind** [comment]
谢谢反馈，已经更新该功能。
