### ISSUE TITLE
[Help wanted] 网搜无果，纯小白求帮助(我想规范加一个label提问的,但我不会，请见谅~）

### ISSUE THREAD

**Issue by neuronsandsynapses** [windingwind/zotero-pdf-translate#157]
@windingwind 你好，有道智云控制台似乎更新了，你给的”Tern字幕组机翻小助手“那个参考步骤似乎不适用啦。现在创建应用后需要去“查看文档“，再”调试代码“。我现在已经创建应用成功啦，但在”创建示例“和将“应用和示例”这一步卡住了，请问要怎么办呢？另外，我是一个纯小白，请问我在有道的控制台创建应用后，已经有一个“ID”和"密钥“了，我看你在插件的主页也给了一个密钥MY_APPID#MY_SECRET#MY_VOCABID(optional)，还有VOCABID那里也不太懂，请问我到底要怎样操作才能在Zotero里使用有道智云翻译呢？问题好长，感谢看完，期待回复~

**Comment by windingwind** [comment]
参考这个文档：https://ai.youdao.com/doc.s
不需要创建示例。将id和密钥复制到插件设置界面的密钥栏就可以。
`MY_APPID#MY_SECRET#MY_VOCABID(optional)`是提供的样例，告诉你appid，secret应该以怎样的格式填入。你只需要把`MY_APPID`换成你的appid，`MY_SECRET`换成你的secret，就可以。
`MY_VOCABID`是有道的自定义字典功能。写了optional的选项不使用可以空着

**Comment by neuronsandsynapses** [comment]
感谢回复，按照您的回复，我以“我的ID#我的密钥”的格式输入到zotero插件的密钥栏中，但还是不能用，为什么呢？是我少输入#符号或者是少空格了吗？

**Comment by windingwind** [comment]
请提供翻译失败时的结果

**Comment by neuronsandsynapses** [comment]
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Youdao Zhiyun*, not Zotero or the PDF Translate addon.
        Error: errorCode: 108

**Comment by windingwind** [comment]
应用ID无效，注册账号，登录后台创建应用和实例并完成绑定，可获得应用ID和应用密钥等信息

**Comment by neuronsandsynapses** [comment]
不好意思，我不明白了，您上面说“不需要创建示例。将id和密钥复制到插件设置界面的密钥栏就可以。”
目前，我在有道智云的控制台只操作了“创建应用”这一步，打开应用详情有一个ID和密钥。
问题是，我没有看到在哪里“创建实例”并且“完成绑定”，控制台已经找不到这两个选项了……

**Comment by windingwind** [comment]
你最开始说“创建示例”，因此我回复不需要创建示例。
> 应用ID无效，注册账号，登录后台创建应用和实例并完成绑定，可获得应用ID和应用密钥等信息
这是官方文档对你遇到的错误代码的解释。
![image](https://user-images.githubusercontent.com/33902321/172525209-6d7e6464-c637-4b1d-85a6-b3f0e629e5be.png)
像这样就是正常的。另外请检查是否账户有余额

**Comment by neuronsandsynapses** [comment]
好的感谢，账户余额就是注册送的50块。“官方文档对你遇到的错误代码的解释。”是什么意思啊？图我看不懂……

**Comment by neuronsandsynapses** [comment]
那我还需要【创建实例】并且完成【实例和应用的绑定】吗？
此外，ID和secret之间用一个#符号隔开即可吗？密钥格式有没有其他需要注意的事项啊？

**Comment by windingwind** [comment]
我只能通过官方文档提供的错误代码解释帮助排查问题，如果仍然无法解决需要联系有道的客服。至少我这里使用正常
我感觉是不需要创建实例的。
和提供的格式一样，用井号隔开就可以。看下前后没有多余的字符就可以

**Comment by neuronsandsynapses** [comment]
好的，感谢感谢，至少我现在知道大概是怎么回事了，刚刚试了下百度翻译，成功了！Thx~~~~

**Comment by windingwind** [comment]
没事，客气啦。将关闭这个issue

**Comment by windingwind** [comment]
有问题可再讨论
