### ISSUE TITLE
Translator errors

### ISSUE THREAD

**Issue by 7homR** [windingwind/zotero-pdf-translate#16]
New to github — please forgive etiquette gaps.

I posted in Zotero forums, but I've been getting errors today no matter what translator I'm using:

[Request Error]
Engine not available, invalid secret, or request too fast.
Please consider using another translate engine or posting issue here: https://github.com/windingwind/zotero-pdf-translate/issues
        Error: HTTP GET https://translate.google.com/translate_a/single?client=webapp [etc.]
 failed with status code 400

Thanks,
~Thomas

**Comment by jasonmayday** [comment]
Same issue, failed with status code 400

**Comment by windingwind** [comment]
v0.2.5 should have solved this issue on Google.
With Microsoft Translate, the free quota of my account is used up, thus the default key will no longer be valid. Get your key and it should work with you.
