### ISSUE TITLE
[Feature]可以取消自动翻译标黄部分并将中文翻译以批注的方式添加上去，感觉这个是不必要的且批注图标影响阅读

### ISSUE THREAD

**Issue by AlbertHAHAHA** [windingwind/zotero-pdf-translate#165]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/107606496/174003810-af10c328-82fe-42cf-bb25-cc17866d637b.png)

**Comment by windingwind** [comment]
see https://github.com/windingwind/zotero-pdf-translate#general-functions
