### ISSUE TITLE
可以自动删掉原文里的尾注和连接符“-”吗，好像很多翻译引擎都有干扰

### ISSUE THREAD

**Issue by ly08ly** [windingwind/zotero-pdf-translate#166]
提交翻译文本的时候，希望可以自动删除原文文本里的尾注“1, 2, 3, [1], [2], [3]"这些还有连接符“-”，感觉很多翻译引擎都会有不同程度的影响。多谢！

**Comment by windingwind** [comment]
这些并非特殊字符，不会太大影响翻译。
机器翻译本来就不确保准确性，只是一种大体意思，用于辅助理解
