### ISSUE TITLE
[Bug]Complete the Title Here

### ISSUE THREAD

**Issue by 2750250486** [windingwind/zotero-pdf-translate#167]
作者你好，请问我申请到了deepl 的key 并填入到了密钥中，提出错误，怎么办？
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon.
        Error: Request timed out

**Comment by windingwind** [comment]
看你的情况是无法访问DeepL。可能是网络问题

**Comment by 2750250486** [comment]
谢谢，我看看是否是密钥的问题

**Comment by JasenChao** [comment]
我也出现了这个问题，网络链接正常的，所有的翻译引擎都报这个错误
