### ISSUE TITLE
[Bug]DeepL API 不可用

### ISSUE THREAD

**Issue by appw-cn** [windingwind/zotero-pdf-translate#168]
**Describe the bug**
使用DeepL API结果显示：
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon.
Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403
**To Reproduce**
1. 在https://www.deepl.com/docs-api 页面，找到DeepL API Free\HTTP Request中的这些代码
```
POST /v2/translate?auth_key=12345678-1234-1234-1234-123456789abc:fx> HTTP/1.0
Host: api-free.deepl.com
User-Agent: YourApp
Accept: */*
Content-Length: [length]
Content-Type: application/x-www-form-urlencoded

auth_key=12345678-1234-1234-1234-123456789abc:fx&text=Hello, world&target_lang=DE
```
2. 把12345678-1234-1234-1234-123456789abc:fx粘到zotero设置的DeepLFree*里面
3. 翻译时结果显示：
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon.
Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403

**Expected behavior**
可能要up主简单讲解一下设置步骤。感谢up主，祝事事顺心~

**Environment**
 - OS: Windows 10
 - Addon Version 0.8.14

**Comment by Kinsley1998** [comment]
同

**Comment by windingwind** [comment]
我确实一直可以用🤔
![image](https://user-images.githubusercontent.com/33902321/174487023-f68dec63-8f15-4ab7-afb0-16c201b5282e.png)
首先需要有效的deepl密钥。对deepl来说没有什么格式，复制进去就行了。
我看到你使用的似乎不是有效的密钥。文档提供的只是个样例，你需要自己注册账号。需要限定国家注册的visa银行卡，如果没有建议放弃

**Comment by Kinsley1998** [comment]
好 谢谢您



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月19日 22:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] [Bug]DeepL API 不可用 (Issue #168) |

我确实一直可以用🤔

首先需要有效的deepl密钥。对deepl来说没有什么格式，复制进去就行了。
我看到你使用的似乎不是有效的密钥。文档提供的只是个样例，你需要自己注册账号。需要限定国家注册的visa银行卡，如果没有建议放弃
