### ISSUE TITLE
加入语音朗读功能的可能性

### ISSUE THREAD

**Issue by molanjingke** [windingwind/zotero-pdf-translate#169]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

—————————————————分割线—————————————————

看到一些生词，但是不知道发音是什么，而且阅读文献时经常是快节奏的，如果能够添加针对单词的语音朗读功能，就能同时对频繁出现的单词进行针对学习，极大提高之后的文献阅读效率。
考虑到自身对zotero的软件框架并不了解，只是询问一下是否存在添加语音朗读功能的可能性。如果能做这一功能，那简直太好了。

**Comment by windingwind** [comment]
这是一个提出很久的功能，但优先级较低。
将会合并讨论到#67
