### ISSUE TITLE
翻译框未弹出

### ISSUE THREAD

**Issue by yyj1126** [windingwind/zotero-pdf-translate#17]
![FC715847-FECF-40FD-9CDD-0DF68FDEE82D](https://user-images.githubusercontent.com/88979298/159534320-d7d831c3-7694-4330-a7b7-cdeb7d3b540b.jpeg)
![EDDA85AC-1542-4103-96C8-432D8061A398](https://user-images.githubusercontent.com/88979298/159534342-51e1c6ec-7cdd-4bd1-89da-1f5cbfffdd76.jpeg)
重启后依旧没有翻译框弹出，请问如何解决这个问题，谢谢

**Comment by windingwind** [comment]
please update to the latest version

**Comment by yyj1126** [comment]
zotero和插件都已经是最新版的了

**Comment by windingwind** [comment]
Your screenshot seems to be PDF Translate v0.1.4, while the latest version is v0.2.6
If the latest add-on still have this bug, please go to Help->Debug Output Logging->View Output. Select some text after the debug window is opened and paste the logs in this issue. With debug logs, I can find out what's going on with your Zotero.

**Comment by yyj1126** [comment]
![image](https://user-images.githubusercontent.com/88979298/159609584-602e7df4-a3eb-415a-b7f8-792af6a526c2.png)
oh,I upgraded PDF Translate to the latest version after I cut the screenshot, but it still didn't work

**Comment by windingwind** [comment]
Thanks. I guess this is not a PDF Translate error, but a Zotero Reader error.

The addon will listen a build-in reader tab select event and wait until the reader is ready. Then it will insert popup/sidebar tab to the reader window. This is how it works.

However, due to some reasons your Zotero reader is never ready(or load too slow that the ready event meets a time out).
May I ask how long it takes to load a reader tab(from Zotero start and the PDF is fully opened) for you?

**Comment by yyj1126** [comment]
About one second. The process of loading doesn't seem to stuck.

**Comment by windingwind** [comment]
Weird. I will add some work around to try to solve this bug.
Is this caused by an add-on conflict? Could you please try disabling all other add-ons and see if it works?

**Comment by windingwind** [comment]
Try this:
[v0.2.7a.zip](https://github.com/windingwind/zotero-pdf-translate/files/8329303/v0.2.7a.zip)

**Comment by yyj1126** [comment]
![1414BD12-F39D-4BD0-BE20-320EAB11F0C4](https://user-images.githubusercontent.com/88979298/159623139-e2cbf5a6-aea9-4f78-b861-6331e188e7a2.png)
![8DEFE695-37BA-4C95-BD70-33C4797272F7](https://user-images.githubusercontent.com/88979298/159623170-eb5a5d28-f3cc-478e-8a79-9b8d44068127.png)
Sorry, I didn't reply in time just now. It shows 'sidebar load failed'

**Comment by yyj1126** [comment]
Sorry, it seems to be the problem of my document. Problem is solved. Thank you a lot!

**Comment by yyj1126** [comment]
Wish better!

**Comment by windingwind** [comment]
Thanks for your patient debug!
I suggest you to provide your ducument with a debugID to the Zotero Forums, https://forums.zotero.org/discussions. 
I don't know if it is a bug with pdf.js or Zotero PDF Reader. The forums may know.
