### ISSUE TITLE
百度及有道词典的密钥

### ISSUE THREAD

**Issue by YS19970128** [windingwind/zotero-pdf-translate#171]
Zotero软件中的pdf translate插件翻译引擎需要密钥才能使用，希望平台提供百度及有道词典的密钥

**Comment by GrayXu** [comment]
单一密钥是限制QPS的，公用肯定容易被ban。注册一个很简单的。

**Comment by YS19970128** [comment]
关键我不会弄😭😭真的哭了，搞了好久了



---- 回复的原邮件 ----
| 发件人 | Gray ***@***.***> |
| 日期 | 2022年07月02日 17:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] 百度及有道词典的密钥 (Issue #171) |

单一密钥是限制QPS的，公用肯定容易被ban。注册一个很简单的。

**Comment by windingwind** [comment]
密钥超量需要付费，我没有钱来供用户免费使用。
注册方法见#20

**Comment by YS19970128** [comment]
好的，感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月02日 22:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] 百度及有道词典的密钥 (Issue #171) |

密钥超量需要付费，我没有钱来供用户免费使用。
注册方法见#20
