### ISSUE TITLE
[Bug]翻译抓取字符乱码

### ISSUE THREAD

**Issue by vagitablebirdcode** [windingwind/zotero-pdf-translate#172]
在翻译PDF的过程中，若PDF的文字内嵌了相关公式，则在翻译界面会显示为一个乱码字符，影响翻译结果。希望可以改进，谢谢！

**Comment by windingwind** [comment]
请提供具体问题的截图

**Comment by vagitablebirdcode** [comment]
![Snipaste_2022-07-02_22-46-09](https://user-images.githubusercontent.com/42081162/177005436-141f370d-65dc-469e-b769-eae4024f165b.png)

**Comment by windingwind** [comment]
这个没法自动更改，只能手动去除或者修改后重新翻译

**Comment by vagitablebirdcode** [comment]
好的知道了，那就自己多做几步了。我之前是使用知云辅助翻译，它的可以把数学符号转成文字类型的，但是他的阅读器体验不好，而且和其他软件是割裂的。您的插件除了这一点外，我可以放心的在zotero内部阅读，体验很好，感谢您的付出努力。

**Comment by windingwind** [comment]
这可能和pdf本身也有关系，大部分pdf的数学符号能够正常显示，但文本确实没法保持公式的原本语义。对翻译引擎来说，如何处理这些符号是黑箱的。仅仅作为辅助阅读，一般还是可以的
