### ISSUE TITLE
[Feature] support DeepL without key

### ISSUE THREAD

**Issue by GrayXu** [windingwind/zotero-pdf-translate#173]
This a great tool! But deepl free API key is hard to register in China :(

I found some translators like [EdgeTranslate/EdgeTranslate](https://github.com/EdgeTranslate/EdgeTranslate) can support deepl directly, without the need to specify an API key. And it seems to be using the web entrance. [related codes here](https://github.com/EdgeTranslate/EdgeTranslate/blob/master/src/background/library/translators/deepl.js#L35)

Is it possible add such feature to zotero-pdf-translate?

thanks!

**Comment by GrayXu** [comment]
of course EdgeTranslate is a brower plugin and easily do something like a spider.  
I just don't know can we implement this inside zotero. 🤔

**Comment by Nyquist24** [comment]
我申请到了API密钥，但还是用不了，显示
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon.
        Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403
求解

**Comment by windingwind** [comment]
@GrayXu 
To avoid possible legal problems, new translation engines must obey the official API rules.
You can do it yourself if you really need that.

**Comment by GrayXu** [comment]
I get it. Thanks
