### ISSUE TITLE
[Bug]我申请到了API密钥，但还是用不了，显示

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-pdf-translate#174]
我申请到了API密钥，但还是用不了，显示
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon.
        Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403
求解

_Originally posted by @Nyquist24 in https://github.com/windingwind/zotero-pdf-translate/issues/173#issuecomment-1173042392_

**Comment by windingwind** [comment]
请一个issue只讨论一个问题。
deepl对我来说正常。你确定你的secret正确填写并能够在官方客户端中使用吗？

**Comment by Nyquist24** [comment]
非常抱歉，确实应该另起一个Issue。
问题已经解决了，我的号是pro，这个插件应该用Api free，非常感谢，祝您生活愉快。

**Comment by windingwind** [comment]
支持free与pro，请选择对应的引擎

**Comment by Evaneena** [comment]
我申请到了API密钥，但还是用不了，显示
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Baidu*, not Zotero or the PDF Translate addon.
        52003:UNAUTHORIZED USER
