### ISSUE TITLE
翻译窗口能否控制横向宽度

### ISSUE THREAD

**Issue by takeiteasyman** [windingwind/zotero-pdf-translate#176]
作者您好！
在使用本翻译的过程中，发现如果翻译的字体调大并且翻译的句子过长，翻译窗口宽度会超出当前显示的范围，需要将视图向右边移动才能完整显示。
希望能控制翻译窗口的宽度，可以不限长度，使得翻译内容可以通过鼠标滚轮即可完整查看

**Comment by wj2392907320** [comment]
你好，请问如何调大翻译的字体呢

**Comment by Spring1547** [comment]
同问，字体太小了，如何调节字体大小

**Comment by Spring1547** [comment]
> 你好，请问如何调大翻译的字体呢
转到并设置字体大小。Edit->Preferences->PDF Translate->Advanced
