### ISSUE TITLE
翻译插件与night插件不兼容

### ISSUE THREAD

**Issue by hsumayun** [windingwind/zotero-pdf-translate#179]
使用night插件，翻译插件不工作、无翻译弹窗，只有高亮文本后才会在右侧出现翻译结果。关闭night插件后，恢复正常

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/179683452-dec84e95-de8c-4113-9cf4-c16a7055d296.png)
对我正常

**Comment by windingwind** [comment]
百度近期调整了接口限额，可以到百度账号的控制台看下是不是用量没了

**Comment by hsumayun** [comment]
您好，不好意思，提个小小建议，这个night模式能不能默认关闭，或者设置一个默认打开的开关，现在每次进去都是打开的，谢谢您发自我的手机-------- 原始邮件 --------发件人： windingwind ***@***.***>日期： 2022年7月19日周二 下午3:21收件人： windingwind/zotero-pdf-translate ***@***.***>抄送： hsumayun ***@***.***>, Author ***@***.***>主    题： Re: [windingwind/zotero-pdf-translate] 翻译插件与night插件不兼容 (Issue #179)

百度近期调整了接口限额，可以到百度账号的控制台看下是不是用量没了
