### ISSUE TITLE
Cannot Adjust！！！（Pop-up Window & Font Size）

### ISSUE THREAD

**Issue by xiaojiujiu999** [windingwind/zotero-pdf-translate#18]
1. the size of pop-up window
2. the font size on the right
![图片](https://user-images.githubusercontent.com/73394116/159613435-7abddd03-aba6-4d95-b59b-611e54c2cbc8.png)

wish better！

**Comment by windingwind** [comment]
Thanks. The sidebar font size bug will be fixed in the next update.
The popup resize is a little bit complex. I'll try to do it.

**Comment by windingwind** [comment]
v0.2.9 can resize popup automatically, making the resize function unnecessary.

**Comment by xiaojiujiu999** [comment]
So so so efficiency！！！Thank you very much to pay attention to my issue.
That's a good job！It has a great enhancement.
But, unfortunately, it still have two problems:
1. The pup-up window is small, cannot move, and  need to scroll through
2. The size of text box is fixed, so left a blank margin on the right
![图片](https://user-images.githubusercontent.com/73394116/159824662-e1f8d85d-ce33-4e63-8f8e-e3f7b5af054c.png) 
![图片](https://user-images.githubusercontent.com/73394116/159824106-27988206-6b30-4630-a1a3-3f608c1f2164.png)

About the first question, you may get some inspirations from [CopyTranslator](https://github.com/CopyTranslator/CopyTranslator) which is designed very well.

Thanks for your contributions!
With best wishes!

**Comment by windingwind** [comment]
Fixed in v0.3.0
