### ISSUE TITLE
有道接口有时候报错

### ISSUE THREAD

**Issue by yuhldr** [windingwind/zotero-pdf-translate#180]
```bash
[JavaScript Error: "HTTP GET http://fanyi.youdao.com/translate?&doctype=json&type=EN_US2ZH_CN&i=文本 failed with status code 500"]
```

![image](https://user-images.githubusercontent.com/25719023/179766254-f4fe7ca0-ff2d-4440-9592-50b3ad6bd71b.png)

**Environment**
 - OS: Windows/Linux
 - Zotero Version(6.0.10)
 - Addon Version(0.8.15)

有道翻译,偶然会有这个报错,一旦错了以后就一直错

之前我一个同学遇到过,但是我当时试了两台电脑,没有问题

今天我电脑上也报错了,好像是js错误,但是我没找到问题所在

**Comment by windingwind** [comment]
See #6. You might be banned temporarily by Youdao.
Use the Youdao Zhiyun for a more stable service.
