### ISSUE TITLE
[Bug]Translate版本0.8.16Deepl pro api翻译出错 403

### ISSUE THREAD

**Issue by Rain-Of-Stars** [windingwind/zotero-pdf-translate#181]
**Describe the bug**
使用Deepl pro中的api进行翻译时一直弹出如下错误，已经核实deepl pro可正常在win客户端、网页中使用（Zotero首选项中选择了正确的Deepl pro翻译引擎），在网页端账户内复制了“用于CAT工具插件的验证密钥”，应该没有缺失。
账号状态看起来是正常的，对账户内的Api也进行过重置以确保唯一性
![image](https://user-images.githubusercontent.com/58496516/180630561-b6f948a9-e63f-4621-b531-227163d11bf0.png)

 DeepL(Pro)*.
Error: HTTP POST https://api.deepl.com/v2/translate failed with status code 403

**To Reproduce**
所有插件内的翻译场景均会触发（划词、注释翻译等）

**Expected behavior**
如何解决403问题

**Screenshots**
![image](https://user-images.githubusercontent.com/58496516/180629912-c106ea86-616b-474f-95e0-d435a600e41d.png)

**Environment**
 - OS: Windows11
 - Zotero Version：6.0.10
 - Addon Version：0.8.16

**Additional context**
感谢作者！

**Comment by windingwind** [comment]
我没有pro账号不是很确定，但可能不是“用于CAT工具插件的验证密钥”。按照deepl的文档，它的英文是authkey，请看下是否是使用的密钥不对

**Comment by windingwind** [comment]
我没有pro账号不是很确定，但可能不是“用于CAT工具插件的验证密钥”。按照deepl的文档，它的英文是authkey，请看下是否是使用的密钥不对

**Comment by windingwind** [comment]
我看了下deepl提供两类订阅，一类是称为”针对个人或团队“是面向其提供的客户端的，一类是称为deepl api的，只有后者具有使用api进行翻译的权限。看起来你的订阅是前者。

**Comment by Rain-Of-Stars** [comment]
> 我看了下deepl提供两类订阅，一类是称为 "针对个人或团队 "是面向其提供的客户端的，一类是称为deepl api的，只有后者具有使用api进行翻译的权限。看起来你的订阅是前者。

您这样描述我也不是很确定了，认识的一个朋友，之前也是这个订阅，用的“"用于CAT工具插件的验证密钥”下面的提供的密钥，可以在插件中选择pro正常使用，突然不能用了（2022.07.21）

**Comment by windingwind** [comment]
近期修复了pro接口错误使用了free版本接口的问题，可能因此突然用不了。deepl的两套订阅是分开的，也许你只有个人团队版本的pro，但没有api版本的pro。尝试切换到free的接口看看？

**Comment by Rain-Of-Stars** [comment]
> 近期修复了pro接口错误使用了free版本接口的问题，可能因此突然用不了。deepl的两套订阅是分开的，也许你只有个人团队版本的pro，但没有api版本的pro。尝试切换到free的接口看看？

原来是这样，感谢您的耐心回复，以及对插件的不断支持。
