### ISSUE TITLE
[Feature] 希望在阅读翻译时，可以通过按钮/快捷键操作：生成当前注释的新注释笔记。

### ISSUE THREAD

**Issue by shliujing** [windingwind/zotero-pdf-translate#182]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
具体：
1. 需求，阅读翻译到一定程度时，希望可以快速生成当前新标注的注释笔记
2. 设置，新的注释笔记，可以在"设置-Translate"中勾选，是否“自动删除旧笔记”
3. 操作，在阅读翻译的UI界面，或通过“2. 设置"中设置的快捷键完成操作

需求背景，我使用obs记录文献笔记会引用到zotero中的注释笔记，所以日常更新操作频繁。
如果能加上这个功能，会极大提高阅读和记笔记效果。

**Describe alternatives you've considered**
1. 按钮改成快捷键
2. 按钮改成“PDF内置阅读器 - Translate面板"上的一个设置按钮

**Additional context**
一些UI界面上设置的考虑：

1. 设置是否删除旧注释笔记。
逻辑要判断“注释笔记”和手动创建的“笔记”。
![](http://i.iamlj.com/win/20220726075624.png)

2. 操作按钮，可选设置处
![](http://i.iamlj.com/win/20220726075847.png)

3. 可选，设置生成注释笔记快捷键
![](http://i.iamlj.com/win/20220726075955.png)

**Comment by windingwind** [comment]
注释笔记指的是什么呢？

**Comment by dentistfrankchen** [comment]
非常同意上面的说法。现在你们的“添加笔记”需要点击。楼主的意思是让您们增加一个用于直接添加的快捷键，这样就不需要点击了。笔记多的时候，点击鼠标很费时间。

**Comment by windingwind** [comment]
我不清楚具体指的是什么，也许可以参阅https://github.com/windingwind/zotero-better-notes.
这是专用于笔记的一个插件。
由于功能请求与本插件关系不大，故此关闭。可在上述仓库中进一步讨论。

**Comment by shliujing** [comment]
之前漏消息了。

注释笔记是这样的，右键生成。
![](http://i.iamlj.com/win/20220802105500.png)

这个可以用obsidian笔记软件的bibnote插件，串联zotero里的笔记和元数据做笔记。和你引用的better notes差不多的功能。

那就先放着吧，的确和翻译关系不大

**Comment by windingwind** [comment]
@shliujing 
better notes是我的另一个插件，可以通过自定义的模板将条目中的注释以自定义条件筛选/整合批量导入笔记中，与你说的需求符合

**Comment by shliujing** [comment]
@windingwind 已用，感谢
