### ISSUE TITLE
[Bug]弹窗显示“添加翻译笔记”无法正常显示

### ISSUE THREAD

**Issue by fan291752035** [windingwind/zotero-pdf-translate#183]
作者大大您好
在右侧笔记打开的情况下，改弹窗无法显示
![image](https://user-images.githubusercontent.com/73932884/180902954-e3339441-07f1-47c9-8c61-76c620392548.png)
![image](https://user-images.githubusercontent.com/73932884/180902988-54f2f500-2a6c-4ebb-8b1c-d712afdcb7e8.png)

**Comment by windingwind** [comment]
请完整截图？

**Comment by windingwind** [comment]
请完整截图整个屏幕

**Comment by fan291752035** [comment]
![image](https://user-images.githubusercontent.com/73932884/180912197-c4088dc6-86c2-4c7c-9fa7-007fa255298c.png)

**Comment by windingwind** [comment]
没有打开的笔记内容。请在右侧选择一个笔记打开，或创建一个笔记

**Comment by fan291752035** [comment]
好的，明白了，谢谢
