### ISSUE TITLE
[Feature] 在夜间模式或护眼模式下，希望图片可以显示原始的色彩

### ISSUE THREAD

**Issue by verigle** [windingwind/zotero-pdf-translate#184]
在夜间模式下， 图片也会以反色显示，这样图片看起来会怪怪的

在夜间模式或护眼模式下，希望图片可以显示原始的色彩

希望设置中可以增加 图片显示的选项：图片是否保持原始色彩显示

**Additional context**
夜间模式下图片怪异显示效果
![image](https://user-images.githubusercontent.com/32769358/181764517-483a8179-e5ac-484e-b435-46382255adc6.png)
图片正常显示效果
![image](https://user-images.githubusercontent.com/32769358/181764801-1d279cbf-b3df-4d95-84b7-4421c2590c06.png)

**Comment by windingwind** [comment]
这似乎和本插件无关。
