### ISSUE TITLE
希望翻译弹窗的窗口可调节

### ISSUE THREAD

**Issue by yanyu2015** [windingwind/zotero-pdf-translate#185]
希望翻译弹窗的窗口可调节
有时候我这边跳出来的翻译结果窗口很狭长，十分不方便。如图
![image](https://user-images.githubusercontent.com/11142054/182340963-a61edb4b-e46a-4b72-b07a-8c500f296a77.png)

**Comment by windingwind** [comment]
已支持调整大小

**Comment by yanyu2015** [comment]
感谢，已经试用。在试用的基础上，想再次提出个改进建议，就是在我已经修改了窗口大小后，下次再弹出能否以上次设置的窗口大小为准？不然每次都要调整还是有点繁琐的
