### ISSUE TITLE
希望在右侧翻译界面增加“暂停翻译功能”的功能，方便临时想保留翻译结果

### ISSUE THREAD

**Issue by CMD-cmd** [windingwind/zotero-pdf-translate#186]
希望在右侧翻译界面增加“暂停翻译功能”的功能，方便临时想保留翻译结果
可能应用场景：选中一段自动在右侧显示翻译结果，这时希望右侧翻译结果暂时保留，同时在左侧文献界面划高亮，而不会影响右侧的整段翻译结果

**Comment by windingwind** [comment]
侧边栏增加一个“自动翻译”的开关是否可以？

**Comment by CMD-cmd** [comment]
对的对的，就是这个意思
