### ISSUE TITLE
[Feature]能不能增加一个打开/关闭首选项中“自动翻译批注”功能的快捷键

### ISSUE THREAD

**Issue by whyihaveyou** [windingwind/zotero-pdf-translate#187]
感觉自动把勾选内容翻译并添加到批注这个功能很实用，但有时候又不希望打开这个功能，单纯只是想高亮文本。而切换只能进入编辑-首选项-translate-自动翻译批注，需要点击多次。切换这个功能的次数感觉真的挺多的，如果能够用快捷键实现就太好了。

**Comment by windingwind** [comment]
可关闭自动翻译批注后，使用左侧边栏批注视图中的翻译按钮进行单个批注的翻译。
