### ISSUE TITLE
希望能给弹窗写入权限，方便选中需要的文字保存到笔记，而不是点击了复制整个再去添加标记，这样很麻烦，因为我是个懒人。谢谢攻城狮

### ISSUE THREAD

**Issue by 754932057** [windingwind/zotero-pdf-translate#188]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
当右侧栏有笔记打开时，选中文本即会有“添加到笔记”按钮。这是自带功能

**Comment by 754932057** [comment]
您可能没有明白我的意思，对此我真的很抱歉，我想说的是：当我在整段反的时候看到弹窗里有一句话，对我很有用，我想摘抄下来，但是，我点击了弹窗里的内容，他会一整段都复制，然后才能在笔记里显示一整段的内容，我还要在笔记里查找一遍，再标记颜色，我觉得这样很影响看文献的效率，所以我才提出这个建议，希望您能理解，谢谢攻城狮啦，好人一生平安！祝好！

**Comment by 754932057** [comment]
> 当右侧栏有笔记打开时，选中文本即会有“添加到笔记”按钮。这是自带功能

您可能没有明白我的意思，对此我真的很抱歉，我想说的是：当我在整段反的时候看到弹窗里有一句话，对我很有用，我想摘抄下来，但是，我点击了弹窗里的内容，他会一整段都复制，然后才能在笔记里显示一整段的内容，我还要在笔记里查找一遍，再标记颜色，我觉得这样很影响看文献的效率，所以我才提出这个建议，希望您能理解，谢谢攻城狮啦，好人一生平安！祝好！

**Comment by windingwind** [comment]
意思是希望能够单独复制翻译结果弹窗中的部分文字吗？侧边栏的翻译源文本与结果都可以编辑或部分选中

**Comment by 754932057** [comment]
> 当右侧栏有笔记打开时，选中文本即会有“添加到笔记”按钮。这是自带功能

对于这个功能我的启发是通过沙拉查词的读写权限功能，因为我常用zotero加沙拉查词这个插件组合一起看文献，他就能直接选中弹窗中的一句话，然后拖入笔记中就好了，我感觉这样效率满满

**Comment by windingwind** [comment]
明白了，将会在下一版本支持部分选中文本

**Comment by 754932057** [comment]
> 意思是希望能够单独复制翻译结果弹窗中的部分文字吗？侧边栏的翻译源文本与结果都可以编辑或部分选中

您说的这个功能我知道的，但是这样回来会切换窗口，影响阅读的连贯性，如果把侧边栏作为独立窗口，又会遮挡文献和笔记内容，这样很影响阅读体验

**Comment by 754932057** [comment]
> 明白了，将会在下一版本支持部分选中文本

谢谢您，希望能理解我的意思并采纳，加油攻城狮，别太熬夜哦，愿您能有一头茂密的头发，哈哈哈

**Comment by 754932057** [comment]
> 明白了，将会在下一版本支持部分选中文本

抱歉，大清早又来打扰您了，希望能在弹窗里也添加一个拼页选取的功能，希望您能够采纳我的建议，当然为了您的健康，我也什么都可以接受，谢谢攻城狮了。

**Comment by windingwind** [comment]
@754932057 
拼接选取按住alt，或在右侧栏中勾选启用

**Comment by 754932057** [comment]
好的，谢谢您，我已知晓




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月6日(星期六) 上午9:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [windingwind/zotero-pdf-translate] 希望能给弹窗写入权限，方便选中需要的文字保存到笔记，而不是点击了复制整个再去添加标记，这样很麻烦，因为我是个懒人。谢谢攻城狮 (Issue #188)



@754932057
 拼接选取按住alt，或在右侧栏中勾选启用

**Comment by 754932057** [comment]
> @754932057 拼接选取按住alt，或在右侧栏中勾选启用

您好啊， 谢谢您的更新，但是还是 有问题，自动弹出的翻译框虽然能选中内容了，但是依然不能拖动到笔记中，希望能在修改下代码

**Comment by 754932057** [comment]
> @754932057 拼接选取按住alt，或在右侧栏中勾选启用

不知道是什么原因，复制翻译弹出里的内容粘贴到笔记时还是显示的英文的，而不是翻译后的中文。
