### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by wangdh96** [windingwind/zotero-pdf-translate#190]
Hi，sir！
Can we make the translation software calls the terminology database information to increase the accuracy of translation.

NiuTrans Terminology Glossary

Add a terminology library

![image](https://user-images.githubusercontent.com/110912935/183657139-9fd4f279-994a-48dd-899d-84ad27ed8464.png)

**Comment by windingwind** [comment]
已支持，具体参数格式见readme
