### ISSUE TITLE
最新版本翻译完后，点击在翻译文本框不能将翻译文本复制到剪贴板了

### ISSUE THREAD

**Issue by YunDingXie** [windingwind/zotero-pdf-translate#191]
**Is your feature request related to a problem? Please describe.**
与问题相关，最新版本翻译完后，点击在翻译文本框不能将翻译文本复制到剪贴板了。这个功能挺实用的，现在的最新版本只能将原文和译文一起添加到笔记里面
**Describe the solution you'd like**
保留之前老版本的这个功能
**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
已修复

**Comment by SSlovely** [comment]
Do I need to double-click now to copy?

**Comment by windingwind** [comment]
> Do I have to double click to copy it?

Yes. The single click is to modify the text inside popup and the double click select all text and copy them.

**Comment by SSlovely** [comment]
ok thanks
