### ISSUE TITLE
[Feature]建议增加一下调整行间距的功能

### ISSUE THREAD

**Issue by MagicYuze** [windingwind/zotero-pdf-translate#192]
在调整翻译字体大小后，如果把整段文字翻译，就会显得密密麻麻。

希望能增加一个调整行间距的功能。这样能根据用户自身需要调整。

**Comment by windingwind** [comment]
已计划

**Comment by windingwind** [comment]
已支持。
![image](https://user-images.githubusercontent.com/33902321/189938042-21eeb350-1471-4b1b-acb2-7d41d007cdf6.png)
