### ISSUE TITLE
字典引擎能否支持本地词库

### ISSUE THREAD

**Issue by beckybecky111** [windingwind/zotero-pdf-translate#194]
如题，能否支持诸如mdd等本地词典，在网络质量较差的情况下也能够流畅地使用
As described in title, can you support local dictionary, so that  we can get translation when the network quality is poor.

**Comment by windingwind** [comment]
是否有相关本地词典获取或使用的文档或参考资料？

**Comment by sensty** [comment]
大佬你看这个行不行
一个支持mdd格式的词典软件
https://github.com/xiaoyifang/goldendict
这个仓库有相关的词典文件
https://github.com/OrcheInk/english-dictionary
mdd和mdx格式分析
https://github.com/csarron/mdict-analysis

**Comment by windingwind** [comment]
感谢分享。我简单调研了一下mdict在js上实现的相关包，似乎很不完全。支持浏览器的代码只有一个7年前的：https://github.com/fengdh/mdict-js
其余的包大多在node环境下。
根据代码大致看了一下，词典文件内部使用的lzo压缩格式似乎没有很好支持浏览器的包，要么需要打包二进制分发（意味着可能无法跨平台），要么依赖nodejs。
> .. note:: python-lzo is required to read mdx files created with engine 1.2
也许暂时放弃对这类文件的支持比较好？
其余部分尚在尝试。

**Comment by windingwind** [comment]
本地词库似乎无法通过纯js的方式支持（或至少很困难）。我将保留该issue开启，但暂时将不会在这方向尝试。

**Comment by windingwind** [comment]
关闭issue，因为无计划支持。

**Comment by contrun** [comment]
能否支持程序化地运行某个命令？我希望能直接运行 goldendict "test"，或者打开 goldendict://test
