### ISSUE TITLE
Hope to add the function of cross page translation

### ISSUE THREAD

**Issue by CigarOVO** [windingwind/zotero-pdf-translate#197]
能否实现跨页翻译？想要类似于知云翻译那种，按住某个快捷键可以选择特定文本拼接的翻译功能。因为如果直接拖拽跨页翻译会将页眉页脚很多不必要的信息一起翻译。

**Comment by windingwind** [comment]
提问前请看文档
https://github.com/windingwind/zotero-pdf-translate#qa
