### ISSUE TITLE
[Bug]DeepL API出错

### ISSUE THREAD

**Issue by agangkeyi** [windingwind/zotero-pdf-translate#198]
**Describe the bug**
DeepL API突然无法正常使用（前一秒还在继续翻译，后一秒就显示error了）

**To Reproduce**
[Request Error]

Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: 
 https://github.com/windingwind/zotero-pdf-translate/issues 

The message below is not Zotero or the PDF Translate addon,  but from  

 DeepL(Free)*.
Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 456

**Environment**
 - OS: macOS
 - Zotero Version(6.0.12)
 - Addon Version(Tools->Add-ons)

谢谢！

**Comment by windingwind** [comment]
Quota exceeded. The character limit has been reached.

https://www.deepl.com/zh/docs-api/accessing-the-api/error-handling/
