### ISSUE TITLE
Deepl free version API is not working [Bug]

### ISSUE THREAD

**Issue by Echo-Bong** [windingwind/zotero-pdf-translate#199]
**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Describe the bug**
I cannot use the deepl free version translator.

**To Reproduce**
1. Go to: any pdfs
2. Click on: select several sentences
3. Scroll down to: translate
4. See error: 
-------------------------------------------------------------
[Request Error]

Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: 
 https://github.com/windingwind/zotero-pdf-translate/issues 

The message below is not Zotero or the PDF Translate addon,  but from  

 DeepL(Free)*.
Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403
-------------------------------------------------------------
**Expected behavior**
The selected sentences are to be translated into Chinese.

**Screenshots**
<img width="627" alt="image" src="https://user-images.githubusercontent.com/35946527/185770584-1874ed80-f14c-47e3-9dd7-36262e02a370.png">

**Environment**
 - OS: macOS
 - Zotero Version: 6.0.12
 - Addon Version: 0.8.22

**Comment by windingwind** [comment]
Please make sure the secret is correct and valid.

**Comment by Echo-Bong** [comment]
Thank you so much! It solved my problem.
