### ISSUE TITLE
Changing the translate engine from Google Translate to Microsoft resets the language parameter string 

### ISSUE THREAD

**Issue by dwl-sdca** [windingwind/zotero-pdf-translate#2]
Unless I'm doing something wrong, changing the translate engine seems to reset the language parameter to the default setting. I'd like my source and tl= language to be retained. Is this possible?

**Comment by windingwind** [comment]
Thanks! 
I'm right now working on a new feature of automatically generating the language parameter string. With this feature, you can just choose your target language from list. I'll @ you once it's ready!

**Comment by windingwind** [comment]
@dwl-sdca Solved.
