### ISSUE TITLE
各api接口申请示例

### ISSUE THREAD

**Issue by Undifinedu** [windingwind/zotero-pdf-translate#20]
[这里](https://doc.tern.1c7.me/zh/folder/setting/)给了各个平台的api申请示例，如有需要可以参照这里。

**Comment by windingwind** [comment]
Thanks!
This issue is added to the pinned #6 and I'll close it.

**Comment by Quin-Yim** [comment]
deepl-free api 域名不对，应该是：https://www.deepl.com/docs-api

**Comment by windingwind** [comment]
> deepl-free api 域名不对，应该是：https://www.deepl.com/docs-api

You mean the document, or this addon?

**Comment by Quin-Yim** [comment]
> > deepl-free api 域名不对，应该是：https://www.deepl.com/docs-api
> 
> You mean the document, or this addon?


your code:
deeplfree: async function () {
      return await this.deepl("https://api-free.deepl.com/v2/translate");
    },
    deeplpro: async function () {
      return await this.deepl("https://api.deepl.com/v2/translate");

the above free link should be: https://www.deepl.com/docs-api

**Comment by windingwind** [comment]
> > > deepl-free api 域名不对，应该是：https://www.deepl.com/docs-api
> > 
> > 
> > You mean the document, or this addon?
> 
> your code: deeplfree: async function () { return await this.deepl("https://api-free.deepl.com/v2/translate"); }, deeplpro: async function () { return await this.deepl("https://api.deepl.com/v2/translate");
> 
> the above free link should be: https://www.deepl.com/docs-api

Not exactly. `/doc-api` is a document page. I developed and tested the API according to DeepL Doc.
![image](https://user-images.githubusercontent.com/33902321/159702880-c2f3ebb3-c89e-46ba-af07-10f96bb90183.png)

And, it work well with me.

**Comment by zyszly** [comment]
怎样才能有Deepl 的秘钥呢

**Comment by ttkx123** [comment]
请问你们知道为什么我才申请的百度翻译的密钥，才用了一天，zotero就显示受限，密钥无效

**Comment by appw-cn** [comment]
自己的DeepL Free API好像也不能用

**Comment by windingwind** [comment]
> 自己的DeepL Free API好像也不能用

我始终可用。

**Comment by appw-cn** [comment]
> > 自己的DeepL Free API好像也不能用
> 
> 我始终可用。

唉呀，被歧视了……
我的步骤是：
1. 在https://www.deepl.com/docs-api页面，找到DeepL API Free\HTTP Request中，这行代码
```
POST /v2/translate?auth_key=12345678-1234-1234-1234-123456789abc:fx> HTTP/1.0
Host: api-free.deepl.com
User-Agent: YourApp
Accept: */*
Content-Length: [length]
Content-Type: application/x-www-form-urlencoded

auth_key=12345678-1234-1234-1234-123456789abc:fx&text=Hello, world&target_lang=DE
```
2. 把12345678-1234-1234-1234-123456789abc:fx粘到zotero设置的DeepLFree*里面
3. 结果显示：
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon.
        Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403

**Comment by XiangYeTan** [comment]
您好！我已经申请了百度api的账号和密钥并按照您的方法（ID#SERECT）将翻译设置为“百度*”,选中文字翻译时会提示一下问错误：
[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from Baidu*, not Zotero or the PDF Translate addon.
        52003:UNAUTHORIZED USER

**Comment by windingwind** [comment]
> 你好，您的这个插件非常好用，我之前用deepl free的时候用得很好，用量用完之后我就想试试deepl pro api，但是之后就会显示 [请求错误]
> 
> 此翻译引擎不可用,可能是密钥错误,也可能是请求过快 可以尝试其他翻译引擎,或者来此查看相关回答: https://github.com/windingwind/zotero-pdf-translate/issues
> 
> 请注意,这些错误与zotero和此翻译插件无关! 错误详情如下:
> 
> DeepL(Pro)*. Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 456
> 
> 我在想是不是因为pro这边用的也是free的deepl的api站点所以失败的呢？

已修复

**Comment by windingwind** [comment]
> 您好！我已经申请了百度api的账号和密钥并按照您的方法（ID#SERECT）将翻译设置为“百度*”,选中文字翻译时会提示一下问错误：
> [Request Error]
> Engine not available, invalid secret, or request too fast.
> Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
> The message below is from Baidu*, not Zotero or the PDF Translate addon.
> 52003:UNAUTHORIZED USER

请确认百度账号开通了对应翻译服务，类别正确，且服务已激活，且有余量。请截图上述内容

**Comment by Yinghui0121** [comment]
经测试，百度API和DeepL free API都反馈下列错误，可否修复呢

[Request Error]
Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues
The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon.
        Error: Request timed out

**Comment by windingwind** [comment]
> 经测试，百度API和DeepL free API都反馈下列错误，可否修复呢
> 
> [Request Error] Engine not available, invalid secret, or request too fast. Use another translation engine or post the issue here: https://github.com/windingwind/zotero-pdf-translate/issues The message below is from DeepL(Free)*, not Zotero or the PDF Translate addon. Error: Request timed out

见 #6 .是你的网络问题或密钥问题，我使用正常

**Comment by Windy-wjf** [comment]
你好，经测试，有道智云无法使用，按照教程，申请密钥之后还会有一个应用ID，但是插件上面没找到地方填，仅填上密钥无法正常使用，会提示：
 有道智云*.
Error: errorCode: 108

**Comment by windingwind** [comment]
> 你好，经测试，有道智云无法使用，按照教程，申请密钥之后还会有一个应用ID，但是插件上面没找到地方填，仅填上密钥无法正常使用，会提示：
> 有道智云*.
> Error: errorCode: 108

请按照readme格式完整规范填写需要的字段

**Comment by allthingsluck** [comment]
你好，我所有的翻译引擎都用不了，显示以下错误
此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 有道智云*.
Error: 连接至服务器时发生错误。请检查网络连接。

**Comment by windingwind** [comment]
@allthingsluck 请确认网络连接。带星号需要密钥

**Comment by mayii2001** [comment]
[v0.8.22]的有道翻译不填密钥时无法翻译

**Comment by windingwind** [comment]
> [v0.8.22]的有道翻译不填密钥时无法翻译

免费接口不稳定，请使用有道智云

**Comment by lan-slot** [comment]
免费的谷歌（中国可用）翻译为啥不太准呢？

**Comment by Windy-wjf** [comment]
> 免费的谷歌（中国可用）翻译为啥不太准呢？

那是谷歌翻译本身的问题，翻译单词还行，翻译长文的时候逻辑很差。

**Comment by WillWillLu** [comment]
你好，我今天用deepl Pro api的时候一直会跳出这个。
![屏幕截图 2022-10-16 192026](https://user-images.githubusercontent.com/99693502/196051579-fa412b89-552e-4858-a7e1-647e8647de07.png)

我看了一下我的密匙是对的，然后点完ok之后也是能翻译的。但是每次在选择完需要翻译的句子之后就会跳出这个出来
