### ISSUE TITLE
[Bug]Microsoft API request method changed?

### ISSUE THREAD

**Issue by everxq** [windingwind/zotero-pdf-translate#200]
**Describe the bug**

_Microsoft Translate not working._

**To Reproduce**

_I tried API key 1 an key 2 respectively, and found only [Request Error]._ 

_The returned message from Mirosoft indicated {"error":{"code":405000,"message":"The request method is not supported for the requested resource."}}_

_https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=zh-CN failed with status code 401_

**Expected behavior**

_Perhaps, it needs updating._

**Screenshots**
![image](https://user-images.githubusercontent.com/26721844/185779937-a42627e3-98b9-4174-a3dc-27650cdfd2ff.png)

**Environment**

 _- OS: Windows 11 Pro 21H2_
 _- Zotero Version 6.0.12_
 _- Addon Version 0.8.22_

**Comment by windingwind** [comment]
Please check:
1. What is the service you are using in MS Azure console? It should look like this:
![image](https://user-images.githubusercontent.com/33902321/185780470-83ddb843-f706-457e-b07c-71f592d7855e.png)

2. Make sure you set the region right and it is active. Use the 'try it' in the Azure console and see if it works.

**Comment by everxq** [comment]
Thanks! Solved by changing location from US to Global ...
