### ISSUE TITLE
所有的翻译引擎都不能用了，显示网络问题。

### ISSUE THREAD

**Issue by allthingsluck** [windingwind/zotero-pdf-translate#202]
每次翻译都是这样：
[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 百度*.
Error: 连接至服务器时发生错误。请检查网络连接。

**Comment by windingwind** [comment]
1. 确定是否正确填写密钥
2. 确定是否正确联网
3. 确定是否有代理等设置导致上不去网

**Comment by allthingsluck** [comment]
> 

感谢感谢，是因为代理设置导致上不去网，现在已经解决了。
