### ISSUE TITLE
希望实现个性化UI

### ISSUE THREAD

**Issue by kong-chen123** [windingwind/zotero-pdf-translate#203]
### 1、希望能够修改字体
目前默认的翻译显示字体应该是宋体，希望能够增加切换字体选项，个人认为微软雅黑可能会更好看一点。
### 2、希望能够保持上次设置的翻译框宽度。
目前显示的翻译框太窄了，每次调整大小后，下次翻译又变窄了，所以希望能每次手动调整宽度后，以后翻译能够保持之前设置的宽度。

**Comment by windingwind** [comment]
已计划
