### ISSUE TITLE
[Bug]Google翻译不能使用，但是Google API可以使用

### ISSUE THREAD

**Issue by realHongYuZhou** [windingwind/zotero-pdf-translate#204]
虽然谷歌API可以使用，但是谷歌API翻译的结果和谷歌翻译网站的结果有太大差距，所以想使用Google引擎，但是不论是否开启VPN，一直有请求超时的错误

zotero pdf translate 0.8.22
zotero 6.0.13
OS WIN11

[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 谷歌.
Error: Request timed out

**Comment by windingwind** [comment]
这两个接口应该使用的是同一个服务。谷歌可能通过启发式方法检测用户是否来自其客户端，并对非网页/客户端的访问结果予以劣化。
如果要使用完整的谷歌翻译API：https://cloud.google.com/translate/pricing，注册赠金$300，每月$10限制50w字符，即只可免费试用1500w以下字符，相比国内其他翻译服务免费的量很少。是否确实有使用这个API的需求？

**Comment by realHongYuZhou** [comment]
好的，谢谢您

**Comment by windingwind** [comment]
如果没有对上面提到的接口的需求，将不会为其提供支持。
