### ISSUE TITLE
请问标题翻译完成后，前面都会出现一个蓝色小方块内写着abc，英文标题也变成中文，需要点一下又恢复英文，是什么情况呢

### ISSUE THREAD

**Issue by liangx15** [windingwind/zotero-pdf-translate#205]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题。如果不详细说明通过什么步骤可以复现问题，具体表现是什么，你正在使用哪个版本的插件，我没办法帮到你。不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows/macOS/Linux
 - Zotero Version(Help->About Zotero)
 - Addon Version(Tools->Add-ons)

**Additional context**

**Comment by windingwind** [comment]
1. 蓝色emoji字符用于表示该内容已经翻译过。下次调用翻译标题时不会再消耗流量；且用于表示目前查看的标题栏是翻译结果，而非原标题。
2. 翻译完成以后标题变成中文翻译结果是正常的。
3. 点一下会恢复原标题也是正常的。
