### ISSUE TITLE
[Bug]Complete the Title Here

### ISSUE THREAD

**Issue by zhuxy1103** [windingwind/zotero-pdf-translate#207]
请问使用插件进行翻译时，显示：擎不可用，秘密无效，或请求太快。
请考虑使用其他翻译引擎或在这里发布问题:https://github.com/windingwind/zotero-pdf-translate/issues
错误:请求超时
从8.27日到目前为止都不能正常使用翻译，请问是什么错误呢？
谢谢您的回复！

**Comment by windingwind** [comment]
8.27至今没有更新过插件，因此是你网络的问题。请检查是否错误设置了代理。
谷歌在部分地区无法访问

**Comment by zhuxy1103** [comment]
> 8.27至今没有更新过插件，因此是你网络的问题。请检查是否错误设置了代理。 谷歌在部分地区无法访问
您好，不知如何查看是否错误设置了代理，对这方面不是特别了解，谢谢解答

**Comment by windingwind** [comment]
不清楚具体原因，但应该是你的网络问题。所有翻译引擎都用不了吗？

**Comment by zhuxy1103** [comment]
您好，只有Google(API)可用，其他都不可用

**Comment by windingwind** [comment]
能用就行。带星号的需要填写密钥，详见主页

**Comment by zhuxy1103** [comment]
好的，谢谢
