### ISSUE TITLE
翻译窗口位置问题

### ISSUE THREAD

**Issue by pekideer** [windingwind/zotero-pdf-translate#209]
翻译时由于篇幅等问题，窗口的某部分会显示在屏幕之外，如果要看到完整的翻译就需要拉滚动条。是否可以改善这个情况，即翻译窗口能确保在显示屏幕之内完整显示？

**Comment by windingwind** [comment]
翻译内容较多时，无法保证长宽两方都一定在屏幕内。目前自适应尽量保证宽度不超过屏幕。
与#203 相关，将引入一个选项，用于保持上一次翻译框的长宽。

**Comment by windingwind** [comment]
见#203，已支持。
