### ISSUE TITLE
是否可以支持手动点击来确定翻译？

### ISSUE THREAD

**Issue by lartpang** [windingwind/zotero-pdf-translate#21]
当前版本中，选择文本后，对于仅仅只是为了添加颜色的情况下，翻译的自动弹窗略显多余，并且还会带来不必要的翻译请求。

![image](https://user-images.githubusercontent.com/26847524/159619981-6ef3ea09-c617-4b39-a147-404b204f3a2b.png)

不知是否可以支持手动点击来确定翻译的形式？

**Comment by windingwind** [comment]
Thanks for your advice!
I will add this feature in the future release.

**Comment by windingwind** [comment]
v0.2.7 should solve this issue.
![image](https://user-images.githubusercontent.com/33902321/159634758-a123c6c1-5715-4e9d-981f-f568e5582b09.png)

**Comment by lartpang** [comment]
Nice! Thanks for your work!
