### ISSUE TITLE
[Feature] Adding the variation of Dictionary for single word translation

### ISSUE THREAD

**Issue by uraxurax** [windingwind/zotero-pdf-translate#210]
I want to use English to Japanese dictionary in Dictionary for single word translation because I'm Japanese, 
However, I cannot use it because Dictionary for single word supports only  en2zh and en2en now.

If possible, I want to request to add English to Japanese dictionary.

Regards, hiro

**Comment by windingwind** [comment]
Hi, any suggestions for the en2ja translation service? I don’t know which services you want to use.

Is it accessible in browser directly, like Google Translate, or require login?

**Comment by uraxurax** [comment]
Hi, thank you fro your reply.

Is it acceptable weblio(https://ejje.weblio.jp/)?
User can use en2ja dictionary on it without logging in.

For example, User can get the meaning of **translation** by following URL.

https://ejje.weblio.jp/content/translation

Regards,
hiro

**Comment by windingwind** [comment]
Thanks, that's nice! I'll add it to the next release soon.

**Comment by uraxurax** [comment]
Dear windingwind,

Thank you for your quick update.
I test the update and It works perfect.

Regards,
hiro

**Comment by windingwind** [comment]
Glad to know it works 😄
Have a nice day!
