### ISSUE TITLE
[Bug] 闪退现象

### ISSUE THREAD

**Issue by kevinzhangcode** [windingwind/zotero-pdf-translate#211]
**Describe the bug**
升级到`MacOS12.6`，再次使用插件出现多次翻译导致出现Zotero闪退现象，尝试从`0.8.23`降级到`0.8.22`，仍然出现翻译导致zotero闪退。

查看错误日志：
<img width="997" alt="image" src="https://user-images.githubusercontent.com/38588781/190332421-d8bc65e1-3636-48f9-83bc-6fda10285f0c.png">

查看Error Console
<img width="629" alt="image" src="https://user-images.githubusercontent.com/38588781/190332086-17c1b3fd-097c-4ad9-b8c0-efde0ad3b0a0.png">

**Expected behavior**
翻译正常进行

**Screenshots**
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/38588781/190334539-84af1738-dde3-455e-8fa4-1f25703606a2.png">
**Environment**
 - OS: macOS
 - Zotero Version: 6.0.13
 - Addon Version: 0.8.23

**Comment by windingwind** [comment]
你好，我不确定具体的原因。可以麻烦提供更详细信息吗？包括：
1. 崩溃发生时，正在执行什么操作？是否每次崩溃都发生在特定的操作时？
2. 崩溃的情况是卡住无响应一段时间后退出，还是直接闪退？
3. 启用了其他什么插件？（如有可能，禁用其他所有插件后是否还会发生？禁用全部插件后是否还会发生？）
4. （如有可能）运行时Zotero占用了多大的内存，如果重复打开-关闭pdf数次，是否内存占用不断升高，或者关闭pdf后恢复到刚启动的占用量？

由于是在操作系统升级后产生的问题，也可能是Zotero本身存在兼容性问题。需要进一步了解具体情况，谢谢！

**Comment by kevinzhangcode** [comment]
@windingwind 感谢帮助！提供的具体信息如下：

> Q1. 崩溃发生时，正在执行什么操作？是否每次崩溃都发生在特定的操作时？
>> **A1. 崩溃发生，正在使用选择工具指定文字翻译；每次奔溃都在执行选择文字翻译的时候。**

> Q2. 崩溃的情况是卡住无响应一段时间后退出，还是直接闪退？
>> **A2. 崩溃发生，直接闪退，并没有出现卡住的现象（个人每次都碰见直接闪退）**

> Q3. 启用了其他什么插件？（如有可能，禁用其他所有插件后是否还会发生？禁用全部插件后是否还会发生？）
> **A3. 如图所示，其中2、3是官方自带插件，尝试关闭BetterNotes插件，翻译测试一段时间正常，尝试同时打开BetterNotes和翻译插件，一段时间后即闪退，CPU利用异常。**
<img width="688" alt="image" src="https://user-images.githubusercontent.com/38588781/190346016-3d91cd2e-b97b-4d1e-ba49-577a4daef6ac.png">

> Q4. （如有可能）运行时Zotero占用了多大的内存，如果重复打开-关闭pdf数次，是否内存占用不断升高，或者关闭pdf后恢复到刚启动的占用量？
> **A4: 尝试同时打开BetterNotes和翻译插件，奔溃之前，存在CPU利用率超过100%，两分钟后自动闪退**
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/38588781/190349973-47a27e76-039a-4b26-bfcc-e90eae15e9ae.png">

**Comment by kevinzhangcode** [comment]
还是存在以上问题，CPU使用效率突然到80%以上，闪退。
<img width="568" alt="image" src="https://user-images.githubusercontent.com/38588781/190361249-437ee0da-2def-4736-8533-9906ed283932.png">

**Comment by windingwind** [comment]
如果CPU占用升高，这可能预示存在死循环（并且，理论上不应与better notes插件有关，因为它不会在阅读器界面做任何可能引起死循环的事情）
请在菜单栏打开输出日志：
![image](https://user-images.githubusercontent.com/33902321/190363023-db5408a2-7c92-434e-848c-ea973fbdb603.png)

然后在阅读文献的同时，请麻烦观察该窗口中的输出内容。如果出现重复输出某些内容，或者在卡死时不断输出内容，或卡死时有报错，请告诉我，谢谢！

另外想了解卡死是每次翻译都必然发生吗，还是仅仅偶尔发生？

**Comment by kevinzhangcode** [comment]
Q:了解卡死是每次翻译都必然发生吗，还是仅仅偶尔发生？
A: 偶尔发生的

感谢您的帮助！重启电脑后使用一段时间，无法复现以上Bug。
1、重启电脑和zotero之后，使用一段时间（超过3个小时），没有复现以上问题，感谢您的帮助。
2、**唯一更改的设置“记住弹窗大小”**
> 版本：
- `Zotero`: 6.0.13   ;
- `Zotero Better Notes`：0.6.28  
-  `Zotero PDF Translate`:0.8.23
如碰见类似问题，可以检查版本，设置“记住弹窗大小”。
