### ISSUE TITLE
希望添加单词本功能，搜集所读领域的相关词汇。[Feature]Complete the Title Here

### ISSUE THREAD

**Issue by lmlm1995** [windingwind/zotero-pdf-translate#212]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
单词本功能超出了插件”翻译“本身的作用，且不属于主要功能。如我曾经讨论过的原因（#128），将不考虑支持。
建议另建插件达到需要的功能。为了满足按需安装的需要，一个插件应该尽量只含一类功能，而非瑞士军刀式的集合体。
