### ISSUE TITLE
BUG 翻译插件无法使用（PDF预览界面不同）

### ISSUE THREAD

**Issue by slyviazheng** [windingwind/zotero-pdf-translate#213]
安装了ZOTERO的翻译插件，但无法翻译，而且自己点开PDF的界面和教程的界面不同，不知道是哪里出了问题
![1](https://user-images.githubusercontent.com/113893372/190984160-5f26c5a0-f8f0-4d06-afcf-64758567b040.jpg)
![2](https://user-images.githubusercontent.com/113893372/190984192-13b89590-41d8-488c-a9c6-1e5601ca08e7.png)

**Comment by windingwind** [comment]
编辑-首选项-打开pdf方式设置为内置阅读器。不要使用quicklook。

**Comment by slyviazheng** [comment]
谢谢您的回复，根据您的建议，已调好，感谢🙏

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: windingwind ***@***.***>
发送时间: Tuesday, September 20, 2022 10:59:22 PM
收件人: windingwind/zotero-pdf-translate ***@***.***>
抄送: slyviazheng ***@***.***>; Author ***@***.***>
主题: Re: [windingwind/zotero-pdf-translate] BUG 翻译插件无法使用（PDF预览界面不同） (Issue #213)


编辑-首选项-打开pdf方式设置为内置阅读器。不要使用quicklook。
