### ISSUE TITLE
[Bug]切换论文时，选取失败。翻译页面消失，无法加载

### ISSUE THREAD

**Issue by xiaolese1** [windingwind/zotero-pdf-translate#214]
**Describe the bug**
打开两篇论文后，在论文A中选取大段文字进行翻译后。打开另一篇论文B，选取任意论文B中的文字无法翻译，仍然显示论文A中之前选取的段落。此外，有时候当切换到论文B后，右侧翻译界面消失，无法再出现，只能关闭后重启。

**To Reproduce**
1. 打开论文A，论文B
2. A中选取一段文字，观察右侧翻译结果，正常。在论文A等待10分钟左右
3. 切换到论文B，选取段落或单个单词，观察右侧翻译结果，仍然显示论文A中段落
4. 切换回论文A的界面，重现选取单个单词，观察右侧结果，正常
5. 切换回论文B后，可正常使用翻译
6. 回到文库新打开论文C，右侧纯白无论文信息，tag。或者右侧有论文信息，无翻译选项

**Expected behavior**
翻译应该随着论文的切换，自动切换。右侧无翻译界面后，能有刷新按钮重新加载翻译选项

**Environment**
 - OS: Windows
 - Zotero Version(Help->About Zotero)  6.0.13
 - Addon Version(Tools->Add-ons)  Release 0.8.23

**Comment by xiaolese1** [comment]
![image](https://user-images.githubusercontent.com/104977940/191181969-5169033a-7556-42ea-a8ca-78f89674e934.png)

**Comment by xiaolese1** [comment]
![image](https://user-images.githubusercontent.com/104977940/191182385-1fdbbbef-d1e8-42f0-ab21-424b56acd571.png)

**Comment by xiaolese1** [comment]
> ![image](https://user-images.githubusercontent.com/104977940/191181969-5169033a-7556-42ea-a8ca-78f89674e934.png)

从adds-on的页面可以看出，translate的插件打开了，但右侧的界面无翻译页面。通常出现在打开新文献时。



> ![image](https://user-images.githubusercontent.com/104977940/191182385-1fdbbbef-d1e8-42f0-ab21-424b56acd571.png)

左侧选取的段落和右侧翻译显示段落不一致，自动翻译已经打开



> 感谢反馈。请问：
> 
> 1. 是否可以按照上述步骤稳定复现？我自己在使用的过程中，页面停留长时间后切换仍然可以正常工作。
> 2. 请根据[Common Issues #6](https://github.com/windingwind/zotero-pdf-translate/issues/6) 的调试步骤，将出现问题过程中的调试输出粘贴或上传此处。
>    谢谢！

1. 没法100%复现，但大多数情况下都会出现
2. 等出现后我会更新错误日志

**Comment by ShioHZY** [comment]
我也多次遇到这个问题，与您描述一致

**Comment by CharlesLee78** [comment]
我也遇到这个问题，几乎每次首次打开均无法显示右侧翻译界面，重启后正常，与您描述一致

**Comment by xiaolese1** [comment]
最近在升级到 Zotero 6.0.15并且插件升级到最新后，问题出现频率减少。此外，同时别打开太多文章也会降低该问题出现可能性。

**Comment by windingwind** [comment]
我注意到在当前pdf尚未加载完成时切换到其他pdf标签页，会导致侧边栏不正常切换。看起来似乎是Zotero的bug。

**Comment by windingwind** [comment]
请测试v0.9.3

**Comment by duofengzhiling** [comment]
我找到了一个百分之百的复现方法，一次性打开很多文献，然后就出现翻译插件失效的问题。或者切换文件速度过快也会导致（偶尔）

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
