### ISSUE TITLE
[Feature]使用百度通用翻译的自定义术语库 干预通用翻译的最终结果

### ISSUE THREAD

**Issue by xjtusjtu** [windingwind/zotero-pdf-translate#215]
作者大大您好，我个人非常喜欢这个插件，但是

**Is your feature request related to a problem? Please describe.**
目前插件的百度通用翻译并没有调用自定义术语库，干预最终的翻译结果

**Describe the solution you'd like**
百度通用翻译API接口已经支持自定义术语功能，建议在API设置中增加开启选项（可做一个开关）
具体而言，只需要在请求中增加action参数即可，请求干预时将 action 字段设置为1，不干预时设置为0

**Additional context**
- 翻译软件copytranslator下类似的Issue：https://github.com/CopyTranslator/CopyTranslator/issues/321
- 百度通用翻译相关文档：https://api.fanyi.baidu.com/doc/21

恳请作者大大考虑增加这个功能，谢谢！

**Comment by windingwind** [comment]
将下一版本更新。

**Comment by xjtusjtu** [comment]
感谢大大！
