### ISSUE TITLE
[Feature]请问是否可以把火山翻译加入可选的翻译引擎中？

### ISSUE THREAD

**Issue by dewiorchid** [windingwind/zotero-pdf-translate#217]
感谢大大开发的翻译插件，很好用！
就是最近翻译专业论文的时候，可用的几个翻译引擎译成中文的结果都有点难以理解，最近发现网页版的火山翻译的翻译效果挺好的，不知道大大是否可以把火山翻译加入可选的翻译引擎中？
非常感谢！

**Comment by windingwind** [comment]
将支持。

**Comment by dewiorchid** [comment]
谢谢开发者大大！！（比心

**Comment by windingwind** [comment]
我看了下，火山引擎的文档不全，没有关于具体加密和接口的信息。做起来比较麻烦，因此暂时不会支持。

**Comment by dewiorchid** [comment]
好的，了解了，谢谢开发者大大！

**Comment by YDQ098** [comment]
你好，能支持一下搜狗翻译吗

**Comment by windingwind** [comment]
> 你好，能支持一下搜狗翻译吗

不能。请搜索历史issue。

**Comment by windingwind** [comment]
暂时关闭issue，因为无计划支持。
