### ISSUE TITLE
小牛翻译问题

### ISSUE THREAD

**Issue by anastakeshui** [windingwind/zotero-pdf-translate#219]
如题，用得最新版0.8.23，一直用的小牛翻译，上午还可以翻译，下午再用就翻译不了了，我看了小牛翻译上我还有可翻译字符的，后来换了好几个版本的翻译插件都翻译不了，显示“此翻译引擎不可用,可能是密钥错误,也可能是请求过快  可以尝试其他翻译引擎”，又试了openl翻译也不行，请问一下是什么原因啊

**Comment by windingwind** [comment]
请截图。

**Comment by anastakeshui** [comment]
![`3 LELA_`AZD1RR@ HCY1XE](https://user-images.githubusercontent.com/114151856/191741348-00064648-1702-4ba9-9f5b-274f3153308c.png)
![)1~9L}WAG~6%4PU~QM%~RQ](https://user-images.githubusercontent.com/114151856/191741368-020bc4ec-ea40-4247-87fb-912ba13ba7c2.png)
![image](https://user-images.githubusercontent.com/114151856/191741270-af0fd91a-d5f9-4b9e-9bc1-1e84d2b32dbb.png)
这样能看见吗

**Comment by windingwind** [comment]
需要错误详细。

**Comment by anastakeshui** [comment]
![image](https://user-images.githubusercontent.com/114151856/191756558-7e9de78f-2c5b-4712-adc7-8cbbbf4481d3.png)
详细的是怎么看啊，这个吗，我不太理解你的意思

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/191918938-1add51bf-8688-4f92-8670-018ed4f6ad6e.png)
即，密钥错误或账号无余量。请检查密钥设置

**Comment by anastakeshui** [comment]
可是我完全没有动密钥，这是突然就不行了的；然后账号余量我上面的截图也很明显是有的啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate] zotero-pdf-translate 突然翻译不了了 (Issue #219)





 

 即，密钥错误或账号无余量。请检查密钥设置

**Comment by windingwind** [comment]
请检查是否有清除过插件设置，或由于其他插件的缘故清除了本插件的设置内容。
关于接口具体情况，请咨询服务提供商（小牛）。

**Comment by xiaozhuaipeiqi** [comment]
无法自动翻译，需要手动点一下翻译才行。也无法自动翻译到评论。

**Comment by windingwind** [comment]
无法**自动**翻译和无法翻译有本质上的区别。自动翻译设置如果打开，请排查是否有其他插件引起的冲突。

**Comment by windingwind** [comment]
是否需要进一步帮助？若无将关闭问题。
