### ISSUE TITLE
[Bug]使用百度垂直领域翻译api显示签名错误

### ISSUE THREAD

**Issue by Blitz030** [windingwind/zotero-pdf-translate#222]
使用的的目前最新版本的插件。所有设置做完之后使用百度垂直领域翻译翻译api一直出现签名错误，但使用百度翻译api没有问题。

我不懂编程，所以猜测签名生成的code可能需要更新。

https://fanyi-api.baidu.com/product/124
54001表示签名错误，请检查您的签名生成方法是否正确。
应该对 appid+q+salt+domian+密钥 拼接成的字符串做MD5得到32位小写的sign。确保要翻译的文本q为UTF8格式。
注意在生成签名拼接 appid+q+salt+domain+密钥 字符串时，q不需要做URL encode，在生成签名之后，发送HTTP请求之前才需要对要发送的待翻译文本字段q做URL encode。

**Comment by windingwind** [comment]
接口应当一直没有变，代码也没有变过，请检查垂域翻译的接口是否正确设置。垂域翻译与文本翻译需要在百度控制台中开启不同的两个服务。

**Comment by Blitz030** [comment]
接口设置指的是The secret format is MY_APPID#MY_KEY#DOMAIN_CODE(split with '#').吗？垂直翻译服务确定开通了，MY_APPID#MY_KEY#DOMAIN_CODE也反复检查过

**Comment by Blitz030** [comment]
已经解决了~
