### ISSUE TITLE
deepl pro密钥用不了 也没有确定键 然后填写了密钥也翻译不了

### ISSUE THREAD

**Issue by Sabrinahouonearth** [windingwind/zotero-pdf-translate#225]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题。如果不详细说明通过什么步骤可以复现问题，具体表现是什么，你正在使用哪个版本的插件，我没办法帮到你。不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Describe the bug**

**To Reproduce**
1. Go to '首选项'
2. Click on 'Translate'
3. Click on '翻译引擎'
4. Scroll down to 'deepl pro'
5. Click on '密钥‘
6. Copy’ 密钥‘
7. Back to PDF and then Translate the article or sentences
8. See error: 
9
**Expected behavior**

**Screenshots**

**Environment**
 - OS: macOS Monterey
 - Zotero Version(6.0.13)
 - Addon Version(Zotero PDF Translate)

**Additional context**
<img width="622" alt="Screen Shot 2022-09-23 at 3 23 35 PM" src="https://user-images.githubusercontent.com/112771390/192325081-3853e3dd-ff41-45ab-898b-790eb61ea3dd.png">
<img width="394" alt="Screen Shot 2022-09-23 at 3 23 54 PM" src="https://user-images.githubusercontent.com/112771390/192325084-4fdace5e-cb3c-45a2-a894-eb56d1abeb22.png">

**Comment by windingwind** [comment]
请确认账户开通了pro（而非free），并密钥正确。确认键在首选项窗口的下方。
请粘贴翻译结果中的完整错误提示到此处。

**Comment by Sabrinahouonearth** [comment]
确认账户开通了pro， 密钥确实正确，我自己还多次刷新密钥然后填了很多次。 确实键确实没有，如上图一所示。利用deepl pro翻译引擎入下图所示。
<img width="957" alt="Screen Shot 2022-09-26 at 2 05 06 PM" src="https://user-images.githubusercontent.com/112771390/192348744-6b63e691-83d2-46cb-8e0e-3cc655d04bd4.png">
![Screen Shot 2022-09-26 at 2 06 46 PM](https://user-images.githubusercontent.com/112771390/192349019-87282fce-e2e4-455d-bfde-7ebe5ae79a11.png)

**Comment by windingwind** [comment]
请截图deepl官网的订阅类型页面。deepl提供两类订阅，只有api订阅才能使用接口。如果你是客户端订阅，则无法使用。

**Comment by Sabrinahouonearth** [comment]
好的 我不是API类型的订阅。等我现在的订阅过期我会尝试再次切换翻译引擎。谢谢对我的回复！

**Comment by BOOLXXY** [comment]
> 好的 我不是API类型的订阅。等我现在的订阅过期我会尝试再次切换翻译引擎。谢谢对我的回复！
有可能是插件不匹配，我也是你的情况，然后在deepl公众号看到了这个内容，换了一遍插件之后就可以用了：
zotero划词翻译插件(把原插件卸载重新安装)

7.0及以上版本使用：https://download.deepl-pro.com/zotero-pdf-translate/releases/latest/download/zotero-pdf-translate.xpi
6.0版本使用：https://download.deepl-pro.com/zotero-pdf-translate/releases/download/v1.0.25/zotero-pdf-translate.xpi
