### ISSUE TITLE
[Bug] CNKI Translate

### ISSUE THREAD

**Issue by taetaem** [windingwind/zotero-pdf-translate#226]
我用的是最新版本的翻译插件，但是用CNKI学术翻译一直报错说
[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 CNKI学术翻译.
想知道这是为什么啊，有什么解决办法吗，谢谢

**Comment by windingwind** [comment]
请按照#6 排查问题，谢谢！

**Comment by MuyTu** [comment]
[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 谷歌API(中国可用).
Error: Request timed out
所有的翻译引擎都换过了，还是这个样子。。。

**Comment by windingwind** [comment]
谷歌本身在中国大陆地区可能存在访问限制，这取决于你所在地区网络通道情况。临近国内重要会议、节庆时，网络管制通常会更严格，与插件无关。
注册密钥的引擎始终可以使用。
单词翻译经由字典引擎（除非手动关闭字典翻译功能），因此可能单个词翻译不受影响，因为不使用谷歌或其他服务。
如错误提示所说，建议使用需要密钥的引擎。

**Comment by YoungLer** [comment]
![1664697481102](https://user-images.githubusercontent.com/114852549/193444390-1d2af88b-15c9-483a-abc8-683d2528d551.jpg)
出现这个界面是因为翻译太频繁，次数达到某一个阈值让程序认为你是机器人。解决方案就是登入网页版的”知网学术翻译“，随意输入一段英文，然后网页会提示你进行验证，验证完就可以在zotero里继续使用啦。

**Comment by Asuna233** [comment]
> 我用的是最新版本的翻译插件，但是用CNKI学术翻译一直报错说 [请求错误]
> 
> 此翻译引擎不可用,可能是密钥错误,也可能是请求过快 可以尝试其他翻译引擎,或者来此查看相关回答: https://github.com/windingwind/zotero-pdf-translate/issues
> 
> 请注意,这些错误与zotero和此翻译插件无关! 错误详情如下:
> 
> CNKI学术翻译. 想知道这是为什么啊，有什么解决办法吗，谢谢

我今天也出现了这个问题，然后我访问了知网翻译的网页，主动复制了一段文字进行翻译，然后提示了这个对话框，验证之后就好了

> ![1664697481102](https://user-images.githubusercontent.com/114852549/193444390-1d2af88b-15c9-483a-abc8-683d2528d551.jpg) 出现这个界面是因为翻译太频繁，次数达到某一个阈值让程序认为你是机器人。解决方案就是登入网页版的”知网学术翻译“，随意输入一段英文，然后网页会提示你进行验证，验证完就可以在zotero里继续使用啦。

**Comment by windingwind** [comment]
各位：
我已针对人机验证步骤在最新插件中增加了自动验证的功能，烦请继续使用并观察是否仍然会出现上面所述的问题。
如果仍然需要人机验证，请此处留言，谢谢！

**Comment by qyycdfrfr** [comment]
![image](https://user-images.githubusercontent.com/114758786/193524064-748fadd5-56be-4ca6-8650-fec38e8df0e9.png)
还是不行

**Comment by windingwind** [comment]
@qyycdfrfr 此处只讨论CNKI翻译引擎。

**Comment by lan-slot** [comment]
The cnki translation has long  delay

**Comment by windingwind** [comment]
> The cnki translation has long delay

That might be something I cannot control. Please update to the latest verison and see if it is still slow.

**Comment by lan-slot** [comment]
> > The cnki translation has long delay
> 
> That might be something I cannot control. Please update to the latest verison and see if it is still slow.

Thanks guru，after updating it still slow when translate long sentences，I know there might be something u cannot control. Still very much appreciate!

**Comment by cktyhub** [comment]
> 我用的是最新版本的翻译插件，但是用CNKI学术翻译一直报错说 [请求错误]
> 
> 此翻译引擎不可用,可能是密钥错误,也可能是请求过快 可以尝试其他翻译引擎,或者来此查看相关回答: https://github.com/windingwind/zotero-pdf-translate/issues
> 
> 请注意,这些错误与zotero和此翻译插件无关! 错误详情如下:
> 
> CNKI学术翻译. 想知道这是为什么啊，有什么解决办法吗，谢谢

我遇到了这个问题，跟前面有人提到的一样通过手动打开知网学术翻译随便翻译一下，再使用插件的知网翻译成功。

**Comment by Yooupi** [comment]
使用CNKI学术翻译时，选中文本过多，会出现如下错误。

[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 CNKI学术翻译.
[object XMLHttpRequest]

**Comment by liuxiaozhu01** [comment]
> ![1664697481102](https://user-images.githubusercontent.com/114852549/193444390-1d2af88b-15c9-483a-abc8-683d2528d551.jpg) 出现这个界面是因为翻译太频繁，次数达到某一个阈值让程序认为你是机器人。解决方案就是登入网页版的”知网学术翻译“，随意输入一段英文，然后网页会提示你进行验证，验证完就可以在zotero里继续使用啦。

但是我登入网页版之后，并没有提示验证，这是为什么呢？

**Comment by AndyRyuu** [comment]
知网学术翻译的网页还存在么？
