### ISSUE TITLE
[Bug]关于谷歌API（中国可用）似乎出bug

### ISSUE THREAD

**Issue by handsome-77** [windingwind/zotero-pdf-translate#228]
**Describe the bug**
采用谷歌API（中国可用）翻译引擎时，单词可以翻译，但是两个单词以上或一个句子时就无法翻译。

**To Reproduce**
1. 划一个词，出现翻译结果
2. 划两个词，显示请求超时
3. 划一个句子，也显示请求超时

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83406401/192662759-2bda8fcb-e685-4036-8852-68efb110bbc3.png)

![image](https://user-images.githubusercontent.com/83406401/192662737-26543223-ba1a-4e19-9db3-18d2d441c6cf.png)

**Environment**
 - OS: Windows
 - Zotero Version(Help->About Zotero)：6.0.13
 - Addon Version(Tools->Add-ons)：0.8.23

**Additional context**

**Comment by Xo-X** [comment]
是的，今天突然出问题了，单词都无法翻译。

**Comment by violin-debug** [comment]
我也这样，不知道大家有解决的方法没有

**Comment by handsome-77** [comment]
> 我也是这样的，你的问题解决了吗？

还没，等开发大大解答

**Comment by ChenKe22** [comment]
俺也一样

**Comment by zhoue666** [comment]
hi, same problem occured

**Comment by cabbage479** [comment]
我也是这样的

**Comment by MJ0-0** [comment]
我的也是，好像所有搜索引擎都没法用了

**Comment by cindy825** [comment]
我也是这样的，重新下载了之前的旧版本也没法使用，现在只有有道可以用了

**Comment by Rookie-Kai** [comment]
谷歌API我挂上梯子才能正常使用
目前我试了试CNKI学术翻译，这个是可以正常使用的

**Comment by windingwind** [comment]
各位好。
1. 谷歌本身在中国大陆地区可能存在访问限制，这取决于你所在地区网络通道情况。临近国内重要会议、节庆时，网络管制通常会更严格，与插件无关。
2. 注册密钥的引擎始终可以使用。
3. 单词翻译经由字典引擎（除非手动关闭字典翻译功能），因此可能单个词翻译不受影响，因为不使用谷歌或其他服务。
4. 如错误提示所说，建议使用需要密钥的引擎。

**Comment by xlnn** [comment]
hi, same problem occured

**Comment by handsome-77** [comment]
> 各位好。
> 
> 1. 谷歌本身在中国大陆地区可能存在访问限制，这取决于你所在地区网络通道情况。临近国内重要会议、节庆时，网络管制通常会更严格，与插件无关。
> 2. 注册密钥的引擎始终可以使用。
> 3. 单词翻译经由字典引擎（除非手动关闭字典翻译功能），因此可能单个词翻译不受影响，因为不使用谷歌或其他服务。
> 4. 如错误提示所说，建议使用需要密钥的引擎。

感谢解答！！

**Comment by SeaCheChe** [comment]
> 各位好。
> 
> 1. 谷歌本身在中国大陆地区可能存在访问限制，这取决于你所在地区网络通道情况。临近国内重要会议、节庆时，网络管制通常会更严格，与插件无关。
> 2. 注册密钥的引擎始终可以使用。
> 3. 单词翻译经由字典引擎（除非手动关闭字典翻译功能），因此可能单个词翻译不受影响，因为不使用谷歌或其他服务。
> 4. 如错误提示所说，建议使用需要密钥的引擎。

梯子改用全局模式果然可以用，谢谢，希望大会结束后能不再用全局模式了

**Comment by llxlr** [comment]
谷歌翻译也退华了，什么用户量低，这不一堆用的吗
