### ISSUE TITLE
zotero-pdf-translate 突然不能翻译了

### ISSUE THREAD

**Issue by suxiaom1** [windingwind/zotero-pdf-translate#229]
你好！我使用的是最新版的翻译插件版本0.8.24，我一直使用的是谷歌API（中国可用）翻译器，之前都可以自动翻译，但现在选择英语字词后不会自动翻译了，也不会报错，只会显示我选中的英文字词，我试着重新下载并安装翻译插件，但还是没用，这怎么解决呢？

**Comment by suxiaom1** [comment]
![QQ图片20220928113730(1)](https://user-images.githubusercontent.com/114551662/192683080-c0ed1467-9839-4bd1-b765-5ae229208c0b.jpg)

**Comment by suxiaom1** [comment]
![QQ图片2022092811504(1)](https://user-images.githubusercontent.com/114551662/192683651-53620b9d-fa1a-41c6-9bfc-571f2b0269ac.jpg)

**Comment by windingwind** [comment]
see #228
