### ISSUE TITLE
[Bug] 谷歌Api中国翻译无法使用

### ISSUE THREAD

**Issue by waityousea** [windingwind/zotero-pdf-translate#230]
**Environment**
 - OS: Windows
 - Zotero Version 6.0.13
 - Zotero PDF Translate Version(0.8.24)

**Additional context**
Zotero PDF Translate
使用过程中的翻译问题：
  

今天使用Zotero进行论文翻译时突然无法正常使用（PS：9.27晚上还是正常的），查看Zotero PDF Translate信息后发现今天您更新了插件，经过测试发现，只有CNKI学术翻译和彩云两个api可以使用。

其他几个api分别出现了不同的问题，汇总信息如下：
**1. 谷歌Api中国可用**
请求错误]
  此翻译引擎不可用,可能是密钥错误,也可能是请求过快
  可以尝试其他翻译引擎,或者来此查看相关回答:
  https://github.com/windingwind/zotero-pdf-translate/issues 
  
  请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 
  
   谷歌API(中国可用).
  **Error: Request timed out**
2.  DeepL(Free)*
请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 DeepL(Free)*.
Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403

3. 小牛
[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 小牛*.
13002:apikey is empty

**Comment by royalina** [comment]
同样的时间节点，同样的问题，同样的错误原因

**Comment by Chrysene2000** [comment]
我的CNKI学术翻译也用不了了，就在刚刚，于是过来搜索为啥。

**Comment by zzydzh** [comment]
单个单词可以翻译，一句话显示同样错误

**Comment by windingwind** [comment]
see #6 and #228

**Comment by yzy1999999** [comment]
> 单个单词可以翻译，一句话显示同样错误

**Comment by zzydzh** [comment]
> > 单个单词可以翻译，一句话显示同样错误

改用有道翻译等可以翻译

**Comment by nzlJimmy** [comment]
谷歌的问题，挂个梯子就可以翻译了

**Comment by Liuliu-55** [comment]
> > > 单个单词可以翻译，一句话显示同样错误
> 
> 改用有道翻译等可以翻译

我的有道翻译也用不了

**Comment by xiamoyl** [comment]
我都用不了

**Comment by wenbohuang1002** [comment]
同样用不了了

**Comment by TTOONNG** [comment]
单个单词可以翻译，但是句子不行

**Comment by Moyun0203** [comment]
我的今天刚安装这个插件用了一会，然后就不行了，请问有解决办法吗？

**Comment by Sophier99** [comment]
我的也是，所有的翻译都用不了，到底是为什么啊！哭泣，明天就要组会汇报了，今天上午翻译的好好的，下午不行过后我重启又可以了，然后又不行，就一直到晚上都不行。求解决啊哭哭哭！

**Comment by dabai-tutu** [comment]
突然用不了了，崩溃啊，同样的问题

**Comment by Moyun0203** [comment]
> 见#228
> 
> 谷歌本身在中国大陆地区可能存在访问限制，这取决于你所在地区网络通道情况。临近国内重要会议、节庆时，网络管制通常会更严格，与插件无关。 注册密钥的引擎始终可以使用。 单词翻译经由字典引擎（除非手动关闭字典翻译功能），因此可能单个词翻译不受影响，因为不使用谷歌或其他服务。 如错误提示所说，建议使用需要密钥的引擎。


那个CNKI翻译引擎也不行，请问怎么进行密钥的注册？？？？

**Comment by windingwind** [comment]
常见问题#6

**Comment by Moyun0203** [comment]
你好，貌似又不可以了，今天上午还能用CNKI学术翻译，用着用着又不可以翻译了。请问那个翻译引擎的密钥怎么搞？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 晚上10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [windingwind/zotero-pdf-translate] [Bug] 谷歌Api中国翻译无法使用 (Issue #230)





 
见#228
 
谷歌本身在中国大陆地区可能存在访问限制，这取决于你所在地区网络通道情况。临近国内重要会议、节庆时，网络管制通常会更严格，与插件无关。
 注册密钥的引擎始终可以使用。
 单词翻译经由字典引擎（除非手动关闭字典翻译功能），因此可能单个词翻译不受影响，因为不使用谷歌或其他服务。
 如错误提示所说，建议使用需要密钥的引擎。

**Comment by xiangqingqing** [comment]
试了百度和有道，还是同样的问题

**Comment by windingwind** [comment]
请认真看主页的说明，只有需要密钥的翻译服务是稳定可访问的，其他的一律不保证使用稳定性。密钥申请见主页。
此处关闭。

**Comment by xiangqingqing** [comment]
可是我的百度也是用的密钥呀，也是没用哦，昨晚还是正常使用，今天就不正常了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月29日 13:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] [Bug] 谷歌Api中国翻译无法使用 (Issue #230) |

请认真看主页的说明，只有需要密钥的翻译服务是稳定可访问的，其他的一律不保证使用稳定性。密钥申请见主页。
此处关闭。

**Comment by windingwind** [comment]
> 可是我的百度也是用的密钥呀，也是没用哦，昨晚还是正常使用，今天就不正常了
> […](#)

请检查账户余量。
