### ISSUE TITLE
[Bug]Complete the Title Here您好！我想请问一下，今天使用CNKI翻译时，一直显示这个页面，我重新下载了几次最新版本的插件还是如此，请问该如何解决？期待您的回复！

### ISSUE THREAD

**Issue by 1481597349** [windingwind/zotero-pdf-translate#231]
**Describe the bug**
您好！我想请问一下，今天使用CNKI翻译时，一直显示这个页面，我重新下载了几次最新版本的插件还是如此，请问该如何解决？期待您的回复！
![image](https://user-images.githubusercontent.com/114599403/192819014-ac8da8c1-f866-4152-8689-85e62d091787.png)

**Comment by dabai-tutu** [comment]
同问同问，怎么搞啊

**Comment by zyh2746303487** [comment]
挂个梯子就好了

**Comment by windingwind** [comment]
请合并到#226讨论，此处关闭
