### ISSUE TITLE
 有道智云*. Error: errorCode: 108

### ISSUE THREAD

**Issue by Doctoressence** [windingwind/zotero-pdf-translate#235]
有道智云*.
Error: errorCode: 108
有道智云的IP和密钥没有办法输入到zotero里
![image](https://user-images.githubusercontent.com/114747133/193274846-648d02d9-5f7d-42c1-9766-5d23575f61d7.png)
![image](https://user-images.githubusercontent.com/114747133/193274372-691beedc-c9af-4ca5-bb32-b7d565765565.png)
![image](https://user-images.githubusercontent.com/114747133/193274538-1d09ea28-c9e8-4822-bbcf-a869d7f5e860.png)

**Comment by windingwind** [comment]
请检查密钥格式`MY_APPID#MY_SECRET#MY_VOCABID(optional)`

**Comment by Doctoressence** [comment]
搞定了，谢谢大佬！






&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 晚上11:07
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate]  有道智云*. Error: errorCode: 108 (Issue #235)





 
请检查密钥格式MY_APPID#MY_SECRET#MY_VOCABID(optional)

**Comment by MED-P0520** [comment]
这个密钥格式是怎么填写哇

**Comment by Doctoressence** [comment]
MY_APPID#MY_SECRET#MY_VOCABID


&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月1日(星期六) 晚上7:06
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate]  有道智云*. Error: errorCode: 108 (Issue #235)





 
这个密钥格式是怎么填写哇

**Comment by 155127gwc** [comment]
密钥格式的最后一个填我的什么啊？MY_VOCABID（这个是填什么啊？）

**Comment by JiangQ01** [comment]
我按格式填也是这个报错
"""[请求错误]
此翻译服务不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译服务，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 有道智云

Service error: 310"""
