### ISSUE TITLE
[Bug]Zotero更新了6.0.15后突然无法时时翻译

### ISSUE THREAD

**Issue by SeaCheChe** [windingwind/zotero-pdf-translate#236]
最近好久没用zotero了，今天更新了一下zotero到最新版本（6.0.15）之后，无法时时翻译，不知道为什么，求解答，具体请看贴图
电脑是mac系统，系统版本10.15.7
更换谷歌（中国可用）和有道都不行
<img width="925" alt="image" src="https://user-images.githubusercontent.com/105227871/193413708-4e6a1a97-8a3b-49f5-92b3-d6b8ef8c63bf.png">
<img width="932" alt="image" src="https://user-images.githubusercontent.com/105227871/193413733-582b9ad5-b84e-4330-99a2-89797af7cec3.png">

**Comment by IceTea0120** [comment]
me too

**Comment by tigerwang1998** [comment]
same problem

**Comment by lubiandexiaochitan** [comment]
I don't know exactly why, but the translation came back after I turned on the VPN

**Comment by tigerwang1998** [comment]
您好，邮件已收到。
 久等不回或急事请电话联系。

**Comment by windingwind** [comment]
see #224 and #228

**Comment by zzzzzdev** [comment]
maybe i think the problem is that google translate api
is no longer be supported in China.
