### ISSUE TITLE
Unicode normalization

### ISSUE THREAD

**Issue by KveinAxel** [windingwind/zotero-pdf-translate#237]
![NPDPOV43AP`8N$)M$V5X1~A](https://user-images.githubusercontent.com/41867249/193462179-7d17e450-ed6c-4fe2-9127-e1378cbd21c7.png)

这个例子中的ff连写的unicode被过滤了，感觉应该先把unicode规范化一遍再翻译，能识别一些pdf生成导致的unicode。

具体的规范化见：https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization 很多库应该都有支持

**Comment by windingwind** [comment]
谢谢，之前有人提过我忘了这事了
方便上传样例pdf让我测试下吗？

**Comment by KveinAxel** [comment]
公式（31）下面那行的efficient

[coefficient.pdf](https://github.com/windingwind/zotero-pdf-translate/files/9692977/coefficient.pdf)

用有道后端的时候会翻译错误，谷歌只是恰好会翻译不带ff的版本

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/193486659-832cbfd8-e44a-4376-8f1d-5ecbe2626e9e.png)
这个PDF似乎没有正确存储ffi的unicode码，直接存成了i

**Comment by windingwind** [comment]
之前已经对字符做了NFKC normalization，我自己都忘了这事了

https://github.com/windingwind/zotero-pdf-translate/blob/93e590533983b08c5ad5649d8463f1fbbb8b740c/src/translate.ts#L570-L572
