### ISSUE TITLE
[Bug]小牛翻译的api无法使用

### ISSUE THREAD

**Issue by mistofflees** [windingwind/zotero-pdf-translate#239]
下载的最新版本的zotero，输入小牛api码之后显示请求错误。

[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 小牛*.
13001:apikey error OR apikey unauthorized OR service package running out

**Comment by windingwind** [comment]
请正确注册并设置密钥

**Comment by windingwind** [comment]
合并到#243 讨论，此处关闭
