### ISSUE TITLE
Google翻译依旧不可用

### ISSUE THREAD

**Issue by zys1346** [windingwind/zotero-pdf-translate#24]
使用Google Translate（CN），显示如下错误：
[Request Error]
Engine not available, invalid secret, or request too fast.
Please consider using another translate engine or posting issue here: https://github.com/windingwind/zotero-pdf-translate/issues
        Error: Request timed out

**Comment by windingwind** [comment]
See #5 .

**Comment by zys1346** [comment]
谢谢!
