### ISSUE TITLE
[Bug]翻译功能失效

### ISSUE THREAD

**Issue by tangfangcslg** [windingwind/zotero-pdf-translate#240]
问题描述：
翻译功能有时会自动失效（划词不翻译），即使重启了Zotero也没有重新生效。

**Comment by windingwind** [comment]
请详细描述并带截图。

**Comment by xpx9826** [comment]
翻译功能失效，所有API的划线翻译都不可使用
![1665023118869](https://user-images.githubusercontent.com/52862920/194200351-dcf1bf6c-9554-4255-a81a-344a2b8a2247.jpg)

**Comment by pickxiguapi** [comment]
同样出现该问题

**Comment by windingwind** [comment]
小牛出现问题请向其官网客服反馈，其他翻译问题请见#6

**Comment by windingwind** [comment]
小牛翻译问题请合并到#243 讨论

**Comment by Amy-ing** [comment]
我也一样，网和密钥都
![微信图片_20221006104901](https://user-images.githubusercontent.com/115127606/194203105-87253953-6a77-4cdb-9514-ac371e579d38.jpg)
对的，就是翻译不了
