### ISSUE TITLE
[Feature]请问在右侧的翻译区，中文译文的字体大小可以调整嘛，如果不可以的话，可以方便增加这个功能嘛，因为视力原因，在笔记本上阅读文献时，感觉字体太小，有点费力。非常感谢！

### ISSUE THREAD

**Issue by Hustjunjie** [windingwind/zotero-pdf-translate#242]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
见readme qa
