### ISSUE TITLE
[Bug]小牛翻译功能失效

### ISSUE THREAD

**Issue by Dawnshyc** [windingwind/zotero-pdf-translate#243]
你好，我想请问一下小牛翻译上一秒还可以用，下一秒就翻译不了了，我看solution那里好像是说显示change translate engine，是用不了这个了的意思吗？谢谢~

[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 小牛*.
Error: Request timed out

**Comment by windingwind** [comment]
我了解到小牛今天出现问题，请等待其恢复服务。与插件无关

**Comment by Dawnshyc** [comment]
> 

好的，谢谢！

**Comment by Amy-ing** [comment]
现在好了

**Comment by windingwind** [comment]
> 可是谷歌也不行了

谷歌出现问题因为国内无法访问谷歌服务，与网络环境有关。参见类似提问

**Comment by Amy-ing** [comment]
您好，您的信件我已收到

**Comment by windingwind** [comment]
> 不知道为什么，挂梯子就可以用，不挂梯子所有翻译引擎都没法用

推荐使用需要密钥的国内翻译服务。不带*的不保证使用。

**Comment by windingwind** [comment]
由于小牛已恢复服务，将关闭问题。

**Comment by maoqing123456** [comment]
> 
![image](https://user-images.githubusercontent.com/115159880/194314051-c1d104a4-311d-4673-be13-cb20c86f02b1.png)

为什么我的还没有恢复

**Comment by cherubic01** [comment]
为什么使用这个插件，用有道翻译器不能翻译出结果，并且也没有出现是服务器的问题
