### ISSUE TITLE
[Bug]翻译之后不会在注释中显示

### ISSUE THREAD

**Issue by anber111** [windingwind/zotero-pdf-translate#244]
您好，我在10.6日下午使用0.8.21版本翻译的时候，在注释上还能显示出来翻译结果，但是更新到0.8.25之后就不显示了，我用的zotero是6.0.15版本。之前在注释的右上角会有一个翻译的图标，现在也没有了，是因为这个zotero是beta版吗？我把插件退回0.8.21版本也不行了，谢谢

**Comment by anber111** [comment]
评论会提示错误。。。

**Comment by anber111** [comment]
![2022-10-06 202549](https://user-images.githubusercontent.com/104560666/194314047-590c5308-725d-4c95-be0b-9f1a1ee48fe1.png)

**Comment by anber111** [comment]
终于发出来图了，我用选图框出来就有这些插件，直接选中就没有了，看看孩子吧，谢谢了

**Comment by anber111** [comment]
![屏幕截图 2022-10-06 203953](https://user-images.githubusercontent.com/104560666/194314803-011a9e21-0e9c-438a-a134-d871e1303a72.png)
这个是我用0.8.21版本的，一直是正常的

**Comment by windingwind** [comment]
具体问题是：
- 注释上面的翻译图标消失
- 翻译结果正常（有弹窗提示翻译完成）但未保存在注释的评论
- 翻译结果不正常

的哪一个？

**Comment by anber111** [comment]
是这两个问题，但是我今天又更新了一下zotero之后，发现好了，也不知道是啥原因，我昨天给zotero反馈，他们说是插件的问题。
谢谢了

注释上面的翻译图标消失

翻译结果正常（有弹窗提示翻译完成）但未保存在注释的评论





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 晚上7:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate] [Bug]翻译之后不会在注释中显示 (Issue #244)





 
具体问题是：
  
注释上面的翻译图标消失
 
翻译结果正常（有弹窗提示翻译完成）但未保存在注释的评论
 
翻译结果不正常
  
的哪一个？

**Comment by windingwind** [comment]
如果再次遇到问题，请按照#6 排查。我需要可复现的操作或调试报告方能帮助解决问题。

**Comment by anber111** [comment]
好的，谢谢了







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate] [Bug]翻译之后不会在注释中显示 (Issue #244)





 
如果再次遇到问题，请按照#6 排查。我需要可复现的操作或调试报告方能帮助解决问题。

**Comment by windingwind** [comment]
暂时关闭，需要可再打开
