### ISSUE TITLE
[Feature]希望可以针对“标题翻译”功能做出进一步改进

### ISSUE THREAD

**Issue by CMD-cmd** [windingwind/zotero-pdf-translate#245]
目前的“标题翻译”功能，可以在左侧文件夹处或者中间条目处右键进行翻译，但是在设置选项卡中缺乏相应设置；个人认为增加这些设置项可以提高使用效率：

1. 增加“导入外文文献自动翻译标题”选项，这样就不用鼠标右键去点每篇文献了，而“cmd+T”快捷键可以更改为触发“显示/隐藏标题翻译”
2. 增加”标题翻译使用特定翻译引擎“选项，这样可以为标题翻译设置独立的翻译引擎（可以使用免费额度较少或较为昂贵的、但是翻译准确度较高的引擎去翻译标题，在提高翻译可读性的同时以免超过字符限制）

望大佬采纳！

**Comment by windingwind** [comment]
针对1：
可行。目前按快捷键时，如果已有翻译结果，则只会显示或隐藏；否则会执行翻译。因此这部分逻辑是相同的。

针对2：
可行。

将后续版本更新。

**Comment by CMD-cmd** [comment]
好哒好哒！谢谢开发者大大~

**Comment by Victory-Hugo** [comment]
最近使用zotero6无法再点击 标题翻译 ， 不知道是什么问题。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/143314364/b66648b2-f583-45c3-a230-0bfda750958c)
