### ISSUE TITLE
[Bug]谷歌翻译API挂梯子后翻译不完全，只翻译选择部分的开头

### ISSUE THREAD

**Issue by Potato-Xue** [windingwind/zotero-pdf-translate#246]
![image](https://user-images.githubusercontent.com/115202660/194460022-59e307eb-1ff1-4bdd-8159-c4a9d04c786a.png)

选中的翻译片段只能翻译一部分，并且翻译准确性貌似会受到参考文献数字的影响，之前使用没有遇到这样的情况。

第一次反馈问题不知道格式是否准确，期待开发大大的答复。谢谢！

**Comment by Potato-Xue** [comment]
![image](https://user-images.githubusercontent.com/115202660/194460613-5bb6c2e6-96fc-43b4-b34f-b22b82c914be.png)

有些单词中的空格突然不见了，导致无法翻译准确。

**Comment by Potato-Xue** [comment]
![image](https://user-images.githubusercontent.com/115202660/194460748-b92e5fa3-45b0-4b01-bc15-bb2ecf69b98b.png)

有些单词中的空格突然不见了，导致无法翻译准确。例如图片中的 the most变成了themost，出现了无法正确翻译的情况。

**Comment by windingwind** [comment]
词语连起来的情况多半是pdf源文本就有问题，可以复制出来看下具体是什么原因，或者把pd发在这里。
翻译只有一部分的情况，我估计是pdf源文本中有特殊字符等。和梯子之类的没关系，和插件也没关系。

**Comment by Potato-Xue** [comment]
收到!&nbsp;感谢开发大大的回复!
昨天后面发现其他的文章都没问题，只有这一篇会这样。&nbsp;回去看看这个文章从不同下载来源有没有区别。
再次感谢回复! 辛苦了！

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月7日(周五) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [windingwind/zotero-pdf-translate] [Bug]谷歌翻译API挂梯子后翻译不完全，只翻译选择部分的开头 (Issue #246)




 
词语连起来的情况多半是pdf源文本就有问题，可以复制出来看下具体是什么原因，或者把pd发在这里。
 翻译只有一部分的情况，我估计是pdf源文本中有特殊字符等。和梯子之类的没关系，和插件也没关系。
