### ISSUE TITLE
求问大佬出现这样的提示该咋解决

### ISSUE THREAD

**Issue by HalfOra** [windingwind/zotero-pdf-translate#247]
[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 百度*.
52003:UNAUTHORIZED USER

**Comment by muzizhixin** [comment]
我也是遇到了这个问题

**Comment by rookiehey** [comment]
我也是

**Comment by windingwind** [comment]
带星的翻译引擎需要注册账户并填写密钥。请仔细阅读readme。
