### ISSUE TITLE
[Bug]无法翻译所选文字

### ISSUE THREAD

**Issue by palpitation9** [windingwind/zotero-pdf-translate#248]
我使用的是8.25版本，选取文字后，无法翻译。第一次反馈不知是否恰当，希望得到回复谢谢～
<img width="901" alt="截屏2022-10-08 15 35 53" src="https://user-images.githubusercontent.com/106011137/194695957-b3661a78-51e4-4bc8-809d-af5bf4d1d9ac.png">

**Comment by windingwind** [comment]
如说明所说，换个翻译引擎。
