### ISSUE TITLE
[Bug]显示此翻译引擎不可用，更换引擎也都不行[Bug]

### ISSUE THREAD

**Issue by hcfjw** [windingwind/zotero-pdf-translate#249]
zetero版本是6.0.15，PDF Translate版本是0.8.25
翻译框显示：
此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 有道智云*.
Error: errorCode: 108
<img width="1368" alt="截屏2022-10-08 15 33 27" src="https://user-images.githubusercontent.com/115341307/194696204-b42309e9-01da-4d05-b5b4-572143a9eaff.png">

希望能得到大佬们的帮助解决这个问题，感谢各位大佬！！！

**Comment by windingwind** [comment]
带星的翻译引擎需要正确设置密钥方能使用。
