### ISSUE TITLE
[Bug]选择文献内容翻译后，添加图片笔记会自动将上一次翻译的内容添加到图片备注

### ISSUE THREAD

**Issue by The-New-Coder** [windingwind/zotero-pdf-translate#25]
~Search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) and make sure this is not a duplicated issue~

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by windingwind** [comment]
This is actually a feature called translate annotation, introduced in the recent update. If you don't need it, go to Edit>Preferences and uncheck `Translate Annotation`

**Comment by windingwind** [comment]
Fixed in v0.3.1
