### ISSUE TITLE
Request：摘要翻译结果放在单独的字段，像标题翻译一样

### ISSUE THREAD

**Issue by pekideer** [windingwind/zotero-pdf-translate#250]
**Is your feature request related to a problem? Please describe.**
摘要翻译 没有像 标题翻译一样 单独放在副标题，而是与原英文摘要合并在一起。翻译行为导致英文摘要保持纯净
**Describe the solution you'd like**
建议像翻译标题一样，将翻译后的中文摘要单独放在一个字段，如“系列标题”或“系列文本”
**Describe alternatives you've considered**
无
**Additional context**
无

**Comment by volatile-static** [comment]
zotero的字段没办法自定义的

**Comment by pekideer** [comment]
是否可以放入现有的字段？（比如中文标题放到 副标题 字段、IF影响因子可以放入 档案 字段）&nbsp;


13340214836
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月9日(星期天) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [windingwind/zotero-pdf-translate] Request：摘要翻译结果放在单独的字段，像标题翻译一样 (Issue #250)





 
zotero的字段没办法自定义的

**Comment by volatile-static** [comment]
可以在首选项设置存到哪个字段，但是原有内容怎么处理？

**Comment by volatile-static** [comment]
或许可以放到[extra字段](https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra)

**Comment by windingwind** [comment]
放在extra不方便可视化，无法在右侧清晰地看到翻译结果。考虑到不占用其他字段，仍然放在摘要合适。
摘要字段仅仅用于用户阅读，与引文格式一般无关，因此从功能意义上说没有必要”保持纯净性“。

**Comment by windingwind** [comment]
已放在extra
