### ISSUE TITLE
[Bug]作为单独窗口打开后，拼接选取、清空选取等按钮失效。

### ISSUE THREAD

**Issue by Yooupi** [windingwind/zotero-pdf-translate#252]
**Describe the bug**
PDF Translate在zotero作为单独窗口打开后，“清空选取、拼接选取”等按钮失效。

**To Reproduce**
1.在文章中点击“打开单独窗口”按钮；
2.在单独窗口中使用“清空选取、拼接选取”时会失效，点击“清空选取”并未清空，使用“拼接选取”并未拼接。

**Expected behavior**
希望能在单独窗口中独立使用“清空选取、拼接选取”等按钮。

**Screenshots**
如下图：
![image](https://user-images.githubusercontent.com/101870448/194803383-cc12fe9d-3d95-49ca-911a-46fafca23ae5.png)
![image](https://user-images.githubusercontent.com/101870448/194803443-b37c8582-8481-499a-86dd-f10abb9f4c83.png)

**Environment**
 - OS: Windows11 22H2
 - Zotero Version(Help->About Zotero)：6.0.15
 - Addon Version(Tools->Add-ons)：0.8.25

**Comment by Yooupi** [comment]
Anyone else have the same problem?

**Comment by windingwind** [comment]
问题我已知晓，可以暂时通过按住alt以拼接选取。有空我排查下
