### ISSUE TITLE
微软翻译API输入密钥后依旧无法使用

### ISSUE THREAD

**Issue by NinSUM** [windingwind/zotero-pdf-translate#253]
按教程申请了微软翻译api,输入了密钥。显示以下信息
[请求错误]

此翻译引擎不可用,可能是密钥错误,也可能是请求过快
可以尝试其他翻译引擎,或者来此查看相关回答:
https://github.com/windingwind/zotero-pdf-translate/issues 

请注意,这些错误与zotero和此翻译插件无关! 错误详情如下: 

 微软*.
Error: HTTP POST https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=zh-CN failed with status code 401

**Comment by windingwind** [comment]
请截图azure的服务页面

**Comment by NinSUM** [comment]
已经删除了原来申请的密钥，重新创建了翻译api，发现选择区域为global时创建时验证失败，显示The provided location 'global' is not available for resource group。选择其他区域则可以创建，但使用时又出现了上面的问题

**Comment by windingwind** [comment]
关于创建服务等问题不在我的答复范围内。请咨询服务提供商。
只保证支持global服务。
