### ISSUE TITLE
[Bug]已经获取了微软密钥，但是在Zotero中输入仍无法进行翻译

### ISSUE THREAD

**Issue by DCLe-DA** [windingwind/zotero-pdf-translate#254]
获取了微软的密钥，复制粘贴进入Zotero的指定区域仍然无法翻译，
显示Error: HTTP POST https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=zh-CN failed with status code 401
![question](https://user-images.githubusercontent.com/60722957/195485862-f0edd291-1819-419d-972c-abf9629ed59a.jpeg)

**Comment by DCLe-DA** [comment]
<img width="547" alt="捕获" src="https://user-images.githubusercontent.com/60722957/195486072-6864d2d5-731a-4498-82f8-582732c2b057.PNG">
附一张微软密钥的图，显示密钥无误

**Comment by DCLe-DA** [comment]
附Azure的资源截图：
<img width="821" alt="捕获" src="https://user-images.githubusercontent.com/60722957/195487219-24280475-39dc-46b5-ad1c-e35e73e101c6.PNG">
<img width="752" alt="捕获1" src="https://user-images.githubusercontent.com/60722957/195487236-9c71ea12-c5cd-4015-b303-df932e914e87.PNG">
<img width="915" alt="捕获2" src="https://user-images.githubusercontent.com/60722957/195487244-67d06b44-a667-49d3-a2e6-fe2987e7990f.PNG">

**Comment by windingwind** [comment]
地区请选择global或北美，不要设置其他地区

**Comment by DCLe-DA** [comment]
> 地区请选择global或北美，不要设置其他地区

您好，感谢解答。但我已尝试改为global，或者north central US ,结果依然无法使用

<img width="821" alt="global" src="https://user-images.githubusercontent.com/60722957/195495436-28948f0b-d920-4ac2-b675-f32c5e5e99ed.PNG">
<img width="265" alt="捕获1" src="https://user-images.githubusercontent.com/60722957/195495505-0e8b1d1a-c002-4eb9-94c8-068f40d2cc6e.PNG">

**Comment by DCLe-DA** [comment]
> 地区请选择global或北美，不要设置其他地区

好的谢谢您，问题解决了！
