### ISSUE TITLE
翻译窗口过窄

### ISSUE THREAD

**Issue by yanyu2015** [windingwind/zotero-pdf-translate#255]
翻译悬浮窗口过窄，上次反馈后作者已经增加了调节窗口宽度的功能，感谢！但是每次都要重新调宽度，十分麻烦，希望能够一次调整宽度后，自动固定宽度

**Comment by windingwind** [comment]
https://zotero.yuque.com/books/share/4443494c-c698-4e08-9d1e-ed253390346d/whr95i

**Comment by yanyu2015** [comment]
已解决，感谢！
