### ISSUE TITLE
能不能增加朗文字典查词呀，求求了，必应词典单词的美音音标很奇怪

### ISSUE THREAD

**Issue by MOZLF** [windingwind/zotero-pdf-translate#256]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
请提供在线可用的服务网址

**Comment by MOZLF** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1240418006
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年10月15日 ***@***.***> 写道： 




请提供在线可用的服务网址



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>侠之大者，为国为民，非常感谢，两个在线词典网址如下：朗文网址：https://www.ldoceonline.com/柯林斯网址：https://www.collinsdictionary.com/dictionary/english/world

**Comment by windingwind** [comment]
@MOZLF 已加collins

**Comment by MOZLF** [comment]
看到啦看到啦谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月18日(周二) 晚上8:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [windingwind/zotero-pdf-translate] 能不能增加朗文字典查词呀，求求了，必应词典单词的美音音标很奇怪 (Issue #256)




 
@MOZLF 已加collins

**Comment by sjhsbhqf** [comment]
海词词典怎么申请API呢？在网上查半天没查到
