### ISSUE TITLE
跪求增加自建deepl API接口

### ISSUE THREAD

**Issue by dongdashan1** [windingwind/zotero-pdf-translate#258]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/46799913/195748083-fcee2df3-fc4d-4e78-9d89-9e21f2b137c5.png">      类似于这种的 接口。 可以参考https://github.com/clubxdev/bob-plugin-deeplx的实现 谢谢大哥

**Comment by windingwind** [comment]
这不是大众的需求，因此不会做。有需要可自己实现
