### ISSUE TITLE
[Bug]所有翻译路径都无法使用

### ISSUE THREAD

**Issue by jess663** [windingwind/zotero-pdf-translate#259]
知网的学术翻译错误，如图
![知网](https://user-images.githubusercontent.com/67717993/195962910-de39fc15-3c13-4817-832e-e7758c061103.png)

有道的翻译错误，如图
![有道](https://user-images.githubusercontent.com/67717993/195962935-a71f95f5-00ee-4ccf-bc55-fd45613b4311.png)

需要密匙的小牛的翻译错误，如（已添加密匙）
![小牛](https://user-images.githubusercontent.com/67717993/195962989-5afc0326-95d4-4cd5-b806-546b580a53b3.png)

求指导，感谢！

**Comment by Liuliu-55** [comment]
我也不能用了，但我没有提示不可用，就是翻译不了

**Comment by jess663** [comment]
您好，我是黄圣赟。您的邮件我已收到，我会尽快回复您的。

**Comment by windingwind** [comment]
https://zotero.yuque.com/books/share/4443494c-c698-4e08-9d1e-ed253390346d/age09f
