### ISSUE TITLE
[Bug]微软翻译无法使用

### ISSUE THREAD

**Issue by roycham** [windingwind/zotero-pdf-translate#263]
![image](https://user-images.githubusercontent.com/86769983/196189641-2a7562f3-ef0a-475d-b2f7-47f8f62ce3ac.png)
![image](https://user-images.githubusercontent.com/86769983/196189875-77461359-8677-44d5-95f7-987f4aa154f8.png)

**Comment by windingwind** [comment]
地区global

**Comment by csf2022scut** [comment]
> 

选global就创建不了翻译引擎了
