### ISSUE TITLE
[Bug]内置pdf阅读页面右侧翻译和笔记栏整个消失

### ISSUE THREAD

**Issue by neuronsandsynapses** [windingwind/zotero-pdf-translate#267]
你好，很感谢你之前帮助我弄翻译的API，现在我遇到一个超级可怕的bug，网上搜索无果，诚挚期待你的帮助（比心）

**Describe the bug**
问题一：每次打开zotero都会出现之前很久之前打开的八篇文献和一个open in new window打开的空白页
问题二：内置pdf阅读器页面右侧的翻译栏和笔记栏完全消失，不是最小化了，是消失了，无论哪个点都调不出来

**Expected behavior**
希望软件能够正常使用，能够正常阅读和翻译文献

**Screenshots**
![image](https://user-images.githubusercontent.com/106907481/196470351-9752286a-210f-4127-9bbe-78529964be52.png)

**Environment**
 - OS: Windows11
 - Zotero Version：6.0.15
 - Addon Version：0.8.25

**Additional context**
期待回复，十分感谢！

**Comment by windingwind** [comment]
和插件无关的问题，我无法解决。建议重新安装zotero或在zotero论坛寻求帮助。

**Comment by vincenthao** [comment]
我也遇到了右侧翻译栏消失的问题，关闭翻译插件，重启zotero软件后，恢复正常使用。

**Comment by windingwind** [comment]
和插件无关，pdf标签记忆等都是zo的功能
