### ISSUE TITLE
[Bug]Complete the Title Here

### ISSUE THREAD

**Issue by ybc0508** [windingwind/zotero-pdf-translate#268]
您好！感谢您抽空查看此信息。

   遇到的问题是：无法正常使用翻译引擎“谷歌API(中国可用)”，显示“此翻译引擎不可用,可能是密钥错误,也可能是请求过快”（截屏图附后）

   想请问如何修复呢？目前该插件似乎没有可用的翻译引擎了。
![image](https://user-images.githubusercontent.com/116266070/196910891-731e7240-0c5a-4f6e-b0e9-ae63dd7a6b1e.png)
   盼回复！万分感谢！

**Comment by windingwind** [comment]
#6
