### ISSUE TITLE
[Feature]投票：是否为自动翻译功能添加辅助键

### ISSUE THREAD

**Issue by Trzeth** [windingwind/zotero-pdf-translate#269]
#266 New feat: Add mod key optine for auto translate

开启自动翻译功能选项后，会对任意选中的字段进行弹窗翻译。
但是，在我对句子标红时，在我随便选词分散注意力时，并不意味着我需要对这个词进行翻译。
因此，我提议添加一个辅助键，当按下辅助键时，才会对选中的字段进行翻译，否则，不显示弹窗。

![image](https://user-images.githubusercontent.com/17211844/197324912-40a5c07d-ae5e-4005-ba4d-bf16e3272483.png)

当然，你可以通过关闭自动翻译，并使用T或Ctrl+T组合键达到同样的目的。
唯一的区别是，添加辅助键在选中字段时不会显示翻译按钮（左图），而使用T键的方法会显示（右图）。

你可以对本条Issue下添加吧不同的emoji来进行投票，或留下你的宝贵意见。
👍：同意
👎：不同意
🤔/其他：都可以

**Comment by volatile-static** [comment]
我的建议是把选颜色的框也关掉

**Comment by windingwind** [comment]
> 我的建议是把选颜色的框也关掉

个人来说同意，如果弹框仍然存在，只是没有翻译按钮，似乎意义不是特别大？

**Comment by heyyxcusa** [comment]
个人建议可以在Preference里加一个选项满足不同人群需求。习惯用插件翻译个别单词，今天突然发现还需要点一下Translate才能翻译而不是自动翻译觉得没之前方便了...我看设置里有启用弹窗和自动翻译，如果不喜欢最右边（第三个）视图取消勾选这两项就可以了，而喜欢自动翻译弹窗的用户（我）不得不再点一下Translate感觉有点麻烦，因为有时候只用鼠标看文献不想多按键。

**Comment by windingwind** [comment]
开启自动翻译后，选中就会自动翻译。部分文献由于高级设置中的忽略语言，不会自动翻译

**Comment by heyyxcusa** [comment]
> 开启自动翻译后，选中就会自动翻译。部分文献由于高级设置中的忽略语言，不会自动翻译

谢谢！但今天突然发现设置中是勾选了开启自动翻译，高级设置忽略语言也是只设置了中文，但看英文PDF都是第二种只有翻译按钮，还以为已经按投票结果改成有辅助键的模式了...（刚试了10篇PDF只有1篇正常显示了）

**Comment by windingwind** [comment]
请在新issue讨论该问题，附上出现问题的文章pdf，设置界面截图
