### ISSUE TITLE
Is it possible to add the ability to display the results of multiple translation engines at the same time[Feature]

### ISSUE THREAD

**Issue by Saunak626** [windingwind/zotero-pdf-translate#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
Can you please discribe why you need this feature?

**Comment by fan291752035** [comment]
感觉是为了比较那个翻译的更好更准确，其实没啥用
