### ISSUE TITLE
[Feature] 希望支持通过代理服务器连接翻译引擎

### ISSUE THREAD

**Issue by du33169** [windingwind/zotero-pdf-translate#270]
**Is your feature request related to a problem? Please describe.**
众所周知Google翻译退出中国了，之前改hosts的方法目前（2022-10-22）已经失效，但是Google翻译的效果仍然是最好的。
目前要用的话只能通过全局代理才能连接，比较麻烦。

**Describe the solution you'd like**
希望支持通过代理连接翻译引擎，可以自己填写代理服务器地址。

**Describe alternatives you've considered**
略

**Additional context**
略

**Comment by windingwind** [comment]
https://www.zotero.org/support/kb/socks_proxy

**Comment by kettly1260** [comment]
但是这样会让所有流量都接入代理，能否只让该插件接入代理呢

**Comment by windingwind** [comment]
见更新日志。支持在密钥栏设置自定义url

**Comment by cjhonlyone** [comment]
@windingwind 抱歉打扰一下，我搜索了还是没有找到自定义url的介绍，可以告诉我自定义代理的介绍页面吗？万分感谢！

**Comment by windingwind** [comment]
1. 谷歌翻译的第三方网址，直接输入在密钥区域
2. 代理和第三方网址不一样。代理请通过代理软件设置
