### ISSUE TITLE
[Bug]在分割视图中无法翻译

### ISSUE THREAD

**Issue by linkfqy** [windingwind/zotero-pdf-translate#271]
**Describe the bug**
分割视图中选中文本，不会弹出弹窗，侧边栏也不会获取到选中的内容

**To Reproduce**
1. 右键页面选择split horizontally
2. 选中文本

**Environment**
 - OS: Windows 10
 - Zotero Version 6.0.15
 - Addon Version 0.8.28

**Comment by windingwind** [comment]
如果两侧均有选中文本，如何确定翻译哪一边？

**Comment by linkfqy** [comment]
> 如果两侧均有选中文本，如何确定翻译哪一边？

翻译最后划出的文本即可
