### ISSUE TITLE
[Feature]希望增加字节火山引擎的翻译api支持

### ISSUE THREAD

**Issue by richardodliu** [windingwind/zotero-pdf-translate#279]
首先非常感谢开发者对于各类翻译APi的支持，经过对于各类软件的长期使用和体验，个人感觉字节的火山翻译引擎质量比较可靠，希望可以加入对这个API的支持。
链接如下：
https://www.volcengine.com/docs/4640/130872

**Comment by richardodliu** [comment]
> 首先非常感谢开发者对于各类翻译APi的支持，经过对于各类软件的长期使用和体验，个人感觉字节的火山翻译引擎质量比较可靠，希望可以加入对这个API的支持。 链接如下： https://www.volcengine.com/docs/4640/130872

**Comment by windingwind** [comment]
See https://github.com/windingwind/zotero-pdf-translate/issues/217
