### ISSUE TITLE
您的IP“121.33.***.***”存在异常请求，且已被系统自动加入黑名单，请不要恶意进行爬取数据，谢谢。

### ISSUE THREAD

**Issue by HMethod** [windingwind/zotero-pdf-translate#28]

**Comment by HMethod** [comment]
我想请教一下，我是正常的使用啊，怎么就成爬去数据了呢。。。请问怎么解决呢

**Comment by HMethod** [comment]
使用的是小牛翻译的引擎

**Comment by windingwind** [comment]
申请一个账户并使用需要secret的翻译器（如微软，彩云，百度等）将有更稳定的体验。小牛使用的是其网页翻译的接口，存在被封ip的可能性

**Comment by HMethod** [comment]
另外，请问使用百度的API的话，不需要填写app ID吗？我尝试填百度的密钥，好像也用不了

**Comment by HMethod** [comment]
应该说是插件只提供了密钥的输入框，没有ID的输入框，整懵了

**Comment by HMethod** [comment]
已解决，谢谢！！！

**Comment by zyx990921** [comment]
你好，我的小牛翻译也出现了这个问题，请问你是怎么翻译的~还能继续用小牛翻译吗？呜呜

**Comment by HMethod** [comment]
> 你好，我的小牛翻译也出现了这个问题，请问你是怎么翻译的~还能继续用小牛翻译吗？呜呜

我使用百度翻译了，申请一个API就好了，Lauguage Settings那里有教你怎么设置 [https://github.com/windingwind/zotero-pdf-translate#lauguage-settings]

**Comment by zyx990921** [comment]
谢谢谢谢好人一生平安！

**Comment by Syzygy33** [comment]
> 已解决，谢谢！！！

请问怎么解决的啊

**Comment by Syzygy33** [comment]
> > 已解决，谢谢！！！
> 
> 请问怎么解决的啊

已解决 应该之前是bug

**Comment by windingwind** [comment]
> > > 已解决，谢谢！！！
> > 
> > 
> > 请问怎么解决的啊
> 
> 已解决 应该之前是bug

I'll close this issue.
