### ISSUE TITLE
[enhancement]翻译结果的中文太小了，可以放大字体吗

### ISSUE THREAD

**Issue by Cubxx** [windingwind/zotero-pdf-translate#280]
每次翻译的时候，翻译结果字体都非常小，很难看清

希望可以提供放大字体的按钮

**Additional context**
![image](https://user-images.githubusercontent.com/109600351/198580379-d3ad48ae-fe6a-4cd9-88f7-1629a3ad7634.png)

**Comment by windingwind** [comment]
#6
