### ISSUE TITLE
[Feature]希望可以增加“自动翻译”的临时快捷键

### ISSUE THREAD

**Issue by CMD-cmd** [windingwind/zotero-pdf-translate#284]
- 功能需求：按住某个修饰键（如 `cmd`、`ctrl`），可以临时打开自动翻译
- 应用场景：当我在阅读文献时，不希望每次光标选中的文本都被翻译（光标选中只是给自己的视觉引导），而如果有句子想要临时翻译一下，可以直接按住`cmd`、`ctrl`等用光标去划句子，这样就不用先拿鼠标去点击开启“自动翻译”了

**Comment by windingwind** [comment]
翻译快捷键ctrl+T。关闭自动翻译即可
