### ISSUE TITLE
自动翻译批注 能不能设置不自动添加音标

### ISSUE THREAD

**Issue by verigle** [windingwind/zotero-pdf-translate#286]
自动翻译批注功能 希望可以设置不添加音标
音标字符占用两行宝贵的批注空间，却导致翻译的中文内容被折叠，影响一眼看到翻译内容，希望可以设置关闭自动添加音标，
或者能不能把音标放到内容的最后显示？

**Comment by verigle** [comment]
![image](https://user-images.githubusercontent.com/32769358/199990158-feb7db3f-9f4b-45f0-b1bc-eb81f1a88cf4.png)
不能自动显示出来批注，却被音标占用了位置

**Comment by windingwind** [comment]
关闭词典翻译即可。

**Comment by dfjs458** [comment]
> 

请问怎么显示音标呀

**Comment by dfjs458** [comment]
> ![image](https://user-images.githubusercontent.com/32769358/199990352-d44e570d-322a-48cb-b014-37dbe2377724.png)
> 
> 不能自动显示出来批注，却被音标占用了位置

请问这是选的哪个翻译词典呀

**Comment by yanchenmochen** [comment]
选择有道词典，是可以的
