### ISSUE TITLE
[Bug]不能自动翻译

### ISSUE THREAD

**Issue by CXl1998** [windingwind/zotero-pdf-translate#287]
**Describe the bug**
选中PDF文字后不会自动翻译，

**Expected behavior**
选中后自动翻译

**Environment**
 - OS: Windows 11
 - Zotero版本6.0.16
 - 插件版本0.8.29，

**Comment by windingwind** [comment]
检查使用的翻译引擎是否正常工作。

**Comment by CXl1998** [comment]
正常，并且点翻译按钮是可以翻译出来的

**Comment by windingwind** [comment]
检查首选项-翻译设置是否开启自动翻译。

**Comment by windingwind** [comment]
是否有更新？若无将关闭问题

**Comment by CXl1998** [comment]
已更新并设置，问题依旧存在

**Comment by chstu1** [comment]
我的也不可以自动翻译，而且刚开始打开的时候,通常文献选中文字后不会出现弹窗，侧栏也不并没有“翻译”功能，需要切换一下主页，再跳回文献页面，侧栏才会出现“翻译”，但仍不能自动翻译。我的zotero是最新版，pdf translate是0.9.2。
无论是句子段落还是单词都需要点击才可以翻译。

**Comment by windingwind** [comment]
请测试v0.9.3

**Comment by MOHANWANANOUtaiyang** [comment]
![image](https://user-images.githubusercontent.com/121038068/209302852-280046f9-b971-48d1-a6ba-becb1e1227b4.png)
同样无法自动翻译

**Comment by Chikit-L** [comment]
![QQ截图20230130161543](https://user-images.githubusercontent.com/57130625/215475913-5baad4e3-d953-4349-bca3-b0f6ae2200ab.png)
我同样遇到了这个问题，昨天还可以进行自动翻译，今天突然不能使用。
translate 0.9.8
Zotero版本6.0.20

**Comment by windingwind** [comment]
@MOHANWANANOUtaiyang 更新插件，关于翻译引擎请看主页

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
