### ISSUE TITLE
希望新增划词翻译窗口移动的功能

### ISSUE THREAD

**Issue by tughv** [windingwind/zotero-pdf-translate#290]
有时候划词翻译出来的窗口挡住了其他内容，希望这个窗口能够用鼠标移动到其他位置

**Comment by Trzeth** [comment]
可以尝试侧边栏代替，或用侧边栏里的独立窗口功能。

**Comment by tughv** [comment]
想要中英文对照看侧边栏不是很方便

**Comment by volatile-static** [comment]
> 想要中英文对照看侧边栏不是很方便

所以说独立窗口能隐藏所有按钮也不错
