### ISSUE TITLE
[Feature] Question about a possible new language in the add-on: Kinyarwanda

### ISSUE THREAD

**Issue by kinyarwanda** [windingwind/zotero-pdf-translate#291]
**Question:
I hope this question has not been asked too many times and I am missing the answser. I wonder how to add another language possibility, in my case Kinyarwanda, which exists in google translate. 

Thanks in advance!
Best,

**Comment by windingwind** [comment]
Sorry I'm not familiar with Kinyarwanda. Could you please check if the language `Swahili - Kenya` is what you want?

**Comment by kinyarwanda** [comment]
Hello. Thanks for your answer. Swahili-Kenya would also be a very interesting add-on (with more than 200 million speakers!).
Kinyarwanda is another language, it shoud be Kinyarwanda-Rwanda. I think the source language (SL) is rw on Google translate.

Best,

**Comment by windingwind** [comment]
@kinyarwanda 
Please try v0.9.1. Sorry for the missing of this language. I copied the language-culture codes from somewhere and it might not be correct.

I saw the Swahili-Kenya is sw-KE in http://www.lingoes.net/en/translator/langcode.htm . Not sure if this website is correct? Currently, I use `rw`.
