### ISSUE TITLE
[Bug]不能识别pdf字符 

### ISSUE THREAD

**Issue by Fhj-id** [windingwind/zotero-pdf-translate#293]
**Describe the bug**

**To Reproduce**
1. Go to 'Zotero'
2. click the paper
3. translate

**Expected behavior**
translate successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/60789585/201511612-4ad4059e-56a9-49f9-948a-85afcef1febe.png)
![image](https://user-images.githubusercontent.com/60789585/201512008-9812d447-19f0-46c5-bee8-12331ae817a3.png)

**Environment**
 - OS: Windows
 - Zotero Version:6.0.18
 - Addon Version:0.9.0

**Additional context**
目前只有这一篇文献出现问题 文献DOI: 10.1117/12.867648 
翻译栏显示:TypeError: res is null

**Comment by volatile-static** [comment]
这篇文章在我这边测试没有任何问题

**Comment by Fhj-id** [comment]
谢谢，那可能是我的设备问题。
&nbsp;


Mr.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月13日(星期天) 下午4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [windingwind/zotero-pdf-translate] [Bug]不能识别pdf字符  (Issue #293)





 
这篇文章在我这边测试没有任何问题

**Comment by yeeus** [comment]
我也遇到了这个问题。
请问您解决了吗？

**Comment by Fhj-id** [comment]
解决了，应该是浏览器下载的pdf经过Zotfile的重命名移动和scihub自动下载的文件冲突了。重下一次pdf，我的目录下有俩个pdf，有一个能看一个不能看，删除那个不能看的就可以了&nbsp;


Mr.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月14日(星期一) 上午8:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [windingwind/zotero-pdf-translate] [Bug]不能识别pdf字符  (Issue #293)





 
我也遇到了这个问题。
 请问您解决了吗？
