### ISSUE TITLE
[Feature]希望添加科大讯飞搜翻译引擎

### ISSUE THREAD

**Issue by americanvain** [windingwind/zotero-pdf-translate#294]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
添加科大讯飞翻译引擎
1.接口文档（必看）：https://www.xfyun.cn/doc/nlp/xftrans/API.html
按照该文档可以添加接口

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by MuiseDestiny** [comment]
> 我最近比较忙，欢迎有意向的朋友贡献代码。可能近期没空做

加入了
