### ISSUE TITLE
翻译大段英文时，不能自动识别pdf行号

### ISSUE THREAD

**Issue by wuyinbuquan97** [windingwind/zotero-pdf-translate#296]
在我们进行pdf长短翻译时，自动把行号加入到翻译内容中，导致翻译准确度大幅下降

**Comment by windingwind** [comment]
选取行为与pdf有关，与插件无关。

**Comment by wuyinbuquan97** [comment]
是的，我的意思是您是否可以优化选中的结果，比如在大段选取之后，首先检查选区的内容多行首字符是否是连续的数字，如果是自动把这些数字去掉之后再导入近翻译区进行翻译，我这个只是一个小建议，谢谢回复
