### ISSUE TITLE
为什么选中目标语言为中文，结果翻译之后是英文解释，如图

### ISSUE THREAD

**Issue by yulu2199** [windingwind/zotero-pdf-translate#297]
![image](https://user-images.githubusercontent.com/99959985/202081920-34e80477-de9c-484f-9c54-e2dc6b59286b.png)

**Comment by windingwind** [comment]
单个词语开启了词典翻译，不同词典支持语言不同。请在首选项中设置你需要的词典语言，或关闭词典。
