### ISSUE TITLE
Microsoft Translate: Microsoft secret

### ISSUE THREAD

**Issue by dwl-sdca** [windingwind/zotero-pdf-translate#3]
I don't understand this process. I've used Microsoft translate from the web. Please provide further guidance on your Quick Start Guide about how to format a proper Language Parameter for Microsoft Translate. I am completely naive about the function of "secret"  and couldn't find an explanation after a search of the web.

I'm completely without any experience with the programming involved in this plugin. Thus, what I'm about to suggest may be impossibly difficult or impossible. Could you set a PDF Translate service where the user enters the 2-letter ISO code for the source language and the code for the target language and automatically generate the language parameter string?

**Comment by windingwind** [comment]
Thanks for this issue!  
Here's the detailed 5 steps of getting your own Microsoft translate secret:  
1. Open https://azure.microsoft.com/en-us/free/cognitive-services/ and click `start free`. Login your Microsoft Account or create a new one. Select the free subscription for your account.
![image](https://user-images.githubusercontent.com/33902321/157784190-0b8e7d93-79d5-4d30-a272-c14e2fe97cf2.png)

2. Open https://portal.azure.com/#create/Microsoft.CognitiveServicesTextTranslation  
![image](https://user-images.githubusercontent.com/33902321/157785103-3fda6893-94e6-4d60-817b-5b9cc190442a.png)

3. Click `Next`. You don't have to change anything in the Identity and Tags. Check status and click create.
![image](https://user-images.githubusercontent.com/33902321/157785351-e7e6b784-b16b-46a0-b560-8fcc2f767880.png)

4. Wait for the service ready. You can see your new translate service in your Azure homepage. https://portal.azure.com/#home
![image](https://user-images.githubusercontent.com/33902321/157785519-b7ad07cc-1781-4011-8430-fbe73563a9fb.png)

5. Click the transltor shown above.
![image](https://user-images.githubusercontent.com/33902321/157785637-6c3ec9f8-8c19-4bc6-98ee-2afdfeed1c72.png)

Congretulations! Your get the secret in your clipboard now.

Replace the default secret in Zotero Preferrence. Don't forget to click `OK` before leave.
![image](https://user-images.githubusercontent.com/33902321/157785955-1fb787e9-fc5d-4ede-9252-fa0aaf6b0a2a.png)

**Comment by he-hai** [comment]
Thanks, a nice tool. I think maybe use the word "key" like in the step 5 would make it easier to understand.

**Comment by windingwind** [comment]
> Thanks, a nice tool. I think maybe use the word "key" like in the step 5 would make it easier to understand.
Updated. Thanks!

**Comment by xiaooomd** [comment]
My version is zotero7 beta68. I followed your steps to apply for Microsoft api. The application shows that it is not available. Have you ever encountered this kind of problem?          The error is as follows：  https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=zh-CN failed with status code 401

**Comment by z1352367587** [comment]
> 我的版本是 zotero7 beta68。我按照您的步骤申请了 Microsoft api。应用程序显示它不可用。你有没有遇到过这种问题？错误如下：https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=zh-CN failed，状态码为 401 配置如图所示![image](https://private-user-images.githubusercontent.com/51357799/313905750-88f1edea-d6f3-482c-a2ba-c34ecf321e9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTc0MjIsIm5iZiI6MTczMDc5NzEyMiwicGF0aCI6Ii81MTM1Nzc5OS8zMTM5MDU3NTAtODhmMWVkZWEtZDZmMy00ODJjLWEyYmEtYzM0ZWNmMzIxZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA4NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYmQ4OGFjM2YyOGRhYzU1ZGNhNmUzZTg5ZGZiODNhNDZmOWJiMjAxNzgxM2MyZmIwNjY4N2Q4ZmQxM2RlYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xANP7B2niI2I_7nNahGrCmAz1MiQBYijhSHg4BVbrsM)

区域要选全球global

**Comment by bigben446** [comment]
显示key的位数不对？

<img width="485" alt="2f9ee15748ac09025c28b44e109ff3b" src="https://github.com/user-attachments/assets/e3fdecd6-3dd2-4c50-a9c3-8a2ff86c3c6f">
