### ISSUE TITLE
[Feature] 逐句对照

### ISSUE THREAD

**Issue by hqzqaq** [windingwind/zotero-pdf-translate#300]
![image](https://user-images.githubusercontent.com/51304606/203201723-22473ddc-5b88-473a-9049-e5e46eb86d02.png)
希望这样的功能：在翻译大段内容的时候，在翻译窗口时，鼠标选中一句话，zotero能高亮显示英文句子
![image](https://user-images.githubusercontent.com/51304606/203202675-f8fc27e0-5032-4db8-84c1-811da5da6d2a.png)
像是百度翻译这样的效果

**Comment by windingwind** [comment]
不是所有翻译引擎都有逐句对应功能，因此对大多数翻译服务来说可能无法做到。
如果有人有兴趣为具有逐句对应的翻译服务添加对照功能，欢迎PR

**Comment by MuiseDestiny** [comment]
@hqzqaq 
现在的条件下，已经实现了弹窗翻译核心功能。如果按照你图中交互方式，应该比较难实现主句对照，因为本身PDF要翻译的文字已经是选区，已经被高亮，再高亮上再高亮挺别扭。另外，翻译的中文被安排在一个textbox下也不方便进行样式定义。如果实现这个功能在新的窗口能接受吗，考虑到这个功能并不是高频使用的功能。等做出来你看下。

**Comment by hqzqaq** [comment]
> @hqzqaq 现在的条件下，已经实现了弹窗翻译核心功能。如果按照你图中交互方式，应该比较难实现主句对照，因为本身PDF要翻译的文字已经是选区，已经被高亮，再高亮上再高亮挺别扭。另外，翻译的中文被安排在一个textbox下也不方便进行样式定义。如果实现这个功能在新的窗口能接受吗，考虑到这个功能并不是高频使用的功能。等做出来你看下。

非常感谢您的开发，我都以为已经被遗忘了，感谢您的付出

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/219991371-bc86571e-ac4d-4167-9682-803ba3ffc520.png)

类似这样，当然UI我会优化

**Comment by MuiseDestiny** [comment]
因为在PDF里实现这个功能，涉及到缩放PDF，选区可能看不见，我觉得放在一个新的窗口比较好设计好实现。

**Comment by hqzqaq** [comment]
> 因为在PDF里实现这个功能，涉及到缩放PDF，选区可能看不见，我觉得放在一个新的窗口比较好设计好实现。

确实，这样挺好的 :+1::+1::+1:

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/219999332-d479d62c-87f4-4e8e-b9e4-db48db75f7a7.png)

手动实现的，所以可以比百度翻译分的更细。


https://github.com/MuiseDestiny/zotero-style/releases/tag/2.2.1在这里下载，然后需要你帮忙测试下。

原因：由于是手动分割句子，不是基于API，对于英文从`.`分割，但对于`Fig. 2`的点要特殊处理，目前只考虑了Fig、Figure、Table，其它没考虑到的情况需要测试过程中发现，最后我再PR。如果路过此处也想测试，可以通过上述链接下载。

**Comment by MuiseDestiny** [comment]
https://user-images.githubusercontent.com/51939531/220005971-36fb5413-439f-4cfb-94d1-641b0cc89350.mp4

使用方法：
选中打段文字，按`Shift+Tab+P`选择命令即可。

**Comment by hqzqaq** [comment]
👌

**Comment by hqzqaq** [comment]
貌似需要先选中文字之后，点击翻译，之后按**shift + tab +p** 才能显示这个窗口
![image](https://user-images.githubusercontent.com/51304606/220006812-6925c73b-484e-44db-8788-50d986f37481.png)
直接选中是不行的
![image](https://user-images.githubusercontent.com/51304606/220006890-0ffd35e8-b834-416b-8427-e549385b7094.png)

**Comment by MuiseDestiny** [comment]
> 貌似需要先选中文字之后，点击翻译，之后按**shift + tab +p** 才能显示这个窗口 ![image](https://user-images.githubusercontent.com/51304606/220006812-6925c73b-484e-44db-8788-50d986f37481.png) 直接选中是不行的 ![image](https://user-images.githubusercontent.com/51304606/220006890-0ffd35e8-b834-416b-8427-e549385b7094.png)

对的，这个后面都可以优化，先手动点击翻一下。

**Comment by hqzqaq** [comment]
还有个问题，再进行上面的操作之后，再选中其它文字，点击翻译，再**shitf + tab + p** 留下的还是上一步的翻译的文字 
![image](https://user-images.githubusercontent.com/51304606/220008638-e87d2b7c-9705-4a47-8964-cbb67a193c86.png)
需要按esc推出，再进入 translate Sentences

**Comment by MuiseDestiny** [comment]
> 还有个问题，再进行上面的操作之后，再选中其它文字，点击翻译，再**shitf + tab + p** 留下的还是上一步的翻译的文字 ![image](https://user-images.githubusercontent.com/51304606/220008638-e87d2b7c-9705-4a47-8964-cbb67a193c86.png) 需要按esc推出，再进入 translate Sentences

好的，等待新的翻译结果出来后再按shift p试试。

**Comment by MuiseDestiny** [comment]
也可以对UI排版等等提建议。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.2.1
重新下载就修复bug了，然后可以调节宽度高度。目前默认上下排版，也支持左右，等合并后写进首选项就可以了。

![image](https://user-images.githubusercontent.com/51939531/220082678-7eb28ac7-80b2-4c07-a25e-24bedae127d0.png)

**Comment by hqzqaq** [comment]
> 好的，辛苦您了。
