### ISSUE TITLE
[Bug]长句翻译无法正确识别单词，两三个单词黏在一起影响准确度

### ISSUE THREAD

**Issue by kuailexiaogou** [windingwind/zotero-pdf-translate#302]
无法正确识别单词之间的间隙，多个单词黏在一起，导致翻译准确度下降。

1. Go to zotero
2. Click on a pdf
3. Scroll down to a long sentence

应该每个单词分开准确翻译的，pdf是非扫描版的，单词识别应该没有问题才对

<img width="863" alt="b1950b121af025cc45b84230012038f" src="https://user-images.githubusercontent.com/118895675/203527649-c6225e76-195f-4781-98aa-0c8a890a9295.png">

 - OS: Windows
 - Zotero 6.0.18
 - Addon 0.9.1

**Comment by windingwind** [comment]
与PDF有关，即使非扫描版也可能在分发等环节错误转换
