### ISSUE TITLE
[Bug]部分词条标题翻译错误，翻译成其他词条内容；部分词条无法翻译；部分词条翻译不显示

### ISSUE THREAD

**Issue by bigxixiLin** [windingwind/zotero-pdf-translate#306]
zotero版本6.0.18；插件版本0.9.4
翻译错误，翻译为其他词条内容
![YLW%M6)5L6JZ}RY2 4LV1_F](https://user-images.githubusercontent.com/116795958/204078080-8ca91b6e-ed57-48a4-8298-63a5d3c49a25.png)

部分词条无法翻译：
![QWHZJK1`8WELHG1EZHUPC(S](https://user-images.githubusercontent.com/116795958/204078303-d2550124-3278-4186-aff0-3b546348d7ff.png)
在右侧信息栏的短标题删除abc后才能重新翻译（正常情况下，abc是跟着翻译内容的，但我的只有蓝色框框里面的abc）

部分词条翻译不显示：
两种情况
一种是空白，类似词条无法翻译的情况，但短标题处仍然正常翻译
另一种是显示原英文标题
![NQSEC1 FN257I~USSEUSP X](https://user-images.githubusercontent.com/116795958/204078412-8ee58c41-d414-49e3-96ad-95a08183a096.png)

**Comment by windingwind** [comment]
请问插件版本是多少

**Comment by bigxixiLin** [comment]
> 请问插件版本是多少
zotero版本6.0.18；插件版本0.9.4

**Comment by windingwind** [comment]
是否有可稳定复现的步骤？例如，即使重启zotero后什么也不做，也会出现该问题，还是在特定情况下出现？

**Comment by bigxixiLin** [comment]
> 

重启试过了，还是有问题，操作就是和正常使用插件的步骤一样，右键选择标题翻译

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
