### ISSUE TITLE
[Feature]希望能够实现源语言自动检测

### ISSUE THREAD

**Issue by tony2038** [windingwind/zotero-pdf-translate#307]
很多翻译引擎都支持源语言自动检测的功能，希望在这个插件中也能支持源语言自动检测
或者能提供一个源语言选择的菜单，这样不用每次去修改设置

**Comment by windingwind** [comment]
右侧栏可以选择语言

**Comment by TensorABC** [comment]
> 右侧栏可以选择语言

对于哲学类原著可能会遇到多种语言并存的情况，阅读者在此并没有先验地知道语言种类的义务，如果使用搜索引擎查询，那便等同于没有使用插件翻译T-T
