### ISSUE TITLE
Deepl 翻译添加了密钥还是提示错误

### ISSUE THREAD

**Issue by nuxynumy** [windingwind/zotero-pdf-translate#31]
[Request Error]
Engine not available, invalid secret, or request too fast.
Please consider using another translate engine or posting issue here: https://github.com/windingwind/zotero-pdf-translate/issues
        Error: HTTP POST https://api.deepl.com/v2/translate failed with status code 403

**Comment by windingwind** [comment]
Could you please follow the debug steps here: https://github.com/windingwind/zotero-pdf-translate/issues/6#issuecomment-1078768099

**Comment by nuxynumy** [comment]
(3)(+0000001): Opening E:\zotero\storage\C4EMNEDY\Antala - 2021 - Design, development and performance evaluation of .pdf

(3)(+0000001): Notifier.trigger('open', 'file', [1148]) called [observers: 4]

(3)(+0000005): Notifier.trigger('add', 'tab', [tab-C2zJaPub], {"tab-C2zJaPub":{"itemID":1148}}) called [observers: 5]

(3)(+0000003): Notifier.trigger('select', 'tab', [tab-C2zJaPub], {"tab-C2zJaPub":{"type":"reader"}}) called [observers: 5]

(3)(+0000006): ZoteroPDFTranslate: open file event detected.

(3)(+0000000): ZoteroPDFTranslate: open file event detected.

(3)(+0000001): ZoteroPDFTranslate: Update Translate Panels

(3)(+0000029): Refreshing item box

(3)(+0000059): Getting contents of E:\zotero\storage\C4EMNEDY\.zotero-pdf-state

(3)(+0000124): ZoteroPDFTranslate: buildSideBarPanel

(3)(+0000085): itemTree.render(). Displaying Item Tree

(4)(+0000028): SELECT itemID FROM items WHERE (itemID NOT IN (SELECT itemID FROM deletedItems) AND itemID NOT IN (SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)) AND itemID NOT IN (SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems))) AND itemID IN (SELECT itemID FROM items WHERE (libraryID=?)) AND itemID IN (SELECT itemID FROM items WHERE (itemTypeID IN (SELECT itemTypeID FROM itemTypesCombined WHERE typeName=?))) [1, 'note']

(3)(+0004543): ZoteroPDFTranslate: onTranslate

(3)(+0000001): ZoteroPDFTranslate: buildPopupPanel

(3)(+0000002): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000009): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000002): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): HTTP POST "auth_key=82caa6ff-8ea6-37cc-cbe1-adb19feaa07e&text=Sapota fruit (Achras Zapota L.) is very important fruit crop of India. India is the largest producer of sapota with 1.2 MT production and cultivated on 0.10 Mha in 2017–2018 (Anonymous 2020). Sapota is high on calories providing 83 cal per 100 g. A good source of dietary fibre, the pulp of this fruit functions as an excellent laxative. It is loaded with a rich array of vitamins A, C, niacin, folate and pantothenic acid and minerals iron, potassium and copper. The &source_lang=EN&target_lang=ZH" to https://api.deepl.com/v2/translate

(1)(+0003731): HTTP POST https://api.deepl.com/v2/translate failed with status code 403

(3)(+0000002): Error: HTTP POST https://api.deepl.com/v2/translate failed with status code 403 Error: HTTP POST https://api.deepl.com/v2/translate failed with status code 403 Zotero.HTTP</this.UnexpectedStatusException@chrome://zotero/content/xpcom/http.js:21:18 Zotero.HTTP</this._requestInternal/xmlhttp.onloadend<@chrome://zotero/content/xpcom/http.js:522:25 From previous event: Zotero.HTTP</this._requestInternal@chrome://zotero/content/xpcom/http.js:266:20 Zotero.HTTP</this.request@chrome://zotero/content/xpcom/http.js:156:47 deepl/<@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:54:24 safeRun@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:295:22 requestTranslate@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:319:23 deepl@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:52:20 deeplpro@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:42:20 getTranslation@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:835:18 callTranslate@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:815:25 onSelect@chrome://zoteropdftranslate/content/scripts/zoteropdftranslate.js:788:13

(3)(+0000001): ===>false<=== (boolean)

(3)(+0000000): ZoteroPDFTranslate: Translate return false

(3)(+0000000): ZoteroPDFTranslate: buildPopupPanel

(3)(+0000002): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000002): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000000): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000000): ZoteroPDFTranslate: updatePopupStyle

**Comment by windingwind** [comment]
your key is not complete.

**Comment by iamzhujiaqi** [comment]
sorry I copy the key from deepl website, but it still shows "[Request Error]
Engine not available, invalid secret, or request too fast."

**Comment by windingwind** [comment]
> sorry I copy the key from deepl website, but it still shows "[Request Error] Engine not available, invalid secret, or request too fast."

Use a valid key and  choose the correct plan(free or pro)

**Comment by iamzhujiaqi** [comment]
你好，我已经收到您的邮件，会尽快查收并回复:D
