### ISSUE TITLE
[Feature] Hello! l love this plugin

### ISSUE THREAD

**Issue by newgenes** [windingwind/zotero-pdf-translate#313]
I am using this plugin just fine.
However, there is no Korean dictionary, so it is a bit inconvenient.
Can't you add a Korean dictionary in advance?
Thank you for always.

**Comment by windingwind** [comment]
Thanks for your love. Any suggestions for the Korean dictionary?

Better to be accessible in the browser and not require login.

**Comment by volatile-static** [comment]
> Any suggestions for the Korean dictionary?

Recommendation required.

**Comment by newgenes** [comment]
Naver dictionary is common in koreaI think almost Korean want to use naver dictionary.Thanks you!Sent from my iPhoneOn Dec 12, 2022, at 12:59 PM, volatile-static ***@***.***> wrote:﻿

Any suggestions for the Korean dictionary?

Recommendation required.

**Comment by newgenes** [comment]
Is it difficult to put in a dictionary?

thanks

**Comment by windingwind** [comment]
Currently, I am focusing on migration from Zotero 6 to Zotero 7, which requires very basic changes. Before this is done and the new version is compatible with both Z6 and Z7, I would not have time to add new features.

PRs are still welcomed, as long as they can work with the current plugin and Zotero.

**Comment by newgenes** [comment]
Then there is no choice
I still use this plugin and am very satisfied.
Thank you.

**Comment by windingwind** [comment]
The new version 1.0.0 is officially released. After 1-2 weeks of testing and bug fixes, I'll begin to work on this thread.

**Comment by newgenes** [comment]
After seeing this article, I immediately reinstalled the program and updated it, but it disappeared.

WOW T_T

**Comment by windingwind** [comment]
Hi, what does `disappeared` means?

**Comment by newgenes** [comment]
this plugin "zotero pdf translate"

so.. i recoveryed plugin version to old version

**Comment by windingwind** [comment]
Weird. When does the disappearance happen? During the update, or after restarting? Is it not visible in addon manager, or the translation panel is invisible?

**Comment by windingwind** [comment]
And, what is your Zotero version?

**Comment by newgenes** [comment]
The current version is 6.0.21, and I reinstalled the program several times and restarted it. In the end, I had no choice but to go back to the old version.

**Comment by windingwind** [comment]
So the plugin just disappears in tool->addon manager? Download from Github release and install also fails?

**Comment by newgenes** [comment]
It is not to update plugin in addon manager, so I downloaded plugin from Github..

**Comment by windingwind** [comment]
Please let's make the problem clear, `disappear` seems to be one of the most serious allegations to me. LOL

1. When does the disappearance happen? After installing the xpi of version 1.0.0 from Github?
2. What does the disappearance looks like? Disappear from the addon manager, without any warnings?

**Comment by windingwind** [comment]
I realized the prefs pane is missing when locale=en-US. The 1.0.1 should fixed this bug.

**Comment by newgenes** [comment]
thanks a lot

**Comment by newgenes** [comment]
Genius please help me. 
I installed version 1.0.1, and then I challenged another problem .
  
![2023-02-05_11-26-07](https://user-images.githubusercontent.com/117580803/216798370-1d797a68-b917-430b-957b-aa72b8d9b79f.jpg)

Fonts are not changed.

**Comment by windingwind** [comment]
Could you please show me the screenshot of preference settings page of this plugin, containing the font settings?

**Comment by newgenes** [comment]
![2023-02-05_17-15-00](https://user-images.githubusercontent.com/117580803/216808643-4c56aa4a-df24-4135-9f85-31b31b540073.jpg)
![2023-02-05_17-15-15](https://user-images.githubusercontent.com/117580803/216808652-565e3e28-649e-41ba-af49-42909d8cd78c.jpg)

**Comment by newgenes** [comment]
AND I Think auto translation is better than click the button

**Comment by newgenes** [comment]
I found the cause of error.
If I do not check 'Use Dictonary~~" check box, I can not change font size and line height.
I checked box, I solved problem by checking the checkbox.

**Comment by windingwind** [comment]
Opps, I will check that.

You can enable auto translation. Does this function works in the latest version?

**Comment by newgenes** [comment]
I am using latest version 1.0.1 but I can not find funtion of auto translation..
