### ISSUE TITLE
标题翻译和摘要翻译无法使用

### ISSUE THREAD

**Issue by haozhang86** [windingwind/zotero-pdf-translate#314]
zotero ：6.0.18， translate：0.9.5 

在库窗口，使用标题翻译和摘要翻译时，无反应，提示如此，请问该如何解决，问题出在哪里？
![image](https://user-images.githubusercontent.com/56377040/206841682-f860ea65-e7bb-424d-9691-9164f41c1d14.png)

**Comment by haozhang86** [comment]
version => 6.0.18, platform => Win32, oscpu => Windows NT 6.2; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.18, extensions => Zotero LibreOffice Integration (6.0.3.SA.6.0.18, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.18, extension), Zotero PDF Translate (0.9.5, extension), scite Plugin for Zotero (1.11.6, extension, disabled), ZoteroPreview (0.1.6, extension, disabled), Sci-Hub Plugin for Zotero (1.4.4, extension, disabled), ZoteroQuickLook (1.4.6, extension, disabled), Zutilo Zotero 工具箱 (3.10.0, extension, disabled), Zotero Debug Bridge (0.1.5, extension, disabled), Zotero PDF Preview (0.3.7, extension, disabled), Mdnotes for Zotero (0.2.3, extension, disabled), ZotFile (5.1.2.999, extension, disabled), Delitem (0.0.20, extension, disabled), Better BibTex for Zotero (6.7.42, extension, disabled), MarkDBConnect (0.0.20, extension, disabled), Jasminum (0.2.3, extension, disabled), Zotero IF Pro Max (4.5.1, extension, disabled), Zotero Better Notes (0.7.28, extension, disabled), Chartero (1.3.2, extension, disabled), Zotero更新影响因子 (0.95.4, extension, disabled)

(3)(+0007718): itemTree.render(). Displaying Item Tree

(3)(+0000016): Viewing item in pane 0

(3)(+0000008): Refreshing item box

(3)(+0002232): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(4)(+0000004): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000020): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000004): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000003): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(3)(+0000003): MIME type application/pdf cannot be handled internally

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(3)(+0001987): ZoteroPDFTranslate: onTranslateTitle, type=items

(3)(+0000236): ZoteroPDFTranslate: onSwitchTitle, true

(3)(+0000004): {}

(3)(+0001733): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000015): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000003): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(3)(+0000003): MIME type application/pdf cannot be handled internally

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1830, 'https://link.springer.com/10.1007/s13131-022-1995-3']

(3)(+0002327): ZoteroPDFTranslate: onTranslateAbstract, type=items

(3)(+0000026): {}

**Comment by windingwind** [comment]
请检查不自动翻译语言设置中是否忽略了选中条目的语言，或者是否已经被翻译过。

**Comment by haozhang86** [comment]
> 请检查不自动翻译语言设置中是否忽略了选中条目的语言，或者是否已经被翻译过。

好的，我尝试一下，感谢

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
