### ISSUE TITLE
fail to translate

### ISSUE THREAD

**Issue by schnappitle** [windingwind/zotero-pdf-translate#318]
**To Reproduce**
1. Go to 'PDF 阅读器'
2. Click on '划词翻译以及 ctrl + T'
3.等了很久之后更换翻译引擎后
5. 更换翻译引擎后
6. See the same error

**Expected behavior**
跟知云一样在几秒内出翻译结果

**Screenshots**
![error1](https://user-images.githubusercontent.com/120539838/207495996-9a7a5772-1847-41f8-8db2-63bd2aed29bd.png)

**Environment**
 - OS: Windows 10
 - Zotero Version(6.0.18)
 - Zotero PDF Translate Version(0.8.29)

**Comment by windingwind** [comment]
#6
