### ISSUE TITLE
[Feature]Limit free translation times for Niutrans, please.

### ISSUE THREAD

**Issue by NanFangZhe2020** [windingwind/zotero-pdf-translate#32]
Hi, bro. Sorry to bother you.
I need you help.
Because many users who use your plug-in are blocked by IP. And I'm one of them.
This will result in fewer people using your plug-in.
So, Please try to modify the limit.
thx, : )
Niutrans（小牛翻译）https://niutrans.com/

**Comment by windingwind** [comment]
Hi, I guess you didn’t see #6 and #28 .

Thanks for your concern. This IP block is from the Niu Trans, not me. This add-on only calls API for users.
Use a translate engine with secret instead, as I’ve suggested in #6 and #28 .

I have to remind you that I don’t make any profit from this add-on. How many people are using it is none of my business actually. I reply issues and make updates only for myself.

**Comment by NanFangZhe2020** [comment]
Allright, thx bro.
I am just giving you a suggestion.
