### ISSUE TITLE
[界面显示]mac版本翻译内容显示不全，希望优化改进！

### ISSUE THREAD

**Issue by danielheart** [windingwind/zotero-pdf-translate#322]
如下图所示，Mac版的默认翻译界面有部分显示不出来。如果要全部现实的话，则需要占用很宽的显示区域。希望可以改进！谢谢大佬！
![WX20221216-164920@2x](https://user-images.githubusercontent.com/68719683/208060852-88e4264b-dfc5-49c6-b720-77c38ca3c64e.png)
![WX20221216-165603@2x](https://user-images.githubusercontent.com/68719683/208061142-ca2dd25f-fd8a-4524-a45a-6ccac427abc1.png)

**Comment by FakeTrader** [comment]
英文状态下侧边栏设置项过宽。
替代方案：Preference / Translate / Advanced，取消勾选 Show Settings

**Comment by danielheart** [comment]
> 英文状态下侧边栏设置项过宽。 替代方案：Preference / Translate / Advanced，取消勾选 Show Settings

感谢FakeTrader的回复，问题已完美解决！
