### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by zys1346** [windingwind/zotero-pdf-translate#33]
请问是否可以增加一个功能，当识别为翻译的目标语言时则不显示翻译，比如设置英文翻译为中文时，对于中文论文进行划词时不显示翻译，或者增加一个翻译快捷键。谢谢！

**Comment by windingwind** [comment]
翻译快捷键为t，可以关闭自动翻译。检测语言很难做到

**Comment by zys1346** [comment]
OK，谢谢
