### ISSUE TITLE
取消自动切换至翻译面板

### ISSUE THREAD

**Issue by LamFTS** [windingwind/zotero-pdf-translate#330]
开发者你好，请问能不能不让插件自动切换到翻译面板呢？每次打开条目或者切换条目时，右侧的面板总是翻译，比如我同时打开了两篇文章，都切换到了参考文献条目，一旦切换到另一篇文章，或者从另一篇文章切换回来，之前打开的参考文献面板就会变成翻译，有没有办法实现切换条目时保持右侧面板之间的状态。
![图片](https://user-images.githubusercontent.com/53118840/209561452-7aff64d9-5673-4ad4-a0dd-d4985e8b63ed.png)

**Comment by windingwind** [comment]
https://zotero.yuque.com/staff-gkhviy/pdf-trans/ngu6mc

关闭自动聚焦

**Comment by LamFTS** [comment]
非常感谢。
