### ISSUE TITLE
[Bug]笔记翻译内容不显示

### ISSUE THREAD

**Issue by sylvesterww** [windingwind/zotero-pdf-translate#332]
环境：macOS，zetero6.0.19，[zotero-pdf-translate]0.98

问题：笔记翻译内容不显示

复现：
1.滑词翻译
2.添加笔记
3.如果已创建空白笔记，会显示在笔记添加英文和三个横杠，无创建空白笔记的话点击添加笔记无反应。

<img width="1369" alt="screenshot1" src="https://user-images.githubusercontent.com/78637425/210295725-260d64e7-5d62-42b9-a24f-1304fdcd4566.png">

**Comment by Sunzhiyu123** [comment]
我和你一样，Mac OS也是不行，但是在windows系统里却没问题，希望作者尽快修复。

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
