### ISSUE TITLE
[Feature]Support the Volcengine translate

### ISSUE THREAD

**Issue by timelic** [windingwind/zotero-pdf-translate#333]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
[火山翻译](https://translate.volcengine.com/translate?category=&home_language=zh&source_language=detect&target_language=en&text=)是一个字节跳动出品的翻译项目，现支持API调用。希望插件能支持火山翻译。

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by windingwind** [comment]
将不会支持，原因见历史issue

**Comment by windingwind** [comment]
有意愿欢迎pr，文档不全我目前不会去花时间尝试

**Comment by timelic** [comment]
> 有意愿欢迎pr，文档不全我目前不会去花时间尝试

明白，确实这家伙的文档很垃圾...
