### ISSUE TITLE
[Bug]Mac OS系统无法“添加翻译笔记”

### ISSUE THREAD

**Issue by Sunzhiyu123** [windingwind/zotero-pdf-translate#334]
**Describe the bug**
在PDF中选取所需要的文字，自动弹出翻译，并显示出“添加翻译笔记”的按钮，但是点击“添加翻译笔记”的按钮后，只能显示出原文，无法显示中文翻译。

**To Reproduce**
1. 选择需要翻译的文字
2. 弹窗中显示
![1672822139152](https://user-images.githubusercontent.com/114121128/210517534-67c89fe7-5dad-4712-9cae-e4986e9b06b1.jpg)
3. 点此此按钮
4. 右侧笔记中只能显示原文而无法显示翻译

**Expected behavior**
理应在右侧笔记中出现中文翻译。

**Screenshots**
![1672822265636](https://user-images.githubusercontent.com/114121128/210518297-d52b09fd-affd-4097-af2f-7bed106170ab.jpg)

**Environment**
 - OS: macOS 12.6.2
 - Zotero Version 6.0.19
 - Addon Version 0.9.8

**Additional context**

**Comment by Jenny-Qiu-941** [comment]
同样的问题~期待修复！
（这个插件真的好好用www

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
