### ISSUE TITLE
功能建议：选择英文显示“translate按钮”，点击按钮后可以只在右侧翻译窗口翻译

### ISSUE THREAD

**Issue by pisceswb** [windingwind/zotero-pdf-translate#336]
**Is your feature request related to a problem? Please describe.**
想对英文PDF进行详细阅读时，如果使用翻译弹窗会遮挡PDF内容，自动翻译不方便高亮标注，快捷键Ctrl+T的两个按键距离实在太远，不方便按。

**Describe the solution you'd like**
因此提一个功能建议：希望能够在选择英文内容后，在高亮颜色下显示“Translate”按钮，就像在中文文章中选择文本时显示的那样。但是按下“Translate”按钮后，可以选择不弹出翻译弹窗，在右侧的翻译窗口进行翻译。
这样，即不会有弹窗遮挡PDF内容，又不影响选择个别文本内容进行高亮（再次选择文本过程中，不按“Translate”按钮就不会触发翻译，已经翻译的内容一直都在右侧，可供参考比较原文），又不用按Ctrl+T这个不太方便的快捷键。

**Describe alternatives you've considered**

**Additional context**
这个一个非常棒的插件，感谢作者的辛苦付出！！
![1](https://user-images.githubusercontent.com/104658457/212532561-e2d528df-cc43-469c-aec6-8c536d5276df.png)

**Comment by pisceswb** [comment]
想到一个简单的实现方法：
1. 将“en”添加到“对特定语言文件关闭自动翻译”的设置中。
2. 如果您觉得以上建议是有益的功能的话，需要您增加一个设置选项，“当右侧翻译栏显示时，不弹出翻译弹窗”。这样就能够实现上述功能了。

**Comment by pisceswb** [comment]
另外，右侧翻译的上下部分的按键占用太大空间了，建议缩小或能够折叠，尽量扩大翻译内容的可用空间。谢谢！

再次感觉作者的辛苦付出！

**Comment by pisceswb** [comment]
> 想到一个简单的实现方法：
> 
> 1. 将“en”添加到“对特定语言文件关闭自动翻译”的设置中。
> 2. 如果您觉得以上建议是有益的功能的话，需要您增加一个设置选项，“当右侧翻译栏显示时，不弹出翻译弹窗”。这样就能够实现上述功能了。

不支持跨页拼接文本了；
当把侧边栏的Ctrl+T按钮隐藏后，即便把文本复制到右侧翻译窗口，也不能使用Ctrl+T进行翻译了

**Comment by windingwind** [comment]
关闭显示弹窗，并直接通过右侧按键翻译即可。
