### ISSUE TITLE
[Feature] Option to send shortened original quote to Note with full translation

### ISSUE THREAD

**Issue by forensmatt** [windingwind/zotero-pdf-translate#339]
**Is your feature request related to a problem? Please describe.**

I often translate whole pages, and sending/copying a translation to a note copies both original text and translation, which for long texts take up much unnecessary room in the note (and the annotation as well), since I only need the translation and the reference for the original text. 

**Describe the solution you'd like**
I would find it very useful to have the choice to "add to note" with a shortened original language quote and full translation  of the text. For example, for the original language, paste the first three words, an ellipsis (...) and the last three words, rather than the whole quote, followed by the full translation. So something like "Si los tres…diálogo o discusión.” [reference] + [full translation].
That will provide the link to the original reference and take much less room in the note.

I do this manually right now quite a bit, so any automation would be useful.

**Describe alternatives you've considered**

**Additional context**
Just greatly appreciate your work! This plugin is an amazing time saver.

**Comment by windingwind** [comment]
The plugin provides a setting `Replace Raw when Adding to Note`. When this is on, the add-to-note button will replace the original text with the translation result:

`raw(ref)translation` => `translation(ref)`
