### ISSUE TITLE
插件报错PDF阅读器未能正确打开

### ISSUE THREAD

**Issue by Frozen-hc** [windingwind/zotero-pdf-translate#343]
**Describe the bug**
插件报错：The PDF reader is not loaded correctly and the translate tools will not work on this page. Please reopen this PDF attachment.
之后翻译插件无法使用。

**To Reproduce**
重启软件后未能复现。在其他Issues下有duofengzhiling评论原因为一次性打开太多文献，链接：https://github.com/windingwind/zotero-pdf-translate/issues/214

**Screenshots**
![Snipaste_2023-01-24_17-53-51](https://user-images.githubusercontent.com/55055205/214265051-3492440e-2b08-43fd-b651-c1a27200c885.png)

**Environment**
 - OS: Windows
 - Zotero Version: 0.8.8
 - Addon Version: 0.9.8

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
