### ISSUE TITLE
[function suggestion]Hope to add the function of adjusting font size

### ISSUE THREAD

**Issue by YangQiGuiKong** [windingwind/zotero-pdf-translate#345]
**Is your feature request related to a problem? Please describe.**
Sometimes, the fonts size in the window of translate tool is too small to read on different devices.  
![image](https://user-images.githubusercontent.com/101174061/214998376-dd1dba67-d401-4a1b-b7b2-06f63a5bd8af.png)

**Describe the solution you'd like**
Maybe can add a function: Press and hold **Ctrl** while sliding the mouse wheel to adjust the font size

**Describe alternatives you've considered**
None

**Additional context**
This is a great plugin, thanks to the author for his hard work!

**Comment by windingwind** [comment]
#6

**Comment by YangQiGuiKong** [comment]
你好，我已收到信件，感谢来信。

**Comment by YangQiGuiKong** [comment]
感谢我，我之前在功能介绍中没看到调整方式，刚在常见问题中找到了
