### ISSUE TITLE
[Bug]外部批注的注释与翻译不同步

### ISSUE THREAD

**Issue by zyx335588** [windingwind/zotero-pdf-translate#347]
**Describe the bug**
开启自动翻译批注功能后，用zotero阅读器打开外部编辑器做过批注的PDF文献；如果批注较多，大概率会再zotero中出现注释与翻译不同步的情况，且外部注释在Zotero内无法编辑。

**To Reproduce**
1. 开启translate插件的自动翻译批注功能
2. 用Zotero阅读器打开一篇用外部PD编辑器做过注释的PDF
如果PDF中的注释较多，大概率会发生上述现象。

**Expected behavior**
注释与翻译保持一致，或者对于外部注释直接不翻译

**Screenshots**
![image](https://user-images.githubusercontent.com/22871049/215236706-6a257988-2eaf-47ae-8a1a-cb718913b48c.png)

**Environment**
 - OS: Windows
 - Zotero Version：6.0.19-beta.15
 - Addon Version：0.9.8

**Comment by windingwind** [comment]
Fixed in latest version 1.0.0.

If you encounter this bug in the new version, please open a new issue.
