### ISSUE TITLE
建议当PDF没有父条目或“语言”一栏为空时，可以不启用自动翻译

### ISSUE THREAD

**Issue by pisceswb** [windingwind/zotero-pdf-translate#349]
如题，建议当PDF没有父条目或“语言”一栏为空时，可以不启用自动翻译。
因为有些手动导入的中文PDF，没有原数据，语言栏为空，选择文本或标注文本时，会触发自动翻译。
没有父条目的PDF，不能设置语言栏，在标注文本时，一定会引起启动自动翻译

**Comment by windingwind** [comment]
在语言禁用设置中额外填入`,,`即可
