### ISSUE TITLE
[Bug] Chinese (simplified) may be set equal to default system language

### ISSUE THREAD

**Issue by stg1205** [windingwind/zotero-pdf-translate#35]
**Describe the bug**
The plugin failed to translate English to Chinese (Simplified). The popup only showed the original word. However, when I changed the target language to other Chinese, it would work. I think this may be related to environment variables of default system language because mine is set to English. 

**To Reproduce**
1. Change you default system language to English (United States)
2. Set the source language to English (US) and the target language to Chinese (Simplified)
3. Do the translation as the way described in README

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55123830/160227840-b26551ec-c3af-49b7-8233-dc186f4bb6e8.png)

**Environment**
 - OS: Windows
 - Zotero Version: 6.0.3
 - Addon Version: 0.3.4

**Comment by windingwind** [comment]
thanks. will be fixed in the next update.

**Comment by windingwind** [comment]
fixed in v0.3.5
