### ISSUE TITLE
[Bug]Complete the Title Here

### ISSUE THREAD

**Issue by xlnn** [windingwind/zotero-pdf-translate#354]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  

When translating paper, there are extra blanks in the translation result.As follows:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows/macOS/Linux
 - Zotero Version(Help->About Zotero)
 - Addon Version(Tools->Add-ons)

**Additional context**
![image](https://user-images.githubusercontent.com/57608826/216917376-aaf183c4-a67b-4d83-a3bc-edb4b0c649ad.png)

**Comment by windingwind** [comment]
fixed
