### ISSUE TITLE
[Bug]翻译小窗的相关问题

### ISSUE THREAD

**Issue by csf2022scut** [windingwind/zotero-pdf-translate#355]
**Describe the bug**

1. 选择一大段文字翻译，翻译结果会超出PDF阅读器窗口，需滑动底部滚动条才能看到完整翻译结果

2.同时第二次翻译大段文字时翻译结果窗口会直接消失，重新选中较少文字翻译后翻译小窗才会恢复

**To Reproduce**

1. 选中一大段文字自动翻译发现窗口超出正常PDF视图大小
![image](https://user-images.githubusercontent.com/117445516/217250652-07522c14-0cd8-4016-83bf-a5813ddf4e6c.png)
2. 右滑底部滚动条才能查看全部翻译结果
![image](https://user-images.githubusercontent.com/117445516/217250958-f4fcea45-6e43-4cd4-87b8-23d311695731.png)
3. 左键点击文章任意位置关闭翻译结果窗口，同时底部滚动条消失
4. 重新选择一大段文字发现翻译结果小窗不显示
![image](https://user-images.githubusercontent.com/117445516/217251675-1ca66902-59b4-486e-95b7-8e3a7946137e.png)
5. 再次关闭翻译结果窗口
6. 重新选择一小段文字翻译结果窗口可以恢复正常
![image](https://user-images.githubusercontent.com/117445516/217251868-4ac9e255-c9c4-4d11-95ce-acced15d01b4.png)
7. 再次选择大段文字依然发生上述错误
![image](https://user-images.githubusercontent.com/117445516/217251964-29187262-7811-4d7b-9083-39f5f737fdd9.png)

**Environment**

- OS: Windows 10
- Zotero Version 6.0.20
- Addon Version 1.0.3

希望开发者能解决这个bug，谢谢！

**Comment by windingwind** [comment]
翻译窗口大小默认自适应，可在设置中改为记忆手动设置的大小。
第二次不显示弹窗是因为两次选择的文本完全一样，这种情况下隐藏弹窗是有意如此设计的。
