### ISSUE TITLE
[Feature]Complete the Title Here

### ISSUE THREAD

**Issue by bianhaotian** [windingwind/zotero-pdf-translate#356]
**Is your feature request related to a problem? Please describe.**
从哪一个版本开始标题翻译结果从短标题到其他了呀？原来放在段标题中，我可以把短标题固定出来和英文标题对照看查找我需要的文章，现在放在其他字段中，会影响对照阅读效果。因为存在citation插件在题录捕捉进来的时候自动给引用次数，并放在其他字段。后面再翻译标题或者摘要的时候，似乎会重写其他字段？引用次数也被覆盖了。

**Comment by windingwind** [comment]
1. 放在extra字段是zotero官方推荐的规范做法。
2. 可以固定标题翻译为单独列，不影响阅读
3. 本插件不会覆盖extra字段。如果其他插件覆盖，是其操作不规范，建议向其作者反馈。

**Comment by windingwind** [comment]
标题与摘要翻译可在右侧信息栏直接查看

**Comment by bianhaotian** [comment]
windingwind/zotero-pdf-translate
收到了，谢谢。不过出现这样一个问题，见图。


2023-02-11
---- Replied Message ----
| From | ***@***.***> |
| Date | 02/10/2023 00:46 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [windingwind/zotero-pdf-translate] [Feature]Complete the Title Here (Issue #356) |

标题与摘要翻译可在右侧信息栏直接查看

**Comment by windingwind** [comment]
没有看到图片

**Comment by bianhaotian** [comment]
windingwind/zotero-pdf-translate
 开关一下插件又好了，可能有插件冲突，没问题了 谢谢！


2023-02-11


---- Replied Message ----
| From | ***@***.***> |
| Date | 02/11/2023 15:22 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [windingwind/zotero-pdf-translate] [Feature]Complete the Title Here (Issue #356) |
windingwind/zotero-pdf-translate
收到了，谢谢。不过出现这样一个问题，见图。


2023-02-11
---- Replied Message ----
| From | ***@***.***> |
| Date | 02/10/2023 00:46 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [windingwind/zotero-pdf-translate] [Feature]Complete the Title Here (Issue #356) |

标题与摘要翻译可在右侧信息栏直接查看
