### ISSUE TITLE
点击批注翻译后出现abc字样的符号，不知怎样去除

### ISSUE THREAD

**Issue by shuaiyb** [windingwind/zotero-pdf-translate#358]
![image](https://user-images.githubusercontent.com/124781989/217516286-87b7ecf3-f225-408e-b7ff-404f19be4ba3.png)

**Comment by RTcui** [comment]
> 有意设置如此，用于修改翻译内容时进行翻译内容的替换
@windingwind   没太理解这个意思，是换其他翻译引擎后翻译内容会自动更新吗？

那么abc符号功能是否可实现自由选择呢。翻译后的内容有时会加粗标记一下，但是新版本软件会自动恢复默认。所以又用回了老版本。

**Comment by windingwind** [comment]
批注翻译结果在右侧栏可以编辑并重新翻译，这是从老版本就有的功能（但过去只支持翻译结果存在批注评论的情况）。
emoji不会出现在正文文本，其他符号可能导致重新翻译时替换出错，因此不允许自己设置。
