### ISSUE TITLE
v1.0.6 及之后版本与 Zotero Style 冲突

### ISSUE THREAD

**Issue by FakeTrader** [windingwind/zotero-pdf-translate#360]
**Describe the bug**
文献列表显示空白

**To Reproduce**
1. Zotero Style == v2.1.2
2. Zotero PDF Translate >= 1.0.6
3. 重启 Zotero，文献列表显示空白
4. Translate 回退至 v1.0.5 可正常显示
5. 单独启用 Style 或 Translate 最新版也可正常显示

**Environment**
 - OS: macOS
 - Zotero Version: 6.0.21
 - Addon Version: 如上

**Screenshot**
![WX20230210-160620@2x](https://user-images.githubusercontent.com/9635792/218036699-e19448f7-9920-43aa-ad82-24f972235cc7.png)

**Comment by windingwind** [comment]
@MuiseDestiny

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3
@FakeTrader 更新试试。

**Comment by FakeTrader** [comment]
可以了，感谢大佬
