### ISSUE TITLE
Separator of the translated text

### ISSUE THREAD

**Issue by Morpheuslavius** [windingwind/zotero-pdf-translate#362]
Hello everyone, 
first of all I would like to thank you very much for the work you put into the development of extensions to zotero especially pdf translator. I have a small suggestion about adding the option to insert any character, space or enter etc. automatically after adding a translation, for example in the body or comment. Would such an option be possible to implement? attached screen what I mean
<img width="427" alt="Zrzut ekranu 2023-02-10 o 22 29 42" src="https://user-images.githubusercontent.com/121285521/218205098-9f8c6d16-59dd-45f2-a75d-d7305ec9ce65.png">

**Comment by windingwind** [comment]
This emoji is put here to separate translation and raw text because it won't appear in the raw text of a paper.

Using other symbols that might also appear as part of the raw text will spoil the annotation translation editing feature.

**Comment by Morpheuslavius** [comment]
get it, this application I mentioned was supposed to be for linking notes to obsidian, where the translated text would be automatically formatted by the admonition extension to a collapsible tab >[!Translation]-.
> 
![Zrzut ekranu 2023-03-8 o 13 49 30](https://user-images.githubusercontent.com/121285521/223717665-5cdbff6e-1e77-44d4-bfc9-d518ebb223d6.png)
