### ISSUE TITLE
[Bug]无法自动翻译

### ISSUE THREAD

**Issue by heyyxcusa** [windingwind/zotero-pdf-translate#364]
**Describe the bug**
在首选项中启用年自动翻译及自动弹窗，特定语言关闭自动翻译中只设置了中文，但在翻译英文PDF使只能自动弹窗显示Translate按钮，无法自动翻译，多篇英文PDF均是此情况。
**To Reproduce**
划词

**Expected behavior**
希望能够划词弹窗里就能自动翻译

**Screenshots**
插件设置截图：
![image](https://user-images.githubusercontent.com/91315264/218297721-5938caf9-ddf4-4a09-9b32-3056018662e8.png)
![image](https://user-images.githubusercontent.com/91315264/218297734-79d6a5e2-6421-4a70-9486-5837599d66ff.png)
问题截图：
![image](https://user-images.githubusercontent.com/91315264/218297769-41922f1b-7795-4460-9a8d-a2c7f41e5630.png)
![image](https://user-images.githubusercontent.com/91315264/218297828-6b7a50a3-4ade-453e-a233-d3e3b9eda2a9.png)
但有少部分PDF能正常自动翻译：
![image](https://user-images.githubusercontent.com/91315264/218297972-4ae88dd8-927c-4d9e-85e9-d72ceab44905.png)

**Environment**
 - OS:Linux
 - Zotero Version：6.0.20
 - Addon Version：0.4.8

**Additional context**

附上一篇无法自动翻译文献PDF：
[Petra Schneider et al_2020_Rethinking drug design in the artificial intelligence era.pdf](https://github.com/windingwind/zotero-pdf-translate/files/10715502/Petra.Schneider.et.al_2020_Rethinking.drug.design.in.the.artificial.intelligence.era.pdf)

**Comment by windingwind** [comment]
请升级插件

**Comment by heyyxcusa** [comment]
> 请升级插件

您好，所有插件均是最新版本。
![image](https://user-images.githubusercontent.com/91315264/218299229-175f5729-e8ce-4050-bdb6-a8997df86b85.png)

**Comment by heyyxcusa** [comment]
> 请升级插件

感谢！才发现最新插件版本是1.0.8！还想请问一下已开启插件自动更新，也Check update了可是为什么无法自动更新至最新版本呢？我看此插件更新时间为2023.2.05但版本仍是0.4.8
![image](https://user-images.githubusercontent.com/91315264/218299336-7bf8863e-2946-4844-8c0e-bdab67e6b0af.png)

**Comment by windingwind** [comment]
与网络环境有关。直接下载覆盖安装即可

**Comment by windingwind** [comment]
请发送文献链接或pdf，并附文献条目信息栏截图

**Comment by heyyxcusa** [comment]
> 请发送文献链接或pdf，并附文献条目信息栏截图

信息栏截图：
![image](https://user-images.githubusercontent.com/91315264/218300672-f0d7aec3-d2ac-4176-a1e9-2a1ad74489b9.png)
PDF：
[Petra Schneider et al_2020_Rethinking drug design in the artificial intelligence era.pdf](https://github.com/windingwind/zotero-pdf-translate/files/10715625/Petra.Schneider.et.al_2020_Rethinking.drug.design.in.the.artificial.intelligence.era.pdf)

**Comment by windingwind** [comment]
文献信息栏语言为zh cn，匹配了你的忽略自动翻译语言

**Comment by heyyxcusa** [comment]
> 文献信息栏语言为zh cn，匹配了你的忽略自动翻译语言

非常感谢！已根据删除高级关闭对特定语言自动翻译设置解决。
