### ISSUE TITLE
[Feature] Support Offline Translation via RFC2229 DICT protocol

### ISSUE THREAD

**Issue by hykilpikonna** [windingwind/zotero-pdf-translate#365]
**Is your feature request related to a problem? Please describe.**

Currently, all of the dictionary/translation services are online, which isn't great because if I want to read on the subway without internet.

**Describe the solution you'd like**

I hope you could add support for the [DICT protocol](https://en.wikipedia.org/wiki/DICT) so that people can run e.g. [dictd](https://wiki.archlinux.org/title/dictd) locally with an offline dictionary like [WordNet](https://en.wikipedia.org/wiki/WordNet) and have this plugin connect to it.

**Comment by windingwind** [comment]
I am busy these days. I’ll come back and work on this issue when I have time. Welcome PR.
