### ISSUE TITLE
There is a problem with the translation window. As follows in specific.It affects beatuy!

### ISSUE THREAD

**Issue by xlnn** [windingwind/zotero-pdf-translate#368]
**Is your feature request related to a problem? Please describe.**
There is a problem with the translation window. As follows in specific.It affects beatuy!

**Describe the solution you'd like**
I hope translation at normal!

**Describe alternatives you've considered**
I don't have.

**Additional context**
There is a picture!
![image](https://user-images.githubusercontent.com/57608826/218631832-14c4a1de-8ce0-4a0a-8800-8a20bb72cd0b.png)

**Comment by windingwind** [comment]
Are you using the latest version of the plugin?

**Comment by xlnn** [comment]
> Are you using the latest version of the plugin?

Yes.It is the latest of the plugin.As follows!
![image](https://user-images.githubusercontent.com/57608826/218657756-7e47459f-3e22-4cb1-8b6d-c179268749a3.png)
