### ISSUE TITLE
[Feature]override the URL of the DeepL API by specifying the server_url argument

### ISSUE THREAD

**Issue by lol2025** [windingwind/zotero-pdf-translate#369]
![Snipaste_2023-02-14_13-57-27](https://user-images.githubusercontent.com/20666312/218654262-a472f085-def7-4344-a814-4ce3cf2188a9.png)
deepl api risk control on ip, using vpn can easily lead to api blocked, with reverse proxy can perfectly solve this problem

**Comment by windingwind** [comment]
This is not a standard usage of DeepL API and I’m not going to implement this. Pull requests are always welcome.
