### ISSUE TITLE
翻译的最后一行总是只显示一半。希望改善下翻译界面

### ISSUE THREAD

**Issue by yuzuan** [windingwind/zotero-pdf-translate#37]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  
3. Remember to delete this section before submit.   

**Issues not in the template format will be ignored/不按模板格式的提问将不会被回复**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows/macOS/Linux
 - Zotero Version(Help->About Zotero)
 - Addon Version(Tools->Add-ons)

**Additional context**

**Comment by windingwind** [comment]
Issues not in the template format will be ignored/不按模板格式的提问将不会被回复
