### ISSUE TITLE
希望可以开发出单词发音功能

### ISSUE THREAD

**Issue by Cai-aa** [windingwind/zotero-pdf-translate#373]
在阅读英文文献遇到陌生单词查词时，有时候想知道单词的准确发音，就需要去在别的软件上单独查一次单词发音，希望可以把单词发音功能整合到这个翻译插件里边，可以在翻译页面增加一个喇叭按钮，一点击就能知道单词的准确发音。

**Comment by windingwind** [comment]
必应等部分词典有发音
