### ISSUE TITLE
[Feature]希望可以增加火山翻译

### ISSUE THREAD

**Issue by shy86** [windingwind/zotero-pdf-translate#374]
https://translate.volcengine.com/

试用了一下，虽然火山翻译不是很出名，但是翻译效果还不错。希望作者可以考虑一下

**Comment by windingwind** [comment]
参见先前issue

**Comment by shy86** [comment]
> 参见先前issue

我查看了先前的issue，然后浏览了一下目前的文档。发现了这些链接：
 https://www.volcengine.com/docs/6369/67269

**Comment by windingwind** [comment]
看起来文档比之前好一点，不过签名方法实在是有点太复杂了，欢迎pr，但我可能没时间做
