### ISSUE TITLE
[Feature]希望可以增加条目自动翻译功能

### ISSUE THREAD

**Issue by csf2022scut** [windingwind/zotero-pdf-translate#378]
**Describe the solution you'd like**
尊敬的开发者，您好！对于目前的可以右击条目翻译条目标题和摘要的功能，希望可以增加鼠标在条目上停留一段时间后就自动显示条目翻译的功能，谢谢！

**Comment by windingwind** [comment]
你好，这个功能不会实现。自动翻译是危险的，可能导致ip被封禁或使用大量翻译额度。要批量翻译，请多选条目然后手动选择翻译。

**Comment by csf2022scut** [comment]
> 你好，这个功能不会实现。自动翻译是危险的，可能导致ip被封禁或使用大量翻译额度。要批量翻译，请多选条目然后手动选择翻译。

好的，谢谢！
