### ISSUE TITLE
[Feature]Allow setting a default item language when it is empty, for auto-translation to work when highlighting text in PDF

### ISSUE THREAD

**Issue by wenlzhang** [windingwind/zotero-pdf-translate#380]
**Is your feature request related to a problem? Please describe.**
It often occurs to me that an item saved through the Zotero browser extension would have no `language` filled in the Zotero item. This means that auto-translation would not work when highlighting text in a PDF file. Then one has to manually fill in the language, e.g., English, which is inconvenient.

**Describe the solution you'd like**
It would be great if there can be an option in settings that allows to set a default language to use when `language` is empty in the Zotero item. This way, the auto-translation would still work when highlighting text in the PDF file.

**Additional context**
Maybe the following two issues are related:

- https://github.com/windingwind/zotero-pdf-translate/issues/364
- https://github.com/windingwind/zotero-pdf-translate/issues/349

**Comment by windingwind** [comment]
Items with specified languages will NOT be translated automatically, while empty language field items DO NOT trigger this check.

If you find empy language field items are not automatically translated when auto-translate is enabled, then it might be a bug.

**Comment by wenlzhang** [comment]
> If you find empy language field items are not automatically translated when auto-translate is enabled, then it might be a bug.

This is the case for me. When a language, e.g., English, is specified for the Zotero item, auto-translation works; when it is empty, it does not work.

<img width="128" alt="image" src="https://user-images.githubusercontent.com/44930227/221354495-27e013ac-a832-4e3a-b60d-7ad94174f796.png">

Related PDF Translate settings are as follows:

<img width="577" alt="image" src="https://user-images.githubusercontent.com/44930227/221354518-bbd8a833-5b3c-4316-8fbb-c7067328ddd5.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/44930227/221354531-41952280-82ab-4666-a8c4-973a76e6d602.png">

**Comment by windingwind** [comment]
Not sure what is happening to your case. Could you please provide a debug output described in #6?

**Comment by wenlzhang** [comment]
Here is what I have in the console:
```
(3)(+47111873): [Zotero Better Notes] sync start

(3)(+0000002): [Zotero Better Notes] BN:Sync []

(3)(+0000001): [Zotero Better Notes] {} [] []

(3)(+0003845): [Zotero PDF Translate] runTranslationTask {}

(3)(+0000002): [Zotero PDF Translate] disabledByItemLanguage

(3)(+0003322): [Zotero PDF Translate] {}

(3)(+0000002): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000000): [Zotero PDF Translate] {}

(3)(+0004723): [Zotero PDF Translate] runTranslationTask {}

(3)(+0000002): [Zotero PDF Translate] disabledByItemLanguage

(3)(+0006377): [Zotero PDF Translate] {}

(3)(+0000002): [Zotero PDF Translate] {}

(3)(+0000000): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000002): [Zotero PDF Translate] runTranslationTask {}

(3)(+0000001): [Zotero PDF Translate] disabledByItemLanguage

(3)(+0003011): [Zotero PDF Translate] runTranslationTask {}

(3)(+0000001): [Zotero PDF Translate] disabledByItemLanguage
```
