### ISSUE TITLE
[Feature]DeepLX Api 

### ISSUE THREAD

**Issue by freejool** [windingwind/zotero-pdf-translate#381]
https://github.com/OwO-Network/DeepLX

这个接口需要自己部署，优点是无需token

**Comment by freejool** [comment]
Translate Services 选择 DeepL(Custom) , Secret 填入 http://127.0.0.1:1188/translate 即可。

**Comment by kettly1260** [comment]
> Translate Services 选择 DeepL(Custom) , Secret 填入 http://127.0.0.1:1188/translate 即可。

我按照这个搭建了一个代理，没办法在这个软件上正常使用，提示不可用。而且从服务端看不到对应的访问。但是同样的代理在“沉浸式翻译”上是可以正常使用的

**Comment by freejool** [comment]
> > Translate Services 选择 DeepL(Custom) , Secret 填入 http://127.0.0.1:1188/translate 即可。
> 
> 我按照这个搭建了一个代理，没办法在这个软件上正常使用，提示不可用。而且从服务端看不到对应的访问。但是同样的代理在“沉浸式翻译”上是可以正常使用的，提示Zotero Error: xxx.abc.com uses an invalid security certificate.。

是否在Translate Services 选择 DeepL(Custom) ？

**Comment by kettly1260** [comment]
> > > Translate Services 选择 DeepL(Custom) , Secret 填入 http://127.0.0.1:1188/translate 即可。
> > 
> > 
> > 我按照这个搭建了一个代理，没办法在这个软件上正常使用，提示不可用。而且从服务端看不到对应的访问。但是同样的代理在“沉浸式翻译”上是可以正常使用的，提示Zotero Error: xxx.abc.com uses an invalid security certificate.。
> 
> 是否在Translate Services 选择 DeepL(Custom) ？

是的

**Comment by SYZ622** [comment]
> tero Error: xxx.abc.com uses an invalid security
请问现在的版本还有DeepL(Custom)吗？
