### ISSUE TITLE
[Bug]Maybe memory leak caused by 'Zotero PDF-Translate' add-on extension

### ISSUE THREAD

**Issue by anneal2023** [windingwind/zotero-pdf-translate#384]
Hi windingwind, thanks for your brilliant work of this very useful add-on!

**Describe the bug**

Whenever I edit a note for about 10-20 min as keeping the PDF-Translate add-on working alongside, the Zotero program would become slower responsible, and halted, finally crash... While I disabled this add-on, the problem disappeared too and the Zotero ran smoothly. The system memory monitor shows that physical RAM used by Zotero is increasing when I enable the PDF-Translate add-on, but stays normal if the add-on is disabled. So I doubt that there is a memory leak induced by the PDF-Translate plugin. 

**Environment**
 - OS: Windows 7
 - Zotero Version 6.0.22
 - Addon Version 0.9.8

**Comment by windingwind** [comment]
Please try the latest version. There have been very fundamental changes since v1.0.0+.
