### ISSUE TITLE
[Bug]我想使用portableapps中的zotero，这个离线版的zotero似乎是32位的，翻译功能不能实现，没有翻译功能

### ISSUE THREAD

**Issue by heyeruoqi** [windingwind/zotero-pdf-translate#385]
**Describe the bug**
我想使用portableapps中的zotero，这个离线版的zotero似乎是32位的，翻译功能不能实现，没有翻译功能，请使用u盘安装portableapps的zotero进行调试。
![image](https://user-images.githubusercontent.com/102173897/222241240-157ec898-f5e2-49c3-87be-bf178a9ff41e.png)

**To Reproduce**

**Expected behavior**
希望portableapps的zotero中可以使用这个插件，其他插件都是能使用的，只有这个不行

**Screenshots**
![image](https://user-images.githubusercontent.com/102173897/222241240-157ec898-f5e2-49c3-87be-bf178a9ff41e.png)

**Environment**
 - OS: Windows
 - Zotero Version6.0.22
 - Addon Version0.8.25

**Additional context**

**Comment by windingwind** [comment]
以官方分发为准。
另外你安装了插件吗，我感觉是没安装插件
