### ISSUE TITLE
[Feature] support chatgpt translate

### ISSUE THREAD

**Issue by lfyzjck** [windingwind/zotero-pdf-translate#387]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

As openai release chatgpt openapi, we can use gpt-3.5-turbo translate paper to another language with better quality.

**Is your feature request related to a problem? Please describe.**
No, it's a new feature

**Describe the solution you'd like**
support openai api and allow user to config private apiKey itself, like other translate engines.

**Describe alternatives you've considered**

**Additional context**

**Comment by Oldstone233** [comment]
同样希望能够支持chatgpt API进行翻译，open AI 允许用户使用自己的API

**Comment by GrayXu** [comment]
[Add support for translate with openai #386](https://github.com/windingwind/zotero-pdf-translate/pull/386)

**Comment by lfyzjck** [comment]
👏
