### ISSUE TITLE
[Feature]内置浏览器

### ISSUE THREAD

**Issue by Ohlagrange** [windingwind/zotero-pdf-translate#388]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
就是在zotero里集成一个网页浏览器，真正意义上实现All in one，方便后续使用chatgpt，new bing等工具后的实现更惊艳的交互体验。

**Additional context**
例如：在数篇参考文献的pdf中将摘要，本文研究内容，和结论等部分语句打上标记后，告诉chatgpt基于这些内容写一个Introduction。

**Comment by windingwind** [comment]
该功能与本插件无关，我没有更多精力维护一个新插件了，抱歉

**Comment by Ohlagrange** [comment]
> 该功能与本插件无关，我没有更多精力维护一个新插件了，抱歉

大佬能不能给个思路，最近在学习你的插件开发文档。
就是像你的这个插件一样加一栏web工具，能够访问一些页面简单的网站，如各种搜索引擎之类的。。
![Snipaste_2023-03-14_18-03-15](https://user-images.githubusercontent.com/23275388/224966727-16c6f5b1-8b0f-4082-83fe-ef3855a5e0c0.png)
