### ISSUE TITLE
标题翻译的位置

### ISSUE THREAD

**Issue by MrGongqi** [windingwind/zotero-pdf-translate#389]
你好，能不能将标题翻译和摘要翻译单独在info里设置一栏，不要将标题翻译放在extra这一栏里。

**Comment by zhyang-dev** [comment]
> 1 最新版本info里面有专门一栏 2 放在extra是zotero规范

![image](https://user-images.githubusercontent.com/24970893/224197616-c1ee6510-b2f1-4e89-a5e1-f39dad05c373.png)
摘要翻译的结果确实是单独一栏，但是这内容只能看一行，没法看全，能否像摘要一样全文显示？或者有什么解决方法吗？

**Comment by windingwind** [comment]
和摘要一样，单击展开

**Comment by zhyang-dev** [comment]
> 和摘要一样，单击展开

谢谢回复。我的【摘要翻译】有的文章展不开，有的可以，下面【其他】都能正常显示。测试了另一台机子也是类似，都装的zotero 6.0.22 + 插件1.0.9。不清楚触发条件。

https://user-images.githubusercontent.com/24970893/224203264-5425785f-505d-4189-a193-1deff9150206.mp4

**Comment by windingwind** [comment]
禁用所有其他插件，或者重启zotero还是固定的某些条目无法展开摘要翻译吗

**Comment by tzycsu** [comment]
主要是引用数也在其它一栏冲突。

**Comment by windingwind** [comment]
如上所述，放在其他是zotero的规范。不存在冲突

**Comment by windingwind** [comment]
标题翻译栏是其他栏的显示，实际数据还是在其他栏。

被覆盖是因为对方插件使用其他栏不按照zotero的约定规范。应该联系其作者，让ta按zotero规范存取数据

**Comment by Lingweiz1998** [comment]
同样的情况，我的“其他”一栏用来看引用数量。这在之前存放在短标题的时候没有问题，刚刚突然不知道为什么更新后就不得不翻译在其他了。。还可以再翻译到短标题栏吗？

**Comment by wddwh221** [comment]
> 如上所述，放在其他是zotero的规范。不存在冲突



> 禁用所有其他插件，或者重启zotero还是固定的某些条目无法展开摘要翻译吗

我的也无法展开摘要翻译，不知道是什么原因

**Comment by xjtusjtu** [comment]
> 禁用所有其他插件，或者重启zotero还是固定的某些条目无法展开摘要翻译吗

我也是无法展开摘要翻译，已尝试关闭诸多插件，未得到解决😥

**Comment by windingwind** [comment]
关于展开摘要翻译问题，请提供截图，操作系统，zotero版本，插件版本，其他安装了什么插件。

**Comment by wddwh221** [comment]
![%C A2_KTGY (`A~8FVCEZ37](https://user-images.githubusercontent.com/50294544/227409374-d7ad6a35-7d88-4dd7-9cf6-b222499b0b8b.png)
![5XVGZNZW%VZ`ETMQ8GU)Q H](https://user-images.githubusercontent.com/50294544/227409378-ba9bdda2-f635-4f25-b321-288d12e1307a.png)
截图如上 分别是展开摘要翻译和不展开摘要翻译的情况
操作系统 Windows10专业版
zotero版本 6.0.23
插件版本 1.0.13
其他插件 已全部禁用

**Comment by trarer** [comment]
> 关于展开摘要翻译问题，请提供截图，操作系统，zotero版本，插件版本，其他安装了什么插件。

不是插件原因。我测试了一下，如果单词的长度超过一行，摘要翻译的显示栏不会展开，采用省略号表示。若要展开，需要在首行汉字中加空格。

**Comment by zyx335588** [comment]
这个摘要翻译文本框似乎有的可以展开有的不能展开，刚刚专门建了一个profile来测试，但是也没找到什么规律

https://user-images.githubusercontent.com/22871049/228414221-d1ef0bee-a63b-4eeb-9405-9792f756e5a3.mp4
