### ISSUE TITLE
您的IP“218.61.108.113”存在异常请求，且已被系统自动加入黑名单，请不要恶意进行爬取数据，谢谢。[Bug]

### ISSUE THREAD

**Issue by gaokun786** [windingwind/zotero-pdf-translate#39]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  
3. Remember to delete this section before submit.   

**Issues not in the template format will be ignored/不按模板格式的提问将不会被回复**

Edit the template below/编辑以下模版

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows/macOS/Linux
 - Zotero Version(Help->About Zotero)
 - Addon Version(Tools->Add-ons)

**Additional context**

**Comment by gaokun786** [comment]
想问一下这是因为什么

**Comment by windingwind** [comment]
Issues not in the template format will be ignored/不按模板格式的提问将不会被回复
