### ISSUE TITLE
[Bug]Send more characters than the selected word to DeepL API

### ISSUE THREAD

**Issue by reginalluna** [windingwind/zotero-pdf-translate#390]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题。如果不详细说明通过什么步骤可以复现问题，具体表现是什么，你正在使用哪个版本的插件，我没办法帮到你。不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Describe the bug**
I monitored the usage of the number of characters sent by the translator to the DeepL API. For example, I selected the word "soul" and the translator used the DeepL API quota over the number of characters of the word contains, which is not possible. 

**To Reproduce**
=> Please check the screenshot

**Expected behavior**
Fix this problem.

**Screenshots**

1. This is the number of character usage before I clicked on "translating" the selected word "soul."

![image](https://user-images.githubusercontent.com/54960230/224168652-da0b3824-5fc2-4a86-a121-96f094af1802.png)

2. Selected the word "soul." 
![image](https://user-images.githubusercontent.com/54960230/224168966-091dbda2-de2d-47a9-91e4-d973a3b34f36.png)

3. After the translator translated the word, the character usage changed to 281. 
![image](https://user-images.githubusercontent.com/54960230/224169014-778c96ad-f1e9-4b30-bec0-132d977f9383.png)

**Environment**
 - OS: Windows 11 
 - Zotero Version: 6.0.22
 - Addon Version: 1.0.9

**Additional context**

**Comment by windingwind** [comment]
Please go to Menu-Help-Debug Output Logging-View Output and do a translation once. Please paste the details in the debug output window, including the HTTP request contents like:
![image](https://user-images.githubusercontent.com/33902321/224611099-e1703843-20b4-4e1c-adfc-dabafad4e01b.png)
