### ISSUE TITLE
[Feature]（不紧急）Automatic Annotation Translation 能不能区分设置源文件语言为中文时不加入批注（为其它语言时执行默认行为）

### ISSUE THREAD

**Issue by gigberg** [windingwind/zotero-pdf-translate#391]
（英文版的zotero6.0.22, 界面语言为en，插件版本1.0.9）
当前设置：
自动翻译select(关闭)+不自动翻译哪些语言(已设置zh)
自动翻译备注(开启)+备注添加到comment(开启)

当前效果：
对中文添加备注时，会自动翻译备注(翻译为英文)，并且添加到翻译到comment中

改进需求：已经设置“不自动翻译哪些语言(zh)”的情况下，禁止掉自动翻译“中文”备注功能，或者添加“不自动翻译哪些语言的备注”设置项

缓兵之计：直接关闭掉自动翻译备注

#152

**Comment by windingwind** [comment]
语言禁用设置对条目的语言栏生效，请检查是否是与设置对应
