### ISSUE TITLE
首选项里面看不到插件的设置项

### ISSUE THREAD

**Issue by tcmtom** [windingwind/zotero-pdf-translate#393]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题。如果不详细说明通过什么步骤可以复现问题，具体表现是什么，你正在使用哪个版本的插件，我没办法帮到你。不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Describe the bug**
明明已经打开并且可以正常使用，但是首选项里面看不到插件的设置项，能看见茉莉花插件和theme的
**To Reproduce**

**Expected behavior**
设置项里能正常显示插件的设置项
**Screenshots**
![image](https://user-images.githubusercontent.com/94541098/224926696-2a12321d-baad-4a2c-9050-c169415d909e.png)
![image](https://user-images.githubusercontent.com/94541098/224927326-115aaf6a-9e35-4eb2-9f9a-dd6092c3a050.png)
![image](https://user-images.githubusercontent.com/94541098/224927534-9c60c907-f6b5-475a-aed8-df2d1ffc30ed.png)

**Environment**
 - OS: Windows 10
 - Zotero Version(Help->About Zotero)6.0.23
 - Addon Version(Tools->Add-ons)见截图

**Additional context**
zotero-reference也存在这个问题https://github.com/MuiseDestiny/zotero-reference/issues/90

**Comment by windingwind** [comment]
禁用其他所有插件，重启zotero是否还有这个问题？
