### ISSUE TITLE
[Feature] How about add chatGPT translate ? 

### ISSUE THREAD

**Issue by aitianci** [windingwind/zotero-pdf-translate#395]
**Is your feature request related to a problem? Please describe.**
NO problem, here is a simple suggestion, when chatGPT gives a such good result in translation and answering questions I do thinks it's a promotion for translation function. 

**Describe the solution you'd like**
Add support for openai api, and users may input their own token id for more words input. 

**Describe alternatives you've considered**
Or you can make it an individual addon to simply use chatGPT in zotero. No matter users can use it to translate or ask questions. 

**Additional context**
Thanks to your work, the addon is easy to use and helpful.

**Comment by windingwind** [comment]
We already have it in the latest release.
