### ISSUE TITLE
[Need Help] Purchase Translation API?

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-pdf-translate#4]
I've received some suggestions about supporting more translate engines, like DeepL, Caiyun, etc. However, these translate services usually require payment to get the full API.

This means either requiring the user to go through tedious steps to set up a key (and possibly paying for it), or requiring me to provide a full API with no restrictions. The latter requires a relatively large fee, but I cannot currently afford it.

The prices are listed below:
- [DeepL](https://www.deepl.com/en/pro?cta=header-prices) US$6.99 per month unlimited
- [Microsoft](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/) $10 per million chars of standard translation

Looking for suggestions!

**Comment by drwanghaipeng** [comment]
小牛翻译很棒，可以加上么

**Comment by The-New-Coder** [comment]
可做收费服务

**Comment by windingwind** [comment]
> 可做收费服务

Anyone who wants other translate engines to be supported can comment here. I'll try if I can find a free API; if not, I may consider starting a crowdfunding.

Supported translate engines are listed [here](https://github.com/windingwind/zotero-pdf-translate#translate-engine)

**Comment by drwanghaipeng** [comment]
翻译出来的字体可以调大点吗？这个插件越来越棒了

**Comment by windingwind** [comment]
> 翻译出来的字体可以调大点吗？这个插件越来越棒了

谢谢建议，将在下一版本更新添加字体设置

**Comment by windingwind** [comment]
> 翻译出来的字体可以调大点吗？这个插件越来越棒了

@drwanghaipeng font-size settings are now supported in v0.0.8.

**Comment by byheaven** [comment]
Hi，希望能先支持Deepl的个人API调用方式，也就是用户提供api key的方式。从翻译质量来说，deepl还是最佳的。

**Comment by windingwind** [comment]
> Hi，希望能先支持DeepL的个人API调用方式，也就是用户提供api key的方式。从翻译质量来说，deepL还是最佳的。
> 并且DeepL提供[免费的API订阅](https://www.deepl.com/zh/pro-api?cta=menu-pro-api/)

由于我没有deepl允许地区内的支付方式，因此无法注册使用免费额度的api。是否有合适的注册方式，或者是否可以提供一个测试的api key？

**Comment by windingwind** [comment]
> > > Hi，希望能先支持DeepL的个人API调用方式，也就是用户提供api key的方式。从翻译质量来说，deepL还是最佳的。
> > > 并且DeepL提供[免费的API订阅](https://www.deepl.com/zh/pro-api?cta=menu-pro-api/)
> > 
> > 
> > 由于我没有deepl允许地区内的支付方式，因此无法注册使用免费额度的api。是否有合适的注册方式，或者是否可以提供一个测试的api key？
> 
> 我是从淘宝购买的一个代注册服务，我把我的API key发给你，请告知一下邮箱地址？

wyzlshx@foxmail.com

**Comment by windingwind** [comment]
@byheaven DeepL is supported now in v0.0.9

**Comment by byheaven** [comment]
> @byheaven DeepL is supported now in v0.0.9

WoW, thank you so much!

**Comment by Cherrycaptor** [comment]
Hello developers, if you want to crowdfund to solve the cost problem caused by the DEEPL API translation engine, I think I can participate together

**Comment by Oldstone233** [comment]
建议增加一个百度翻译的API，可以让用户自己去申请（步骤很方便，而且网上教程也比较多），然后在插件上添加自己的ID和KEY，平时看文献用免费版的就够用。
![Snipaste_2022-03-20_15-58-19](https://user-images.githubusercontent.com/79570947/159153561-2b9882f3-f5ac-4b62-900f-30c757913033.jpg)

**Comment by windingwind** [comment]
> 建议增加一个BaiDu的API，可以让用户自己去申请（步骤很方便，而且网上教程也比较多），然后在插件上添加自己的ID和KEY，平时看文献用免费版的就够用。 ![Snipaste_2022-03-20_15-58-19](https://user-images.githubusercontent.com/79570947/159153561-2b9882f3-f5ac-4b62-900f-30c757913033.jpg)

Baidu is supported now in v0.1.3. Be aware that the secret for baidu should be in the formt: `appid#key` and have fun with it!

**Comment by windingwind** [comment]
> Hello developers, if you want to crowdfund to solve the cost problem caused by the DEEPL API translation engine, I think I can participate together

Thank your support!
I haven't received any request for the Pro API, as the free one should be enough for personal use.
Right now, there is no cost for maintaining this add-on and crowdfund is not planned.
Thanks again!

**Comment by windingwind** [comment]
This issue will be closed as the pro APIs seems not to be necessary.
Feel free to open a new issue about it any time.

For new translate engine request, please start a new issue.
