### ISSUE TITLE
[Feature]快速切换翻译引擎

### ISSUE THREAD

**Issue by PikakueNNZ** [windingwind/zotero-pdf-translate#40]
1.有时候对一种翻译引擎的结果不满意，希望能够在翻译界面快速在不同引擎之间切换，以对照不同引擎的翻译结果
2.有时阅读的文献不局限于英文，如果遇到其他语言的文献需要手动切换源语言，能否实现源语言的自动识别？
3.我们重点关注的是应该是翻译结果，而非原文，现在原文和译文在屏幕中所占的显示比例差不多，能否手动调整原文和译文的显示比例？

**Comment by windingwind** [comment]
Thanks! I will add these features in the future.

**Comment by windingwind** [comment]
对于2：部分翻译引擎支持自动识别，如果在右侧提供一个选择源语言的选项，是否可以接受

**Comment by windingwind** [comment]
对于3：v0.3.9 support resizing sidebar textarea

**Comment by PikakueNNZ** [comment]
> 对于2：部分翻译引擎支持自动识别，如果在右侧提供一个选择源语言的选项，是否可以接受

经过测试，v0.3.9中谷歌、小牛、有道、彩云、deepL(free)、百度无法自动识别日文，其他引擎我没有密钥因此没有尝试
![image](https://user-images.githubusercontent.com/40914469/160320332-cc8ae773-a7b4-4fc6-84a2-6625c8c33748.png)

![image](https://user-images.githubusercontent.com/40914469/160320308-cf2a76f1-697d-47ff-8e0c-8ae0874672db.png)
能够在右侧切换源语言也是方便很多的

**Comment by PikakueNNZ** [comment]
> 对于3：v0.3.9 support resizing sidebar textarea

v0.3.9 手动调整侧边文本框比例后，切换不同pdf后，文本框又恢复了默认比例，无法记忆设置的文本框比例

**Comment by windingwind** [comment]
v0.3.10添加了侧边栏选择语言&比例保留（直到zotero重启）

**Comment by zyy341** [comment]
为什么用谷歌翻译的接口，和我自己复制去网页版谷歌翻译，结果不同？

**Comment by windingwind** [comment]
v0.3.11添加了侧边栏选择语言。此issue将会关闭

**Comment by windingwind** [comment]
> 为什么用谷歌翻译的接口，和我自己复制去网页版谷歌翻译，结果不同？

也许谷歌翻译的不同接口使用了不同的模型。我不知道。
