### ISSUE TITLE
[Bug]所有标签页的翻译都跑到第一个标签页的翻译中

### ISSUE THREAD

**Issue by Lyn6969** [windingwind/zotero-pdf-translate#401]
**Describe the bug**
我的zotero中开启了多个标签页，每次当我重新打开zotero后，第一个（最左侧）标签之后的侧边栏翻译都不见了，都集中到了第一个标签页的翻译旁边，如图1所示，需要把所有标签页关闭，然后在一个个打开才能恢复正常。

**To Reproduce**
如果多个标签页共存，在多个标签页之前切换的时候就有概率出现这个bug

**Expected behavior**
即使多个标签页，翻译的位置也能保持正常

**Screenshots**
图1
![image](https://user-images.githubusercontent.com/42564665/226242783-231be73f-95a5-4719-9f8b-929b7796dccf.png)

**Environment**
 - OS: Windows
 - Zotero Version(6.0.22)
 - Addon Version(1.0.12)

**Additional context**

**Comment by windingwind** [comment]
请问同时开启了其他哪些插件，在1.0.12之前的版本有碰到过这个问题吗，是否有可以稳定复现的操作办法

**Comment by Lyn6969** [comment]
开了这些插件：

![image](https://user-images.githubusercontent.com/42564665/226266272-1a690d2f-4d0b-40d3-ab8d-2d99ac0d4e1d.png)

现在就是开一篇文章以上就会出现这种情况

当我同时打开两篇文章，第一篇的信息栏会出现两个翻译，另外一篇没有翻译：
![image](https://user-images.githubusercontent.com/42564665/226266498-6fbd4a20-3ca1-429a-b6ec-8afa88c1979c.png)
当我同时打开三篇文章，第一篇的信息栏会出现三个翻译，另外两篇没有翻译：
![image](https://user-images.githubusercontent.com/42564665/226266616-fdec214c-38a0-45ab-9cb0-ef29b3d7faf0.png)

**Comment by Lyn6969** [comment]
> 请问同时开启了其他哪些插件，在1.0.12之前的版本有碰到过这个问题吗，是否有可以稳定复现的操作办法

好像没有，虽然之前也出现过翻译不出现的情况，但是在几个标签页之间切换一下，翻译就出现了，现在怎么切换都不行了

**Comment by windingwind** [comment]
请尝试一下禁用所有插件后还出现这个问题吗

**Comment by Lyn6969** [comment]
> 请尝试一下禁用所有插件后还出现这个问题吗

经过我的测试，好像是和zotero-style插件有关系，把style插件禁用之后就好了，style插件我用的也是最新版

**Comment by windingwind** [comment]
@MuiseDestiny 请看一下这个，有没有什么头绪

**Comment by Lyn6969** [comment]
好像跟Night to zotero这个插件也有关系，在开启style的情况下，把Night关了，也就正常了

**Comment by dcgggg** [comment]
你好，我也遇到过类似的情况，但在使用较早版本时没有这种情况，如0.9.8

**Comment by MuiseDestiny** [comment]
试了下是Night问题，应该是这里导致的
https://github.com/tefkah/zotero-night/blob/f7c1327c3b2240f41863023b98c3c9d90edd22c2/content/zotero-night.ts#L486

**Comment by windingwind** [comment]
这是啥原因，理论上night只会加样式？

**Comment by Lyn6969** [comment]
感谢两位大佬的辛苦付出！

**Comment by MuiseDestiny** [comment]
> 所有标签页的翻译都跑到第一个标签页的翻译中

应该不是跑到，而是重复出现了`翻译`tab

至于为什么其中一个会消失，还不清楚

**Comment by Lyn6969** [comment]
> > 所有标签页的翻译都跑到第一个标签页的翻译中
> 
> 应该不是跑到，而是重复出现了`翻译`tab
> 
> 至于为什么其中一个会消失，还不清楚

感觉像是其他标签页的翻译都加载到第一个标签页的侧边栏里面了

**Comment by MuiseDestiny** [comment]
注释掉Night`await reader._initPromise`后
![image](https://user-images.githubusercontent.com/51939531/226341498-d15a1b5f-be52-4d7e-9708-c00c7f9ad03b.png)
不影响Night的功能使用
![image](https://user-images.githubusercontent.com/51939531/226341546-121cca66-8b45-4a87-9111-0402b7bd69e1.png)


可以下载试试
https://github.com/MuiseDestiny/zotero-night/releases/tag/0.0.1

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-night/releases/tag/0.0.1

@Lyn6969 
试试

**Comment by Lyn6969** [comment]
> [MuiseDestiny/zotero-night@`0.0.1` (release)](https://github.com/MuiseDestiny/zotero-night/releases/tag/0.0.1)
> 
> @Lyn6969 试试
好的谢谢大佬！

**Comment by Lyn6969** [comment]
@MuiseDestiny  大佬，这个问题又出现了，但是我已经不再使用night了，关闭了style之后一切正常；除此之外style还会导致reference插件显示的参考文献最右边的加号显示不出来，翻译插件最右侧也是有一段被挡住了，我很喜欢style插件，但是太影响使用了，您有时间可以看看是什么问题😭

**Comment by MuiseDestiny** [comment]
> @MuiseDestiny 大佬，这个问题又出现了，但是我已经不再使用night了，关闭了style之后一切正常；除此之外style还会导致reference插件显示的参考文献最右边的加号显示不出来，翻译插件最右侧也是有一段被挡住了，我很喜欢style插件，但是太影响使用了，您有时间可以看看是什么问题😭

好的，会解决

**Comment by Lyn6969** [comment]
> > @MuiseDestiny 大佬，这个问题又出现了，但是我已经不再使用night了，关闭了style之后一切正常；除此之外style还会导致reference插件显示的参考文献最右边的加号显示不出来，翻译插件最右侧也是有一段被挡住了，我很喜欢style插件，但是太影响使用了，您有时间可以看看是什么问题😭
> 
> 好的，会解决

麻烦您了，感谢！

**Comment by MuiseDestiny** [comment]
可以留个邮箱联系你远程吗，因为我暂时无法复现这个bug

**Comment by Lyn6969** [comment]
> 
lynnyl6969@foxmail.com

**Comment by youyouhdhd** [comment]
> 

或许你可以尝试把zotero if 里的划词翻译关掉试试，我关掉后就正常了

**Comment by youyouhdhd** [comment]
实测证明这个bug还存在，当开启night for zotero 时会导致翻译与参考文献条目在一篇论文中重复出现，在其他文献中消失
![image](https://user-images.githubusercontent.com/54936458/230765493-a8453950-98f0-46f4-baa7-78e44dbb9e98.png)
![image](https://user-images.githubusercontent.com/54936458/230765511-b50c9470-f2ab-4fcb-968f-fb0378ca2da8.png)
