### ISSUE TITLE
[Feature]CNKI验证码

### ISSUE THREAD

**Issue by Frozen-hc** [windingwind/zotero-pdf-translate#402]
**Is your feature request related to a problem? Please describe.**
CNKI翻译引擎多次请求后翻译显示翻译不可用（原因：需要验证）

**Describe the solution you'd like**
在插件中添加自动识别验证码的功能

**Describe alternatives you've considered**
使用浏览器打开cnki网址，手动输入验证码进行验证

**Comment by windingwind** [comment]
不会支持。绕过验证码是对服务方的不尊重行为，请谅解。
