### ISSUE TITLE
Conflict with other add-ons

### ISSUE THREAD

**Issue by Kaiser-Zheng** [windingwind/zotero-pdf-translate#404]
I discovered that the multiple translation tab was present when using the Zotero PDF Translate add-on along with the Night Mode add-on (https://github.com/tefkah/zotero-night). However, when I removed the Night Mode add-on, the problem was resolved.

Currently, I am using the latest version of Zotero PDF Translate.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/65280722/226542965-d584a58a-e4b3-4bd0-8ec2-4fc649e0d1e5.png">

I have tested the Zotero-PDF-Translate tool with various versions, including 1.0.0 and earlier versions, which worked without any issues. However, when testing versions 1.0.10 and later, I encountered problems. I have not yet sure which specific version caused the tool to stop functioning properly.

**Comment by Kaiser-Zheng** [comment]
"I discovered that the multiple translation tab was present when using the Zotero PDF Translate add-on along with the Night Mode add-on (https://github.com/tefkah/zotero-night). However, when I removed the Night Mode add-on, the problem was resolved. 

Currently, I am using the latest version of Zotero PDF Translate."

**Comment by windingwind** [comment]
A known issue. See #401

**Comment by Kaiser-Zheng** [comment]
Understood, thanks.
