### ISSUE TITLE
[Bug]翻译中出现[abc]特殊字符🔤

### ISSUE THREAD

**Issue by Lusenc** [windingwind/zotero-pdf-translate#405]
**Describe the bug**
选择一段英文后，翻译的文本中出现🔤特殊字符，之前的版本没有，如图所示
![image](https://user-images.githubusercontent.com/50198715/226601401-1f2fdb58-3c41-49ce-87ea-055075346032.png)

**To Reproduce**
1. 选中英文文本并高亮
2. 查看弹窗的中文翻译
3. 翻译前后出现🔤符号
4. 表现为：🔤这里是翻译🔤

**Expected behavior**
将🔤去除

**Screenshots**
![image](https://user-images.githubusercontent.com/50198715/226602050-3f97bc7f-273f-4edc-a5c7-9611ed2dd95a.png)

**Environment**
 - OS: Windows
 - Zotero Version 6.0.23
 - Addon Version 1.0.13

**Comment by VsWilson** [comment]
同遇到，而且需要修改生成的笔记时，要先把两个符号去掉。不然就会锁定自动生成的内容，操作会繁琐很多，希望作者大大百忙之中抽空瞅一眼，双手合十。

**Comment by VsWilson** [comment]
已用上，感谢。
很好，很强大

**Comment by colin4k** [comment]
> 已经提交PR #420 编译后的插件下载地址也在里面 本地虚拟机测试一切正常

这个版本的问题是无法修改标注的内容，修改之后会自动恢复修改前的内容。有个简单办法是，在Zotero的’首选项-高级-高级设置-编辑‘种，找到’extensions.zotero.ZoteroPDFTranslate.splitChar‘，将值设置为空即可
