### ISSUE TITLE
翻译标题的位置可以自定义设置吗

### ISSUE THREAD

**Issue by popatofire** [windingwind/zotero-pdf-translate#408]
之前的标题翻译都是填充在短标题栏，但最新版本，翻译只显示在插件的标题翻译里，如果不在信息栏开启标题翻译就不显示标题翻译结果，原来习惯的短标题栏是空白的。
希望可以自已选择标题翻译结果的存放位置，这样还可以选择是否依旧填充在短标题栏。

**Comment by windingwind** [comment]
不能。原因见过往回复

**Comment by PPPHHH810** [comment]
> 不能。原因见过往回复

zotcard模板编辑的地方找不到引用标题翻译和摘要翻译怎么办，笔记模板没办法引用了，之前引用的是短标题的摘要（因为之前翻译结果放在这两处），求解答
