### ISSUE TITLE
terminology library 

### ISSUE THREAD

**Issue by yyelder** [windingwind/zotero-pdf-translate#409]
Hopes to add terminology library functionality to handle some technical terminology issues

**Comment by windingwind** [comment]
Depends on which service you use. Basically we already implemented all features that a service has.

**Comment by Mr-wang0129** [comment]
It's kind of like the little green whale, you can customize the translation of a word, and after you customize it, you can follow the translation of the word.

**Comment by xjtusjtu** [comment]
First, you can do this in the way you add tags(for terminology) on such attchments. Therefore, you can know what are terminologies in the paper. Through the filter of tags, you can quickly select the target words.

Second, Xiaoniu Translator supports intervening the translation results by customizing terminologies.

The little green whale is an integrating softwares, where as this tool just a Zotero pluigin for translation.
