### ISSUE TITLE
[Bug]在空白处拖动鼠标后翻译结果消失

### ISSUE THREAD

**Issue by PikakueNNZ** [windingwind/zotero-pdf-translate#41]
**To Reproduce**
1. 用鼠标选中一段文字
2. 在旁边空白处按下鼠标左键拖动一小段距离（不选中任何文字）

**Expected behavior**
完成步骤1后正常显示翻译结果，完成步骤2后翻译结果消失，出现报错
[Request Error]
Engine not available, invalid secret, or request too fast.
Please consider using another translate engine or posting issue here: https://github.com/windingwind/zotero-pdf-translate/issues
        TypeError: xhr.response[0] is null

**Screenshots**
![image](https://user-images.githubusercontent.com/40914469/160290221-ed00147f-8c31-4c9e-9ff2-7299f58137db.png)
![image](https://user-images.githubusercontent.com/40914469/160290235-0d6b8a38-5b94-4a86-bac1-47a90a75fde6.png)

**Additional context**
我在阅读过程中喜欢取消选中，所以会在旁边空白处进行点击，而有时候点击鼠标过程中鼠标会有少许移动，所以就遇到了这个问题。
是否可以在拖动鼠标后判断选中文字的数量，若未选中文字或选中文字数量少于某个数值则不进行翻译

**Comment by windingwind** [comment]
Thanks for letting me know!
I’ll try to fix it.

**Comment by windingwind** [comment]
旁边空白处指的是什么位置，文档空白处还是其他地方？我似乎无法复现

**Comment by windingwind** [comment]
Try v0.3.7

**Comment by PikakueNNZ** [comment]
> 旁边空白处指的是什么位置，文档空白处还是其他地方？我似乎无法复现

指文档空白处，v0.3.9完美解决了该问题，非常感谢
