### ISSUE TITLE
[Feature]1.0.13版本插件移除了 “是否更新显示与编辑上一条批注”的开关

### ISSUE THREAD

**Issue by xjtusjtu** [windingwind/zotero-pdf-translate#410]
如题，并参见[Issue#106](https://github.com/windingwind/zotero-pdf-translate/issues/106#issue-1213237912)，该开关似乎在最新版本中移除，恳请作者大大考虑将其加回来

使用场景：
- 在翻译一个段落后，会对其中部分语句或者新单词做批注后，手动点击翻译（或者自动翻译），会替换侧边栏翻译tab下的原文，导致整段的翻译被当前批注内容所替代
- 如果整个段落没看完，这就导致整个段落又需要重新翻译一遍，浪费翻译API的字数

谢谢作者大大！

**Comment by windingwind** [comment]
是的，批注评论中，两个emoji包围中间的内容是自动替换为最新翻译的结果的。不建议修改这部分内容。写在emoji外侧不受影响

**Comment by xjtusjtu** [comment]
额，我描述的场景可能并不是这个，具体来说

我现在正在看这一段
![image](https://user-images.githubusercontent.com/57665402/230557027-73a7433a-06ce-4a1a-999f-6a91b6e1e61c.png)

但我对第一句做高亮后翻译（或者对其中某个单词高亮后翻译），我原来整段的翻译被替换掉了，但是我此时可能还没有看完😅
![image](https://user-images.githubusercontent.com/57665402/230557484-a57b259b-8c37-46b7-b99e-a0883dbea8e2.png)

重新翻译整段的话，有点浪费字数
