### ISSUE TITLE
请问这种表情包🔤怎么去掉，之前都没有这个

### ISSUE THREAD

**Issue by lhr0307** [windingwind/zotero-pdf-translate#411]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonglong2020** [comment]
同样的问题

**Comment by xjtusjtu** [comment]
语句翻译看上去还好；
但是对于多行的单词翻译，显示效果很不美观；恳请作者大大考虑设置一个开关，或者自定义表情符号

![image](https://user-images.githubusercontent.com/57665402/227860090-3a663cef-b543-4099-8132-e8e0f791b32f.png)

**Comment by Lusenc** [comment]
遇到了同样的问题

**Comment by Cheedom** [comment]
之前没用这个问题，更新后就有了
