### ISSUE TITLE
[Feature]翻译的快捷键能修改吗？之前单独 T 可以使用，现在不行了，能修改成自定义吗

### ISSUE THREAD

**Issue by zdf0145** [windingwind/zotero-pdf-translate#413]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
Ctrl t

**Comment by zdf0145** [comment]
> Ctrl t

想自定义，或者单独T触发翻译（以前可以），Ctrl T 跨距大有点麻烦

**Comment by windingwind** [comment]
T作为快捷键的问题是会和库中的find-as-you-type冲突，所以取消了。自定义做起来不太方便，因为zotero隐性占用了许多快捷键，会经常有人来提问为什么xx快捷键设置了无效
