### ISSUE TITLE
[Bug]1.0.13版本添加翻译到笔记无法反向链接（在页面显示失效）

### ISSUE THREAD

**Issue by realHongYuZhou** [windingwind/zotero-pdf-translate#414]
1.0.13版本更新后，添加翻译到条目笔记后，点击笔记上出现的在页面显示没有反应。
之前添加的笔记格式如下：
```
英文原文
----
中文翻译（引用信息）
```
更新后的翻译格式如下：
`英文原文（引用信息）中文翻译`

查看两者之间链接区别，发现是连接无法定位到页面，链接地址最后page=NaN
`“Materials and methods” (地址)) ([pdf](zotero://open-pdf/library/items/XAP7WH5Y?page=2))`

`“Patients collection” (地址) ([pdf](zotero://open-pdf/library/items/XAP7WH5Y?page=NaN)) `

**Comment by realHongYuZhou** [comment]
我又尝试了V1.0.10~V1.0.12，很遗憾，都没有之前的效果，我无法确定我之前的版本是什么，但现在确实无法使用反向链接定位到原文中的位置了。

**Comment by realHongYuZhou** [comment]
0.9.4版本是可以用的，希望作者下次更新可以恢复该功能

**Comment by Sherry-smile** [comment]
是的，我也有这个问题，希望可以恢复翻译的双向连接

**Comment by windingwind** [comment]
感谢反馈，这是已知问题。
我目前暂时没有太多时间去深入寻找解决办法，暂时标为need help

**Comment by Linghan-z** [comment]
这个问题解决了吗？

**Comment by yiyixi** [comment]
> 

找到了曲线救国方案，先使用zotero自带高亮文本标记内容，然后后台会自动添加翻译的笔记，再点击标记好的内容，右键添加笔记即可。

**Comment by jachin-byte** [comment]
另一种曲线救国的方案，先“添加笔记”，然后双击复制翻译框的内容替换掉笔记双引号“”里的内容。希望大佬能抽出空来解决了这个痛点，其实这个功能大家用的挺多的。

**Comment by moxi000** [comment]
希望解决这个问题

**Comment by Onion1603Yang** [comment]
希望解决这个问题！双向链接真的很重要！

**Comment by dongdongwcpp** [comment]
为啥我总是找不到这段代码在哪里，仓库搜"添加笔记"也找不到类似的字符串？ @windingwind

**Comment by windingwind** [comment]
已修复，见最新prerelease

**Comment by Hellon189** [comment]
@windingwind 你好，我也是目前还在用6.0，最新的prerelease无法安装呢，希望可以出个6.0的，感恩！！
