### ISSUE TITLE
[Bug]自动翻译批注功能有bug，在翻译后的中文字段前后都出现”🔤“

### ISSUE THREAD

**Issue by Cheedom** [windingwind/zotero-pdf-translate#415]
**Describe the bug**
自动翻译批注功能有bug，在翻译后的中文字段前后都出现”🔤“

**To Reproduce**
1. 选中论文中的字段
2. 点击高亮（任意颜色）
3. 点击批注栏查看批注
4. 发现翻译后的中文字段前后都有🔤

**Expected behavior**
之前从来没用出现过这个问题，去掉这个🔤，感谢大佬

**Screenshots**
<img width="692" alt="image" src="https://user-images.githubusercontent.com/101678015/228088679-5612a45a-3223-4c16-87ec-b8cc06c4d7ca.png">

**Environment**
 - OS: Windows
 - Zotero Version: 6.0.23
 - Zotero  PDF Translate 1.0.14

**Comment by healerlalala** [comment]
我也是这个问题，感谢提问！希望大佬尽快优化！

**Comment by linshenwuqi** [comment]
我也有这个问题，并且更改批注经常会出现没有保存的状况，感谢提问！

**Comment by Wang-Juihsin** [comment]
以前是没有这个问题的，这是现在选择“自动翻译”后的效果。更重要的是，现在自动翻译、自动添加为笔记的译文是不可更改的，就算做了更改删减之类，等你退出笔记修改后，马上又会自动变回来。

**Comment by healerlalala** [comment]
同志们！在插件设置那里取消自动翻译批注就不会有🔤了！

**Comment by Achellesphi** [comment]
> 这个看起来不是bug，而是feature，🔤是用来做定界符的。以此实现笔记里面对翻译的自动删除
> 
> https://github.com/windingwind/zotero-pdf-translate/blob/4e964fb6367980769627bddf1247360f5e1a94d4/src/modules/services.ts#L116-L123

所以想请问这个🔤在哪里更改去掉，或者更改成其他自定义的定界符呢？

**Comment by diegoto32** [comment]
编辑-首选项-翻译-高级-分隔符，删除后面的图标
