### ISSUE TITLE
[Feature] 添加对腾讯 TranSmart 的支持

### ISSUE THREAD

**Issue by pboymt** [windingwind/zotero-pdf-translate#417]
腾讯除了腾讯云的翻译服务以外还有一个 TranSmart 交互式翻译，可以在客户端直接生成 key 来用。

他们的主页是这个 [Tencent TranSmart](https://transmart.qq.com/zh-CN/index)。

**Comment by pboymt** [comment]
刚才 TranSmart 工作人员回复我说腾讯云将会切换到 TranSmart 翻译引擎，那么就不用单独加了，需要监控一下腾讯的接口会不会有改动。

**Comment by myriad2** [comment]
> 刚才 TranSmart 工作人员回复我说腾讯云将会切换到 TranSmart 翻译引擎，那么就不用单独加了，需要监控一下腾讯的接口会不会有改动。

可以问一下  什么时候切换么？谢谢

**Comment by pboymt** [comment]
> > 刚才 TranSmart 工作人员回复我说腾讯云将会切换到 TranSmart 翻译引擎，那么就不用单独加了，需要监控一下腾讯的接口会不会有改动。
> 
> 可以问一下  什么时候切换么？谢谢

不知道啊，他们只说了一定会换，具体时间表没有。
