### ISSUE TITLE
Target language setting not saved

### ISSUE THREAD

**Issue by he-hai** [windingwind/zotero-pdf-translate#42]
**Describe the bug**
Hi, nice tool. I found that it doesn't save the setting for target language. My zotero is set to be in English, the plugin default target language is "English - US". I changed it to Chinese, but when I restart Zotero, it goes back to "English - US". This happens also when I just open the preference for setting. You could see below the environment details I use. Many thanks. 

**Expected behavior**
Save the setting for target language. 

**Environment**
 - OS: Windows 11
 - Zotero Version 6.0.3
 - Addon Version 0.3.5

**Comment by windingwind** [comment]
Thanks for letting me know!
A recent update causes this behavior. I’ll fix it soon.

**Comment by windingwind** [comment]
Fixed in v0.3.6

**Comment by he-hai** [comment]
Thanks for the quick response. I found that it now saves the last translation result too.

**Comment by windingwind** [comment]
> Thanks for the quick response. I found that it now saves the last translation result too.

Yes, that’s because they share the same elements. Is Do you mean this behavior annoying?

**Comment by windingwind** [comment]
> Thanks for the quick response. I found that it now saves the last translation result too.

Yes, that’s because they share the same elements. Do you mean this behavior is confusing?

**Comment by he-hai** [comment]
Nope, I'm OK with that. Just let you know.
