### ISSUE TITLE
[Bug] 文本取消选择后，对之前所选的文档二次翻译

### ISSUE THREAD

**Issue by jn-yxy** [windingwind/zotero-pdf-translate#422]
**Describe the bug**
使用GPT引擎，PDF中的划词翻译功能，选中后自动弹窗翻译或侧边栏翻译，在取消划词内容后，侧边栏重新开始生成翻译，而不保存上次翻译的结果。

**To Reproduce**
1. 划词翻译
2. 弹窗翻译，侧边栏同步显示
3. 去校划词
4. 侧边栏重新翻译

**Expected behavior**
因为gpt接口翻译的不确定性，希望保存上次翻译结果，避免出现准确结果被替换的问题

**Screenshots**
![image](https://user-images.githubusercontent.com/24293938/229395064-95f91151-b2db-4e41-be45-e47ef5aad5f7.png)
![4xUaxQLMHV](https://user-images.githubusercontent.com/24293938/229395821-781a7d8f-7ac3-4343-8158-ebb117603810.gif)

**Environment**
 - OS: Windows
 - Zotero Version 6.0.23
 - Addon Version 1.0.16

**Comment by Maasea** [comment]
看了以下触发自动翻译的代码，这个bug 似乎并不是GPT独有的。使用其他的翻译引擎也会在取消选中的时候再次翻译。

只不过其他翻译引擎是一次性显示所有结果，所以看起来像是保存了翻译。而GPT因为采用了 stream 模式，重新翻译的过程中会刷新面板，造成现在这种情况。

同样的文本让GPT 翻译两次得出的结果不一样是预期内的。

目前，最直接解决该问题的方式是关闭自动翻译。最终解决方式可能需要等待作者修复，或者我提交一个 PR。

**Comment by windingwind** [comment]
谢谢指出，我最近在重写笔记插件，可能没太多时间顾及这部分，欢迎pr
