### ISSUE TITLE
有关标题翻译

### ISSUE THREAD

**Issue by youyouhdhd** [windingwind/zotero-pdf-translate#425]
**Is your feature request related to a problem? Please describe.**
作者您好，我在更新插件之后发现标题翻译结果的位置发生了更改，同时，在“其他”栏出现了有关标题翻译的信息，这在使用的时候带来了一些困扰：首先之前的版本标题翻译显示在“短标题栏中”，更新后如果想要显示标题翻译不得不多展示一个标题栏，同时“其他”与别的插件有所冲突，有些插件会在其他栏存放内容
**Describe the solution you'd like**
给出一个能够使用旧版位置的选项，即还把结果存放在“短标题”栏

**Describe alternatives you've considered**
感谢作者的付出
**Additional context**
![Clip_20230404_222718](https://user-images.githubusercontent.com/54936458/229824723-7c5873c7-bc24-4c71-b96f-f987e242ada9.png)
![image](https://user-images.githubusercontent.com/54936458/229824861-1a8c1b65-569c-4eba-b61f-502a7e8916a3.png)

**Comment by windingwind** [comment]
见既往issue
