### ISSUE TITLE
选中的文本无法自动翻译

### ISSUE THREAD

**Issue by Florianismeandonlyme** [windingwind/zotero-pdf-translate#427]
如题，今天使用的过程中发现选中的文本无法自动翻译。问题如下：
![image](https://user-images.githubusercontent.com/58820847/229978572-2ffebdc1-3704-4354-92ae-d23001761160.png)
如上图，选中文本后在标注栏里出现了一个翻译的按钮，再次点击后才能进行翻译，且翻译结果不会自动加入标注当中。
翻译插件的设置如下：
![image](https://user-images.githubusercontent.com/58820847/229978751-84e9c301-4ede-46f7-9175-7381a36c2bac.png)

PS. 
1. 此问题仅在这篇文献中出现，当在其他文献中翻译时，并未出现此BUG。
2. 该问题出现前，我刚刚配置完Baidu API，不知道是否与此问题相关。

另一篇文献的翻译页面：
![image](https://user-images.githubusercontent.com/58820847/229979159-ab1e6c17-8d3b-49bc-81f7-0cc97f92fde1.png)

**Comment by windingwind** [comment]
请检查该文献的语言设置，是否触发了禁用自动翻译。

**Comment by Liong667** [comment]
nice！
