### ISSUE TITLE
[Bug]无法自动翻译

### ISSUE THREAD

**Issue by Hallalei** [windingwind/zotero-pdf-translate#429]
使用的是1.0.20版本

出现：虽然可以正常点击按钮翻译，但是不能自动划词翻译与注释自动翻译

![image](https://user-images.githubusercontent.com/93133421/230363652-db6669c8-2495-4554-91fb-e6fbbbbf269d.png)

之前偶尔出现，现在就是经常出现这个bug，试过很多办法如重启，与关闭可能有矛盾的插件（试过关闭greenfrog、zotero style）都还是不好使

![image](https://user-images.githubusercontent.com/93133421/230365738-479b854c-4e95-4a38-96f8-faa0da8c680d.png)
zheshiwod这是我的设置图

**Comment by windingwind** [comment]
#6

**Comment by suhw1999** [comment]
I have found the same problem, @windingwind . 

I'm not sure this is a bug or new design, but It's true that whatever I check the “Auto-Trans (selection)” or not, there would not be auto translated when I select the words or sentences.


the debug output:

(3)(+1300774): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000000): [Zotero PDF Translate] {}

(3)(+0000000): [Zotero PDF Translate] {}

(3)(+0000005): [Zotero PDF Translate] runTranslationTask {}

(3)(+0000001): [Zotero PDF Translate] disabledByItemLanguage

(3)(+0005457): [Zotero PDF Translate] {}

(3)(+0002919): [Zotero PDF Translate] [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Zotero PDF Translate] {}

**Comment by WHOLIDAY0328** [comment]
我之前也是这个问题，现在安装了最新版本的，应该是可以了。

**Comment by Hallalei** [comment]
今天自己又可以自动翻译了，我什么设置都没有改变。

**Comment by Hallalei** [comment]
> #6

您好，这个问题并不是我设置的问题，它会不经意间出现，比如我今天什么设置都没有调，只是把其他的一些插件重新打开了（比如greenfrog、chartero、citition等）它就又恢复了
![image](https://user-images.githubusercontent.com/93133421/230540299-a5927467-af32-49c4-a0df-75254a92d8be.png)
这是我目前开启的插件

**Comment by suhw1999** [comment]
作者你好，我这有同样的问题，最近更新后突然出现的

![2023-04-09_12-57](https://user-images.githubusercontent.com/83744319/230755237-7b7df670-55c2-422a-958c-3fa56977ef65.png)

我已经打开自动翻译，但还是需要点击翻译，我是在Ubuntu22.04上使用的，zotero和插件都是最新版，Ubuntu存在这个问题。但是win11上是正常的。

禁用和重装插件都试过，无法解决，我不确定是不是我这里的问题

系统Ubuntu22.04.2LTS
Zotero最新版和zotero-pdf-translate最新版

Debug输出（选择内容后）：
(3)(+0522037): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000000): [Zotero PDF Translate] {}

(3)(+0000001): [Zotero PDF Translate] {}

(3)(+0000000): [Zotero PDF Translate] {}

(3)(+0000007): [Zotero PDF Translate] runTranslationTask {}

(3)(+0000000): [Zotero PDF Translate] disabledByItemLanguage

> #6

**Comment by windingwind** [comment]
1. 看起来自动更新插件会导致自动翻译失效，可以重启zotero
2. ubuntu和其他操作系统理论上不会有ui以外的区别，请检查条目语言与设置中的禁用自动翻译语言

**Comment by suhw1999** [comment]
找到问题了

更新后由于我使用的Ubuntu以英文为默认语言，导致插件中 Disable Automatic Translation when File Language is(split with ,)为空，应该是插件检测到zotero系统语言为English，关闭了自动翻译。添加（中文,zh）功能回复正常。
![image](https://user-images.githubusercontent.com/83744319/230850262-5fc430ef-75c6-4026-b3aa-e72632a8ea8c.png)

感觉作者可以调整下自动翻译选项和此选项之间的逻辑优先级问题，（在以English为默认语言的系统中，插件更新到最新版此选项 Disable Automatic Translation when... 会被默认置为空，导致中文到English的自动翻译失效Bug）

**Comment by suhw1999** [comment]
> 找到问题了
> 
> 更新后由于我使用的Ubuntu以英文为默认语言，导致插件中 Disable Automatic Translation when File Language is(split with ,)为空，应该是插件检测到zotero系统语言为English，关闭了自动翻译。添加（中文,zh）功能回复正常。 ![image](https://user-images.githubusercontent.com/83744319/230850262-5fc430ef-75c6-4026-b3aa-e72632a8ea8c.png)
> 
> 感觉作者可以调整下自动翻译选项和此选项之间的逻辑优先级问题，（在以English为默认语言的系统中，插件更新到最新版此选项 Disable Automatic Translation when... 会被默认置为空，导致中文到English的自动翻译失效Bug）

@windingwind

**Comment by suhw1999** [comment]
找到问题了

更新后由于我使用的Ubuntu以英文为默认语言，导致插件中 Disable Automatic Translation when File Language is(split with ,)为空，应该是插件检测到zotero系统语言为English，关闭了自动翻译。添加（中文,zh）后功能恢复正常。

![image](https://user-images.githubusercontent.com/83744319/230852802-77ad1456-63f8-456f-81eb-f9009769ecac.png)

感觉作者可以调整下自动翻译选项和此选项之间的逻辑优先级问题，（在以English为默认语言的系统中，插件更新到最新版后，此选项 Disable Automatic Translation when... 会被默认置为空，导致English到中文的自动翻译失效Bug）

> 1. 看起来自动更新插件会导致自动翻译失效，可以重启zotero
> 2. ubuntu和其他操作系统理论上不会有ui以外的区别，请检查条目语言与设置中的禁用自动翻译语言

**Comment by Hallalei** [comment]
> 找到问题了
> 
> 更新后由于我使用的Ubuntu以英文为默认语言，导致插件中 Disable Automatic Translation when File Language is(split with ,)为空，应该是插件检测到zotero系统语言为English，关闭了自动翻译。添加（中文,zh）后功能恢复正常。
> 
> ![image](https://user-images.githubusercontent.com/83744319/230852802-77ad1456-63f8-456f-81eb-f9009769ecac.png)
> 
> 感觉作者可以调整下自动翻译选项和此选项之间的逻辑优先级问题，（在以English为默认语言的系统中，插件更新到最新版后，此选项 Disable Automatic Translation when... 会被默认置为空，导致English到中文的自动翻译失效Bug）
> 
> > 1. 看起来自动更新插件会导致自动翻译失效，可以重启zotero
> > 2. ubuntu和其他操作系统理论上不会有ui以外的区别，请检查条目语言与设置中的禁用自动翻译语言

果然好用了！！！！

**Comment by tianyang09** [comment]
> 添加（中文,zh
> 添加（中文,zh，怎么添加，在哪里可以添加？求帮助，谢谢

**Comment by tianyang09** [comment]
> > 找到问题了
> > 更新后由于我使用的Ubuntu以英文为默认语言，导致插件中Disable Automatic Translation when File Language is(split with ,)为空，应该是插件检测到zotero系统语言为English，关闭了自动翻译。添加（中文,zh）后功能修复正常。
> > ![图像](https://user-images.githubusercontent.com/83744319/230852802-77ad1456-63f8-456f-81eb-f9009769ecac.png)
> > 感觉作者可以调整下自动翻译选项和此选项之间的递优化优先级问题，（在以英语为默认语言的系统中，插件更新到最新版后，此选项 Disable Automatic Translation when... 会被默认设置为空，导致English到中文的自动翻译失效Bug）
> > > 1. 看起自动更新插件会导致自动翻译失败，可以重新启动zotero
> > > 2. ubuntu和其他操作系统理论上不会有ui以外的区域，请检查条款语言与设置中的禁止使用自动翻译语言
> 
> 果然好用了！！！！

怎么添加啊？

**Comment by tianyang09** [comment]
> 找到问题了
> 
> 更新后由于我使用的Ubuntu以英文为默认语言，导致插件中Disable Automatic Translation when File Language is(split with ,)为空，应该是插件检测到zotero系统语言为English，关闭了自动翻译。添加（中文,zh）后功能修复正常。
> 
> ![图像](https://user-images.githubusercontent.com/83744319/230852802-77ad1456-63f8-456f-81eb-f9009769ecac.png)
> 
> 感觉作者可以调整下自动翻译选项和此选项之间的递优化优先级问题，（在以英语为默认语言的系统中，插件更新到最新版后，此选项 Disable Automatic Translation when... 会被默认设置为空，导致English到中文的自动翻译失效Bug）
> 
> > 1. 看起自动更新插件会导致自动翻译失败，可以重新启动zotero
> > 2. ubuntu和其他操作系统理论上不会有ui以外的区域，请检查条款语言与设置中的禁止使用自动翻译语言
![image](https://github.com/windingwind/zotero-pdf-translate/assets/64260293/e8f7c3d9-6a49-4cbe-a8f3-17cfdb6e3b7c)
