### ISSUE TITLE
Translation Field Problems -- Zotero 6.0.23-beta.7+2e4fed400

### ISSUE THREAD

**Issue by djkatz49** [windingwind/zotero-pdf-translate#430]
When entering data into other Info fields, such as Author or Abstract, the selected field shifts to the **Title Translation field**.

Then appearing in the Extra field are repetitive entries like:

titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:
titleTranslation:

**Comment by windingwind** [comment]
Please clear the field and disable all other plugins and see if this still happens.

**Comment by djkatz49** [comment]
I disabled all the other plugins and restarted.

The only plug-in enabled was Zotero PDF Translate.

I tried to enter the first name in the Author field and the cursor shifted
up to the Title Translation field.

[image: image.png]

**Comment by michaelweinold** [comment]
@windingwind, I can confirm the issue persists in Zotero 6.0.26: 

![ezgif-2-3ee8a43f77](https://github.com/windingwind/zotero-pdf-translate/assets/23102087/38e75030-bafb-4fd0-83be-39a14a95b9f5)

**Comment by windingwind** [comment]
Copy. I'll take a look

**Comment by windingwind** [comment]
fixed in v1.1.0-1
