### ISSUE TITLE
[Bug] The function of modifying and updating translation results manually has disappeared

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-pdf-translate#432]
For  recent version , The function of modifying and updating translation results manually has disappeared, Or the function can not be activated .
I tried installing a lower version, but it still didn't work.

**Comment by windingwind** [comment]
It is enabled in the latest version. No need to enable it manually.

If it doesn’t work, please report it as a bug in a new issue.

**Comment by lil-i321** [comment]
> 

For 1.0.20, the update button cannot be triggered,  and reinstall 0.8.2 cannot be triggered either.
I remember in the past, after modifying the translation results, the update button could automatically display. Click the update button, translation results in the comment area will be updated.

**Comment by windingwind** [comment]
Retranslating will automatically update the annotation. You don’t need to press the button.

**Comment by lil-i321** [comment]
> Retranslating will automatically update the annotation. You don’t need to press the button.

Unable to update the  annotation in the conmment area after modified the translation results in the translate area.

**Comment by windingwind** [comment]
Not MODIFYING, but RETRANSLATING.

**Comment by lil-i321** [comment]
> Not MODIFYING, but RETRANSLATING.

之前的版本是可以修改翻译结果并在注释区更新，现在修改原文然后重新翻译，不能手动修改翻译后的结果。

**Comment by windingwind** [comment]
我确认最新版本正常工作。
1. 翻译某些任意文本
2. 开启或关闭自动翻译批注均可，批注某些文本
3. 右侧栏更新批注翻译结果，同时批注正常翻译（如果开启了自动翻译批注，则不会更新到右侧栏，需要手动点一下翻译按钮）
4. 修改翻译源文本，重新点击翻译按钮
5. 批注翻译结果正常更新

**Comment by windingwind** [comment]
直接在批注里修改即可

**Comment by lil-i321** [comment]
> 

好的，非常感谢！！
