### ISSUE TITLE
翻译窗口不显示，疑似插件未工作

### ISSUE THREAD

**Issue by chengxiangan** [windingwind/zotero-pdf-translate#433]
## 问题描述
您好，近期使用时翻译窗口在编辑-首选项、右侧条目栏窗口均未显示，按ctrl t也没有反应，如图：

![image](https://user-images.githubusercontent.com/130080931/230724474-c89938d7-8967-4b11-a079-d8be606f8701.png)

![image](https://user-images.githubusercontent.com/130080931/230724515-b719f7a8-bc09-4572-a687-545979fdf1dc.png)
 更新、重启插件均无法解决。降为旧版本（0.8.30）时，上述两窗口出现了翻译栏，但仍无法正常使用翻译功能，尝试了原有issues中的解决方案也无法翻译。

## 打开zotero后未进行任何操作，复制的调试日志如下：

[JavaScript Error: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/hp/AppData/Roaming/Zotero/Zotero/Profiles/bqi465ag.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/hp/AppData/Roaming/Zotero/Zotero/Profiles/bqi465ag.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js" line: 12889}]

version => 6.0.23, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.23, extensions => ZotFile (5.1.2.999, extension), DOI Manager (1.4.2, extension), Delitem (0.0.20, extension), Zotero Tag (0.3.0, extension), Zotero更新影响因子 (0.95.6, extension), Zotero Reference (0.1.5, extension), Jasminum (0.2.4, extension), Notero (0.4.6, extension), Zotero Better Notes (0.8.9, extension), Better BibTex for Zotero (6.7.67, extension), Zotero PDF Translate (1.0.20, extension), Shockwave Flash (28.0.0.161, plugin), Sci-Hub Plugin for Zotero (1.4.4, extension, disabled), Zotero IF (1.4.8, extension, disabled), Zotero Style (2.6.0, extension, disabled)

(3)(+0062076): Getting contents of C:\Users\hp\AppData\Roaming\Zotero\Zotero\Profiles\bqi465ag.default\treePrefs.json

(3)(+0000006): Writing column prefs of length 5962 to file C:\Users\hp\AppData\Roaming\Zotero\Zotero\Profiles\bqi465ag.default\treePrefs.json

**Comment by windingwind** [comment]
请在编辑-首选项-高级-设置编辑器，搜索pdftranslate，并删除所有设置，然后重启软件，看下

**Comment by chengxiangan** [comment]
> 请在编辑-首选项-高级-设置编辑器，搜索pdftranslate，并删除所有设置，然后重启软件，看下

已解决，谢谢您~

**Comment by menyLiu** [comment]
你好，我遇到了相同的问题。我在编辑-首选项-高级-设置编辑器，搜索pdftranslate中看到了一些加粗表示的文件，右击”重置“（因为在我的zotero中这些文件无法删除）随后重启软件，但并没有解决这个问题。我该如何做？

**Comment by 1index** [comment]
您好，我也遇到了相同的问题，请问您解决了吗？

**Comment by jiuyuanqingxiang** [comment]
您好，我按照上面的方法将所有可以reset的选项都reset了，翻译窗口还是不显示，请问该如何解决？

**Comment by windingwind** [comment]
请保证插件版本最新。报告问题时请按照#6提供所需信息

**Comment by jiuyuanqingxiang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Nouzen-86** [comment]
> 

我的问题是zotero将pdftranslate自动升级了1.0.26版本，然后翻译窗口就消失了。
我的解决方式是将zotero的pdftranslate移除，重新下载1.0.25版本就可以重新使用了，并且我关闭了zotero自动升级插件的选项。

**Comment by jiuyuanqingxiang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
