### ISSUE TITLE
[Bug] 插件的设置页面消失

### ISSUE THREAD

**Issue by luxiancao** [windingwind/zotero-pdf-translate#434]
### 情况描述
1. 已经安装插件
![1](https://user-images.githubusercontent.com/50064198/230748872-1639cc8d-7733-4e34-8387-7eb3f6529115.jpg)

2. 首选项中却没有出现插件的设置界面
![2](https://user-images.githubusercontent.com/50064198/230748880-433b6dc6-7e58-4d94-946f-f7545ea3c452.jpg)

### 已经尝试过但没有奏效的解决方法
1. 重新安装最新版插件
2. 重新安装最新版zotero

目前也没有查到能解决的办法，故只能求教作者大大

**Comment by windingwind** [comment]
请逐个禁用其他插件
