### ISSUE TITLE
在使用时，没有同时对比多个翻译引擎的结果的选项

### ISSUE THREAD

**Issue by zhangtou** [windingwind/zotero-pdf-translate#435]
**Describe the bug**
在中文文档介绍里有这样一句话：”右上角的+按钮可添加一个对比翻译引擎。翻译时，可以同时对比多个翻译引擎的结果。“但是我在最新版本1.0.20版本的插件里没有看到+按钮。

**Expected behavior**
支持对比翻译结果

**Screenshots**
![image](https://user-images.githubusercontent.com/50612347/230752028-7298d490-0046-4155-bfbf-be9c2a65812a.png)
![image](https://user-images.githubusercontent.com/50612347/230752129-73226bf0-8ab9-46c7-b78b-b951a0341399.png)

**Environment**
 - OS: Windows
 - Zotero Version ：6.0.23
 - Addon Version：1.0.20

**Additional context**
第一个图是插件介绍里面的，第二个图是本人使用的界面

**Comment by windingwind** [comment]
在独立翻译窗口

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/230784386-924b03d3-4163-4ba3-a9c7-18c5538ae03e.png)
