### ISSUE TITLE
同时打开多个pdf时侧边栏窗口发生错位

### ISSUE THREAD

**Issue by Leonoves** [windingwind/zotero-pdf-translate#437]
如下图：
![image](https://user-images.githubusercontent.com/85266230/230849770-c1af508a-8c41-4cfa-94af-79abc0eaf658.png)
![image](https://user-images.githubusercontent.com/85266230/230849803-f1aeafb3-cb6a-4e82-8cb7-babc15a8aaf8.png)
同时打开两个窗口后侧边栏翻译窗口发生错位，不知是翻译插件的问题还是zotero自身的问题。插件版如下，自动跟更新：
![image](https://user-images.githubusercontent.com/85266230/230850202-b2f9e851-a293-40bf-97b1-e97b0b08684f.png)

**Comment by octahedron-lh** [comment]
我也有这个问题, 侧边栏老是乱的.  之前的版本是切换文献时 信息不随着切换   现在多了bug是像楼上那样

**Comment by Leonoves** [comment]
已经解决了，不是这个插件的问题。一般是主题类插件导致的，停用就好了。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月12日 00:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] 同时打开多个pdf时侧边栏窗口发生错位 (Issue #437) |

我也有这个问题, 侧边栏老是乱的. 之前的版本是切换文献时 信息不随着切换 现在多了bug是像楼上那样
