### ISSUE TITLE
翻译的弹窗无法记住大小

### ISSUE THREAD

**Issue by pupupupu4444** [windingwind/zotero-pdf-translate#439]
使用1.0.14的时候，翻译弹窗无法记住大小
更新到1.0.20的时候，情况并没有得到改善

**Comment by windingwind** [comment]
请截图设置，详细描述操作过程

**Comment by pupupupu4444** [comment]
![1](https://user-images.githubusercontent.com/130426276/232178624-3371885b-ef82-4c72-b3fa-ebdb3f63eab5.png)
![2](https://user-images.githubusercontent.com/130426276/232178628-dfbf8ca3-e339-4503-bc06-58be88814c56.png)
