### ISSUE TITLE
[Feature]Request to add Ali Translate Professional Edition

### ISSUE THREAD

**Issue by aoaim** [windingwind/zotero-pdf-translate#44]
According to my experience on Bob, Ali Translate Pro works very well. I hope it can be added to this plugin, thanks!
https://mt.console.aliyun.com/basic

**Comment by windingwind** [comment]
Calling AliCloud API without open-SDK is not that easy, while the SDK is based on the Node.js platform, quite different from the browser environment of Zotero.

This feature may not be supported. Thanks for your suggestion.
