### ISSUE TITLE
error of PDF Translate when filling author fields 

### ISSUE THREAD

**Issue by mlana** [windingwind/zotero-pdf-translate#440]
**Describe the bug**/ **To Reproduce**
in zotero when i fill the "author" field it happens that:
i write the "last name"
then i tap "tab" to go the "first name" field,
at that point the cursor jumps to the "title translation" field
and if i click with the pointer on the "first name" field,
the focus remains in the "title translation" field
but in the "extra" field a string "title translation:" starts to appear,
and multiplies itself at every click in the "first name" field.

to stop all this and to be able to fill the "first name" field, i must click outside the info panel, on anything in the other panes; then i re-click on the "first name" field and it is now fillable; apparently it happens with any item (book, email, journal, report, ecc.) i choose.

if i disable zotero PDF translate the problem is gone

**Expected behavior**
i can fill the author fields by orderly jumping from one to the following by using the pointer or the TAB key

**Environment**
 - OS: macOs 13.2.1; 
 - Zotero Version: 6.0.23 
 - Addon Version: 1.0.20

**Comment by maximeescande** [comment]
Same behavior on
    Ubuntu 20.04;
    Zotero Version: 6.0.23
    Addon Version: 1.0.20
Temporary fix by un-ticking "Info Panel: Show Title Translation" and "Info Panel: Show Abstract Translation" in Zotero Edit > Preferences > Translate.

**Comment by mlana** [comment]
wonderful,
thank you!!
Maurizio

Il 14/04/23 13:54, maximeescande ha scritto:
>
> Same behavior on
> Ubuntu 20.04;
> Zotero Version: 6.0.23
> Addon Version: 1.0.20
> Temporary fix by un-ticking "Info Panel: Show Title Translation" and 
> "Info Panel: Show Abstract Translation" in Zotero Edit > Preferences > 
> Translate.
>
> Message ID: 
> ***@***.***>
>


------------------------------------------------------------------------

------------------------------------------------------------------------
Maurizio Lana - 347 7370925

**Comment by windingwind** [comment]
Ohh sorry for the late reply. I have not had time to look into this.

This is a known issue with the upper stream dependency  zotero-plugin-toolkit. Hopefully someone else can look into it and see if it can be fixed.

I will be traveling in the next few days and may not have much time.

**Comment by githubnll** [comment]
I also have this problem, when I fill in the author, it jumps to the title translation, and under "Other" it shows

**Comment by MagicanX** [comment]
The problem is still relevant. Still no solution found?
