### ISSUE TITLE
[Bug]auto translate not work

### ISSUE THREAD

**Issue by asdeww22** [windingwind/zotero-pdf-translate#441]
auto translate not work and show a click for translate
before it work good but after update not work

**Comment by suhw1999** [comment]
Check the following setting (Disable Automatic Translation when File Language is(split with ','), If it's empty, then try to fill it with (zh, 中文, 中文), this will work out.
![image](https://user-images.githubusercontent.com/83744319/232420605-509bc58b-de38-4e42-b590-1ed3a562f57c.png)

This bug will appear when your Zotero Language is English, and has already been mentioned in #429 .

Hope helpfull. @asdeww22

**Comment by asdeww22** [comment]
> Check the following setting (Disable Automatic Translation when File Language is(split with ','), If it's empty, then try to fill it with (zh, 中文, 中文), this will work out. ![image](https://user-images.githubusercontent.com/83744319/232420605-509bc58b-de38-4e42-b590-1ed3a562f57c.png)
> 
> This bug will appear when your Zotero Language is English, and has already been mentioned in #429 .
> 
> Hope helpfull. @asdeww22
worked
thank you
