### ISSUE TITLE
Zotero pdf translate和zotero reference插件不兼容

### ISSUE THREAD

**Issue by AlexLee1992** [windingwind/zotero-pdf-translate#444]
![image](https://user-images.githubusercontent.com/38725845/232755739-6aebe68e-7d3c-41d8-be5b-26929a688d21.png)
像图中这种，有时候有很多参考文献窗口，有时候有很多翻译窗口，有的时候两个又都不显示，请问一下这个怎么解决啊？

**Comment by DegreeL** [comment]
这个插件好像和Night for Zotero这种护眼功能的插件不兼容  把这类插件disable就好了
