### ISSUE TITLE
[Bug]信息栏的标题翻译和摘要翻译会自动强制锁定输入光标在这两个的输入框，不能切换到信息栏其他字段

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [windingwind/zotero-pdf-translate#447]
以下任一情况输入光标会自动跳转到 “标题翻译或者摘要翻译的输入框“”，并强制锁定光标在此，并在《其他字段》输出 “titleTranslation:‘’。
      ①点击了标题翻译或者摘要翻译输入框
      ②修改了信息栏的任何一个字段，但是没点回车
       光标每点击一次任何别的字段（比如档案、存档位置等），就会在《其他字段》输出一行 “titleTranslation:‘’，然后光标就自动跳回标题翻译或者摘要翻译的输入框，导致不能编辑信息边栏其他项。
        陷入死循环后，除非再点击一次标题，才能恢复正常。

**Comment by volatile-static** [comment]
#440 重复了
