### ISSUE TITLE
duplicate translate panels 

### ISSUE THREAD

**Issue by gglin001** [windingwind/zotero-pdf-translate#448]
不确定什么操作导致出现多个(不止两个) 翻译 的 panel

如下图

<img width="578" alt="Screen Shot 2023-04-21 at 2 51 31 PM" src="https://user-images.githubusercontent.com/13805221/233562977-095cb881-1239-4443-9b03-89b23a2a3a35.png">

**Comment by crazy-zxx** [comment]
+1
windows11 用户也遇到了这个问题，而且频繁出现

**Comment by volatile-static** [comment]
我这边没有发现哎，你们都用了哪些插件？

**Comment by crazy-zxx** [comment]
![image](https://user-images.githubusercontent.com/29439759/233782103-d28aa24c-5f2b-4de5-999a-8f43d12ed570.png)
我使用的插件列表：
![image](https://user-images.githubusercontent.com/29439759/233782115-962a54dc-175a-472f-836d-806faba1d0e3.png)
Night for Zotero：https://github.com/tefkah/zotero-night
zotero GPT：https://github.com/MuiseDestiny/zotero-gpt
Zotero lF Pro Max：https://github.com/zibrr/zotero-if-pro-max_cracked
Zotero PDF Preview：https://github.com/windingwind/zotero-pdf-preview

**Comment by gglin001** [comment]
>  Night for Zotero：https://github.com/tefkah/zotero-night

似乎将这个插件禁用以后会消失

**Comment by gglin001** [comment]
可以确认 插件

> Night for Zotero：https://github.com/tefkah/zotero-night

会导致这个问题, 关闭以后重启 zotero 会消失, close issue
