### ISSUE TITLE
After some translation in ZOTERO: "Error: HTTP POST https://www2.deepl.com/jsonrpc failed with status code 429"

### ISSUE THREAD

**Issue by pcavicch** [windingwind/zotero-pdf-translate#449]
[Request Error]

Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: 
 https://github.com/windingwind/zotero-pdf-translate/issues 

The message below is not Zotero or the PDF Translate addon,  but from DeepLx

Error: HTTP POST https://www2.deepl.com/jsonrpc failed with status code 429

**Comment by windingwind** [comment]
No promises to these free apis. 429 error code means too many requests.
