### ISSUE TITLE
[Bug] Language settings cannot be saved.

### ISSUE THREAD

**Issue by skymagician** [windingwind/zotero-pdf-translate#45]
**Describe the bug**
Language settings cannot be saved. When you restart Zotero, it will reset to default.

**To Reproduce**
1. Go to 'preferences'
2. Click on 'translate from English-US to Chinese-China'
3. Restart Zotero

**Expected behavior**
'Translate from English-US to Chinese-China' should be saved when you restart Zotero. 

**Environment**
 - OS: Windows 11 21H2
 - Zotero Version(6.0.3)
 - Addon Version(0.3.5)

**Additional context**
Zotero language is set to English.

**Comment by windingwind** [comment]
see #42
