### ISSUE TITLE
[Bug] The translators do not work, except Google.

### ISSUE THREAD

**Issue by Txindoki666** [windingwind/zotero-pdf-translate#450]
Greetings, I have installed the add-on but only Google works as a source for the translation. The other translators do not work.
Hopefully it can at least be fixed Deepl. 
Thank you.

Contex: 
[Request Error]

Engine not available, invalid secret, or request too fast.
Use another translation engine or post the issue here: 
 https://github.com/windingwind/zotero-pdf-translate/issues 

The message below is not Zotero or the PDF Translate addon,  but from DeepL(Free Plan)🗝️

Error: HTTP POST https://api-free.deepl.com/v2/translate failed with status code 403

**Comment by windingwind** [comment]
See #6
