### ISSUE TITLE
小牛翻译引擎api过期了，求更新

### ISSUE THREAD

**Issue by Joshua2228** [windingwind/zotero-pdf-translate#452]
**Describe the bug**
小牛翻译引擎api证书过期了，在北京时间2023/04/24 11:26.

**To Reproduce**
选中搜索，就会出现已过期的字样

**Expected behavior**
请更新一下证书，谢谢

**Screenshots**
![image](https://user-images.githubusercontent.com/131666481/233973950-9eec0303-9836-43ac-aac2-00c37c8104a4.png)

**Environment**
 - OS: Windows
 - Zotero 6.0.26(Help->About Zotero)
 - Addon 1.0.20Tools->Add-ons)

**Additional context**

**Comment by ZoeZhang2023** [comment]
请问这是小牛翻译的问题还是zotero的问题，根据提示写的是小牛翻译安全证书到期的问题，请问如何解决啊

**Comment by zgq2020** [comment]
我也是这个问题

**Comment by WenjieXu2000** [comment]
同样的问题，我感觉是小牛那边的问题

**Comment by zgq2020** [comment]
出现这个问题，然后关闭zotero或者重启电脑。重新打开zotero，可以正常使用，没多久又出现这个问题

**Comment by Acid1982** [comment]
me too

**Comment by windingwind** [comment]
小牛侧的问题，等他们修复，和插件无关

**Comment by Xieleilab** [comment]
我也是这个问题

**Comment by ZoeZhang2023** [comment]
登录小牛翻译官网找到客服反馈了这个问题，说是正在排查中，晚些时候重启试试。

**Comment by dogingate** [comment]
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 小牛🗝️

Zotero Error: api.niutrans.com uses an invalid security certificate.

The certificate expired on 2023年4月24日 11:26. The current time is 2023年4月25日 12:38.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by octahedron-lh** [comment]
请问为什么还是没法用小牛翻译啊~    客服说已经修复了好像

**Comment by dogingate** [comment]
现在可以了，应该是小牛的问题，我切换了其他翻译器没有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月30日(周日) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [windingwind/zotero-pdf-translate] 小牛翻译引擎api过期了，求更新 (Issue #452)




 
请问为什么还是没法用小牛翻译啊~    客服说已经修复了好像

**Comment by octahedron-lh** [comment]
那为什么我还是不可以, 显示和你一样的请求错误...额

**Comment by dogingate** [comment]
不知道了，我用的是windows，好久没用了，你在试试么



***@***.***
 
发件人： yilifanghaishui
发送时间： 2023-05-01 13:10
收件人： windingwind/zotero-pdf-translate
抄送： dogingate; Comment
主题： Re: [windingwind/zotero-pdf-translate] 小牛翻译引擎api过期了，求更新 (Issue #452)
那为什么我还是不可以, 显示和你一样的请求错误...额
