### ISSUE TITLE
[Bug]插件勾选“弹窗 记住大小”，只记高度不记宽度

### ISSUE THREAD

**Issue by dongfangxiyu** [windingwind/zotero-pdf-translate#453]
**Describe the bug**
插件勾选“弹窗 记住大小”，只记高度不记宽度

**To Reproduce**
1. Go to '编辑->首选项->翻译->用户界面->弹窗：记住大小'
2. Click on '弹窗：记住大小'
3. 随意划词翻译 

**Expected behavior**
改变弹窗大小后，只有高度被记住，宽度始终为默认值，且没有自适应变化

**Screenshots**

**Environment**
 - OS: Windows
 - Zotero Version 6.0.26 (Help->About Zotero)
 - Addon Version 1.0.20 (Tools->Add-ons)

**Additional context**

**Comment by baird19** [comment]
插件版本 1.0.20和22版本都没有修复

**Comment by QiguaiR** [comment]
我的也是，只记高度，不记**宽度**。而且弹窗里也没有显示”添加翻译到笔记“的选项。
