### ISSUE TITLE
GOOGLE API请求错误

### ISSUE THREAD

**Issue by LemonBoy68** [windingwind/zotero-pdf-translate#454]
GOOGLE API请求错误。

[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： Google

Zotero Error: An error occurred during a connection to translate.3822808.com.

Encountered end of file

version：latest
platform：Win11

**Comment by chstu1** [comment]
请问您解决这个问题了吗
