### ISSUE TITLE
UP你好，这是我的一个需求和建议。

### ISSUE THREAD

**Issue by heyeruoqi** [windingwind/zotero-pdf-translate#455]
你好，我是一个理科转文科的硕士生，之前在使用Marginnote3的时候，选中一部分文字点击研究，可以弹出内置浏览器搜索文本，可以选择百度引擎，谷歌引擎，百度图片，谷歌图片，百度学术，谷歌学术，百度翻译，腾讯翻译，谷歌翻译等等其他翻译，而Windows上我只找到了edge浏览器打开的pdf，选中文字点击放大镜才能实现搜索的类似功能，所以特别需要Windows上zotero有一款插件能实现上述要求，我今天用GPT4写了相关的代码，奈何没学过js和css等内容，也不会封装，既不知道能不能跑的通，也不知道GPT4写得有没有什么问题，我相信这个需求不止有我一个人有，对于没有文科背景的理科生，看论文需要不断查资料，如果选中文本按住快捷键弹出一个窗口能搜索内容，并在再次选中其他文本的时候刷新显示新的文本的查找内容就更好了，我可以给您GPT4的代码作为参考。
以下是我训练GPT4的时候的需求指令：

如果我想做一个zotero的插件，实现的功能为当我使用zotero将pdf打开，并将某几个文字选中，会弹出一个窗口，这个窗口上呈现我刚刚选中的文字在不同网站上的搜索结果。这些文字可以在不同的网站上被搜索，我分为以下几类：文本搜索类，名词搜索类，学术搜索类，问题搜索类，图片搜索类，翻译类，地图类，历史类。这些类别可以被用户选择，且每一类别中的每一项也能被用户选择。文本搜索类为在谷歌、必应、百度三个搜索引擎上搜索选中的文字的搜索结果，默认搜索引擎为百度，名词搜索类为在百度百科、维基百科、搜狗百科上搜索选中文字的搜索结果，学术搜索类为在谷歌学术、百度学术、必应学术这三个网站搜索选中的内容，问题搜索类为在quora，知乎这两个网站搜索选中的内容。图片搜索类为在谷歌图片、必应图片、百度图片三个图片搜索网站搜索选中的关键词，翻译类为在谷歌翻译、百度翻译、彩云小译、腾讯翻译君、deepl这五个网站将选中内容进行文本翻译，另外，请在翻译类再增加一项，chatgpt翻译，你将选中内容翻译为中文后将翻译完的内容显示在chatgpt翻译窗口界面上，地图类为请将选中内容在高德地图、百度地图、谷歌地图等网站搜索，并将选中内容在百度百科网站和维基百科网站的介绍内容附在窗口界面，历史类为将选中内容在百度百科和维基百科中查找相关资料，将相关内容呈现在窗口界面，并将查到的资料按照历史时间发生的先后顺序按照1.2.3.4这样的顺序列出，若结果出现地面，请将地名作为超链接，以方便我点击这个地名可以跳转到百度百科，最后，将这个插件封装成xpi格式。我该如何写代码，这个代码在什么软件上能运行，如何封装等所有顺序跟我详细说一说。

当然，我最开始肯定以为GPT如果能做到最好的话，那么我新增加的地图、历史等需求也能做到，现在想想要求还是高了，如果up可以考虑做这个插件的话，我可以付费，我也问过淘宝的一些做插件的卖家，都没回复，可能其他人也需要这个功能，可以从最简单的直接打开百度引擎，谷歌引擎开始，一版一版地增加新的功能。我反而奇怪的是为什么这么久都没人提过这个需求。

**Comment by XingyanMao** [comment]
这一功能可以通过quicker实现呀~可以试试quicker里的动作“EVER智识”，不过需要根据你的要求自定义了

**Comment by windingwind** [comment]
你好，
关于插件开发，可参考https://zotero.yuque.com/staff-gkhviy/developer

**Comment by windingwind** [comment]
由于与插件无关，此处关闭
