### ISSUE TITLE
希望优化音标排列

### ISSUE THREAD

**Issue by healerlalala** [windingwind/zotero-pdf-translate#459]
因为平常笔记是和obsidian联动的，一些生词的英音和美音的音标是竖排下来的，有些占地方。如果可以的话，希望可以实现横排效果。
<img width="246" alt="image" src="https://user-images.githubusercontent.com/128845767/236625132-473f1704-ee7a-4351-936d-48a5d0faa600.png">
希望可以能有这样的呈现，谢谢开发者大大！
<img width="681" alt="image" src="https://user-images.githubusercontent.com/128845767/236625166-13304ca9-53c9-40dc-8c22-af4f17663f3c.png">

**Comment by windingwind** [comment]
谢谢建议，这方面是众口难调的，所以不考虑改动。谢谢理解！
