### ISSUE TITLE
当选中文本为中文时，希望可以不进行“自动翻译”与“注释翻译”

### ISSUE THREAD

**Issue by lllaterOn** [windingwind/zotero-pdf-translate#46]

**Comment by windingwind** [comment]
You can change the preference settings.

**Comment by windingwind** [comment]
v0.3.12 support this feature.

**Comment by lllaterOn** [comment]
Thank you very much for your prompt reply and update! I've updated the plugin to v0.3.12, but it doesn't seem like what's in the Settings interface has changed. Where is this feature set up? I want the selected English text to be automatically translated when I turn on the Auto Translate feature, but the selected Chinese text is not translated.


&nbsp;(The above content is translated by Microsoft, if my functional requirements are causing you trouble, I am very sorry)









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 晚上11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate] 当选中文本为中文时，希望可以不进行“自动翻译”与“注释翻译” (Issue #46)





 
v0.3.12 support this feature.

**Comment by lllaterOn** [comment]
Hello! I'm sorry to have caused you trouble due to my negligence.&nbsp;
I've learned how to use the new features. Thank you for answering so patiently!&nbsp;
I wish you a smooth work and a happy life!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 凌晨0:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-translate] 当选中文本为中文时，希望可以不进行“自动翻译”与“注释翻译” (Issue #46)





 

 Set this to the languages that you don't want to translate.
 
You can find language here:
 
 
Sometimes Chinese papers will be marked as zh, zh-CN, '中文', '中文;', etc. Make sure to cover all of them and concat with ','(comma), like this: zh,zh-CN,中文,中文;

**Comment by windingwind** [comment]
: )
