### ISSUE TITLE
[Feature]添加批量翻译等待时间

### ISSUE THREAD

**Issue by lyk7539511** [windingwind/zotero-pdf-translate#460]
**Is your feature request related to a problem? Please describe.**
当使用gpt作为翻译引擎时，OpenAI官方对于API的请求频率有限制，每分钟不超过3次，因此如果批量翻译标题或摘要的时候就会出现脚本自动跳过超时未反应的翻译内容，从而造成翻译遗漏的情况。

**Describe the solution you'd like**
请求在批量翻译标题等类似任务时添加等待时间以避免自动跳过，或者限制每两次翻译的间隔时间。

**Comment by windingwind** [comment]
欢迎pr。可在设置中增加一个选项。目前间隔时间是写死的1s

**Comment by lyk7539511** [comment]
好的。
我没有使用过TS，也没写过zotero的插件，所以还需要时间看，请暂时先不要关这个issue，谢谢

**Comment by Geo123abc** [comment]
可以考虑支持多个gpt账号做负载均衡

沉浸式翻译扩展支持多个 API Key 负载均衡, 请在填写的时候用英文逗号 , 分隔不同的 key  [来自](https://immersivetranslate.com/docs/services/openai/#:~:text=%E6%B2%89%E6%B5%B8%E5%BC%8F%E7%BF%BB%E8%AF%91%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%20API%20Key%20%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%2C%20%E8%AF%B7%E5%9C%A8%E5%A1%AB%E5%86%99%E7%9A%84%E6%97%B6%E5%80%99%E7%94%A8%E8%8B%B1%E6%96%87%E9%80%97%E5%8F%B7%20%2C%20%E5%88%86%E9%9A%94%E4%B8%8D%E5%90%8C%E7%9A%84%20key)

**Comment by ASC8384** [comment]
请问能否提供自定义超时时限的选项？
用的是自建服务，在翻译长文本上可能有点满。
