### ISSUE TITLE
[Bug] 无法翻译某些 RSS Feed 订阅

### ISSUE THREAD

**Issue by lyk7539511** [windingwind/zotero-pdf-translate#461]
**Describe the bug**
某些情况下无法正确执行翻译

**To Reproduce**
点击左上角的棕色按钮->new Feed->add URL即可添加订阅
可以用这两个RSS链接进行测试
http://export.arxiv.org/rss/cs.CV 可以正常翻译
https://ieeexplore.ieee.org/rss/TOC42.XML 无法翻译
https://rss.sciencedirect.com/publication/science/15320464 无法翻译

**Expected behavior**
正确翻译题目和摘要

**Screenshots**
![Screen Recording 2023-05-07 at 09 53 20](https://user-images.githubusercontent.com/26186177/236653776-a606d7fc-fde7-4fe9-9d0f-67adb568951d.gif)

**Environment**
 - OS: macOS
 - Zotero Version：6.0.26
 - Addon Version(Tools->Add-ons)：1.0.22

**Comment by windingwind** [comment]
翻译条目需要写入数据到条目，但订阅应当是不可修改的，该功能不是为订阅设计的。部分订阅可以修改的话就可以翻译，修改不了就不能翻译。
