### ISSUE TITLE
划词翻译无法朗读

### ISSUE THREAD

**Issue by LemonBoy68** [windingwind/zotero-pdf-translate#463]
大家好~
请问大家有选中词汇无法有朗读的图标吗？试了好几个版本都不行(设置已勾选朗读发音)，大家有类似的问题吗？

platform:W11
zotero: latest
plugin: latest

**Comment by Ask-Yang** [comment]
+1,有音标但是没有小喇叭。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/80316215/fa21a75a-89d0-4813-bbba-d1d92e7ab629)

**Comment by Ask-Yang** [comment]
> +1,有音标但是没有小喇叭。 ![image](https://user-images.githubusercontent.com/80316215/237568235-fa21a75a-89d0-4813-bbba-d1d92e7ab629.png)

重装也没用。但我另一个电脑上就没问题，不知道什么原因。

**Comment by LemonBoy68** [comment]
> 没

真的很奇怪阿，难道是zotero的问题吗？

**Comment by Ask-Yang** [comment]
要是有个办法能彻底卸载插件就好了，不知道插件的元信息在哪。

**Comment by Ask-Yang** [comment]
我的出问题的zotero版本是6.0.26

**Comment by LemonBoy68** [comment]
我的是最新版的，不知不觉就自己更新了，想改回老版本，我担心卸载以后原来的插件都没啦

**Comment by Ask-Yang** [comment]
重装插件和重装zotero都没用。应该是元信息有问题。不知道插件的元信息放在哪个文件里。

**Comment by windingwind** [comment]
可能是数据源页面改动导致的。有空我会检查一下
