### ISSUE TITLE
[Bug]接入GPT翻译服务后字典翻译失效&词组翻译效果不佳

### ISSUE THREAD

**Issue by MarioZZJ** [windingwind/zotero-pdf-translate#466]
**Describe the bug**
翻译服务选择 GPT，同时勾选打开字典服务。对词语进行翻译时好像还是默认调用了 GPT。另外，GPT 对单词、词组的翻译效果不好，可能需要设置规则或修改 prompt。

**To Reproduce**
1. 配置翻译服务
2. PDF 中选中单词或词组
3. 点击翻译

**Expected behavior**
1. 检测为词语，则走字典翻译。
2. 加强对词组的翻译效果。

**Screenshots**
1. 配置服务
![图片](https://github.com/windingwind/zotero-pdf-translate/assets/52254876/201d4032-a102-4f26-92de-62b325cd6941)
2. 对单词进行翻译，调用的貌似还是 GPT，而且输出了 prompt 的翻译
![效果1：单词](https://github.com/windingwind/zotero-pdf-translate/assets/52254876/27769219-6e0b-4380-804a-b1c0d1d0fd91)
3. 对词组进行翻译，貌似结果变成了续写
![效果2：词组](https://github.com/windingwind/zotero-pdf-translate/assets/52254876/22bb0327-a432-4679-acff-e145f11feb36)

**Environment**
 - OS: Windows
 - Zotero Version 6.0.25
 - Addon Version 1.0.22

**Comment by MarioZZJ** [comment]
![图片](https://github.com/windingwind/zotero-pdf-translate/assets/52254876/f8ae9e89-5d73-4db6-a926-a98183d2d573)
![图片](https://github.com/windingwind/zotero-pdf-translate/assets/52254876/05d8cb1f-4a4c-4417-ba6f-5ef47333afc5)

@lyk7539511 你好，留意到你的 PR #442 ，我在 playground 复现得到一样的结果，方便修一下嘛？

@windingwind 请问没有调用词典的原因可能是什么呢

**Comment by windingwind** [comment]
理论上，根据是否有空格来决定调用的翻译服务（词典或翻译）。也许是这段话的原文pdf选中的文本中含有空格。
