### ISSUE TITLE
[Bug] 将高级设置中的分割符 🔤改为星号*之后无法翻译

### ISSUE THREAD

**Issue by Wangmz-1211** [windingwind/zotero-pdf-translate#467]
**Describe the bug**
如题，将高级设置中的分割符 🔤改为星号*之后无法翻译。
- 未修改：选中文本时会弹出窗口，包含翻译内容
- 修改后：窗口中只有翻译按钮，点击后过一会显示英文内容，之后不会进行翻译

**To Reproduce**
1. 点击Zotero首选项
2. 选择“翻译”选项卡
3. 高级 - 分隔符，修改为 *

**Expected behavior**
翻译功能正常，并在其他插件导出的Markdown中自动粗体

**Screenshots**
- 修改前
![image](https://github.com/windingwind/zotero-pdf-translate/assets/72479273/259818fb-9049-4bd7-9374-9ffc98c28c21)

- 修改后
![image](https://github.com/windingwind/zotero-pdf-translate/assets/72479273/aff58940-b1b9-471a-9f26-f19d2af4be32)

**Environment**
 - OS: Linux
 - Zotero Version 6.0.26
 - Addon Version 1.0.22

**Comment by Maasea** [comment]
因为 `*` 是正则的一个符号，没有做转义造成无法完成翻译。

我尝试修改代码，发现即使使用 `**` 作为分隔符，导出笔记后以如下的形式显示，而不是加粗。
> 你可以手动将注释内的分隔符改成 `**` ，来复现下面的结果。

![image](https://github.com/windingwind/zotero-pdf-translate/assets/41108003/d1a3c477-dd58-4046-ae99-f7e5961456bd)

**猜测原因**：

在使用 _从注释中添加笔记_ 时，Zotero 会对笔记内的一些符号做一次转义，以保留最原始的笔记内容，`**` 会被改成 `\*\*`。这是因为有些注释的内容本来就是 `**`，如果导出成笔记变成加粗，对于不了解 Markdown 的用户来说反而是一件奇怪的事情。

**Comment by Wangmz-1211** [comment]
感谢回复！
