### ISSUE TITLE
请问小牛翻译一直是这样的错误怎么办?

### ISSUE THREAD

**Issue by octahedron-lh** [windingwind/zotero-pdf-translate#470]
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 小牛🗝️

Zotero Error: api.niutrans.com uses an invalid security certificate.

The certificate expired on 2023年4月24日 5:26. The current time is 2023年5月22日 21:59.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by octahedron-lh** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/73725434/597ee900-9691-4bf8-9eea-8cdbe08c5866)
有大神帮忙指导一下吗...一直用不上比失恋了还难受

**Comment by Chenchengz1** [comment]
请问解决了吗，我也是这个问题

**Comment by xushipeng1990** [comment]
同问，我也是这个问题。

**Comment by SCger007** [comment]
可以按照readme里面输入密钥的格式修改一下。
例：有道智云：用户ID#密钥
按照这个格式去输入可能会解决问题

**Comment by octahedron-lh** [comment]
> 可以按照readme里面输入密钥的格式修改一下。 例：有道智云：用户ID#密钥 按照这个格式去输入可能会解决问题

还是不行啊哥们, 小牛翻译都没有用户ID的.

**Comment by octahedron-lh** [comment]
> 请问解决了吗，我也是这个问题

我将插件-script代码里面的api地址前缀从https://api.niutrans........改成了http://api.niutrans......就好了.

**Comment by octahedron-lh** [comment]
> 同问，我也是这个问题。

我将插件-script代码里面的api地址前缀从https://api.niutrans........改成了http://api.niutrans......就好了.
