### ISSUE TITLE
[Feature] GPT翻译建议可以增加定义学科领域的选项

### ISSUE THREAD

**Issue by maizhouzi** [windingwind/zotero-pdf-translate#471]
用GPT翻译功能希望可以增加一个输入学科领域的选项，映射到prompt类似于：你是一个xx领域的研究人员，帮我翻译...
这样定义学科领域后翻译准确度可以提高，比如定义了AI领域，Transformer翻译时就会保留，而如果不定义，它会被翻译为变压器。
这个是该插件的
![image](https://github.com/windingwind/zotero-pdf-translate/assets/66940944/46e78898-a389-46a0-bfa8-60e9568a05ce)
这个是调用gpt3.5的，但是告诉了学科领域的翻译
![image](https://github.com/windingwind/zotero-pdf-translate/assets/66940944/c131529f-dc63-4ee8-b85a-b64647c007a1)

**Comment by windingwind** [comment]
Welcome PR

**Comment by fredericky123** [comment]
请求open ai configure里允许自定义prompt

**Comment by windingwind** [comment]
最新预发布版本已支持
