### ISSUE TITLE
CNKI doesn't work

### ISSUE THREAD

**Issue by Evane5cence** [windingwind/zotero-pdf-translate#472]
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： CNKI

Error: HTTP GET https://dict.cnki.net/fyzs-front-api/getToken failed with status code 404

**Comment by Blake-D1141** [comment]
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： CNKI

Error: HTTP GET https://dict.cnki.net/fyzs-front-api/getToken failed with status code 404
