### ISSUE TITLE
翻译的时候都会有🔤类字符出现

### ISSUE THREAD

**Issue by TheShy-Dream** [windingwind/zotero-pdf-translate#473]
**Describe the bug**
每次翻译的时候都会有🔤类字符出现

**To Reproduce**
1. 选中自动翻译即可复现

**Expected behavior**
返回翻译并且没有🔤

**Screenshots**
![image](https://github.com/windingwind/zotero-pdf-translate/assets/58178926/b10c97a0-b5e5-4c37-99fc-1773e87b946e)

**Environment**
 - OS: Windows
 - Zotero Version:6.0.26
 - Addon Version:1.0.22

**Additional context**
不知道作者是有意设置的图标还是一不小心转义时候出了错，最好能够去掉

**Comment by JeffeyChou** [comment]
> 

在设置中可以选择分隔符
![image](https://github.com/windingwind/zotero-pdf-translate/assets/90391082/043b0295-210d-44ef-b689-278b36216be8)

**Comment by TheShy-Dream** [comment]
Thank you very much.
