### ISSUE TITLE
[Bug]插件导致信息面板元数据无法编辑，因为焦点自动跳到标题翻译字段

### ISSUE THREAD

**Issue by cesaryuan** [windingwind/zotero-pdf-translate#476]
**Describe the bug**

当在信息面板编辑条目的任意一个元数据时，第一次编辑正常，第二次及以后的点击会使得编辑框焦点会自动跳转到标题翻译，并伴随有[其他]字段不断出现titleTranslation:的现象。

**To Reproduce**
1. 点开任意条目的信息面板
2. 点击任意字段进行编辑
3. 编辑后点击其他任意字段的编辑框
4. Bug出现

**Expected behavior**
可正常编辑元数据

**Screenshots**

https://github.com/windingwind/zotero-pdf-translate/assets/35998162/217e884b-b6be-41cf-b6cf-6ca7069ab971

**Environment**
 - OS: Windows
 - Zotero Version 6.0.26
 - Addon Version 1.0.22

测试环境中只有PDF Translate一个插件
![image](https://github.com/windingwind/zotero-pdf-translate/assets/35998162/6ff00c08-3104-43a7-8874-70217a0361a9)

**Comment by shao12781566** [comment]
经常性出现在文献库界面插件不工作的情况，“切换原标题和翻译”功能无法使用

**Comment by yfdyh000** [comment]
Duplicate of #430.
