### ISSUE TITLE
之前文档的批注翻译不显示了

### ISSUE THREAD

**Issue by ihahya** [windingwind/zotero-pdf-translate#477]
您好，现在使用的是zotero6，之前看文献做批注时的自动翻译 大部分都无法显示了；但现在进行批注仍能正常翻译。如图：
<img width="952" alt="8f88b44d9b82067285634f7e5a3300a" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/a8431c0f-d730-45e0-9cde-18067aaf9ec0">

**Comment by windingwind** [comment]
如果翻译服务不可用，批注翻译结果将不正确。以前的翻译出问题我也没法解决

**Comment by ihahya** [comment]
好的谢谢回复
