### ISSUE TITLE
The configuration interface of the Zotero 7 beta version translation plugin is not visible.

### ISSUE THREAD

**Issue by muranhuli** [windingwind/zotero-pdf-translate#478]
**Describe the bug**
The configuration interface of the Zotero 7 beta version translation plugin is not visible and appears as a blank screen.

**To Reproduce**
1. Install Zotero 7 beta version.
2. Access the configuration interface of the translation plugin.
3. Unable to see the specific configuration interface of the translation plugin; it appears as a blank screen.

**Expected behavior**
I hope to be able to see the configuration interface of the translation plugin.

**Screenshots**
<img width="800" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/38523623/d05a0223-a6c9-4637-8964-1ce6bf0e3573">

**Environment**
 - OS: MacBook Pro M1 13.2.1 (22D68)
 - Zotero Version: Zotero 7 beta
 - Addon Version: 1.0.22

**Additional context**
The configuration interface of the Zotero 7 beta version translation plugin is not visible and appears as a blank screen.

**Comment by Tyqfat** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/100210376/b1bcdd5a-5e51-4404-8919-7d38120c96e2)


> **Describe the bug** The configuration interface of the Zotero 7 beta version translation plugin is not visible and appears as a blank screen.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install Zotero 7 beta version.
> 2. Access the configuration interface of the translation plugin.
> 3. Unable to see the specific configuration interface of the translation plugin; it appears as a blank screen.
> 
> **Expected behavior** I hope to be able to see the configuration interface of the translation plugin.
> 
> **Screenshots** <img alt="image" width="800" src="https://user-images.githubusercontent.com/38523623/246097974-d05a0223-a6c9-4637-8964-1ce6bf0e3573.png">
> 
> **Environment**
> 
> * OS: MacBook Pro M1 13.2.1 (22D68)
> * Zotero Version: Zotero 7 beta
> * Addon Version: 1.0.22
> 
> **Additional context** The configuration interface of the Zotero 7 beta version translation plugin is not visible and appears as a blank screen.

I also encountered the same problem, and the configuration interface of all the plugins was not visible, showing a blank screen.
![image](https://github.com/windingwind/zotero-pdf-translate/assets/100210376/0174b5ff-735e-49ee-a073-c153b9b04b9e)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate/releases/tag/v1.1.0-0

**Comment by muranhuli** [comment]
> https://github.com/windingwind/zotero-pdf-translate/releases/tag/v1.1.0-0

Thank you, the issue has been successfully resolved.
