### ISSUE TITLE
[Bug] Stand-alone window on top doesn't work for macOS

### ISSUE THREAD

**Issue by easypickings** [windingwind/zotero-pdf-translate#479]
**Describe the bug**

**To Reproduce**
1. Open translate sidebar and click 'open stand-alone window'
2. Toggle always on top
3. Click somewhere else

**Expected behavior**
The stand-alone window should be on top of the screen

**Environment**
 - OS: macOS
 - Zotero Version: 6.0.26
 - Addon Version: 1.0.22

**Comment by windingwind** [comment]
Sorry, this is a platform issue. I cannot solve it.
