### ISSUE TITLE
[Bug] 谷歌翻译的目标语言不对

### ISSUE THREAD

**Issue by yanyu2015** [windingwind/zotero-pdf-translate#48]
1 当使用google翻译的时候，选择英文，得到的还是英文
2 希望能够缩放翻译结果窗口的字体，或者支持调节

**Comment by yanyu2015** [comment]
感谢！！！
1 刚装完重启2次时，发现这窗口没有顺利加载
![image](https://user-images.githubusercontent.com/11142054/160502925-6d57b464-9474-4b9b-be87-e5305c3d171f.png)
现在设置目标语言后可以了
2 字体已经成功设置，建议说明在preference中，一开始在菜单中没找到，不然我还以为要改参数
3 部分时候会出现这样的现象，选中文本，PDF中已经出现小窗的翻译结果，而右侧面板中的翻译结果没有显示。
4 最后请教下，由于PDF划词翻译通常因为在换行出会有断行，感觉这个会影响翻译效果，请问这种情况是翻译引擎会自动处理嘛？如果没有，开发者是否会考虑优化呢？

**Comment by windingwind** [comment]
谢谢，
字体设置说明在readme，设置里面也有提示文字，我认为没必要再做多余说明。
换行符一直以来都是替换空格的
