### ISSUE TITLE
添加插件后无法翻译

### ISSUE THREAD

**Issue by duanbobaba** [windingwind/zotero-pdf-translate#480]
添加后显示“此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： CNKI

Error: HTTP GET https://dict.cnki.net/fyzs-front-api/getToken failed with status code 404”

请问如何解决？

**Comment by windingwind** [comment]
#6
