### ISSUE TITLE
百度，小牛和deepl(pro)翻译引擎输入密钥后还是不可用

### ISSUE THREAD

**Issue by jiaxuan-711** [windingwind/zotero-pdf-translate#484]
申请了百度，小牛和deepl(pro)de API密钥并在zotero中填入，但是在翻译时均显示翻译错误，已经确定密钥输入正确，在其翻译网站上均可以正常使用，有余量。免费翻译引擎可以正常使用，下载的xpi版本为最新版1.0.23.具体如下：
1.百度：
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 百度🗝️

Service error: 52003:UNAUTHORIZED USER

2.小牛：
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 小牛🗝️

Zotero Error: api.niutrans.com uses an invalid security certificate.

The certificate expired on 2023年4月24日 4:26. The current time is 2023年6月29日 0:49.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

3.deepl(pro)
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： DeepL(Pro订阅)🗝️

Error: HTTP POST https://api.deepl.com/v2/translate failed with status code 403

感谢解答!

**Comment by windingwind** [comment]
#6
