### ISSUE TITLE
[Bug]在Zotero 7中不显示翻译服务设置界面

### ISSUE THREAD

**Issue by Tsi-Min** [windingwind/zotero-pdf-translate#491]
插件在Zotero 7中不显示翻译服务设置界面，无法切换翻译引擎

Zotero>Preferences>Translate 显示空白

![image](https://github.com/windingwind/zotero-pdf-translate/assets/136872201/cc521140-b1e2-4a28-997f-d55b16854c1d)

 - OS: macOS 12.1
 - Zotero Version：7.0.0-beta.13+2277c7389
 - Addon Version：1.0.23

已分别重装软件与插件多次，问题仍然存在。请求debug, 非常感谢！

**Comment by windingwind** [comment]
Please use the latest beta if you are on Z7

**Comment by Tsi-Min** [comment]
it's already the latest version addon I am using.

**Comment by windingwind** [comment]
The BETA version, also known as pre-release.

**Comment by Tsi-Min** [comment]
my fault, it's fixed, thank you!
