### ISSUE TITLE
[Bug]自动翻译选择内容失效

### ISSUE THREAD

**Issue by ZHAOCAHOYUE** [windingwind/zotero-pdf-translate#492]
**Describe the bug**
7月10号更新后，设置中自动翻译选择内容和自动翻译批注失效了

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows/macOS/Linux
 - Zotero Version(Help->About Zotero)
 - Addon Version(Tools->Add-ons)

**Additional context**

**Comment by windingwind** [comment]
#6
