### ISSUE TITLE
去掉CNKI翻译结尾的广告

### ISSUE THREAD

**Issue by frostime** [windingwind/zotero-pdf-translate#494]
> 这个 issue 已经提交了相关的 PR  #496，请作者查收

## Is your feature request related to a problem? Please describe.

- **问题**：在使用 CNKI 引擎翻译的时候，会自动附上一个后缀广告

    ![image](https://github.com/windingwind/zotero-pdf-translate/assets/27268127/3dea80ca-9db9-4312-9d85-816908eefa49)

    >  (查看名企职位领高薪offer！--->智联招聘https://dict.cnki.net/ad.html)

- **希望**：希望可以去除这个固定的广告，让翻译结果变得更加干净

## Describe the solution you'd like

在 cnki.ts 的中，增加一个固定模板的替换，去掉尾部的字符串常量

![image](https://github.com/windingwind/zotero-pdf-translate/assets/27268127/b94662e7-0f7f-4755-96d5-b4c3939ab61b)

```ts
tgt = tgt.replace('(查看名企职位领高薪offer！--->智联招聘https://dict.cnki.net/ad.html)', '');
```

目前我在 1.0.23 基础上更改了以上的代码，编译后的插件已经能去掉广告了。

![image](https://github.com/windingwind/zotero-pdf-translate/assets/27268127/16a326ac-5334-4aa8-8595-780fa5120801)

![image](https://github.com/windingwind/zotero-pdf-translate/assets/27268127/abcfb37a-bf54-48ee-aaaa-bca0624dd365)

## Describe alternatives you've considered

No, the aforementioned solution is the optimal.

## Additional context

No.

**Comment by CharlesKeeling65** [comment]
你好，这个修改了源码之后如何编译成.xpi插件呀

**Comment by frostime** [comment]
> 你好，这个修改了源码之后如何编译成.xpi插件呀

- 下载下来
- pnpm install
- 修改代码
- pnpm run build-prod

**Comment by frostime** [comment]
> 能具体说明一下怎么进行的修改吗？目前还是zotero6版本，或者能否分享一下修改后的cnki.ts文件

https://github.com/windingwind/zotero-pdf-translate/pull/496

就增加了一行代码

**Comment by frostime** [comment]
> > 你好，这个修改了源码之后如何编译成.xpi插件呀
> 
> * git clone
> * pnpm install
> * 修改代码
> * pnpm run build-prod
> 
> 在 build 目录下的 xpi 文件就是。
> 
> 不过需要注意的是，不能直接在 main 分支上修改。而是要 checkout 到最近的一次 [v1.0.23](https://github.com/windingwind/zotero-pdf-translate/tree/v1.0.23) 版本上再更改代码并手动编译，否则编译出来的 xpi 无法被 zotero6 识别。

**Comment by shao12781566** [comment]
> > 能具体说明一下怎么进行的修改吗？目前还是zotero6版本，或者能否分享一下修改后的cnki.ts文件
> 
> https://github.com/windingwind/zotero-pdf-translate/pull/496/files
> 
> 就增加了一行代码
> 
> > > 你好，这个修改了源码之后如何编译成.xpi插件呀
> > 
> > 
> > 
> > * git clone
> > * pnpm install
> > * 修改代码
> > * pnpm run build-prod
> > 
> > 在 build 目录下的 xpi 文件就是。
> > 不过需要注意的是，不能直接在 main 分支上修改。而是要 checkout 到最近的一次 [v1.0.23](https://github.com/windingwind/zotero-pdf-translate/tree/v1.0.23) 版本上再更改代码并手动编译，否则编译出来的 xpi 无法被 zotero6 识别。



> * pnpm install

因为是个程序小白，所以能否略微详细的说明一下具体的修改步骤，谢谢！

**Comment by windingwind** [comment]
感谢@frostime。

**Comment by frostime** [comment]
> > > 能具体说明一下怎么进行的修改吗？目前还是zotero6版本，或者能否分享一下修改后的cnki.ts文件
> > 
> > 
> > https://github.com/windingwind/zotero-pdf-translate/pull/496/files
> > 就增加了一行代码
> > > > 你好，这个修改了源码之后如何编译成.xpi插件呀
> > > 
> > > 
> > > 
> > > * git clone
> > > * pnpm install
> > > * 修改代码
> > > * pnpm run build-prod
> > > 
> > > 在 build 目录下的 xpi 文件就是。
> > > 不过需要注意的是，不能直接在 main 分支上修改。而是要 checkout 到最近的一次 [v1.0.23](https://github.com/windingwind/zotero-pdf-translate/tree/v1.0.23) 版本上再更改代码并手动编译，否则编译出来的 xpi 无法被 zotero6 识别。
> 
> > * pnpm install
> 
> 因为是个程序小白，所以能否略微详细的说明一下具体的修改步骤，谢谢！

程序小白就不用太关心这个改代码了，这玩意还需搭建前端环境，如果不是开发者的话其实挺麻烦的。
作者已经 PR 了我的更改，并且刚刚发版了，更新一下插件就行了。

**Comment by RTcui** [comment]
> > 你好，这个修改了源码之后如何编译成.xpi插件呀
> 
> * git clone
> * pnpm install
> * 修改代码
> * pnpm run build-prod
> 
> 在 build 目录下的 xpi 文件就是。
> 
> 不过需要注意的是，不能直接在 main 分支上修改。而是要 checkout 到最近的一次 [v1.0.23](https://github.com/windingwind/zotero-pdf-translate/tree/v1.0.23) 版本上再更改代码并手动编译，否则编译出来的 xpi 无法被 zotero6 识别。

求助大神，同是程序小白。但由于个人需要，需要用之前的版本。想自己把这个广告去掉。
VScode pnpm 都安装了，git clone ,修改代码这些也没有问题。但有些问题和最后封装不明白。
 我的操作如下：
git clone 某个版本的代码
新建分支a，然后在此分支下修改代码；
把a并入main分支

问题：  1.以上操作步骤是否有问题；2.最后封装时在VScode 里面输入命令吗？

求大神指点迷津，是否可以有个简单的教程。   谢谢谢谢！！

**Comment by frostime** [comment]
> > > 你好，这个修改了源码之后如何编译成.xpi插件呀
> > 
> > 
> > 
> > * git clone
> > * pnpm install
> > * 修改代码
> > * pnpm run build-prod
> > 
> > 在 build 目录下的 xpi 文件就是。
> > 不过需要注意的是，不能直接在 main 分支上修改。而是要 checkout 到最近的一次 [v1.0.23](https://github.com/windingwind/zotero-pdf-translate/tree/v1.0.23) 版本上再更改代码并手动编译，否则编译出来的 xpi 无法被 zotero6 识别。
> 
> 求助大神，同是程序小白。但由于个人需要，需要用之前的版本。想自己把这个广告去掉。 VScode pnpm 都安装了，git clone ,修改代码这些也没有问题。但有些问题和最后封装不明白。 我的操作如下： git clone 某个版本的代码 新建分支a，然后在此分支下修改代码； 把a并入main分支
> 
> 问题： 1.以上操作步骤是否有问题；2.最后封装时在VScode 里面输入命令吗？
> 
> 求大神指点迷津，是否可以有个简单的教程。 谢谢谢谢！！

1. 不是直接新建分支，而是先要 checkout 到 v1.0.23 的 tag。main 分支的代码是兼容 zotero7 的，旧版的 zotero6 不一定能识别到。
2. 更改完了之后，直接打开 vscode 终端运行 pnpm run build-prod就行。运行完之后，在目录下会多出来一个编译目录，里面有个 xpi 文件，那个就是可以安装的插件文件。

**Comment by RTcui** [comment]
> > > > 你好，这个修改了源码之后如何编译成.xpi插件呀
> > > 
> > > 
> > > 
> > > * git clone
> > > * pnpm install
> > > * 修改代码
> > > * pnpm run build-prod
> > > 
> > > 在 build 目录下的 xpi 文件就是。
> > > 不过需要注意的是，不能直接在 main 分支上修改。而是要 checkout 到最近的一次 [v1.0.23](https://github.com/windingwind/zotero-pdf-translate/tree/v1.0.23) 版本上再更改代码并手动编译，否则编译出来的 xpi 无法被 zotero6 识别。
> > 
> > 
> > 求助大神，同是程序小白。但由于个人需要，需要用之前的版本。想自己把这个广告去掉。 VScode pnpm 都安装了，git clone ,修改代码这些也没有问题。但有些问题和最后封装不明白。 我的操作如下： git clone 某个版本的代码 新建分支a，然后在此分支下修改代码； 把a并入main分支
> > 问题： 1.以上操作步骤是否有问题；2.最后封装时在VScode 里面输入命令吗？
> > 求大神指点迷津，是否可以有个简单的教程。 谢谢谢谢！！
> 
> 1. 不是直接新建分支，而是先要 checkout 到 v1.0.23 的 tag。main 分支的代码是兼容 zotero7 的，旧版的 zotero6 不一定能识别到。
> 2. 更改完了之后，直接打开 vscode 终端运行 pnpm run build-prod就行。运行完之后，在目录下会多出来一个编译目录，里面有个 xpi 文件，那个就是可以安装的插件文件。

感谢大神的回复，废了九牛二虎之力，后来借助chatgpt的帮助，一步步的安装环境，我已经修改好了。再次感谢！！！
