### ISSUE TITLE
Google(CN) and Youdao Translate not working in v0.1.3

### ISSUE THREAD

**Issue by Lraxer** [windingwind/zotero-pdf-translate#5]
Hi, I downloaded and installed the latest version v0.1.3. I tried the translate engines that do not require secrets but only Niu Translate worked. I'm in China and Google Translate(CN) can't work.

![2022-03-21_11-11_1](https://user-images.githubusercontent.com/32860114/159201385-951053b6-5d2c-446f-8112-2b2bed4b7a1a.png)

Besides, Youdao Translate returned `[object Object]`.

![2022-03-21_11-11](https://user-images.githubusercontent.com/32860114/159201472-e4c2ffc5-0896-4bca-b143-7346ee7c0fa7.png)

Youdao Translate works fine in v0.1.2. Is there something wrong? My zotero version is 6.0.

**Comment by windingwind** [comment]
@Lraxer The new release v0.1.4 fixed Youdao error.

As for the Google(CN), it uses `google.cn` instead of `google.com`(which is banned in China mainland). However, if you cannot access https://translate.google.cn, the Google(CN) option will not work as well. There are no ensurance you can use Google(CN) in China mainland: depending on your network environment.

**Comment by Lraxer** [comment]
I can access [translate.google.cn](https://translate.google.cn/) directly but I can't use the API. For example, I can access https://translate.google.cn/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=google only via proxy. [Seems like some people have similar problems.](https://zhuanlan.zhihu.com/p/346484391)

Anyway, Youdao is enough for me. Thanks for your help!

**Comment by windingwind** [comment]
Thanks, I've noticed that. Seem like this API is anyway unavailable under China GWF.
I'd like recomand Niu trans to you, which out-performs Youdao and does not require secret key.

**Comment by windingwind** [comment]
@Lraxer I updated a new translate engine, Google(API): `translate.googleapis.com`
 I don't need VPN to access it.

**Comment by Lraxer** [comment]
> @Lraxer I updated a new translate engine, Google(API): `translate.googleapis.com` I don't need VPN to access it.

Great! The latest version works perfectly for me.
