### ISSUE TITLE
[Bug] cannot install plugin in Zotero 6.0.26

### ISSUE THREAD

**Issue by markkwanhz** [windingwind/zotero-pdf-translate#500]
**Describe the bug**
安装插件时显示 「无法安装插件"%S"。它可能无法与该版本的Zotero兼容」

**To Reproduce**
使用add-ons manager安装时会出现，插件版本是1.0.24，从release页面下载

**Environment**
 - OS: macOS, M2Pro
 - Zotero Version  6.0.26
 - Addon Version 1.0.24

**Comment by windingwind** [comment]
请不要下载预发布版本

**Comment by windingwind** [comment]
或尝试1.0.23
