### ISSUE TITLE
[Feature] 希望添加文字识别ocr功能

### ISSUE THREAD

**Issue by zhangdoudou** [windingwind/zotero-pdf-translate#501]
问题：
插件的划词翻译在大多数文档中已经非常好用了，但是有些pdf文档划词并不准确，容易划到很多句子，例如下面这种情况，我其实只想翻译下面那个段落，但是上面的内容会划到，我猜应该是pdf格式排版的问题。

![20230717125124]( https://raw.githubusercontent.com/zhangdoudou/imgs/main/Blogs/20230717125124.png)

解决方法：
如果翻译插件可以支持文字识别功能就好了，就是可以截图识别文字然后自动翻译。目前各大平台都是有免费的ocr使用api的，比如百度，或许可以添加这个接口，让用户使用。

**Comment by windingwind** [comment]
谢谢建议，但不会支持
