### ISSUE TITLE
[Feature]请取消或放宽单次翻译的单词最大1000词限制

### ISSUE THREAD

**Issue by shingler** [windingwind/zotero-pdf-translate#502]
你好，翻译功能很棒，为我节省了很多时间和精力。但是有的英文段落有些长，pdf-translate限制1000词的限制条件似乎有点严格，每次还得花时间去英文原文里找哪里被截断了。希望以后能取消文本长度限制或放宽限制的条件，比如2000词，谢谢。

**Comment by windingwind** [comment]
翻译服务限制，与插件无关。换个翻译服务即可

**Comment by RTcui** [comment]
@windingwind    是否可以事项，如果大于1000词，则自动分开提交服务器，最终返回所有文字的翻译呢。

**Comment by windingwind** [comment]
分开翻译没有上下文。不如自己多划一次

**Comment by RTcui** [comment]
谢谢回复~

**Comment by qiqicliff** [comment]
> 你好，翻译功能很棒，为我节省了很多时间和精力。但是有的英文段落有些长，pdf-translate限制1000词的限制条件似乎有点严格，每次还得花时间去英文原文里找哪里被截断了。希望以后能取消文本长度限制或放宽限制的条件，比如2000词，谢谢。

换个API就好了，打开Zotero,编辑->首选项->翻译插件，更换翻译服务
![image](https://github.com/windingwind/zotero-pdf-translate/assets/103885652/c1965ea7-11da-4b39-b848-d3f933ff9c58)
