### ISSUE TITLE
zotero 7设置里翻译的具体菜单设置消失了

### ISSUE THREAD

**Issue by jinshengcui** [windingwind/zotero-pdf-translate#505]
**Describe the bug**
zotero 7里设置中翻译的具体设置选项为空白

**To Reproduce**

1. 点击编辑
2. 点击设置
3. 翻译菜单未出现具体设置选项

**Expected behavior**
目的是设置具体的翻译api，但是目前翻译菜单下具体设置选项一片空白

**Screenshots**
![image](https://github.com/windingwind/zotero-pdf-translate/assets/33824346/67c4aa77-ab1d-4701-a2b1-cfa37f1f118d)

**Environment**

- Windows 11
- Zotero 7.0.0-beta.21+d968e8ec3(64-bit)
- 1.0.24

**Comment by windingwind** [comment]
zotero7请下载pre release
