### ISSUE TITLE
[Feature]GPT3.5翻译支持多个key，实现负载均衡

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-pdf-translate#508]
感谢开发者如此完美的作品。
**Is your feature request related to a problem? Please describe.**
翻译服务选择GPT3.5时容易触发限制，但是gpt3.5的翻译效果还是可以的，少了很多机器味，读起来很自然。
现在zotero style+zotero pdf translate 可以实现整个PDF翻译，这个功能很强大，但是很容易触发GPT的限制。
单独使用zotero pdf translate，如果阅读太快，应该也会触发GPT3.5的限制。

**Describe the solution you'd like**
zotero pdf translate 支持多个GPT3.5的key实现负载均衡，提高zotero style全文翻译的成功率
可以参考[沉浸式翻译的负载均衡方案](https://immersivetranslate.com/docs/services/openai/#:~:text=%E6%B2%89%E6%B5%B8%E5%BC%8F%E7%BF%BB%E8%AF%91%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%20API%20Key%20%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%2C%20%E8%AF%B7%E5%9C%A8%E5%A1%AB%E5%86%99%E7%9A%84%E6%97%B6%E5%80%99%E7%94%A8%E8%8B%B1%E6%96%87%E9%80%97%E5%8F%B7%20%2C%20%E5%88%86%E9%9A%94%E4%B8%8D%E5%90%8C%E7%9A%84%20key)

https://github.com/windingwind/zotero-pdf-translate/issues/460#issuecomment-1643417376

https://github.com/MuiseDestiny/zotero-style/issues/501#issuecomment-1646546358

**Comment by windingwind** [comment]
欢迎PR

**Comment by fredericky123** [comment]
请问可以负载均衡了吗
