### ISSUE TITLE
使用微软翻译api时翻译内容中有特殊字符会返回 400错误

### ISSUE THREAD

**Issue by No-108** [windingwind/zotero-pdf-translate#510]
版本：[Release 1.1.0-3](https://github.com/windingwind/zotero-pdf-translate/releases/tag/v1.1.0-3)
错误：[Request Error]\n\nEngine not available, invalid secret, or request too fast.\nUse another translation engine or post the issue here: \n https://github.com/windingwind/zotero-pdf-translate/issues \n\nThe message below is not Zotero or the PDF Translate addon, but from Microsoft🗝️

Error: HTTP POST https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=zh-CN failed with status code 400

经过简单测试，如待翻译的句子中存在中文引号（“”）或者希腊字母（公式）以及使用中文翻译为英文，则会出现以上错误。

**Comment by windingwind** [comment]
欢迎PR
