### ISSUE TITLE
[Bug]无法自动翻译

### ISSUE THREAD

**Issue by JaggerL** [windingwind/zotero-pdf-translate#514]
**Describe the bug**
选中PDF文字后不会自动翻译（已在首选项设置自动翻译选择内容和批注），手动点击翻译才会进行翻译。和https://github.com/windingwind/zotero-pdf-translate/issues/287中的问题一样。

**Expected behavior**
选中文字后会自动翻译

**Environment**

- OS: Windows 11
- Zotero Version 6.0.26（最新版）
- Addon Version 1.0.24（最新版）

**Comment by JaggerL** [comment]
Somehow the problem disappeared yesterday.

**Comment by foryond** [comment]
Ubuntu系统下，同样出现选中无法自动翻译的情况，点击translate按钮后成功翻译，谢谢！ 
- Zotero V6.0.30
- Zotero PDF Translate V1.0.23
![zoterotranslate003](https://github.com/windingwind/zotero-pdf-translate/assets/45784147/1ceca150-06e0-49a6-b7b8-9dfc0cd52b4c)
![zoterotranslate002](https://github.com/windingwind/zotero-pdf-translate/assets/45784147/44c31353-170f-4bdd-b497-eb77dbfd4cb9)
![zoterotranslate001](https://github.com/windingwind/zotero-pdf-translate/assets/45784147/5e6fbe63-2c9f-4fbd-8950-badcaab768fc)

**Comment by gs0908** [comment]
Describe the bug
选中PDF文字后不会自动翻译（已在首选项设置自动翻译选择内容和批注），手动点击翻译才会进行翻译。和[https://github.com/windingwind/zotero-pdf-translate/issues/514]的问题相同

Expected behavior
选中文字后会自动翻译

Environment

OS: Windows 11
Zotero Version 6.0.36（最新版）
Addon Version 1.0.27（最新版）

**Comment by gs0908** [comment]
Describe the bug
选中PDF文字后不会自动翻译（已在首选项设置自动翻译选择内容和批注），手动点击翻译才会进行翻译。和[](https://github.com/windingwind/zotero-pdf-translate/issues/514)中的问题相同

Expected behavior
选中文字后会自动翻译

Environment

OS: Windows 11
Zotero Version 6.0.36（最新版）
Addon Version 1.0.27（最新版）

**Comment by gs0908** [comment]
Describe the bug
选中PDF文字后不会自动翻译（已在首选项设置自动翻译选择内容和批注），手动点击翻译才会进行翻译。和[地址](https://github.com/windingwind/zotero-pdf-translate/issues/514)中的问题相同

Expected behavior
选中文字后会自动翻译

Environment

OS: Windows 11
Zotero Version 6.0.36（最新版）
Addon Version 1.0.27（最新版）

**Comment by gs0908** [comment]
Describe the bug
选中PDF文字后不会自动翻译（已在首选项设置自动翻译选择内容和批注），手动点击翻译才会进行翻译。和(https://github.com/windingwind/zotero-pdf-translate/issues/514)中的问题相同

Expected behavior
选中文字后会自动翻译

Environment

OS: Windows 11
Zotero Version 6.0.36（最新版）
Addon Version 1.0.27（最新版）
