### ISSUE TITLE
希望能够恢复对文献的标题翻译的可修改功能

### ISSUE THREAD

**Issue by jiuzhou1004** [windingwind/zotero-pdf-translate#515]
Describe the bug

之前经常利用插件对英文期刊标题进行翻译，并在阅读后以此栏信息为基础修改标记论文主要内容，现在最新版本1.0.25无法在翻译后的基础上进行修改，希望能够在下个版本恢复标题翻译内容可手动修改。十分感谢！

Screenshots

![image](https://github.com/windingwind/zotero-pdf-translate/assets/130376336/15e1ba8e-30e8-4039-9c95-361f3567bb25)

Environment

OS: macOS
Zotero Version：6.0.23
Addon Version：1.0.24

**Comment by windingwind** [comment]
在 其他 栏进行修改即可。
