### ISSUE TITLE
[Bug]翻译末尾仍然存在cnki的广告

### ISSUE THREAD

**Issue by Forever-Yf** [windingwind/zotero-pdf-translate#518]
**Describe the bug**
1.0.24版本插件在PDF里面划词翻译的时候末尾仍出现cnki的广告“智联........”
以下为截图
![image](https://github.com/windingwind/zotero-pdf-translate/assets/98394507/6e05d39a-4fa3-4abd-ba00-78bc8efd35eb)

**Environment**
Windows 10
Zotero 6
插件版本1.0.24

**Comment by yykphy** [comment]
更新到1.0.25版，也有同样的问题。
![error](https://github.com/windingwind/zotero-pdf-translate/assets/139735634/924085cb-127b-47d4-ba08-2e3e0343bd2f)

**Environment**
Windows 11
Zotero 6
插件版本1.0.25

**Comment by RTcui** [comment]
> 



> 更新到1.0.25版，也有同样的问题。 ![error](https://user-images.githubusercontent.com/139735634/257467243-924085cb-127b-47d4-ba08-2e3e0343bd2f.jpg)
> 
> **Environment** Windows 11 Zotero 6 插件版本1.0.25

自己修改代码即可，参考大神帖子  https://github.com/windingwind/zotero-pdf-translate/issues/494#issue-1795975159

p.s.感谢开发者及各网友前辈的辛苦付出！

**Comment by RTcui** [comment]
自己修改代码

**Comment by Forever-Yf** [comment]
> > 
> 
> > 更新到1.0.25版，也有同样的问题。![错误](https://user-images.githubusercontent.com/139735634/257467243-924085cb-127b-47d4-ba08-2e3e0343bd2f.jpg)
> > **环境**视窗 11 Zotero 6 插件版本1.0.25
> 
> 自己修改代码即可，参考大神帖子 [#494 （评论）](https://github.com/windingwind/zotero-pdf-translate/issues/494#issue-1795975159)
> 
> p.s.感谢开发者及各网友前辈的辛苦付出！

我看到1.0.24和1.0.25版本的源码cnki.js文件里面已经添加了该代码，但是仍未生效，请问您有解决办法吗？谢谢！

**Comment by RTcui** [comment]
> 

知网翻译助手8月2号开始好像正在调整，官网有工号，现在正常翻译都没有广告了。我看还出会员功能了，可以关注一下。欢迎交流~~
