### ISSUE TITLE
[Bug]更新到1.0.26之后无法正常启动，在插件中关闭开启后设置界面异常

### ISSUE THREAD

**Issue by z0ow** [windingwind/zotero-pdf-translate#524]
**Before Issue/提问之前**

1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题。如果不详细说明通过什么步骤可以复现问题，具体表现是什么，你正在使用哪个版本的插件，我没办法帮到你。不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Describe the bug**
如题，昨天还用着好好的。

**To Reproduce**

1. 更新到1.0.26，无法正常工作
2. 在软件内禁用、开启后，设置界面出现如下情况
![image](https://github.com/windingwind/zotero-pdf-translate/assets/20352723/1c002fbd-29ea-4f4c-8488-61df40f6ea78)
3. 卸载1.0.26，回滚到1.0.25，一切正常

**Expected behavior**
如题，此次更应不应导致无法使用问题。

**Screenshots**

**Environment**

- OS: **Windows** /macOS/Linux
- Zotero Version(Help->About Zotero) **6.0.26**
- Addon Version(Tools->Add-ons) **1.0.26**

**Additional context**

**Comment by mengchaoheng** [comment]
the same problem. sovled it by install 1.0.25

**Comment by Joym07** [comment]
install 1.0.25

**Comment by zxs2109** [comment]
感谢感谢，已解决，安装1.0.25即可正常使用。忙活了一个多小时，把各种解决办法都试了个遍。

**Comment by deardeer7** [comment]
+1，突然不能用了，翻译功能栏直接没有了，但是看插件是启用状态

**Comment by sakaili** [comment]
同样的问题，翻译栏没有了，禁用再启用也无效。

**Comment by sakaili** [comment]
同样的问题，翻译栏直接没有了，禁用再启用也无效。
这是v1.0.25版本的链接：https://github.com/windingwind/zotero-pdf-translate/releases/tag/v1.0.25

**Comment by MrKeanu-V** [comment]
same bro, I think it`s a problem with zotero, but finally I find it`s something en`t right by the new version. It will be sovled by installing the previous version.

**Comment by windingwind** [comment]
已经删除1.0.26。因为相关依赖的原因，不再对z6版本进行维护。

**Comment by z0ow** [comment]
@windingwind 明白，万分感谢解答疑问和修正更新！😄
