### ISSUE TITLE
[Bug] 突然插件失效了，移除重新安装后首选项里不显示插件了。

### ISSUE THREAD

**Issue by QiuLiangcai** [windingwind/zotero-pdf-translate#525]
之前用的是老版本的，突然插件失效了，右侧边栏里没有了翻译的界面（以前也出现过，但是过一会他自己就好了，但这次重启了也不行），选文本时弹窗里也不显示所选取的文本了。移除重新安装后，插件里显示已经显示插件了，但是首选项里不显示插件。这个是怎么回事呢

**Comment by mxa4646** [comment]
同样的问题，昨天还好，今天突然失效，看到更新日期是今天

**Comment by windingwind** [comment]
重新安装1.0.25
