### ISSUE TITLE
[Bug]110-5 没有设置界面

### ISSUE THREAD

**Issue by jlu511** [windingwind/zotero-pdf-translate#526]
**Describe the bug**
更新110-5之后，翻译插件设置界面没有，pdf阅读界面也没有翻译的功能部分。禁用其他插件之后，只启用翻译插件，设置界面与翻译界面均正常。一旦启用其他插件，则界面消失

**To Reproduce**

**Expected behavior**
![image](https://github.com/windingwind/zotero-pdf-translate/assets/64378673/5abf793d-3bcf-4b5f-9d2e-db56e5c9761d)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/64378673/87dcfdb0-7ae9-46c7-a77e-c8e7fa00439a)

**Screenshots**
其他插件，只要打开任意一个，均出现上述bug，我已经一一尝试过。

**Environment**

- OS: Windows 10
- Zotero Version 7 beta 26
- Addon Version 110-5

**Additional context**
no

**Comment by EasyD0** [comment]
同样有此问题

**Comment by Stevetich** [comment]
似乎确实最新版本有问题

**Comment by windingwind** [comment]
1.1.0-6是否解决了？
是上游依赖仓库的问题

**Comment by thetaaaaa** [comment]
1.0.26同样有此问题，zotero版本为zotero 6.

**Comment by windingwind** [comment]
1.0.26已经从发布列表删除。重新下载安装1.0.25即可。后续不再维护z6的插件版本

**Comment by jlu511** [comment]
> 1.1.0-6是否解决了？ 是上游依赖仓库的问题

谢谢更新，110-6已经解决了
