### ISSUE TITLE
[Feature] 增加弹出框显示位置设置

### ISSUE THREAD

**Issue by wwjCMP** [windingwind/zotero-pdf-translate#528]
**Is your feature request related to a problem? Please describe.**
现在在鼠标选择的文字下方，会出现弹出框被遮挡情况。

**Describe the solution you'd like**
希望可以提供设置显示在选择文字的左右两侧，或者在选择文字的上方，弹出框可以覆盖或者部分覆盖原文以实现合适的显示位置，因为有时候通过翻译内容快速阅读的时候不一定需要对照原文来看。

**Comment by windingwind** [comment]
可以通过右侧栏查看
