### ISSUE TITLE
[Bug] Can't translate when language of Zotero is English 

### ISSUE THREAD

**Issue by pencilheart** [windingwind/zotero-pdf-translate#531]
**Describe the bug**

Due to some reason, language of Zotero needs to be English. But once I do this, the plug-in displays normally and the words can be recognized, but cannot be translated (including automatic translation and cmd+T). When Zotero is set to Chinese and all functions are normal.

**To Reproduce**

1. Go to 'Setting->Language: English'
2. Open one item;
3. Select any text;
4. No any translation result.

**Screenshots**
![Xnip2023-08-08_09-29-07](https://github.com/windingwind/zotero-pdf-translate/assets/61617063/2beeb580-c6ef-4733-8042-3ad41f7b7dc8)

**Expected behavior**

Expect this plugin to work when Zotero is set to English.

**Environment**

- OS: macOS 13.5 (22G74)
- Zotero Version: 7.0.0-beta.28+3a43a98f1
- Addon Version: 1.1.0-6

**Comment by muranhuli** [comment]
I also encountered the same problem

**Comment by windingwind** [comment]
fixed in 1.1.0-8
