### ISSUE TITLE
[Feature]是否会加入欧路词典默认翻译接口

### ISSUE THREAD

**Issue by code-thx** [windingwind/zotero-pdf-translate#534]
1.准确度高：欧路词典的默认翻译，翻译精准度总体来说很不错，相信很多人在接触zotero之前都用过欧路的默认翻译。
2.免费，不用科学上网，没有字数限制；

但是不知道欧路的默认翻译引擎具体用的是哪个引擎。

![image](https://github.com/windingwind/zotero-pdf-translate/assets/103620369/f4c7902f-65af-493f-ac03-ae13f27e9a74)

**Comment by windingwind** [comment]
welcome pr

**Comment by RTcui** [comment]
> welcome pr

对编程一窍不通😭😭还望各路大神无私奉献🤝🫶

**Comment by sasaju** [comment]
好像欧路词典没有开放翻译相关的API？我没有找到

**Comment by SouthToSouth** [comment]
楼主，目前这是不可能的。
https://my.eudic.net/OpenAPI/Doc_Index#-api-doc
看这里吧，就只有三种api 
1. 语音打分
2. 单词本操作
3. 多语言识别

**Comment by windingwind** [comment]
谢谢补充。此处关闭

**Comment by pengxy0** [comment]
> 楼主，目前这是不可能的。 https://my.eudic.net/OpenAPI/Doc_Index#-api-doc 看这里吧，就只有三种api
> 
> 1. 语音打分
> 2. 单词本操作
> 3. 多语言识别
> 
> 总之没有翻译引擎的api。没有api也就没办法集成。

可以将单词添加到单词本，Zotero one实现了这个功能，要是Zotero PDF也可以就好了，期待大神！
