### ISSUE TITLE
[Feature]如何设置才能在将翻译内容自动添加到标注时取消前后两个'abc'按钮？

### ISSUE THREAD

**Issue by colin4k** [windingwind/zotero-pdf-translate#535]
**Is your feature request related to a problem? Please describe.**
翻译内容自动添加到标注后，内容前后都有'abc'按钮

**Describe the solution you'd like**
因为我利用插件自动同步标注到Obsidian笔记，这两个'abc'按钮很影响美观，希望能够有一个地方可以设置取消这两个按钮

**Comment by windingwind** [comment]
see readme
