### ISSUE TITLE
[Bug]在zotero的界面语言为英文时，zotero-pdf-translate插件不工作

### ISSUE THREAD

**Issue by aaronkhq** [windingwind/zotero-pdf-translate#536]
插件版本：v1.1.0-7
电脑：macos M1 Ventura 13.0.1 (22A400)
zotero：7.0.0-beta.32

作者好，刚发现：在zotero的界面语言为英文时，zotero-pdf-translate插件不工作。

**Comment by Dorence** [comment]
addon version: v1.0.0-7
zotero version: 7.0.0-beta.33

My interface language is English, the error console shows:

```
Error: Localized string not available for pdfReader-addToNote intl.js:137:15
```

which not occuring when language is set to Chinese.

**Comment by pencilheart** [comment]
#531

**Comment by windingwind** [comment]
fixed in 1.1.0-8
