### ISSUE TITLE
增加翻译标题和翻译摘要的修改

### ISSUE THREAD

**Issue by vagitablebirdcode** [windingwind/zotero-pdf-translate#538]
目前在使用1.0.25的版本，可是我无法编辑翻译后的标题。希望之后可以添加“翻译标题”条目的编辑功能，感谢开发者！

**Comment by LIZSK** [comment]
你好，同样的问题，请问解决了吗？

**Comment by LIZSK** [comment]
我记得以前是可以编辑的，最近不可以了

**Comment by northword** [comment]
![图片](https://github.com/windingwind/zotero-pdf-translate/assets/44738481/f72b3357-de06-4891-81fb-1ff1a59a3e9e)

在额外字段修改

**Comment by vagitablebirdcode** [comment]
> ![图片](https://user-images.githubusercontent.com/44738481/263643294-f72b3357-de06-4891-81fb-1ff1a59a3e9e.png)
> 
> 在额外字段修改

额外的字段是“其他”字段，translate插件不仅会生成自有条目，为了向下兼容，还会在其他条目中加入同样的信息。但是这么多信息归类为一个条目，显然不能与单一生成的条目比。

**Comment by northword** [comment]
> translate插件不仅会生成自有条目

没看太明白，插件不会生成条目。如果你说的是字段——插件始终将译文存储在“其他字段”，原始标题下现实的、文献仓库列表里显示的列，数据均从“其他”字段读取。

**Comment by vagitablebirdcode** [comment]
> > translate插件不仅会生成自有条目
> 
> 没看太明白，插件不会生成条目。如果你说的是字段——插件始终将译文存储在“其他字段”，原始标题下现实的、文献仓库列表里显示的列，数据均从“其他”字段读取。

会的，请看我下方的截图，“标题翻译”与“摘要翻译”都是插件生成的自有条目，在导出时不会跟最bib文件一起导出。如果没有，您可以更新到新的版本。旧版本默认全部生成在“其他”条目中，优点是可以兼容zotero，缺点是作为一个条目，在导出时也会跟最导出，污染导出条目。我的建议是，可以在这些自有条目中进行编辑，而该功能之前我记得是可以的。
![图片](https://github.com/windingwind/zotero-pdf-translate/assets/42081162/e06ae3e6-1118-4f49-af7d-d9e387f01cff)

**Comment by northword** [comment]
这两个所谓的自有条目，其数据来源就是“其他”字段。

**Comment by vagitablebirdcode** [comment]
> 这两个所谓的自有条目，其数据来源就是“其他”字段。

您的意思是，只要我修改“其他”字段中的信息，那么在这些条目中也会自动修改对嘛？

**Comment by northword** [comment]
> > 这两个所谓的自有条目，其数据来源就是“其他”字段。
> 
> 您的意思是，只要我修改“其他”字段中的信息，那么在这些条目中也会自动修改对嘛？

是的。

**Comment by vagitablebirdcode** [comment]
> 这两个所谓的自有条目，其数据来源就是“其他

> > > 这两个所谓的自有条目，其数据来源就是“其他”字段。
> > 
> > 
> > 您的意思是，只要我修改“其他”字段中的信息，那么在这些条目中也会自动修改对嘛？
> 
> 是的。

按照你的做法，确实修改成功了，非常感谢！不过，还是希望可以直接在显式的字段中进行修改，这更符合直觉一些。不过鉴于该问题已经解决，我会关闭该issue。

**Comment by vagitablebirdcode** [comment]
> 你好，同样的问题，请问解决了吗？

该问题已经解决，请查看下方的对话，或可以直接[跳转](https://github.com/windingwind/zotero-pdf-translate/issues/538#issuecomment-1695275485)该链接到达重要位置。

**Comment by RTcui** [comment]
> > 这两个所谓的自有条目，其数据来源就是“其他
> 
> > > > 这两个所谓的自有条目，其数据来源就是“其他”字段。
> > > 
> > > 
> > > 您的意思是，只要我修改“其他”字段中的信息，那么在这些条目中也会自动修改对嘛？
> > 
> > 
> > 是的。
> 
> 按照你的做法，确实修改成功了，非常感谢！不过，还是希望可以直接在显式的字段中进行修改，这更符合直觉一些。不过鉴于该问题已经解决，我会关闭该issue。

可以用之前没更改版本的插件，比如我用的是v0.9.8，翻译标题在短标题里面，而且这样比较方便笔记模板调用。
zotero7软件包括插件，有很多新功能，但是也总会出现bug，时不时会因为软件的问题影响学习的进度。我的应对方法是：自己用z6稳定版和之前用的比较稳定的插件。   在自己电脑用hyper-v开个虚拟机，体验最新版zotero和新版插件的功能，两个软件登陆同一个账号，这样数据互相同步。

**Comment by RTcui** [comment]
> 不建议使用将数据存储在短标题的版本，会影响部分应用样式。可以通过`topItem.getField("titleTranslation")`获取目前的翻译结果，和短标题是一样的用法，只是键不同

感谢大佬回复，不多对于小白来说，不太懂你的意思。。    感谢你为zotero功能开发做出的巨大奉献。
