### ISSUE TITLE
大佬可不可以把翻译的框放在原文框的上面 第一时间想看到的是翻译[Feature]

### ISSUE THREAD

**Issue by Syzygy33** [windingwind/zotero-pdf-translate#54]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  
3. Remember to delete this section before submit.   

**Issues not in the template format will be ignored/不按模板格式的提问将不会被回复**

Edit the template below/编辑以下模版

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
new settings added in v0.3.15
