### ISSUE TITLE
zotero7中，弹窗大小随鼠标点击变化

### ISSUE THREAD

**Issue by pengershuai** [windingwind/zotero-pdf-translate#541]
**Is your feature request related to a problem? Please describe.**
在使用翻译的时候会不由自主的点击弹窗中的文字，但是新版本鼠标点击后弹窗会自动变化，导致排版变来变去，不是很适应，也没办法聚焦到选中的文字上。

**Describe the solution you'd like**
希望能够给出一个明确的选项，让用户自主选择要不要让弹窗随鼠标点击变化。

**Describe alternatives you've considered**
额外的希望能够增加选项，设置弹窗中字体的粗细。

**Additional context**

**Comment by xihuai18** [comment]
你是怎么在zotero7装上的请问？我这边说版本不match

**Comment by pengershuai** [comment]
> 你是怎么在zotero7装上的请问？我这边说版本不match

release界面选择pre-release版本的
![image](https://github.com/windingwind/zotero-pdf-translate/assets/56161897/a55c9b6e-ffae-41b6-a6b1-12ee796dd427)

**Comment by xihuai18** [comment]
> > 你是怎么在zotero7装上的请问？我这边说版本不match
> 
> release界面选择pre-release版本的 ![image](https://user-images.githubusercontent.com/56161897/260762243-a55c9b6e-ffae-41b6-a6b1-12ee796dd427.png)

找到了，感谢

**Comment by QuantumRoseinAmethystVase** [comment]
Same

**Comment by Anphetamine** [comment]
same

**Comment by zhimaerfan** [comment]
Same. And clicking the "Add Note" button doesn't work, a similar bug was fixed before, it happened on M2 macbook air OS 13.4.
同样点击会变化框的大小。并且点击“添加笔记”按钮无效，之前修复过类似bug，它发生在M2 macbook air OS 13.4上 。
