### ISSUE TITLE
[Bug]zotero7 version 1.1.0-8 无法识别selection的内容

### ISSUE THREAD

**Issue by shenwan0524** [windingwind/zotero-pdf-translate#543]
**Describe the bug**
您好，我正在使用zotero7 version 1.1.0-8，但安装并配置好后我发现选中部分的内容无法识别

**Screenshots**
<img width="1576" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/66790176/07bd14fe-5e53-4302-999a-dd17fe4c1268">

**Environment**

- OS: macOS
- Zotero Version：zotero 7
- Addon Version: 1.1.0-8

**Comment by windingwind** [comment]
更新插件

**Comment by windingwind** [comment]
更新插件后重启zotero。如果还有问题见#6 提供调试输出

**Comment by shenwan0524** [comment]
谢谢！应该不是插件的bug，查看了#6，我想是PDF reader的问题，更新了zotero，现在可以识别了。
