### ISSUE TITLE
[Bug]Zotero7 beta36 中 translate 插件[1.1.0-9]无法自动翻译批注

### ISSUE THREAD

**Issue by BillionReyz** [windingwind/zotero-pdf-translate#547]
**Describe the bug**
Zotero7 beta36 中 translate 插件[1.1.0-9]无法自动翻译批注
下面的截图是其他已安装插件，已经尝试仅保留 translate 插件开启但依然无法自动将高亮的批注翻译在批注评论里。
**Screenshots**
<img width="704" alt="截屏2023-08-20 10 38 43" src="https://github.com/windingwind/zotero-pdf-translate/assets/59037759/d0b6f89d-6ad3-4abf-8dd6-5705392d130e">

**Environment**

- OS: macOS
- Zotero Version(7.0.0-beta36)
- Addon Version(1.1.0-9)

**Comment by windingwind** [comment]
#6
