### ISSUE TITLE
Zotero翻译所有的注释内容，导致注释添加为笔记的时候，英文没有了，全部是中文

### ISSUE THREAD

**Issue by Vivian4849** [windingwind/zotero-pdf-translate#549]
**Describe the bug**
Zotero翻译所有的注释内容，导致注释添加为笔记的时候，英文没有了，全部是中文
**To Reproduce**

1. 选择文本，添加高亮注释
2. 点击添加到笔记
3. 显示的都是中文翻译

**Expected behavior**
添加笔记以后显示英文原文和中文翻译

**Screenshots**

![image](https://github.com/windingwind/zotero-pdf-translate/assets/142001583/cf82618c-d38b-4971-92f9-c26aa6e933ea)

**Environment**

- OS: Windows
- Zotero Version(6.0.26)
- Addon Version(1.0.25)

**Additional context**

**Comment by windingwind** [comment]
请检查设置中选择翻译批注的位置

**Comment by Vivian4849** [comment]
> 请检查设置中选择翻译批注的位置

已恢复正常
