### ISSUE TITLE
[Feature] Do not auto generate a (annotation) note when highlighting words

### ISSUE THREAD

**Issue by dragonyanglong** [windingwind/zotero-pdf-translate#55]
@windingwind , Thanks so much for your fantastic tool for the zetero, and I really like it. If possible, could you please help with the following feature request, which makes me a bit frustrated since I am a heavy user for the highlighting function in zotero. I appreciate it!

**Is your feature request related to a problem? Please describe.**
When I highlight some words using colors, it will automatically generate notes, is it ok to disable this auto-function?

**Describe the solution you'd like**
I hope we could keep the feature that when we select some words, it auto show the translated words in a pop-up window. But when we highlight the words with colored pens, don't generate notes for them. 

**Describe alternatives you've considered**
If the auto pop-up window has strong correlation with the auto note generation when highlighting, is it ok to provide a button to disable the whole auto pop-up window. I could just use the the "translate" panel on the right hand side to manually translate it. On the bottom line, I don't want this add-on to affect any functions of the original highlighting.

**Additional context**
No.

**Comment by windingwind** [comment]
Thanks for your like!

This featrue already exists. You can find it in edit->preferences, uncheck the translate annotations.

**Comment by windingwind** [comment]
Hi,
I'll close this issue. Feel free to open it agian~
