### ISSUE TITLE
能重置为默认的prompt吗？

### ISSUE THREAD

**Issue by fredericky123** [windingwind/zotero-pdf-translate#553]
不知道最新版prompt更新了哪里，自定义的prompt导致不出来，老是输出英文了
能重置默认的prompt吗
卸载后重装，配置信息还是在，导致prompt还是自定义的

**Comment by windingwind** [comment]
menu Edit - Preferences - Advanced - Config Editor - extensions.zotero.ZoteroPDFTranslate.gptPrompt

**Comment by fredericky123** [comment]
> menu Edit - Preferences - Advanced - Config Editor - extensions.zotero.ZoteroPDFTranslate.gptPrompt

这里已经变成了自定义的空白prompt
想知道原始prompt是什么，需要改回去

**Comment by windingwind** [comment]
click reset

**Comment by fredericky123** [comment]
啊 谢谢 竟然没有看懂reset的图标标志
