### ISSUE TITLE
[Bug]外网环境下不能使用小牛翻译

### ISSUE THREAD

**Issue by octahedron-lh** [windingwind/zotero-pdf-translate#554]
**Describe the bug**
在小牛翻译2023年4月23号官方证书更新之后, 我的插件使用小牛翻译时就显示错误(见截图1), 多方尝试现基本确定是和我在国外网络情况下被判断证书过期, 浏览器和Zotero都刷新不出新的证书. 当我直连VPN到国内时,一切正常.(见截图2,3).  

**To Reproduce**

1. 在外网环境下
2. 将翻译选项设为“小牛翻译”，设置正确的密钥
3. 选中文本翻译
4. 显示 [请求错误]

**Expected behavior**
我期望在外网环境下也能正常实现小牛翻译的正常运行.

**Screenshots**
截图1: 
![image](https://github.com/windingwind/zotero-pdf-translate/assets/73725434/61cc64c2-59ef-4ce7-b6e1-ba19ec5450a5)
截图2: 
![image](https://github.com/windingwind/zotero-pdf-translate/assets/73725434/1c6037d7-66ae-4a63-9e38-c5bf2dcb733c)
截图3: 
![image](https://github.com/windingwind/zotero-pdf-translate/assets/73725434/cc2dd900-b4c7-486f-b00d-aff80c1cc807)

**Environment**

- OS: Windows
- Zotero Version: 现用7.0.0-beta.36+3ef1f0992 (64-bit), 错误也会出现在Zotero 6版本
- Addon Version: 现用1.1.0-9, 错误也会出现2023年4月23号起的任何版本

**Additional context**
重装浏览器、更换浏览器、清除浏览器缓存、利用chrome://net-internals/#hsts清楚niutrans.com的旧证书等方法我已尝试无效。 

虽然错误显示的内容已经指出：“这些错误与本插件无关，由小牛翻译服务引起”，但出于1. 小牛的工作人员无法解决这个问题 2.我安装的另一个zotero插件(Zotero IFpro max)也有小牛翻译选项, 同样的密钥在外网条件下翻译无报错.   我抱着试试的态度提出了这个问题, 提前谢谢!

**Comment by windingwind** [comment]
插件只提供通过api的访问，证书等问题与插件无关，因此无法在插件解决。
