### ISSUE TITLE
zotero beta38 /translate1.1.0-12 标题翻译无效

### ISSUE THREAD

**Issue by Z0o0o** [windingwind/zotero-pdf-translate#558]
1.标题翻译无效
2.选中自动翻译无效，需要点击才会翻译
<img width="129" alt="Snipaste_2023-08-26_13-29-34" src="https://github.com/windingwind/zotero-pdf-translate/assets/121789386/7a183173-bd7f-4fce-8dfe-fe49b08c3cee">

**Comment by windingwind** [comment]
#6

**Comment by thebetter2** [comment]
> 1.标题翻译无效 2.选中自动翻译无效，需要点击才会翻译 <img alt="Snipaste_2023-08-26_13-29-34" width="129" src="https://user-images.githubusercontent.com/121789386/263441639-7a183173-bd7f-4fce-8dfe-fe49b08c3cee.png">

大哥，你用的是zip压缩包版本的zotero7吧，用那个正常程序安装的zotero7正常。（我两个试过了，压缩包版本的zotero7也是选中不能自动翻译，好像zip压缩包版本的zoteo7不是注册的程序的原因？我也不清楚）

**Comment by Brave126** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/49699838/00c1fa67-29e4-4123-9a54-b1a427ffcdc6)
你看下语言这里是中还是en，有时候英文的也是zh插件认为是中文的就不会翻译，我这之前就是这个问题

**Comment by Z0o0o** [comment]
> ![image](https://user-images.githubusercontent.com/49699838/264518380-00c1fa67-29e4-4123-9a54-b1a427ffcdc6.png)你看下语言这里是中还是en，有时候英文的也是zh插件认为是中文的就不会翻译，我这之前就是这个问题

谢谢您，确实是这个问题，但是明明是英文文献为什么会识别成中文，有没有什么解决办法，不然以后导入进来都要一个一个改
