### ISSUE TITLE
[Bug]PDF侧边栏标注页诱发内存泄漏

### ISSUE THREAD

**Issue by trarer** [windingwind/zotero-pdf-translate#559]
**Describe the bug**

激活插件以后，当打开具有大量标注信息的PDF条目，并保持侧边栏的标注页开启。关闭该条目后，占用内存并不会清理并持续累积。

**To Reproduce**

1. 打开具有大量标注信息（几十条或上百条最好）的PDF条目。
2. 打开侧边栏并保持标注页开启。
3. 将PDF文档从头到尾滚动一遍，然后关闭。
4. 打开多个不同（十条以上最好）的具有大量标注的PDF条目，重复步骤1～3。
5. 运行javascript开发者工具，输入`Zotero.openInViewer('about:memory')`，查看内存占用情况。

**Expected behavior**

可以看到heap相关进程占用了大量内存，报告摘要如下：

```
2,548.06 MB (100.0%) -- explicit
├──1,653.25 MB (64.88%) -- gfx
│  ├──1,649.38 MB (64.73%) ── heap-textures
│  └──────3.88 MB (00.15%) ++ (5 tiny)

2,373.20 MB (100.0%) -- heap-committed
├──2,285.21 MB (96.29%) ── allocated
└─────87.99 MB (03.71%) ── overhead
```

**Environment**

- OS: macOS Ventura 13.5.1 (M2)
- Zotero Version: 7.0.0-beta.38+b79e0b3d7
- Addon Version: 1.1.0-13

**Additional context**

这个问题在貌似只在 macOS 上存在，而且很多对PDF标注有影响的插件都有类似共性问题。

**Comment by northword** [comment]
与此插件无关，请前往 Zotero 论坛发帖。

**Comment by trarer** [comment]
Zotero 论坛认为是插件本身问题，因为不开启插件并不产生内存泄漏问题，也有很多插件无此问题。由于我不是开发者，无法辨析是哪里出了问题。

**Comment by windingwind** [comment]
非插件问题。zotero的近期版本将修复

**Comment by etShaw-zh** [comment]
请问你的问题解决了吗？我也遇到这个问题

**Comment by trarer** [comment]
并没有解决，新版本也没见修复

**Comment by windingwind** [comment]
非插件问题，我无法解决，请不要再在此处回复。z7 beta的近期版本或将修复
