### ISSUE TITLE
阅读pdf时右侧栏笔记内容过多造成无法滚动到底部

### ISSUE THREAD

**Issue by Elmusk** [windingwind/zotero-pdf-translate#564]
**Describe the bug**
作者你好，感谢你编写的插件，对我帮助很大。现在我遇到个问题，已禁用其他插件，当阅读pdf的时候，查看右边的笔记时候，发现当笔记内容过多后，无法滚动到最底部，部分内容无法显示。在条目试图下正常。

**To Reproduce**

1. 点击任意文献pdf
2. 然后点击右上角笔记按钮
3. 点击一个内容较多的笔记
4. 滚动到底部发现有些内容无法出现

**Expected behavior**
pdf阅读试图下：
![image](https://github.com/windingwind/zotero-pdf-translate/assets/36355661/4454c4e3-480a-43f5-8f9b-2676eb261635)
条目试图下：
![image](https://github.com/windingwind/zotero-pdf-translate/assets/36355661/31969e88-4a6b-4d12-ad1a-daa1d84f52e7)

**Environment**
OS: Windows 11
Zotero Version: 7.0.0-beta.38+b79e0b3d7
Addon Version: 1.1.0-13

**Comment by tuipsam** [comment]
我在使用translate插件时也有同样问题。把translate禁用后就正常了。希望可以看看是哪里出的bug。

**Comment by Redshift860** [comment]
我遇到了同样的问题，请问现在解决了吗
