### ISSUE TITLE
[Feature]能否指定特定词翻译？

### ISSUE THREAD

**Issue by CigarOVO** [windingwind/zotero-pdf-translate#565]
**Is your feature request related to a problem? Please describe.**
当使用翻译软件时，一些特有名词总是翻译错误
**Describe the solution you'd like**
能否人为指定翻译结果然后让翻译器翻译其他剩下的语句呢？

**Comment by windingwind** [comment]
换翻译服务，用小牛等有自定义词典功能的服务
