### ISSUE TITLE
靠近PDF边缘点翻译的时候，翻译框会超出边界

### ISSUE THREAD

**Issue by CaiGY001** [windingwind/zotero-pdf-translate#568]
靠近PDF边缘点翻译的时候，翻译弹窗超出边界，导致部分翻译结果被遮住，翻译弹窗也不能移动。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/143858748/9e6ead9d-f291-4b66-bd8a-8732e9bc8063)

**Comment by windingwind** [comment]
在设置里勾选弹窗自适应大小，翻译几个词就不会出现弹窗这么长看不见；翻译整段内容的弹窗会居中。
