### ISSUE TITLE
Release 1.1.0-14版本 MAC CMD+T 快捷键失效

### ISSUE THREAD

**Issue by CMD-cmd** [windingwind/zotero-pdf-translate#569]
Release 1.1.0-14版本 MAC CMD+T 快捷键失效
表现为：
- 文献条目界面按 cmd+T 无法切换标题翻译
- 文献阅读界面按 cmd+T 无法侧边栏翻译

**Comment by windingwind** [comment]
1. 切换标题翻译已移除
2. 已修复
