### ISSUE TITLE
使用小牛翻译引擎，ip被封禁

### ISSUE THREAD

**Issue by zgq2020** [windingwind/zotero-pdf-translate#57]
使用小牛翻译，ip被封禁，由此我专门问了下小牛的客服，客服说插件没有正确调用小牛的翻译接口，所以被小牛的程序自动封禁了。小牛客服帮我解封了ip，但他说之后如果仍然使用这个插件，还是会被封禁。

**Comment by zgq2020** [comment]
那请问是否能通过购买更高的额度，避免被封禁的情况

**Comment by windingwind** [comment]
将会在近期更新增加使用secret的接口。
你认为需要移除现有的免费接口吗？加入免费接口的初衷是方便使用，但目前我收到非常多的ip封禁相关问题。

**Comment by zgq2020** [comment]
个人认为目前不必移除免费接口，或者可以将无风险的接口和有风险接口分成两列，供用户自己选择，且在用户选择有风险接口时提示用户，明确告知其风险。
期待新增加的serect接口，感谢开发者的工作，让科研更便捷。赞

**Comment by zgq2020** [comment]
期待新增加的secret接口

**Comment by windingwind** [comment]
v0.3.14 updated. You can now use the `Niu*` with your NiuTrans apikey. The old `Niu` is named as `Niu(Trial)` now.

**Comment by zgq2020** [comment]
Thanks for your work

**Comment by Qitingshe** [comment]
> 

不用去除免费接口，但是需要将默认的自动翻译给关掉，否则的话，每次鼠标选中文本都会请求一次，造成短时间内大量的请求

**Comment by Qitingshe** [comment]
可以尝试添加辅助按键进行自动翻译，如，按住shift键，然后选中文本自动翻译，这样可以避免无效请求
