### ISSUE TITLE
[Bug]zotero7,Macbook 划中翻译框，无法添加翻译到笔记

### ISSUE THREAD

**Issue by lenken012** [windingwind/zotero-pdf-translate#571]
**Describe the bug**
选中文字翻译后，翻译框点击翻译添加笔记按钮无反应，无法添加翻译到笔记

**To Reproduce**

1. 进入PDF界面，选中文本翻译
2. 翻译后点击下方的添加翻译到笔记
3. 没有任何反应，无法添加至右侧笔记页面

**Expected behavior**
解决点击添加笔记按钮无反应的情况，实现实时添加翻译笔记

**Screenshots**
<img width="1788" alt="1" src="https://github.com/windingwind/zotero-pdf-translate/assets/141751384/711a7ade-1844-43a0-b53c-9294e2095969">

**Environment**

- OS:Apple M1 Pro；macOS13.3.1 (22E261) 
- Zotero Version：7.0.0-beta.39+ecba25be0
- Addon Version：1.1.0-15

**Comment by cos-666** [comment]
我也是

**Comment by windingwind** [comment]
@cos-666 不要在标记为已解决的，针对过时版本的问题下回复。如果有问题单开一个issue
