### ISSUE TITLE
[Feature]希望接入开源翻译站点提供的谷歌翻译

### ISSUE THREAD

**Issue by albertface** [windingwind/zotero-pdf-translate#572]
在某些特定领域的翻译方面感觉谷歌翻译比其他翻译都准，但目前谷歌翻译的镜像站所剩无几，全局代理又会影响论文下载等其他方面。所以希望能够接入其他自建的开源谷歌翻译，例如[simply](https://simple-web.org/projects/simplytranslate.html)和[lingva](https://github.com/thedaviddelta/lingva-translate)。

**Comment by northword** [comment]
代理使用规则模式或pac以缓解

**Comment by albertface** [comment]
如果我在其他应用中不想使用这个规则，为了一个翻译功能每次切来切去也太麻烦了

**Comment by northword** [comment]
没能理解，你的问题在于不开代理不能访问谷歌，开了代理影响学术网站识别ip，那你在代理里，谷歌相关始终走代理，学术网站始终走直连即可。这在任何应用都适用，而不是为本插件进行的修改。

**Comment by albertface** [comment]
举个例子，我习惯在浏览器使用swichyomega配置代理规则并且走socks5端口，然后代理软件中关闭http代理。如果要为插件额外增加代理规则，就要每次使用时切换一次代理软件的设置。
每个人的环境都有所不同，所以还是希望能在插件内直接解决这个问题。

**Comment by albertface** [comment]
之前issue中也有类似的需求：[#270]和[#490]

**Comment by windingwind** [comment]
Google Google does not require a secret, but you can put your own API URL in the secret to replace the default URL (translate.google.com/translate.googleapi.com).

**Comment by albertface** [comment]
Sorry, but the problem is not solved yet. Actually, one of the reasons for this issue is that "there are few public URL left for Google Translate". 
Meanwhile, I also tried to directly fill in the public url from the open source mirror sites mentioned above, but an error occurs as "请求错误". I guess that the response of the url is different from the official Google Translate.

**Comment by windingwind** [comment]
so that's something we cannot help. i would agree with @northword that proxy rules would be the most reasonable solution. 

i won't reply to this thread anymore.
