### ISSUE TITLE
[Feature]关于未来版本中增加“为新文献自动翻译标题/摘要”选项的请求

### ISSUE THREAD

**Issue by PhoenixHwang** [windingwind/zotero-pdf-translate#573]
**Is your feature request related to a problem? Please describe.**
大佬好，translate插件的“翻译标题/摘要”功能能够大幅提升非英语母语者快速鉴别文献的效率，尤其在元分析和零散文献调研等场景下。但当使用者每一次抓取新文献时，均需手动选择相应条目，再右键对标题/摘要进行翻译。尽管插件提供了选中多个条目进行翻译的功能，已经十分方便，但依旧存在优化机械式重复操作的空间。

**Describe the solution you'd like**
鉴于此，特来咨询在未来版本中，是否考虑新增“自动翻译标题/摘要”的功能。这将能够减少一些重复操作，结合将标题翻译栏在界面中常驻，能够更加高效地实现新条目标题自动双语对照。

**Describe alternatives you've considered**
当然，一些使用者可能并不需要自动翻译标题/摘要（以节省token和后台占用），也许可以考虑将“是否自动翻译新导入文献标题/摘要”作为插件设置中的一个选项，以最大化该插件的自由度。不胜感激~

**Additional context**
![image](https://github.com/windingwind/zotero-pdf-translate/assets/127656547/25754d0d-6345-45ac-8f5a-25a7d66262de)

**Comment by northword** [comment]
你这是不是很旧的版本了？新的插件不会将翻译写入短标题。
部分引文样式需要使用短标题输出字段，建议不要非法占用字段。

另外说升级后的 zotero actions & tags 插件可以缓解此问题。

**Comment by PhoenixHwang** [comment]
啊~ 抱歉我的失误，请忽略存储字段，这是我手动迁徙的。插件原本提供了“标题翻译”字段，也可以拉出来固定。主要就是想咨询自动翻译标题/摘要的请求，您是指升级后的 zotero actions &amp; tags 插件可以实现该自动操作吗？我这就去试试，谢谢大佬！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月8日(周五) 中午12:48
收件人: ***@***.***&gt;;
抄送: "Phoenix ***@***.******@***.***&gt;;
主题: Re: [windingwind/zotero-pdf-translate] [Feature]关于未来版本中增加“为新文献自动翻译标题/摘要”选项的请求 (Issue #573)




 
你这是不是很旧的版本了？新的插件不会将翻译写入短标题。
 部分引文样式需要使用短标题输出字段，建议不要非法占用字段。
 
另外说升级后的 zotero actions &amp; tags 插件可以缓解此问题。

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-tag/discussions/107
