### ISSUE TITLE
zotero7的zotero-pdf-translate插件不稳定

### ISSUE THREAD

**Issue by mengchaoheng** [windingwind/zotero-pdf-translate#574]
zotero7的zotero-pdf-translate插件不稳定，有时候翻译失败，没有弹出翻译。有一定的随机性，有时恢复正常后，过一会再次出现问题。视频见https://youtu.be/x4CQSBjzJac

**Comment by QuantumRoseinAmethystVase** [comment]
一样的问题，我是最近添加的PDF几乎不能选中后弹窗翻译，之前添加的PDF却功能正常。

**Comment by mengchaoheng** [comment]
您好，更新1.1.0-16后问题依旧，请问有没有同样的问题？

**Comment by QuantumRoseinAmethystVase** [comment]
> 您好，更新1.1.0-16后问题依旧，请问有没有同样的问题？

1.1.0-18打开最近的PDF时还是不能自动弹出弹窗，只有翻译的按钮，点一下才出现弹窗。

**Comment by windingwind** [comment]
见#6。请仔细阅读使用文档！！！！
