### ISSUE TITLE
[Feature]在PDF中实现原文整段、整页或全文翻译

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-pdf-translate#575]
最近web端的沉浸式翻译插件对快速理解整篇英文非常有用。

希望该插件也能实现，整段、整页、全文翻译功能，增加快捷方式配合鼠标翻译实现该功能。

谢谢

**Comment by northword** [comment]
参考：http://b23.tv/eRrYY3D

**Comment by llity** [comment]
@northword 这个插件不错，它本身依赖于翻译插件才能工作吧

**Comment by northword** [comment]
相关需要咨询一下up主或在评论置顶链接里的那位up。

**Comment by windingwind** [comment]
本插件中不会实现该功能
