### ISSUE TITLE
[Feature]希望可以提供术语表功能

### ISSUE THREAD

**Issue by feeshy** [windingwind/zotero-pdf-translate#577]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
希望插件可以支持术语表功能，允许用户自己指定某些术语的翻译

**Describe alternatives you've considered**

**Additional context**
某些API是支持术语表的（比如[DeepL](https://www.deepl.com/zh/docs-api/glossaries)）

**Comment by yzy1228682367** [comment]
哇哦，如果可以有这个功能，就很赞！

**Comment by windingwind** [comment]
使用翻译服务的术语表即可
