### ISSUE TITLE
[Feature] 推荐一个第三方 Deepl Api 服务

### ISSUE THREAD

**Issue by lol2025** [windingwind/zotero-pdf-translate#579]
不需要绑定信用卡，而且送1年每月50w字符量，速度基本上和官方没区别。申请地址：https://deepl-pro.com/#/translate

这里有替换好接口的插件包下载：https://mp.weixin.qq.com/s/7Ony4OwGQh3iJpo8N2PoTQ

希望作者能在插件中加个接口，或者可以通过密钥格式自动判断，官方pro版没有尾缀，免费版是:fx尾椎，这个是:dp尾椎，谢谢。

**Comment by windingwind** [comment]
欢迎pr。也建议该厂商通过pr支持接口。
