### ISSUE TITLE
[Feature]增加段落发音朗读功能

### ISSUE THREAD

**Issue by Kearney3** [windingwind/zotero-pdf-translate#583]
**Before Issue/提问之前**

1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;

**Issues not in the template format will be ignored/不按模板格式或不完整填写模板内容的提问将不会被回复。如果你看不懂英文可以用中文提问，但请有礼貌地详细描述你的问题，不要浪费大家的时间！！！**

**Edit the template below and delete the section above/必须准确详细地填写编辑以下提问模版，并删除上面的内容，否则不会被回复**

**Is your feature request related to a problem? Please describe.**
希望能够添加朗读功能，对于划线的段落可以朗读出来，类似于Edge中的朗读网页功能。这样阅读论文的时候相当于做听力磨耳朵了！

**Describe the solution you'd like**
可以调用系统的发音库或者使用网络上的发音引擎

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
可参考读屏软件或系统自带的读屏功能。不会在插件中实现
