### ISSUE TITLE
[Bug]GPT翻译的模型仅有一个选项，不能进行选择或修改

### ISSUE THREAD

**Issue by chengwenlong2008** [windingwind/zotero-pdf-translate#585]
**Describe the bug**
GPT翻译的模型仅有一个选项，不能进行选择或修改，我仅有3.5turbo的使用渠道

**Expected behavior**
希望可以有多种选择或者可以自行修改。

**Screenshots**
![image](https://github.com/windingwind/zotero-pdf-translate/assets/141288165/4f769e02-5d5b-442d-8775-75cffe873318)

**Environment**

- OS: Windows11
- Zotero Version 7
- Addon Version(1.1.0-17)

**Comment by Maasea** [comment]
这是因为不同的 Key 有着不同的模型权限，比如有些人支持使用 gpt4。所以这里通过调用官方的接口获取当前key所支持的模型。

当无法正确获取模型时（比如你使用的是第三方服务），则会出现这种情况。

你可以在 设置-> 高级 -> 编辑器 （最底部） 搜索 model 来手动修改模型。

新的更新将支持手动填写模型 #584 。

**Comment by chengwenlong2008** [comment]
好的，感谢！问题已解决

**Comment by GrayXu** [comment]
@Maasea 感谢，还想问下zotero6的版本是不是没有类似的实现

**Comment by Maasea** [comment]
> @Maasea 感谢，还想问下zotero6的版本是不是没有类似的实现

实现方法类似的，但是 owner 修改了部分配置，使得后续得更新只支持zotero7
