### ISSUE TITLE
[Feature]请问支持配置多个gpt key 实现分流负载吗？如何配置

### ISSUE THREAD

**Issue by fredericky123** [windingwind/zotero-pdf-translate#587]
尝试用#隔开多个key，发现会提示错误，支持同时配置多个key吗

**Comment by windingwind** [comment]
不支持

**Comment by fredericky123** [comment]
Bob 翻译和 沉浸式翻译，都是支持多个api的
强烈建议实现负载均衡作为未来的一个plan
感谢！
https://immersivetranslate.com/docs/services/openai/#:~:text=%E6%B2%89%E6%B5%B8%E5%BC%8F%E7%BF%BB%E8%AF%91%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%20API%20Key%20%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%2C%20%E8%AF%B7%E5%9C%A8%E5%A1%AB%E5%86%99%E7%9A%84%E6%97%B6%E5%80%99%E7%94%A8%E8%8B%B1%E6%96%87%E9%80%97%E5%8F%B7%20%2C%20%E5%88%86%E9%9A%94%E4%B8%8D%E5%90%8C%E7%9A%84%20key
