### ISSUE TITLE
[Bug]Pop-up window show an extra line when side window switched to note tab

### ISSUE THREAD

**Issue by hao-yg** [windingwind/zotero-pdf-translate#59]
**Describe the bug**
Sometimes I take some notes on the right side when reading documents. However, when translated sentences are shown in the pop-up window, it appears that there is an extra line showing ‘adding notes’ so that the translated word are squeezed out of the window. This bug ‘won't' happen when I switch the side window to other tab, such as the message tab.

**To Reproduce**
1. open a pdf document
2. Click on the note button in the upper right corner
3. add a new note
4. choose words to be translated, and the pop-up window shows bug.

**Expected behavior**
All translated words stay inside the window

**Screenshots**
![屏幕截图 2022-03-30 225809](https://user-images.githubusercontent.com/73220026/160867307-22666156-5acd-45b7-8439-0803e28d677d.jpg)
![屏幕截图 2022-03-30 230410](https://user-images.githubusercontent.com/73220026/160867325-78cee72a-dc38-4690-8ccd-038236e750a2.jpg)

**Environment**
 - Windows
 - Zotero Version 6.0.4
 - Addon Version 0.3.11

**Additional context**

**Comment by windingwind** [comment]
fixed in v0.3.15
