### ISSUE TITLE
[Feature]希望可以增加历史记录的功能

### ISSUE THREAD

**Issue by Donnie-L** [windingwind/zotero-pdf-translate#590]
在阅读过程中，如果某些引擎翻译不满意，可能会切换多个引擎来翻译。或者想多次查看之前的翻译结果。那么这些情况就需要多次重复划词，多次翻译，重复消耗token。

如果插件可以记录5-10条的翻译历史，那么就可以前后对比，不需要多次消耗翻译token。

**Comment by windingwind** [comment]
历史记录的功能其实是设计的时候就预留的，主要问题是怎么显示合适
