### ISSUE TITLE
[Bug]弹窗UI宽度无法自适应变化

### ISSUE THREAD

**Issue by Zz-dong** [windingwind/zotero-pdf-translate#591]
**Describe the bug**
弹窗UI宽度无法自适应，小框可以拖动，但是外面的狂无法自适应的跟随变化大小

**Screenshots**
![image](https://github.com/windingwind/zotero-pdf-translate/assets/78004570/c06bdc32-562f-4af9-9d9b-4286a9334aa2)

**Environment**

- OS: Windows11
- Zotero Version：7.0.0-beta.40+24ae34104 (64-bit)
- Addon Version：1.1.0-18

**Comment by skipskipthree** [comment]
同样的bug

**Comment by Aaronlves** [comment]
我也遇到了，而且我还遇到一个：文件太大的时候这个弹窗不会自动翻译了...

**Comment by windingwind** [comment]
@Aaronlves 与文件大小无关，见#6

**Comment by Zz-dong** [comment]
@windingwind 除了上述提到的bug之外，当选中一个单词时，有时出现发音按钮也会超出边框（根据测试，取决于单词音标的长度）。我觉得应该是类似的bug，或许可以一起解决
![image](https://github.com/windingwind/zotero-pdf-translate/assets/78004570/a87c0f8c-9529-4b3b-ac9d-141c38937f38)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/78004570/6130b2d6-fc57-4787-8b42-7f745cc0d729)

**Comment by Aaronlves** [comment]
> @Aaronlves 与文件大小无关，见#6

不好意思偏题了。但是借楼回复一下，刚刚看了最近被关闭的一个issue，发现这个问题确实跟文件大小无关。如果文档的语言没有标记或者标记不是en，那么这个translator就不会自动运作。建议在#6里写清楚这一问题的解决办法。我看好多人遇到了这个问题但并不知道是什么原因。我一直以为是跟页数大小有关系来着 :D

**Comment by Frozen-hc** [comment]
我也遇到了这样的问题

**Comment by windingwind** [comment]
Auto-Translation doesn't occur
Check if the current item's language is in the plugin settings' ignore list. See https://github.com/windingwind/zotero-pdf-translate#advanced

#6写的非常清楚，只是很多人不看

**Comment by skipskipthree** [comment]
隔壁更新了zotero style插件，不能自适应的问题解决了

**Comment by Zz-dong** [comment]
> 隔壁更新了zotero style插件，不能自适应的问题解决了

这个问题似乎与zotero style无关。 我没有启用zotero style插件就出现了这个问题。其次是我安装了zotero style最新版的插件也没有解决这个问题，难受。

**Comment by Frozen-hc** [comment]
> > 隔壁更新了zotero style插件，不能自适应的问题解决了
> 
> 这个问题似乎与zotero style无关。 我没有启用zotero style插件就出现了这个问题。其次是我安装了zotero style最新版的插件也没有解决这个问题，难受。

我安装最新版style解决了此问题，使用的是其beta最新版

**Comment by windingwind** [comment]
fixed in latest prerelease
