### ISSUE TITLE
[Feature]是否可以增加模拟网页获取译文的方法，而不是调用API？

### ISSUE THREAD

**Issue by jasonyuu** [windingwind/zotero-pdf-translate#593]
目前免费的翻译引擎具有诸多限制，是否可以增加模拟网页获取译文，这样可以使用更多的翻译引擎免费翻译，据我所知，知云就是这么干的
![image](https://github.com/windingwind/zotero-pdf-translate/assets/64294920/556238a1-72e1-4cb8-98c7-d50f21bb7467)
。
搜狗翻译十分准确，但是已经无法通过调用API的方式使用，是否可以通过这种方式添加到插件中？
只是想提供一种添加更多免费翻译方式的思路，还请作者大大考虑。

**Comment by windingwind** [comment]
欢迎pr。模拟网页请求的稳定性很差，我没有时间经常维护这类，因此我倾向于不添加这类翻译服务（除非有人pr）

**Comment by jasonyuu** [comment]
您好，您的邮件我已经收到

**Comment by jasonyuu** [comment]
您好，您的邮件我已经收到
