### ISSUE TITLE
[Bug]Complete the Title Here

### ISSUE THREAD

**Issue by Aaronlves** [windingwind/zotero-pdf-translate#594]
**Describe the bug**
Sentences selected in a large PDF can not be translated automatically. I need to click the "translate" button to translate. And I encounter a more severe bug half a month ago in which I can't even translate what I select by the button below.

**To Reproduce**
_I guess it is:_
1. Open a PDF with over (about) 200 pages.
2. Select any sentence.
3. Here it is.

**Expected behavior**
The sentence selected could be translated in the pop-up window in a large PDF as same as in a smaller PDF.

**Screenshots**
When in a PDF with over around 200 pages:
![image](https://github.com/windingwind/zotero-pdf-translate/assets/37626504/87bfe32c-6cd3-4283-8f21-37dd636b84b9)
When in a smaller PDF:
![image](https://github.com/windingwind/zotero-pdf-translate/assets/37626504/b4317212-4c0b-4004-b603-1cee337928e8)

**Environment**
- OS: Windows 11
- Zotero Version: 7.0.0-beta.40+24ae34104 (64-bit)
- Addon Version: 1.1.0-17

**Additional context**
I don't know why and how it happened. But I met this problem about half a year ago.

**Comment by windingwind** [comment]
#6 
<img width="327" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/33902321/159ff34a-9872-456d-b269-6bf08be560c3">
