### ISSUE TITLE
Common Issues

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-pdf-translate#6]
## Translation don't Show Up
Choose some text, right click on the choosen text, and then view result in the popup/right sidebar.

## Translate Error
| Type | Detail | Solution |
| ---- | ---- | ---- |
| Request Error | Slow or no result/Error: Request timed out | change a translate engine |
| Request Error | Error: ... failed with status code 4xx | invalid secret |
| Request Error | Error: ... failed with status code 425 | request too fast |
| Others | - | post a issue |

> **For China Mainland Users** Google(CN) uses `google.cn` but you may still meet timed out error, even if you can access `google.cn` in your browser. It depends on your network environment.

## Translate Engine & Secret
See https://github.com/windingwind/zotero-pdf-translate#translate-engine

### Show/Hide Popup
Edit->Preferences->PDF Translate->Enable Popup

**Comment by windingwind** [comment]
# Debug Steps

- Start Zotero but don't open the PDF.
- Go to Help->Debug Output Logging->View Output.
- Open your PDF.
- Select some text after the debug window is opened.
- Copy the logs and paste them in your issue.

**Comment by gcb-0909** [comment]
IP被限制了怎么办？
