### ISSUE TITLE
[Bug]Complete the Title Here

### ISSUE THREAD

**Issue by Kevin-wangyu** [windingwind/zotero-pdf-translate#600]
**Describe the bug**
已经翻译好标题，但右键“切换原标题/翻译”不起作用，仍然是英文，重装后起作用，但过段时间或者下次打开zotero又会失效，已经很多次了

**Screenshots**
![image](https://github.com/windingwind/zotero-pdf-translate/assets/63687567/133e43aa-bbc8-46fd-90c9-d4ef16a4504d)

**Environment**

- OS: Windows 11
- Zotero Version: 6.0.27
- Addon Version: 1.0.25

**Comment by windingwind** [comment]
zotero6版本已经停止维护。
