### ISSUE TITLE
[Feature]please support chatglm2, thanks!

### ISSUE THREAD

**Issue by zeushera140** [windingwind/zotero-pdf-translate#603]
https://github.com/THUDM/ChatGLM2-6B
I tried it, good for English-Chinese.

**Comment by Maasea** [comment]
After looking at the ChatGLM project, it itself is a large Python model that can't possibly be integrated into zotero-pdf-translate.

However, in the project introduction, a similar interface to ChatGPT has been implemented, as mentioned in the [guide](https://github.com/THUDM/ChatGLM2-6B#api-%E9%83%A8%E7%BD%B2).

In other words, you can deploy ChatGLM on your own computer, and then replace the interface in zotero-pdf-translate's chatgpt with a local address.
