### ISSUE TITLE
[Bug] CNKI翻译英文句子卡顿

### ISSUE THREAD

**Issue by Tyqfat** [windingwind/zotero-pdf-translate#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.44+64a78412c (64-bit)
- Plugin Version: [Release 1.1.0-18] or [Release 1.1.0-17

### Describe the bug

选择CNKI翻译英文句子时，响应较慢，选句子时卡顿，而且有时候翻译好的中文会变成原英文，这时又得重新选中句子，继续等待一小会才会出翻译结果。

### Debug Output

1696820676511	addons.xpi	WARN	Checking D:\AllSoftwares\Softwares\Zotero_win-x64\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1696820677231	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "Deleting older translator Peoples'daily.js with same ID as People's Daily.js" {file: "file:///D:/AllSoftwares/SoftwareDownload/Zotero%20Storage/translators/Peoples'daily.js" line: 0}]

[JavaScript Error: "Style with ID http://www.zotero.org/styles/gb7714-2015-note-ez-revised already loaded from GBT-7714-note-Chinese-EZ-auCapital.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

[JavaScript Error: "Style with ID http://www.zotero.org/styles/gb7714-2015-note-ez-revised already loaded from GBT-7714-note-Chinese-EZ-auCapital.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

[JavaScript Error: "Style with ID http://www.zotero.org/styles/gb7714-2015-numeric-ez-revised already loaded from GBT-7714-numeric-Chinese-EZ改-copy.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

appName => Zotero, version => 7.0.0-beta.44+64a78412c, os => Windows 6.2 9200, locale => zh-CN, extensions => Zotero GPT (0.3.0, extension, disabled), PDF Figure (0.1.2, extension, disabled), Better Notes for Zotero (1.1.4-25, extension, disabled), Crush Reference (0.6.4, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Ethereal Style (3.1.5, extension, disabled), Jasminum (1.0.0-6, extension, disabled), Translate for Zotero (1.1.0-17, extension, disabled)

### Anything else?

无

**Comment by windingwind** [comment]
翻译速度与插件无关
