### ISSUE TITLE
[Bug] 侧边栏的复制按钮会被任务栏遮挡

### ISSUE THREAD

**Issue by Nyeilim** [windingwind/zotero-pdf-translate#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: latest
- Plugin Version: 1.1.0-18

### Describe the bug

Win10 下打开文献条目, 侧边栏的复制按钮会被任务栏遮挡
但是打开图书条目好像就不会, 奇怪
<img src="https://github.com/windingwind/zotero-pdf-translate/assets/33322256/d3db75f9-1178-40aa-a5b1-6fc930415e57" height='600px'/>

###  Output

[Debug Output.zip](https://github.com/windingwind/zotero-pdf-translate/files/12844106/Debug.Output.zip)

**Comment by Nyeilim** [comment]
这种情况的出现似乎和文献有关, 我重新下载两篇文献就没事了

**Comment by Nyeilim** [comment]
令我困惑的是, 这个现象好像和特定的文献有关, 极少数文献的翻译界面显示是正常的, 有些不是

**Comment by Nyeilim** [comment]
找到原因了, 如果一篇文献的信息页过长, 在主页面不能一页显示的话, 打开之后就会出现这样的问题
下面两图展示的就是 '能够一页显示的信息页' 和 '不能一页显示的信息页'
<div>
<img height='400px' src='https://github.com/windingwind/zotero-pdf-translate/assets/33322256/d873220f-89bf-489a-ab79-c1523ddf6bc8'/>
<img height='400px' src='https://github.com/windingwind/zotero-pdf-translate/assets/33322256/4d04bf8a-b9bd-4be8-9f9b-46b1e1d75d42'/>
</div>

**Comment by jlu511** [comment]
> 找到原因了, 如果一篇文献的信息页过长, 在主页面不能一页显示的话, 打开之后就会出现这样的问题 下面两图展示的就是 '能够一页显示的信息页' 和 '不能一页显示的信息页'
> 
> <img alt="" height="400px" src="https://user-images.githubusercontent.com/33322256/273622485-d873220f-89bf-489a-ab79-c1523ddf6bc8.png"> <img alt="" height="400px" src="https://user-images.githubusercontent.com/33322256/273623592-4d04bf8a-b9bd-4be8-9f9b-46b1e1d75d42.png">

并不是，右边的文献虽然长，但是有下拉条，可以向下滚动，使文献完全显示出来。
而翻译页面显示补全，有可能是dpi的改变，通常高分辨屏幕用了125%或150%放大，这时候翻译界面下面的复制等几个图标显示不出来，并且也没有滚动条可以向下滚动。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/64378673/e71cf7f5-b51f-4036-89c6-53ea7b88fd55)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/64378673/43d4f2d4-97a9-4fa3-ba1a-afa999517180)
我这里是125%放大，显示不全
