### ISSUE TITLE
[Bug] 更新1.1.0-18版本后，新添加的文献无法自动翻译

### ISSUE THREAD

**Issue by ihahya** [windingwind/zotero-pdf-translate#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Windows
- Zotero Version:  7
- Plugin Version:  1.1.0-18

### Describe the bug

10.12更新了1.1.0-18版本的插件，自此新添加的文献（无论是哪个网站）都无法选中之后自动翻译，但是之前的文献仍可以自动翻译
有查询前人的提问，没有找到解决方法
在#6中也没有找到解决方法
感谢解答！

### Debug Output

[Debug Output_files.zip](https://github.com/windingwind/zotero-pdf-translate/files/12909147/Debug.Output_files.zip)

### Anything else?

<img width="941" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/133827dc-8ef9-49c2-af3b-590c8c549a5f">
<img width="870" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/28511e7c-7088-4323-a0b9-03575cd6c430">

**Comment by windingwind** [comment]
检查条目语言及忽略自动翻译语言设置

**Comment by ihahya** [comment]
目测没有问题
<img width="582" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/ad83035a-009f-41fb-b573-df3d2ac987c6">
<img width="542" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/7cfab07b-1902-4376-a36a-94d6e6356085">

**Comment by windingwind** [comment]
检查条目语言，另善用搜索，见#6已有说明

**Comment by ihahya** [comment]
您好，条目语言已检查，是英语无误
#6 也重看了，恕我眼拙还是没有找到，希望您指点一下
但是今天发现有变化，之前是无法识别到语言，今天是可以识别语言，但选中后需要点击一下翻译才能正常进行
<img width="947" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/cfdd642d-1e52-4464-b1c3-42e319d857c9">
<img width="884" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/b400d668-d468-4970-8d99-16699d1ccb4e">

**Comment by windingwind** [comment]
请截图条目语言数据。另识别语言指的是什么？没有该功能

**Comment by windingwind** [comment]
see https://github.com/windingwind/zotero-pdf-translate/issues/613#issuecomment-1764189952

**Comment by ihahya** [comment]
解决了！感谢，我误解了条目语言的意思，以为是文本语言，才发现条目信息栏显示是zh
<img width="933" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/129815867/297b603e-8b49-4615-8e30-f9102a3354e6">
现在已解决，非常感谢！（今天满课，回复晚不好意思）
能另外问一下是什么导致新添加的条目变成zh的吗

**Comment by windingwind** [comment]
其他插件，如茉莉花
