### ISSUE TITLE
[Bug] Tranlate Title and Translate Abstract stopped working

### ISSUE THREAD

**Issue by jmspfs** [windingwind/zotero-pdf-translate#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 Pro, 22H2
- Zotero Version: 6.0.27
- Plugin Version: 1.0.25

### Describe the bug

I've been using the pluggin since last week and noticed the Tranlate Title and Translate Abstract features are somewhat unstable. They worked for some itens (tests with journal articles and conference papers), but not for others. They didn't work for some items, then worked in other try. Yesterday the pluggin stoped working at all (it didn't show up, neither as these mouse options, nor in the pdf window) and the pluggin pane ( add-ons) in Zotero didn't work at all (didn't show up when clicked). All got back, after a system reboot, but the Tranlate Title and Translate Abstract features don't work anymore. They show up, but don't do anything.

### Debug Output

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://xxx:****@xxxxnet:18080/xxxx/zotero/
Line Number 1, Column 1:" {file: "https://xxxx:****@xxxx.net:18080/xxxx/zotero/" line: 1}]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

version => 6.0.27, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.27, extensions => Zotero PDF Translate (1.0.25, extension), ZotFile (5.1.2, extension, disabled), Zotero LibreOffice Integration (6.0.4.SA.6.0.27, extension, disabled), Zotero Word for Windows Integration (6.0.3.SA.6.0.27, extension, disabled), Zutilo Utility for Zotero (3.10.0, extension, disabled), ZoteroPreview (0.1.6, extension, disabled), ZoteroAbstractCleaner (0.0.7, extension, disabled), Zotero Citation Counts Manager (1.3.0, extension, disabled), PDF kit for Zotero (1.0.0, extension, disabled), Zotero Add Collection Tag (0.0.2, extension, disabled), Better BibTex for Zotero (6.7.125, extension, disabled)

(3)(+0048983): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(4)(+0000005): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000040): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000007): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000006): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000005): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(3)(+0000007): MIME type application/pdf cannot be handled internally

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(3)(+0007048): [Zotero PDF Translate] runTranslationTask {"noDisplay":true}

(3)(+0000001): [Zotero PDF Translate] disabledByItemLanguage

(3)(+0003554): itemTree.render(). Displaying Item Tree

(3)(+0003068): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(4)(+0000006): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000029): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000015): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000008): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(4)(+0000006): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(3)(+0000008): MIME type application/pdf cannot be handled internally

(4)(+0000003): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [12449, 'https://ieeexplore.ieee.org/document/7811597']

(3)(+0002294): [Zotero PDF Translate] runTranslationTask {"noDisplay":true}

(3)(+0000002): [Zotero PDF Translate] disabledByItemLanguage

**Comment by jmspfs** [comment]
I think the issue is solved: "item language" must be assigned in order for the feature to work. I don't hink it is obvious and maybe it should hbe in the FAQs...

**Comment by windingwind** [comment]
Well, in some earlier versions of the plugin, the `disable auto-translate for languages` is not correctly initialized (they should be empty, not undefined.) So please check here and type things here, close the settings window, then open again and delete things here. This should solve this issue.

If you are on Z7 and with the latest beta, then this bug should be fixed.

**Comment by jmspfs** [comment]
Yes, if I put "en" in the "Disable Automatic..." box it works without the language setting in the Info page of the item being set, i.e., with it empty. Again, I think it is somewhat confusing, as it doen't seem connected. May be it should be put in FAQs...
Thank you for your quick reply! Please keep up your wonderful work!

**Comment by windingwind** [comment]
This is a bug with earlier versions of the plugin, and I think it’s fixed in the latest beta (with Zotero 7).

**Comment by jmspfs** [comment]
Do you recommend changing to Zotero 7? Is it stable enough? There are other pluggins you made and I would like to try but they don't work with Zotero 6....

**Comment by windingwind** [comment]
Well, actually they do, but you would need to install an earlier version (not the prerelease). All my plugins work with Z6 before Z7 beta was out.

There’s no standard for stable, for me it works well. Z7 is faster and more modern. But if you don’t want to spend time on the upgrade, then just wait for the official release.
