### ISSUE TITLE
[Bug] 新手1.0.25版本沒辦法使用翻譯功能

### ISSUE THREAD

**Issue by yunnnnn97** [windingwind/zotero-pdf-translate#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 13.3.1（22E261）
- Zotero Version: 6.0.28

### Describe the bug

第一次使用Zotero和翻譯功能
安裝完擴充軟件並重啟動Zotero想嘗試翻譯功能時顯示如下資訊

### Debug Output

嘗試過重新安裝都沒辦法解決：

[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： CNKI

Error: HTTP GET https://dict.cnki.net/fyzs-front-api/getToken failed with status code 404

**Comment by windingwind** [comment]
见#6
换用其他翻译服务，部分服务需要单独设置。谷歌翻译应该适用大多数情况

**Comment by yunnnnn97** [comment]
> 见#6
> 换用其他翻译服务，部分服务需要单独设置。谷歌翻译应该适用大多数情况

Dear,
感謝你的回覆，調整後已經可以使用！
