### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yanchu97** [windingwind/zotero-pdf-translate#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version: 

### Describe the bug

最近谷歌翻译和谷歌API都突然不能用了，之前一直都可以，用着梯子和全局，访问外网正常。

### Debug Output

[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： Google(API)

Error: HTTP GET https://translate.googleapis.com/translate_a/single?client=gtx&sl=en-US&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=964953.560429&q=Assume%20L%20rounds%20of%20message%20exchanges%2C%20and%20take%20the%20lth%20round%20for%20example%3A%20the%20source%20n failed with status code 429

**Comment by windingwind** [comment]
https://stackoverflow.com/questions/66370556/429-errors-returned-from-google-translate-when-using-googletrans-library
