### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ZXYYSQ** [windingwind/zotero-pdf-translate#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 家庭中文版
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version: 9.16更新版本

### Describe the bug

已经浏览过讨论信息，设置好了自动不翻译选项，部分条目以前翻译不出来，现在可以了
![image](https://github.com/windingwind/zotero-pdf-translate/assets/148554896/2e024555-5904-40bc-92ed-f3fffd0fff50)

但右键翻译标题和摘要还是有部分条目无法显示
![image](https://github.com/windingwind/zotero-pdf-translate/assets/148554896/e36bc319-df13-402b-a98b-47647b156236)

### Debug Output

[Debug.Output.zip](https://github.com/windingwind/zotero-pdf-translate/files/13113318/Debug.Output.zip)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/148554896/f091261d-51be-4087-88e6-c664c7dcc0fc)

**Comment by windingwind** [comment]
需要完整的debug output

**Comment by ZXYYSQ** [comment]
我重启以后又可以翻译了，但是有时候已经翻译的条目会清空，需要重新再次右键翻译标题。请问应该如何获得完整调试输出

**Comment by windingwind** [comment]
翻译内容存在其他(`Extra`)字段，可能被某些滥用字段的插件覆盖修改。请禁用所有插件后排查问题
