### ISSUE TITLE
[Bug]After the update, the Zotero plug-in cannot be opened, and there is no translation option.

### ISSUE THREAD

**Issue by tc20722770** [windingwind/zotero-pdf-translate#62]
![image](https://user-images.githubusercontent.com/82642014/161037668-65d818a6-4b92-4f58-b6f1-c62cfa225dc7.png)

**Comment by windingwind** [comment]
Please follow the debug steps here: #6  and describe your problem in detail.

**Comment by tc20722770** [comment]
I can't open the plug-in option in the Zotero tool, and the translation plug-in can't be used

**Comment by tc20722770** [comment]
> 请按照此处的调试步骤操作：#6 并详细描述您的问题。

I can't uninstall and reinstall the Zotero PDF translate plug-in because I can't open the plug-in option in the Zotero tool options.

**Comment by windingwind** [comment]
This is a Zotero bug. Exit Zotero using task manager or restart your computer.

**Comment by tc20722770** [comment]
> option in the Zotero tool opt

The problem of restarting the computer has been solved, thank you. But I also found a problem: the sidebar cannot be displayed on the current PDF page, but on the front page.

**Comment by windingwind** [comment]
> > option in the Zotero tool opt
> 
> The problem of restarting the computer has been solved, thank you. But I also found a problem: the sidebar cannot be displayed on the current PDF page, but on the front page.

I don't get your point. What's the version of add-on you are using and again, please follow the debug steps here: https://github.com/windingwind/zotero-pdf-translate/issues/6 and describe your problem in detail.
