### ISSUE TITLE
[Feature] 未来能否添加插件版本与Zotero版本的对应表？

### ISSUE THREAD

**Issue by JSHZT** [windingwind/zotero-pdf-translate#620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Ubuntu20.04
- Zotero Version: 6.0.27
- Plugin Version:1.1.0.20

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate#install
