### ISSUE TITLE
[Bug] 更改不了识别语言（显示为Chinese）

### ISSUE THREAD

**Issue by ZZ0923-dc** [windingwind/zotero-pdf-translate#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win10
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version:Translate for Zotero  1.1.0-20

### Describe the bug

能翻译成其他语言但是无法翻译成中文，选Chinese后翻出来的全是英文，所有的Chinese可选项都试了

### Debug Output

[Debug Output.txt](https://github.com/windingwind/zotero-pdf-translate/files/13188009/Debug.Output.txt)

### Anything else?

![78ff73c1a4a0beb20215c108759e216](https://github.com/windingwind/zotero-pdf-translate/assets/148696583/e3da02a1-78da-4eaa-81bd-1e132958d2df)

**Comment by windingwind** [comment]
这两个框分别是从【chinese】翻译到【chinese】。你要从英文翻译到中文，左侧选择english。

**Comment by ZZ0923-dc** [comment]
> 这两个框分别是从【chinese】翻译到【chinese】。你要从英文翻译到中文，左侧选择english。

前天还能改，昨天更新后左侧不能更改了

**Comment by windingwind** [comment]
最新版已修复
