### ISSUE TITLE
[Bug] 语言识别问题

### ISSUE THREAD

**Issue by heyeruoqi** [windingwind/zotero-pdf-translate#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MACos 13
- Zotero Version: 7.0.0-beta.47+f012a348a
- Plugin Version:1.1.0-20

### Describe the bug

能够识别语言真的帮了大忙了，不过似乎有些文献第一页摘要是用英文介绍的，如果只识别第一页还是容易被识别为英语，能否识别第二页，或者说第三页的文字呢，这样子应该会更稳定些，我这里提供下一篇意大利文被识别为英语的案例：

文献名：Stratigrafie, paesaggi, soundscapes. Riflessioni su restauro archeologico, conoscenza e accessibilità a margine del teatro ellenistico-romano di Velia。
DOI：10.13128/rar-10722

链接: https://pan.baidu.com/s/1pQ29WDwmpu6Lz_xiJLPF5A 提取码: 1234 
--来自百度网盘超级会员v2的分享

### Debug Output

没有了

### Anything else?

没有了

**Comment by heyeruoqi** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/102173897/3313f32c-d6ba-4c1a-a705-d01973c931ed)

**Comment by heyeruoqi** [comment]
链接: https://pan.baidu.com/s/1AoSwsheSefYiIlB5AEZ8_A 提取码: 1234 
--来自百度网盘超级会员v2的分享

这篇文献也是识别错误了语言，原语言为法语

**Comment by windingwind** [comment]
语言识别基于摘要-标题，不会根据正文内容进行识别。如果文献信息与正文语言不同，则需手动调整。自动识别语言的目的不是每次都识别对（也是不可能的）。

**Comment by heyeruoqi** [comment]
> 语言识别基于摘要-标题，不会根据正文内容进行识别。如果文献信息与正文语言不同，则需手动调整。自动识别语言的目的不是每次都识别对（也是不可能的）。

如何手动调整呢，我想要切换成意大利语，右侧面板一直显示的是英语，切换不到其他语言。

**Comment by windingwind** [comment]
最新版本已修复
