### ISSUE TITLE
[Feature] 希望可以增加Fontfamily的设置选项，Linux下翻译结果的字体很丑。

### ISSUE THREAD

**Issue by wengyk** [windingwind/zotero-pdf-translate#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Arch linux
- Zotero Version: 6.0.27
- Plugin Version: 1.0.25

### Describe the feature request

我在zotero的配置文件prefs.js中添加：user_pref("extensions.zotero.ZoteroPDFTranslate.fontFamily", "Noto Serif CJK SC");
无法改变翻译结果的字体。
希望可以添加fontfamily的设置选项，这样Linux下翻译结果的显示效果会好得多。

**Comment by windingwind** [comment]
请问是哪个区域的字体，请提供截图

**Comment by wengyk** [comment]
> 请问是哪个区域的字体，请提供截图

![Screenshot from 2023-10-30 16-36-44](https://github.com/windingwind/zotero-pdf-translate/assets/5418636/b63e72a4-565d-41a7-984c-a959d2768a96)
这个框框里的字体不能单独设置，导致在linux下显示的字体很难看。

**Comment by windingwind** [comment]
已在先前<https://github.com/windingwind/zotero-pdf-translate/commit/332215ef5b6d70a3f8f18be6edc240bf887d5a5c>修复。

**Comment by wengyk** [comment]
> 已在先前[332215e](https://github.com/windingwind/zotero-pdf-translate/commit/332215ef5b6d70a3f8f18be6edc240bf887d5a5c)修复。

我在zotero7上安装了最新版的插件，翻译框里的字体显示已经没有问题了，非常感谢！但是还不能设置fontfamily。
![Screenshot from 2023-11-28 22-46-53](https://github.com/windingwind/zotero-pdf-translate/assets/5418636/cfd6c21e-02b0-464d-9b48-696ae6a03866)
