### ISSUE TITLE
[Feature] 我想使用学校提供的小牛翻译api，但是无法使用

### ISSUE THREAD

**Issue by yeahbab** [windingwind/zotero-pdf-translate#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.0
- Plugin Version:1.1.0-18

### Describe the feature request

我想使用学校使用的小牛翻译api，但是选择菜单的小牛翻译输入api后出现：
[请求错误]\n\n此翻译引擎不可用，可能是密钥错误，也可能是请求过快。\n可以尝试其他翻译引擎，或者来此查看相关回答：\nhttps://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f \n\n请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 小牛🗝️

Service error: 13001:apikey error OR apikey unauthorized OR service package running out
但是咨询客服询问，小牛那边没有出现问题，想问下作者大大怎么操作啊

### Describe the solution you'd like

（我觉得可能是学校提供的小牛翻译api文档可能和官网上的不一样）
接下来提供一下api文档：
接口地址： http://ip:port/niutrans/textTranslation?apikey=apikey的值
请求方式： POST
传参方式： application/json
请求参数：
![微信截图_20231030155723](https://github.com/windingwind/zotero-pdf-translate/assets/149364633/7d86cc1f-bf2d-4ce4-a9eb-0ffbd38902d1)
返回结果：
{
    "code": 200,
    "msg": "成功",
    "data": [
        {
            "sentences": [
                {
                    "data": "Hello",
                    "contrastSourceText": "你好",
                    "paragraphOrder": 0,
                    "order": 0,
                    "uuid": ,
                    "historyResult": null,
                    "len": 0,
                    "sourceLanguageAbbreviation": "zh",
                    "targetLanguageAbbreviation": "en"
                }
            ],
            "order": 0
        }
   ]

}

### Anything else?

希望作者大大能回复，谢谢大大

**Comment by windingwind** [comment]
看起来你们学校有私有部署的小牛服务，和公有的小牛翻译不同。我需要完整的服务地址。

**Comment by yeahbab** [comment]
我这边只能找到他的登入地址：https://trans.neu.edu.cn/
如果不是这个，我也找不到合适的地址了，在此再次谢谢作者大大花费业余时间解决我的问题！

**Comment by coreur** [comment]
我们也是私有部署的小牛翻译，请求的api和这个相同，只是请求的url不一样（不是http://ip:port/niutrans/textTranslation?）。请问我应该在插件的哪个地方进行修改？希望作者大大能抽空解答下，谢谢啦~

> 接下来提供一下api文档：
接口地址： [http://ip:port/niutrans/textTranslation?apikey=apikey的值](http://ip:port/niutrans/textTranslation?apikey=apikey%E7%9A%84%E5%80%BC)
请求方式： POST
传参方式： application/json
请求参数：
微信截图_20231030155723
返回结果：
{
"code": 200,
"msg": "成功",
"data": [
{
"sentences": [
{
"data": "Hello",
"contrastSourceText": "你好",
"paragraphOrder": 0,
"order": 0,
"uuid": ,
"historyResult": null,
"len": 0,
"sourceLanguageAbbreviation": "zh",
"targetLanguageAbbreviation": "en"
}
],
"order": 0
}
]

}

**Comment by windingwind** [comment]
@JacketLee 是小牛官方人员，私有API我不清楚细节

**Comment by coreur** [comment]
我之前用python的request库写过一个脚本，能正常返回翻译结果。想在zotero用，但是JavaScript我不太懂。我再琢磨琢磨，谢谢作者大大了。
