### ISSUE TITLE
[Bug] 自动更新异常

### ISSUE THREAD

**Issue by Saunak626** [windingwind/zotero-pdf-translate#626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win10
- Zotero Version: 7.0.0-beta.47+f012a348a (64-bit)
- Plugin Version: 1.1.0-21

### Describe the bug

在zotero中自动更新会导致插件版本回退

### Debug Output

![bug3](https://github.com/windingwind/zotero-pdf-translate/assets/34276206/7f118880-f90f-42ef-ab95-04579d997073)

**Comment by windingwind** [comment]
fixed
