### ISSUE TITLE
[Feature] 能否自定义GPT的prompt

### ISSUE THREAD

**Issue by shannon-paul** [windingwind/zotero-pdf-translate#627]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

在使用GPT进行翻译时能否自定义prompt，因为我发现自带的prompt效果不太好，我对比了我直接使用GPT的prompt（“我在读一篇英文论文，请帮我把以下内容翻译成中文”），这种简洁的prompt比系统自带的prompt效果要好

**Comment by windingwind** [comment]
1. 请规范填写issue
2. 该功能已有，请善用搜索
