### ISSUE TITLE
[Bug] 有道翻译和百度翻译突然都不能用了

### ISSUE THREAD

**Issue by Julita6677** [windingwind/zotero-pdf-translate#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 14.0
- Zotero Version: 6.0.29
- Plugin Version: 1.0.25

### Describe the bug

百度翻译突然就不能用了，已经重启过软件，插件也关了重开过，密钥也重新输了一遍，百度翻译本月的免费额度还没用完，但就是不能用了😭
<img width="389" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/149487675/3d95479d-8266-445b-8b82-8925e7cef8c1">

### Debug Output

[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 百度🗝️

Service error: 54004:Please recharge

**Comment by windingwind** [comment]
Please recharge means 请充值。请理解一下英文。网页显示的额度可能有延迟

**Comment by Julita6677** [comment]
抱歉！确实没看懂这里recharge 的意思🥲，刷新了一下真的该充钱了

**Comment by splinexuan** [comment]
我检查了一下，充值以后还有这个错误不知道为什么

**Comment by splinexuan** [comment]
我找到了官方的

错误码 | 含义 | 解决方法

0 | 成功 |  
52001 | 请求超时 | 重试
52002 | 系统错误 | 重试
52003 | 未授权用户 | 请检查您的 appid 是否正确，或者服务是否开通
54000 | 必填参数为空 | 请检查是否少传参数
54001 | 签名错误 | 请检查您的签名生成方法
54003 | 访问频率受限 | 请降低您的调用频率
54004 | 账户余额不足 | 请前往管理控制台为账户充值
54009 | 语种检测失败 | 不在支持检测的语种范围内
58000 | 客户端IP非法 | 检查个人资料填写的IP地址是否正确，可前往管理控制平台修改，IP限制，IP可留空
58002 | 服务当前已关闭 | 请前往管理控制台开启服务


> 我检查了一下，充值以后还有这个错误不知道为什么
