### ISSUE TITLE
[Bug]打开PDF时没有侧边栏翻译 关闭时在主页面侧边栏显示翻译

### ISSUE THREAD

**Issue by Syzygy33** [windingwind/zotero-pdf-translate#63]
**Before Issue/提问之前**
1. See #6 and search the [Issues Page](https://github.com/windingwind/zotero-pdf-translate/issues) to make sure this is not a duplicated issue;  
2. If this is a bug with Translate, i.e. no result or error, make sure you can access the translate service and the secret is currect;  
3. Remember to delete this section before submit.   

**Issues not in the template format will be ignored/不按模板格式的提问将不会被回复**

Edit the template below/编辑以下模版

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows/macOS/Linux
 - Zotero Version(Help->About Zotero)
 - Addon Version(Tools->Add-ons)

**Additional context**

**Comment by windingwind** [comment]
Please follow the debug steps here: #6  and describe your problem in detail.

**Comment by windingwind** [comment]
fixed in v0.3.17
