### ISSUE TITLE
[Bug] ALT快捷键拼接模式不可用

### ISSUE THREAD

**Issue by gwx06** [windingwind/zotero-pdf-translate#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.47
- Plugin Version:1.1.0-21

### Describe the bug

ALT快捷键拼接模式无效，只能手动在插件页面点击拼接

### Debug Output

Submit…
Clear
1698979636145	addons.xpi	WARN	Checking D:\Program Files\Zotero\distribution\extensions for addons

1698979636190	addons.xpi-utils	WARN	addMetadata: Add-on undefined is invalid: Error: Invalid addon ID: expected addon ID undefined, found undefined in manifest(resource://gre/modules/addons/XPIDatabase.jsm:2972:15) JS Stack trace: addMetadata@XPIDatabase.jsm:2972:15
processFileChanges@XPIDatabase.jsm:3433:26
checkForChanges@XPIProvider.jsm:3065:55
startup@XPIProvider.jsm:2492:12
callProvider@AddonManager.jsm:234:31
_startProvider@AddonManager.jsm:542:17
startup@AddonManager.jsm:748:14
startup@AddonManager.jsm:3468:26
observe@addonManager.js:78:29

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 2652 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2652:33
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1053 getUpdateFile
resource://gre/modules/UpdateService.jsm 732 getCanApplyUpdates
resource://gre/modules/UpdateService.jsm 3725 get canUsuallyApplyUpdates
resource://gre/modules/UpdateService.jsm 3733 get canApplyUpdates
resource://gre/modules/UpdateService.jsm 2654 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getUpdateFile@resource://gre/modules/UpdateService.jsm:1053:32
getCanApplyUpdates@resource://gre/modules/UpdateService.jsm:732:39
get canUsuallyApplyUpdates@resource://gre/modules/UpdateService.jsm:3725:12
get canApplyUpdates@resource://gre/modules/UpdateService.jsm:3733:1
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2654:9
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1053 getUpdateFile
resource://gre/modules/UpdateService.jsm 4122 UM__loadXMLFileIntoArray
resource://gre/modules/UpdateService.jsm 4017 UpdateManager
resource://gre/modules/XPCOMUtils.jsm 161 XPCU_serviceLambda
resource://gre/modules/XPCOMUtils.jsm 62 get
resource://gre/modules/UpdateService.jsm 2668 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getUpdateFile@resource://gre/modules/UpdateService.jsm:1053:32
UM__loadXMLFileIntoArray@resource://gre/modules/UpdateService.jsm:4122:29
UpdateManager@resource://gre/modules/UpdateService.jsm:4017:28
XPCU_serviceLambda@resource://gre/modules/XPCOMUtils.jsm:161:30
get@resource://gre/modules/XPCOMUtils.jsm:62:51
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2668:9
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 4024 UpdateManager
resource://gre/modules/XPCOMUtils.jsm 161 XPCU_serviceLambda
resource://gre/modules/XPCOMUtils.jsm 62 get
resource://gre/modules/UpdateService.jsm 2668 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
UpdateManager@resource://gre/modules/UpdateService.jsm:4024:33
XPCU_serviceLambda@resource://gre/modules/XPCOMUtils.jsm:161:30
get@resource://gre/modules/XPCOMUtils.jsm:62:51
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2668:9
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1786 pingStateAndStatusCodes
resource://gre/modules/UpdateService.jsm 2801 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
pingStateAndStatusCodes@resource://gre/modules/UpdateService.jsm:1786:5
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2801:28
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1053 getUpdateFile
resource://gre/modules/UpdateService.jsm 4122 UM__loadXMLFileIntoArray
resource://gre/modules/UpdateService.jsm 4216 _getUpdates
resource://gre/modules/UpdateService.jsm 4260 addUpdateToHistory
resource://gre/modules/UpdateService.jsm 1365 cleanupReadyUpdate
resource://gre/modules/UpdateService.jsm 2920 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getUpdateFile@resource://gre/modules/UpdateService.jsm:1053:32
UM__loadXMLFileIntoArray@resource://gre/modules/UpdateService.jsm:4122:29
_getUpdates@resource://gre/modules/UpdateService.jsm:4216:33
addUpdateToHistory@resource://gre/modules/UpdateService.jsm:4260:24
cleanupReadyUpdate@resource://gre/modules/UpdateService.jsm:1365:8
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2920:7
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1370 cleanupReadyUpdate
resource://gre/modules/UpdateService.jsm 2920 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
cleanupReadyUpdate@resource://gre/modules/UpdateService.jsm:1370:24
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2920:7
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1267 cleanUpReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1375 cleanupReadyUpdate
resource://gre/modules/UpdateService.jsm 2920 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
cleanUpReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1267:17
cleanupReadyUpdate@resource://gre/modules/UpdateService.jsm:1375:3
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2920:7
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/gwx/AppData/Roaming/Zotero/Zotero/Profiles/guun1f3x.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 6879}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/gwx/AppData/Roaming/Zotero/Zotero/Profiles/guun1f3x.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 6879}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 655}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:655:7

1698979667624	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/l0o0/jasminum/main/update.json - 404: Not Found

1698979667625	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/muisedestiny/zotero-file/main/update.json - 404: Not Found

1698979667719	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/muisedestiny/zotero-style/main/update.json - 404: Not Found

1698979671045	addons.xpi	WARN	Download of https://github.com/windingwind/zotero-better-notes/releases/latest/download/zotero-better-notes.xpi failed: Expected addon version 1.1.4-3 instead of 1.0.4

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\gwx\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist"]
openWindowPrompt@resource://gre/modules/Prompter.jsm:1226:17
openPrompt@resource://gre/modules/Prompter.jsm:1067:12
openPromptSync@resource://gre/modules/Prompter.jsm:1046:10
confirmEx@resource://gre/modules/Prompter.jsm:1465:10
confirmEx@resource://gre/modules/Prompter.jsm:305:14
submit/<@chrome://zotero/content/standalone/standalone.js:856:22
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

appName => Zotero, version => 7.0.0-beta.48+0cab24fb8, os => Windows 10.0 22631, locale => zh-CN, extensions => Translate for Zotero (1.1.0-21, extension), Awesome GPT (0.3.2, extension, disabled), Wandering File (0.2.8, extension, disabled), Easier Citation (0.4.2, extension, disabled), PDF Figure (0.1.2, extension, disabled), Night (0.1.0-2, extension, disabled), Jasminum (1.0.0-6, extension, disabled), Del Item With Attachment (0.2.4, extension, disabled), Crush Reference (0.6.4, extension, disabled), Ethereal Style (3.1.9, extension, disabled), Better Notes for Zotero (1.1.4-31, extension, disabled), Zotero Addons (1.3.1, extension, disabled), Better BibTex for Zotero (6.7.136, extension, disabled), Linter for Zotero (1.6.9, extension, disabled)
(3)(+0061273): [Translate for Zotero] runTranslationTask {}

(3)(+0000004): [Translate for Zotero] {"id":"Z53C088J-1698979752993","type":"text","raw":"We placed single cells from a human KRAS/NRAS/BRAF wild-type, microsatellite-unstable CRC cell line, HCA-7, into three-dimensional (3D) culture in type-1 collagen to derive a cell line from colonies with cystic morphology, which we designate","result":"","audio":[],"service":"niutranspro","candidateServices":[],"itemId":521,"status":"processing","extraTasks":[],"langfrom":"en","langto":"zh-CN","secret":"dd963a94cb1ac615c60754a3a665f1a7"}

(3)(+0000000): HTTP POST "{"from":"en","to":"zh","apikey":"dd963a94cb1ac615c60754a3a665f1a7","dictNo":"","memoryNo":"","source":"zotero","src_text":"We placed single cells from a human KRAS/NRAS/BRAF wild-type, microsatellite-unstable CRC cell line, HCA-7, into three-dimensional (3D) culture in type-1 collagen to derive a cell line from colonies with cystic morphology, which we designate"}" to http://api.niutrans.com/NiuTransServer/translation

(3)(+0000926): HTTP POST http://api.niutrans.com/NiuTransServer/translation succeeded with 200

(3)(+0003901): [Translate for Zotero] runTranslationTask {}

(3)(+0000003): [Translate for Zotero] {"id":"K1VItgzl-1698979757825","type":"text","raw":"RESULTS Establish","result":"","audio":[],"service":"niutranspro","candidateServices":[],"itemId":521,"status":"processing","extraTasks":[],"langfrom":"en","langto":"zh-CN","secret":"dd963a94cb1ac615c60754a3a665f1a7"}

(3)(+0000000): HTTP POST "{"from":"en","to":"zh","apikey":"dd963a94cb1ac615c60754a3a665f1a7","dictNo":"","memoryNo":"","source":"zotero","src_text":"RESULTS Establish"}" to http://api.niutrans.com/NiuTransServer/translation

(3)(+0000124): HTTP POST http://api.niutrans.com/NiuTransServer/translation succeeded with 200

(3)(+0002996): [Translate for Zotero] runTranslationTask {}

(3)(+0000002): [Translate for Zotero] {"id":"ohlswf91-1698979760947","type":"text","raw":"from a human KRAS/NRAS/BRAF wild-type, microsatellite-unstable CR","result":"","audio":[],"service":"niutranspro","candidateServices":[],"itemId":521,"status":"processing","extraTasks":[],"langfrom":"en","langto":"zh-CN","secret":"dd963a94cb1ac615c60754a3a665f1a7"}

(3)(+0000000): HTTP POST "{"from":"en","to":"zh","apikey":"dd963a94cb1ac615c60754a3a665f1a7","dictNo":"","memoryNo":"","source":"zotero","src_text":"from a human KRAS/NRAS/BRAF wild-type, microsatellite-unstable CR"}" to http://api.niutrans.com/NiuTransServer/translation

(3)(+0000215): HTTP POST http://api.niutrans.com/NiuTransServer/translation succeeded with 200

(3)(+0018284): HTTP POST "error=true&errorData=1698979636145%09addons.xpi%09WARN%09Checking%20D%3A%5CProgram%20Files%5CZotero%5Cdistribution%5Cextensions%20for%20addons%0A1698979636190%09addons.xpi-utils%09WARN%09addMetadata%3A%20Add-on%20undefined%20is%20invalid%3A%20Error%3A%20Invalid%20addon%20ID%3A%20expected%20addon%20ID%20undefined%2C%20found%20undefined%20in%20manifest(resource%3A%2F%2Fgre%2Fmodules%2Faddons%2FXPIDatabase.jsm%3A2972%3A15)%20JS%20Stack%20trace%3A%20addMetadata%40XPIDatabase.jsm%3A2972%3A15%0AprocessFileChanges%40XPIDatabase.jsm%3A3433%3A26%0AcheckForChanges%40XPIProvider.jsm%3A3065%3A55%0Astartup%40XPIProvider.jsm%3A2492%3A12%0AcallProvider%40AddonManager.jsm%3A234%3A31%0A_startProvider%40AddonManager.jsm%3A542%3A17%0Astartup%40AddonManager.jsm%3A748%3A14%0Astartup%40AddonManager.jsm%3A3468%3A26%0Aobserve%40addonManager.js%3A78%3A29%0A%5BJavaScript%20Error%3A%20%22DEPRECATION%20WARNING%3A%20Calling%20FileUtils.getDir(...%2C%20...%2C%20true)%20causes%20main%20thread%20I%2FO%20and%20should%20be%20avoided%20especia…" (21987 chars) to https://repo.zotero.org/repo/report

(3)(+0002308): HTTP POST https://repo.zotero.org/repo/report succeeded with 200

(3)(+0024649): HTTP POST "error=true&errorData=1698979636145%09addons.xpi%09WARN%09Checking%20D%3A%5CProgram%20Files%5CZotero%5Cdistribution%5Cextensions%20for%20addons%0A1698979636190%09addons.xpi-utils%09WARN%09addMetadata%3A%20Add-on%20undefined%20is%20invalid%3A%20Error%3A%20Invalid%20addon%20ID%3A%20expected%20addon%20ID%20undefined%2C%20found%20undefined%20in%20manifest(resource%3A%2F%2Fgre%2Fmodules%2Faddons%2FXPIDatabase.jsm%3A2972%3A15)%20JS%20Stack%20trace%3A%20addMetadata%40XPIDatabase.jsm%3A2972%3A15%0AprocessFileChanges%40XPIDatabase.jsm%3A3433%3A26%0AcheckForChanges%40XPIProvider.jsm%3A3065%3A55%0Astartup%40XPIProvider.jsm%3A2492%3A12%0AcallProvider%40AddonManager.jsm%3A234%3A31%0A_startProvider%40AddonManager.jsm%3A542%3A17%0Astartup%40AddonManager.jsm%3A748%3A14%0Astartup%40AddonManager.jsm%3A3468%3A26%0Aobserve%40addonManager.js%3A78%3A29%0A%5BJavaScript%20Error%3A%20%22DEPRECATION%20WARNING%3A%20Calling%20FileUtils.getDir(...%2C%20...%2C%20true)%20causes%20main%20thread%20I%2FO%20and%20should%20be%20avoided%20especia…" (21987 chars) to https://repo.zotero.org/repo/report

(3)(+0000789): HTTP POST https://repo.zotero.org/repo/report succeeded with 200

**Comment by easypickings** [comment]
Same problem on macOS

**Comment by gaojunyang666** [comment]
我也遇到了这个问题，这个功能是非常好用的，希望作者大大可以尽快修复

**Comment by dyc610** [comment]
zotero 7 最新版同样的问题，希望作者尽快修复！非常感谢！

**Comment by gaojunyang666** [comment]
尊敬的作者大大，请您修复一下这个问题

**Comment by dklsgui** [comment]
目前1.1.0-18这个功能还能使用，后面几个版本好像都不能使用了

**Comment by gaojunyang666** [comment]
> 目前1.1.0-18这个功能还能使用，后面几个版本好像都不能使用了

谢谢您的提醒
求作者大大尽快修复呀

**Comment by NomajYu** [comment]
同样的问题。顺便借楼问一下，问一下有人知道zotero如何跨页选取文字并且高亮吗？分两段有点蠢。

**Comment by LY-must-win** [comment]
我也遇到同样的问题，有解决的艾特我一下

**Comment by zbsun-code** [comment]
同样的问题，1.1.0-25，zotero 7

**Comment by Lyn6969** [comment]
有没有临时的解决方案？

**Comment by Lyn6969** [comment]
> 可以改成长按才执行拼接吗？Windows 经常会使用到 alt + tab 这样的快捷键，切一下窗口就变成拼接模式。

就是长按，松开就不拼了
