### ISSUE TITLE
chatgpt 翻译服务不可用

### ISSUE THREAD

**Issue by lily-99** [windingwind/zotero-pdf-translate#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macOS 13.2.1
- Zotero Version: 6.0.30
- Plugin Version: zotero-pdf-translate v1.0.25

### Describe the feature request

I have entered the correct chatgpt key, but the zotero-pdf-translate plugin always pops up that the service is not available.I tried using Tencent's translation and it worked.May I ask what should be the problem?

### Describe the solution you'd like

I would like to use chatgpt translation service.

**Comment by windingwind** [comment]
We need more details.

**Comment by lily-99** [comment]
![Snipaste_2023-11-04_14-18-15](https://github.com/windingwind/zotero-pdf-translate/assets/71930631/2581752e-ea43-47e2-8ffe-5bf9ea755fff)
![Snipaste_2023-11-04_14-16-40](https://github.com/windingwind/zotero-pdf-translate/assets/71930631/cb1320d7-ba62-4abc-ab0c-f582f5498405)

**Comment by windingwind** [comment]
You are not able to access openAI server. Please check your internet environment.

**Comment by lily-99** [comment]
It's okay to access chatGPT(https://chat.openai.com) through the website, but not able to API- secret.

**Comment by lily-99** [comment]
It's okay to access chatGPT(https://chat.openai.com/) through the website, but not able to access through API key.

**Comment by lily-99** [comment]
I've solved it, thanks.
