### ISSUE TITLE
人在国外，输入了可用的chatgpt密钥，但是依旧无法使用翻译

### ISSUE THREAD

**Issue by Nomalhaut001** [windingwind/zotero-pdf-translate#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 6.0.3
- Plugin Version:1.0.22

### Describe the feature request

<img width="495" alt="屏幕截图 2023-11-06 160517" src="https://github.com/windingwind/zotero-pdf-translate/assets/145206073/0c7d69f3-f2f6-4b90-becb-3ae1eaad8b01">
<img width="464" alt="屏幕截图 2023-11-06 160552" src="https://github.com/windingwind/zotero-pdf-translate/assets/145206073/f206a363-d64d-4fbf-b78f-5804dcd76684">
如图所示，api key显示可用，但是翻译依旧报错。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
insufficient quota意思是余额不足。
