### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by galanz01** [windingwind/zotero-pdf-translate#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows 11 22H2
- Zotero Version: 7.0.0-beta.49+1bb6722c4 (64-bit)
- Plugin Version: 1.1.0-20; 1.1.0-21均试过

### Describe the bug

忽然所有的翻译均无法使用，不管是需要使用API的还是不需要使用API的，都是选中句子之后就出现句子原文，但是不翻译成中文。试过卸载之后重装，关掉zotero之后再打开等，但是都无法使用。

### Debug Output

1699350587611	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "this._pdfThumbnails is undefined" {file: "resource://zotero/reader/reader.js" line: 26583}]

[JavaScript Error: "TypeError: Zotero.ZoteroStyle.data.views is undefined" {file: "jar:file:///C:/Users/ixiur/AppData/Roaming/Zotero/Zotero/Profiles/lmibrn56.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 147839}]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "Download request 1/2C9EGT5T failed"]

[JavaScript Error: "您的 WebDAV 服务器对 GET 请求返回了 HTTP 403 错误。

如果您频繁收到此消息，请检查您的 WebDAV 服务器设置，或联系 WebDAV 服务器的管理员。

网址: https://axi84%40163%2Ecom:********@dav.jianguoyun.com/dav/zotero/2C9EGT5T.zip" {file: "chrome://zotero/content/xpcom/storage/webdav.js" line: 1496}]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\ixiur\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "referenceNode is null" {file: "jar:file:///C:/Users/ixiur/AppData/Roaming/Zotero/Zotero/Profiles/lmibrn56.default/extensions/zoterogpt@polygon.org.xpi!/chrome/content/scripts/zoterogpt.js" line: 73997}]

[JavaScript Error: "referenceNode is null" {file: "jar:file:///C:/Users/ixiur/AppData/Roaming/Zotero/Zotero/Profiles/lmibrn56.default/extensions/zoterofigure@polygon.org.xpi!/chrome/content/scripts/zoterofigure.js" line: 970}]

[JavaScript Error: "this._id(...) is null" {file: "chrome://zotero/content/elements/relatedBox.js" line: 131}]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "WebSocket connection closed: 1006 "]

appName => Zotero, version => 7.0.0-beta.49+1bb6722c4, os => Windows 10.0 22621, locale => zh-CN, extensions => Jasminum (1.0.0-6, extension), Crush Reference (0.6.3, extension), Awesome GPT (0.3.2, extension), PDF Figure (0.1.2, extension), Better Notes for Zotero (1.1.4-28, extension), Ethereal Style (3.2.5, extension), Translate for Zotero (1.1.0-20, extension), Duplicates Merger for Zotero (1.1.5, extension, disabled), Green Frog (0.16.02, extension, disabled)

(3)(+0406947): [Translate for Zotero] runTranslationTask {"noCheckZoteroItemLanguage":true}

(3)(+0000003): [Translate for Zotero] {"id":"u6Oi8Hp3-1699350687060","type":"text","raw":"Search Strategy We conducted a literature s","result":"","audio":[],"service":"google","candidateServices":[],"itemId":6126,"status":"processing","extraTasks":[],"langfrom":"zh","langto":"zh-CN","secret":""}

(3)(+0000001): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=702520.822348&q=Search%20Strategy%20We%20conducted%20a%20literature%20s

(5)(+0000006): CookieSandbox: Being paranoid about channel for translate.google.com

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to translate.google.com

(5)(+0000920): CookieSandbox: Being paranoid about channel for translate.google.com

(5)(+0000001): CookieSandbox: Not tracking received cookies for translate.google.com

(3)(+0000000): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=702520.822348&q=Search%20Strategy%20We%20conducted%20a%20literature%20s succeeded with 200

(3)(+0005516): [Translate for Zotero] runTranslationTask {"noCheckZoteroItemLanguage":true}

(3)(+0000008): [Translate for Zotero] {"id":"JSpytHMG-1699351000666","type":"text","raw":"Search Strategy","result":"","audio":[],"service":"google","candidateServices":[],"itemId":6126,"status":"processing","extraTasks":[],"langfrom":"zh","langto":"zh-CN","secret":""}

(3)(+0000002): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=604354.986294&q=Search%20Strategy

(5)(+0000011): CookieSandbox: Being paranoid about channel for translate.google.com

(5)(+0000000): CookieSandbox: Cleared cookies to be sent to translate.google.com

(5)(+0000242): CookieSandbox: Being paranoid about channel for translate.google.com

(5)(+0000001): CookieSandbox: Not tracking received cookies for translate.google.com

(3)(+0000001): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=604354.986294&q=Search%20Strategy succeeded with 200

(3)(+0007765): [Translate for Zotero] runTranslationTask {"noCheckZoteroItemLanguage":true}

(3)(+0000002): [Translate for Zotero] skipped empty

(3)(+0005344): [Translate for Zotero] runTranslationTask {"noCheckZoteroItemLanguage":true}

(3)(+0000002): [Translate for Zotero] skipped empty

(3)(+0004378): [Translate for Zotero] runTranslationTask {"noCheckZoteroItemLanguage":true}

(3)(+0000010): [Translate for Zotero] {"id":"DAOqlBBZ-1699351018365","type":"text","raw":"Search Strategy","result":"","audio":[],"service":"google","candidateServices":[],"itemId":6126,"status":"processing","extraTasks":[],"langfrom":"zh","langto":"zh-CN","secret":""}

(3)(+0000001): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=604354.986294&q=Search%20Strategy

(5)(+0000015): CookieSandbox: Being paranoid about channel for translate.google.com

(5)(+0000000): CookieSandbox: Cleared cookies to be sent to translate.google.com

(5)(+0000238): CookieSandbox: Being paranoid about channel for translate.google.com

(5)(+0000001): CookieSandbox: Not tracking received cookies for translate.google.com

(3)(+0000000): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=604354.986294&q=Search%20Strategy succeeded with 200

(1)(+0010924): WebSocket connection closed: 1006

(3)(+0000002): Delaying 5000 ms

(3)(+0005014): Connecting to streaming server at wss://stream.zotero.org/

(5)(+0000008): CookieSandbox: Being paranoid about channel for stream.zotero.org

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to stream.zotero.org

(5)(+0000764): CookieSandbox: Being paranoid about channel for ocsp.r2m01.amazontrust.com

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to ocsp.r2m01.amazontrust.com

(5)(+0000596): CookieSandbox: Being paranoid about channel for ocsp.r2m01.amazontrust.com

(5)(+0000002): CookieSandbox: No Set-Cookie header received for ocsp.r2m01.amazontrust.com

(5)(+0008046): CookieSandbox: Being paranoid about channel for stream.zotero.org

(5)(+0000001): CookieSandbox: No Set-Cookie header received for stream.zotero.org

(3)(+0000002): WebSocket connection opened

(3)(+0000001): WebSocket message: {"event":"connected","retry":10000}

(3)(+0000010): WebSocket message send: {"action":"createSubscriptions","subscriptions":[{"apiKey":"********"},{"topics":["styles","translators"]}]}

**Comment by galanz01** [comment]
![3](https://github.com/windingwind/zotero-pdf-translate/assets/59480437/98a40c86-c1f0-475f-9a99-655930a21244)
![4](https://github.com/windingwind/zotero-pdf-translate/assets/59480437/43099501-3c7a-4ed4-8424-c0c9be0b3f65)
补充一下，刚刚发现在PDF阅读界面我的翻译中被翻译语言Chinese无法切换成为其它的语言，但是如果选择将Chinese翻译为其它语言可以选，也可以翻译。在翻译设置界面我设置的默认被翻译语言是English，但是阅读界面就一直是Chinese，无法修改。

**Comment by windingwind** [comment]
需要使用prerelease-21产生的debug output

**Comment by galanz01** [comment]
> 需要使用prerelease-21产生的debug output

重新装回prerelease-21之后又好了。多谢回复。请关闭这个issue吧。
