### ISSUE TITLE
[Bug] zotero 7 中，划词后显示朗读的喇叭，但是无法朗读

### ISSUE THREAD

**Issue by 15933353173** [windingwind/zotero-pdf-translate#637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0
- Plugin Version:1.0.254

### Describe the bug

zotero 7 中，划词后显示朗读的喇叭，但是无法朗读

### Debug Output

无

**Comment by Echoiland** [comment]
具有同样的问题，在bing词典无法发音，尽管具有2个喇叭图标。在海词词典选择单个词语选择是可以发音的，并且具有4个喇叭。

**Comment by 353600van** [comment]
你好，我想问一下这个问题解决了吗

**Comment by April040** [comment]
我也遇到了同样问题，希望能尽快解决一下 I have encountered the same problem. hope it can be solved soon

**Comment by JinchaoC** [comment]
zotero6下有一样的问题

**Comment by knightpalace** [comment]
希望大佬在解决此问题的时候，可以考虑在右侧边栏也加一个发音按钮，方便读者自己查单词使用~

**Comment by iloubin** [comment]
同样的问题，无法朗读。


无奈我是配合欧路词典使用朗读。
