### ISSUE TITLE
[Bug] 侧边栏无“翻译”选项，卸载重装后好。但zotero关闭重启后，侧边栏“翻译”又消失

### ISSUE THREAD

**Issue by kijlk** [windingwind/zotero-pdf-translate#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  MacOS 14.1
- Zotero Version: 6.0.30
- Plugin Version: 1.0.25

### Describe the bug

与 #123 问题类似，但是pdf文件有父条目。
问题描述：
在zotero重启后翻译结果只有弹窗，没有侧边栏内容；
多次重启zotero无好转。
尝试卸载translate插件重装，重装后侧边栏出现“翻译”，但是一旦zotero关闭再重启，侧边栏的翻译就会消失。
<img width="1017" alt="截屏2023-11-08 13 37 05" src="https://github.com/windingwind/zotero-pdf-translate/assets/90626408/9c57f31f-6562-4015-884b-1a4a23da9d3b">

### Debug Output

无

**Comment by kijlk** [comment]
重启几次之后离奇好了...

**Comment by duolanda** [comment]
我也遇到这个问题了，多重启几次之后就会好吗

**Comment by kijlk** [comment]
> 我也遇到这个问题了，多重启几次之后就会好吗

这个问题在我这里是由于mac的关闭机制引起的。
具体原因是我点击右上角的关闭按钮关闭，但实际上并没有完全关闭程序，但是translate插件好像因此关闭了。
如果你选择使用command+q完全关闭程序，再打开zotero就能够解决这个问题。不过一旦点击右上角的关闭，这个问题仍然会出现。

**Comment by duolanda** [comment]
> > 我也遇到这个问题了，多重启几次之后就会好吗
> 
> 这个问题在我这里是由于mac的关闭机制引起的。 具体原因是我点击右上角的关闭按钮关闭，但实际上并没有完全关闭程序，但是translate插件好像因此关闭了。 如果你选择使用command+q完全关闭程序，再打开zotero就能够解决这个问题。不过一旦点击右上角的关闭，这个问题仍然会出现。

同样的现象在我这里复现成功。我平时习惯用 command+w 关闭窗口，所以经常会出现侧栏翻译消失的情况，按照你说的用 command+q 彻底关闭再重启后确实又出现了，非常感谢！
