### ISSUE TITLE
[Bug] IP was blocked without any abnormal operation, with caution saying "There are abnormal requests from your IP **"

### ISSUE THREAD

**Issue by tanxiaoke** [windingwind/zotero-pdf-translate#64]
**Describe the bug**

**To Reproduce**

When I select the text, a caution occurred, saying "There are abnormal requests from your IP **. Your IP has been listed into blacklist". I have no idea what happened to me, since I had just use this plug (v0.3.16) very normally for only 1 day, without any abnormal operation.  

**Expected behavior**

Considering your plug is very elegant and more effective, so could you please help tackle with this issue? (The IP address was hidden in the pic , if you need this, I will send you in a proper way). Thank you for your plug and attention! I will appreciate it very much if you can kindly help me out.

**Screenshots**

![image](https://user-images.githubusercontent.com/94229328/161292811-e93f12ae-7752-49b1-a21f-0e870f9c62a3.png)

**Environment**
 - OS: Windows
 - Zotero Version V6.0
 - Addon Version V0.3.16

**Additional context**

One  thing I have to mention, that is, during reading and translating using this plug, I tried to update the Zotero IF Pro Max v.2.5.5 (from 青柠). Then I have confirm this issue with it's developer, and his reply was "nothing with IF plug". So I turn to seek help from you.

**Comment by windingwind** [comment]
See #57

**Comment by tanxiaoke** [comment]
Got it! Thank you for your rapid reply! You are so kind. I'll consult 小牛.

**Comment by windingwind** [comment]
Asking service provider to unblock your IP is not a good solution. You should use the official Niu Trans with secret. 
Using the free Niu(trial) can make your IP be blocked again.

**Comment by tanxiaoke** [comment]
开发者您好：我已与小牛客服沟通，对方回复说即使是付费获取密钥购买流量也会被封掉，对方请我反馈给您“您联系开发者更改下调用我们接口的地址，就可以使用。当前情况下，即使付费购买流量，也会被系统封掉”。刚刚咨询完，向您反馈下。谢谢

**Comment by tanxiaoke** [comment]
昨天确实选用了“小牛试用”。不过，如果选其他接口，他们不长臂拦截。我再用其他合规申请的api吧  谢谢您的回复 后台封禁已经解除了 我后面正规使用

**Comment by windingwind** [comment]
正如我所说，我提供了两套接口，分别是免费的试用以及官方文档的付费接口。如客服所说，试用接口不是正规调用；正规调用方法是选择`小牛翻译*`并正确填写secret。

**Comment by Qitingshe** [comment]
有两个小需求，
1. 能否提供辅助按键进行自动翻译，目前情况下使用自动翻译，会造成任何情况下鼠标选中文本都会请求api进行翻译，如果可以的话，可以增加功能：按住shift键，之后选中文本进行自动翻译，可以避免不必要的请求
2. 
<img width="363" alt="图片" src="https://user-images.githubusercontent.com/11593949/161373373-9305312d-80df-4473-976a-ed92f7404a8c.png">
该界面上的engine配置界面其实不是很常用，建议仅保留原文文本框和翻译文本框，更加简洁一点
