### ISSUE TITLE
[Bug] 新注册的百度，设置密钥之后，为啥还是不能用？

### ISSUE THREAD

**Issue by penglian714** [windingwind/zotero-pdf-translate#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: mac os ventura 13.6.1
- Zotero Version: 6.0.30
- Plugin Version: 1.0.25
<img width="584" alt="截屏2023-11-08 23 42 38" src="https://github.com/windingwind/zotero-pdf-translate/assets/150264742/3442a463-be55-46c6-ae90-c8ed151a7f89">
<img width="270" alt="截屏2023-11-08 23 47 06" src="https://github.com/windingwind/zotero-pdf-translate/assets/150264742/5d9de473-91ab-4d45-8b81-fd29fc872156">

### Describe the bug

今天刚注册的百度，不存在需要充值的情况。
阅读了几遍密钥设置方法，是填入完整的 ID#密钥，到这一步都跟着做了，但还是不行。
不知道是哪出了问题，求解。

### Debug Output

[JavaScript Error: "IndexedDB Maintenance finished with error: NS_ERROR_NOT_AVAILABLE: ActorsParent.cpp:16691"]

version => 6.0.30, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => zh-CN, appName => Zotero, appVersion => 6.0.30, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.30, extension), Zotero Word for Mac Integration (6.0.10.SA.6.0.30, extension), Zotero PDF Translate (1.0.25, extension)

(3)(+0231691): [Zotero PDF Translate] {}

(3)(+0000109): [Zotero PDF Translate] {}

(3)(+0030350): Checking for unprocessed full-text content

(4)(+0000002): SELECT itemID FROM fulltextItems WHERE synced=2

(3)(+0000003): No unprocessed full-text content found

(3)(+0000001): Unregistering full-text content processor idle observer

(3)(+0000002): Stopping full-text content processor

(3)(+0269990): Backing up database 'zotero'

(4)(+0000005): PRAGMA main.locking_mode=NORMAL

(4)(+0000019): PRAGMA main.locking_mode=EXCLUSIVE

(3)(+0000022): Backed up to zotero.sqlite.bak

(4)(+0004956): SELECT itemID FROM items JOIN deletedItems USING (itemID) WHERE libraryID=? AND dateDeleted <= DATE('NOW', '-30 DAYS') [1]

**Comment by windingwind** [comment]
翻译目标语言有误。选择`Chinese`

**Comment by 1289183863** [comment]
我也遇到了相同问题

**Comment by 1289183863** [comment]
请问您解决了嘛？
