### ISSUE TITLE
[Bug] crtl T 快捷键似乎在最新版本失效了

### ISSUE THREAD

**Issue by z2332677** [windingwind/zotero-pdf-translate#641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOs 14.1
- Zotero Version:7.0.0-beta.49+1bb6722c4 
- Plugin Version:1.1.0-21

### Describe the bug

crtl T 快捷键似乎在最新版本失效了

### Debug Output

1699508413869	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1699508414465	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///Users/edan/Library/Application%20Support/Zotero/Profiles/ughn6yq6.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 6879}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///Users/edan/Library/Application%20Support/Zotero/Profiles/ughn6yq6.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 6879}]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 655}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:655:7

Warning: attempting to write 7998 bytes to preference extensions.zotero.zoteroif.notesmetadatatemplate. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.

[JavaScript Error: "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setIntPref]" {file: "chrome://zotero/content/xpcom/plugins.js" line: 307}]

1699508443888	addons.xpi-utils	WARN	disabling legacy extension zotfile@columbia.edu

1699508443891	addons.xpi-utils	WARN	disabling legacy extension jasminum@linxzh.com

[JavaScript Error: "NotFoundError: Could not get children of file(/Users/edan/Library/Application Support/Zotero/Crash Reports/events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 655}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:655:7

appName => Zotero, version => 7.0.0-beta.49+1bb6722c4, os => macOS 14.1, locale => zh-CN, extensions => Zotero Reference (0.5.8, extension), Zotero Better Notes (1.0.4, extension), Actions and Tags for Zotero (1.0.0-23, extension), Magic for Zotero (1.3.1, extension), Zotero One (5.2.8, extension), Awesome GPT (0.4.6.1, extension), Ethereal Style (3.2.6, extension), Translate for Zotero (1.1.0-21, extension), ZotFile (5.1.2, extension, disabled), Jasminum (0.2.7, extension, disabled), Wandering File (0.2.8, extension, disabled), PDF Figure (0.1.2, extension, disabled), Linter for Zotero (1.6.10, extension, disabled)

**Comment by yzy1228682367** [comment]
是的，我好像也有这个问题。

https://github.com/windingwind/zotero-pdf-translate/assets/50101175/19f3073a-c3e3-4d88-916f-38eb03770591
