### ISSUE TITLE
The add-on "%S"could not be installed.It may be incompatible with this version of Zotero.[Bug] 

### ISSUE THREAD

**Issue by yanyu2015** [windingwind/zotero-pdf-translate#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

当前的zotero版本是3.0.30
之前用着好好的，昨天误触删除后，就无法重新按照此插件。
安装xpi文件后提示：
```
The add-on "%S"could not be installed.It may be incompatible with this version of Zotero.
```

### Debug Output

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://%40126%2Ecom:****@dav.jianguoyun.com/dav/zotero/
Line Number 1, Column 1:" {file: "https://%40126%2Ecom:****@dav.jianguoyun.com/dav/zotero/" line: 1}]

[JavaScript Error: "1699758396643	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1699758396643	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

[JavaScript Error: "1699758403078	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1699758403079	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

version => 6.0.30, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.30, extensions => Zotero Word for Windows Integration (6.0.3.SA.6.0.30, extension), Zotero Style (2.6.9, extension, disabled), ZotFile (5.1.3, extension, disabled), Zotero Tag (0.3.0, extension, disabled), DOI Manager (1.4.2, extension, disabled), Zotero Debug Bridge (2.0.0, extension, disabled), Zutilo Utility for Zotero (3.10.0, extension, disabled), Better BibTex for Zotero (6.7.136, extension, disabled), Zotero LibreOffice Integration (6.0.4.SA.6.0.30, extension, disabled)

### Anything else?

无

**Comment by yteshi** [comment]
Hi, I faced the same error but couldn't find a solution. Can you please help me solve this issue?

**Comment by windingwind** [comment]
see readme

**Comment by yanyu2015** [comment]
> Hi, I faced the same error but couldn't find a solution. Can you please help me solve this issue?

 I upgrade to Zotero 7 and install the respective plugin. However, I would advise you to carefully consider the decision of upgrading to Zotero 7.
