### ISSUE TITLE
可以在插件中添加锁定翻译的按钮吗[Bug] 

### ISSUE THREAD

**Issue by GXJ-Githuboxueji** [windingwind/zotero-pdf-translate#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win11 23H2
- Zotero Version: 7 beta
- Plugin Version:1.1.0-20

### Describe the bug

就是我一般默认开启自动翻译，但是也希望能在旁边有个自动锁定的按钮让我自行开与关。如果可以，辛苦开发者加上，好嘛。

### Debug Output

谢谢

### Anything else?

无

**Comment by windingwind** [comment]
1. 什么叫自动锁定
2. 侧边栏本来就有选框可以自己打开或关闭自动翻译

**Comment by GXJ-Githuboxueji** [comment]
我错了…👮👮



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月12日(周日) 中午11:47
收件人: ***@***.***&gt;;
抄送: "Gao ***@***.******@***.***&gt;;
主题: Re: [windingwind/zotero-pdf-translate] 可以在插件中添加锁定翻译的按钮吗[Bug]  (Issue #643)




  
什么叫自动锁定
 
侧边栏本来就有选框可以自己打开或关闭自动翻译

**Comment by windingwind** [comment]
不是指责，只是我没看懂你的功能请求的意思。消息太多不能周到回复请谅解
如果该请求无需解决我将关闭issue。
