### ISSUE TITLE
[Bug] the preferences page and sidebar doesn't show this plugin

### ISSUE THREAD

**Issue by jadezz0802** [windingwind/zotero-pdf-translate#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: mac sonoma 14.1.1
- Zotero Version: 6.0.3
- Plugin Version:1.0.25

### Describe the bug

The preferences page and sidebar doesn't show this plugin.Restarting zotero and reinstalling the plugin didn't help.<img width="939" alt="截屏2023-11-20 18 19 23" src="https://github.com/windingwind/zotero-pdf-translate/assets/151519096/7c7f58ec-31e1-4de9-9eba-dfa22436df36">
<img width="388" alt="截屏2023-11-20 18 23 30" src="https://github.com/windingwind/zotero-pdf-translate/assets/151519096/f749118f-bb81-4b77-9ae6-7ed13f8a588a">
<img width="760" alt="截屏2023-11-20 18 21 04" src="https://github.com/windingwind/zotero-pdf-translate/assets/151519096/bcbef0bd-c1bf-4c39-be37-10d4903afb32">

### Debug Output

<img width="165" alt="截屏2023-11-20 18 42 01" src="https://github.com/windingwind/zotero-pdf-translate/assets/151519096/940a5ab1-0725-4c13-ba9a-f900fd198a3b">
can't upload the files

D1579001399
<img width="999" alt="截屏2023-11-20 18 42 55" src="https://github.com/windingwind/zotero-pdf-translate/assets/151519096/172fb551-3b7b-4fbf-9aa3-c10102857fa2">

**Comment by windingwind** [comment]
Goto menu -> Zotero -> Preference -> Advanced -> Config Editor, search for `secretObj` and reset it to empty. Then restart Zotero.

**Comment by jadezz0802** [comment]
> Goto menu -> Zotero -> Preference -> Advanced -> Config Editor, search for `secretObj` and reset it to empty. Then restart Zotero.

It works!!! But the sidebar has sth. wrong...<img width="1288" alt="截屏2023-11-20 19 54 11" src="https://github.com/windingwind/zotero-pdf-translate/assets/151519096/5fc06cc7-9b61-4f07-92a0-cad63da22ba0">

**Comment by windingwind** [comment]
Please check the settings of UI of this plugin. Did you disabled all other panels but the transaltion source?
