### ISSUE TITLE
[Bug]  Linux Zotero 7 not compatible.

### ISSUE THREAD

**Issue by LiukDiihMieu** [windingwind/zotero-pdf-translate#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Ubuntu 22.04 LTS
- Zotero Version: 7.0.0 beta.39
- Plugin Version: Pre-release 1.1.0-21

### Describe the bug

In Edit > Settings, I cannot see any panel for this addon. When using windows version I can see a zotero-translate tag, but on Ubuntu nothing.

### Debug Output

1700553068634	addons.xpi	WARN	Checking /snap/zotero-snap/67/distribution/extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1700553069697	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "TypeError: Zotero.Reader.registerEventListener is not a function" {file: "jar:file:///home/myself/snap/zotero-snap/common/.zotero/zotero/j5pinza8.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 16056}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NotFoundError: Could not get children of file(/home/myself/snap/zotero-snap/common/.zotero/zotero/Crash Reports/events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.39+ecba25be0, os => Linux 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2, locale => en-US, extensions => Translate for Zotero (1.1.0-21, extension), Awesome GPT (0.3.2, extension, disabled), Night (0.1.0-2, extension, disabled)

**Comment by windingwind** [comment]
Update your Zotero.
