### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by reem97sj** [windingwind/zotero-pdf-translate#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 11
- Zotero Version:  6
- Plugin Version:

### Describe the bug

![image](https://github.com/windingwind/zotero-pdf-translate/assets/150335203/600db993-05a5-4c59-8901-eade9e90b81d)

I am a user from the Kingdom of Saudi Arabia. When I want to use the "openl.io" translator, it does not work for me even though I put the key code in it. What is the problem?

### Debug Output

![image](https://github.com/windingwind/zotero-pdf-translate/assets/150335203/600db993-05a5-4c59-8901-eade9e90b81d)

I am a user from the Kingdom of Saudi Arabia. When I want to use the "openl.io" translator, it does not work for me even though I put the key code in it. What is the problem?

### Anything else?

no

**Comment by windingwind** [comment]
The `openl` we implemented in this plugin is https://openl.club/, which I think is a different service from openl.io. I just realized that these two are so similar!

You could try Google, which is OK for most of the languages.
