### ISSUE TITLE
[Bug] 请问翻译标题后如何让条目列表中依然显示英文原文

### ISSUE THREAD

**Issue by YuDi0-0** [windingwind/zotero-pdf-translate#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

OS: Windows 11 22H2
Zotero Version: 7.0.0
Plugin Version: 1.0.0

### Describe the bug

在条目列表右键进行标题翻译后，条目列表中的的标题名称就自动变成了中文，请问如何调回英文，使保持仅在右侧信息栏显示翻译结果？
![微信图片_20231123232613](https://github.com/windingwind/zotero-pdf-translate/assets/73322947/5e77b916-6b8d-446f-ae47-c47586ec607f)

### Debug Output

.

**Comment by windingwind** [comment]
please update plugin

**Comment by YuDi0-0** [comment]
> please update plugin

插件版本是1.1.0-21，应该是最新的了，是不是我编辑器里的设置不对？我记得以前zotero6的时候好像右键可以选择显示翻译标题还是原本标题，现在的右键里面没有这个选项了

**Comment by windingwind** [comment]
最新版不会改变标题列显示内容，与本插件无关。依次禁用其他所有插件并尝试确定是哪个引起的
