### ISSUE TITLE
[Bug] Hello, I don't know why I can't pronounce the words in my translation, and I have chosen a translation dictionary that can be pronounced

### ISSUE THREAD

**Issue by 353600van** [windingwind/zotero-pdf-translate#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 6.0.30
- Plugin Version:1.0.25

### Describe the bug

![A9R@P2Q 6SBXWIHJC 9$U}Y](https://github.com/windingwind/zotero-pdf-translate/assets/149308453/477f8dbc-4310-4b4f-b2c4-1a16279d5e0e)
![5LSZDH5}ZUIIY}_GZP8_ D](https://github.com/windingwind/zotero-pdf-translate/assets/149308453/108ee2dd-0de8-48a3-b570-bd7a89be23b4)

Clicking the pronunciation button has no response，

### Debug Output

提交。。。
清楚
[JavaScript 错误：“上传请求 1/2CPGS2GW 失败”]

[JavaScript Error： “您的 Zotero 文件存储配额已经达到，有些文件将不能上传。Zotero 的其他数据将继续同步到 Zotero 服务器。

在 zotero.org 的帐户设置里查看更多的存储选项。

牛雪琦_Xueqi NIU_2023_内陆水体 strongCHsub4-sub-strong 冒泡排放研究进展.pdf （1404 KB）“]

[JavaScript 错误：“上传请求 1/327ZCW5I 失败”]

[JavaScript Error： “您的 Zotero 文件存储配额已经达到，有些文件将不能上传。Zotero 的其他数据将继续同步到 Zotero 服务器。

在 zotero.org 的帐户设置里查看更多的存储选项。

于浩冉_2022_泸沽湖氮磷时空分布及内外源污染负荷研究.pdf （6597 KB）“]

版本 => 6.0.30，平台 => Win32，oscpu => Windows NT 10.0;WOW64，语言环境 => zh-CN，appName => Zotero，appVersion => 6.0.30，扩展名 => Zotero PDF 翻译（1.0.25，扩展名），Zotero IF（1.5.0，扩展名，禁用），Zotero Style（2.6.7，扩展名，禁用），ZotFile（5.1.2，扩展名，禁用），Zotero Tag（0.3.0，扩展名，禁用），Sci-Hub Plugin for Zotero（1.4.4，扩展名，禁用），Zotero LibreOffice 集成（6.0.4.SA.6.0.30，扩展名，禁用），Zotero Word for Windows集成（6.0.3.SA.6.0.30， 扩展，禁用）、Jasminum（0.2.8，扩展，禁用）、Zotero Better Notes（1.0.4，扩展，禁用）
(3)（+0007544）： [Zotero PDF翻译] {}

(3)（+0000001）： [Zotero PDF翻译] {}

(3)（+0000002）： [Zotero PDF翻译] {}

(3)（+0000000）： [Zotero PDF翻译] {}

(3)（+0000001）： [Zotero PDF翻译] {}

(3)（+0000034）： [Zotero PDF翻译] runTranslationTask {}

(3)（+0000005）： [Zotero PDF翻译] {“id”：“UlHYli75-1701053191585”，“type”：“text”，“raw”：“aquatic”，“result”：“”，“audio”：[]，“service”：“bingdict”，“candidateServices”：[“haici”]，“itemId”：525，“status”：“processing”，“extraTasks”：[]，“langfrom”：“zh-US”，“langto”：“zh-CN”，“secret”：“”}

(3)（+0000002）：HTTP GET https://cn.bing.com/dict/search?q=aquatic/

(3)（+0000399）：HTTP GET https://cn.bing.com/dict/search?q=aquatic/ 成功，显示 200

(3)（+0000015）： [Zotero PDF翻译] {}

(3)（+0000000）： [Zotero PDF翻译] {}

(3)（+0000001）： [Zotero PDF翻译] {}

(3)（+0000327）： [Zotero PDF翻译] [警告]创建未指定命名空间的元素样式。找到 multiply 命名空间匹配项。

(3)（+0000001）： [Zotero PDF翻译] {}

(3)（+0000369）： [Zotero PDF翻译] {}

(3)（+0001780）：安排下一次 Feed 更新

(4)(+0000001): SELECT （ case when lastCheck IS NULL THEN 0 ELSE strftime（'%s'， lastCheck） + refreshInterval * 60 - strftime（'%s'， 'now'） END ） AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY 下页检查 ASC 限制 1

(3)（+0000008）：没有自动更新的提要

(4)（+0000050）：从设置中选择 COUNT（*），其中 setting='mImport' AND key='cleanup'

**Comment by windingwind** [comment]
#637
