### ISSUE TITLE
[Bug] 正文中的翻译结果框中的内容偶尔无法复制

### ISSUE THREAD

**Issue by xba0** [windingwind/zotero-pdf-translate#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 6.0.30
- Plugin Version: 1.0.25

### Describe the bug

正文中的翻译框中的翻译结果偶尔无法部分选中并复制, 会复制完整的源文

### Debug Output

w

**Comment by windingwind** [comment]
鼠标在框内则复制翻译，鼠标在框外则复制原文
