### ISSUE TITLE
[Bug] 无法将条目标题切换为翻译后的中文

### ISSUE THREAD

**Issue by XinLi0111** [windingwind/zotero-pdf-translate#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11
- Zotero Version:  7.0.0-beta.52+2f8e536f2 (64-bit)
- Plugin Version: 1.1.0-22

### Describe the bug

帮助说可以切换“切换条目列表显示原标题/翻译后的标题。”之前的版本记得右键菜单有个选项，现在找不到了

### Debug Output

-

**Comment by windingwind** [comment]
最新版中移除，使用单独标题翻译列替代
