### ISSUE TITLE
is this a bug or some settings that i did not turn off [Bug] 

### ISSUE THREAD

**Issue by Horacejinhao** [windingwind/zotero-pdf-translate#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 14.0 (23A344)
- Zotero Version: 6.030
- Plugin Version: 1.0.25

### Describe the bug

the translation has been added to note, which is what i want. but the translation will automatic translate the highlight words agian and add it to the note again.
<img width="290" alt="截屏2023-12-11 14 16 18" src="https://github.com/windingwind/zotero-pdf-translate/assets/152418841/2e01043f-fc67-452a-84af-cfb2d1ca9073">

### Debug Output

1702274444563	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 461"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:461
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:471
parser()@resource://gre/modules/addons/AddonUpdateChecker.jsm:631
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:651
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:576

1702274445462	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 461"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:461
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:471
parser()@resource://gre/modules/addons/AddonUpdateChecker.jsm:631
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:651
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:576
onStopRequest()@standalone.js:64
openModalWindow()@jar:file:///Applications/Zotero.app/Contents/Resources/omni.ja!/components/nsPrompter.js:353
openPrompt()@jar:file:///Applications/Zotero.app/Contents/Resources/omni.ja!/components/nsPrompter.js:563
alert()@jar:file:///Applications/Zotero.app/Contents/Resources/omni.ja!/components/nsPrompter.js:612
alert()@jar:file:///Applications/Zotero.app/Contents/Resources/omni.ja!/components/nsPrompter.js:54
this.alert()@zotero.js:1198
observe()@standalone.js:940
installNotifyObservers()@resource://gre/modules/AddonManager.jsm:1894
startInstall()@resource://gre/modules/AddonManager.jsm:1904
installAddonFromAOM()@resource://gre/modules/AddonManager.jsm:2067
installAddonFromAOM()@resource://gre/modules/AddonManager.jsm:3548
onDrop/<()@extensions.js:3666
safeCall()@resource://gre/modules/AddonManager.jsm:177
makeSafe/<()@resource://gre/modules/AddonManager.jsm:192

No chrome package registered for chrome://zoteropdftranslate/content/icons/favicon.png

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///Users/horacejin/Library/Application%20Support/Zotero/Profiles/1txljlbc.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml
Line Number 6, Column 12:" {file: "jar:file:///Users/horacejin/Library/Application%20Support/Zotero/Profiles/1txljlbc.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml" line: 6 column: 12 source: "    <label><html:h2>&zotero.zoteropdftranslate.pref.general.label;</html:h2></label>"}]

[JavaScript Error: "TypeError: oldPane is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 820}]
_selectPane@chrome://zotero/content/bindings/preferences-mac.xml:820:36
observe@chrome://zotero/content/bindings/preferences-mac.xml:744:17

[JavaScript Error: "TypeError: oldPane is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 820}]
_selectPane@chrome://zotero/content/bindings/preferences-mac.xml:820:36
observe@chrome://zotero/content/bindings/preferences-mac.xml:744:17

[JavaScript Error: "TypeError: oldPane is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 820}]
_selectPane@chrome://zotero/content/bindings/preferences-mac.xml:820:36
observe@chrome://zotero/content/bindings/preferences-mac.xml:744:17

[JavaScript Error: "TypeError: oldPane is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 820}]
_selectPane@chrome://zotero/content/bindings/preferences-mac.xml:820:36
showPane@chrome://zotero/content/bindings/preferences-mac.xml:752:13
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1107:11

[JavaScript Error: "TypeError: oldPane is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 820}]
_selectPane@chrome://zotero/content/bindings/preferences-mac.xml:820:36
observe@chrome://zotero/content/bindings/preferences-mac.xml:744:17

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///Users/horacejin/Library/Application%20Support/Zotero/Profiles/1txljlbc.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml
Line Number 6, Column 12:" {file: "jar:file:///Users/horacejin/Library/Application%20Support/Zotero/Profiles/1txljlbc.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml" line: 6 column: 12 source: "    <label><html:h2>&zotero.zoteropdftranslate.pref.general.label;</html:h2></label>"}]

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1312:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblinput@chrome://zotero/content/bindings/preferences-mac.xml:1328:9

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblchange@chrome://zotero/content/bindings/preferences-mac.xml:1323:9

[JavaScript Error: "TypeError: oldPane is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 820}]
_selectPane@chrome://zotero/content/bindings/preferences-mac.xml:820:36
showPane@chrome://zotero/content/bindings/preferences-mac.xml:752:13
onxblcommand@chrome://zotero/content/bindings/preferences-mac.xml:1107:11

version => 6.0.30, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => zh-CN, appName => Zotero, appVersion => 6.0.30, extensions => Zotero PDF Translate (1.0.25, extension), Zotero LibreOffice Integration (6.0.4.SA.6.0.30, extension, disabled), Zotero Word for Mac Integration (6.0.10.SA.6.0.30, extension, disabled)

**Comment by windingwind** [comment]
#6
