### ISSUE TITLE
框选pdf文本后，无法翻译。

### ISSUE THREAD

**Issue by ZhengZhouBugMaker** [windingwind/zotero-pdf-translate#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win 10 22H2
- Zotero Version: 7.0.0-beta.53+969031a37 (64-bit)
- Plugin Version: 11-23 （prelease）

### Describe the bug

![Snipaste_2023-12-14_10-16-05](https://github.com/windingwind/zotero-pdf-translate/assets/118353983/dcc5d606-36ee-4ce8-9472-0333728504b0)
![Snipaste_2023-12-14_10-16-20](https://github.com/windingwind/zotero-pdf-translate/assets/118353983/8edeaeb9-cc41-4c1a-8df7-0a0d42473c65)
框选文字后无法翻译，尝试所有翻译api均有此问题。所框选英文词段，出现在翻译后的功能栏中。

### Debug Output

[Debug Output.txt](https://github.com/windingwind/zotero-pdf-translate/files/13667575/Debug.Output.txt)

**Comment by ZhengZhouBugMaker** [comment]
the add‘s version is Release 1.1.0-23（Pre-release） @windingwind

**Comment by windingwind** [comment]
Your `splitChar` is not correctly set.

<img width="800" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/33902321/40978777-1b06-4d61-a427-4bb107d8a874">

**Comment by ZhengZhouBugMaker** [comment]
WOW！The question is solved. Thank you @windingwind !
there is a another question.-----How to swap the location of two translation areas？
![Snipaste_2023-12-14_20-22-28](https://github.com/windingwind/zotero-pdf-translate/assets/118353983/fa8b9019-78e4-497c-a590-05b967974dea)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate?tab=readme-ov-file#user-interface

**Comment by ZhengZhouBugMaker** [comment]
thank you ! I am all gratitude.
