### ISSUE TITLE
[Feature]Shortcuts & UI settings

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-pdf-translate#66]
有两个小需求，
1. 能否提供辅助按键进行自动翻译，目前情况下使用自动翻译，会造成任何情况下鼠标选中文本都会请求api进行翻译，如果可以的话，可以增加功能：按住shift键，之后选中文本进行自动翻译，可以避免不必要的请求
2. 
<img width="363" alt="图片" src="https://user-images.githubusercontent.com/11593949/161373373-9305312d-80df-4473-976a-ed92f7404a8c.png">
该界面上的engine配置界面其实不是很常用，建议仅保留原文文本框和翻译文本框，更加简洁一点

_Originally posted by @Qitingshe in https://github.com/windingwind/zotero-pdf-translate/issues/64#issuecomment-1086583027_

**Comment by windingwind** [comment]
@Qitingshe Moved to this issue.

**Comment by windingwind** [comment]
@Qitingshe
For 1, the translate shortcut is `T`. You can disable automatic translation and use shortcut.

**Comment by Qitingshe** [comment]
thanks for your reply, I didn‘t know there has shortcut `T`,  I'm looking forward to the new features. thanks for your works

**Comment by windingwind** [comment]
you can control which part will show in the sidebar since v0.3.20
