### ISSUE TITLE
[Bug] zotero6最新的插件不能使用国内的转发地址做gpt翻译，试了多个转发地址都不可以，确认不是网络原因，而且同样的配置在7上可以配置

### ISSUE THREAD

**Issue by 17794** [windingwind/zotero-pdf-translate#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 6
- Plugin Version:1.0.25

### Describe the bug

zotero6最新的插件不能使用国内的转发地址做gpt翻译,配置后界面一直无任何输出,插件状态一直显示加载中，用zotero7做同样的配置则可以输出。

### Debug Output

已启用日志，日志处无内容，翻译无响应，像卡住了一样

**Comment by windingwind** [comment]
只维护最新版，旧版本不再维护
