### ISSUE TITLE
[Feature] 请求支持Gemini

### ISSUE THREAD

**Issue by fredericky123** [windingwind/zotero-pdf-translate#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

### Anything else?

请求支持该api
https://makersuite.google.com/app/prompts/new_chat

**Comment by windingwind** [comment]
welcome PR

**Comment by sasaju** [comment]
#669 已提交PR

**Comment by fredericky123** [comment]
好像有bug,用着用着，总是会自动切换为Google api，并且gemini在设置中找不到了
<img width="172" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/13982749/6411af82-3ad2-447f-a7ef-e104769d555b">

**Comment by sasaju** [comment]
> 好像有bug,用着用着，总是会自动切换为Google api，并且gemini在设置中找不到了 <img alt="image" width="172" src="https://private-user-images.githubusercontent.com/13982749/293494706-6411af82-3ad2-447f-a7ef-e104769d555b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDc4NzMsIm5iZiI6MTcwNDAwNzU3MywicGF0aCI6Ii8xMzk4Mjc0OS8yOTM0OTQ3MDYtNjQxMWFmODItM2FkMi00NDdmLWE3ZWYtZTEwNDc2OWQ1NTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3MjYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OWU3MTRhYjNlMDRjYmQyZGU5NTk1Y2I4OWUyMjc5OWU5MjJjNTE3NzY1YzdkNDE5OGRiOTFmZmZjMGVmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1xF5Xo5dTFe0ocI1dYT1HybIOZZQ1n7Hx_MbSZ2PPIw">

你是安装的我打包的版本吗？那可能是因为目前作者的最新版打包的时候还没并入我的分支，你可以安装我打包的版本之后关掉自动更新
![image](https://github.com/windingwind/zotero-pdf-translate/assets/21136684/f7c6f7c1-c27e-4c78-a3ce-0ce65694b425)

**Comment by fredericky123** [comment]
安装的是作者的最新版本，开始是有gemini的选项的，总是会自动消失，不知道是什么bug

**Comment by windingwind** [comment]
请更新，已修复

**Comment by SugarMuzi** [comment]
zotero6版本的插件不支持gemini吗？
