### ISSUE TITLE
[Feature]wish to add pronunciation function

### ISSUE THREAD

**Issue by q77190858** [windingwind/zotero-pdf-translate#67]
每次我碰到不认识的单词，我不仅想翻译它，而且想知道这个单词如何发音。

我希望能添加一个发音的功能，我点击发音的按钮，就能有选中的单词的发音

像知云文献阅读一样在侧栏，或者像沙拉查词一样在弹出的窗口发音，我觉得都可以。

**Comment by windingwind** [comment]
Thanks. 
This feature will not have a high priority. If you have an urgent need, you can contribute code yourself.

**Comment by breakertt** [comment]
> 每次我碰到不认识的单词，我不仅想翻译它，而且想知道这个单词如何发音。
> 
> 我希望能添加一个发音的功能，我点击发音的按钮，就能有选中的单词的发音
> 
> 像知云文献阅读一样在侧栏，或者像沙拉查词一样在弹出的窗口发音，我觉得都可以。

已经可以看到音标了，但是发音实现起来比较复杂。

**Comment by lihengxuan123** [comment]
同求，蹲

**Comment by volatile-static** [comment]
#227 大家来这里讨论一下

**Comment by windingwind** [comment]
done

**Comment by jhong-tao** [comment]
In addition to phonetic symbols, I hope to increase the pronunciation function

**Comment by ybsun0215** [comment]
I want the same thing
