### ISSUE TITLE
[Bug] Error code: PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by nachtgefallen** [windingwind/zotero-pdf-translate#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Windows 10 22H2
- Zotero Version: 6.0.30
- Plugin Version: 1.0.25

### Describe the bug

插件为最新版本，apikey输入正常，但无法翻译，错误信息如下：

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 小牛🗝️

Zotero Error: An error occurred during a connection to api.niutrans.com.

TCP connection reset by peer

Error code: PR_CONNECT_RESET_ERROR

登录账户进行数据同步也不可用：

An error occurred during a connection to api.zotero.org.

TCP connection reset by peer

Error code: PR_CONNECT_RESET_ERROR

貌似是网络连接问题导致资源无法访问，请问如何解决？

### Debug Output

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "An error occurred during a connection to api.zotero.org.

TCP connection reset by peer

Error code: PR_CONNECT_RESET_ERROR
"]

[JavaScript Error: "An error occurred during a connection to api.zotero.org.

TCP connection reset by peer

Error code: PR_CONNECT_RESET_ERROR
"]

[JavaScript Error: "An error occurred during a connection to repo.zotero.org.

TCP connection reset by peer

Error code: PR_CONNECT_RESET_ERROR
"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "An error occurred during a connection to api.zotero.org.

TCP connection reset by peer

Error code: PR_CONNECT_RESET_ERROR
"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

version => 6.0.30, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.30, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.30, extension), Zotero Word for Windows Integration (6.0.3.SA.6.0.30, extension), Shockwave Flash (34.0.0.301, plugin), Zotero PDF Translate (1.0.25, extension, disabled)

(3)(+0013193): Scheduling next feed update

(4)(+0000001): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1

(3)(+0000003): No feeds with auto-update

(3)(+0005356): Getting Zotero sync password

(3)(+0000002): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000265): WebSocket error

(1)(+0000001): WebSocket connection closed: 1006

(3)(+0000000): Delaying 15000 ms

(3)(+0011543): Starting full-text content processor

(3)(+0003461): Getting Zotero sync password

(3)(+0000001): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000263): WebSocket error

(1)(+0000001): WebSocket connection closed: 1006

(3)(+0000000): Delaying 30000 ms

(3)(+0026774): Getting contents of C:\Users\84363\AppData\Roaming\Zotero\Zotero\Profiles\kdikmr1v.default\treePrefs.json

(3)(+0000004): Writing column prefs of length 2233 to file C:\Users\84363\AppData\Roaming\Zotero\Zotero\Profiles\kdikmr1v.default\treePrefs.json

(3)(+0003225): Getting Zotero sync password

(3)(+0000000): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000263): WebSocket error

(1)(+0000000): WebSocket connection closed: 1006

(3)(+0000001): Delaying 60000 ms

(3)(+0060009): Getting Zotero sync password

(3)(+0000002): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000332): WebSocket error

(1)(+0000001): WebSocket connection closed: 1006

(3)(+0000000): Delaying 60000 ms

**Comment by nachtgefallen** [comment]
杀毒软件关掉之后就好了，重启杀毒软件之后网络马上就不能用了，看来是杀毒软件导致网络异常。可以麻烦解答一下吗——如何设置杀毒软件才能让zotero正常联网又不用完全退出杀毒软件？

**Comment by windingwind** [comment]
与插件无关的问题，恕无法帮助
