### ISSUE TITLE
[Feature] 翻译和Better notes联动问题的建议

### ISSUE THREAD

**Issue by imomoe233** [windingwind/zotero-pdf-translate#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win10
- Zotero Version: 7
- Plugin Version: 1.1.4-49

### Describe the feature request

在作者大大的zotero pdf translate中，翻译如果添加在注释，会跟在注释后面，这导致在将从注释导入笔记的时候，生成的内容会是“注释+翻译”。
且同样的，如果添加在comment，导入到笔记时，也会使翻译和注释在同一行。
由于有些内容太长或者翻译的内容长短不一致，导致笔记看起来较为杂乱。
经过我的尝试，我没有办法在模板中将这两个拆开，或者我没有找到合适的API来做这个，希望大佬可以做一个复选框，来勾选当翻译时，是“注释+翻译”的形式还是“注释 + /换行 + 翻译”的形式，亦或者是在导入到笔记时，可以选择是否将注释和翻译换行。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
1. 
<img width="342" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/33902321/310a2af2-faee-4b63-ae28-cf37ba247b88">

2. 粘贴`Zotero.Prefs.set('extensions.zotero.ZoteroPDFTranslate.splitChar', '\n🔤', true)`并单击Run

<img width="900" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/33902321/47ff6cd3-072e-4cec-a7a5-3c1bb2f7aa5f">
