### ISSUE TITLE
[Feature] Switch to Orginal/Translation

### ISSUE THREAD

**Issue by MarekAdam** [windingwind/zotero-pdf-translate#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win10 64bit
- Zotero Version: 6-> 7.0.0-beta.54+6b996d4f9 (64-bit)
- Plugin Version: 1.0.25 -> 1.1.0-26

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
In Zotero 6 i had option on list "Switch to Orginal/Translation". On Zotero 7 i have only translate title/Translate Abstract. 
I have to turn on something or there is no this option on 7?
I have papers in english russian, german, french etc so its reeeeeealy good option to work. 
I know that i can add column with translated title but it was much better option :)

![Zrzut ekranu 2024-01-01 23 18 34](https://github.com/windingwind/zotero-pdf-translate/assets/40676162/4204bc8a-91d1-4055-b665-c7a4f8f1afa7)

**Comment by windingwind** [comment]
This is no longer supported in the Z7 version. Changing the original title confuses several users, and this feature hacks the native title column, which is not an encouraged behavior for a plugin.
