### ISSUE TITLE
[Bug] Zotero 7 独立窗口无法调整宽度

### ISSUE THREAD

**Issue by Rzlnmc** [windingwind/zotero-pdf-translate#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Win 10 & Win 11
- Zotero Version: 7.0.0-beta.54+6b996d4f9 (64-bit)
- Plugin Version: 1.1.0-26

### Describe the bug

无法正常调整独立窗口（Translate Panel）的宽度（水平方向），只能增加宽度，增加后无法减少，垂直方向可以正常调整。
在两台电脑上均出现同样问题（使用百度网盘进行数据同步）。

### Debug Output

调整宽度后没有输出。

**Comment by anshangtangyuan** [comment]
同样的错误
