### ISSUE TITLE
[Bug] GhatGPT翻译出现繁体结果

### ISSUE THREAD

**Issue by ZhiguoZhao** [windingwind/zotero-pdf-translate#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 14.2.1 (23C71)
- Zotero Version: 7.0.0-beta.54+6b996d4f9
- Plugin Version: 1.1.0-beta.28

### Describe the bug

使用GhatGPT进行翻译（English -> Chinese）时，会出现繁体结果。

### Debug Output

<img width="987" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/112527426/d6cea4e5-70f8-429e-9358-272934de9985">

**Comment by windingwind** [comment]
与插件无关，翻译服务问题向服务商反馈
