### ISSUE TITLE
[Bug] 划词后自动翻译，但翻译内容仍然是上一次划词内容

### ISSUE THREAD

**Issue by tsinglinrain** [windingwind/zotero-pdf-translate#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.54+6b996d4f9
- Plugin Version: 1.1.0-beta.28

### Describe the bug

plugin配置如下：

<div align="center">
	<img src="https://github.com/windingwind/zotero-pdf-translate/assets/68103537/625a1a55-8f25-4511-a709-d481dd891932" alt="Editor" width="500">
</div>

阅读英文文献时，经常划词翻译以及做标记，但是划着划着，就会出现如下情况。

<div align="center">
	<img src="https://github.com/windingwind/zotero-pdf-translate/assets/68103537/053b83f6-178e-4339-95e7-60fc1b43aa9d" alt="Editor" width="500">
</div>

划到单词 `the` ，应当显示 `the` 的释义，但其内容为上一句的翻译。

但是如果做颜色标记，则左侧翻译内容仍然时正确的。
<div align="center">
	<img src="https://github.com/windingwind/zotero-pdf-translate/assets/68103537/a050c0cd-d703-4559-aaa1-eec4ca8767c2" alt="Editor" width="200">
</div>

### Debug Output

Disable all other plugins后尝试了很久，很难复现（也许是多个插件干扰），所以没有上传debug output.

如果复现了，我再补充。

2024.1.11.20:37补充
已经补充存在其他插件的情况（试了很久，只存在translate插件的情况下似乎不会复现此情况）：
[Debug Output.zip](https://github.com/windingwind/zotero-pdf-translate/files/13903243/Debug.Output.zip)
对应内容如下
<div align="center">
	<img src="https://github.com/windingwind/zotero-pdf-translate/assets/68103537/2c0c7c04-1875-4abe-9938-839e0a9e59e7" alt="Editor" width="400">
</div>

### Anything else?

暂时的解决方法是点击键盘上的`Alt`键，随后即可回复正常。

**Comment by neil-code** [comment]
一样，应该是bug，5.0的版本是正常的

**Comment by zhaojing629** [comment]
我也这样，咋解决啊QAQ  我划下一段的时候还是上一段的翻译

**Comment by windingwind** [comment]
需要可复现的步骤，或者调试输出

**Comment by zhaojing629** [comment]
xdm，我下了1.1.0.26好像就可以了  你们试试看行不行

**Comment by neil-code** [comment]
Debug ID：D771371571，这样能看吗 还是需要我把日志保存下来

**Comment by neil-code** [comment]
> 需要可复现的步骤，或者调试输出

Debug ID：D771371571，这样能看吗 还是需要我把日志保存下来

**Comment by neil-code** [comment]
> xdm，我下了1.1.0.26好像就可以了 你们试试看行不行

好像真的可以了 谢谢 先用老版本替代了

**Comment by windingwind** [comment]
需要上传完整debug output

**Comment by cgl-sd** [comment]
按`ALT`有用，谢谢
