### ISSUE TITLE
[Feature] 增加划词行为的健壮性

### ISSUE THREAD

**Issue by StLeoX** [windingwind/zotero-pdf-translate#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: linux
- Zotero Version: 6.0.30
- Plugin Version: 1.0.25

### Describe the feature request

**增加划词的健壮性，能做基本的单词 trim**
用户可能将特殊字符包括 _、- 划进来，希望 trim 掉返回正常响应。

### Describe the solution you'd like

trimPrefix
用例： -test 变为 test
trimSuffix
用例： test- 变为 test

**Comment by windingwind** [comment]
我认为没有必要，标点符号也是有相对应的语义的
