### ISSUE TITLE
选中文本后，点击翻译框的内容会粘贴并翻译上次剪切板内容

### ISSUE THREAD

**Issue by Liwt0** [windingwind/zotero-pdf-translate#68]
**Describe the bug**
选中文本后，点击翻译框的内容会粘贴并翻译上次剪切板内容，无法复制目标文本的翻译结果

**To Reproduce**
1. 选中要翻译的内容
![image](https://user-images.githubusercontent.com/90240641/161429989-e5b11cb3-445a-4727-b789-a6c7ba7a00f6.png)

2. 出现翻译结果框

3. 点击翻译结果，会粘贴剪切板上次内容并翻译，无法实现复制目标结果
![image](https://user-images.githubusercontent.com/90240641/161430020-8e96df17-7205-4e53-8722-ec6ffbcbba0f.png)

**Expected behavior**
点击翻译结果，复制保存到剪切板，不会粘贴上次剪切板内容

.

**Environment**
 - OS: Windows
 - Zotero Version 6.0.4
 - Addon Version 0.3.19

**Comment by Liwt0** [comment]
应该是和剪切板内容读取上有bug
![image](https://user-images.githubusercontent.com/90240641/161430319-bfe31d65-e71a-4b36-ae99-3617e0cad1a9.png)

**Comment by Liwt0** [comment]
主要原因是在同时打开多个文献时才会出现
1.在第一个文献中选中翻译，点击复制
2.在第二个文献中选中翻译，再右击翻译内容框会出现粘贴上次结果

**Comment by Liwt0** [comment]
![image](https://user-images.githubusercontent.com/90240641/161430490-a5dd21e4-9aa1-494b-9d47-18122c2eabce.png)
![image](https://user-images.githubusercontent.com/90240641/161430514-e0cd2427-63de-4bb9-b804-b3e346fb89ea.png)

**Comment by Liwt0** [comment]
![image](https://user-images.githubusercontent.com/90240641/161430537-42256e87-2c23-4193-a92f-3c04b136bfe3.png)

**Comment by windingwind** [comment]
这主要是由于翻译频率比较高，
1. 你先翻译了一个长句，耗时较长；
2. 你翻译了一个短句，耗时较短；
3. 收到短句的翻译结果。更新到界面；
4. 此时长句的翻译刚刚结束，收到结果，更新到界面。
因此，先前翻译的结果覆盖了后翻译的结果。

这个插件不会读取你的剪切板，只是在你点击复制的时候，将文本复制到剪切板。
将会尝试修复。

**Comment by windingwind** [comment]
fixed in v0.3.20
