### ISSUE TITLE
希望能出一个针对arXiv论文的精细化翻译功能，能翻译全文，并且保留图片在原文中的位置顺序，其中翻译引擎也是可以自选的，最终输出.md或者.pdf格式的文件

### ISSUE THREAD

**Issue by August-L-J** [windingwind/zotero-pdf-translate#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: WIN 10 22H2
- Zotero Version: 7.0.0-beta.54+6b996d4f9 (64-bit)
- Plugin Version: [Release 1.1.0-beta.28](https://github.com/windingwind/zotero-pdf-translate/releases/tag/v1.1.0-beta.28)

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
我是一位大四学生，正在做毕设，正在做深度学习，机器学习的研究学习，关于这方面的论文大多是arXiv的形式，由于都是英文内容，鉴于语言问题，希望能出一个针对arXiv论文的精细化翻译功能，能做到翻译全文的效果，并且保留图片在原文中的位置顺序，希望其中翻译引擎也是可以自选的，翻译完成后可以输出一个翻译后的文件，可以是```.md```或者```.pdf```格式的文件

**Why do you need this feature?**
语言问题，全英文的论文读起来比较难受，如果能做到把全英文的论文翻译成中文（或者其他语言）就能大大提高读论文的能力

### Describe the solution you'd like

**The solution you'd like**
能精确直接翻译arXiv论文，做到全文翻译，并且保留图片在原文中的位置顺序，其中翻译引擎也是可以自选的
翻译完成后可以输出一个翻译后的文件，可以是```.md```或者```.pdf```格式的文件

**Alternatives you've considered**
暂无

**Comment by windingwind** [comment]
不会实现，可参考其他此类产品

**Comment by August-L-J** [comment]
噢噢！我刚刚找了一下，发现用```gpt_academic```GitHub上的项目的，里面的```[Arxiv论文精细翻译（输入arxivID）[需Latex]]的```功能就能实现了！！
果然其他人有做平替的功能~
