### ISSUE TITLE
[Feature] A PDF Translation Annotation Button on popmenu or translate pane

### ISSUE THREAD

**Issue by zyx335588** [windingwind/zotero-pdf-translate#69]
When I opened a PDF with highlights, all highlights were translated and stored with the highlights if the Translation Annotation was checked in Preferences. However, most of them were not needed to be translated or stored. I would like only to store several of the translations for future reference. It may be a solution that a button on the popmenu or translate pane was added to allow users to make choices.

**Another suggestion:**

Whether a *Copy Both* beside *Copy Raw* and *Copy Result* buttons could be considered to make users copy both raw and result separated by a line break. It would be more convenient to copy them to other editors to build a corpus. 

Or, more directly, adding a button to store all the needed text and translation in an item child note with a special title or tag (such as *Golden Sentence* like a bioinformatic program [TBtools](https://github.com/CJ-Chen/TBtools) developed by @CJ-Chen). The function of **Golden Words, Golden Sentences** in TBtools ([link1](https://mp.weixin.qq.com/s?src=11&timestamp=1648999393&ver=3716&signature=Jrg3I1c5EbL9lXIdnRZeKsIH1*63R3ZqFf3jddenxxU0WMQ6H*S4R0RAGIptfZmnKs97MNaRPyxbAxxOjAV9MCQBHKDcVBrqobIpwyDpfPftO0VegjsKGNZ-D23YEy2Q&new=1), [link2](https://mp.weixin.qq.com/s?__biz=MzIwNjI0Njc1NQ==&mid=2651132182&idx=1&sn=115f72782ccc60541cf6e23d8b54524b&chksm=8cd5371abba2be0ce4df49774692ccd7b98cb3849c01b2ace47012b8bf20fa1cdd254d46d497&scene=178&cur_album_id=1503452975850127362#rd)) should be easily implemented with your plugin, zotero's note editor (support some HTML tags) and note export function.

**Comment by windingwind** [comment]
Adding a Copy Both button is easy. Will update in the next release.

I'm not clear about your point: do you mean add ALL annotations of a document to a new note(with translation)?

**Comment by windingwind** [comment]
try v0.3.20 please

**Comment by zyx335588** [comment]
Thank you for the update.

NOT all the annotations, but those I choose. This is why I think a button is more suitable than an automatic method. In most cases, I use this plugin only to get the approximate meaning of a sentence. However, in some cases, I want to store them. For example, I could store some sentence patterns, some good sentences used to describe a phenomenon... I can copy both of the raw text and the translation to another editor to achieve it. Since Zotero has a build-in note editor, I think besides manual copy, these texts can be directly stored to the Zotero note with a specific title or tag. Of course, it is better if the key words can be highlighted at the same time. And then, after some time, I can export these notes in different items to an HTML file or a file in other formats by filtering the note title or note tag.

I don't know whether I express it clearly or not. The following webpages described a similar function in TBtool can be referred to.
https://www.jianshu.com/p/7f5586b7a43f
https://www.jianshu.com/p/0e8ccc382edf

**Comment by Xuyihaoby** [comment]
I have the same suggestion.When I highlight some words ,the translation will be stored as a note automatically.

**Comment by windingwind** [comment]
2 solutions:

1. Add a `translate annotation` checkbox/switch in the popup & sidebar. You can manually enable/disable translation for every annotation.
2. Add `translate annotation`  to the right-click menu of annotations.

Which one do you prefer?

**Comment by Xuyihaoby** [comment]
Well, if I understand properly, the above question can be solved by edit-preference-PDF translate-function-uncheck the fourth box

**Comment by zyx335588** [comment]
> 3 solutions:
> 
> 
> 
> 1. Add a `translate annotation` checkbox/switch in the popup & sidebar. You can manually enable/disable translation for every annotation.
> 
> 2. Add `translate annotation`  to the right-click menu of annotations.
> 
> 3. Automatically translate `Add to Note` text, just like the automatic annotation translation function.
> 
> ![image](https://user-images.githubusercontent.com/33902321/161960014-7b88f661-dd94-4f6f-b910-635076fc2793.png)
> 
> 
> 
> 
> 
> Which one do you prefer?

@windingwind I prefer the third.

**Comment by zyx335588** [comment]
@Xuyihaoby 
Yes, for the problem:
> When I opened a PDF with highlights, all highlights were translated and stored with the highlights if the Translation Annotation was checked in Preferences.
It can be solved by unchecking the fourth box.

Now, in fact, we discuss another issue while it was put in this issue together with the above question. As @windingwind said, I want a more convenient way to collect useful information from PDF document and store them in a note, and if possible, to export them.

**Comment by cjlCMU** [comment]
> @zyx335588 try v0.3.22
![image](https://user-images.githubusercontent.com/102497540/162338825-5874cba6-0f10-4aa8-848a-7b8d9d236580.png)
![image](https://user-images.githubusercontent.com/102497540/162338845-6db368ca-5175-457c-9c0e-c515d01cd089.png)
I tried your new version on win11 laptop, but I failed to see the "add to note" button. I am looking forward you to fixing this bug.

**Comment by windingwind** [comment]
@cjlCMU 
Open a note editor and it will show up. If no active note editor is selected, I don't know where to insert the text.

BTW, the button label is too long right now. Any suggestions?

![image](https://user-images.githubusercontent.com/33902321/162341286-ef87d5eb-2722-4896-8798-d5851c7f08b5.png)

**Comment by chunyanghu** [comment]
some annotation can be translated automatically, but some annotations can't be translated. I don't why?
![屏幕截图 2022-04-08 101930](https://user-images.githubusercontent.com/25714958/162350377-f3b868d1-e9e4-4ad3-a4e4-00b180056e7f.png)
![屏幕截图 2022-04-08 101950](https://user-images.githubusercontent.com/25714958/162350384-df9bbf91-7014-42cb-810c-5c8dc64bc4c4.png)

**Comment by windingwind** [comment]
v0.4.0 release fixed some bugs with this new feature.

**Comment by zyx335588** [comment]
> @cjlCMU Open a note editor and it will show up. If no active note editor is selected, I don't know where to insert the text.

That's great!
I think if the note editor is not activated, we can try to create a new note with a special title or tag by coding for the first time. In the latter, append translations to the note with this title or tag.

**Comment by windingwind** [comment]
> > @cjlCMU Open a note editor and it will show up. If no active note editor is selected, I don't know where to insert the text.
> 
> That's great! I think if the note editor is not activated, we can try to create a new note with a special title or tag by coding for the first time. In the latter, append translations to the note with this title or tag.

Nice suggestion. Adding the selected text with citation info to note directly is a little bit challenging, though.

**Comment by windingwind** [comment]
Now it looks like this:

![image](https://user-images.githubusercontent.com/33902321/162352734-89c7d643-c718-4e66-9526-593cebf03d22.png)

**Comment by windingwind** [comment]
I'll close this issue. Feel free to open it again.
