### ISSUE TITLE
[Feature] 批量标题翻译使用拼接，降低翻译引擎访问频率

### ISSUE THREAD

**Issue by nkh0472** [windingwind/zotero-pdf-translate#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 21H2 10.0.22000.2538
- Zotero Version: 7.0.0
- Plugin Version: 1.0.0

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
已知高频率访问翻译服务有可能会被封禁

**Why do you need this feature?**
当通过右键菜单批量翻译大量标题及摘要时，会高频率访问翻译服务。尤其是标题翻译具有内容短、数量多的特点。

### Describe the solution you'd like

**The solution you'd like**
拼接多个标题进行批量翻译，例如拼接5个标题，每个一行。插件获取结果后再根据分行将原始翻译解析为拼接的多个标题。

**Alternatives you've considered**
批量获取标题，每个一行放进doc文档；使用谷歌文档翻译获得标题翻译；将文档内容粘贴回插件进行解析。
该操作已经经过长时间的验证（用于字幕制作等场景），可以高效翻译数百~千行的内容。

### Anything else?

Github项目SubtitleEdit支持这样的操作，在菜单栏的翻译菜单中，自动翻译时支持句子级别的拼接及解析（3.x.x版本，目前4.0.x版本该功能已经独立出来）；
SubtitleEdit的百度翻译插件也支持拼接（Bulk）翻译。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/67589323/ffdb10d1-19b1-4332-b000-fccb63cf7f17)

**Comment by windingwind** [comment]
欢迎PR

**Comment by nkh0472** [comment]
> 欢迎PR

不太熟悉TypeScript……有心无力

**Comment by wqshuei** [comment]
翻译的准确率怎么样？
