### ISSUE TITLE
请问如何清除已翻译的标题和摘要？

### ISSUE THREAD

**Issue by rblxq** [windingwind/zotero-pdf-translate#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 专业版 22H2
- Zotero Version: 6.0.30
- Plugin Version: 1.0.5

### Describe the feature request

在批量翻译标题和摘要时，由于某些中文文献的语言设定错误，导致进行翻译并显示在侧边栏了，请问如何清除保存的标题和摘要翻译。

我设置了中文语言并在插件设置中对中文关闭自动翻译，点击翻译或重新翻译，仍然显示标题翻译和摘要翻译。
我还将插件进行卸载和重装，发现以前的翻译仍然存在。
![50fab67b6c42036bc42a9590893a071](https://github.com/windingwind/zotero-pdf-translate/assets/53112918/d408b820-7d38-4ee0-95d3-3416cd86dcad)
![Snipaste_2024-01-19_14-11-29](https://github.com/windingwind/zotero-pdf-translate/assets/53112918/400b1378-0ada-4301-af2c-342877a4b586)

**Comment by windingwind** [comment]
在extra字段编辑/删除即可
