### ISSUE TITLE
[Feature] 将标题翻译结果设置到某个字段

### ISSUE THREAD

**Issue by MedAIerHHL** [windingwind/zotero-pdf-translate#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0
- Plugin Version:1.0.0

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
将标题翻译结果放在短标题字段

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
不建议如此做。CLS对字段有严格规范，每个字段都在特定引用格式中承担作用。
