### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xiaooomd** [windingwind/zotero-pdf-translate#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 Version 22H2
- Zotero Version: 7.0.0-beta.54+6b996d4f9 (64-bit)
- Plugin Version:1.1.0-beta.28

### Describe the bug

使用划句翻译功能，没开拼接模式，上一次需要翻译的文本会出现在翻译后的框内。上传的图片可以看到，没有开启拼接模式，且只选了一句，但是翻译后的内容包含了上一次的结果。通过重启zotero会正常，但是过一会又会出现异常。

### Debug Output

1706152952422	addons.xpi	WARN	Checking D:\app\zotero7\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1706152953192	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "item is null" {file: "chrome://zotero/content/itemPane.js" line: 114}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/zoterofigure@polygon.org.xpi!/chrome/content/scripts/zoterofigure.js" line: 5319}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/zoterofigure@polygon.org.xpi!/chrome/content/scripts/zoterofigure.js" line: 5319}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/zoterofigure@polygon.org.xpi!/chrome/content/scripts/zoterofigure.js" line: 5319}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/zoterofigure@polygon.org.xpi!/chrome/content/scripts/zoterofigure.js" line: 5319}]

[JavaScript Error: "this._pdfThumbnails is undefined" {file: "resource://zotero/reader/reader.js" line: 26615}]

[JavaScript Error: "TypeError: parent is null" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 16184}]

[JavaScript Error: "TypeError: container is null" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/night@tefkah.com.xpi!/chrome/content/scripts/night.js" line: 664}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/zoterofigure@polygon.org.xpi!/chrome/content/scripts/zoterofigure.js" line: 5319}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/%E8%82%96%E8%8C%82%E6%A0%8B/AppData/Roaming/Zotero/Zotero/Profiles/6byv1sur.default/extensions/zoterofigure@polygon.org.xpi!/chrome/content/scripts/zoterofigure.js" line: 5319}]

appName => Zotero, version => 7.0.0-beta.54+6b996d4f9, os => Windows 10.0 19045, locale => zh-CN, extensions => Zotero Reference (0.5.8, extension), Zotero Better Notes (1.0.4, extension), PDF Figure (0.1.2, extension), Night (0.1.0-2, extension), Easier Citation (0.4.2, extension), Translate for Zotero (1.1.0-beta.28, extension), 蒲公英 (1.0.0-7, extension), Zotero PDF Preview (1.0.0-4, extension), Green Frog (0.16.04, extension), Zotero Attanger (1.0.8, extension), Zoplicate (2.1.0, extension), Awesome GPT (0.5.1.4, extension), Sci-PDF (1.1.0, extension), Better BibTex for Zotero (6.7.144, extension), Ethereal Style (3.3.6, extension), MarkDB-Connect (0.1.0-rc.6, extension, disabled)

### Anything else?

![image](https://github.com/windingwind/zotero-pdf-translate/assets/51357799/111b15d8-55a9-4137-be15-8771b3ec3044)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/51357799/580db9ef-c19e-4600-b7a9-b20ce5d5b1e5)

**Comment by windingwind** [comment]
fixed in the latest beta
