### ISSUE TITLE
Feature Request: Add a shortcut key to avoid the popup menu

### ISSUE THREAD

**Issue by hanmala123** [windingwind/zotero-pdf-translate#7]
Right click will pop up the translation window as well as built-in menu.

Thank you for creating this plugin👍.

**Comment by windingwind** [comment]
Please update add-on via Tools->Add-ons. 

Since v0.1.1, you can manually enable/disable the popup in the Preference.

**Comment by windingwind** [comment]
As there had been an big update and this issue seems no longer a problem in the latest version, I'll close it.
Feel free to open it again any time.
