### ISSUE TITLE
[Bug] 翻译侧窗无法显示

### ISSUE THREAD

**Issue by Liu321H** [windingwind/zotero-pdf-translate#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: WIN 10
- Zotero Version: 7.0.0-beta.55+9151fb355 (64-bit)
- Plugin Version:1.1.0-beta.30

### Describe the bug

有弹窗翻译，无法显示侧窗翻译

### Debug Output

1706275767045	addons.xpi	WARN	Checking D:\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1706275767927	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

appName => Zotero, version => 7.0.0-beta.55+9151fb355, os => Windows 10.0 19045, locale => zh-CN, extensions => Jasminum (1.0.0-12, extension, disabled), Better Notes for Zotero (1.1.4-49, extension, disabled), Easier Citation (0.4.2, extension, disabled), PDF Figure (0.1.2, extension, disabled), Ethereal Style (3.3.6, extension, disabled), Chartero (2.3.3, extension, disabled), Translate for Zotero (1.1.0-beta.30, extension, disabled)

**Comment by Liu321H** [comment]
![bug](https://github.com/windingwind/zotero-pdf-translate/assets/157811365/3f1b01f9-82b8-4d1f-8cf4-28f82d533b00)
不显示侧栏

**Comment by Catenfei** [comment]
我也是，一打开就这样了

**Comment by daimawanjiaA** [comment]
貌似是zotero自动更新了，ui都变了

**Comment by ajinmidejcj** [comment]
我也我也

**Comment by print-dont-worry** [comment]
我也是，还在这里找原因

**Comment by Slmtdhy** [comment]
有人解决了吗，我也遇到这种情况了

**Comment by EasonC13** [comment]
同樣問題，可能是 UI 改過

**Comment by realmalcolm12** [comment]
zotero自动更新后，此问题出现了，不显示侧窗，相同问题zotero-addon那个插件的logo也没有了，我在设置已经禁用了自动更新。

**Comment by Liu321H** [comment]
新版7.0.0beta55+不支持很多插件如reference。旧版54+覆盖安装即可使用。

**Comment by print-dont-worry** [comment]
> 新版7.0.0beta55+不支持很多插件如参考。旧版54+覆盖安装即可使用。

请问去哪里下载54+呢，我没有找到

**Comment by Liu321H** [comment]
链接：https://pan.baidu.com/s/179OZ5zNno57kWtmHf05aRw?pwd=yjeu 
提取码：yjeu

**Comment by print-dont-worry** [comment]
> 链接：https://pan.baidu.com/s/179OZ5zNno57kWtmHf05aRw?pwd=yjeu 提取码：yjeu

十分感谢！！

**Comment by EasonC13** [comment]
換成舊版並沒有解決這個問題，可能還是要請開發者更新
