### ISSUE TITLE
[Bug] zotero7 beta中的 translate插件无法翻译日语和韩语，zotero6中一切正常

### ISSUE THREAD

**Issue by historylbb** [windingwind/zotero-pdf-translate#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0 Zotero
- Plugin Version: 1.1.0-beta.30 以及之前的各种版本

### Describe the bug

![QQ截图20240127143554](https://github.com/windingwind/zotero-pdf-translate/assets/157869253/5c8060f0-b179-4ebe-9955-2a73dbb40ea4)
![QQ截图20240127143541](https://github.com/windingwind/zotero-pdf-translate/assets/157869253/4b42bd8e-4b18-49ca-b540-156b6633b722)
![QQ截图20240127143352](https://github.com/windingwind/zotero-pdf-translate/assets/157869253/4ea72b8a-bcd8-4741-aa0c-2d9486c0c951)
![QQ截图20240127143340](https://github.com/windingwind/zotero-pdf-translate/assets/157869253/41228b8b-f6ab-4ada-8fc5-70124f337170)

软件环境禁用了其他的插件，只留下zotero-pdf-translate，如图所示，韩语和日语翻译均失败，显示的原文，英语翻译一切正常。也检查过翻译语言设置，同样的设置在zotero6中翻译韩语和日语一切正常。之后换了一台从未安装过zotero的电脑，bug同样存在。
希望大佬在下一个版本中排查一下原因！感激不尽！

### Debug Output

1706333950955	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1706333952369	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIServerSocket.init]" {file: "jar:file:///C:/Program%20Files/Zotero/app/omni.ja!/integration/libreoffice/components/zoteroLibreOfficeIntegration.js" line: 87}]

[JavaScript Error: "o.item is undefined" {file: "jar:file:///C:/Users/BB/AppData/Roaming/Zotero/Zotero/Profiles/jxorv1vu.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 155}]

[JavaScript Error: "o.item is undefined" {file: "jar:file:///C:/Users/BB/AppData/Roaming/Zotero/Zotero/Profiles/jxorv1vu.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 155}]

[JavaScript Error: "o.item is undefined" {file: "jar:file:///C:/Users/BB/AppData/Roaming/Zotero/Zotero/Profiles/jxorv1vu.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 155}]

[JavaScript Error: "o.item is undefined" {file: "jar:file:///C:/Users/BB/AppData/Roaming/Zotero/Zotero/Profiles/jxorv1vu.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 155}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\BB\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.55+9151fb355, os => Windows 10.0 19045, locale => zh-CN, extensions => Translate for Zotero (1.1.0-beta.30, extension), Zotero GPT (0.2.8, extension, disabled), Zotero PDF Preview (0.3.7, extension, disabled), Zotero Style (2.6.7, extension, disabled)

(3)(+0020675): [Translate for Zotero] runTranslationTask {}

(3)(+0000001): [Translate for Zotero] {"id":"tSE7ChRx-1706333973412","type":"text","raw":"즉 당시는 학교를 설립했어도 학생들에게 가르칠 교 재가 없 어 「천자 문j 이 나 『농몽선습』, 혹은 중국의 역사 등을 교육하 고 있는 상황이었다, 일부 유지가들이 초등 • 중등 • 전문 교과서를 편술하여 이전에 비해 비록 사정은 조금 나아졌으나 이 모두가 우리 나라의 상황에 적합하게 씌어진 것만은 아니었다. 교 과 서 는 국가의","result":"","audio":[],"service":"google","candidateServices":[],"itemId":783,"status":"processing","extraTasks":[],"langfrom":"zh","langto":"zh-CN","callerID":"zoteropdftranslate@euclpts.com","secret":""}

(3)(+0000001): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=275781.131377&q=%EC%A6%89%20%EB%8B%B9%EC%8B%9C%EB%8A%94%20%ED%95%99%EA%B5%90%EB%A5%BC%20%EC%84%A4%EB%A6%BD%ED%96%88%EC%96%B4%EB%8F%84%20%ED%95%99%EC%83%9D%EB%93%A4%EC%97%90%EA%B2%8C%20%EA%B0%80%EB%A5%B4%EC%B9%A0%20%EA%B5%90%20%EC%9E%AC%EA%B0%80%20%EC%97%86%20%EC%96%B4%20%E3%80%8C%EC%B2%9C%EC%9E%90%20%EB%AC%B8j%20%EC%9D%B4%20%EB%82%98%20%E3%80%8E%EB%86%8D%EB%AA%BD%EC%84%A0%EC%8A%B5%E3%80%8F%2C%20%ED%98%B9%EC%9D%80%20%EC%A4%91%EA%B5%AD%EC%9D%98%20%EC%97%AD%EC%82%AC%20%EB%93%B1%EC%9D%84%20%EA%B5%90%EC%9C%A1%ED%95%98%20%EA%B3%A0%20%EC%9E%88%EB%8A%94%20%EC%83%81%ED%99%A9%EC%9D%B4%EC%97%88%EB%8B%A4%2C%20%EC%9D%BC%EB%B6%80%20%EC%9C%A0%EC%A7%80%EA%B0%80%EB%93%A4%EC%9D%B4%20%EC%B4%88%EB%93%B1%20%E2%80%A2%20%EC%A4%91%EB%93%B1%20%E2%80%A2%20%EC%A0%84%EB%AC%B8%20%EA%B5%90%EA%B3%BC%EC%84%9C%EB%A5%BC%20%ED%8E%B8%EC%88%A0%ED%95%98%EC%97%AC%20%EC%9D%B4%EC%A0%84%EC%97%90%20%EB%B9%84%ED%95%B4%20%EB%B9%84%EB%A1%9D%20%EC%82%AC%EC%A0%95%EC%9D%80%20%EC%A1%B0%EA%B8%88%20%EB%82%98%EC%95%84%EC%A1%8C%EC%9C%BC%EB%82%98%20%EC%9D%B4%20%EB%AA%A8%EB%91%90%EA%B0%80%20%EC%9A%B0%EB%A6%AC%20%EB%82%98%EB%9D%BC%EC%9D%98%20%EC%83%81%ED%99%A9%EC%97%90%20%EC%A0%81%ED%95%A9%ED%95%98%EA%B2%8C%20%EC%94%8C%EC%96%B4%EC%A7%84%20%EA%B2%83%EB%A7%8C%EC%9D%80%20%EC%95%84%EB%8B%88%EC%97%88%EB%8B%A4.%20%EA%B5%90%20%EA%B3%BC%20%EC%84%9C%20%EB%8A%94%20%EA%B5%AD%EA%B0%80%EC%9D%98

(3)(+0000134): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=275781.131377&q=%EC%A6%89%20%EB%8B%B9%EC%8B%9C%EB%8A%94%20%ED%95%99%EA%B5%90%EB%A5%BC%20%EC%84%A4%EB%A6%BD%ED%96%88%EC%96%B4%EB%8F%84%20%ED%95%99%EC%83%9D%EB%93%A4%EC%97%90%EA%B2%8C%20%EA%B0%80%EB%A5%B4%EC%B9%A0%20%EA%B5%90%20%EC%9E%AC%EA%B0%80%20%EC%97%86%20%EC%96%B4%20%E3%80%8C%EC%B2%9C%EC%9E%90%20%EB%AC%B8j%20%EC%9D%B4%20%EB%82%98%20%E3%80%8E%EB%86%8D%EB%AA%BD%EC%84%A0%EC%8A%B5%E3%80%8F%2C%20%ED%98%B9%EC%9D%80%20%EC%A4%91%EA%B5%AD%EC%9D%98%20%EC%97%AD%EC%82%AC%20%EB%93%B1%EC%9D%84%20%EA%B5%90%EC%9C%A1%ED%95%98%20%EA%B3%A0%20%EC%9E%88%EB%8A%94%20%EC%83%81%ED%99%A9%EC%9D%B4%EC%97%88%EB%8B%A4%2C%20%EC%9D%BC%EB%B6%80%20%EC%9C%A0%EC%A7%80%EA%B0%80%EB%93%A4%EC%9D%B4%20%EC%B4%88%EB%93%B1%20%E2%80%A2%20%EC%A4%91%EB%93%B1%20%E2%80%A2%20%EC%A0%84%EB%AC%B8%20%EA%B5%90%EA%B3%BC%EC%84%9C%EB%A5%BC%20%ED%8E%B8%EC%88%A0%ED%95%98%EC%97%AC%20%EC%9D%B4%EC%A0%84%EC%97%90%20%EB%B9%84%ED%95%B4%20%EB%B9%84%EB%A1%9D%20%EC%82%AC%EC%A0%95%EC%9D%80%20%EC%A1%B0%EA%B8%88%20%EB%82%98%EC%95%84%EC%A1%8C%EC%9C%BC%EB%82%98%20%EC%9D%B4%20%EB%AA%A8%EB%91%90%EA%B0%80%20%EC%9A%B0%EB%A6%AC%20%EB%82%98%EB%9D%BC%EC%9D%98%20%EC%83%81%ED%99%A9%EC%97%90%20%EC%A0%81%ED%95%A9%ED%95%98%EA%B2%8C%20%EC%94%8C%EC%96%B4%EC%A7%84%20%EA%B2%83%EB%A7%8C%EC%9D%80%20%EC%95%84%EB%8B%88%EC%97%88%EB%8B%A4.%20%EA%B5%90%20%EA%B3%BC%20%EC%84%9C%20%EB%8A%94%20%EA%B5%AD%EA%B0%80%EC%9D%98 succeeded with 200

(3)(+0001901): [Translate for Zotero] runTranslationTask {}

(3)(+0000001): [Translate for Zotero] {"id":"U36teryK-1706333975450","type":"text","raw":"즉 당시는 학교를 설립했어도 학생들에게 가르칠 교 재가 없 어 「천자 문j 이 나 『농몽선습』, 혹은 중국의 역사 등을 교육하 고 있는 상황이었다, 일부 유지가들이 초등 • 중등 • 전문 교과서를 편술하여 이전에 비해 비록 사정은 조금 나아졌으나 이 모두가 우리 나라의 상황에 적합하게 씌어진 것만은 아니었다.","result":"","audio":[],"service":"google","candidateServices":[],"itemId":783,"status":"processing","extraTasks":[],"langfrom":"zh","langto":"zh-CN","callerID":"zoteropdftranslate@euclpts.com","secret":""}

(3)(+0000001): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=851382.707010&q=%EC%A6%89%20%EB%8B%B9%EC%8B%9C%EB%8A%94%20%ED%95%99%EA%B5%90%EB%A5%BC%20%EC%84%A4%EB%A6%BD%ED%96%88%EC%96%B4%EB%8F%84%20%ED%95%99%EC%83%9D%EB%93%A4%EC%97%90%EA%B2%8C%20%EA%B0%80%EB%A5%B4%EC%B9%A0%20%EA%B5%90%20%EC%9E%AC%EA%B0%80%20%EC%97%86%20%EC%96%B4%20%E3%80%8C%EC%B2%9C%EC%9E%90%20%EB%AC%B8j%20%EC%9D%B4%20%EB%82%98%20%E3%80%8E%EB%86%8D%EB%AA%BD%EC%84%A0%EC%8A%B5%E3%80%8F%2C%20%ED%98%B9%EC%9D%80%20%EC%A4%91%EA%B5%AD%EC%9D%98%20%EC%97%AD%EC%82%AC%20%EB%93%B1%EC%9D%84%20%EA%B5%90%EC%9C%A1%ED%95%98%20%EA%B3%A0%20%EC%9E%88%EB%8A%94%20%EC%83%81%ED%99%A9%EC%9D%B4%EC%97%88%EB%8B%A4%2C%20%EC%9D%BC%EB%B6%80%20%EC%9C%A0%EC%A7%80%EA%B0%80%EB%93%A4%EC%9D%B4%20%EC%B4%88%EB%93%B1%20%E2%80%A2%20%EC%A4%91%EB%93%B1%20%E2%80%A2%20%EC%A0%84%EB%AC%B8%20%EA%B5%90%EA%B3%BC%EC%84%9C%EB%A5%BC%20%ED%8E%B8%EC%88%A0%ED%95%98%EC%97%AC%20%EC%9D%B4%EC%A0%84%EC%97%90%20%EB%B9%84%ED%95%B4%20%EB%B9%84%EB%A1%9D%20%EC%82%AC%EC%A0%95%EC%9D%80%20%EC%A1%B0%EA%B8%88%20%EB%82%98%EC%95%84%EC%A1%8C%EC%9C%BC%EB%82%98%20%EC%9D%B4%20%EB%AA%A8%EB%91%90%EA%B0%80%20%EC%9A%B0%EB%A6%AC%20%EB%82%98%EB%9D%BC%EC%9D%98%20%EC%83%81%ED%99%A9%EC%97%90%20%EC%A0%81%ED%95%A9%ED%95%98%EA%B2%8C%20%EC%94%8C%EC%96%B4%EC%A7%84%20%EA%B2%83%EB%A7%8C%EC%9D%80%20%EC%95%84%EB%8B%88%EC%97%88%EB%8B%A4.

(3)(+0000148): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=851382.707010&q=%EC%A6%89%20%EB%8B%B9%EC%8B%9C%EB%8A%94%20%ED%95%99%EA%B5%90%EB%A5%BC%20%EC%84%A4%EB%A6%BD%ED%96%88%EC%96%B4%EB%8F%84%20%ED%95%99%EC%83%9D%EB%93%A4%EC%97%90%EA%B2%8C%20%EA%B0%80%EB%A5%B4%EC%B9%A0%20%EA%B5%90%20%EC%9E%AC%EA%B0%80%20%EC%97%86%20%EC%96%B4%20%E3%80%8C%EC%B2%9C%EC%9E%90%20%EB%AC%B8j%20%EC%9D%B4%20%EB%82%98%20%E3%80%8E%EB%86%8D%EB%AA%BD%EC%84%A0%EC%8A%B5%E3%80%8F%2C%20%ED%98%B9%EC%9D%80%20%EC%A4%91%EA%B5%AD%EC%9D%98%20%EC%97%AD%EC%82%AC%20%EB%93%B1%EC%9D%84%20%EA%B5%90%EC%9C%A1%ED%95%98%20%EA%B3%A0%20%EC%9E%88%EB%8A%94%20%EC%83%81%ED%99%A9%EC%9D%B4%EC%97%88%EB%8B%A4%2C%20%EC%9D%BC%EB%B6%80%20%EC%9C%A0%EC%A7%80%EA%B0%80%EB%93%A4%EC%9D%B4%20%EC%B4%88%EB%93%B1%20%E2%80%A2%20%EC%A4%91%EB%93%B1%20%E2%80%A2%20%EC%A0%84%EB%AC%B8%20%EA%B5%90%EA%B3%BC%EC%84%9C%EB%A5%BC%20%ED%8E%B8%EC%88%A0%ED%95%98%EC%97%AC%20%EC%9D%B4%EC%A0%84%EC%97%90%20%EB%B9%84%ED%95%B4%20%EB%B9%84%EB%A1%9D%20%EC%82%AC%EC%A0%95%EC%9D%80%20%EC%A1%B0%EA%B8%88%20%EB%82%98%EC%95%84%EC%A1%8C%EC%9C%BC%EB%82%98%20%EC%9D%B4%20%EB%AA%A8%EB%91%90%EA%B0%80%20%EC%9A%B0%EB%A6%AC%20%EB%82%98%EB%9D%BC%EC%9D%98%20%EC%83%81%ED%99%A9%EC%97%90%20%EC%A0%81%ED%95%A9%ED%95%98%EA%B2%8C%20%EC%94%8C%EC%96%B4%EC%A7%84%20%EA%B2%83%EB%A7%8C%EC%9D%80%20%EC%95%84%EB%8B%88%EC%97%88%EB%8B%A4. succeeded with 200

(3)(+0004667): [Translate for Zotero] runTranslationTask {}

(3)(+0000001): [Translate for Zotero] {"id":"LuNEtrSQ-1706333980267","type":"text","raw":"즉 당시는 학교를 설립했어도 학생들에게 가르칠 교 재가 없 어 「천자 문j 이 나 『농몽선습』, 혹은 중국의 역사 등을 교육하 고 있는 상황이었다, 일부 유지가들이 초등 • 중등 • 전문 교과서를 편술하여 이전에 비해 비록 사정은 조금 나아졌으나 이 모두가 우리 나라의 상황에 적합하게 씌어진 것만은 아니었다. 교 과 서 는 국가의 상 황","result":"","audio":[],"service":"google","candidateServices":[],"itemId":783,"status":"processing","extraTasks":[],"langfrom":"zh","langto":"zh-CN","callerID":"zoteropdftranslate@euclpts.com","secret":""}

(3)(+0000000): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=119457.517845&q=%EC%A6%89%20%EB%8B%B9%EC%8B%9C%EB%8A%94%20%ED%95%99%EA%B5%90%EB%A5%BC%20%EC%84%A4%EB%A6%BD%ED%96%88%EC%96%B4%EB%8F%84%20%ED%95%99%EC%83%9D%EB%93%A4%EC%97%90%EA%B2%8C%20%EA%B0%80%EB%A5%B4%EC%B9%A0%20%EA%B5%90%20%EC%9E%AC%EA%B0%80%20%EC%97%86%20%EC%96%B4%20%E3%80%8C%EC%B2%9C%EC%9E%90%20%EB%AC%B8j%20%EC%9D%B4%20%EB%82%98%20%E3%80%8E%EB%86%8D%EB%AA%BD%EC%84%A0%EC%8A%B5%E3%80%8F%2C%20%ED%98%B9%EC%9D%80%20%EC%A4%91%EA%B5%AD%EC%9D%98%20%EC%97%AD%EC%82%AC%20%EB%93%B1%EC%9D%84%20%EA%B5%90%EC%9C%A1%ED%95%98%20%EA%B3%A0%20%EC%9E%88%EB%8A%94%20%EC%83%81%ED%99%A9%EC%9D%B4%EC%97%88%EB%8B%A4%2C%20%EC%9D%BC%EB%B6%80%20%EC%9C%A0%EC%A7%80%EA%B0%80%EB%93%A4%EC%9D%B4%20%EC%B4%88%EB%93%B1%20%E2%80%A2%20%EC%A4%91%EB%93%B1%20%E2%80%A2%20%EC%A0%84%EB%AC%B8%20%EA%B5%90%EA%B3%BC%EC%84%9C%EB%A5%BC%20%ED%8E%B8%EC%88%A0%ED%95%98%EC%97%AC%20%EC%9D%B4%EC%A0%84%EC%97%90%20%EB%B9%84%ED%95%B4%20%EB%B9%84%EB%A1%9D%20%EC%82%AC%EC%A0%95%EC%9D%80%20%EC%A1%B0%EA%B8%88%20%EB%82%98%EC%95%84%EC%A1%8C%EC%9C%BC%EB%82%98%20%EC%9D%B4%20%EB%AA%A8%EB%91%90%EA%B0%80%20%EC%9A%B0%EB%A6%AC%20%EB%82%98%EB%9D%BC%EC%9D%98%20%EC%83%81%ED%99%A9%EC%97%90%20%EC%A0%81%ED%95%A9%ED%95%98%EA%B2%8C%20%EC%94%8C%EC%96%B4%EC%A7%84%20%EA%B2%83%EB%A7%8C%EC%9D%80%20%EC%95%84%EB%8B%88%EC%97%88%EB%8B%A4.%20%EA%B5%90%20%EA%B3%BC%20%EC%84%9C%20%EB%8A%94%20%EA%B5%AD%EA%B0%80%EC%9D%98%20%EC%83%81%20%ED%99%A9

(3)(+0000135): HTTP GET https://translate.google.com/translate_a/single?client=gtx&sl=zh&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=119457.517845&q=%EC%A6%89%20%EB%8B%B9%EC%8B%9C%EB%8A%94%20%ED%95%99%EA%B5%90%EB%A5%BC%20%EC%84%A4%EB%A6%BD%ED%96%88%EC%96%B4%EB%8F%84%20%ED%95%99%EC%83%9D%EB%93%A4%EC%97%90%EA%B2%8C%20%EA%B0%80%EB%A5%B4%EC%B9%A0%20%EA%B5%90%20%EC%9E%AC%EA%B0%80%20%EC%97%86%20%EC%96%B4%20%E3%80%8C%EC%B2%9C%EC%9E%90%20%EB%AC%B8j%20%EC%9D%B4%20%EB%82%98%20%E3%80%8E%EB%86%8D%EB%AA%BD%EC%84%A0%EC%8A%B5%E3%80%8F%2C%20%ED%98%B9%EC%9D%80%20%EC%A4%91%EA%B5%AD%EC%9D%98%20%EC%97%AD%EC%82%AC%20%EB%93%B1%EC%9D%84%20%EA%B5%90%EC%9C%A1%ED%95%98%20%EA%B3%A0%20%EC%9E%88%EB%8A%94%20%EC%83%81%ED%99%A9%EC%9D%B4%EC%97%88%EB%8B%A4%2C%20%EC%9D%BC%EB%B6%80%20%EC%9C%A0%EC%A7%80%EA%B0%80%EB%93%A4%EC%9D%B4%20%EC%B4%88%EB%93%B1%20%E2%80%A2%20%EC%A4%91%EB%93%B1%20%E2%80%A2%20%EC%A0%84%EB%AC%B8%20%EA%B5%90%EA%B3%BC%EC%84%9C%EB%A5%BC%20%ED%8E%B8%EC%88%A0%ED%95%98%EC%97%AC%20%EC%9D%B4%EC%A0%84%EC%97%90%20%EB%B9%84%ED%95%B4%20%EB%B9%84%EB%A1%9D%20%EC%82%AC%EC%A0%95%EC%9D%80%20%EC%A1%B0%EA%B8%88%20%EB%82%98%EC%95%84%EC%A1%8C%EC%9C%BC%EB%82%98%20%EC%9D%B4%20%EB%AA%A8%EB%91%90%EA%B0%80%20%EC%9A%B0%EB%A6%AC%20%EB%82%98%EB%9D%BC%EC%9D%98%20%EC%83%81%ED%99%A9%EC%97%90%20%EC%A0%81%ED%95%A9%ED%95%98%EA%B2%8C%20%EC%94%8C%EC%96%B4%EC%A7%84%20%EA%B2%83%EB%A7%8C%EC%9D%80%20%EC%95%84%EB%8B%88%EC%97%88%EB%8B%A4.%20%EA%B5%90%20%EA%B3%BC%20%EC%84%9C%20%EB%8A%94%20%EA%B5%AD%EA%B0%80%EC%9D%98%20%EC%83%81%20%ED%99%A9 succeeded with 200

(3)(+0002672): Starting full-text content processor

(4)(+0000001): Registering notifier observer 'fulltext_ZC' for [sync]

**Comment by windingwind** [comment]
检查文献language字段设置。

**Comment by historylbb** [comment]
> 检查文献language字段设置。

![QQ图片20240128202553](https://github.com/windingwind/zotero-pdf-translate/assets/157869253/8621a597-610f-437f-9ac2-c29595c1f8de)
去掉自动检测条目语言发现正常了！谢谢大佬！

**Comment by historylbb** [comment]
大佬您好，去掉自动检测条目语言虽然阅读日韩文献翻译正常了，但是阅读中文文献时，选中中文文献也会翻译了（原来选中自动检测条目语言不会翻译），然后翻译成乱码，虽然影响没有那么大，但还是希望这个bug能够得到大佬的完全解决。期待！
![QQ截图20240129114822](https://github.com/windingwind/zotero-pdf-translate/assets/157869253/e8e7e8af-ce2e-4ed6-9944-eda3cad289f7)
