### ISSUE TITLE
[Bug] 自动给notes添加翻译时，中文notes就不要翻译了

### ISSUE THREAD

**Issue by fredericky123** [windingwind/zotero-pdf-translate#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Mac OS
- Zotero Version: 7.0.0-beta.55+9151fb355
- Plugin Version:1.1.0-beta.30

### Describe the bug

自动给notes添加翻译时，中文notes就不要翻译了
翻译前加个判断应该就好了
![image](https://github.com/windingwind/zotero-pdf-translate/assets/13982749/dd5e4f27-ff32-404f-a7ad-0c01e02e711b)

### Debug Output

如上

**Comment by thebetter2** [comment]
这个问题是 你自己的中文文献的语言那一栏写的en，才会导致这个问题，改成zh就好了，不是插件的原因。

**Comment by fredericky123** [comment]
> 这个问题是 你自己的中文文献的语言那一栏写的en，才会导致这个问题，改成zh就好了，不是插件的原因。

不是唉，我的语言那里为zh，使用茉莉花导入的题录，元信息是准确的

**Comment by windingwind** [comment]
请截图插件设置页面，或提供debug output。我测试正常

**Comment by fredericky123** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/13982749/eda7ed3b-3df8-4450-b8ea-c2850b3c0069)
(5)(+0000046): CookieSandbox: Being paranoid about channel for api.zotero.org

(5)(+0000001): CookieSandbox: No Set-Cookie header received for api.zotero.org

(3)(+0000000): HTTP POST https://api.zotero.org/users/4680078/items succeeded with 200

(3)(+0000000): [ConcurrentCaller] Done with function (0/4 running, 0 queued)

(4)(+0000001): Tags haven't changed

(4)(+0000000): Relations have not changed for item 1/RE2E2Z8U

(4)(+0000000): Field 'dateAdded' has not changed

(4)(+0000000): Field 'dateModified' has not changed

(3)(+0000001): Saving to sync cache:

(3)(+0000000): [ "0": { "key": "RE2E2Z8U" "version": 49951 "library": { "type": "user" "id": 4680078 "name": "fred" "links": { "alternate": { "href": "https://www.zotero.org/fred" "type": "text/html" } } } "links": { "self": { "href": "https://api.zotero.org/users/4680078/items/RE2E2Z8U" "type": "application/json" } "alternate": { "href": "https://www.zotero.org/fred/items/RE2E2Z8U" "type": "text/html" } "up": { "href": "https://api.zotero.org/users/4680078/items/YAQHMHI7" "type": "application/json" } } "meta": {} "data": { "key": "RE2E2Z8U" "version": 49951 "parentItem": "YAQHMHI7" "itemType": "annotation" "annotationType": "highlight" "annotationText": "“ 大 众创 业， 万众创 新” 理 念提出以来， 我国政 府 对创业的支持力度不断加强“ ，十四五”规 划进一步强调， 要“推 进 创新创业创造向纵深发展" "annotationComment": "🔤自“大众创业，万众创新”理念提出以来，我国政府对创业的支持力度不断加强，“十四五”规划进一步强调，要“推进创新创业创造向纵深发展”。🔤" "annotationColor": "#ffd400" "annotationPageLabel": "233" "annotationSortIndex": "00000|000359|00528" "annotationPosition": "{\"pageIndex\":0,\"rects\":[[67.444,286.775,296.212,295.162],[51.024,271.375,301.055,279.762],[51.024,255.975,202.78,264.362]]}" "tags": [] "relations": {} "dateAdded": "2024-01-28T07:32:20Z" "dateModified": "2024-01-28T07:32:25Z" } } ]

(4)(+0000000): INSERT OR REPLACE INTO syncCache (libraryID, key, syncObjectTypeID, version, data) VALUES (?, ?, ?, ?, ?) [1, 'RE2E2Z8U', 3, 49951, '{"key":"RE2E2Z8U","version":49951,"library":{"type":"user","id":4680078,"name":"fred","links":{"alternate":{"href":"https://www.zotero.org/fred","type":"text/html"}}},"links":{"self":{"href":"https://api.zotero.org/users/4680078/items/RE2E2Z8U","type":"application/json"},"alternate":{"href":"https://www.zotero.org/fred/items/RE2E2Z8U","type":"text/html"},"up":{"href":"https://api.zotero.org/users/4680078/items/YAQHMHI7","type":"application/json"}},"meta":{},"data":{"key":"RE2E2Z8U","version":49951,"parentItem":"YAQHMHI7","itemType":"annotation","annotationType":"highlight","annotationText":"“ 大 众创 业， 万众创 新” 理 念提出以来， 我国政 府 对创业的支持力度不断加强“ ，十四五”规 划进一步强调， 要“推 进 创新创业创造向纵深发展","annotationComment":"🔤自“大众创业，万众创新”理念提出以来，我国政府对创业的支持力度不断加强，“十四五”规划进一步强调，要“推进创新创业创造向纵深发展”。🔤","annotationColor":"#ffd400","annotationPageLabel":"233","annotationSortIndex":"00000|000359|00528","annotationPosition":"{\"pageIndex\":0,\"rects\":[[67.444,286.775,296.212,295.162],[51.024,271.375,301.055,279.762],[51.024,255.975,202.78,264.362]]}","tags":[],"relations":{},"dateAdded":"2024-01-28T07:32:20Z","dateModified":"2024-01-28T07:32:25Z"}}']

(3)(+0000000): [ConcurrentCaller] All tasks are done

**Comment by windingwind** [comment]
<img width="800" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/33902321/e26418db-c846-439b-971f-a116da36fe95">

**Comment by fredericky123** [comment]
啊 谢谢 那里竟然一直为空
