### ISSUE TITLE
[Bug] 翻译窗口的宽度超出界面，导致文字显示不全

### ISSUE THREAD

**Issue by yue2388253** [windingwind/zotero-pdf-translate#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0
- Plugin Version: 1.1.0-beta.30

### Describe the bug

当翻译较多文字时，弹出的翻译窗口超出了zotero，导致文字显示不全。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/33801130/3b241c6b-f011-4764-b2cf-b4d71d3a5612)

### Debug Output

-

**Comment by zzlb0224** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/8912444/38f8bf63-aa4c-4e46-b494-c4940956e28b)
我也遇到了同样的问题，感觉这个可以调整浮动的位置来处理。

**Comment by zzlb0224** [comment]
建议判断一下最大宽度的一半和中心点的位置
