### ISSUE TITLE
最新版侧栏不显示

### ISSUE THREAD

**Issue by lisontowind** [windingwind/zotero-pdf-translate#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows11
- Zotero Version:  7.0.0-beta.55+9151fb355 
- Plugin Version: 1.1.0-beta.30

### Describe the bug

大大，zotero大改之后插件从侧栏消失了

### Debug Output

![image](https://github.com/windingwind/zotero-pdf-translate/assets/47842345/dfc1a188-f59d-470d-94ae-4f531860150b)

**Comment by nkh0472** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/67589323/099e018d-2096-446f-ba04-81367133f4e3)

补充说明：标题翻译和摘要翻译栏无法展开，仅单行高度；下面的其他栏高度是默认展开的

**Comment by BillZhangZT** [comment]
我也遇到了同样的问题

**Comment by Cahir-Lin** [comment]
same ques

**Comment by liuh16art** [comment]
i met same question

**Comment by cohesioncompany** [comment]
this is a common question

**Comment by tylzh97** [comment]
same question

**Comment by ustiniansy** [comment]
same question

**Comment by xingjianxu** [comment]
same question

**Comment by Brioal** [comment]
同样遇到了

**Comment by YuanfengZhang** [comment]
It seems that the interface of sidebar in zotero has been changed.

**Comment by nkh0472** [comment]
Please do not send the same reply repeatedly, as each participant will receive an email notification. You can use the emoji button to indicate agreement.

**Comment by tangyuep** [comment]
一样的问题

**Comment by warmxjg** [comment]
期待更新

**Comment by 13071558875** [comment]
求更新，还有中文文档谷歌翻译用不了，因为默认是中文翻译中文，但是中文文档里有些英文文献也想翻译

**Comment by leileilei2000** [comment]
我已解决，通过重新安装旧版本解决该问题

**Comment by ercaoeatting** [comment]
> 我已解决，通过重新安装旧版本解决该问题

但是会一直强制自动更新哇

**Comment by 13071558875** [comment]
> > 我已解决，通过重新安装旧版本解决该问题
> 
> 但是会一直强制自动更新哇

回退到beta54，然后编辑器里搜索update，关掉两个选项就好了

**Comment by ercaoeatting** [comment]
> > > 我已解决，通过重新安装旧版本解决该问题
> > 
> > 
> > 但是会一直强制自动更新哇
> 
> 回退到beta54，然后编辑器里搜索update，关掉两个选项就好了

我这样做了，但是有一天莫名其妙又给我更新了，看来还是等作者更新吧

**Comment by anshangtangyuan** [comment]
> > > 我已解决，通过重新安装旧版本解决该问题
> > 
> > 
> > 但是会一直强制自动更新哇
> 
> 回退到beta54，然后编辑器里搜索update，关掉两个选项就好了

他会强制更新的

**Comment by yzzmoon** [comment]
> > > 我已解决，通过重新安装旧版本解决该问题
> > 
> > 
> > 但是会一直强制自动更新哇
> 
> 回退到beta54，然后编辑器里搜索update，关掉两个选项就好了

您好，我想问问beta 54版本在哪里下载呀

**Comment by zxcvbnm12138** [comment]
同样的问题，求更新

**Comment by 13071558875** [comment]
> > 我已解决，通过重新安装旧版本解决该问题
> 
> 但是会一直强制自动更新哇

把update.exe改名，用个空文件改名成update.exe可以解决自动更新问题，后面想更新了就再改回来

**Comment by 13071558875** [comment]
> > > > 我已解决，通过重新安装旧版本解决该问题
> > > 
> > > 
> > > 但是会一直强制自动更新哇
> > 
> > 
> > 回退到beta54，然后编辑器里搜索update，关掉两个选项就好了
> 
> 他会强制更新的

把update.exe改名，用个空文件改名成update.exe可以解决自动更新问题，后面想更新了就再改回来

**Comment by MinanaYaa** [comment]
隔壁Zotero-style可以在侧边栏显示东西了，大佬快点修复修复

**Comment by anqiwen** [comment]
same question

**Comment by sasaju** [comment]
> 求更新，还有中文文档谷歌翻译用不了，因为默认是中文翻译中文，但是中文文档里有些英文文献也想翻译

可以尝试关掉这个选项
![image](https://github.com/windingwind/zotero-pdf-translate/assets/21136684/7908a594-0067-49c5-8629-a23b9286395c)

**Comment by XDevKoi** [comment]
话说7的旧版本在哪下？
