### ISSUE TITLE
[Feature]  求恢复条目标题切换为翻译后的中文

### ISSUE THREAD

**Issue by Lynn-x** [windingwind/zotero-pdf-translate#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Plugin Version:1.1.0-beta.30

### Describe the feature request

#654 
求恢复条目标题切换为翻译后的中文功能，或者在设置加个开关实现。笔记本小屏幕很难容下两个标题页，原来这个功能真的很实用，求作者恢复！

### Describe the solution you'd like

能否在设置里加个开关，这样可以兼顾不同需求。合并显示大幅提升了小屏幕阅读效率，真的很需要

**Comment by SHIChu1125** [comment]
同求恢复条目标题切换为翻译后的中文以及将翻译后的标题放在短标题栏内

**Comment by windingwind** [comment]
见既往issue。无计划实现此功能
