### ISSUE TITLE
[Feature] 下划线不翻译

### ISSUE THREAD

**Issue by fredericky123** [windingwind/zotero-pdf-translate#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Mac
- Zotero Version: 最新
- Plugin Version:beta 30

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
目前可以根据语言判断是否翻译注释
能否增加个设置，根据是下划线还是高亮，决定是否翻译

**Why do you need this feature?**
有的时候做注释，是因为重要方便以后阅读，想要实现下划线的不用自动翻译，而高亮的文本进行自动翻译

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
在侧边栏按需开启/关闭自动翻译批注即可（目前最新beta没有侧边栏，但那是另一个问题，与此请求无关）。感谢建议，但我认为不必要实现，此处关闭。

**Comment by fredericky123** [comment]
因为有些是单纯的想划重点，不需要翻译，区分开估计能省一半的流量；现在所有重点和难点都会翻译；需要自动翻译的难点还是挺多的，所以关闭自动翻译也不是很方便
不是当务之急，不过依然感谢

**Comment by windingwind** [comment]
感谢理解，之后有空了我会看看
