### ISSUE TITLE
[Bug] CTRL+T conflict with Zotero Style

### ISSUE THREAD

**Issue by fieri** [windingwind/zotero-pdf-translate#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows 11
- Zotero Version: latest
- Plugin Version: latest

### Describe the bug

install zotero 6 and latest version of Style and Translate plugin, Ctrl + T will not work.

### Debug Output

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml
Line Number 6, Column 12:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml" line: 6 column: 12 source: "    <label><html:h2>&zotero.zoteropdftranslate.pref.general.label;</html:h2></label>"}]

[JavaScript Error: "XML Parsing Error: undefined entity
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 3, Column 5:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 3 column: 5 source: "    <caption label="&zotero.zoteroreference.caption.refresh;" />"}]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 7, Column 7:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 7 column: 7 source: "      <html:h3>Functions</html:h3>"}]

[JavaScript Error: "Error: Target container is not a DOM element." {file: "resource://zotero/loader.jsm -> resource://zotero/react-dom.js" line: 26121}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml
Line Number 6, Column 12:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml" line: 6 column: 12 source: "    <label><html:h2>&zotero.zoteropdftranslate.pref.general.label;</html:h2></label>"}]

[JavaScript Error: "XML Parsing Error: undefined entity
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 3, Column 5:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 3 column: 5 source: "    <caption label="&zotero.zoteroreference.caption.refresh;" />"}]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 7, Column 7:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 7 column: 7 source: "      <html:h3>Functions</html:h3>"}]

[JavaScript Error: "Error: Target container is not a DOM element." {file: "resource://zotero/loader.jsm -> resource://zotero/react-dom.js" line: 26121}]

[JavaScript Error: "[Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: jar:file:///C:/Program%20Files%20(x86)/Zotero/omni.ja!/components/nsSidebar.js :: init :: line 15"  data: no]"]
init@jar:file:///C:/Program%20Files%20(x86)/Zotero/omni.ja!/components/nsSidebar.js:15:17
varDump@chrome://zotero/content/xpcom/utilities/utilities.js:1528:15
varDump@chrome://zotero/content/xpcom/utilities/utilities.js:1545:25
Zotero.Debug</this.log@chrome://zotero/content/xpcom/debug.js:92:17
debug@chrome://zotero/content/xpcom/zotero.js:1136:5
../zotero-plugin-toolkit/dist/basic.js/log/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js:678:19
log@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js:674:29
onInit/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js:16714:11
../zotero-plugin-toolkit/dist/managers/readerTabPanel.js/addReaderTabPanel/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js:2924:13
addReaderTabPanel@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js:2886:11

[JavaScript Error: "TypeError: _window.PDFViewerApplication.pdfDocument is null" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 16964}]

[JavaScript Error: "TypeError: can't access dead object" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 16958}]

[JavaScript Error: "TypeError: iframe is null" {file: "chrome://pdfpreview/content/scripts/index.js" line: 408}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml
Line Number 6, Column 12:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/preferences.xhtml" line: 6 column: 12 source: "    <label><html:h2>&zotero.zoteropdftranslate.pref.general.label;</html:h2></label>"}]

[JavaScript Error: "XML Parsing Error: undefined entity
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 3, Column 5:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 3 column: 5 source: "    <caption label="&zotero.zoteroreference.caption.refresh;" />"}]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 7, Column 7:" {file: "jar:file:///C:/Users/focus/AppData/Roaming/Zotero/Zotero/Profiles/i5bfobon.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 7 column: 7 source: "      <html:h3>Functions</html:h3>"}]

[JavaScript Error: "Error: Target container is not a DOM element." {file: "resource://zotero/loader.jsm -> resource://zotero/react-dom.js" line: 26121}]

version => 6.0.30, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.30, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.30, extension), Zotero Word for Windows Integration (6.0.3.SA.6.0.30, extension), Better BibTex for Zotero (6.7.160, extension), ZoteroPreview (0.1.6, extension), Sci-Hub Plugin for Zotero (1.4.4, extension), ZotFile (5.1.2, extension), Zotero PDF Preview (0.3.7, extension), Zotero PDF Translate (1.0.13, extension), Zutilo Utility for Zotero (3.10.0, extension), Zotero Reference (0.5.5, extension), Zotero Style (2.6.0, extension)

(3)(+0047143): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000001): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":34}}

(3)(+0000000): [Zotero Style] {}

(3)(+0000018): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000001): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":3}}

(3)(+0000002): [Zotero Style] {}

(3)(+0000024): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000000): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":10}}

(3)(+0000000): [Zotero Style] {}

(3)(+0000076): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000001): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":1}}

(3)(+0000000): [Zotero Style] {}

(3)(+0000020): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000001): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":5}}

(3)(+0000000): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000000): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":2}}

(3)(+0000000): [Zotero Style] {}

(3)(+0000017): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000001): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":3}}

(3)(+0000001): [Zotero Style] {}

(3)(+0000000): [Zotero Style] {"tag":"span","classList":["zoterostyle"],"styles":{"display":"inline-block","flex":"1"}}

(3)(+0000001): [Zotero Style] {}

(3)(+0000000): [Zotero Style] {"tag":"span","classList":["zoterostyle","number"],"styles":{"marginRight":"6px"},"properties":{"innerHTML":8}}

(3)(+0000001): [Zotero Style] {}

### Anything else?

no

**Comment by windingwind** [comment]
Z6 version is no longer maintained. Thanks for the report.
