### ISSUE TITLE
[Bug] zotero7beta55版本后翻译栏不显示了

### ISSUE THREAD

**Issue by dongrikeai** [windingwind/zotero-pdf-translate#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

zotero7beta55版本后翻译栏不显示了，作者大大能不能适配一下呀

### Debug Output

无

**Comment by night978** [comment]
同遇到这个问题

**Comment by Niu-XueLiang** [comment]
OS: win11
Zotero Version: 7.0.0-beta.60+91e1c6ca3 (64-bit)
Plugin Version: 1.1.0-beta.30

**Comment by wangkiwah** [comment]
期待更新

**Comment by windingwind** [comment]
#705
