### ISSUE TITLE
突然无法翻译，被加入黑名单

### ISSUE THREAD

**Issue by githuberiex** [windingwind/zotero-pdf-translate#72]
之前使用时没问题，今天开始选择PDF的内容进行翻译时出现如下问题：
**您的IP“ *** ”存在异常请求，且已被系统自动加入黑名单，请不要恶意进行爬取数据，谢谢。**

- 该插件设置如下图：

![image](https://user-images.githubusercontent.com/37798958/161948907-dfa63b32-ef96-4413-9bf1-4a0b8e2e7b09.png)

**Comment by windingwind** [comment]
see  #64 #57
