### ISSUE TITLE
[Feature] 弹出面板快速切换翻译服务按钮

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-pdf-translate#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macOS
- Zotero Version: v7
- Plugin Version: 最新版

### Describe the feature request

在面部增加翻译服务切换按钮，方便获得更好的翻译服务。

![image](https://github.com/windingwind/zotero-pdf-translate/assets/11771112/9d49f3a4-f1ac-4af8-bbbb-cff1bbbd20cf)

在设置中配置哪些服务显示在这里。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/11771112/03fa6e85-654d-4861-829b-f23bbc38b4cb)

**Comment by windingwind** [comment]
谢谢建议，不考虑在此处增加太多内容。
