### ISSUE TITLE
[Bug] 界面加载不全，出现白屏问题

### ISSUE THREAD

**Issue by shao12781566** [windingwind/zotero-pdf-translate#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0-beta.63+52856ae69
- Plugin Version:  1.1.0-beta.31

### Describe the bug

文件列表界面存在加载不全的问题，下拉后会出现白屏问题或明显的分页栏。通过列表设置关闭标题翻译后恢复正常

![Snipaste_2024-02-27_10-37-37](https://github.com/windingwind/zotero-pdf-translate/assets/57243196/f9089a00-f4d4-40be-9e48-9868f945539e)
![5ce3c046fe81eeb51c25072dff1fe8b6](https://github.com/windingwind/zotero-pdf-translate/assets/57243196/5c4ac179-cf5b-4274-a691-3ad083400f85)
![abf2c5c729c4b70731929fd201b754f](https://github.com/windingwind/zotero-pdf-translate/assets/57243196/a079db17-8812-4830-ba84-f7da3d8b4fde)
![Snipaste_2024-02-27_10-32-40](https://github.com/windingwind/zotero-pdf-translate/assets/57243196/295419db-160f-4aee-bf30-5e25cdf68520)
![Snipaste_2024-02-27_10-33-24](https://github.com/windingwind/zotero-pdf-translate/assets/57243196/ce478e2d-679a-48e5-96d0-60f6acc2d6c6)

**Comment by windingwind** [comment]
请禁用其他所有插件后复现。
另提问请尊重提问规范
