### ISSUE TITLE
[Bug] 使用ChatGPT翻译时，拼接模式出现问题

### ISSUE THREAD

**Issue by null147** [windingwind/zotero-pdf-translate#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [x] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

选择使用ChatGPT翻译时，遇到两段较长的进行Alt拼接，正在选中第二段的过程中会先开始翻译已选择的第一段，当第二段选择完成时，插件没有停止已将开始的第一段翻译的输出，造成两次翻译的内容会快速交替出现在结果窗口中。

### Debug Output

https://github.com/windingwind/zotero-pdf-translate/assets/20415961/8366c084-7b14-4d15-b895-fbc8f8ab2911

**Comment by hiyoungshen** [comment]
同样的翻译拼接出现问题，但问题略有不同，故借楼。

使用chatgpt翻译时，当使用如下翻译配置：

![image](https://github.com/windingwind/zotero-pdf-translate/assets/48718428/32672ef9-845f-464e-82d9-74766eee6450)

即关闭自动翻译。

操作：进行拼接翻译时，先选中一段，按住alt，选完另一段再松开alt。

问题：如果此时点击翻译，翻译插件会把选中的两段进行拼接翻译。但是当使用，Add to Note的时候，翻译却只会翻译第二段。

**Comment by hiyoungshen** [comment]
用的7.0.0-beta.64+8f8c0d079 (64-bit)

**Comment by lil-i321** [comment]
> 
> 问题：如果此时点击翻译，翻译插件会把选中的两段进行拼接翻译。但是当使用，Add to Note的时候，翻译却只会翻译第二段。

同样的问题。包括添加注释时。

**Comment by windingwind** [comment]
> 问题：如果此时点击翻译，翻译插件会把选中的两段进行拼接翻译。但是当使用，Add to Note的时候，翻译却只会翻译第二段。

add to note 不支持拼接。
