### ISSUE TITLE
[Feature] 翻译弹出窗口被边兰遮挡

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-pdf-translate#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macOS
- Zotero Version: 7.0
- Plugin Version: 最新版

### Describe the feature request

让弹出窗口显示之页面呢，单个词翻译被侧边栏遮挡了。
<img width="529" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/11771112/52e02076-649b-415a-8ed8-a9e40c860dff">

**Comment by zzlb0224** [comment]
能不能提升弹出窗口的z-index。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/8912444/9245a9ca-2976-4bd0-bdf3-9e74a6981e8b)

**Comment by windingwind** [comment]
弹窗涉及z本身，插件无法解决。建议使用侧边栏/单独窗口
至于最新z7beta没有侧边栏是另一个问题，与此处无关故关闭
