### ISSUE TITLE
[Feature] 标题和摘要翻译信息边栏不显示，显示在其他字段里

### ISSUE THREAD

**Issue by jackhanyuan** [windingwind/zotero-pdf-translate#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win11
- Zotero Version: 7.0.0-beta.64+8f8c0d079 (64-bit)
- Plugin Version: v1.1.0-beta.31

### Describe the feature request

标题和摘要翻译在信息边栏字段为空，显示在其他字段里。导致better notes笔记模板中${titleTranslation}获取不到

**Comment by gaojunyang666** [comment]
开发者您好，我来补充这个问题，在最新的beta版本中，出现了
![7eb4e559187d84cd3059caa6e7a8af7](https://github.com/windingwind/zotero-pdf-translate/assets/63088548/3f474430-30d9-4699-8cc3-29876bfffd21)
这样的标题和摘要翻译无法在上面显示的问题，尽管完成了标题和摘要翻译并且出现在“其它”字段，上面的这两部分内容始终是空白，正常情况下，也就是在上一个版本中，应该正常的被识别并且显示在上面，就像这样
![image](https://github.com/windingwind/zotero-pdf-translate/assets/63088548/e5581439-769b-4123-b875-d5ddfeb65a1b)

**Comment by hahaha9968** [comment]
${topItem.getField('extra').match(/^(.*?)(?=abstractTranslation:)/s)[0].replace(/^titleTranslation:\s*/, "")}我之前都是用这句代替模版里的${titleTranslation}，现在可以换回去了
