### ISSUE TITLE
[Bug] 安装不成功

### ISSUE THREAD

**Issue by Du11JK** [windingwind/zotero-pdf-translate#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macos 14.3.1
- Zotero Version: 7.0.0-beta.64+8f8c0d079
- Plugin Version: Release 1.1.0-beta.31

### Describe the bug

安装无响应
<img width="628" alt="Snipaste_2024-03-01_19-02-56" src="https://github.com/windingwind/zotero-pdf-translate/assets/48244012/e8dfebb3-9c99-4c3e-a6b8-cb9cd3330c5d">

### Debug Output

<img width="985" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/48244012/ae811067-d117-4402-97b0-c28d0bf7e182">

**Comment by windingwind** [comment]
请详细描述
