### ISSUE TITLE
请求功能，在标题翻译列中补充未翻译的中文题目

### ISSUE THREAD

**Issue by pisceswb** [windingwind/zotero-pdf-translate#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win11
- Zotero Version: 7 beat.65
- Plugin Version: 1.1.0-beta.31

### Describe the feature request

pdf-translate的翻译标题功能非常实用，非常感谢作者！

受限于屏幕尺寸，有时不能使原题目列和标题翻译列共同显示在窗口中，如果只显示标题翻译列的话，部分中文文献的题目是空白的。
请问作者能否将未翻译的中文题目也增加到标题翻译列中，这样就不用显示原题目列了，只显示标题翻译列就可以了。
为了方便区分中英文文献，可以在英文翻译题目前加标识，例如：
En_这是一个英文翻译题目
中文_这是一个中文题目

### Describe the solution you'd like

谢谢作者！

**Comment by trarer** [comment]
老版本有一个在标题列中显示翻译的功能，后来好像因为7.0出来后删除了。

**Comment by pisceswb** [comment]
> 老版本有一个在标题列中显示翻译的功能，后来好像因为7.0出来后删除了。

嗯。感觉平时隐藏标题列，使用标题翻译列用于看文献和整理文献。等在论文中引用文献时，显示标题列，确认题目的大小写等规范性。这样可能好些，不过当前的标题翻译列中未翻译的标题和中文标题都是空白，不能满足只显示翻译标题列时的使用情况。

**Comment by pisceswb** [comment]
另外建议，侧边栏中的标题翻译行能够自动回车显示成多行，这样能够看到完整的标题译文。

**Comment by pisceswb** [comment]
+1
