### ISSUE TITLE
论文无法翻译

### ISSUE THREAD

**Issue by baileichao** [windingwind/zotero-pdf-translate#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11 23H2
- Zotero Version:7.0.0-beta.65
- Plugin Version:1.1.0-beta.31

### Describe the bug

论文无法翻译，出现如下界面，
![image](https://github.com/windingwind/zotero-pdf-translate/assets/57392772/1abb4745-ecdd-48d6-bbb6-a45933a2dd29)
点击那个翻译的图标，还是原文，没有翻译的结果，
![image](https://github.com/windingwind/zotero-pdf-translate/assets/57392772/80f3b1c6-096c-4bc6-8112-4750242ca42e)
我试了下，好像就这篇论文是这个情况，其它的论文是能正常翻译的，并且设置里面也是从英文到中文，没有变成从英文到英文的状态。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/57392772/57e0d84e-cac5-460a-b7c5-e841077ccfce)

下面是该论文地址，由于论文比较大，上传不上来，我就不上传了。
https://www.sciencedirect.com/science/article/pii/S0012825224000564

### Debug Output

[Debug Output.zip](https://github.com/windingwind/zotero-pdf-translate/files/14505941/Debug.Output.zip)

**Comment by baileichao** [comment]
已经解决，要把语言里面改成en，就行了，

**Comment by clathrin** [comment]
您好，我也出现了这个问题。并且很奇怪，对于同一个论文PDF。如果通过下载PDF，再导入zotero，是可以正常翻译的；如果是通过zotero connector浏览器插件导入（附带PDF)zotero的，则不能正常翻译。但将zotero语言修改为en后可以正常翻译
