### ISSUE TITLE
[Bug]同一条目下只有第一个打开的文档会出现翻译栏

### ISSUE THREAD

**Issue by chenghao2262** [windingwind/zotero-pdf-translate#74]
**Describe the bug**
有一部分英文文档不会自动显示出翻译侧栏，但是可以自动在弹窗中翻译

**To Reproduce**
同一条目下只有第一个打开的文档会出现翻译栏
同一条目下有两个文档
第一个为文献本身
第二个为补充材料
打开第一个有翻译栏。再打开另一个就不会有翻译栏
需要将第一个关闭再打开另一个才会有翻译栏
当然此时再打开第一个就不会有翻译栏

**Screenshots**
正常
![image](https://user-images.githubusercontent.com/10097062/162191971-c8eb5d6b-da85-48a6-bdb8-526be8fbe784.png)
非正常
![image](https://user-images.githubusercontent.com/10097062/162192025-33d73f7b-77d0-44ec-9ab0-8e71a8ef04a5.png)

**Environment**
 - OS: Windows
 - Zotero Version(Help->About Zotero) 6.0.4
 - Addon Version(Tools->Add-ons) 0.3.2

**Comment by windingwind** [comment]
fixed in v0.3.21

**Comment by windingwind** [comment]
是的，目前三个以上没有办法。没法找到侧栏和文档的一一对应，zotero的接口不完善
