### ISSUE TITLE
[Feature] 请求支持自定义gemini模型版本

### ISSUE THREAD

**Issue by lokiter** [windingwind/zotero-pdf-translate#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10 21H2
- Zotero Version: 7.0.0-beta.65
- Plugin Version:1.1.0-beta.33

### Describe the feature request

gemini模型现在支持选择ggemini-1.5-pro-latest、gemini-1.0各个版本，希望能够像openai支持选择不同的模型或者自定以模型名称
https://ai.google.dev/models/gemini?hl=en#model-variations
![image](https://github.com/windingwind/zotero-pdf-translate/assets/74828715/cb448ce1-b23d-44c3-96bb-87a46a14131d)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/74828715/e8a4ffbc-446f-41c1-8c7b-deaa5caf04f4)

### Describe the solution you'd like

希望在现有基础上增加模型切换，谢谢！

**Comment by sasaju** [comment]
gemini-1.5-pro-latest我还没申请到，这个版本现在有提供API吗。翻了翻文档应该是还没有，https://ai.google.dev/tutorials/rest_quickstart?hl=en#text-only_input

**Comment by YouJiacheng** [comment]
把接口url改了就行，比如Gemini 1.5 Flash
https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
