### ISSUE TITLE
最新版小牛翻译登录环境异常与翻译不成功但调用字符[Bug] 

### ISSUE THREAD

**Issue by Qingchan2020** [windingwind/zotero-pdf-translate#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Windows 11 
- Zotero Version: 7.0
- Plugin Version:1.1.1-beta.33

### Describe the bug

更新了zotero7.0之后，插件登录小牛翻译引擎显示登录网络环境异常。禁用其他插件后，登录成功，但是不能翻译不成功，小牛控制台显示一直在调用字符

### Debug Output

![1709992883182](https://github.com/windingwind/zotero-pdf-translate/assets/162801963/52c8ab1f-df5d-4514-9fac-b59424c6f304)

**Comment by Qingchan2020** [comment]
小牛翻译引擎与茉莉花插件冲突，启用茉莉花插件时候，登录小牛翻译引擎显示：登录网络环境异常

**Comment by Qingchan2020** [comment]
今天检测出：

**Comment by Qingchan2020** [comment]
今天检测出：小牛翻译引擎与茉莉花插件冲突，启用茉莉花插件，登录小牛翻译引擎显示登录网络环境异常。禁用后就没有问题
![1710036435438](https://github.com/windingwind/zotero-pdf-translate/assets/162801963/b7751dbe-f403-4e66-8985-e259046697bb)
![1710036494870](https://github.com/windingwind/zotero-pdf-translate/assets/162801963/b768c4a2-5260-4155-b46b-0a35f9f55e3a)

**Comment by windingwind** [comment]
如果禁用其他所有插件正常，则请向导致问题的插件作者反映。此处暂时关闭

**Comment by LZJ10086** [comment]
朋友，你解决这个问题了吗

**Comment by y3477619** [comment]
好像真的是因为茉莉花插件的原因，我关掉以后，翻译插件能够正常使用了

**Comment by Chapoly1305** [comment]
可能有关。
https://github.com/windingwind/zotero-pdf-translate/issues/1146
https://github.com/windingwind/zotero-pdf-translate/pull/1168
