### ISSUE TITLE
[Bug] 标题翻译栏目不能固定宽度，注释翻译的相关功能失效

### ISSUE THREAD

**Issue by Sinoftj** [windingwind/zotero-pdf-translate#748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 7
- Plugin Version: all

### Describe the bug

![WX20240313-001145@2x](https://github.com/windingwind/zotero-pdf-translate/assets/118784753/17e3d54b-7361-4c97-907c-4487c5166e86)
可以看到，选择了“存在笔记本身”的时候，还是会在注释评论中翻译，且因为默认不翻译中文，就把标点翻译出来了。

![WX20240313-094805@2x](https://github.com/windingwind/zotero-pdf-translate/assets/118784753/9001d213-becc-4d23-a62f-5c89c207dd34)
从1.1.0-beta.27版本后，“标题翻译”栏，每次重启的时候，都会回到默认的宽度和位置，无法记忆。

### Debug Output

无

**Comment by windingwind** [comment]
Please provide debug output
