### ISSUE TITLE
[Bug]some annotation can be translated automatically, but some annotations can't be translated. I don't why?

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-pdf-translate#75]
some annotation can be translated automatically, but some annotations can't be translated. I don't why?
![屏幕截图 2022-04-08 101930](https://user-images.githubusercontent.com/25714958/162350377-f3b868d1-e9e4-4ad3-a4e4-00b180056e7f.png)
![屏幕截图 2022-04-08 101950](https://user-images.githubusercontent.com/25714958/162350384-df9bbf91-7014-42cb-810c-5c8dc64bc4c4.png)

_Originally posted by @chunyanghu in https://github.com/windingwind/zotero-pdf-translate/issues/69#issuecomment-1092377595_

**Comment by windingwind** [comment]
@chunyanghu I need more information.

**Comment by chunyanghu** [comment]
> @chunyanghu I need more information.
When I highlight some sentences, they will be translated, and add annotations, but sometimes, they won't be translated.

**Comment by chunyanghu** [comment]
![屏幕截图 2022-04-08 113154](https://user-images.githubusercontent.com/25714958/162357443-36898f2b-761a-4d5c-9124-cd6ab853434b.png)
For example, I select two pieces of sentences in the same way, the first one is translated, but the second one isn't translated. I don't know why.

**Comment by windingwind** [comment]
Follow the debug steps in #6

**Comment by XujqGitHub** [comment]
I've encountered the same problem. This feature is functional in some PDFs but not in others. I have test three PDF files. Only one PDF works well.
![zoterotranslatbug1](https://user-images.githubusercontent.com/35099240/162451316-fb0a025d-8a8e-4011-8efd-71c2fd738c4d.png)
![zoterotranslatbug2](https://user-images.githubusercontent.com/35099240/162452060-2b79b489-3449-44c3-bbff-93075dba82b4.png)

**Comment by windingwind** [comment]
@XujqGitHub I need more detailed information to help you. Please follow the debug steps in https://github.com/windingwind/zotero-pdf-translate/issues/6

**Comment by XujqGitHub** [comment]
@windingwind like this？https://github.com/windingwind/zotero-pdf-translate/issues/6#issuecomment-1078768099
version => 6.0.4, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.4, extensions => Zotero LibreOffice Integration (6.0.0.SA.6.0.4, extension), Zotero Word for Windows Integration (6.0.0.SA.6.0.4, extension), Zotero Update IFs (0.91.0, extension), Better BibTex for Zotero (6.4.3, extension), Zotero PDF Translate (0.4.1, extension)

(3)(+0011580): Viewing attachment 1/N28QFMZQ

(3)(+0000004): Opening D:\Xujq\Zotero\storage\N28QFMZQ\Matsuki et al. - 2019 - Bilateral Drive Gear—A Highly Backdrivable Reducti.pdf

(3)(+0000001): Notifier.trigger('open', 'file', [373]) called [observers: 6]

(3)(+0000010): Notifier.trigger('add', 'tab', [tab-tq9KYM2S], {"tab-tq9KYM2S":{"itemID":373}}) called [observers: 5]

(3)(+0000005): Notifier.trigger('select', 'tab', [tab-tq9KYM2S], {"tab-tq9KYM2S":{"type":"reader"}}) called [observers: 5]

(3)(+0000006): ZoteroPDFTranslate: open attachment event detected.

(3)(+0000001): ZoteroPDFTranslate: Update Translate Panels

(3)(+0000000): ZoteroPDFTranslate.bindAddToNote

(3)(+0000022): Refreshing item box

(3)(+0000027): ZoteroPDFTranslate: open window event detected.

(3)(+0000112): Getting contents of D:\Xujq\Zotero\storage\N28QFMZQ\.zotero-pdf-state

(3)(+0000055): ZoteroPDFTranslate: buildSideBarPanel

(3)(+0000085): itemTree.render(). Displaying Item Tree

(3)(+0011291): ZoteroPDFTranslate: onTranslate. language disable=false

(3)(+0000000): ZoteroPDFTranslate: buildPopupPanel

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0001002): Creating notifier queue Wbxsy4gd
