### ISSUE TITLE
[Bug] alt拼接模式失效，侧边栏显示失效

### ISSUE THREAD

**Issue by zifeiyu1999** [windingwind/zotero-pdf-translate#750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11
- Zotero Version: 7.0.0-beta.66
- Plugin Version:1.1.0-23

### Describe the bug

alt拼接模式失效，侧边栏显示失效，请大佬有时间更新修复一下啊，拼接模式不能用太难受了

### Debug Output

1111111

**Comment by MinanaYaa** [comment]
新版UI大改了，侧边栏API失效了，等大佬修复吧， #705

**Comment by Piagari** [comment]
嗯，好的



---- 回复的原邮件 ----
| 发件人 | Zheng ***@***.***> |
| 日期 | 2024年03月15日 09:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] [Bug] alt拼接模式失效，侧边栏显示失效 (Issue #750) |

新版UI大改了，侧边栏API失效了，等大佬修复吧， #705

**Comment by Mrscatdog** [comment]
急需修复侧边栏，只显示弹窗太难受了

**Comment by Piagari** [comment]
确实，我是6转7的，之前看文献一直喜欢用测栏。现在弹窗翻译感觉使用自动翻译比之前翻译速度变慢了。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月15日 16:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] [Bug] alt拼接模式失效，侧边栏显示失效 (Issue #750) |

急需修复侧边栏，只显示弹窗太难受了

**Comment by zearo-github** [comment]
希望大佬能及时看到，修复bug

**Comment by thwyyyyy** [comment]
同求，没有侧边用着很难受
