### ISSUE TITLE
[Bug] 标题翻译栏目不能固定宽度，注释翻译的相关功能失效

### ISSUE THREAD

**Issue by Sinoftj** [windingwind/zotero-pdf-translate#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Mac OS 14
- Zotero Version:  7.0.0-beta.65+b047f3d90
- Plugin Version: lasted

### Describe the bug

**如图所示，一旦选择“存在笔记本身”，还是会在评论中出现，由于不翻译中文，只会留下符号。**
![WX20240313-222509@2x](https://github.com/windingwind/zotero-pdf-translate/assets/118784753/6fc9fea0-cd29-4d8b-9ea8-45ba6214208f)

**额外说一下，英文文献翻译的时候，也会把人名、年份进行翻译，但是这是多余的，是否可以增加一个功能，进行规避？**

![312282620-9001d213-becc-4d23-a62f-5c89c207dd34](https://github.com/windingwind/zotero-pdf-translate/assets/118784753/50d2adf7-1c7b-4efe-b7e0-ce62e2cd3762)
每次重启，该栏的宽度都会失效，需要重新设置，且发生在1.1.0-beta.27后面的每一个版本上。

### Debug Output

<img width="1721" alt="截屏2024-03-13 22 21 46" src="https://github.com/windingwind/zotero-pdf-translate/assets/118784753/4b5a932a-9bf0-4452-a72f-9a92b41070ed">

**Comment by windingwind** [comment]
1. update to the latest version. the custom column width bug should have been fixed.
2. please provide valid debug output following the steps. your screenshot does not contain any useful information.

**Comment by Sinoftj** [comment]
我觉得提供这个debug是非常困难的事情，因为它总是频繁且随机的出现。只要开启对应的功能就会这样。

**Comment by windingwind** [comment]
我无法复现，如果用户也无法提供调试输出，则无可能修复或定位问题。

**Comment by Sinoftj** [comment]
[debug.txt](https://github.com/windingwind/zotero-pdf-translate/files/14618139/debug.txt)
我不确定这是否可以让您从中找到一些问题，我是在第一时间出现这个bug后导出的日志。

**Comment by windingwind** [comment]
> 如图所示，一旦选择“存在笔记本身”，还是会在评论中出现，由于不翻译中文，只会留下符号。

根据给的截图，确定侧边栏显示的注释是按照当前的设置进行的吗？看起来原文是英文文献而注释文本是中文。是否是先前未修改注释翻译位置时的做注释？

**Comment by Sinoftj** [comment]
![WX20240316-115135@2x](https://github.com/windingwind/zotero-pdf-translate/assets/118784753/87c411f9-0347-4c9c-8dd6-6981e4de5b59)

一开始，我开启了自动翻译批注（注释），并选择了“存在笔记评论”，这样的话，我每次进行批注的时候，会将翻译结果，自动存在注释的评论中。

但是我认为这样不适合，所以我取消了勾选“存在笔记评论”，选择了“存在笔记本身”，这样一旦进行批注的时候，插件就会对批注进行翻译，替换原来的英文内容。按理说，此时插件对某一个注释的翻译工作应该结束了。

但是，Bug就在这里出现了，插件再次已经对已经完成翻译的注释进行了再次翻译。但此时，注释已经变成了中文，所以只翻译了非中文的相关符号。

**Comment by windingwind** [comment]
我推测是你有另一台设置了自动翻译批注+翻译批注到评论的电脑B，在将你当前电脑A的内容自动同步过去的时候，再次触发了翻译，并保存到了评论。

**Comment by Sinoftj** [comment]
可能您说的是正确的，我调整了另一台电脑的设置，进行了统一，目前没有出现过这样的情况了。
