### ISSUE TITLE
开启翻译插件后，会导致隔壁sytle插件中的期刊标签显示不完全

### ISSUE THREAD

**Issue by baileichao** [windingwind/zotero-pdf-translate#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11，23H2
- Zotero Version:7.0.0-beta.68
- Plugin Version:1.1.0-beta.37

### Describe the bug

问题如题目，说是有的插件代码还是什么有点老，需要更新，希望大佬可以优化，感谢感谢。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/57392772/223e04d8-1fd9-4691-ac1b-a6fa078f29d5)

### Debug Output

无。

**Comment by windingwind** [comment]
其他插件问题与本插件无关，请向对应作者反馈
