### ISSUE TITLE
Why not support GPT3.5-0125-preview or other optional models, such as gpt4 ?[Feature] 

### ISSUE THREAD

**Issue by McKinleyLu** [windingwind/zotero-pdf-translate#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS:  Windows 11 23H2
- Zotero Version: 6.0.0
- Plugin Version: 1.0.25

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**
GPT3.5 has wrong translation results.

**Alternatives you've considered**
If it supports GPT3.5-0125 and GPT4 models, the translation results will be better.

### Anything else?

Nothing

**Comment by windingwind** [comment]
We do. You can change the model in settings.

<img width="245" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/33902321/958d0d1a-5273-4460-b5e6-c70c5babf983">
