### ISSUE TITLE
[Bug] zotero6版本的插件是否支持gemini？

### ISSUE THREAD

**Issue by SugarMuzi** [windingwind/zotero-pdf-translate#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macos
- Zotero Version: 6.0.37
- Plugin Version:1.0.25

### Describe the bug

我在issues中搜索到已经添加了对gemini的支持，因此，我找到了#669所对应的版本如下图：
![image](https://github.com/windingwind/zotero-pdf-translate/assets/125560403/61251133-37b0-441c-9c87-42145f4b01b0)
但是，我在安装这个插件的时候报错，显示不兼容当前zotero版本，因此是否对gemini的支持不在zotero6版本的插件中？是否可以同步更新到zotero6的插件中

### Debug Output

<img width="435" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/125560403/d25f6459-54ea-470a-8f6f-00762fe3bed1">

**Comment by sasaju** [comment]
> gemini的支持不在zotero6版本的插件中？
是的

**Comment by windingwind** [comment]
无计划对z6版本提供更多支持，只维护最新版本。

**Comment by GrayXu** [comment]
可以用one-hub/one-api做一次中转，然后以GPT入口来调用gemini
