### ISSUE TITLE
[Feature]  Zotero 6 still dont have a malayalam language

### ISSUE THREAD

**Issue by BoseJohnson** [windingwind/zotero-pdf-translate#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: w 10
- Zotero Version: 6
- Plugin Version:latest stable

### Describe the feature request

I had mentioned this issue before , But the solution (fix) only available for zotero 7 users. Some plugins I am using couldnt cope with zotero 7. So I had to switch between zotero 6 for majority of my work and zotero 7 for translation only ( because no malayalam language in zotero 6) . this switch become a major issue for my work flow.

### Describe the solution you'd like

If you can add "malayalam " in zotero 6 iam very much thankful to you .

**Comment by windingwind** [comment]
Sorry, I didn't notice your request is the Z6 version. As mentioned in the issue template:

> Only bug reports that can be reproduced on the latest Zotero and plugin will be considered.

But anyway, if you need, I can compile a Z6 version for you here.

**Comment by BoseJohnson** [comment]
Yes please. that would be fine.

**Comment by windingwind** [comment]
[zotero-pdf-translate.xpi.zip](https://github.com/windingwind/zotero-pdf-translate/files/14729936/zotero-pdf-translate.xpi.zip)

I didn't test since I no longer use z6, please check. Unzip and install the `xpi`.

**Comment by BoseJohnson** [comment]
That works.You just made my day!

**Comment by BoseJohnson** [comment]
Sorry , auto translation of this language not working, also no translation option for the 2nd split screen (view option) .

**Comment by windingwind** [comment]
OK, since I don't have time to debug this history version, please install the version from the release page that works for you and follow these steps:

1. Open Preferences
2. Advanced - Config Editor
3. Search `extensions.zotero.ZoteroPDFTranslate.sourceLanguage` and set it to `ml`.

Let me know if it does not work for you.

**Comment by BoseJohnson** [comment]
i tried but worked only once. But through this process I could understand that the auto-translation didnt work because something got wrong with my pdf. Then one you had compiled for me was fine.(though not the split screen issue, but iam okay with this) . I think no further issue will show.

**Comment by windingwind** [comment]
Only Z7 supports translation in the standalone window, which is not a bug but something not implemented on Z6.

**Comment by BoseJohnson** [comment]
I understood.I dont know I think this might help you.That is one of the two split screens ( view→split horizontally ) does not show pop up (translation) window .

**Comment by windingwind** [comment]
Thanks for the clarification. The answer is same here - we need an official API from Z7 to implement this feature.
