### ISSUE TITLE
[Bug] extension built on commit a859ecc failed to popup.

### ISSUE THREAD

**Issue by Lslightly** [windingwind/zotero-pdf-translate#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows11
- Zotero Version: 6.0.36
- Plugin Version: 1.0.25

### Describe the bug

The released extension at [github release](https://github.com/windingwind/zotero-pdf-translate/releases/tag/v1.0.25) can popup the translation but the generated version can not.

steps to reproduce the bug.

```bash
git clone https://github.com/windingwind/zotero-pdf-translate.git
cd zotero-pdf-translate
git checkout z6
git reset --hard a859ecc
```

Then change the `devDependencies` in `package.json` by replacing all `^` with empty string. The reason is that `^` will use the newest version of dependency, whose interfaces have changed. Especially, `zotero-types` has many differences between `1.0.13` and `1.3.20`. Then build the extension.

```bash
npm install
npm run build
```

Then install this extension in zotero and restart the zotero. After that, disable and then re-enable the extension to make the settings of the extension available in the preference menu of zotero. Use the following settings. 

![image](https://github.com/windingwind/zotero-pdf-translate/assets/57594668/18593a8f-2e4b-4a08-8e74-004ec159d834)

Then select a word in English and there is no popup. See the following image.

![image](https://github.com/windingwind/zotero-pdf-translate/assets/57594668/5cce7422-fb83-4ef0-95dd-e390bb93f900)

### Debug Output

[JavaScript Error: "WeakRef is not defined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js" line: 7242}] createElement@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:7242:17 addStyle@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:9857:25 initializeUI@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:9402:11 node_modules/zotero-plugin-toolkit/dist/managers/prompt.js/Prompt<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:9396:11 node_modules/zotero-plugin-toolkit/dist/managers/prompt.js/PromptManager2<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:10027:36 ZToolkit<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:14182:21 Addon<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:14150:19 @resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:14209:25 @resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/index.js:2:1 startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Lslightly/AppData/Roaming/Zotero/Zotero/Profiles/chia1tlx.default/extensions/zoteropdftranslate@euclpts.com.xpi!/bootstrap.js:94:3

**Comment by windingwind** [comment]
You may check the version of `zotero-plugin-toolkit`. It should be `<2.1.8`
