### ISSUE TITLE
正则表达，避免人名及年份翻译

### ISSUE THREAD

**Issue by Sinoftj** [windingwind/zotero-pdf-translate#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Mac os 14.1
- Zotero Version: lasted
- Plugin Version:lasted

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
在进行翻译的时候，虽然可以设置不翻译中文，但是这可能不够，因为它还是会翻译作者和年份。就像截图中展示的一样。

**Why do you need this feature?**
我想这可能会带来2个问题，一是让注释看起来很混乱，二是翻译成中文，反而可能不知道作者是谁了。

<img width="275" alt="截屏2024-03-27 10 01 57" src="https://github.com/windingwind/zotero-pdf-translate/assets/118784753/6c3f1c7e-e8ba-441c-906d-d1ffe8b5e8cb">

### Describe the solution you'd like

**The solution you'd like**
例如，可以增加正则表达：\(([^)]+?,\s?\d{4}(;\s?[^)]+?,\s?\d{4})*\))
匹配和保留括号内的作者和年份，同时允许翻译文本中的其他部分

**Comment by windingwind** [comment]
谢谢建议，但无法实现。翻译服务依赖上下文
