### ISSUE TITLE
[Bug] 使用谷歌api翻译俄语文献时，仍然有大量俄语不翻译。

### ISSUE THREAD

**Issue by Caserpzz** [windingwind/zotero-pdf-translate#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 家庭中文版 22H2
- Zotero Version: 7.0.0-beta.68+c31a40c74 (64-bit)
- Plugin Version:1.1.0-beta.38

### Describe the bug

![image](https://github.com/windingwind/zotero-pdf-translate/assets/143203566/53417e22-26fa-4100-be64-9d3c56278bfc)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/143203566/1d20ef21-3aa6-4e19-80da-cac403d1449a)

### Debug Output

[Debug Output.zip](https://github.com/windingwind/zotero-pdf-translate/files/14804937/Debug.Output.zip)

**Comment by windingwind** [comment]
debug output无有效信息，请严格按照说明步骤记录debug output
