### ISSUE TITLE
Not installable in Zotero 7 Beta

### ISSUE THREAD

**Issue by ngasoft** [windingwind/zotero-pdf-translate#770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Ubuntu 22.04
- Zotero Version: 7 Beta
- Plugin Version: 1.0.25

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate?tab=readme-ov-file#install
