### ISSUE TITLE
[Bug] 置顶小窗口导致切换窗口后点击原生zotero窗口无反应

### ISSUE THREAD

**Issue by dzylikecode** [windingwind/zotero-pdf-translate#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 6.0.36
- Plugin Version: 1.0.25

### Describe the bug

打开翻译的小窗口,置顶,然后切换到后天或者打开其他的应用使得zotero不在最顶层. 点击zotera窗口,没有反应

### Debug Output

输出正常

### Anything else?

需要先点击小窗口的界面让它到最顶层,再点击zotera才会弹出

**Comment by windingwind** [comment]
感谢反馈，此问题无法解决
