### ISSUE TITLE
突然无法自动翻译

### ISSUE THREAD

**Issue by keaideliaojun** [windingwind/zotero-pdf-translate#773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0
- Plugin Version:1.1.0-beta.38

### Describe the bug

上午用着用着突然选中后，尽管设置了自动翻译，仍不不能自动翻译，同时显示翻译键和添加笔记键，但是点击翻译后仍无法正常翻译。如下图
![image](https://github.com/windingwind/zotero-pdf-translate/assets/94065935/e163fd80-78d7-4437-a59f-b67f882ab0bc)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/94065935/65850802-4a35-4789-a654-d9c7da1e96d0)
但是添加批注后，批注内显示翻译内容。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/94065935/c1589d6d-8a77-4b37-9f66-918c60bdd5e6)
翻译设置页面
![image](https://github.com/windingwind/zotero-pdf-translate/assets/94065935/52fd5535-4ea3-4277-9655-1ff2428b866d)

### Debug Output

[Debug Output.txt](https://github.com/windingwind/zotero-pdf-translate/files/14914273/Debug.Output.txt)

**Comment by gwx06** [comment]
同样问题，求解决

**Comment by BoseJohnson** [comment]
Same issue + No standalone window

**Comment by yanan0122** [comment]
同样问题🙋‍♂️

**Comment by blankiee1024** [comment]
同样的问题，突然无法翻译，出现一个窗口
![截屏2024-04-09 下午3 41 38](https://github.com/windingwind/zotero-pdf-translate/assets/103927754/336e4565-ca31-4b6a-9ea4-6964725edc96)

**Comment by windingwind** [comment]
please update plugin

**Comment by keaideliaojun** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/94065935/69ab9e82-ea33-4f13-90bf-dbe0b7fe0c25)

**Comment by windingwind** [comment]
please update to zotero7 beta70

**Comment by ptv666** [comment]
同样的问题

**Comment by grdivg** [comment]
same problem

**Comment by keaideliaojun** [comment]
各位更新软件后，再更新插件就好了，感谢作者！！！
