### ISSUE TITLE
[Feature] 调整插件在侧边栏中的位置

### ISSUE THREAD

**Issue by lisontowind** [windingwind/zotero-pdf-translate#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0-beta.72+128a540af (64-bit)
- Plugin Version: 1.1.0-beta.40

### Describe the feature request

**Why do you need this feature?**
侧边栏翻译窗口和其他信息栏混在一起，滑动起来稍微有点奇怪。

### Describe the solution you'd like

**The solution you'd like**
是否可以像侧边栏的笔记一样拥有一个独立的显示

**Comment by windingwind** [comment]
谢谢建议，不做考虑
