### ISSUE TITLE
[Bug] 插件可能与Zotero Reference/Style有冲突？

### ISSUE THREAD

**Issue by AlbireoBai** [windingwind/zotero-pdf-translate#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 7.0.0-beta.72+128a540af (64-bit）
- Plugin Version: 1.1.0-beta-40

### Describe the bug

1.1.0-beta-40大约发布6小时后安装，刚刚安装时可以正常使用，但一觉醒来，所有的免费翻译服务均有如下报错（这里以Google为例，同时我确定可以正常使用google服务）：
‘’‘[请求错误]\n\n此翻译引擎不可用，可能是密钥错误，也可能是请求过快。\n可以尝试其他翻译引擎，或者来此查看相关回答：\nhttps://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f \n\n请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： Google
Error: 连接至服务器时发生错误。请检查网络连接。’‘’
我多次尝试重装插件并重启软件和电脑后仍然显示相同报错，因此准备上报Issue.
但在”Disable all other plugins（Zotero Reference/Style）, exit Zotero, and restart Zotero“之后，translate又完全恢复正常了，并且remove translate重新安装后也没有发生相同报错...@-@

### Debug Output

（很抱歉没能复现这一bug，以下是重装translate后无Error的Debug Output，不知道会不会有所帮助）
1712736507233	addons.xpi	WARN	Checking D:\Program\Working\Zotero7\distribution\extensions for addons

1712736508361	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1712736508392	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712736509129	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "r is undefined" {file: "jar:file:///C:/Users/21062/AppData/Roaming/Zotero/Zotero/Profiles/weacohlo.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 145}]

[JavaScript Error: "r is undefined" {file: "jar:file:///C:/Users/21062/AppData/Roaming/Zotero/Zotero/Profiles/weacohlo.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 145}]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Upload request 1/26DYW6YA failed"]

[JavaScript Error: "您的 Zotero 文件存储配额已经达到，有些文件将不能上传。Zotero 的其他数据将继续同步到 Zotero 服务器。

在 zotero.org 的帐户设置里查看更多的存储选项。

Muiruri 等 - 2022 - Numerical Simulation of High Strain Rate and Temperature Properties of Laser Powder Bed Fusion Ti6Al.pdf (8145 KB)"]

[JavaScript Error: "Upload request 1/2N56PQLU failed"]

[JavaScript Error: "您的 Zotero 文件存储配额已经达到，有些文件将不能上传。Zotero 的其他数据将继续同步到 Zotero 服务器。

在 zotero.org 的帐户设置里查看更多的存储选项。

理论力学_同济.pdf (53427 KB)"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

appName => Zotero, version => 7.0.0-beta.72+128a540af, os => Windows 10.0 22631, locale => zh-CN, extensions => Translate for Zotero (1.1.0-beta.40, extension), Zotero Style (2.6.7, extension, disabled), Zotero Reference (0.5.8, extension, disabled)

**Comment by duofengzhiling** [comment]
翻译一栏只能无法更改源语言

**Comment by congmoyue** [comment]
反复测试会遇到类似问题，然后翻译出现在选中框，而且有时候选中不同的段落出现相同的之前的翻译

**Comment by congmoyue** [comment]
<img width="786" alt="2" src="https://github.com/windingwind/zotero-pdf-translate/assets/3453824/404ddc2d-8c3b-4bb8-a779-7e23a0f7caa8">
<img width="1020" alt="1" src="https://github.com/windingwind/zotero-pdf-translate/assets/3453824/739925ab-216e-478e-8333-7654b301fee0">
补充了两种状态希望您对您寻找问题能有所帮助

**Comment by windingwind** [comment]
感谢反馈，请先打开debug output，然后执行触发问题的操作，然后提交debug output。截图对排查问题帮助不大

**Comment by congmoyue** [comment]
1712753220427	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1712753220726	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1712753220727	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1712753220727	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1712753220734	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.journalabbr@zsc.com	WARN	Loading extension 'journalabbr@zsc.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.zoterofigure@polygon.org	WARN	Loading extension 'zoterofigure@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.zoterogpt@polygon.org	WARN	Loading extension 'zoterogpt@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.zoteroreference@polygon.org	WARN	Loading extension 'zoteroreference@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220734	addons.webextension.zoterostyle@polygon.org	WARN	Loading extension 'zoterostyle@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753220739	addons.webextension.zoteroAddons@ytshen.com	WARN	Loading extension 'zoteroAddons@ytshen.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712753221062	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error running bootstrap method 'startup' on journalabbr@zsc.com"]

[JavaScript Error: "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]" {file: "jar:file:///C:/Users/onlymmx/AppData/Roaming/Zotero/Zotero/Profiles/pt1sxx37.default/extensions/journalabbr@zsc.com.xpi!/chrome/content/scripts/journalabbr.js" line: 195}]

[JavaScript Error: "Components.classes['@mozilla.org/embedcomp/prompt-service;1'] is undefined" {file: "jar:file:///C:/Users/onlymmx/AppData/Roaming/Zotero/Zotero/Profiles/pt1sxx37.default/extensions/better-bibtex@iris-advies.com.xpi!/bootstrap.js" line: 40}]

[JavaScript Error: "TypeError: _0x24855f is undefined" {file: "jar:file:///C:/Users/onlymmx/AppData/Roaming/Zotero/Zotero/Profiles/pt1sxx37.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 1}]

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/onlymmx/AppData/Roaming/Zotero/Zotero/Profiles/pt1sxx37.default/extensions/jasminum@linxzh.com.xpi!/chrome/content/scripts/index.js" line: 5029}]

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/onlymmx/AppData/Roaming/Zotero/Zotero/Profiles/pt1sxx37.default/extensions/jasminum@linxzh.com.xpi!/chrome/content/scripts/index.js" line: 5029}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "this._pdfThumbnails is undefined" {file: "resource://zotero/reader/reader.js" line: 27376}]

[JavaScript Error: "this._pdfThumbnails is undefined" {file: "resource://zotero/reader/reader.js" line: 27376}]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

appName => Zotero, version => 7.0.0-beta.72+128a540af, os => Windows 10.0 22631, locale => zh-CN, extensions => Jasminum (1.0.0-14, extension), Ethereal Reference (0.7.5, extension), zotero-journalabbr (0.7.12, extension), Better BibTex for Zotero (6.7.173, extension), Zotero 插件市场 (1.6.0, extension), Translate for Zotero (1.1.0-beta.40, extension), Better Notes for Zotero (1.1.4-beta.61, extension), PDF Figure (0.2.1, extension), Ethereal Style (4.3.0, extension), Awesome GPT (0.8.0, extension), Zotero PDF Preview (1.0.0-4, extension, disabled)

(5)(+0021684): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0002007): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000001): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0001982): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0002017): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0002001): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000001): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(3)(+0000415): Starting full-text content processor

(4)(+0000000): Registering notifier observer 'fulltext_km' for [sync]

(3)(+0000686): HTTP POST "1712753220427 addons.xpi WARN …" (10568 chars) to https://repo.zotero.org/repo/report?debug=1

(3)(+0000001): POST body gzipped from 10568 to 1872; 82% savings

(5)(+0000002): CookieSandbox: Being paranoid about channel for repo.zotero.org

(5)(+0000000): CookieSandbox: Cleared cookies to be sent to repo.zotero.org

(5)(+0000729): CookieSandbox: Being paranoid about channel for ocsp.r2m01.amazontrust.com

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to ocsp.r2m01.amazontrust.com

(5)(+0000159): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000001): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0000077): CookieSandbox: Being paranoid about channel for ocsp.r2m01.amazontrust.com

(5)(+0000000): CookieSandbox: No Set-Cookie header received for ocsp.r2m01.amazontrust.com

(5)(+0000371): CookieSandbox: Being paranoid about channel for repo.zotero.org

(5)(+0000000): CookieSandbox: No Set-Cookie header received for repo.zotero.org

(3)(+0000000): HTTP POST https://repo.zotero.org/repo/report?debug=1 succeeded with 200

(5)(+0001558): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000001): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0001986): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000001): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0002002): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000001): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0001998): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000001): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0001999): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0002004): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

(5)(+0001999): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

(5)(+0000000): {"code":"\n if (!window.Meet.tasks){\n window.Meet.tasks = []\n } else {\n window.Meet.tasks\n }\n "}

(5)(+0000000): HTTP/1.0 200 OK X-Zotero-Version: 7.0.0-beta.72+128a540af X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"result":[]}

**Comment by congmoyue** [comment]
[日志.txt](https://github.com/windingwind/zotero-pdf-translate/files/14932466/default.txt)
应该是抓取到最后的错误信息了，希望有帮助

**Comment by windingwind** [comment]
感谢反馈。请尝试禁用其他所有插件的情况下复现

**Comment by congmoyue** [comment]
[第二次日志.txt](https://github.com/windingwind/zotero-pdf-translate/files/14932696/default.txt)
这次是只剩一个插件进行的测试，也是可以复现出来，希望有用

**Comment by windingwind** [comment]
关于提到的翻译原文本和结果文本在侧边栏的显示顺序，请检查设置中是否开启了翻译 -> 高级 -> 侧边栏：反转源/结果显示位置。
