### ISSUE TITLE
[Bug]最新版信息栏不显示标题翻译和摘要翻译

### ISSUE THREAD

**Issue by gaojunyang666** [windingwind/zotero-pdf-translate#784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

![image](https://github.com/windingwind/zotero-pdf-translate/assets/63088548/67279c68-a554-4522-91d8-85e5cf68e35c)
如图所示，在设置中打开了所有，但是在信息栏还是无法显示

### Debug Output

抱歉我不会这个

**Comment by from1999** [comment]
在下面的“其他”这一栏里翻译之后会增加一个titletranslate:...
![image](https://github.com/windingwind/zotero-pdf-translate/assets/57467142/32fb2817-3f73-4e52-a0a2-22b9d636d6d0)

**Comment by from1999** [comment]
zotero7 好像就没有给标题翻译单独一栏了，我之前zotero6还有，升级了7之后就没有了

**Comment by windingwind** [comment]
文库列表可通过“标题翻译”列显示。本插件已不支持替代原始标题显示，具体可搜索历史讨论

**Comment by Catenfei** [comment]
![image](https://github.com/windingwind/zotero-pdf-translate/assets/98819531/2e4430df-0de3-4320-9f7d-2f53d3019a15)
列表z这里可以显示吗

**Comment by MmDawN** [comment]
> 文库列表可通过“标题翻译”列显示。本插件已不支持替代原始标题显示，具体可搜索历史讨论

请问后续版本中，侧边栏的Info里还能像Zotero6一样直接显示”标题翻译“、”摘要翻译“字段吗？

现在的版本得下拉到Info里“其他”字段才能看得到，相比Zotero6多多少少有些麻烦。

**Comment by Cehnchen** [comment]
标题翻译无法手动修改有网友知道应该怎么办吗
