### ISSUE TITLE
条目栏宽度再次失效

### ISSUE THREAD

**Issue by Sinoftj** [windingwind/zotero-pdf-translate#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Mac lasted
- Zotero Version:  beta lasted
- Plugin Version: lasted

### Describe the bug

条目框的宽度再次失效，之前修复了，现在随着版本更新，再次出现。已经排出style等其他插件的🎮。
![WX20240413-130520@2x](https://github.com/windingwind/zotero-pdf-translate/assets/118784753/7c8b4611-e436-44be-8cb9-6e259bd7a639)
![WX20240413-130443@2x](https://github.com/windingwind/zotero-pdf-translate/assets/118784753/6073bdad-6131-4559-b34a-20a687d4aa5f)

### Debug Output

[debug.txt](https://github.com/windingwind/zotero-pdf-translate/files/14965355/debug.txt)

### Anything else?

请求为翻译提供正则功能，避免划词翻译的时候，将作者名字翻译成中文！

**Comment by windingwind** [comment]
请禁用其他所有插件情况下提供调试输出&复现步骤

**Comment by Sinoftj** [comment]
其他插件造成的冲突
