### ISSUE TITLE
请问如何更换翻译弹窗和侧边栏的翻译区域的背景颜色，白色比较亮眼[Feature] 

### ISSUE THREAD

**Issue by luobendewugong** [windingwind/zotero-pdf-translate#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

### Anything else?

您的插件非常好用，对我起到了很大的帮助？谢谢！想咨询如何更换翻译弹窗和侧边栏的翻译区域的背景颜色，白色比较亮眼，时间久了眼睛疼，非常感谢！

**Comment by windingwind** [comment]
请完整提问
