### ISSUE TITLE
[Feature] 侧边栏的翻译按钮可不可以单独建立一个组，像Note那样

### ISSUE THREAD

**Issue by mingo99** [windingwind/zotero-pdf-translate#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0
- Plugin Version: 1.1.0-beta.41

### Describe the feature request

目前侧边栏中翻译窗口的按钮是和Info、Abstract以及Tags是一组的，如果上下滚动翻译内容会不小心切换到别的页面。

### Describe the solution you'd like

可不可以像Note一样建立一个单独的侧边栏，独立于Info以及其他页面，这样就不会因为滚动从而切换到别的页面。

**Comment by windingwind** [comment]
在侧边栏图标双击/右键菜单可锁定。
