### ISSUE TITLE
[Bug] 无法自动划词翻译

### ISSUE THREAD

**Issue by zxy-smart** [windingwind/zotero-pdf-translate#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS Monterey 12.6.1
- Zotero Version:  7.0.0-beta.75+f7dc68c7f
- Plugin Version: 1.1.0-23

### Describe the bug

划词后无法自动翻译

### Debug Output

划词后无法自动翻译，只显示“翻译“和”添加笔记“
<img width="896" alt="截屏2024-04-20 12 11 41" src="https://github.com/windingwind/zotero-pdf-translate/assets/82951587/8779d706-67c8-4917-ad62-132af752bf4b">
点击”翻译“也无法显示翻译后内容，点击”添加笔记“按钮无任何反应，只有在高亮后才显示翻译内容
<img width="798" alt="截屏2024-04-20 12 11 51" src="https://github.com/windingwind/zotero-pdf-translate/assets/82951587/c0d622c7-dd3d-4b91-9e4b-c56f08e35f64">
<img width="811" alt="截屏2024-04-20 12 23 01" src="https://github.com/windingwind/zotero-pdf-translate/assets/82951587/43b91ab2-045b-4051-9553-1899e78d60cb">
这是我的插件设置
<img width="525" alt="截屏2024-04-20 12 20 51" src="https://github.com/windingwind/zotero-pdf-translate/assets/82951587/25b67e17-8bc6-407e-b713-aae47f2bbeb7">
请问该怎么处理，才能恢复划词就自动翻译呢？

**Comment by hollandloprabbit** [comment]
我也遇到了同样的问题

**Comment by Beanpow** [comment]
<img width="875" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/37178760/aa8d34ec-f9b7-4e56-9952-332378ced840">
也许是这个问题

**Comment by zxy-smart** [comment]
根据您的提示，我解决了，谢谢🙏
