### ISSUE TITLE
[Bug] 无法使用GPT翻译引擎

### ISSUE THREAD

**Issue by RsFantasy** [windingwind/zotero-pdf-translate#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: WIN11
- Zotero Version: 6.0.36
- Plugin Version: 1.0.25

### Describe the bug

![Snipaste_2024-04-20_22-46-59](https://github.com/windingwind/zotero-pdf-translate/assets/38896143/f6adf6e7-7368-4bd2-a581-f0e14b46e4b8)
![Snipaste_2024-04-20_22-53-17](https://github.com/windingwind/zotero-pdf-translate/assets/38896143/390c2591-051a-43ee-b6b4-fe6a3f5a3813)

使用自己的api，无法调用gpt引擎

### Debug Output

![Snipaste_2024-04-20_22-57-47](https://github.com/windingwind/zotero-pdf-translate/assets/38896143/12f3c8df-e78f-4061-affa-1e2a7f4e7b2d)
还有个问题是不显示弹窗，不管怎么设置。

### Anything else?

感谢开发者开发这么强大的工具

**Comment by windingwind** [comment]
翻译服务问题与插件无关，请检查网络环境。
