### ISSUE TITLE
[Feature]Wish to add the function of adjusting font size（希望可以添加调节字号大小的选项)

### ISSUE THREAD

**Issue by malditof** [windingwind/zotero-pdf-translate#79]
希望可以增加翻译结果的字号大小调节选项，目前的字体偏小，阅读起来略有吃力，谢谢！
Can you add the font size adjustment option? The current font is too small, which makes it a little difficult to read. Thank you!

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate#advanced-ui
