### ISSUE TITLE
[Feature] 请求增加调整评论文字字体大小的功能

### ISSUE THREAD

**Issue by humbertLr** [windingwind/zotero-pdf-translate#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: windows 10
- Zotero Version: 6.0.36
- Plugin Version: 1.0.20

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
有些文献需要对许多单独的句子添加评论，想把字体调大一点从而便于阅读。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**
增加一个设置选项

**Comment by windingwind** [comment]
与插件无关，请向zotero forums反馈
