### ISSUE TITLE
[Feature] Offline Llama model support request.

### ISSUE THREAD

**Issue by ydlee1994** [windingwind/zotero-pdf-translate#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win 11
- Zotero Version: 6.0.36
- Plugin Version: latest.

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
Not.

**Why do you need this feature?**
Cause sometimes no internet connection and still need a translation service. Offline Llama provides this feature.

### Describe the solution you'd like

**The solution you'd like**
Just like the solution TTime provides. A connection with Ollama.

**Comment by GrayXu** [comment]
https://github.com/windingwind/zotero-pdf-translate/pull/799 provides custom model supports.  
For ollama, you can use `http://localhost:11434/v1/chat/completions` and specify your local model name.
