### ISSUE TITLE
[Bug] chatgpt翻译服务无法使用

### ISSUE THREAD

**Issue by hzb666** [windingwind/zotero-pdf-translate#795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11
- Zotero Version: 7.0.0
- Plugin Version: 1.1.0-beta.41

### Describe the bug

本插件chatgpt翻译无法使用，相同的密钥和接口可在zotero gpt里正常使用。接口后添加v1/chat/completions也不行，提示输入为空。
![image](https://github.com/windingwind/zotero-pdf-translate/assets/29155232/19283ab4-6e35-45c4-9cd8-2a2ff752c1c3)

### Debug Output

1714823467568	addons.xpi	WARN	Checking D:\Software\Zotero\distribution\extensions for addons

1714823468219	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714823468220	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714823468232	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468232	addons.webextension.delitemwithatt@redleaf.me	WARN	Loading extension 'delitemwithatt@redleaf.me': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468232	addons.webextension.frlars21@github.com	WARN	Loading extension 'frlars21@github.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468232	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468232	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468232	addons.webextension.scipdf@ytshen.com	WARN	Loading extension 'scipdf@ytshen.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468233	addons.webextension.zoplicate@chenglongma.com	WARN	Loading extension 'zoplicate@chenglongma.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468233	addons.webextension.zoteroattanger@polygon.org	WARN	Loading extension 'zoteroattanger@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468233	addons.webextension.zoterocitation@polygon.org	WARN	Loading extension 'zoterocitation@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468233	addons.webextension.zoterogpt@polygon.org	WARN	Loading extension 'zoterogpt@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468233	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468233	addons.webextension.zoteroreference@polygon.org	WARN	Loading extension 'zoteroreference@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468257	addons.webextension.tara@linxzh.com	WARN	Loading extension 'tara@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714823468257	addons.webextension.tara@linxzh.com	WARN	Loading extension 'tara@linxzh.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714823468259	addons.webextension.zoteroAddons@ytshen.com	WARN	Loading extension 'zoteroAddons@ytshen.com': Reading manifest: Using experimental APIs requires a privileged add-on.

[JavaScript Error: "TypeError: _0x24855f is undefined" {file: "jar:file:///C:/Users/huzhibin/AppData/Roaming/Zotero/Zotero/Profiles/lkq0lge6.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 1}]

[JavaScript Error: "r is undefined" {file: "jar:file:///C:/Users/huzhibin/AppData/Roaming/Zotero/Zotero/Profiles/lkq0lge6.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 145}]

[JavaScript Error: "r is undefined" {file: "jar:file:///C:/Users/huzhibin/AppData/Roaming/Zotero/Zotero/Profiles/lkq0lge6.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 145}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Attempt to override an existing message: "delitemwithatt-delete-collection-and-attachment"." {file: "delitemwithatt-addon.ftl" line: 0}]

[JavaScript Error: "TypeError: can't convert undefined to object" {file: "jar:file:///C:/Users/huzhibin/AppData/Roaming/Zotero/Zotero/Profiles/lkq0lge6.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 1}]

[JavaScript Error: "Attempt to override an existing message: "delitemwithatt-delete-collection-and-attachment"." {file: "delitemwithatt-addon.ftl" line: 0}]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Style with ID http://www.zotero.org/styles/acsfullname already loaded from acsfull-name.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

[JavaScript Error: "Style with ID http://www.zotero.org/styles/acsfullname already loaded from acsfull-name.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

[JavaScript Error: "Security Error: Content at resource://zotero/reader/reader.html may not load or link to chrome://zoterogpt/content/icons/favicon.png."]

appName => Zotero, version => 7.0.0-beta.77+adaa61f2c, os => Windows 10.0 22635, locale => zh-CN, extensions => Translate for Zotero (1.1.0-beta.41, extension), Ethereal Reference (0.7.5, extension), Sci-PDF (1.1.1, extension), Del Item With Attachment (0.3.1, extension), Easier Citation (0.4.3, extension), Zotero Citation Counts Manager (2.0, extension), Zotero 插件市场 (1.6.1, extension), Green Frog (0.19.0, extension), Zotero Attanger (1.2.0, extension), Zoplicate (3.0.0, extension), Jasminum (1.0.0-16, extension), Awesome GPT (0.8.4, extension), Better BibTex for Zotero (6.7.182, extension), 蒲公英 (1.0.0-8, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin)

(3)(+0020733): Notifier.trigger('close', 'tab', [tab-jscK4jsy], true) called [observers: 9]

(4)(+0000017): Unregistering notifier observer in notifier with id 'ItemDetails_vY'

(4)(+0000001): Unregistering notifier observer in notifier with id 'paneHeader_fA'

(4)(+0000000): Unregistering notifier observer in notifier with id 'itemBox_4z'

(4)(+0000001): Unregistering notifier observer in notifier with id 'abstractBox_ay'

(4)(+0000000): Unregistering notifier observer in notifier with id 'attachmentsBox_Uv'

(4)(+0000000): Unregistering notifier observer in notifier with id 'notesBox_Yx'

(4)(+0000000): Unregistering notifier observer in notifier with id 'attachmentbox_ZH'

(4)(+0000001): Unregistering notifier observer in notifier with id 'noteEditor_c9'

(4)(+0000000): Unregistering notifier observer in notifier with id 'tagsBox_mO'

(4)(+0000000): Unregistering notifier observer in notifier with id 'relatedbox_FO'

(4)(+0000000): Unregistering notifier observer in notifier with id 'librariesCollectionsBox_Rr'

(4)(+0000000): Unregistering notifier observer in notifier with id 'tagsBox_S1'

(4)(+0000001): Unregistering notifier observer in notifier with id 'relatedbox_cC'

(3)(+0000000): [Zoplicate] onDestroy non duplicates

(4)(+0000001): Unregistering notifier observer in notifier with id '2C'

(3)(+0000000): [Green Frog] notify close tab ["tab-jscK4jsy"] true

(3)(+0000010): Notifier.trigger('add', 'tab', [tab-jscK4jsy], {"tab-jscK4jsy":{"itemID":1968,"type":"reader"}}) called [observers: 9]

(3)(+0000005): Notifier.trigger('select', 'tab', [tab-jscK4jsy], {"tab-jscK4jsy":{"type":"reader"}}) called [observers: 9]

(4)(+0000003): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1945, 'https://pubs.acs.org/doi/10.1021/acs.chemrev.0c00811']

(3)(+0000003): [Zotero Attanger] close tab true

(3)(+0000005): [Jasminum] notify close tab ["tab-jscK4jsy"] true

(3)(+0000001): [Green Frog] notify add tab ["tab-jscK4jsy"] {"tab-jscK4jsy":{"itemID":1968,"type":"reader"}}

(3)(+0000000): [Green Frog] notify select tab ["tab-jscK4jsy"] {"tab-jscK4jsy":{"type":"reader"}}

(4)(+0000030): Registering notifier observer 'paneHeader_SQ' for [item]

(4)(+0000003): Registering notifier observer 'itemBox_kt' for [item]

(4)(+0000037): Registering notifier observer 'abstractBox_WL' for [item]

(4)(+0000004): Registering notifier observer 'attachmentsBox_Po' for [item]

(4)(+0000001): Registering notifier observer 'notesBox_dH' for [item]

(4)(+0000007): Registering notifier observer 'tagsBox_nh' for [item-tag,setting] with priority 101

(4)(+0000001): Registering notifier observer 'relatedbox_1v' for [item]

(4)(+0000000): Registering notifier observer 'noteEditor_RC' for [item,file]

(4)(+0000000): Registering notifier observer 'attachmentbox_VZ' for [item]

(4)(+0000002): Registering notifier observer 'librariesCollectionsBox_Vt' for [item]

(4)(+0000001): Registering notifier observer 'tagsBox_Fj' for [item-tag,setting] with priority 101

(4)(+0000001): Registering notifier observer 'relatedbox_J5' for [item]

(4)(+0000000): Registering notifier observer 'ItemDetails_w7' for [item,itempane]

(3)(+0000003): Viewing item

(3)(+0000114): [Zoplicate] onInit non duplicates

(4)(+0000001): Registering notifier observer 'zf' for [item]

(3)(+0000008): Refreshing item box

(3)(+0000119): Switching lastCreatorFieldMode to 0

(3)(+0000013): Setting mode to 'edit'

(3)(+0000001): Reloading tags box

(3)(+0000001): [Translate for Zotero] try itemLanguage en

(3)(+0000006): [Zotero Attanger] add tab {"tab-jscK4jsy":{"itemID":1968,"type":"reader"}}

(3)(+0000000): [Zotero Attanger] select tab {"tab-jscK4jsy":{"type":"reader"}}

(3)(+0000001): [Zoplicate] notify close tab ["tab-jscK4jsy"] true

(3)(+0000000): [Zoplicate] refreshDuplicates false

(3)(+0000000): [Jasminum] notify add tab ["tab-jscK4jsy"] {"tab-jscK4jsy":{"itemID":1968,"type":"reader"}}

(3)(+0000000): [Jasminum] notify select tab ["tab-jscK4jsy"] {"tab-jscK4jsy":{"type":"reader"}}

(3)(+0000061): Viewing item

(3)(+0000000): Refreshing item box

(3)(+0000001): Setting mode to 'edit'

(3)(+0000030): Refreshing item box

(3)(+0000001): Refreshing item box

(3)(+0000000): Refreshing item box

(3)(+0000000): Refreshing item box

(3)(+0000001): Refreshing item box

(3)(+0000000): Refreshing item box

(3)(+0000021): Getting contents of D:\huzhibin\documents\Zotero\storage\72TFT4BR\.zotero-reader-state

(3)(+0000218): itemTree.render(). Displaying Item Tree

(3)(+0000125): BlockingObserver: Added observer

(4)(+0000024): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [1945, 'https://pubs.acs.org/doi/10.1021/acs.chemrev.0c00811']

(3)(+0000009): [Awesome GPT] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000009): [Zoplicate] notify add tab ["tab-jscK4jsy"] {"tab-jscK4jsy":{"itemID":1968,"type":"reader"}}

(3)(+0000000): [Zoplicate] refreshDuplicates false

(3)(+0000001): [Zoplicate] notify select tab ["tab-jscK4jsy"] {"tab-jscK4jsy":{"type":"reader"}}

(3)(+0000000): [Zoplicate] refreshDuplicates false

(3)(+0000236): Got MIME type application/pdf from extension 'pdf'

(3)(+0002125): [Translate for Zotero] runTranslationTask {}

(3)(+0000004): [Translate for Zotero] try itemLanguage en

(3)(+0000001): [Translate for Zotero] try auto detect language

(3)(+0000001): [Translate for Zotero] try itemLanguage en

(3)(+0000000): [Translate for Zotero] {"id":"GGnB0ksq-1714823492939","type":"text","raw":"ters seem to be attracting less attention. There has been no comprehensive review focusing on this topic, even though this chemistry has become a powerful tool for the rapid and simple constru","result":"","audio":[],"service":"chatgpt","candidateServices":[],"itemId":1968,"status":"processing","extraTasks":[],"langfrom":"en","langto":"zh-CN","callerID":"zoteropdftranslate@euclpts.com","secret":"sk-SAm8viKlgbCAVpQHKDDwsgJ5uSacOsuQKbVpMy2X9OI23WaG"}

(3)(+0000000): HTTP POST "{"model":"gpt-3.5-turbo","messages":[{"role":"user","content":""}],"temperature":1,"stream":true}" to https://api.chatanywhere.tech

(5)(+0000031): CookieSandbox: Being paranoid about channel for api.chatanywhere.tech

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to api.chatanywhere.tech

(5)(+0000046): CookieSandbox: Being paranoid about channel for ocsp.digicert.com

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to ocsp.digicert.com

(5)(+0000326): CookieSandbox: Being paranoid about channel for ocsp.digicert.com

(5)(+0000000): CookieSandbox: No Set-Cookie header received for ocsp.digicert.com

(5)(+0000172): CookieSandbox: Being paranoid about channel for api.chatanywhere.tech

(5)(+0000000): CookieSandbox: No Set-Cookie header received for api.chatanywhere.tech

(3)(+0000002): [Translate for Zotero] try itemLanguage en

(1)(+0000001): HTTP POST https://api.chatanywhere.tech failed with status code 405: <html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx</center> </body> </html>

(3)(+0000006): [Translate for Zotero] try itemLanguage en

(3)(+0000434): {better-bibtex} +8753 removing fallback debug logger

(3)(+0003358): Writing reader state to D:\huzhibin\documents\Zotero\storage\72TFT4BR\.zotero-reader-state

(3)(+0002043): Starting full-text content processor

(4)(+0000000): Registering notifier observer 'fulltext_Pp' for [sync]

(3)(+0006931): {better-bibtex} +12332 idle: Sat May 04 2024 19:51:46 GMT+0800 (\u4e2d\u56fd\u6807\u51c6\u65f6\u95f4), save-database idle

(3)(+0000001): {better-bibtex} +1 emit: better-bibtex event emit idle {"state":"idle","topic":"save-database"}

(3)(+0000516): {better-bibtex} +515 idle: Sat May 04 2024 19:51:46 GMT+0800 (\u4e2d\u56fd\u6807\u51c6\u65f6\u95f4), save-database active

(3)(+0000000): {better-bibtex} +1 emit: better-bibtex event emit idle {"state":"active","topic":"save-database"}

**Comment by windingwind** [comment]
翻译服务问题，请咨询服务提供商
