### ISSUE TITLE
[Bug] 条目菜单没有显示翻译标题与翻译摘要，设置里面打开了也没有。

### ISSUE THREAD

**Issue by Catenfei** [windingwind/zotero-pdf-translate#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

![image](https://github.com/windingwind/zotero-pdf-translate/assets/98819531/e02b8c3a-02da-41cf-a72c-f0eebf69cf93)
![image](https://github.com/windingwind/zotero-pdf-translate/assets/98819531/00abbc79-1cca-432e-9afb-c49963757ccb)

### Debug Output

1714915117113	addons.xpi	WARN	Checking C:\APP\Zotero\distribution\extensions for addons

1714915117612	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714915117613	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714915117614	addons.webextension.pdfpreview@windingwind.com	WARN	Loading extension 'pdfpreview@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714915117615	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714915117615	addons.webextension.zoterotag@euclpts.com	WARN	Loading extension 'zoterotag@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714915117626	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.pdfpreview@windingwind.com	WARN	Loading extension 'pdfpreview@windingwind.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zotero-format-metadata@northword.cn	WARN	Loading extension 'zotero-format-metadata@northword.cn': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zoteroattanger@polygon.org	WARN	Loading extension 'zoteroattanger@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zoterocitation@polygon.org	WARN	Loading extension 'zoterocitation@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zoterogpt@polygon.org	WARN	Loading extension 'zoterogpt@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zoteroreference@polygon.org	WARN	Loading extension 'zoteroreference@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zoterostyle@polygon.org	WARN	Loading extension 'zoterostyle@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117626	addons.webextension.zoterotag@euclpts.com	WARN	Loading extension 'zoterotag@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1714915117640	addons.webextension.tara@linxzh.com	WARN	Loading extension 'tara@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1714915117640	addons.webextension.tara@linxzh.com	WARN	Loading extension 'tara@linxzh.com': Reading manifest: Using experimental APIs requires a privileged add-on.

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

[JavaScript Error: "TypeError: can't access dead object" {file: "jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js" line: 5499}]
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/initReaderKeyboardListener/</<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:5499:86
node_modules/zotero-plugin-toolkit/dist/utils/wait.js/waitUntil/intervalId<@jar:file:///C:/Users/ZJD/AppData/Roaming/Zotero/Zotero/Profiles/2qx8bhno.default/extensions/tara@linxzh.com.xpi!/chrome/content/scripts/tara.js:1214:15

**Comment by windingwind** [comment]
#784
