### ISSUE TITLE
after translate a little minutes, the translated word will be time out error

### ISSUE THREAD

**Issue by Big-Baby** [windingwind/zotero-pdf-translate#8]
after translate a little minutes, the translated word will be time out error.

**Comment by windingwind** [comment]
You requested too fast and were banned by the service provider temporarily. Please wait for a while.

That's why I strongly recommand you to apply a free key(or buy one) and use Engines like DeepL, Microsoft, etc using Secret.

**Comment by windingwind** [comment]
I'll close this issue. Thanks for your report!
