### ISSUE TITLE
[Bug] Texts in the textbox can not be updated if the previous texts were edited.

### ISSUE THREAD

**Issue by zyx335588** [windingwind/zotero-pdf-translate#80]
**Describe the bug**
If the texts were edited in the source textbox, when we select new texts, the source textbox would be not updated.
The same behavior for the translated textbox.

**Additional context**

It may be resolved by using the `value` property but not setting the `value` attribute in the `updateResults` function.
i.e., using `Zotero.ZoteroPDFTranslate.view.sideBarTextboxSource.value = Zotero.ZoteroPDFTranslate._sourceText;`

Although the `readonly` attribute of the textbox can be set, the editable textbox may be more beneficial for additional features, like highlighting keywords in the notes

**Comment by windingwind** [comment]
you can clone the repo, edit code, commit and start a new pull request anytime!

for this issue, i’m not pretty sure why you want to edit the text box?

**Comment by zyx335588** [comment]
I want to implement another function. During this, I found this bug. I think maybe others can edit the texts by accident, so I push this issue. If you think it does not matter, just close this issue.

**Comment by windingwind** [comment]
Already fixed
