### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by f11ly** [windingwind/zotero-pdf-translate#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.78+5be5ca941 (64-bit)
- Plugin Version:1.1.0-beta.41

### Describe the bug

对于一些文献不能正确识别英文然后翻译,,具体请看图片,推测可能是对文献的解码方式不同.

### Debug Output

![1](https://github.com/windingwind/zotero-pdf-translate/assets/150865059/58ea2140-d381-4ed6-864b-12c34d59b79a)

**Comment by windingwind** [comment]
pdf文件本身如此，与插件无关。
