### ISSUE TITLE
[Bug] 自动翻译失效

### ISSUE THREAD

**Issue by too-difficult-to-study** [windingwind/zotero-pdf-translate#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11, version 23H2
- Zotero Version: 6.0.36
- Plugin Version:1.0.25

### Describe the bug

自动翻译失效，检查了自动翻译有开启，未屏蔽英文的自动翻译。尝试更新、重启插件，尝试禁用其他插件，尝试重启zotero，重启电脑都无效
![image](https://github.com/windingwind/zotero-pdf-translate/assets/98164395/301ba577-6f96-433b-8fad-82edd964f44e)

### Debug Output

[Debug Output_files.zip](https://github.com/windingwind/zotero-pdf-translate/files/15344589/Debug.Output_files.zip)

**Comment by too-difficult-to-study** [comment]
[Debug Output_files (2).zip](https://github.com/windingwind/zotero-pdf-translate/files/15344602/Debug.Output_files.2.zip)
重新添加了debug output

**Comment by too-difficult-to-study** [comment]
[Debug Output_files.zip](https://github.com/windingwind/zotero-pdf-translate/files/15344620/Debug.Output_files.zip)
替换了问题中的debug output

**Comment by windingwind** [comment]
请检查文献语言。

**Comment by xunx911** [comment]
+1，用命令菜单是可以的，但是划词没反应，侧边栏也没反应
zotero7.0.0-beta.81+721f54fe4 (64-bit)
1.1.0-beta.31
![image](https://github.com/windingwind/zotero-pdf-translate/assets/58138577/de0a5f83-9b21-4e8e-b64f-7087c9b5afd5)

**Comment by unlsycn** [comment]
同样的问题

**Comment by windingwind** [comment]
@unlsycn @xunx911 请查看先前回复，仅提供zotero版本无助于问题解决。

**Comment by xunx911** [comment]
@windingwind 莫名其妙又好了，当时啥也没干就坏了，前两天又好了

**Comment by windingwind** [comment]
> sry 本来想贴log 不过自行编译master分支解决了这个问题

理论上自己构建的和release的版本应当一致，在不改动源码的情况下自己重新构建不是建议的解决bug方式。如果两者行为不一致，鼓励报告为bug。

**Comment by xunx911** [comment]
> @xunx911 是否是插件后台自动更新了？部分情况下插件更新后部分功能可能异常，需要重新启动zotero

很有可能，虽然说我重新启动没用，过了这两周才好的

**Comment by unlsycn** [comment]
> > sry 本来想贴log 不过自行编译master分支解决了这个问题
> 
> 理论上自己构建的和release的版本应当一致，在不改动源码的情况下自己重新构建不是建议的解决bug方式。如果两者行为不一致，鼓励报告为bug。

嗯 可能是因为之前的插件没有自动更新到prerelease版本

**Comment by Songlin1998** [comment]
是的，只要check好翻译语言基本上就能正常翻译了
