### ISSUE TITLE
[Bug] The tanslate tab can not be shown for some PDF files.

### ISSUE THREAD

**Issue by zyx335588** [windingwind/zotero-pdf-translate#81]
**Describe the bug**
When using Zotero to open some PDF files (like [the maintext](https://link.springer.com/article/10.1186/s12859-016-1342-9) of this article), the translate tab in the right sidebar is not shown. 
When I selected the text the first time, only the color selector popped up, and the `translate` popup menu did not. But from the second time, both were shown in the popmenu and worked properly, while the translate tab was still not shown.

**Expected behavior**
I hope the translate tab can be shown properly, if possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/22871049/162577927-48aba622-d5f2-4d22-b299-8736ee04cbc0.png)

**Environment**
 - **OS**:  Windows 10
 - **Zotero Version**: 6.0.5-beta.2
 - **Addon Version**: 0.4.3

**Comment by windingwind** [comment]
dose this happens to all your attachments, or just this attachment?

**Comment by windingwind** [comment]
Fixed in v0.4.5

The attachment title includes a ' - ', which is the same as the Zotero Reader title template and causes a wrong split.
