### ISSUE TITLE
[Bug] zotero7 在功能菜单中关闭弹窗，弹窗仍然显示

### ISSUE THREAD

**Issue by barryZZJ** [windingwind/zotero-pdf-translate#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.0-beta.79+95d5a5417 (64-bit)
- Plugin Version: 1.1.0-beta.41
![image](https://github.com/windingwind/zotero-pdf-translate/assets/48206733/4b750362-2d2c-4cee-8958-4d53a2fdf148)

### Describe the bug

如图

### Debug Output

None

**Comment by windingwind** [comment]
不启用弹窗仅指本插件的弹窗翻译，zotero本身的弹窗与本插件无关

**Comment by barryZZJ** [comment]
不是啊，你仔细看，不勾选enable的时候反而出现了翻译按钮；勾选enable并且hide popup会比不开插件多一个横杠。
顺带一提现在更新了v1.1.0-beta.42版本后不勾选enable还是会有翻译按钮，不过勾选enable后显示正常了：
![image](https://github.com/windingwind/zotero-pdf-translate/assets/48206733/998532ce-117e-4818-845d-7d87dcf57cfe)

**Comment by CNDrJoe** [comment]
如何关闭 Zotero7 软件本身的弹窗啊，很烦，总是遮挡文字

**Comment by windingwind** [comment]
软件本身功能与插件无关。
