### ISSUE TITLE
zotero 7 中Alt键和默认快捷键冲突问题

### ISSUE THREAD

**Issue by Haifeng-Dai** [windingwind/zotero-pdf-translate#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS 14.5
- Zotero Version: 7.0.0-beta.81+721f54fe4
- Plugin Version: 1.1.0-beta.41

### Describe the bug

当我使用Alt+5快捷键选择区域做标注的时候，翻译中的连接模型会被自动打开，而且关闭不了，除非按住Alt进行一次连接模式的翻译。使用Alt+1-4快捷键选择标注方式似乎不会出发这个问题。

### Debug Output

[bug.txt](https://github.com/windingwind/zotero-pdf-translate/files/15433163/bug.txt)

**Comment by windingwind** [comment]
可否提供复现操作的步骤/录屏？我无法复现alt+5触发拼接翻译

**Comment by Haifeng-Dai** [comment]
> 可否提供复现操作的步骤/录屏？我无法复现alt+5触发拼接翻译

可以的，我录制了，由于GitHub视频上传10MB的限制，我上传到第三方平台了，大概60MB。

主要步骤如下，先展示正常翻译 - 按Alt+5激活选择区域做标注功能 - 选择区域 - 再按Alt+5取消激活标注功能 - 选择文字翻译，此时就一直是增量翻译了。

链接如下：https://musetransfer.com/s/221g1hqtd 请点击链接获取《无主题 - IMG_0005.MOV》, 有效期至2025年6月21日
