### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by luckyandfine** [windingwind/zotero-pdf-translate#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 7.0.0-beta.83+066eda731(64-bit)
- Plugin Version:1.1.0-beta.43

### Describe the bug

![1](https://github.com/windingwind/zotero-pdf-translate/assets/155078509/15a2852e-9502-417b-b850-a834f9b1de1f)
如图，翻译框被侧边栏遮挡

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/15531606/Debug.Output.txt)

**Comment by windingwind** [comment]
感谢反馈，见先前讨论，此弹窗是zotero自带，插件无法处理其位置。可用侧边栏查看翻译结果
