### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wuhaoly1992** [windingwind/zotero-pdf-translate#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.84
- Plugin Version:1.1.0-beta.46

### Describe the bug

拼接模式无法正常使用，选中拼接模式并按住Alt键并不能进行拼接

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/15752720/Debug.Output.txt)

**Comment by thwyyyyy** [comment]
同样的问题，和快捷键功能冲突，建议换成左ctrl开启拼接模式

**Comment by wuhaoly1992** [comment]
> 同样的问题，和快捷键功能冲突，建议换成左ctrl开启拼接模式

谢谢！请问如何更改快捷键呢？好像没有找到相关的设置

**Comment by thwyyyyy** [comment]
> > 同样的问题，和快捷键功能冲突，建议换成左ctrl开启拼接模式
> 
> 谢谢！请问如何更改快捷键呢？好像没有找到相关的设置

不好意思，我的意思是希望作者可以更新一下，让我们能自己改快捷键。

**Comment by windingwind** [comment]
#811
