### ISSUE TITLE
[Feature] 请求增加国内大模型接口

### ISSUE THREAD

**Issue by AbnerHqC** [windingwind/zotero-pdf-translate#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 6.0.36
- Plugin Version: 1.0.25

### Describe the feature request

感谢大佬贡献这个优秀的项目！
大模型在很多论文内容的翻译上性能远超谷歌翻译等结果，GPT接口在国内使用有很多限制，求大佬可以加入通义、文心一言等国内大模型的API支持

**Comment by SWivid** [comment]
试了下用修改插件文件.xpi的方法实现用GPT位置调用DeepSeek

zotero-pdf-translate.xpi右键用如Bandzip查看编辑
pref.js里添加
pref("extensions.zotero.ZoteroPDFTranslate.gptModel", "deepseek-chat");
保存；应用修改的文件到压缩文件
然后安装进zotero6

使用方法：
api接口填：https://api.deepseek.com/v1/chat/completions
模型选 deepseek-chat
temperature官方说1.1适用翻译，0适用代码生成；感觉就默认的1就行

**Comment by windingwind** [comment]
无需修改xpi，z7直接设置即可；z6可在首选项-高级-设置编辑器-`extensions.zotero.ZoteroPDFTranslate.gptModel`设为对应值即可

**Comment by JoeChen2me** [comment]
zotero7可以自定义模型的，但是需要模型的调用逻辑兼容openai。目前可用的有qwen和deepseek，都是兼容openai调用的格式的。但是目前的问题是，希望开放更多的超参数调整，例如maxtoken

**Comment by windingwind** [comment]
@JoeChen2me 欢迎PR

**Comment by fanzhen1** [comment]
> 无需修改xpi，z7直接设置即可；z6可在首选项-高级-设置编辑器-`extensions.zotero.ZoteroPDFTranslate.gptModel`设为对应值即可

你好，我使用zotero 7, Translate for Zotero 1.1.0-beta.54，但没有看到deepseek的选项啊？去编辑器把gotModel设为true也还是没有

**Comment by Kimagure7** [comment]
> zotero7可以自定义模型的，但是需要模型的调用逻辑兼容openai。目前可用的有qwen和deepseek，都是兼容openai调用的格式的。但是目前的问题是，希望开放更多的超参数调整，例如maxtoken

我想在私有openai接口的LLM服务上部署 我该如何操作？

**Comment by liudss** [comment]
> > 无需修改xpi，z7直接设置即可；z6可在首选项-高级-设置编辑器-`extensions.zotero.ZoteroPDFTranslate.gptModel`设为对应值即可
> 
> 你好，我使用zotero 7, Translate for Zotero 1.1.0-beta.54，但没有看到deepseek的选项啊？去编辑器把gotModel设为true也还是没有

翻译服务选择chatgpt，选择config，将模型api改成deepseek的

**Comment by QingYunA** [comment]
DeepSeek模型使用方法：
翻译服务选择：`ChatGPT`
密钥填写deepseek的api，
右边的配置中把接口改为`https://api.deepseek.com/v1/chat/completions`
模型填写：`deepseek-chat`
保存即可～

**Comment by YuZhen-Yang** [comment]
> 试了下用修改插件文件.xpi的方法实现用GPT位置调用DeepSeek
> 
> zotero-pdf-translate.xpi右键用如Bandzip查看编辑 pref.js里添加在最下面（覆盖掉原本openai gpt） pref("extensions.zotero.ZoteroPDFTranslate.gptModel", "deepseek-chat"); 保存；应用修改的文件到压缩文件 然后安装进zotero6
> 
> 使用方法： api接口：https://api.deepseek.com/v1/chat/completions 模型选 deepseek-chat temperature官方说1.1适用翻译，0适用代码生成；感觉就默认的1就行

我使用这个方法成功调出翻译。temperature设置有更新，翻译现在是1.3了，链接：https://api-docs.deepseek.com/zh-cn/quick_start/parameter_settings
 @SWivid 现在我唯一的疑惑：为什么 api接口是https://api.deepseek.com/v1/chat/completions ，咋得到这个，简单看了一下官方文档，没找到说明

**Comment by QingYunA** [comment]
> > 试了下用修改插件文件.xpi的方法实现用GPT位置调用DeepSeek
> > zotero-pdf-translate.xpi右键用如Bandzip查看编辑 pref.js里添加在最下面（覆盖掉原本openai gpt） pref("extensions.zotero.ZoteroPDFTranslate.gptModel", "deepseek-chat"); 保存；应用修改的文件到压缩文件 然后安装进zotero6
> > 使用方法： api接口：https://api.deepseek.com/v1/chat/completions 模型选 deepseek-chat temperature官方说1.1适用翻译，0适用代码生成；感觉就默认的1就行
> 
> 我使用这个方法成功调出翻译。temperature设置有更新，翻译现在是1.3了，链接：https://api-docs.deepseek.com/zh-cn/quick_start/parameter_settings @SWivid 现在我唯一的疑惑：为什么 api接口是https://api.deepseek.com/v1/chat/completions ，咋得到这个，简单看了一下官方文档，没找到说明

deepseek以前为了适配openai接口，使用了和openai几乎一样的api地址格式，由于版本迭代现在官方文档没有了。
