### ISSUE TITLE
[Bug] 标题翻译无法手动修改有网友知道应该怎么办吗

### ISSUE THREAD

**Issue by Cehnchen** [windingwind/zotero-pdf-translate#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

![1718333336266](https://github.com/windingwind/zotero-pdf-translate/assets/172710654/67288771-8d0f-41f9-b0ac-0a454ac557e8)
之前标题翻译这里可以点击进行修改的，现在点击它没有反应

### Debug Output

报告ID：1684745782

**Comment by windingwind** [comment]
可暂时在底部extra/其他栏中编辑，未来zotero7版本将会支持
