### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Darkfiremaster66534** [windingwind/zotero-pdf-translate#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 6.0.36
- Plugin Version: 1.0.25

### Describe the bug

翻译其他PDF正常，翻译某个PDF(见附件)会出问题。
翻译正常：如图
![image](https://github.com/windingwind/zotero-pdf-translate/assets/73219924/a84973a6-f4b6-43c2-b4a9-ee88ebd5c3c1)
翻译不正常：如图
![image](https://github.com/windingwind/zotero-pdf-translate/assets/73219924/2935cf34-d347-4566-aef5-e650b5d553ac)
我看不正常的翻译似乎从选中复制的时候就出错了，"In this work" 变成了",Q WKLV ZRUN"所有字符都被换成了其他的。

[Song et al_2023_Memcapacitor Crossbar Array with Charge Trapping Layer for Physical Unclonable.pdf](https://github.com/user-attachments/files/15831239/Song.et.al_2023_Memcapacitor.Crossbar.Array.with.Charge.Trapping.Layer.for.Physical.Unclonable.pdf)

### Debug Output

[DebugOutput.zip](https://github.com/user-attachments/files/15831191/DebugOutput.zip)

**Comment by windingwind** [comment]
部分pdf本身文本内容错乱，与pdf有关，与插件无关。
