### ISSUE TITLE
[Bug] 条目下的HTML页面只能进行框选翻译，右侧窗口翻译无效

### ISSUE THREAD

**Issue by Nesln** [windingwind/zotero-pdf-translate#838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 14.0 (23A344)
- Zotero Version: 7.0.0-beta.85+c0c00a00e
- Plugin Version:1.1.0-beta.49

### Describe the bug

条目下的PDF文献可以正常框选翻译/右侧翻译窗口翻译，如图所示
<img width="787" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/80193160/706d53e5-6a21-4e39-8a16-1d71c75d9d92">
Zotero的浏览器插件保存的网页HTML只能进行框选翻译，右侧窗口不会显示框选的内容以及翻译；
<img width="1319" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/80193160/2ec0484e-fd43-410c-aec5-71842f7006a3">
在右侧窗口直接输入英文进行翻译时，翻译结果不会出现在右侧窗口的翻译栏，而是出现在HTML页面保留的框选中，如果页面没有框选文字，右侧翻译栏也不会有翻译结果【注：更换其他翻译引擎依然无效】
<img width="850" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/80193160/acfa52d0-333d-4069-904c-09b8600c6290">
<img width="361" alt="image" src="https://github.com/windingwind/zotero-pdf-translate/assets/80193160/7b153497-6705-4964-bcb0-80827d94151d">

### Debug Output

1718458422810	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: can't access dead object" {file: "chrome://zotero/content/xpcom/reader.js" line: 618}]

[JavaScript Error: "TypeError: can't access dead object" {file: "chrome://zotero/content/xpcom/reader.js" line: 618}]

[JavaScript Error: "Error: Library ID not provided" {file: "chrome://zotero/content/xpcom/data/dataObjects.js" line: 377}]

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "can't access dead object" {file: "chrome://zotero/content/xpcom/reader.js" line: 623}]

[JavaScript Error: "can't access dead object" {file: "chrome://zotero/content/xpcom/reader.js" line: 623}]

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "Error: Library ID not provided" {file: "chrome://zotero/content/xpcom/data/dataObjects.js" line: 377}]

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "TypeError: tab._window.ZoteroContextPane.getActiveEditor is not a function" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js" line: 786}]
createPaneNoteStatistics/</interval<@jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zotcard@zotero.org.xpi!/zotcard.js:786:55
notify@resource://gre/modules/Timer.sys.mjs:49:17

[JavaScript Error: "_0x2cc05f.querySelector(...) is null" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zoterogpt@polygon.org.xpi!/chrome/content/scripts/zoterogpt.js" line: 1}]

[JavaScript Error: "_0x12aede is null" {file: "jar:file:///Users/panwei/Library/Application%20Support/Zotero/Profiles/ol3bibfx.default/extensions/zoteromagic@zoterocn.com.xpi!/chrome/content/scripts/zoteromagic.js" line: 1}]

appName => Zotero, version => 7.0.0-beta.85+c0c00a00e, os => macOS 14.0, locale => zh-CN, extensions => Easier Citation (0.4.3, extension), Green Frog (0.19.01, extension), Ethereal Style (4.4.6, extension), Awesome GPT (0.8.4, extension), Better Notes for Zotero (1.1.4-beta.83, extension), Translate for Zotero (1.1.0-beta.49, extension), Magic for Zotero (1.4.6, extension), Obsidian Note for Zotero (1.0.1, extension), Better BibTex for Zotero (6.7.203, extension), Ethereal Reference (0.8.7, extension), ZotCard (3.0.10, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Jasminum (1.0.0-14, extension, disabled)

**Comment by windingwind** [comment]
我无法复现，且提issue时未禁用其他插件，无法确定问题来源，故此关闭。
