### ISSUE TITLE
[Bug] 与插件Zoplicate冲突

### ISSUE THREAD

**Issue by DataSailor** [windingwind/zotero-pdf-translate#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 14.5
- Zotero Version: 7.0.0-beta.89+49d3bae25
- Plugin Version: Translate 1.1.0-beta.49, Zoplicate 3.0.2

### Describe the bug

同时启用Zoplicate与Translate会导致冲突。
当我安装完两款插件，一切功能都很正常。
使用`Cmd + Q`关闭Zotero并重新打开软件，Translate插件没有响应。具体而言，当我选中一片文字，插件不会自动翻译；而当我将文字复制进文本框并点击Translate按钮，插件也不会开始翻译。

我同样在Zoplicate提了一个[Issue](https://github.com/ChenglongMa/zoplicate/issues/55)

### Debug Output

1718773791440	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

[JavaScript Error: "TypeError: item is undefined" {file: "chrome://zotero/content/xpcom/data/items.js" line: 1741}]

appName => Zotero, version => 7.0.0-beta.89+49d3bae25, os => macOS 14.5, locale => en-US, extensions => Zoplicate (3.0.2, extension), Translate for Zotero (1.1.0-beta.49, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Add-on Market for Zotero (1.6.2, extension, disabled), Ethereal Style (4.4.6, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.44, extension, disabled), Better Notes for Zotero (1.1.4-beta.83, extension, disabled), Awesome GPT (0.9.1, extension, disabled)

**Comment by DataSailor** [comment]
我同样在Zoplicate提了一个[Issue](https://github.com/ChenglongMa/zoplicate/issues/55)

**Comment by windingwind** [comment]
提供的debug output未包含有效信息，暂无法帮助
