### ISSUE TITLE
[Bug] zotero选词翻译经常漏句子

### ISSUE THREAD

**Issue by leeeezx** [windingwind/zotero-pdf-translate#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11 23H2
- Zotero Version: 6.0.36
- Plugin Version: 1.0.25

### Describe the bug

使用zotero-pdf-translate选词翻译时，选中一段文字翻译，翻译结果有时会漏掉其中一两句

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/15913678/Debug.Output.txt)

**Comment by windingwind** [comment]
1. 如果是选中的文本与显示的文本不符，为pdf提供方的格式问题；
2. 如果翻译结果缺少内容，与翻译服务有关

与插件无关，将关闭
