### ISSUE TITLE
[Bug] 无法安装，提示不兼容，关闭兼容检查试过了无效，求解

### ISSUE THREAD

**Issue by gengruihuan** [windingwind/zotero-pdf-translate#846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: WIN11 22H2
- Zotero Version: 6.0.36
- Plugin Version:1.1 BETA49

### Describe the bug

安装时提示不兼容

### Debug Output

![1](https://github.com/windingwind/zotero-pdf-translate/assets/28974422/6f06e464-dd98-47ca-acca-59df26222d30)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate?tab=readme-ov-file#install
