### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ywwsnowboy** [windingwind/zotero-pdf-translate#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.91
- Plugin Version: 1.1.0-beta.49

### Describe the bug

![Snipaste_2024-06-23_11-23-21](https://github.com/windingwind/zotero-pdf-translate/assets/71800428/d605ffd5-2468-4542-96e6-709abe00dd0d)
和Better BibTex for Zotero插件存在冲突，如果把Better BibTex for Zotero关闭就没有问题

### Debug Output

[Uploading Debug Output.htm…]()

**Comment by windingwind** [comment]
我无法复现，且未见有效debug output，故此关闭
