### ISSUE TITLE
[Bug]An error about Tencent's translation engine

### ISSUE THREAD

**Issue by NanZhi1998** [windingwind/zotero-pdf-translate#85]
Every time after restarting zotero the the Tencent Translate engine reports an error and shows that “Engine not available, invalid secret, or request too fast.” But after a few minutes, it translates normally.

**Comment by windingwind** [comment]
Please follow the debug steps in #6

**Comment by NanZhi1998** [comment]
[JavaScript Error: "XML Parsing Error: no root element found
Location: ***@***.***/dav/zotero/
Line Number 1, Column 1:" {file: ***@***.***/dav/zotero/" line: 1}]

version => 6.0.4, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.4, extensions => DOI Manager (1.4.2, extension), Jasminum (0.1.6, extension), Zotero LibreOffice Integration (6.0.0.SA.6.0.4, extension), Zotero Word for Windows Integration (6.0.0.SA.6.0.4, extension), ZotFile (5.1.1, extension), Zotero IF (1.4.3, extension), Zotero PDF Translate (0.4.6, extension)

(3)(+0023358): itemTree.render(). Displaying Item Tree

(3)(+0000013): Viewing item in pane 0

(3)(+0000001): Refreshing item box

(4)(+0000352): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [876, '']

(3)(+0000003): Viewing attachment 1/ADFG5QTV

(3)(+0000003): Opening D:\Zoterodata\storage\ADFG5QTV\Cummings - 2002 - Simulation and Synthesis Techniques for Asynchrono.pdf

(3)(+0000001): Notifier.trigger('open', 'file', [874]) called [observers: 5]

(3)(+0000007): Notifier.trigger('add', 'tab', [tab-mFeTJZye], {"tab-mFeTJZye":{"itemID":874}}) called [observers: 5]

(3)(+0000003): Notifier.trigger('select', 'tab', [tab-mFeTJZye], {"tab-mFeTJZye":{"type":"reader"}}) called [observers: 5]

(3)(+0000004): ZoteroPDFTranslate: open window event detected.

(3)(+0000002): ZoteroPDFTranslate: open attachment event detected.

(3)(+0000000): ZoteroPDFTranslate: Update Translate Panels

(3)(+0000000): ZoteroPDFTranslate.bindAddToNote

(3)(+0000032): Refreshing item box

(3)(+0000147): Getting contents of D:\Zoterodata\storage\ADFG5QTV\.zotero-pdf-state

(3)(+0000054): ZoteroPDFTranslate: buildSideBarPanel

(3)(+0000029): ZoteroPDFTranslate: updateSideBarPanelMenu

(3)(+0000064): itemTree.render(). Displaying Item Tree

(4)(+0000030): SELECT itemID FROM items WHERE (itemID NOT IN (SELECT itemID FROM deletedItems) AND itemID NOT IN (SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)) AND itemID NOT IN (SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems))) AND itemID IN (SELECT itemID FROM items WHERE (libraryID=?)) AND itemID IN (SELECT itemID FROM items WHERE (itemTypeID IN (SELECT itemTypeID FROM itemTypesCombined WHERE typeName=?))) [1, 'note']

(3)(+0002354): ZoteroPDFTranslate: onTranslate. language disable=false

(3)(+0001556): ZoteroPDFTranslate: updateSideBarPanelMenu

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0000000): ZoteroPDFTranslate: Translate 1649847204000 start.

(3)(+0000003): HTTP POST "Action=TextTranslate&Language=zh-CN&Nonce=9744&ProjectId=0&Region=ap-shanghai&SecretId=AKID0qQkob7LJ0PXP0KM8drnSFm20i9JBn7A&Source=en&SourceText=Many+designs+require+notification+of+a+pending+full+or+empty+status+with+the+generation+of+%E2%80%9Calmost+full%E2%80%9D+and+%E2%80%9Calmost+empty%E2%80%9D+status+bits.+There+are+many+ways+to+implement+these+two+status+bits+and+each+implementation+is+dependent+upon+the+specified+design+requirements.&Target=zh&Timestamp=1649847204&Version=2018-03-21&Signature=%2BpWFZU%2BHYoVtXRAtd8B1X9rbkew%3D" to https://tmt.tencentcloudapi.com

(3)(+0000347): HTTP POST https://tmt.tencentcloudapi.com succeeded with 200

(3)(+0000006): [object XMLHttpRequest] { "open": function open() { [native code] } "setRequestHeader": function setRequestHeader() { [native code] } "send": function send() { [native code] } "abort": function abort() { [native code] } "getResponseHeader": function getResponseHeader() { [native code] } "getAllResponseHeaders": function getAllResponseHeaders() { [native code] } "overrideMimeType": function overrideMimeType() { [native code] } "onreadystatechange": null "readyState": 4 "timeout": 30000 "withCredentials": false "upload": [object XMLHttpRequestUpload] { "onloadstart": null "onprogress": null "onabort": null "onerror": null "onload": null "ontimeout": null "onloadend": null "addEventListener": function addEventListener() { [native code] } "removeEventListener": function removeEventListener() { [native code] } "dispatchEvent": function dispatchEvent() { [native code] } "setEventHandler": function setEventHandler() { [native code] } "getEventHandler": function getEventHandler() { [native code] } "ownerGlobal": null } "responseURL": "https://tmt.tencentcloudapi.com/" "status": 200 "statusText": "OK" "responseType": "json" "response": { "Response": { "Error": { "Code": "AuthFailure.SignatureFailure" "Message": "请求签名验证失败，请检查您的签名计算是否正确。" } "RequestId": "e309bc93-1f00-4e56-abb4-2c5879cdbbc7" } } "responseText": <<Access Denied>> "responseXML": <<Access Denied>> "mozAnon": false "mozSystem": true "UNSENT": 0 "OPENED": 1 "HEADERS_RECEIVED": 2 "LOADING": 3 "DONE": 4 "getInterface": function getInterface() { [native code] } "setOriginAttributes": function setOriginAttributes() { [native code] } "sendInputStream": function sendInputStream() { [native code] } "mozBackgroundRequest": true "channel": [object XPCWrappedNative_NoHelper] { "forceAllowThirdPartyCookie": true "QueryInterface": function QueryInterface() { [native code] } "URI": [object XPCWrappedNative_NoHelper] { "spec": "https://tmt.tencentcloudapi.com/" "host": "tmt.tencentcloudapi.com" "prePath": "https://tmt.tencentcloudapi.com" "scheme": "https" "userPass": "" "username": "" "password": "" "hostPort": "tmt.tencentcloudapi.com" "port": -1 "pathQueryRef": "/" "equals": function equals() { [native code] } "schemeIs": function schemeIs() { [native code] } "clone": function clone() { [native code] } "resolve": function resolve() { [native code] } "asciiSpec": "https://tmt.tencentcloudapi.com/" "asciiHostPort": "tmt.tencentcloudapi.com" "asciiHost": "tmt.tencentcloudapi.com" "ref": "" "equalsExceptRef": function equalsExceptRef() { [native code] } "cloneIgnoringRef": function cloneIgnoringRef() { [native code] } "cloneWithNewRef": function cloneWithNewRef() { [native code] } "specIgnoringRef": "https://tmt.tencentcloudapi.com/" "hasRef": false "filePath": "/" "query": "" "displayHost": "tmt.tencentcloudapi.com" "displayHostPort": "tmt.tencentcloudapi.com" "displaySpec": "https://tmt.tencentcloudapi.com/" "displayPrePath": "https://tmt.tencentcloudapi.com" "mutate": function mutate() { [native code] } "QueryInterface": function QueryInterface() { [native code] } } "getRequestHeader": function getRequestHeader() { [native code] } "setRequestHeader": function setRequestHeader() { [native code] } "loadFlags": 289407105 "name": "https://tmt.tencentcloudapi.com/" "isPending": function isPending() { [native code] } "status": 0 "cancel": function cancel() { [native code] } "suspend": function suspend() { [native code] } "resume": function resume() { [native code] } "loadGroup": null "originalURI": [object XPCWrappedNative_NoHelper] { "spec": "https://tmt.tencentcloudapi.com/" "host": "tmt.tencentcloudapi.com" "prePath": "https://tmt.tencentcloudapi.com" "scheme": "https" "userPass": "" "username": "" "password": "" "hostPort": "tmt.tencentcloudapi.com" "port": -1 "pathQueryRef": "/" "equals": function equals() { [native code] } "schemeIs": function schemeIs() { [native code] } "clone": function clone() { [native code] } "resolve": function resolve() { [native code] } "asciiSpec": "https://tmt.tencentcloudapi.com/" "asciiHostPort": "tmt.tencentcloudapi.com" "asciiHost": "tmt.tencentcloudapi.com" "ref": "" "equalsExceptRef": function equalsExceptRef() { [native code] } "cloneIgnoringRef": function cloneIgnoringRef() { [native code] } "cloneWithNewRef": function cloneWithNewRef() { [native code] } "specIgnoringRef": "https://tmt.tencentcloudapi.com/" "hasRef": false "filePath": "/" "query": "" "displayHost": "tmt.tencentcloudapi.com" "displayHostPort": "tmt.tencentcloudapi.com" "displaySpec": "https://tmt.tencentcloudapi.com/" "displayPrePath": "https://tmt.tencentcloudapi.com" "mutate": function mutate() { [native code] } "QueryInterface": function QueryInterface() { [native code] } } "owner": null "notificationCallbacks": null "securityInfo": [object XPCWrappedNative_NoHelper] { "QueryInterface": function QueryInterface() { [native code] } } "contentType": "application/json" "contentCharset": "" "contentLength": 195 "open": function open() { [native code] } "open2": function open2() { [native code] } "asyncOpen": function asyncOpen() { [native code] } "asyncOpen2": function asyncOpen2() { [native code] } "contentDisposition": <<Access Denied>> "contentDispositionFilename": <<Access Denied>> "contentDispositionHeader": <<Access Denied>> "loadInfo": [object XPCWrappedNative_NoHelper] { "QueryInterface": function QueryInterface() { [native code] } "loadingPrincipal": [object XPCWrappedNative_NoHelper] { "QueryInterface": function QueryInterface() { [native code] } "read": function read() { [native code] } "write": function write() { [native code] } "equals": function equals() { [native code] } "equalsConsideringDomain": function equalsConsideringDomain() { [native code] } "URI": null "subsumes": function subsumes() { [native code] } "subsumesConsideringDomain": function subsumesConsideringDomain() { [native code] } "subsumesConsideringDomainIgnoringFPD": function subsumesConsideringDomainIgnoringFPD() { [native code] } "checkMayLoad": function checkMayLoad() { [native code] } "cspJSON": "{}" "originAttributes": { "appId": 0 "firstPartyDomain": "" "inIsolatedMozBrowser": false "privateBrowsingId": 0 "userContextId": 0 } "origin": "[System Principal]" "originNoSuffix": "[System Principal]" "originSuffix": "" "baseDomain": "" "appId": 0 "addonId": "" "addonPolicy": null "userContextId": 0 "privateBrowsingId": 0 "isInIsolatedMozBrowserElement": false "isNullPrincipal": false "isCodebasePrincipal": false "isExpandedPrincipal": false "isSystemPrincipal": true } "triggeringPrincipal": [object XPCWrappedNative_NoHelper] { "QueryInterface": function QueryInterface() { [native code] } "read": function read() { [native code] } "write": function write() { [native code] } "equals": function equals() { [native code] } "equalsConsideringDomain": function equalsConsideringDomain() { [native code] } "URI": null "subsumes": function subsumes() { [native code] } "subsumesConsideringDomain": function subsumesConsideringDomain() { [native code] } "subsumesConsideringDomainIgnoringFPD": function subsumesConsideringDomainIgnoringFPD() { [native code] } "checkMayLoad": function checkMayLoad() { [native code] } "cspJSON": "{}" "originAttributes": { "appId": 0 "firstPartyDomain": "" "inIsolatedMozBrowser": false "privateBrowsingId": 0 "userContextId": 0 } "origin": "[System Principal]" "originNoSuffix": "[System Principal]" "originSuffix": "" "baseDomain": "" "appId": 0 "addonId": "" "addonPolicy": null "userContextId": 0 "privateBrowsingId": 0 "isInIsolatedMozBrowserElement": false "isNullPrincipal": false "isCodebasePrincipal": false "isExpandedPrincipal": false "isSystemPrincipal": true } "principalToInherit": null "loadingDocument": null "securityFlags": 264 "securityMode": 8 "isInThirdPartyContext": false "cookiePolicy": 32 "forceInheritPrincipal": false "forceInheritPrincipalOverruleOwner": false "loadingSandboxed": true "aboutBlankInherits": false "allowChrome": false "disallowScript": false "dontFollowRedirects": false "loadErrorPage": false "isDocshellReload": false "externalContentPolicyType": 11 "upgradeInsecureRequests": false "browserUpgradeInsecureRequests": false "verifySignedContent": false "enforceSRI": false "forceAllowDataURI": false "allowInsecureRedirectToDataURI": false "originalFrameSrcLoad": false "forceInheritPrincipalDropped": false "innerWindowID": 0 "outerWindowID": 0 "parentOuterWindowID": 0 "topOuterWindowID": 0 "frameOuterWindowID": 0 "resetPrincipalToInheritToNullPrincipal": function resetPrincipalToInheritToNullPrincipal() { [native code] } "allowDocumentToBeAgnosticToCSP": false "originAttributes": { "appId": 0 "firstPartyDomain": "" "inIsolatedMozBrowser": false "privateBrowsingId": 0 "userContextId": 0 } "enforceSecurity": true "initialSecurityCheckDone": true "loadTriggeredFromExternal": false "appendRedirectHistoryEntry": function appendRedirectHistoryEntry() { [native code] } "redirectChainIncludingInternalRedirects": [] "redirectChain": [] "forcePreflight": false "isPreflight": false "tainting": 0 "maybeIncreaseTainting": function maybeIncreaseTainting() { [native code] } "isTopLevelLoad": true "resultPrincipalURI": null "isFromProcessingFrameAttributes": false "SEC_REQUIRE_SAME_ORIGIN_DATA_INHERITS": 1 "SEC_REQUIRE_SAME_ORIGIN_DATA_IS_BLOCKED": 2 "SEC_ALLOW_CROSS_ORIGIN_DATA_INHERITS": 4 "SEC_ALLOW_CROSS_ORIGIN_DATA_IS_NULL": 8 "SEC_REQUIRE_CORS_DATA_INHERITS": 16 "SEC_COOKIES_DEFAULT": 0 "SEC_COOKIES_INCLUDE": 32 "SEC_COOKIES_SAME_ORIGIN": 64 "SEC_COOKIES_OMIT": 96 "SEC_FORCE_INHERIT_PRINCIPAL": 128 "SEC_SANDBOXED": 256 "SEC_ABOUT_BLANK_INHERITS": 512 "SEC_ALLOW_CHROME": 1024 "SEC_DISALLOW_SCRIPT": 2048 "SEC_DONT_FOLLOW_REDIRECTS": 4096 "SEC_LOAD_ERROR_PAGE": 8192 "SEC_FORCE_INHERIT_PRINCIPAL_OVERRULE_OWNER": 16384 "TAINTING_BASIC": 0 "TAINTING_CORS": 1 "TAINTING_OPAQUE": 2 } "isDocument": false "LOAD_REQUESTMASK": 65535 "LOAD_NORMAL": 0 "LOAD_BACKGROUND": 1 "LOAD_HTML_OBJECT_DATA": 2 "LOAD_DOCUMENT_NEEDS_COOKIE": 4 "INHIBIT_CACHING": 128 "INHIBIT_PERSISTENT_CACHING": 256 "LOAD_BYPASS_CACHE": 512 "LOAD_FROM_CACHE": 1024 "VALIDATE_ALWAYS": 2048 "VALIDATE_NEVER": 4096 "VALIDATE_ONCE_PER_SESSION": 8192 "LOAD_ANONYMOUS": 16384 "LOAD_FRESH_CONNECTION": 32768 "LOAD_DOCUMENT_URI": 65536 "LOAD_RETARGETED_DOCUMENT_URI": 131072 "LOAD_REPLACE": 262144 "LOAD_INITIAL_DOCUMENT_URI": 524288 "LOAD_TARGETED": 1048576 "LOAD_CALL_CONTENT_SNIFFERS": 2097152 "LOAD_CLASSIFY_URI": 4194304 "LOAD_MEDIA_SNIFFER_OVERRIDES_CONTENT_TYPE": 8388608 "LOAD_EXPLICIT_CREDENTIALS": 16777216 "LOAD_BYPASS_SERVICE_WORKER": 33554432 "DISPOSITION_INLINE": 0 "DISPOSITION_ATTACHMENT": 1 "documentURI": null "getRequestVersion": function getRequestVersion() { [native code] } "getResponseVersion": function getResponseVersion() { [native code] } "setCookie": function setCookie() { [native code] } "setupFallbackChannel": function setupFallbackChannel() { [native code] } "thirdPartyFlags": 1 "canceled": false "channelIsForDownload": false "localAddress": "127.0.0.1" "localPort": 59125 "remoteAddress": "127.0.0.1" "remotePort": 7890 "HTTPUpgrade": function HTTPUpgrade() { [native code] } "allowSpdy": true "responseTimeoutEnabled": false "initialRwin": 0 "apiRedirectToURI": null "allowAltSvc": true "beConservative": false "tlsFlags": 0 "lastModifiedTime": <<Access Denied>> "responseSynthesized": false "corsIncludeCredentials": false "corsMode": 1 "redirectMode": 0 "fetchCacheMode": 0 "topWindowURI": <<Access Denied>> "setTopWindowURIIfUnknown": function setTopWindowURIIfUnknown() { [native code] } "networkInterfaceId": "" "proxyURI": null "blockAuthPrompt": false "integrityMetadata": "" "connectionInfoHashKey": "PS.....[tlsflags0x00000000]tmt.tencentcloudapi.com:443 (http:127.0.0.1:7890)[:]" "THIRD_PARTY_FORCE_ALLOW": 1 "CORS_MODE_SAME_ORIGIN": 0 "CORS_MODE_NO_CORS": 1 "CORS_MODE_CORS": 2 "CORS_MODE_NAVIGATE": 3 "REDIRECT_MODE_FOLLOW": 0 "REDIRECT_MODE_ERROR": 1 "REDIRECT_MODE_MANUAL": 2 "FETCH_CACHE_MODE_DEFAULT": 0 "FETCH_CACHE_MODE_NO_STORE": 1 "FETCH_CACHE_MODE_RELOAD": 2 "FETCH_CACHE_MODE_NO_CACHE": 3 "FETCH_CACHE_MODE_FORCE_CACHE": 4 "FETCH_CACHE_MODE_ONLY_IF_CACHED": 5 "requestMethod": "POST" "referrer": null "referrerPolicy": 1 "setReferrerWithPolicy": function setReferrerWithPolicy() { [native code] } "protocolVersion": "http/1.1" "transferSize": 382 "decodedBodySize": 0 "encodedBodySize": 195 "setEmptyRequestHeader": function setEmptyRequestHeader() { [native code] } "visitRequestHeaders": function visitRequestHeaders() { [native code] } "visitNonDefaultRequestHeaders": function visitNonDefaultRequestHeaders() { [native code] } "allowPipelining": false "allowSTS": true "redirectionLimit": 20 "responseStatus": 200 "responseStatusText": "OK" "requestSucceeded": true "isMainDocumentChannel": false "getResponseHeader": function getResponseHeader() { [native code] } "setResponseHeader": function setResponseHeader() { [native code] } "visitResponseHeaders": function visitResponseHeaders() { [native code] } "getOriginalResponseHeader": function getOriginalResponseHeader() { [native code] } "visitOriginalResponseHeaders": function visitOriginalResponseHeaders() { [native code] } "isNoStoreResponse": function isNoStoreResponse() { [native code] } "isNoCacheResponse": function isNoCacheResponse() { [native code] } "isPrivateResponse": function isPrivateResponse() { [native code] } "redirectTo": function redirectTo() { [native code] } "upgradeToSecure": function upgradeToSecure() { [native code] } "channelId": 25151328485390 "topLevelContentWindowId": 0 "isTrackingResource": false "topLevelOuterContentWindowId": 0 "logBlockedCORSRequest": function logBlockedCORSRequest() { [native code] } "REFERRER_POLICY_UNSET": 0 "REFERRER_POLICY_NO_REFERRER_WHEN_DOWNGRADE": 1 "REFERRER_POLICY_NO_REFERRER": 2 "REFERRER_POLICY_ORIGIN": 3 "REFERRER_POLICY_ORIGIN_WHEN_XORIGIN": 4 "REFERRER_POLICY_UNSAFE_URL": 5 "REFERRER_POLICY_SAME_ORIGIN": 6 "REFERRER_POLICY_STRICT_ORIGIN": 7 "REFERRER_POLICY_STRICT_ORIGIN_WHEN_XORIGIN": 8 } "networkInterfaceId": "" "errorCode": 0 "onloadstart": null "onprogress": null "onabort": null "onerror": null "onload": null "ontimeout": function () {...} "onloadend": function bound () { [native code] } "addEventListener": function addEventListener() { [native code] } "removeEventListener": function removeEventListener() { [native code] } "dispatchEvent": function dispatchEvent() { [native code] } "setEventHandler": function setEventHandler() { [native code] } "getEventHandler": function getEventHandler() { [native code] } "ownerGlobal": null }

(3)(+0000005): AuthFailure.SignatureFailure:请求签名验证失败，请检查您的签名计算是否正确。

(3)(+0000000): ZoteroPDFTranslate: Translate 1649847204000 returns false

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

(3)(+0001907): Starting full-text content processor

**Comment by windingwind** [comment]
fixed in v0.4.7
