### ISSUE TITLE
[Bug] 必应词典的发音按钮无效

### ISSUE THREAD

**Issue by JoeChen2me** [windingwind/zotero-pdf-translate#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Windows 11 Version 23H2
- Zotero Version: 7.0.0-beta.91+3c6625f3c (64-bit)
- Plugin Version:1.1.0-beta.49 Build 2024-06-12 08:53:04 

### Describe the bug

在使用 **必应词典** 时，选中单个单词可以出现释义，但是无法朗读发音。能出现喇叭图标，但是点击无效。

### Debug Output

使用必应词典进行单个单词的划词输入如下，能出现喇叭但是单击无发音。
![Uploading image.png…](必应词典的划词输出)  
同样的单词，使用海词词典能实现4个喇叭，单击能切换不同的人声发音。但存在的问题是不会自动播放，在设置中已经勾选自动播放发音。
![Uploading image.png…](海词词典的划词输出)

### Anything else?

 以下是海词词典的单词查询界面  
![海词词典的划词输出](https://github.com/windingwind/zotero-pdf-translate/assets/72426664/454e9df1-54f8-4502-96fb-2ab103480889)  
与之相对比的是必应词典的单词查询界面 ，出现了喇叭，但是无法播放
![必应词典](https://github.com/windingwind/zotero-pdf-translate/assets/72426664/1bcbc608-7dd4-42d0-8842-0ce359a97753)

**Comment by siyaooay** [comment]
![image](https://github.com/user-attachments/assets/923de04d-51a0-4812-97bb-ccd75263d7e2)
把这个改掉，编译一下，就好了。

**Comment by windingwind** [comment]
欢迎提PR @siyaooay

**Comment by siyaooay** [comment]
OK，好的。
