### ISSUE TITLE
[Feature]wish to translate the title automatically and show the result at some field.

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-pdf-translate#86]
1. translate the title automatically when import into the library;
2. show the result at some empty, useless field like {{shortTitle}}.
3. also can add the switch to decide whether to turn it on.
Benefits:
1. Read the title translation directly in the item pane.
2. Export the the title translation as an annotation into BibTeX format file without other manual operation.

**Comment by windingwind** [comment]
This feature is planned and assigned to another developer.

**Comment by lil-i321** [comment]
> 

Thank you very much, urgent need for me.

**Comment by windingwind** [comment]
Will not be that fast: we go as our plan. If this is really urgent for you, contributing code is very welcomed.

**Comment by lil-i321** [comment]
> Will not be that fast: we go as our plan. If this is really urgent for you, contributing code is very welcomed.

Sorry for my wrong expression.
Thanks for your nice plug-in, it really helps me a lot!
Please obey your plan!
Thanks again!

**Comment by windingwind** [comment]
@lil-i321 Try v0.6.0

**Comment by lil-i321** [comment]
> thanks for the updated!
1. extra symbols like "🔤" for every item's translation.
2. Does the translation overwrite the  field of "shortTitle" or attach into? For me, sometimes it is overwritten, sometimes it is attachment.
![图片](https://user-images.githubusercontent.com/57334649/163798936-d57b3b53-2c86-43cd-91ef-2411a8ff0a5e.png)

**Comment by windingwind** [comment]
> > thanks for the updated!
> 
> 1. extra symbols like "🔤" for every item's translation.
> 2. Does the translation overwrite the  field of "shortTitle" or attach into? For me, sometimes it is overwritten, sometimes it is attachment.
>    ![图片](https://user-images.githubusercontent.com/57334649/163798936-d57b3b53-2c86-43cd-91ef-2411a8ff0a5e.png)

1. This symbol is to mark the item as a 'translated' one, so that it will not be translated again.
2. Overwrite. The uppercase letters are not translated by most translate engines. The `ASSISON-SE` is part of your original title.

**Comment by lil-i321** [comment]
> 

OK, got it.
another issue.
Suppose there are 24 articles in a subcollection, right-click "show title tanslation" , there will be 12 articles showing the title tanslation, the remaining 12 articles cannot be displayed.
if there are 15 articles in a subcollection, there will be 8 articles showing the title tanslation, 7articles can not.

**Comment by windingwind** [comment]
Try v0.6.1
Shortcut `T` available now.

**Comment by windingwind** [comment]
Feel free to open it again.
