### ISSUE TITLE
feeds订阅条目的摘要翻译中含有源码[Bug] 

### ISSUE THREAD

**Issue by buzaiqizhong** [windingwind/zotero-pdf-translate#861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [ ] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.0-beta.95+694ccecf4 (64-bit)
- Plugin Version: 1.1.0-beta.49

### Describe the bug

问题出现在feeds订阅的条目，题目翻译正常，但是摘要翻译中含有一些译文之外的字符。
![屏幕截图 2024-07-04 120745](https://github.com/windingwind/zotero-pdf-translate/assets/143082934/5e52521e-0d2d-40a2-b2a0-ed6a84db17f3)

### Debug Output

no

### Anything else?

no

**Comment by windingwind** [comment]
谢谢反馈。由于zotero近期支持富文本格式的摘要，因此翻译结果中无法避免含有富文本标记（即你所述源码）。
