### ISSUE TITLE
[Bug] 启用浮窗翻译后，关闭浮窗无法回到侧栏翻译模式，无论浮窗是否开启，内容持续只显示在浮窗中

### ISSUE THREAD

**Issue by opacscdbph44** [windingwind/zotero-pdf-translate#863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.95+694ccecf4 (64-bit)
- Plugin Version: 1.1.0-beta.50

### Describe the bug

https://github.com/windingwind/zotero-pdf-translate/assets/131225543/9750f159-df22-456f-9fee-643251683862

bug 如题，具体情况如视频所示

### Debug Output

[Debug Output.zip](https://github.com/user-attachments/files/16118389/Debug.Output.zip)

**Comment by windingwind** [comment]
更新插件后请尝试重启zotero，我似乎无法复现

**Comment by opacscdbph44** [comment]
> 更新插件后请尝试重启zotero，我似乎无法复现

刚刚重启了几次神奇地消失了，感谢大佬，耽误您的时间啦，谢谢谢谢，插件超级好用！

**Comment by windingwind** [comment]
> 就是选中英文句子后只可以在弹窗和浮动窗口显示翻译结果

重启zotero

> 而且右侧边栏默认选项是德语翻译，每次翻译需要修改成英语。

手动更正文献语言栏，或关闭自动检测文献语言

**Comment by Petertaoo** [comment]
> > 就是选中英文句子后只可以在弹窗和浮动窗口显示翻译结果
> 
> 重启zotero
> 
> > 而且右侧边栏默认选项是德语翻译，每次翻译需要修改成英语。
> 
> 手动更正文献语言栏，或关闭自动检测文献语言

重启后右侧边栏也无法显示翻译

**Comment by windingwind** [comment]
@Petertaoo 请报告为单独issue
