### ISSUE TITLE
选中英文句子后只可以在弹窗和浮动窗口显示翻译结果，无法在右侧的侧边栏显示翻译结果。该问题无论重启还是重新安装插件都存在，请修复[Bug] 

### ISSUE THREAD

**Issue by Petertaoo** [windingwind/zotero-pdf-translate#864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win10 22H2
- Zotero Version: 7.0.0-beta.95+694ccecf4 (64-bit)
- Plugin Version: 1.1.0-beta.50

### Describe the bug

选中英文句子后只可以在弹窗和浮动窗口显示翻译结果，无法在右侧的侧边栏显示翻译结果。该问题无论重启还是重新安装插件都存在，请修复[Bug] 
![QQ截图20240707210057](https://github.com/windingwind/zotero-pdf-translate/assets/97863183/f2dd55d0-0914-4c72-92f2-f9ef1c094e35)
![QQ截图20240707205948](https://github.com/windingwind/zotero-pdf-translate/assets/97863183/cc9be2b9-138d-4354-a116-e5b64f23a5ca)

### Debug Output

无

**Comment by windingwind** [comment]
请提供Debug Output

**Comment by Petertaoo** [comment]
> 请提供Debug Output

不知道如何提供Debug Output

**Comment by windingwind** [comment]
请认真阅读创建issue时的提示语。

**Comment by lisontowind** [comment]
同样的问题

**Comment by lisontowind** [comment]
[Debug Output.zip](https://github.com/user-attachments/files/16201034/Debug.Output.zip)
这是我的Debug output

**Comment by lisontowind** [comment]
我好像发现问题所在了，是只对标签页上第一个打开的PDF生效，后面打开的都会出现这个问题。。。。

**Comment by windingwind** [comment]
可否提供稳定复现的步骤？我始终无法复现
关闭所有标签页，退出并重新进入zotero，然后通过什么步骤可以稳定复现该问题？

**Comment by lisontowind** [comment]
> 可否提供稳定复现的步骤？我始终无法复现 关闭所有标签页，退出并重新进入zotero，然后通过什么步骤可以稳定复现该问题？

我试了很久，发现应该是和better bibtex冲突。。一关掉better bibtex就好了，一开又有了。。不关闭所有标签页能稳定复现，多打开几个应该也可以。。。。

**Comment by lisontowind** [comment]
我看这位兄弟也装了better bibtex。。。。。。
