### ISSUE TITLE
无法翻译，出现乱码

### ISSUE THREAD

**Issue by Dingbob370** [windingwind/zotero-pdf-translate#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

![image](https://github.com/windingwind/zotero-pdf-translate/assets/161424331/cf853298-1433-4522-a7dc-3d1b45e3d3f9)

### Debug Output

![image](https://github.com/windingwind/zotero-pdf-translate/assets/161424331/3c84d3cc-6a50-498a-b637-863c0fbc42ec)

**Comment by windingwind** [comment]
PDF问题，与插件无关
