### ISSUE TITLE
[Bug]Add to note issue

### ISSUE THREAD

**Issue by 7homR** [windingwind/zotero-pdf-translate#87]
Please see issue here:
https://forums.zotero.org/discussion/96326/add-to-note-has-stopped-working#latest

After restarting Zotero, it would work fine, then stop again after a while. I have since updated the plugin and will report back if it happens again. Thanks.

**Comment by windingwind** [comment]
Please follow the debug steps in #6

**Comment by 7homR** [comment]
Thanks. I'll debug if the issue occurs again.

**Comment by windingwind** [comment]
Thanks for your report.
I reproduced that. Will fix it in the next update.
