### ISSUE TITLE
[Bug] When the translation box is displayed on the right, the width of the text box still changes when the mouse is clicked on it.

### ISSUE THREAD

**Issue by zhimaerfan** [windingwind/zotero-pdf-translate#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 14.6 Beta版(23G5061b)  m2 MacBook Air 
- Zotero Version: 7.0.0-beta.96+4f780424e
- Plugin Version: 1.1.0-beta.53

### Describe the bug

![CleanShot 2024-07-08 at 21 40 43](https://github.com/windingwind/zotero-pdf-translate/assets/44955451/a73ff396-d950-46cf-9ebe-52f975daa35d)
The problem only occurs when the translation box is on the left or right side: clicking on the translated text causes the width of the box to change.
Displaying it above or below does not, as this issue has been fixed once before.

### Debug Output

Submit… Clear Submitted with Debug ID D1291695532 📋 1720446862195 addons.xpi WARN Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons 1720446862653 addons.webextension.zoteropdftranslate@euclpts.com WARN Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots 1720446862898 addons.xpi WARN Addon with ID undefined already installed, older version will be disabled [JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}] [JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}] [JavaScript Error: "original is undefined" {file: "jar:file:///Users/efan/Library/Application%20Support/Zotero/Profiles/gdh70sto.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 5211}] [JavaScript Error: "original is undefined" {file: "jar:file:///Users/efan/Library/Application%20Support/Zotero/Profiles/gdh70sto.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 5211}] [JavaScript Error: "WebSocket connection closed: 1006 "] [JavaScript Error: "WebSocket connection closed: 1006 "] appName => Zotero, version => 7.0.0-beta.96+4f780424e, os => macOS 14.6, locale => zh-CN, extensions => Translate for Zotero (1.1.0-beta.53, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Zutilo Zotero 工具箱 (3.10.0, extension, disabled), DOI Manager (1.4.2, extension, disabled), Zotero Citation Counts Manager (1.3.0, extension, disabled), ZoteroQuickLook (1.4.2, extension, disabled), Sci-Hub Plugin for Zotero (1.4.4, extension, disabled), Storage Scanner for Zotero (5.0.12, extension, disabled), ZotFile (5.1.2, extension, disabled), MarkDBConnect (0.0.24, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Jasminum (1.0.0-16, extension, disabled), Easier Citation (0.4.3, extension, disabled), zotero-inspire (0.3.8, extension, disabled), Del Item With Attachment (0.3.2, extension, disabled), Zoplicate (3.0.2, extension, disabled), PDF Figure (0.2.3, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.44, extension, disabled), Notero (0.5.17, extension, disabled), Zotero Attanger (1.2.4, extension, disabled), Green Frog (0.19.01, extension, disabled), Awesome GPT (0.9.1, extension, disabled), Ethereal Reference (0.9.1, extension, disabled), Ethereal Style (4.5.4, extension, disabled), Zotero IF (1.5.5, extension, disabled), Better Notes for Zotero (1.1.4-beta.96, extension, disabled) (5)(+0002004): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126" sec-ch-ua-platform: "macOS" sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0 Content-Type: application/json Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh,zh-CN;q=0.9 (5)(+0000000): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.96+4f780424e X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found (1)(+0001446): WebSocket connection closed: 1006 (3)(+0000001): Delaying 5000 ms (5)(+0000549): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126" sec-ch-ua-platform: "macOS" sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0 Content-Type: application/json Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh,zh-CN;q=0.9 (5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.96+4f780424e X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found (3)(+0000168): [Translate for Zotero] runTranslationTask {"noCheckZoteroItemLanguage":true} (3)(+0000002): [Translate for Zotero] try itemLanguage en (3)(+0000000): [Translate for Zotero] use autoDetect en (3)(+0000006): [Translate for Zotero] try auto detect language (3)(+0000001): [Translate for Zotero] try itemLanguage en (3)(+0000000): [Translate for Zotero] use autoDetect en (3)(+0000000): [Translate for Zotero] {"id":"gGHniNuh-1720447152220","type":"text","raw":"penalize the EVA","result":"","audio":[],"service":"deeplfree","candidateServices":[],"itemId":13442,"status":"processing","extraTasks":[],"langfrom":"en","langto":"zh-CN","callerID":"zoteropdftranslate@euclpts.com","secret":"4636f792-b3f8-4ee3-9716-ca2c090c51e6:fx"} (3)(+0000000): HTTP POST "auth_key=4636f792-b3f8-4ee3-9716-ca2c090c51e6:fx&text=penalize%20the%20EVA&source_lang=EN&target_lang=ZH" to https://api-free.deepl.com/v2/translate (5)(+0001824): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126" sec-ch-ua-platform: "macOS" sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0 Content-Type: application/json Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh,zh-CN;q=0.9 (5)(+0000002): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.96+4f780424e X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found (3)(+0000158): HTTP POST https://api-free.deepl.com/v2/translate succeeded with 200 (3)(+0000006): [Translate for Zotero] try itemLanguage en (3)(+0000000): [Translate for Zotero] use autoDetect en (5)(+0001832): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126" sec-ch-ua-platform: "macOS" sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0 Content-Type: application/json Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh,zh-CN;q=0.9 (5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.96+4f780424e X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found (3)(+0000080): Writing reader state to /Users/efan/Zotero/storage/MYVGFVHL/.zotero-reader-state (3)(+0000377): Connecting to streaming server at wss://stream.zotero.org/ (5)(+0001544): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126" sec-ch-ua-platform: "macOS" sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0 Content-Type: application/json Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh,zh-CN;q=0.9 (5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.96+4f780424e X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found (5)(+0002001): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126" sec-ch-ua-platform: "macOS" sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0 Content-Type: application/json Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh,zh-CN;q=0.9 (5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.96+4f780424e X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found (3)(+0000057): WebSocket connection opened (3)(+0000001): WebSocket message: {"event":"connected","retry":10000} (3)(+0000003): WebSocket message send: {"action":"createSubscriptions","subscriptions":[{"apiKey":"********"},{"topics":["styles","translators"]}]} (5)(+0001937): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126" sec-ch-ua-platform: "macOS" sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0 Content-Type: application/json Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br, zstd Accept-Language: zh,zh-CN;q=0.9 (5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.96+4f780424e X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found

**Comment by zhimaerfan** [comment]
与该问题类似，但没完全修复 #541

**Comment by windingwind** [comment]
请禁用其他所有插件后重试

**Comment by lazarua** [comment]
在V2.0.5中，已禁用其他所有插件，如果翻译内容较多，仍出现这种现象
![Recording 2024-11-13 at 06 29 43](https://github.com/user-attachments/assets/d8a6ab88-c951-484f-b08c-4290f8deabf3)
