### ISSUE TITLE
[Feature] 增加翻译时使用的proxy

### ISSUE THREAD

**Issue by yanrui20** [windingwind/zotero-pdf-translate#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOS
- Zotero Version: 7.0.0
- Plugin Version: 1.1.0-beta.53

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
在使用google翻译的时候，需要自定义代理，否则无法连接

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
插件不负责代理，自行使用代理软件即可
