### ISSUE TITLE
你这个插件字体不能调大些吗，看得眼睛疼啊，操，6000多star居然不能调节字体大小

### ISSUE THREAD

**Issue by HillCat** [windingwind/zotero-pdf-translate#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
请文明发言
