### ISSUE TITLE
安装不成功，有插件无

### ISSUE THREAD

**Issue by YikeWangUCD** [windingwind/zotero-pdf-translate#884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 12.0.1（M1）
- Zotero Version: 6.0.37
- Plugin Version:1.0.27

### Describe the bug

突然有一天翻译用不了了，具体表现为没有任何翻译弹窗和页面的显示，就像是从未安装过一样。但预测同时，插件页面有该翻译插件。前前后后尝试过很多次，卸载，重装最新版，重启电脑，删除其他插件，结果显示都没办法解决这个问题。下列截图为：（1）翻译插件页面；（2）选中一段文字后没有任何翻译窗口弹出；
<img width="994" alt="image" src="https://github.com/user-attachments/assets/d3c49b8b-39f0-4d25-9ec7-6fb62249841d">

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/bcd1a10e-58b7-4744-afac-6423f6988886">

### Debug Output

[JavaScript Error: "Upload request 1/29AG2TMF failed"]

[JavaScript Error: "您的 Zotero 文件存储配额已经达到，有些文件将不能上传。Zotero 的其他数据将继续同步到 Zotero 服务器。

在 zotero.org 的帐户设置里查看更多的存储选项。

S0304393222000976.html (1559 KB)"]

[JavaScript Error: "Upload request 1/28QZTALK failed"]

[JavaScript Error: "您的 Zotero 文件存储配额已经达到，有些文件将不能上传。Zotero 的其他数据将继续同步到 Zotero 服务器。

在 zotero.org 的帐户设置里查看更多的存储选项。

Kagkadis 等 - 2022 - Factor Timing with Portfolio Characteristics.pdf (12616 KB)"]

version => 6.0.37, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => zh-CN, appName => Zotero, appVersion => 6.0.37, extensions => Markdown Here (2.13.4, extension, disabled), Zotero LibreOffice Integration (6.0.4.SA.6.0.37, extension, disabled), Zotero Word for Mac Integration (6.0.10.SA.6.0.37, extension, disabled), Zotero Better Notes (1.0.4, extension, disabled), Zotero PDF Translate (1.0.27, extension, disabled)

### Anything else?

Super thanks in advance!

**Comment by windingwind** [comment]
请按照issue template的步骤说明提供对应的debug output（需包含复现所报告问题的操作全过程）

**Comment by YikeWangUCD** [comment]
[debug.zip](https://github.com/user-attachments/files/16374150/debug.zip)
I think this is consistent with what I debugged yesterday. I don't know why there isn't a translate related plugin.

**Comment by windingwind** [comment]
首选项（设置）-高级-config editor-搜索关键词`secretObj`-清空-重启zotero

**Comment by YikeWangUCD** [comment]
你太牛了 现在可以用了 谢谢！🙏
