### ISSUE TITLE
[Bug]-0.5.0-Bug for "copy raw" "copy both" & "copy result"???

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-pdf-translate#89]
I have tried the lastest version 0.5.0,
* 0.5.0 can modify the raw text and the result will update accordingly, nice feature! 
For my PC.
> 1. Does it **just display** the modified text and correct results in the source and results areas? How can I not copy them to the clipboard?
> 2. When I selected the text but not yet highlighted, the translator started to work, which ensured real-time translation. At this point, click the copy button, and the clipboard saves the last highlighted text, not the text displayed in raw and result area now.Is this a bit confusing? In other words, the selected action cannot trigger the copy to clipboard, but the translation has already started, click to copy now, it,s not the translation result displayed at result area.
> 3. Can the correct translation be added to the comment area automatically or manually after checking?

> 1. 是不是只是在源码区和结果区**显示**修改后的文本和正确的结果？我怎么不能把他们复制到剪贴板？
> 2. 当我选中文本但还没有高亮标记的时候，翻译员就开始工作了，这保证了翻译的实时性。此时点击复制按钮，剪贴板保存的是上一次高亮的文字，并不是此时在源码区和结果区显示的文字，这是不是有点混乱？即，选中动作不能触发复制到剪贴板，但是已经开始翻译了，此时点击复制，并不是显示的翻译结果。
> 3. 能否把正确的译文自动或检查后手动添加到注释区？

**Comment by windingwind** [comment]
Fixed.

Reply to 3:
By default, the `automatically annotation translation` is on.
You can always edit the translation manually. If you disabled this feature, you can still copy the result to comment.

**Comment by lil-i321** [comment]
> Fixed.
> 
> Reply to 3: By default, the `automatically annotation translation` is on. You can always edit the translation manually. If you disabled this feature, you can still copy the result to comment.

yes, i can edit the raw text and the translation updated automaticlly, and also copy all to comment, nice debug.
For error text ,
When I selected the text but not yet highlighted, the translator started to work, display the correct result, 
then highlight the text , error text and error result will still be attached to the comment area.
* Do you think it is necessary to add the modified raw text and the correct translation to the comment area automatically ?

**Comment by windingwind** [comment]
Thanks for the suggestion. I guess what you want is:
1. Select & translate some text;
2. Modify the translation;
3. Highlight and add the new translation to the comment.
Do I describe it correctly?

**Comment by lil-i321** [comment]
> 
Yes, correct!
it is better add both the modified text and the new translation to the comment.
the wrong raw text is useless.

**Comment by windingwind** [comment]
Replace the original annotation text may be a better way? For me, I don't usually need to modify the text. Adding duplicated raw text is confusing.

**Comment by lil-i321** [comment]
> 
Yes, replace the original annotation text which highlighted will be better ,not add to comment area.
False identification does not happen very often, but occasionally.
If annotated citation text can be added from a area where they can be modified into the correct text, why not?
![图片](https://user-images.githubusercontent.com/57334649/163546278-afa3edce-4a56-4c16-917a-5876d27463fd.png)

**Comment by windingwind** [comment]
As the bug is fixed, I'll close this issue.
Your feature request is moved to a new issue.
