### ISSUE TITLE
[Feature] 请求增加小牛翻译高校版接口

### ISSUE THREAD

**Issue by tasarqaq** [windingwind/zotero-pdf-translate#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 6
- Plugin Version:1.0.25

### Describe the feature request

请问1.0.25或者最新的1.0.27，应如何填写api和key，才能正常使用小牛翻译中的高校版？· 
· 接口地址： https://trans.neu.edu.cn/niutrans/textTranslation?apikey=apikey的值(可在右上角个人中心查看)
· 请求方式： POST
· 传参方式： application/json
· 请求参数：
![1](https://github.com/user-attachments/assets/5ee7a488-9cc3-4d53-962a-0cf394d40201)
· 返回结果：
{
    "code": 200,
    "msg": "成功",
    "data": [
        {
            "sentences": [
                {
                    "data": "Hello",
                    "contrastSourceText": "你好",
                    "paragraphOrder": 0,
                    "order": 0,
                    "uuid": ,
                    "historyResult": null,
                    "len": 0,
                    "sourceLanguageAbbreviation": "zh",
                    "targetLanguageAbbreviation": "en"
                }
            ],
            "order": 0
        }
    ]
}

### Anything else?

如果大佬比较忙，可以教一下我如何自己学习修改

**Comment by sasaju** [comment]
这个貌似只有东北大学有吧，校外的不容易调试。

**Comment by tasarqaq** [comment]
好的好的，我明白了，谢谢大佬！！！已经很棒了






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年9月1日 19:35 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [windingwind/zotero-pdf-translate] [Feature] 请求增加小牛翻译高校版接口 (Issue #893) |

这个貌似只有东北大学有吧，校外的不容易调试。
