### ISSUE TITLE
请求增加翻译服务的自定义 api url

### ISSUE THREAD

**Issue by geekhuashan** [windingwind/zotero-pdf-translate#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: WIN 11
- Zotero Version:  7.0.0
- Plugin Version: 1.1.0-beta.59

### Describe the feature request

希望能够自定义各个服务的api url。

由于公司数据保护的限制，不能直接使用官方的 api url，需要自定义。

希望能够提供 deepl pro 和 microsoft，Google(api) 的自定义接口。

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate?tab=readme-ov-file#service

对未支持的，欢迎PR

**Comment by geekhuashan** [comment]
> https://github.com/windingwind/zotero-pdf-translate?tab=readme-ov-file#service
> 
> 对未支持的，欢迎PR

不会写软件，只会写issue。只能坐等。。。

**Comment by eutopiazen** [comment]
> https://github.com/windingwind/zotero-pdf-translate?tab=readme-ov-file#service
> 
> 对未支持的，欢迎PR

**Comment by eutopiazen** [comment]
现在很多国内大模型兼容openai，而且价格便宜，希望可以自定义api ulr

**Comment by windingwind** [comment]
@eutopiazen 早已经支持gpt/gemini及同类接口的服务了
