### ISSUE TITLE
[Feature] Big feature request: pdf对照翻译

### ISSUE THREAD

**Issue by saccohuo** [windingwind/zotero-pdf-translate#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature request

工作中阅读英文类书籍比较多，虽然可以正常阅读，但是在做快速浏览的时候，始终是中文更方便，所以希望能自建一个翻译文档，与pdf文件对照。这是一个比较巨大的工作，只是想先提出来，看是否是共性需求。
初步想法如下：
1. 全文翻译（默认先有全文所有的翻译），译文可修改（最好Markdown或者orgmode？批注在原文批注），译文要能区分校正过和没校正过的部分（颜色区分？按语句断句？）
2. pdf和译文对照（按照句子划分），两个窗口可以同步滚动。
3. pdf的译文窗口可以弹窗出来，可以在右侧边栏。
4. （可选）跨平台：Windows（优先）/iPad/安卓
5. （可选）翻译可以调用多个源（OpenAI API/DeepL/Google/Microsoft）

**Comment by windingwind** [comment]
据我所知有类似功能的插件服务，因此不考虑实现。感谢提出

**Comment by saccohuo** [comment]
> 据我所知有类似功能的插件服务，因此不考虑实现。感谢提出

请问哪个插件可以实现呢

**Comment by windingwind** [comment]
我不作推荐，请自行搜索

**Comment by greasebig** [comment]
请问有人推荐一下免费翻译全文pdf的插件吗?
