### ISSUE TITLE
[Bug] Zotero大版本更新至7.0后，划词点击翻译后无响应

### ISSUE THREAD

**Issue by scorpio-nova** [windingwind/zotero-pdf-translate#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS Big Sur Version 11.6
- Zotero Version: 7.0.0-beta.109+687399d9b
- Plugin Version: 1.1.0-23

### Describe the bug

完整设置如下，已开启自动翻译
![image](https://github.com/user-attachments/assets/4f0eac85-3667-43cd-8640-a001409689c7)
划词后显示如下（bug：软件没有自动翻译）
![image](https://github.com/user-attachments/assets/2f693362-c1b5-44bb-a011-1212370c0573)
点击Translate手动翻译后显示如下（bug：文本框显示范围很小，没有自适应；等待1分钟后仍没有任何变化；之前即使是翻译失败也会有报错）
![image](https://github.com/user-attachments/assets/9d93a9d4-c056-4510-b930-f40532641636)

考虑到zotero似乎进行了大版本更新（查了changelog之前都是6.x，今天打开自动更新到7.0了）可能是需要对新版本做进一步适配？我是否可以退回旧版本继续使用，还是在新版本下有解决方案？

感谢！

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/16452531/Debug.Output.txt)

**Comment by windingwind** [comment]
升级插件
