### ISSUE TITLE
[Feature] 求支持 https://aihubmix.com/代理接口

### ISSUE THREAD

**Issue by jimmysue** [windingwind/zotero-pdf-translate#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 13.6.1 (22G313)
- Zotero Version:  7
- Plugin Version: 7.0.0-beta.108+80cc97125

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

增加https://aihubmix.com/代理接口的支持

**Why do you need this feature?**
https://aihubmix.com/ 集成了众多大模型的接口，访问无需翻墙

### Describe the solution you'd like

**The solution you'd like**

在chatGPT config 下 设置 https://aihubmix.com/ 代理地址无法成功

### Anything else?

感谢大佬

**Comment by windingwind** [comment]
请按照对应服务商文档正确设置接口地址
https://doc.aihubmix.com/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8/%E5%9C%A8%E5%AE%98%E6%96%B9%20openai%20%E5%BA%93%E4%B8%AD%E4%BD%BF%E7%94%A8

**Comment by jimmysue** [comment]
> 请按照对应服务商文档正确设置接口地址 https://doc.aihubmix.com/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8/%E5%9C%A8%E5%AE%98%E6%96%B9%20openai%20%E5%BA%93%E4%B8%AD%E4%BD%BF%E7%94%A8

我已经按照官方说明进行设置了，还是不成功:

<img width="267" alt="image" src="https://github.com/user-attachments/assets/67ef2fb2-0855-4c07-93ce-edde79367f9c">

同样的账号我在 https://chromewebstore.google.com/detail/sider-chatgpt-%E4%BE%A7%E8%BE%B9%E6%A0%8F-+-gpt-4/difoiogjjojoaoomphldepapgpbgkhkb 是可以正常使用的

**Comment by windingwind** [comment]
服务问题请咨询对应服务提供商，他们应当可以告知你具体是什么问题
