### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zzlb0224** [windingwind/zotero-pdf-translate#902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win 11
- Zotero Version: 7.0.0-beta.113+151218e4d (64-bit)
- Plugin Version:1.1.0-beta.59

### Describe the bug

弹出框的翻译结果在点击之后宽度会变大。
原因是.view-popup.selection-popup的padding:5px，textarea还有个margin-left:2px。加起来18px
textarea的mouseup判断是 popup.scrollWidth > textarea.offsetWidth + 10
这里可能需要改为18
![image](https://github.com/user-attachments/assets/9fa4c5a2-f521-439b-9915-03938e36610c)

### Debug Output

no

### Anything else?

no

**Comment by zzlb0224** [comment]
宽度要到18。现在还是10

**Comment by windingwind** [comment]
改完又改成原本的测了下忘记改回去了，谢谢

**Comment by zzlb0224** [comment]
点击之后宽度还是会变大。
是不是我给的大小不合适。overflow-y要不要改为overlay试试？

**Comment by tzayuan** [comment]
同样的问题。点击一次翻译框宽度增加一次。
