### ISSUE TITLE
[Bug] Auto-Trans doesn't work

### ISSUE THREAD

**Issue by minnyqiu** [windingwind/zotero-pdf-translate#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 13.3
- Zotero Version: 6.0.37
- Plugin Version: Release 1.0.28

### Describe the bug

As the version is limited, I am not able to use the latest Zotero and the plugin. The recommended versions were used.
No matter whether I re-install the plugin or the Zotero software, Auto-Trans cannot be addressed. This may last two weeks. This issue has occurred before, and sometimes restarting the Zotero software can restore it to work.

<img width="600" alt="Screenshot 2024-08-09 at 11 24 22" src="https://github.com/user-attachments/assets/1d5d89c0-2d98-4787-a5db-88baf65cc329">

### Debug Output

[Debug Output_files.zip](https://github.com/user-attachments/files/16555814/Debug.Output_files.zip)

**Comment by windingwind** [comment]
The debug output is not correct.

**Comment by minnyqiu** [comment]
<img width="1003" alt="Screenshot 2024-08-09 at 15 07 29" src="https://github.com/user-attachments/assets/12da4b13-29ef-4618-9119-c52c6a4a7c5e">

**Comment by minnyqiu** [comment]
<img width="990" alt="Screenshot 2024-08-09 at 15 13 28" src="https://github.com/user-attachments/assets/6b0a64e7-0a2b-4625-8158-7ae0ad4ad5b3">

**Comment by windingwind** [comment]
These screenshots are not helpful. We need the full debug output, as described in the issue template.

**Comment by minnyqiu** [comment]
[Archive.zip](https://github.com/user-attachments/files/16557856/Archive.zip)

**Comment by windingwind** [comment]
https://www.zotero.org/download/
Zotero 7 is out and there is no reason to stay on Z6. Please update the plugin. Thanks
