### ISSUE TITLE
[Bug] 点击翻译的浮动窗口，浮动窗口的尺寸会慢慢的变大

### ISSUE THREAD

**Issue by WGowi** [windingwind/zotero-pdf-translate#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS 14
- Zotero Version: 7.0
- Plugin Version:2.0.0

### Describe the bug

点击翻译的浮动窗口，浮动窗口的尺寸会慢慢的变大
点击前：
<img width="973" alt="image" src="https://github.com/user-attachments/assets/da4c3947-bfb1-4ef1-9046-16cc6424a67a">

点击后
<img width="930" alt="image" src="https://github.com/user-attachments/assets/6bb44444-213f-4748-9c8e-e68af7e348eb">

经过前后对比发现窗口明显变大

### Debug Output

点击前：
<img width="973" alt="image" src="https://github.com/user-attachments/assets/da4c3947-bfb1-4ef1-9046-16cc6424a67a">

点击后
<img width="930" alt="image" src="https://github.com/user-attachments/assets/6bb44444-213f-4748-9c8e-e68af7e348eb">

经过前后对比发现窗口明显变大

**Comment by MinsGoing** [comment]
遇到了相同的问题！ @windingwind

**Comment by MinsGoing** [comment]
OS: Win11
Zotero Version: 7.0.12
Plugin Version:2.0.14
场景与上述一致，在选中少量文本翻译时不会出现，选中文本过程时问题与上述描述一致。
