### ISSUE TITLE
[Bug] 翻译窗口大小

### ISSUE THREAD

**Issue by sjads** [windingwind/zotero-pdf-translate#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0 正式版
- Plugin Version: 2.0.0

### Describe the bug

![`}ZGJ5599ROF0`DKX$A_2%3](https://github.com/user-attachments/assets/9e4debdd-89d6-4fd7-80af-2d01918bbe5f)
更新以后，翻译窗口大小不可以拖动，希望可以支持点击中间线，隐藏中文内容

### Debug Output

无

### Anything else?

无

**Comment by windingwind** [comment]
可通过如下设置决定是否仅显示原文/结果框

<img width="800" alt="image" src="https://github.com/user-attachments/assets/e6d78df5-425e-4f63-b20b-56e6bf5b3bf6">
