### ISSUE TITLE
[Bug] 无论是否连接魔法，都用不了google翻译

### ISSUE THREAD

**Issue by aqiuwoo** [windingwind/zotero-pdf-translate#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: ventura 13.5
- Zotero Version: 7.0.0
- Plugin Version:2.0.0

### Describe the bug

无论是否连接魔法，都用不了google翻译。
<img width="800" alt="截屏2024-08-11 12 25 07" src="https://github.com/user-attachments/assets/895cd4ef-997f-4eea-bc45-36235d393076">这是我的插件设置，该网址链接魔法后可以打开
<img width="452" alt="截屏2024-08-11 12 26 27" src="https://github.com/user-attachments/assets/71a18227-9841-444d-bdac-a874dfd82b27">这是插件报错内容，选择Google或Google(api)端都显示网络错误，但是已经打开魔法了呀，请问我应该怎么修改呢？

### Debug Output

已尝试过禁用所有其他插件，退出Zotero，然后重新启动Zotero，仍显示报错

**Comment by liangbingzhao** [comment]
I have the same error. can u reopen issue and ask for help?

**Comment by aqiuwoo** [comment]
还是用不了，可以用网页版的google，代理也是全局代理，但是不能在插件里用，网址也检查了，填在密钥里的网址在浏览器试过是可以用的，实在不知道是什么问题，有人遇到类似情况解决了吗？

**Comment by aqiuwoo** [comment]
> 我有同样的错误。您可以重新打开 issue 并寻求帮助吗？

我没有权限打开这个问题
