### ISSUE TITLE
[Feature]add Sogou translation

### ISSUE THREAD

**Issue by eclaowang** [windingwind/zotero-pdf-translate#91]
Hello, can you add Sogou translation? Sogou translates medical related literature with a high degree of accuracy, so I would appreciate it if you could add it!!!

**Comment by windingwind** [comment]
See #19. The [Sougou](https://deepi.sogou.com/) platform stopped service on Feb. 28.

**Comment by eclaowang** [comment]
I'm sorry to hear that and thank you very much for your reply.
