### ISSUE TITLE
[Bug] 最新版本翻译窗口无“添加到笔记”按钮，设置中已经打开但是无效

### ISSUE THREAD

**Issue by zifeiyu1999** [windingwind/zotero-pdf-translate#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win10 22h2
- Zotero Version: 7.0.1
- Plugin Version:2.0.0

### Describe the bug

![image](https://github.com/user-attachments/assets/31c6ff32-036c-4ac1-a017-43313a01d43f)

### Debug Output

wwww

**Comment by windingwind** [comment]
需要右侧栏打开笔记方显示

**Comment by QAbot-zh** [comment]
> 需要右侧栏打开笔记方显示

是这个意思吗，我应该已经打开笔记栏了，但还是没有显示“翻译添加到笔记”的按钮
![image](https://github.com/user-attachments/assets/95865dbc-f884-4f7d-b9a8-c67088602083)

设置里打开了：
![image](https://github.com/user-attachments/assets/9761457a-fe5f-4811-af8f-3710c443d546)

插件也是最新的：
![image](https://github.com/user-attachments/assets/fa8747c4-5d06-443d-8eeb-461bfd239435)

**Comment by windingwind** [comment]
一个是自带的，一个是插件的带有翻译的添加。自行试下就知道了

**Comment by QAbot-zh** [comment]
> 一个是自带的，一个是插件的带有翻译的添加。自行试下就知道了

OK，是正常的就行，我就怕是我软件产生了什么bug 👌
