### ISSUE TITLE
[Feature] 希望可以在右侧条目中重新恢复添加标题翻译和摘要翻译，粗看的时候很方便

### ISSUE THREAD

**Issue by Catenfei** [windingwind/zotero-pdf-translate#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win
- Zotero Version: 7
- Plugin Version:2

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by Mctalos** [comment]
附议
还有在主窗口列表切换显示原标题和翻译后的标题 这个功能也希望能恢复。

**Comment by amehime** [comment]
同意。设置里还保留着，但是实际信息栏不会单独显示，不是很方便
