### ISSUE TITLE
[Feature] Modify Annotation Translation

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-pdf-translate#92]
> 
Yes, replace the original annotation text which highlighted will be better ,not add to comment area.
False identification does not happen very often, but occasionally.
If annotated citation text can be added from a area where they can be modified into the correct text, why not?
![图片](https://user-images.githubusercontent.com/57334649/163546602-8bae0d91-0f3e-4034-8a52-578433f5ef02.png)

_Originally posted by @lil-i321 in https://github.com/windingwind/zotero-pdf-translate/issues/89#issuecomment-1099960421_

**Comment by windingwind** [comment]
@lil-i321 try v0.6.6

**Comment by lil-i321** [comment]
> @lil-i321 try v0.6.6
for the latest version 0.7.4, the modified annotation translation can not add to the comment area.

**Comment by windingwind** [comment]
@lil-i321 It works fine for me. Could you please describe it in detail?

**Comment by windingwind** [comment]
Is the button missing, or it just doesn't work? If you click or select text in PDF after you translated an annotation, the modification will be disabled.

**Comment by lil-i321** [comment]
> @lil-i321 It works fine for me. Could you please describe it in detail?
step 1. select text in PDF . -> will display the wrong translation.
step 2. correct the original annotation text in the translation panel and click the translate button -> will display the correct translation.
step 3. highlight the text in PDF. -> original false identification and wrong translation will display in the comment area.
in this step, I look forward to display the modified translation in the comment area.

**Comment by lil-i321** [comment]
> 

按键显示正常，就是这个功能不能实现，您可以随便找一篇pdf文献，先选中，再在翻译区修改原文，让译文发生改变，再点高亮，看看修改后的译文能否添加到注释区，以及注释区的原文是否是修改后的？

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/165074324-7fd4c07f-e62a-4744-ac58-0270e3e25ed5.png)
I still can't reproduce your problem

**Comment by windingwind** [comment]
在添加注释与修改之间，不要点击或选取pdf的文本；修改并更新侧边栏的翻译后，需要点击下方的更新注释按钮，方能更新到注释。这一操作与先前版本一致

**Comment by lil-i321** [comment]
> 

我这里没有 updata annotation 这个按钮啊

**Comment by windingwind** [comment]
高亮某些文字，然后在右侧栏编辑文字，此时该按钮会出现。

**Comment by lil-i321** [comment]
> 

并不会啊

**Comment by lil-i321** [comment]
> 

即使如此，这个功能也非常令人满意了！！！非常感谢！！
