### ISSUE TITLE
[Feature] To enhance single word translation

### ISSUE THREAD

**Issue by Warprein** [windingwind/zotero-pdf-translate#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0
- Plugin Version: 2.0.0

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
As a non-native English speaker, en<->en translations for some words can be really futile. For example "steadily: /ˈstɛdɪli/
[adverb] In a steady manner." I know I can basically untick "Use dictionary service for word translations" but then translations for single words (using google translate or deepl for example) can be insufficient for other words (that's probably why there is the different translation service for single words in the first place).

### Describe the solution you'd like

**The solution you'd like**
If we can also select the words in the definition in the pop-up opened for translation (the word steady in the example I gave), or/and if we can toggle between the translation services we use for words and expressions (unticking the "Use dictionary service for word translations" part actually) from the pop-up or translation pane this problem would be solved substantially.

**Alternatives you've considered**
In the long term adding more translation services for single words translations for other languages or making it possible for them to be added by users may be another solution. Still I consider the features that I suggested may become handy anyway.

### Anything else?

![image](https://github.com/user-attachments/assets/c54e959d-f29b-4fbc-9f5a-90e9336ba7b7)

**Comment by windingwind** [comment]
Please open the standalone translate panel (from the header of the `translate` section in item pane) and use the feature `multi-source` to add extra translate services.

**Comment by Warprein** [comment]
Thank you very much for your response but I still would like you to understand that the solution you've provided necessitates keeping a separate pane open all the time or opening it when needed using 3 clicks (context pane>translate>standalone translate pane) which would still just give you a one single translation for the word, and isn't easier or better than looking it up from an external translation service.
I would be very happy if you consider the problem and possible solutions I stated in the future developments of the add-in

**Comment by windingwind** [comment]
You can keep the standalone panel open. I can consider restoring the panel when starting Zotero, but that's off topic.

**Comment by windingwind** [comment]
Also, you don't need to click to scroll to the translate section for each reader tab. Double-click on the section button can pin the section in the item pane.
