### ISSUE TITLE
Error 403: HTTP POST Failure When Using DeepL with Zotero PDF Translate

### ISSUE THREAD

**Issue by junei6-kyoto** [windingwind/zotero-pdf-translate#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: 7.0.2 (64-bit)
- Plugin Version:Translate for Zotero2.0.0

### Describe the bug

Hello,

I have been encountering an issue with the Zotero PDF Translate addon when attempting to use the DeepL translation service. Here is a detailed description of the problem:　

Context:

This error occurs when I try to translate a PDF document using the integrated DeepL engine within the Zotero PDF Translate addon.
I am currently subscribed to the DeepL Pro Plan.
Steps Already Taken:

I have confirmed that my DeepL API key is correctly configured in the addon settings.
I attempted to reduce the frequency of translation requests to see if the issue was related to rate limits.
Suspicions:

There might be an issue with how the addon handles API requests, or perhaps something specific to my setup.
Additionally, I received feedback from Luke, a Technical Support Specialist at DeepL SE, Maarweg 165, 50825 Cologne, Germany. He pointed out that there might be an issue with my DeepL subscription and suggested I check the subscription type used for the plugin with the plugin developer. He also recommended making necessary adjustments via the DeepL account portal if needed.

Could you please help investigate this issue? Any advice or guidance on resolving it would be highly appreciated.

[文書1.docx](https://github.com/user-attachments/files/16770744/1.docx)

### Debug Output

1724802858827	addons.xpi-utils	WARN	addMetadata: Add-on undefined is invalid: Error: File resource://default-theme/ does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:685:11) JS Stack trace: loadManifest@XPIInstall.jsm:685:11
awaitPromise@XPIProvider.jsm:227:15
syncLoadManifest@XPIInstall.jsm:769:29
addMetadata@XPIDatabase.jsm:3104:37
processFileChanges@XPIDatabase.jsm:3569:26
checkForChanges@XPIProvider.jsm:3121:60
startup@XPIProvider.jsm:2532:12
callProvider@AddonManager.sys.mjs:228:31
_startProvider@AddonManager.sys.mjs:536:17
startup@AddonManager.sys.mjs:742:14
startup@AddonManager.sys.mjs:3666:26
observe@amManager.sys.mjs:73:29

[JavaScript Error: "Error: Can't find profile directory." {file: "resource://gre/modules/XULStore.sys.mjs" line: 60}]
load@resource://gre/modules/XULStore.sys.mjs:60:15
XULStore@resource://gre/modules/XULStore.sys.mjs:17:10

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/user01/AppData/Roaming/Zotero/Zotero/Profiles/2xl2bqr9.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 5219}]

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/user01/AppData/Roaming/Zotero/Zotero/Profiles/2xl2bqr9.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 5219}]

appName => Zotero, version => 7.0.3 (x64), os => Windows 11 22631, locale => ja-JP, extensions => Translate for Zotero (2.0.0, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin)

### Anything else?

Error indication　　　　　　　　　　　　　　　　　724802858827	addons.xpi-utils	WARN	addMetadata: Add-on undefined is invalid: Error: File resource://default-theme/ does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:685:11) JS Stack trace: loadManifest@XPIInstall.jsm:685:11
awaitPromise@XPIProvider.jsm:227:15
syncLoadManifest@XPIInstall.jsm:769:29
addMetadata@XPIDatabase.jsm:3104:37
processFileChanges@XPIDatabase.jsm:3569:26
checkForChanges@XPIProvider.jsm:3121:60
startup@XPIProvider.jsm:2532:12
callProvider@AddonManager.sys.mjs:228:31
_startProvider@AddonManager.sys.mjs:536:17
startup@AddonManager.sys.mjs:742:14
startup@AddonManager.sys.mjs:3666:26
observe@amManager.sys.mjs:73:29

[JavaScript Error: "Error: Can't find profile directory." {file: "resource://gre/modules/XULStore.sys.mjs" line: 60}]
load@resource://gre/modules/XULStore.sys.mjs:60:15
XULStore@resource://gre/modules/XULStore.sys.mjs:17:10

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/user01/AppData/Roaming/Zotero/Zotero/Profiles/2xl2bqr9.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 5219}]

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/user01/AppData/Roaming/Zotero/Zotero/Profiles/2xl2bqr9.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 5219}]

appName => Zotero, version => 7.0.3 (x64), os => Windows 11 22631, locale => ja-JP, extensions => Translate for Zotero (2.0.0, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin)

**Comment by junei6-kyoto** [comment]
We cannot reach a solution. I would be grateful for any advice you could give me.

**Comment by windingwind** [comment]
What's your DeepL description? The plugin uses the [DeepL API](https://www.deepl.com/en/pro#developer), not the [DeepL Translator](https://www.deepl.com/en/pro#team)

**Comment by junei6-kyoto** [comment]
Thanks for the reply. I will check the plugin.

2024年8月28日(水) 12:00 windingwind ***@***.***>:

**Comment by junei6-kyoto** [comment]
Resolved.
I was able to use the function after selecting the following.

> Edit > Settings > Translation > Services > Services
> Translation service: “DeepL X”

In the Translation service box, there are several entries for DeepL, but it
looks like I should not have selected “DeepLX (API)”.

Thanks for the advice. I appreciate your reaction.

2024年8月28日(水) 12:57 junei ***@***.***>:
