### ISSUE TITLE
[Feature] 翻译原文和翻译文本框大小不可调整

### ISSUE THREAD

**Issue by CigarOVO** [windingwind/zotero-pdf-translate#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 14.5
- Zotero Version: 7.0.3
- Plugin Version:2.0.0

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
翻译原文框和翻译结果框大小不可调

**Why do you need this feature?**
很多时候更注重翻译结果，文本选择一多需要下滑很久才能看到

### Describe the solution you'd like

**The solution you'd like**
之前老版本中间分隔的横线可以上下调整文本框大小，现在不知道是不是因为版本的原因，不再可以上下拉动调整

**Comment by windingwind** [comment]
可在设置中隐藏源/结果栏，另一栏即有全部高度

**Comment by wuxiii02** [comment]
> 可在设置中隐藏源/结果栏，另一栏即有全部高度

但有时候有需要看一下原文，毕竟翻译也不一定准确。所以感觉还是需要像老版一样有个可以调节原文译文窗口长短的分割线比较好，如果加一个按钮来选择是否有这个分割线是不是更好呢？

**Comment by Petrichor728** [comment]
同求此功能，老版可以，希望新版也能加一个可调节分割线。

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
