### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Yafeia** [windingwind/zotero-pdf-translate#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

划选翻译，显示翻译选项，点击后依旧无响应（多个翻译api都出现这样状况），难道是网速太慢吗

![3fb8472a633ff8234c7f558f7747d82](https://github.com/user-attachments/assets/35497732-f703-45f3-884a-33a7cf0cf2dc)
![3ec292659fe3e485d1a5a9d47daf8fd](https://github.com/user-attachments/assets/38b00218-7b5b-4043-bd60-116b9d96a8af)

![711b878a44329dbf0f39962e6650671](https://github.com/user-attachments/assets/6563ef9d-cf7c-4c02-8973-4f73749b95d6)

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/16842412/Debug.Output.txt)

**Comment by sasaju** [comment]
![image](https://github.com/user-attachments/assets/68fd84ea-56bf-4cb1-ab62-c70b34ed3b28)
选反了，左侧是英文，右侧是中文
