### ISSUE TITLE
[Feature] Is there a way to remove the character limit for a single translation?

### ISSUE THREAD

**Issue by JayHoris** [windingwind/zotero-pdf-translate#933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS:  Windows 10 22H2
- Zotero Version: 7.0.3
- Plugin Version: 2.0.0

### Describe the feature request

**Why do you need this feature?**
It is often necessary to translate long pieces of text, so the upper limit of a single character is often reached, which is very inconvenient

### Describe the solution you'd like

**The solution you'd like**
Customize the maximum number of characters for word translation in the settings, and provide an option for larger amounts, such as 1500 words

**Comment by windingwind** [comment]
#6
