### ISSUE TITLE
[Bug] zotero 7中经常出现插件无法启动的问题

### ISSUE THREAD

**Issue by litaihe** [windingwind/zotero-pdf-translate#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11 教育版 23H2
- Zotero Version: 7.05(64bit)
- Plugin Version:2.0.0

### Describe the bug

启动zetero 时经常出现该插件无法启动的问题，如图所示插件显示插件开启，但是在设置菜单里面看不到插件
![image](https://github.com/user-attachments/assets/a0120101-6ad6-4bf8-88f9-31d86430b9e8)
![image](https://github.com/user-attachments/assets/5444f725-be3f-4de9-b8b5-cd54ef986f23)

### Debug Output

appName => Zotero, version => 7.0.5 (x64), os => Windows 11 22631, locale => zh-CN, extensions => Translate for Zotero (2.0.0, extension), Zotero Attanger (1.2.5, extension)
(3)(+0009484): Scheduling next feed update

(4)(+0000001): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1

(3)(+0000002): No feeds with auto-update

(4)(+0000921): SELECT COUNT(*) FROM settings WHERE setting='mImport' AND key='cleanup'

(3)(+0003278): Writing reader state to C:\Users\14869\OneDrive\论文阅读\Zotero\storage\QH2BTMKK\.zotero-reader-state

(3)(+0004464): HTTP POST "appName => Zotero, version => …" (753 chars) to https://repo.zotero.org/repo/report?debug=1

(3)(+0000003): POST body gzipped from 753 to 480; 36% savings

(3)(+0000391): HTTP POST https://repo.zotero.org/repo/report?debug=1 succeeded with 200

(4)(+0011861): Registering notifier observer 'fulltext_dW' for [sync]

(3)(+0030273): Getting contents of C:\Users\14869\AppData\Roaming\Zotero\Zotero\Profiles\a9lmz57r.default\treePrefs.json

(3)(+0000001): Writing column prefs of length 3243 to file C:\Users\14869\AppData\Roaming\Zotero\Zotero\Profiles\a9lmz57r.default\treePrefs.json

**Comment by litaihe** [comment]
出现无法启动情况日志如下所示

[JavaScript Error: "Error running bootstrap method 'startup' on zoteropdftranslate@euclpts.com"]

[JavaScript Error: "reader._iframeWindow is null" {file: "jar:file:///C:/Users/14869/AppData/Roaming/Zotero/Zotero/Profiles/a9lmz57r.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 5824}]

[JavaScript Error: "Error running bootstrap method 'startup' on zoteroattanger@polygon.org"]

[JavaScript Error: "t._iframeWindow is null" {file: "jar:file:///C:/Users/14869/AppData/Roaming/Zotero/Zotero/Profiles/a9lmz57r.default/extensions/zoteroattanger@polygon.org.xpi!/chrome/content/scripts/zoteroattanger.js" line: 195}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 687}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:687:7


appName => Zotero, version => 7.0.5 (x64), os => Windows 11 22631, locale => zh-CN, extensions => Translate for Zotero (2.0.0, extension), Zotero Attanger (1.2.5, extension)

(4)(+0030369): Registering notifier observer 'fulltext_sa' for [sync]

**Comment by windingwind** [comment]
谢谢反馈，请升级最新版本插件

**Comment by litaihe** [comment]
这个问题我测试了一下，目前没有再遇到无法启动的问题，谢谢您
