### ISSUE TITLE
[Feature] 建议增加一个【中转二次翻译】

### ISSUE THREAD

**Issue by moraduke** [windingwind/zotero-pdf-translate#94]
我先解释一下哈

一个以日语为母语作者写的英文文献，如果直接翻译中文可能翻译不通，但如果先翻译成日语，日语再翻译中文，则可能非常通顺。
以此类推。

当然这是一小部分人的想法，作者可以考虑增加一个选项，勾选以后开启【中转二次翻译】，实现上述功能。

**Comment by windingwind** [comment]
Never heard of that. I don't see the necessity. 
It should be rather a writing issue with the paper author, or a reading issue with the paper reader.
