### ISSUE TITLE
[Feature] 希望能够加上某些字符不翻译的选项，例如中英文括号，逗号啥的，参考Readpaper

### ISSUE THREAD

**Issue by liu-guo-jing** [windingwind/zotero-pdf-translate#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS:  window11
- Zotero Version:  7.0.0
- Plugin Version: Translation

### Describe the feature request

![image](https://github.com/user-attachments/assets/2c92b169-8db9-409b-be44-20ef79875620)
如图，中英文括号，逗号，分号，句号，希腊字母，等等，能否做一个过滤选项，类似readpaper。
![image](https://github.com/user-attachments/assets/0823d05d-9ddb-432e-bcd5-802cb816489d)

**Comment by windingwind** [comment]
可使用支持术语库的翻译服务，自行配置
