### ISSUE TITLE
[bug]无法跨页翻译

### ISSUE THREAD

**Issue by Anapp1ee** [windingwind/zotero-pdf-translate#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 15.0
- Zotero Version: 7.0.6-Beta.2
- Plugin Version: 2.0.1

### Describe the bug

无法跨页翻译,比如我翻译论文，连续选中超过三页，插件只能翻译一页或两页就停止了，之前有过一段时间是正常的

### Debug Output

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]

[JavaScript Error: "WebSocket connection closed: 1006 "]

appName => Zotero, version => 7.0.6-beta.2+b4239fd4c (ARM64), os => macOS 15.0, locale => zh-CN, extensions => Translate for Zotero (2.0.1, extension), Jasminum (1.0.0-16, extension, disabled), Zotero Reading List (1.3.4, extension, disabled), Chartero (2.9.5, extension, disabled), Better Notes for Zotero (2.0.8, extension, disabled), Ethereal Reference (1.1.2, extension, disabled), Actions and Tags for Zotero (2.0.2, extension, disabled)

**Comment by zcwang1027** [comment]
同样的问题，没办法跨页翻译了现在，希望能尽快修复

**Comment by windingwind** [comment]
不要一次选很多
