### ISSUE TITLE
[Bug]翻译标题后，许多文献标题会不可见，点击后才会出现但是文献排序变乱

### ISSUE THREAD

**Issue by Liwt0** [windingwind/zotero-pdf-translate#95]
**Describe the bug**
![image](https://user-images.githubusercontent.com/90240641/163903248-fdad964f-4bbd-4ffc-b5d6-a35f75d09c5e.png)
右键翻译标题后，许多文献标题不可见了，并且出现其他符号
![image](https://user-images.githubusercontent.com/90240641/163903527-20ae786a-9867-4a46-b2aa-aebd59d8c9ec.png)

**To Reproduce**
1. 右键文献，标题翻译
2. 多个文献标题消失，再次点击才会出现，同时文献排序会变化

**Expected behavior**
不影响其他文献

**Screenshots**
![image](https://user-images.githubusercontent.com/90240641/163903728-a659ef61-9fab-490a-935e-dc1b7784e1db.png)
![image](https://user-images.githubusercontent.com/90240641/163903753-0ed95dbe-8686-42bc-8fcb-fb4073a7284b.png)

**Environment**
 - OS: Windows
 - Zotero Version：6.0.4
 - Addon Version：0.6.2

**Comment by Liwt0** [comment]
其他文献标题也会变乱
![image](https://user-images.githubusercontent.com/90240641/163904152-562589cd-b415-4ec1-867d-a777025b4f82.png)

**Comment by windingwind** [comment]
try v0.6.4
