### ISSUE TITLE
[Bug] 微软翻译调用错误，微软翻译已经更新api接口

### ISSUE THREAD

**Issue by Arcolaus** [windingwind/zotero-pdf-translate#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS Sequoia 15.0
- Zotero Version: Zotero 7.0
- Plugin Version: 2.0.1

### Describe the bug

根据[微软翻译官方文档](https://learn.microsoft.com/en-us/azure/ai-services/Translator/quickstart-text-rest-api?tabs=csharp#headers)，其api调用方法对比与插件的调用方法已改变。

我查看过插件repo的[相关代码](https://github.com/windingwind/zotero-pdf-translate/blob/main/src/modules/services/microsoft.ts)
需要做的改动应该并不多。很抱歉我并不会TS，无法及时pr，只能提出该issue，还麻烦开发者同学能够及时修复

### Debug Output

[请求错误]
此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： 微软🗝️

Error: HTTP POST https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=zh-CN failed with status code 401

**Comment by windingwind** [comment]
未发现接口有变化。

**Comment by Arcolaus** [comment]
> 未发现接口有变化。

开发者您好，根据我查看项目提供的[文档](https://zotero.yuque.com/staff-gkhviy/pdf-trans/cim8zn#XZqdN)以及相关代码`src/modules/services/microsoft.ts`，
```ts
  const params = data.secret.split("#");
  const secretKey = params[0];
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "Ocp-Apim-Subscription-Key": secretKey,
  };
  // Sometimes the MicroSoft translator service need a region parameter.
  // The region string is in lower case without space inside. East Asia -> eastasia
  if (params[1]) {
    const region = params[1].replace(" ", "").toLowerCase();
    if (params[1] != "global") headers["Ocp-Apim-Subscription-Region"] = region;
  }
```
我出现此问题的原因是文档中未指明**在创建翻译服务时，如果地区未选择为`global`**，在插件中不光需要填写密钥，还需要增加`#${region}`字段，请问是否可以更新一下文档。

**Comment by cjjcn** [comment]
> > 未发现接口有变化。
> 
> 开发者您好，根据我查看项目提供的[文档](https://zotero.yuque.com/staff-gkhviy/pdf-trans/cim8zn#XZqdN)以及相关代码`src/modules/services/microsoft.ts`，
> 
>   const params = data.secret.split("#");
>   const secretKey = params[0];
>   const headers: Record<string, string> = {
>     "Content-Type": "application/json",
>     "Ocp-Apim-Subscription-Key": secretKey,
>   };
>   // Sometimes the MicroSoft translator service need a region parameter.
>   // The region string is in lower case without space inside. East Asia -> eastasia
>   if (params[1]) {
>     const region = params[1].replace(" ", "").toLowerCase();
>     if (params[1] != "global") headers["Ocp-Apim-Subscription-Region"] = region;
>   }
> 我出现此问题的原因是文档中未指明**在创建翻译服务时，如果地区未选择为`global`**，在插件中不光需要填写密钥，还需要增加`#${region}`字段，请问是否可以更新一下文档。

This is indeed the problem. If no modification is made here, perhaps the author could consider prompting users in the document to select the service region as `global` when creating a new translation service, which can then avoid this issue.
