### ISSUE TITLE
[Bug] in the latest version，The bug of increasing the width by clicking on the pop - up window has not been resolved.

### ISSUE THREAD

**Issue by goodai2** [windingwind/zotero-pdf-translate#951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: window 11 24H2
- Zotero Version: 7.0.0
- Plugin Version:2.0.1

### Describe the bug

in the latest version，The bug of increasing the width by clicking on the pop - up window has not been resolved.

### Debug Output

in the latest version，The bug of increasing the width by clicking on the pop - up window has not been resolved.

**Comment by windingwind** [comment]
I don't see this bug anymore. Closed
