### ISSUE TITLE
[Bug]关闭“启用弹窗”后无法翻译

### ISSUE THREAD

**Issue by Mister-jiao** [windingwind/zotero-pdf-translate#96]
**Describe the bug**
您好，我遇到的问题是:关闭“启用弹窗”后无法翻译。

**To Reproduce**
1. 当选择首选项中的“启用弹窗”时，一切正常
![image](https://user-images.githubusercontent.com/65880243/163913556-2b028111-4cb3-446f-b94f-574bef90d079.png)
![image](https://user-images.githubusercontent.com/65880243/163913501-d10db657-de5c-4363-a63c-49a9a6fa38be.png)
2. 当关闭首选项中的“启用弹窗”时，无法进行翻译（包括点击translate按钮）
![image](https://user-images.githubusercontent.com/65880243/163913702-f4c025a0-a07b-4c64-9512-ebc71c32245a.png)
![image](https://user-images.githubusercontent.com/65880243/163913843-42cc2ce5-c89e-46e9-a17d-10c832717ba5.png)

**Expected behavior**
希望予以解决

**Environment**
 - OS: Windows
 - Zotero 6.0.4
 - Addon 0.6.2

**Comment by windingwind** [comment]
Fixed in v0.6.3
