### ISSUE TITLE
[Bug] 单词可以翻译，但句子翻译不出来

### ISSUE THREAD

**Issue by tietie-lab** [windingwind/zotero-pdf-translate#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

总是提醒“请求错误！此翻译引擎不可用，可能是密钥错误，也可能是请求过快。请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起”我已经换过好几个品牌的秘钥了

### Debug Output

总是提醒“请求错误！此翻译引擎不可用，可能是密钥错误，也可能是请求过快。请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起”我已经换过好几个品牌的秘钥了

**Comment by windingwind** [comment]
请查阅文档，按格式填写相关信息
