### ISSUE TITLE
[Bug] 划词翻译或鼠标焦点位于弹窗时弹窗出现灰色残影

### ISSUE THREAD

**Issue by 27E6** [windingwind/zotero-pdf-translate#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.5 (64-bit)
- Plugin Version:2.0.1

### Describe the bug

划词翻译或鼠标焦点位于弹窗时弹窗出现灰色残影

![屏幕截图 2024-10-02 105843](https://github.com/user-attachments/assets/e5ee3b09-4350-4ae0-9dd8-d9804d7f3c24)
![屏幕截图 2024-10-02 105858](https://github.com/user-attachments/assets/467779a2-05af-44db-95f3-69ce1d9210bc)
![屏幕截图 2024-10-02 105940](https://github.com/user-attachments/assets/d03913c2-011d-4795-bbe1-78ff26494047)

### Debug Output

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

appName => Zotero, version => 7.0.5 (x64), os => Windows 10.0 19045, locale => zh-CN, extensions => Translate for Zotero (2.0.1, extension), Better Notes for Zotero (2.0.8, extension, disabled), Jasminum (1.0.0-17, extension, disabled), Ethereal Reference (1.1.1, extension, disabled), Awesome GPT (1.2.6, extension, disabled), Ethereal Style (5.0.7, extension, disabled), Linter for Zotero (1.19.0, extension, disabled)

(3)(+0016265): [Translate for Zotero] runTranslationTask {}

(3)(+0000001): [Translate for Zotero] try itemLanguage en

(3)(+0000000): [Translate for Zotero] use autoDetect en

(3)(+0000002): [Translate for Zotero] try auto detect language

(3)(+0000000): [Translate for Zotero] try itemLanguage en

(3)(+0000000): [Translate for Zotero] use autoDetect en

(3)(+0000000): [Translate for Zotero] {"id":"cvudCH7v-1727838167212","type":"text","raw":"The network has learned a variety of frequency- and orientation-selective kernels, as well as various colored blobs.","result":"","audio":[],"service":"cnki","candidateServices":[],"itemId":308,"status":"processing","extraTasks":[],"langfrom":"en","langto":"zh-CN","callerID":"zoteropdftranslate@euclpts.com","secret":""}

(3)(+0000011): HTTP POST "{"words":"-Pi4aoIdbM4zLWjoKnE_PmEra9C9mMi-AbK5BovYxUbDREcQOZW9efSoFIywhPhJwkSpsarzQAj1EFCn9iWnABZ9LZv5BeA2pSCU_rGvxkYek_i3szkWwxj0ITVec2ZjAX_nzWhm8saPQP7fJuMf_KFHiJif7jvLaPJCbrveBLI=","translateType":null}" to https://dict.cnki.net/fyzs-front-api/translate/literaltranslation

(3)(+0000208): HTTP POST https://dict.cnki.net/fyzs-front-api/translate/literaltranslation succeeded with 200

**Comment by windingwind** [comment]
I don't see this anymore. Closed
