### ISSUE TITLE
[Bug] Why can't the translated Chinese title overlay the original English title as zotero6 does

### ISSUE THREAD

**Issue by Lishiquan12** [windingwind/zotero-pdf-translate#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0
- Plugin Version:1.0.0

### Describe the bug

 Why can't the translated Chinese title overlay the original English title as zotero6 does

### Debug Output

 Why can't the translated Chinese title overlay the original English title as zotero6 does

### Anything else?

 Why can't the translated Chinese title overlay the original English title as zotero6 does

**Comment by Nobll** [comment]
同问，蹲答复

**Comment by windingwind** [comment]
请使用单独的标题翻译列。

另发言请注意礼貌用语
