### ISSUE TITLE
[Bug]15001：翻译异常请联系客服

### ISSUE THREAD

**Issue by L-Inkink** [windingwind/zotero-pdf-translate#97]
**Describe the bug**
你好，我用Niu(trial)引擎翻译英文文献语句时出现15001报错

**To Reproduce**
1. 先打开一篇英文文献
2. 选择要翻译的英文语句
3. 选择Niu(trial)引擎并点击Translate

**Expected behavior**
翻译出中文语句

**Screenshots**
![Snipaste_2022-04-19_11-41-02](https://user-images.githubusercontent.com/51713323/163915807-dc0a05a8-e016-480c-a5cc-5c7b4543bdac.png)

**Environment**
 - OS: Windows
 - Zotero Version：6.0.4
 - Addon Version：0.6.2

**Additional context**
之前使用没有任何问题，今天突然出现

**Comment by windingwind** [comment]
see #6

**Comment by windingwind** [comment]
trail is for trail use only. no guarantees.

**Comment by L-Inkink** [comment]
> see #6

谢谢！
