### ISSUE TITLE
翻译接管原文对笔记的影响。

### ISSUE THREAD

**Issue by baileichao** [windingwind/zotero-pdf-translate#970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: windows 11 23H2
- Zotero Version: 7.0.7
- Plugin Version:2.0.3

### Describe the feature request

目前的翻译功能，貌似是把英文文献的原文接管了？例如我选择一段文字，点击弹窗的自带添加到笔记功能，添加到笔记条目的是英文原文，但是我先点击翻译插件的添加笔记按钮，添加到笔记条目的是翻译过的中文内容，这个时候，我如果再点击自带的添加笔记按钮，则添加到笔记条目的就是中文内容，而不是原来的英文原文了。这个感觉是如果用翻译插件翻译过一次，就把原文接管了，即使我再用自带的添加笔记功能，添加的也是翻译后的内容。
这个有一个问题，导致和隔壁的插件有点冲突，例如隔壁的zotero one插件的生词本功能，点击生词高亮批注后，本来是：生词+解译，但是貌似翻译插件把生词自动翻译了，结果高亮的生词就是：解译+解译，结果不对。
当然，这只是举例说明一个冲突。像上面的笔记功能，如果有时候不想翻译，但是又选择了那句话，实际上是翻译了的，导致笔记就是翻译后的结果了，而不是原文。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
> 目前的翻译功能，貌似是把英文文献的原文接管了？

不存在接管

> 例如我选择一段文字，点击弹窗的自带添加到笔记功能，添加到笔记条目的是英文原文，但是我先点击翻译插件的添加笔记按钮，添加到笔记条目的是翻译过的中文内容，

正常行为

> 这个时候，我如果再点击自带的添加笔记按钮，则添加到笔记条目的就是中文内容，而不是原来的英文原文了。这个感觉是如果用翻译插件翻译过一次，就把原文接管了，即使我再用自带的添加笔记功能，添加的也是翻译后的内容。

没有这种情况。如果认为可以稳定复现该问题，请上传录屏

> 这个有一个问题，导致和隔壁的插件有点冲突，例如隔壁的zotero one插件的生词本功能，点击生词高亮批注后，本来是：生词+解译，但是貌似翻译插件把生词自动翻译了，结果高亮的生词就是：解译+解译，结果不对。

本插件不干涉其他插件，其他插件的bug请向对应插件作者反馈

> 当然，这只是举例说明一个冲突。像上面的笔记功能，如果有时候不想翻译，但是又选择了那句话，实际上是翻译了的，导致笔记就是翻译后的结果了，而不是原文。

关闭批注自动翻译即可
