### ISSUE TITLE
[Bug] translate突然无法翻译，Google，CNKI,有道

### ISSUE THREAD

**Issue by sherry202209** [windingwind/zotero-pdf-translate#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 7.0.0
- Plugin Version:

### Describe the bug

translate突然无法翻译，Google，CNKI,有道
[请求错误]
此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： Google

Error: HTTP GET 
anslate.google.com/translate_a/single?client=gtx&sl=en&tl=zh&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&source=bh&ssel=0&tsel=0&kc=1&tk=707980.850424&q=The%20majority%20of%20theory%20and%20research%20on%20empowering%20leadership%20to%20date%20has%20focused%20on%20how%20empowering%20leader%20behaviors%20influence%20employees%2C%20portraying%20those%20behaviors%20as%20almost%20exclusively%20beneficial.%20We%20depart%20from%20this%20predominant%20consensus%20to%20focus%20on%20the%20potential%20detriments%20of%20empowering%20leadership%20for%20employees.%20Drawing%20from%20the%20social%20cognitive%20theory%20of%20morality%2C%20we%20propose%20that%20empowering%20leadership%20can%20unintentionally%20increase%20employees%E2%80%99%20unethical%20pro-organizational%20behavior%20(UPB)%2C%20and%20that%20it%20does%20so%20by%20increasing%20their%20levels%20of%20moral%20disengagement.%20Specifically%2C%20we%20propose%20that%20hindrance%20stressors%20create%20a%20reversing%20effect%2C%20such%20that%20empowering%20leadership%20increases%20(vs.%20decreases)%20moral%20disengagement%20when%20hindrance%20stressors%20are%20higher%20(vs.%20lower).%20Ultimately%2C%20we%20argue%20for%20a%20positive%20or%20negative%20indirect%20effect%20of%20empowering%20leadership%20on%20UPB%20through%20moral%20disengagement.%20We%20find%20support%20for%20our%20predictions%20in%20both%20a%20time-lagged%20field%20study%20(Study%201)%20and%20a%20scenario-based%20experiment%20using%20an%20anagram%20cheating%20task%20(Study%202).%20We%20thus%20highlight%20the%20impact%20that%20empowering%20leadership%20can%20have%20on%20unethical%20behavior%2C%20providing%20answers%20to%20both%20why%20and%20when%20the%20dark%20side%20of%20empowering%20leadership%20behavior%20occurs failed with status code 429

### Debug Output

.d

**Comment by chenyv118** [comment]
我也是今天突然出现了这个情况，不知道是为什么

**Comment by sherry202209** [comment]
> 我也是今天突然出现了这个情况，不知道是为什么

我今天谷歌可以用了，有道还是不行

**Comment by karaner** [comment]
我谷歌也不用了

**Comment by Hurricane00** [comment]
我截止10.13还可以，10.14早上突然挂掉了

**Comment by verfassunghuang** [comment]
![image](https://github.com/user-attachments/assets/0fe32019-2cfc-4278-a4b3-187b828e52d1)
使用Gemini api翻译，然后无法弹出完整的翻译内容

**Comment by windingwind** [comment]
无需密钥的翻译服务，如各种文档、错误提示等所说的，不保证可用性。

对使用密钥的翻译服务，如有问题请单独开帖。

由于此帖回复被滥用，关闭且锁定
