### ISSUE TITLE
[Bug] zotero 6.0.37安装zotero translate 最新插件安装不了

### ISSUE THREAD

**Issue by kuki-xie** [windingwind/zotero-pdf-translate#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macos 15.0.1
- Zotero Version:  6.0.37
- Plugin Version: 2.0.3

### Describe the bug

6.0.37 zotero， latest zotero translate: 安装失败：无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容

### Debug Output

version => 6.0.37, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => zh-CN, appName => Zotero, appVersion => 6.0.37, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.37, extension, disabled), Zotero Word for Mac Integration (6.0.10.SA.6.0.37, extension, disabled), ZotFile (5.1.2, extension, disabled)

(3)(+0030432): Starting full-text content processor

**Comment by windingwind** [comment]
升级zotero
