### ISSUE TITLE
[Feature] 希望增加离线翻译功能

### ISSUE THREAD

**Issue by loverchun** [windingwind/zotero-pdf-translate#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.0.7
- Plugin Version: 2.0.3

### Describe the feature request

由于保密需要，教研室的电脑不能连接网络，只能连接内网，因此我的翻译插件在电脑上是不能翻译的，我希望能增加离线翻译的设置模块，这样我可以下载离线翻译包，在电脑上使用该插件。

### Describe the solution you'd like

离线翻译功能的设置类似于百度或有道翻译等。

**Comment by windingwind** [comment]
是否有推荐的离线可用并提供接口的翻译软件

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
