### ISSUE TITLE
[Bug]翻译引擎切换无法自动或者手动再次翻译

### ISSUE THREAD

**Issue by sheshen22** [windingwind/zotero-pdf-translate#98]
腾讯翻译后选择小牛翻译，翻译界面完全没有反应。

![image](https://user-images.githubusercontent.com/104003939/163996336-d294f13f-16aa-4c3d-adb5-c3a25796244f.png)
![image](https://user-images.githubusercontent.com/104003939/163996475-9a04d319-6257-4dec-8cde-4004b9a0ac09.png)

下面是小牛真实的翻译。

![image](https://user-images.githubusercontent.com/104003939/163997459-39055eb6-b94d-4634-941f-5e21b88e46f4.png)

切换翻译引擎后，无法自动翻译或手动按Translate进行翻译。

之前的0.48版本没有这个问题。我不知道是确实存在这个问题，还是因为和其他插件发生了冲突

期待您的帮助！谢谢！

**Environment**
 - OS: Windows
 - Zotero Version(6.04)
 - Addon Version(0.64)

**Comment by windingwind** [comment]
fixed in v0.6.5

**Comment by sheshen22** [comment]
谢谢。目前0.66版本可以切换引擎后，手动按Translate翻译。但仍存在切换翻译引擎后无法自动翻译的问题。

**Comment by sheshen22** [comment]
> fixed in v0.6.5
谢谢。目前0.66版本可以切换引擎后，手动按Translate翻译。但仍存在切换翻译引擎后无法自动翻译的问题。

**Comment by windingwind** [comment]
> > fixed in v0.6.5
> > 谢谢。目前0.66版本可以切换引擎后，手动按Translate翻译。但仍存在切换翻译引擎后无法自动翻译的问题。

是的，这是从0.6.0版本开始的新行为。考虑到大多数情况下不需要重新翻译已有的内容，只有手动点击按钮会重新翻译。
