### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by verfassunghuang** [windingwind/zotero-pdf-translate#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: WIN11 24H2 (ARM VERSION)
- Zotero Version:  7.0.8
- Plugin Version: 2.0.4

### Describe the bug

最近几个版本开始出现Gemini API选定被翻译内容之后无法完整展现翻译内容的问题。升级到2.0.4之后，本问题没有解决.而且在重新填入 Gemini API key，Gemini Api翻译彻底不可用，报错内容如下：{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "generativelanguage.googleapis.com"
        }
      }
    ]
  }
}

本人在沉浸式翻译插件内用了相同的key，能正常使用

### Debug Output

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yTextualAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yTextualAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yAnnotationInstruction"." {file: "reader.ftl" line: 0}]

1729475507394	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yTextualAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yTextualAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yTextualAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yTextualAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "Attempt to override an existing message: "pdfReader-a11yAnnotationInstruction"." {file: "reader.ftl" line: 0}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "TypeError: JSON.parse(...).candidates is undefined" {file: "jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 4156}]
src/modules/services/gemini.ts/geminiTranslate/requestObserver/xmlhttp.onprogress@jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js:4156:36

[JavaScript Error: "TypeError: JSON.parse(...).candidates is undefined" {file: "jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 4156}]
src/modules/services/gemini.ts/geminiTranslate/requestObserver/xmlhttp.onprogress@jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js:4156:36

[JavaScript Error: "TypeError: JSON.parse(...).candidates is undefined" {file: "jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 4156}]
src/modules/services/gemini.ts/geminiTranslate/requestObserver/xmlhttp.onprogress@jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js:4156:36

[JavaScript Error: "TypeError: JSON.parse(...).candidates is undefined" {file: "jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 4156}]
src/modules/services/gemini.ts/geminiTranslate/requestObserver/xmlhttp.onprogress@jar:file:///C:/Users/ascen/AppData/Roaming/Zotero/Zotero/Profiles/frjnvuxa.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js:4156:36

appName => Zotero, version => 7.0.8 (ARM64), os => Windows 11 26120, locale => zh-CN, extensions => Wandering File (0.2.8, extension), Jasminum (1.0.0-16, extension), ZotCard (3.0.11, extension), Zotero OCR (0.8.1, extension), Easier Citation (0.4.6, extension), 蒲公英 (1.0.6, extension), Zotero 插件市场 (1.7.2, extension), Ethereal Style (5.1.5, extension), Better Notes for Zotero (2.0.17, extension), Translate for Zotero (2.0.4, extension)

### Anything else?

[a.pdf](https://github.com/user-attachments/files/17453069/a.pdf)

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
