### ISSUE TITLE
[Feature] 长段翻译的翻译框看不全！

### ISSUE THREAD

**Issue by cutebird00** [windingwind/zotero-pdf-translate#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

![图片](https://github.com/user-attachments/assets/fbee5197-d468-4292-ab1b-b03bd498f9b3)
请看，如果用长段翻译，看不全内容啊好痛苦，右边划不过去了。
而且就算能看全，太长的翻译上下滚动时候总在移动！
还有如果部分选择翻译框内的内容，再点击一下会自动复制，然后翻译框变宽一点，字布局会改变，也很痛苦。
怎么没有zotero6的用着顺手啊啊啊啊

### Describe the solution you'd like

如果可以让pdf左右滑动就好了。。能让我看到没显示全的翻译框。
然后翻译框翻译出来之后能不能固定住，直到我点击翻译框外的区域，不根据文档滑动改变位置。
最后如果部分选择翻译框内内容翻译框不会自动变宽就更好了。。谢谢老板！

**Comment by MUTED64** [comment]
![image](https://github.com/user-attachments/assets/29baf193-9dc7-4295-88e6-a99f3256fe6d)

可以勾上这个选项后自行选择框体大小，超出的部分上下滚动框内的翻译就可以

**Comment by cutebird00** [comment]
> ![image](https://private-user-images.githubusercontent.com/50164562/378853867-29baf193-9dc7-4295-88e6-a99f3256fe6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTkyMDAsIm5iZiI6MTcyOTc1ODkwMCwicGF0aCI6Ii81MDE2NDU2Mi8zNzg4NTM4NjctMjliYWYxOTMtOWRjNy00Mjk1LTg4ZTYtYTk5ZjMyNTZmZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4MzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MjZlMjIwYjM5YWY0MDk1YmRhZjI3MWEyOTk2ZjM3OGUxYTY1ZmQxOGJkMmFhMGNmMzE4NWE0MGY0N2Y0NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PBLn40GfKcIVbWSgADGwVbJDKGCc0eLSfs7N-7p3UgM)
> 
> 可以勾上这个选项后自行选择框体大小，超出的部分上下滚动框内的翻译就可以

谢谢你亲爱的朋友，部分解决了我的问题，但用起来还是不如原来方便（哭）。我主要还是想说长翻译翻译框会为了避免遮挡原文内容扩展到pdf页面范围外，但pdf范围外我又没办法划过去（zotero 6可以），这很难受。希望能改进一下，能划到pdf页面左右范围之外就好了！

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by windingwind** [comment]
弹窗仅为快速预览翻译内容，要查看完整内容建议在侧边栏或单独窗口查看
