### ISSUE TITLE
Erro 400 密钥正确，网络顺畅，但是deepl引擎无法使用

### ISSUE THREAD

**Issue by LEXPERIA128** [windingwind/zotero-pdf-translate#986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  win11 23H2
- Zotero Version: 7.0.9.0
- Plugin Version:2.0.4

### Describe the bug

输入deepl免费密钥之后，出现如图错误
![屏幕截图 2024-10-23 010845](https://github.com/user-attachments/assets/604a278f-17ca-4276-a29a-7d13d7bcdf5f)

### Debug Output

无

**Comment by windingwind** [comment]
请截图deepl订阅界面

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by windingwind** [comment]
请截图deepl订阅界面

**Comment by nauyyl** [comment]
<img width="438" alt="Image" src="https://github.com/user-attachments/assets/e68be729-54c9-4228-a7bb-35b6ebc0f14a" />

**Comment by nauyyl** [comment]
<img width="619" alt="Image" src="https://github.com/user-attachments/assets/b8c04ea2-33a6-48be-b9de-22a727e1999b" />
