### ISSUE TITLE
[Bug] HTTP GET failed with status code 403  youdaozhiyun

### ISSUE THREAD

**Issue by GrizzlyCcc** [windingwind/zotero-pdf-translate#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11
- Zotero Version: 7
- Plugin Version: 2.0.5

### Describe the bug

在多次重新配置有道智云api key并且重置密钥操作只有，仍然无法使用。
![zotero_73b1U4NF1x](https://github.com/user-attachments/assets/018f07bf-10d3-44d7-a063-aefa5a7e2487)

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/17494558/Debug.Output.txt)

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
