### ISSUE TITLE
[Bug] 部分pdf无法划选，但是可以ctrl F搜索，有人遇到这种问题吗

### ISSUE THREAD

**Issue by Yafeia** [windingwind/zotero-pdf-translate#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

部分pdf无法划选，但是可以ctrl F搜索，其他pdf可以正常划选

### Debug Output

nothing here

**Comment by windingwind** [comment]
与pdf格式有关，与插件无关，故此关闭

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
