### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by QAbot-zh** [windingwind/zotero-pdf-translate#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version:  7.0.0
- Plugin Version:  2.0.5

### Describe the feature request

复制多段文本时似乎会自动把段落换行去掉，导致翻译结果混在一起，影响阅读。

示例图1：
![image](https://github.com/user-attachments/assets/d9608b2d-0588-452b-9f48-5611280fad4b)

示例图2：
![image](https://github.com/user-attachments/assets/e1e4ce50-f02e-460e-a1d8-f577fc2e4ef2)

### Describe the solution you'd like

尽量保留复制文本的格式，避免翻译文本产生段落混淆问题

**Comment by windingwind** [comment]
与pdf本身格式有关，与插件无关。故此关闭
