### ISSUE TITLE
请求：同时显示多个引擎的翻译结果

### ISSUE THREAD

**Issue by fredericky123** [windingwind/zotero-pdf-translate#99]
感谢付出！
请问能增加显示多个引擎的翻译结果，类似于这样，来回切换各个引擎的结果不是很方便，想一次性看常用的四个，进行比较
感谢！
![image](https://user-images.githubusercontent.com/13982749/164179787-bcca0a52-74b3-4cd9-868d-b6d82f6892b9.png)

![image](https://user-images.githubusercontent.com/13982749/164181581-c638a88c-e1f9-455f-a084-bb91a155aee1.png)
在上图中的英文原文字，右边的框感觉可以缩小，毕竟在pdf里已经有了，可省略显示

**Comment by fredericky123** [comment]
刚刚注意到英文可折叠！赞

**Comment by windingwind** [comment]
可以在设置里面调整需要显示的右侧栏内容，可以隐藏原文区域；
对于多引擎翻译结果，技术上并不复杂，主要问题是：
1. 消耗多倍翻译字符容量；
2. 显示区域不好布置，容易显得乱；
3. 不确定是否是大众的需求。如果所有提的功能都做，插件会变得臃肿且过于复杂。

有什么建议吗？

**Comment by fredericky123** [comment]
是的，我隐藏了原文区域
1.建议大家都配置私人密钥，可以缓解服务器压力吧
2.布局的话可以在设置里设置引擎个数，如果为1个的话，就现在的布局，如果4个的话，翻译区域可以等分为4个，我在外接显示器上用zotero，还是有很大的空间显示翻译内容的
语言的设置可以最上面，用于所有引擎，之后是引擎名1，翻译内容1，引擎名2，翻译内容2
![image](https://user-images.githubusercontent.com/13982749/164216519-b272f9d8-a992-4ccc-9c77-1d17b3fe14f4.png)

**Comment by windingwind** [comment]
@fredericky123 可以设置同时翻译，减少等待时间，如果确实需要；但可能增加翻译量的消耗。

**Comment by fredericky123** [comment]
那也行！自己手动快速切换，避免等待，翻译量倒不担心，我配置了密钥

**Comment by fredericky123** [comment]
> @fredericky123 或者通过快捷键在新窗口预览所有多个翻译引擎的结果，与快捷键切换方案你觉得哪个更好一些？ 另外快捷键有没有什么建议，现在的翻译快捷键是ctrl+T

这个更好！
option command t? 这个在mac上按着比较方便

**Comment by lusccc** [comment]
> 可以在设置里面调整需要显示的右侧栏内容，可以隐藏原文区域； 对于多引擎翻译结果，技术上并不复杂，主要问题是：
> 
> 1. 消耗多倍翻译字符容量；
> 2. 显示区域不好布置，容易显得乱；
> 3. 不确定是否是大众的需求。如果所有提的功能都做，插件会变得臃肿且过于复杂。
> 
> 有什么建议吗？

你好。可以参考一下utools里的聚合翻译功能，直接聚合多个翻译的网页，避免用户自己配置接口：
![image](https://user-images.githubusercontent.com/8512970/164887916-0206504d-5336-4571-a2af-0bf74e646c61.png)

**Comment by windingwind** [comment]
@fredericky123 try v0.7.0

**Comment by windingwind** [comment]
@lusccc 虽然与本issue话题无关，还是感谢你的建议。
嵌入网页会造成UI问题，界面混乱，并且不方便获取翻译结果。API是可靠标准的调用方式，其他方式都有被停止服务的风险。
如果你是轻度使用，不需要密钥的几个翻译引擎足够用了；重度使用应当配置API密钥。
