### ISSUE TITLE
[Bug] I'm getting Portuguese (Portugal) instead of Portuguese (Brazil)

### ISSUE THREAD

**Issue by lbarrios1** [windingwind/zotero-pdf-translate#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 Home
- Zotero Version: 7.0.9 (64-bit)
- Plugin Version: 2.0.5

### Describe the bug

I'm getting as the result of the translation Portuguese (Portugal), instead of Portuguese (Brazil).

### Debug Output

...

**Comment by lbarrios1** [comment]
Already trying switching translation engines, already reinstalled the plugin. I think it's a bug...

**Comment by windingwind** [comment]
Please report the issue with required information.
