### ISSUE TITLE
[Feature] 将annotation同步为anki 抽认卡【求路人顶一下此需求】

### ISSUE THREAD

**Issue by hermanzhaozzzz** [windingwind/zotero-pdf-translate#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
其实翻译插件的背后是，我不认识某单词，某词组，而anki是用来进行单词和词组记忆的好工具，如果本插件能够提供一个选项，【将所选翻译同步至anki某默认卡组】将会提升我使用本插件的体验。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**
目前已有一个比较繁琐的操作方式 

https://github.com/MengqiangH/zotero-annotations-to-anki

但是这本身可以是一键式完整的工作，如果能串起来用户体验会很好

**Comment by hermanzhaozzzz** [comment]
@ MengqiangH

**Comment by windingwind** [comment]
与本插件无关
