### ISSUE TITLE
[enhancement]  The icon added is too large

### ISSUE THREAD

**Issue by Tariya321** [windingwind/zotero-pdf-translate#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Window 10 22H2
- Zotero Version: 7.0.9
- Plugin Version: 1.2.7

### Describe the bug

![image](https://github.com/user-attachments/assets/50049e5e-d37d-4463-8d47-f1e1c4c50f75)
Here is the problem: while using auto-translation & note, it will add an icon to the top-left corner of this item(as indicated by the arrow), and it may impacts the reading experience.

So, do we have way to approve this(like scaling down the size)? 

### Debug Output

No output need.

**Comment by Tariya321** [comment]
sry, this should be moved to [feature]. OVO

**Comment by windingwind** [comment]
Not related to plugin. Please report to the Zotero forums
